### ISSUE TITLE
Number-type query parameter range validation

### ISSUE THREAD

**Issue by jasminas** [OAI/OpenAPI-Specification#1000]
Hello,

following the posts from #191, I am trying to validate a query parameter against some provided limits. My JSON parameter definition is the following:

`{
     "name": "count",
      "in": "query",
      "type": "number",
      "minimum": 1,
      "maximum": 100
 }`

Isn't there supposed to be a JSON Schema validation message whenever the "count" parameter is outside the bounds, i.e "...?count=111"?

**Comment by webron** [comment]
JSON Schema validation? No JSON Schema has nothing to do with it.

I don't know which tool you're using, but whichever you do it's up to it to perform the validation.

**Comment by jasminas** [comment]
Oh, then maybe I misunderstood. I thought that since JSON Schema definitions are used for describing parameters then there could also be some validation involved.
Let me restate my concern: Is there any way a user can be aware of these limits using swagger-ui?

**Comment by webron** [comment]
JSON Schema is not used for describing parameters, at least not in 2.0 and earlier. 
If you have questions about swagger-ui, please open them on the swagger-ui project.
