### ISSUE TITLE
Change log for v3.0 as an md file

### ISSUE THREAD

**Issue by arno-di-loreto** [OAI/OpenAPI-Specification#1001]
Based on the work I've done on my [OpenAPI Specification Visual Documentation](http://openapi-specification-visual-documentation.apihandyman.io/), I think I could manage to generate a md file containing a change log from version 2.0 (with links to the specifications).

Would that be of interest? If yes where could I put that file in the repo?

**Comment by MikeRalphson** [comment]
Thanks @arno-di-loreto - due to the length of time this has been open, I'm going to close it. I assume the release notes have been sufficient to communicate changes. Your OpenAPI Map is still a tremendous piece of work, and I hope to see a version for OAS 3.1
