### ISSUE TITLE
Extend Open API Specification to Non-REST APIs

### ISSUE THREAD

**Issue by felipecaputo** [OAI/OpenAPI-Specification#1003]
We are building a Message-based API, and I've didn't found any specification framework that supports that kind of services.

Most of what exists in swagger attends us, but we need to specify some other infos, like queue name and possible next queues

**Comment by darrelmiller** [comment]
You can add custom properties to many objects in your OpenAPI definition.  Just prefix the properties with `x-` and standard tooling will ignore those properties.

**Comment by felipecaputo** [comment]
Sorry for taking too long.. I'll do it, thanks!
