### ISSUE TITLE
href in link object a URI?

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#1010]
looking at https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#link-object i am wondering if it is correct that `href` is described as a URI. isn't it a URI template (using OpenAPI's homegrown URI template language) instead of a URI, and must be resolved against variable assignments at runtime?

**Comment by darrelmiller** [comment]
This is currently being reviewed because we know there are  issues with this design.  I actually don't think it will end up using the template parameters there at all, despite the examples in the spec.  I think all that href needs to be is a string that matches the path item key.  Except for the fact that we want to allow a reference to a path item in another OpenAPI spec.

**Comment by dret** [comment]
On 2017-03-27 18:00, Darrel wrote:
> This is currently being reviewed because we know there are issues with
> this design. I actually don't think it will end up using the template
> parameters there at all, despite the examples in the spec. I think all
> that href needs to be is a string that matches the path item key. Except
> for the fact that we want to allow a reference to a path item in another
> OpenAPI spec.

i don't understand all of this, but feel free to close this issue if the 
design is changing in a way that the href member actually does have a 
URI as its value.

**Comment by darrelmiller** [comment]
There was some confusion when writing the spec as to the purpose of `href`.  Some people understood it to be a way to reference resources that are not described by any OpenAPI specification (aka an external resource) and others thought it was simply an alternative to using OperationId as an identifier of the target operation.  
Once we get the confusion ironed out in RC1 it would be great if you could sanity check us then :-)

**Comment by dret** [comment]
On 2017-03-27 18:08, Darrel wrote:
> There was some confusion when writing the spec as to the purpose of
> |href|. Some people understood it to be a way to reference resources
> that are not described by any OpenAPI specification (aka an external
> resource) and others thought it was simply an alternative to using
> OperationId as an identifier of the target operation.
> Once we get the confusion ironed out in RC1 it would be great if you
> could sanity check us then :-)

i'll happily stop my deciphering attempts now, and would be more that 
review the revised language when it becomes available. thanks for the 
quick feedback!

**Comment by handrews** [comment]
Since this was about a pre-release 3.0 draft and the language was already being changed, I'm going to close it as outdated.
