### ISSUE TITLE
Explicitly prohibit definition of Accept and Content-Type as headers

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#1014]
These two headers are controlled separately, using `content`. It doesn't make sense to allow people to explicitly define those as headers as well. It can lead to confusion, conflicts, and just hell for tools to support.

**Comment by MikeRalphson** [comment]
Is there an argument for extending this to `Authorization` too, as that is handled by `securitySchemes`? Or do we acknowledge that not every scheme which uses an `Authorization` header is covered by the specification?

**Comment by darrelmiller** [comment]
I suggest headers should be ignored rather than prohibited, when a specific OAS mechanism exists as an alternative
