### ISSUE TITLE
Support wildcard header/parameter

### ISSUE THREAD

**Issue by testn** [OAI/OpenAPI-Specification#1017]
Is there already a support to provide a wildcard support? A good example is that certain APIs allow customers to send headers that begin with certain keyword and convert all of them into a map. For example, if you define

`x-openapi-*`

and you send

```
x-openapi-key1: value1
x-openapi-key2: value2
x-openapi-key3: value3
```

then the server can interpret that a customer wants to send

`x-openapi : { "key1": "value1", "key2": "value2", "key3": "value3" }`

**Comment by darrelmiller** [comment]
Personally, I will fight supporting this construct because I think this a very poor way to use HTTP headers.  Key value pairs are a very common construct in HTTP headers and the HTTP standard defines how header folding works in case you want to add them as separate headers.

So APIs should support
```
      x-openapi: key1=value, key2=value, key3=value
```
and
``` 
     x-openapi: key1=value
     x-openapi: key2=value
     x-openapi: key3=value
```
But never different header names for different key values.  That just goes against the idea of having HTTP headers registered in a global registry.

**Comment by testn** [comment]
I agree but it is too bad that many projects that support REST interfaces have this kind of pattern. A good example is OpenStack API: https://docs.oracle.com/en/cloud/iaas/storage-cloud/cssto/setting-container-metadata.html

**Comment by darrelmiller** [comment]
@testn I completely understand.  We have the same stuff in Azure storage https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/set-container-metadata
My fear is if we enable it, people are going to do it more.

**Comment by handrews** [comment]
One strong vote against, and no further discussion since 2017, so I'm closing this as out-of-scope.

**Comment by olizilla** [comment]
Please reconsider! Not supporting it blocks accurately generating an openapi spec for all "S3 compatible" APIs per: https://github.com/APIs-guru/aws2openapi/issues/23#issuecomment-500432790

**Comment by handrews** [comment]
@olizilla if AWS can't update to OAS 3.2 then it's a moot point.  Even if we allowed this, it would be done in 3.0.  If AWS S3 is still stuck stuck on "Swagger" (OAS 2.0), or even OAS 3.0, then they'll never be able to use an enhancement even if we added it.

The most critical thing for AWS is to get up to OAS 3.2 across their product line so they can take advantage of new features in future 3.x releases and have a real migration path to 4.0 whenever we decide a new major release is needed (which is not yet).  We can't go back and fix releases that are a decade+ old release line.  So the best thing to do here is lobby AWS to get up-to-date, and then bring back the use case in a new issue, demonstrating that AWS would be in a position to take advantage of the new feature.  Right now there's just no point- they couldn't use it even if we did it.

**Comment by olizilla** [comment]
Ah, I'm not really talking about AWS here. I'm pointing to the many "S3-compatible" APIs that now exist. I'd like to model them in OAS, but it seems it's not possible. My backstory is here https://github.com/cloud-portable/storage/issues/5
