### ISSUE TITLE
operationId should be a required property

### ISSUE THREAD

**Issue by timburks** [OAI/OpenAPI-Specification#1019]
A recent scan of [apis.guru](https://apis.guru/openapi-directory/) found that 72 of 379 API definitions there contain path objects with no specified **operationId** value. This has a significant negative effect on code generation. While code generators can account for missing **operationId** values by making up a replacement, in practice, those replacements are so ugly that they discourage users from using the generated code. 

One workaround is for code generators to have a side input that specifies **operationId** values, but this seems counter to the goal of using an OpenAPI definition as a definitive reference for an API.

Making **operationId** a required field would resolve this problem. It would also beneficially advocate for API methodologies that use more automation and less handwritten code, which would improve API experiences for everyone.

I don't think that it is necessary to impose any of the requirements discussed in [423](https://github.com/OAI/OpenAPI-Specification/issues/423). Transformations for language compatibility can be left to language-specific code generators.

But any operationId value is better than no value, and the 2.0->3.0 transition is a good opportunity to be opinionated.

**Comment by fehguy** [comment]
I've found that they can be easily, uniquely generated and anyone using code generation will want to explicitly set one.  That said, since tools can behave just fine without them, it seems like requiring an operation id will make intermediate authoring steps tedious

**Comment by ePaul** [comment]
I feel that using operation IDs gives a too big emphasis on the operations. This in effect gives a more RPC-like feel instead of a resource-oriented view like it should be for REST.

**Comment by DavidBiesack** [comment]
On the contrary, I think there is great benefit in operationIds now that OpenAPI support links. It is now possible to describe and present/document an API in terms of HATEOS links and via operationId, you can document that each link relation has a HTTP method, request/response bodies/media types and parameters, and completely hide the URLs. Its not complete runtime decoupling and server-driven HATEOS but it has a lot of potential.

**Comment by whitlockjc** [comment]
The router in `swagger-tools` will use the operation method for whenever the `operationId` is not provided.  It's worked well, although I'm not saying it's not an issue as-is.

**Comment by timburks** [comment]
I think it's appropriate to drop this and leave enforcement of this preference to linters.

Since posting this, I've come to see the OpenAPI Specification as an effort to broadly describe REST APIs and not an effort to create and impose a specific methodology (including tools). However, I think the community *is* confused about this distinction. For example, in issue #892, @darrelmiller and @webron opposed using RFC6570 for path templates because it would impact tooling. I'll follow up there with more discussion of this.
