### ISSUE TITLE
Array type in query does not accept a solitary item

### ISSUE THREAD

**Issue by adamjcsmith** [OAI/OpenAPI-Specification#1020]
In this specification:

```yaml
  /demo:
    x-swagger-router-controller: demoController
    get:
      parameters:
        - name: filter
          in: query
          required: false
          type: array
          items:
            type: integer
          collectionFormat: multi
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DemoResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
```

I defined an array-type query string parameter, `filter`. However, during testing it appears that when a single element is passed a validation error is thrown. Example:

```
http://localhost/demo?filter=10
```

Throws an `INVALID_REQUEST_PARAMETER` error: `Expected type array but found type integer`.

However, adding an additional instance is then accepted:
```
http://localhost/demo?filter=10&filter=20
```

Is this the expected behaviour of an array type? This behaviour is the same regardless whether the `collectionFormat` is csv or multi.

**Comment by ePaul** [comment]
I would say the expected behavior is to accept this as an array with a single element (i.e. `[10]` in JSON).
So what you have is likely a bug with whatever tooling you are using on your server.

Please open an issue in that tooling's project – this repository is for the specification.

**Comment by webron** [comment]
What @ePaul said.

**Comment by adamjcsmith** [comment]
This is a problem with Sway, which you can [see here](https://github.com/apigee-127/sway/pull/114).
