### ISSUE TITLE
GET Request on basePath

### ISSUE THREAD

**Issue by abhilash1in** [OAI/OpenAPI-Specification#1021]
I'm trying to deploy a GET request endpoint on `/` using Google Cloud Endpoints (and using NodeJS on Google App Engine), but the GET endpoint is not recognised as a valid one.

I get the response : 

```
{
 "code": 16,
 "message": "Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "service_control"
  }
 ]
}
```
A part of my openapi.yaml file is :
```
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"
paths:
  "/":
    get:
      description: "Returns the message \"Hello, World\""
      operationId: "rootHello"
      produces:
      - "application/json"
      responses:
        200:
          description: "Hello on /"
          schema:
            $ref: "#/definitions/helloMessage"
definitions:
  helloMessage:
    properties:
      message:
        type: "string"
```

Same functionality on `/hello` or anything like that works fine, but doesn't work only on `/`

Detailed StackOverflow Question [here](http://stackoverflow.com/questions/43097453/google-cloud-endpoints-method-does-not-exist-openapi-yaml-specification)

**Comment by webron** [comment]
This is a question to Google Cloud Endpoints, not here. There's nothing wrong with the spec.

**Comment by abhilash1in** [comment]
With respect to OpenAPI, GET on `/` is not prohibited by any means right?

**Comment by webron** [comment]
Absolutely legal.

**Comment by abhilash1in** [comment]
:+1:
