### ISSUE TITLE
Is application/json is default consumes for POST opertion?

### ISSUE THREAD

**Issue by vijju31198** [OAI/OpenAPI-Specification#1031]
if consumes is not provided at operation or global level, do we need to use application/json as default consumes in case of POST operation? 

In petstore example of POST /store/order consumes is not defined and swagger.io (http://petstore.swagger.io/) uses the default consumer as "application/json". 

is it excepted behavior? if yes nothing is specified in swagger specification about this default value 

```json
"/store/order": {
			"post": {
				"tags": ["store"],
				"summary": "Place an order for a pet",
				"description": "",
				"operationId": "placeOrder",
				"produces": ["application/xml",
				"application/json"],
				"parameters": [{
					"in": "body",
					"name": "body",
					"description": "order placed for purchasing the pet",
					"required": true,
					"schema": {
						"$ref": "#/definitions/Order"
					}
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/Order"
						}
					},
					"400": {
						"description": "Invalid Order"
					}
				}
			}
		},
```

**Comment by whitlockjc** [comment]
An empty `consumes` for an operation is documented as follows: _"An empty value MAY be used to clear the global definition."_  Now, I don't see any documentation in the spec with how an empty global `consumes` is to be handled.  I personally would interpret it as your API doesn't dictate which `Content-Type` headers it supports so anything provided would be acceptable.  We should get @webron involved, he'll know.

**Comment by darrelmiller** [comment]
Luckily in V3 this ambiguous situation will not be possible because you can't define a schema for request or response body without also stating a media type.

**Comment by webron** [comment]
The petstore sample has a few gotchas in it, but regardless, in swagger-ui we send application/json by default if no `consumes` is provided but there's a body payload. This is to try and help users instead of chocking on things like that. It is not, however, the default in the spec.

That said, as @darrelmiller said, thankfully this changes in 3.0 and will no longer be necessary.
