### ISSUE TITLE
use Security Definition to pass Authorization header to all endpoints in swagger-ui

### ISSUE THREAD

**Issue by jb08** [OAI/OpenAPI-Specification#1041]
I'd like to use the _Authorize_ feature to authorize once on swagger-ui, and pass the specific `Authorization` header to all endpoints.

> Security Definitions Object is a declaration of the security schemes available to be used in the specification.

`  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }`

<img width="178" alt="screen shot 2017-04-12 at 5 22 48 pm" src="https://cloud.githubusercontent.com/assets/8146460/24981971/aea82216-1fa4-11e7-9ce4-9c65813592f5.png">

_However, after authorizing on the swagger-ui, when I hit an endpoint, the header is not passed, as viewed in the `Curl`._

**Comment by darrelmiller** [comment]
`securityDefinitions` are just definitions, they don't actually apply the security.  You need to use a `security requirement object` for that.  Add the following to the root of your OpenAPI doc:

```json
"security": [ 
     { "api_key" : [ ] } 
]
```

**Comment by webron** [comment]
Also, this is an issue for swagger-ui and not the spec.
