### ISSUE TITLE
[3.0.0-RC0] upgrade from collectionFormat:tsv in 2.0

### ISSUE THREAD

**Issue by mission-liao** [OAI/OpenAPI-Specification#1046]
I've checking Parameter.[style, explode] and see direct mapping from collectionFormat for these values in 2.0:
 - collectionFormat:csv -> style:form
 - collectionFormat:ssv -> style:spaceDelimited
 - collectionFormat:pipes -> style:pipeDelimited
 - collectionFormat:multi -> explode

But I didn't see any mapping for **collectionFormat:tsv**, are we going to drop support for this part in [3.0](https://github.com/OAI/OpenAPI-Specification/releases/tag/3.0.0-rc0)?

**Comment by darrelmiller** [comment]
That was the plan.  Using tabs in URLs seems like a bad idea.

**Comment by MikeRalphson** [comment]
This instance, and the case where a parameter has a `type` of `array` and a `collectionFormat` of **x** (e.g. `pipes`) and an `items.collectionFormat` of **y** (e.g. `csv`) (giving: `a,b|c,d`) seem to be the only parts of the 2.0 specification which can't be losslessly converted to 3.0.x

**Comment by mission-liao** [comment]
@MikeRalphson  in fact, you can have x, y, z .... because items object in 2.0 can be nested with another one.

IMO, it's "too free" and seems to be a "spec design flaw" instead of something purposely supported.
