### ISSUE TITLE
Distinguish between literals and parameters in the otherwise equivalent paths

### ISSUE THREAD

**Issue by michkhol** [OAI/OpenAPI-Specification#1048]
Feeling like beating the dead horse here, but would it be possible for the Swagger _editor_ to accept
`/search/{myncbi-id}/citations`
and
`/search/{myncbi-id}/{search-id}`
as different paths?
The Swagger-UI seems to be fine with that.

**Comment by webron** [comment]
Please open questions on specific tools on their respective repositories. This repo is for the spec itself.

**Comment by michkhol** [comment]
Sorry, it is not clear from your comment, if the spec supports this feature. If it does not, it does not make sense to ask questions about it in other repositories. At the same time Swagger-UI supports it de-facto. Is there an explanation for this?

**Comment by webron** [comment]
You asked about whether it's possible for swagger-editor to accept it. You didn't ask if it's acceptable by the spec. The two paths you described are considered different.

**Comment by michkhol** [comment]
Thanks!
