### ISSUE TITLE
How should basePaths for multiple environments be specified?

### ISSUE THREAD

**Issue by shelbys** [OAI/OpenAPI-Specification#106]
For instance, development vs test vs staging vs production?

We've been putting them in a parallel `basePaths` like:
```
{
  basePath: 'http://api.example.com'
  basePaths: {
    development: 'http://api.dev-example.com',
    test: 'http://api.test-example.com',
    stage: 'http://api.stage-example.com',
    production: 'http://api.example.com'
  }
}
```

**Comment by DeX3** [comment]
Has this been implemented now? I'm still confused on how to use different hosts for different environments. I only want to be able to use the same `swagger.yaml` file in development and in production, but have swagger-editor only go to development when I'm testing locally. Is this possible?

**Comment by webron** [comment]
Closing in favor of #562.

**Comment by leosoto** [comment]
@webron If I understand correctly from the resolution in #562 and the merged patch in #604, that won't allow to specify multiple global base paths based on "environments" as described at the beginning of this issue:

> For instance, development vs test vs staging vs production?

The solution on #562 only supports overriding schema/host/past at the operation level. Shouldn't we reopen this ticket then? (Or perhaps closing it with the explicit reason that OpenAPI won't support this use case) cc: @fehguy

**Comment by webron** [comment]
@leosoto - we've decided that supporting environments is outside the scope.

**Comment by AmreeshTyagi** [comment]
@leosoto environment support is outside the scope. :(  I was waiting for it since long time.
