### ISSUE TITLE
MAINTAINERS file?

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1066]
From the [Open API Initiative Charter](https://www.openapis.org/participate/how-to-contribute/governance):

> The maintainers of the TDC shall be those listed in the MAINTAINERS file in the project repository, available in the top level of the code repository.

Should CONTRIBUTORS(.md) be renamed MAINTAINERS(.md), should a new MAINTAINERS(.md) file be created or should the wording of the governance doc be updated?

**Comment by whitlockjc** [comment]
I can see `CONTRIBUTORS[.md]` and `MAINTAINERS[.md]` being two separate things.  Either way, both are missing and retroactively populating a `CONTRIBUTORS[.md]` would be extremely difficult.  I think it makes sense to keep the governance doc as-is and we should create these files.

I'll let the other @OAI/tdc members chime in.

**Comment by MikeRalphson** [comment]
CONTRIBUTORS.md does exist on the OpenAPI.next branch (but I think it contains maintainers).

**Comment by whitlockjc** [comment]
Ah yes, I forgot to go there.  I think you're right, the current `CONTRIBUTORS.md` should be `MAINTAINERS.md` but at the same time, `CONTRIBUTORS.md` **should** contain all maintainers to at least persist their record of contribution in the event they exit the maintainers role.  Make sense?

**Comment by RobDolinMS** [comment]
If we add a new MAINTAINERS file, we might want to match what the Open Container Initiative (OCI) does: https://github.com/opencontainers/runtime-spec/blob/master/MAINTAINERS

**Comment by whitlockjc** [comment]
Works for me.

**Comment by RobDolinMS** [comment]
@whitlockjc Would you want to write a PR for this one?

**Comment by MikeRalphson** [comment]
Refs #1215 #1214
