### ISSUE TITLE
Server Object must define default API location if not present

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1068]
If Server Object is not provided then we should consider the `url` to be effectively `\`

**Comment by whitlockjc** [comment]
What is this `\` you speak of?  ;)

**Comment by darrelmiller** [comment]
That's the Windows root :-)

**Comment by RobDolinMS** [comment]
TDC: @webron will take this one

**Comment by webron** [comment]
Closed as PR is merged.
