### ISSUE TITLE
Some schema examples contain both required and default which can be confusing

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1077]
This example https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#models-with-polymorphism-support has a required field that also has a default value.

I am recommending that we remove the `default` because it risks making the `required` notion invalid and encourages clients to unnecessarily send default values over the wire.

**Comment by RobDolinMS** [comment]
TDC: @fehguy was previously a hold-out but is now OK with this.  @darrelmiller will write a PR.
