### ISSUE TITLE
CommonMark allows HTML tags, should some be prohibited/ignored?

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1078]
CommonMark allows embedded HTML.  What do we need to do ensure OpenAPI definitions are "safe".  

Long and painful thread here https://talk.commonmark.org/t/make-commonmark-safe-by-default/1265/52

**Comment by DavidBiesack** [comment]
I don't think we need to manage this other than to mention it in the new paragraph about rich text/CommonMark... a note to tool writers to be careful about `<script>` tags is probably enough.

Interpretation of such text is entirely up to the _execution context_ of the tool(s), and there are many such contexts, not all of which are HTML or browsers. We should note that such tools may wish to escape such description strings, but having worked on `swagger-codegen generate -l html` I can say that overzealous escaping of the text gets in the way. (In swagger-codegen it was done both in the html engine **and** in the Markdown library, so even simple and "safe" tags like `<strong>` were escaped.)
