### ISSUE TITLE
Extra ] in schema field type for Parameter Object

### ISSUE THREAD

**Issue by timburks** [OAI/OpenAPI-Specification#1079]
Found in Version 3.0.0-rc2

![screen shot 2017-05-01 at 12 27 35 pm 3](https://cloud.githubusercontent.com/assets/405/25594295/c20d9dde-2e74-11e7-9366-da5d4e11ce05.png)

**Comment by RobDolinMS** [comment]
#TDC: Darrel is taking this one.

**Comment by webron** [comment]
Fixed.
