### ISSUE TITLE
Parameters with contents

### ISSUE THREAD

**Issue by RobDolinMS** [OAI/OpenAPI-Specification#1086]
A parameter today has either a content or a regular type.  

@darrelmiller suggested we should not allow for more than one media type for parameters.

@earth2marsh asks if there are examples of this

@fehguy and @darrelmiller - Please discuss

**Comment by fehguy** [comment]
I talked with @webron about this, I'll retract my concern about limiting the acceptable types to just one.  And since @webron and @darrelmiller have some crazy cosmic communication mechanism, I am pretty sure they're on the same page.

**Comment by darrelmiller** [comment]
@OAI/tdc Add text to limit media type map in parameters to just one entry

**Comment by webron** [comment]
Fixed and merged.
