### ISSUE TITLE
[3.0.0-RC1] Parameter Object with default

### ISSUE THREAD

**Issue by mission-liao** [OAI/OpenAPI-Specification#1087]
In 2.0, service providers allow to describe the "default" value that server side would use when that parameter is not provided in requests. [Parameter.default](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject)

I'm looking for ways to upgrade this part to 3.0:
 - for **formData** and **body**, **default** field in Schema Object might be used for this purpose.
 - for **path**, **query**, **header**, there is no way is 3.0 to describe this AFAIK.

**Comment by darrelmiller** [comment]
In 3.0 all parameter objects support a `schema` object.  The `default` property can be provided there.

**Comment by mission-liao** [comment]
Oh! I missed that part, thanks.
