### ISSUE TITLE
Provide all operations for specific objects

### ISSUE THREAD

**Issue by philippeluickx** [OAI/OpenAPI-Specification#1097]
As a user, I would like to know what I can do with a specific object.
With Petstore as an example

The problem: Operations have 2 types of metadata attached that can refer back to e.g. the object "Pet": tags and object schemas (in parameters or responses).

Object schemas:
I could technically traverse all defined operations and see if the object is used there. 2 issues:
- It assumes that all object definitions are defined in schemas
- Not all relevant operations refer to the "Pet" object definition (e.g. a DELETE operation)

Tags:
The API owner can define different tags. In Petstore, we have a tag "Store" that kind of refers to the "Order" object.

At the moment, the best solutions to me seems to be a combination of schemas, tags and paths - simply checking if I find the object somewhere and assuming it is linked.

**Comment by brylie** [comment]
I can understand the value of being able to ask questions like "what can I do with Pets via this API?" and "what API endpoint(s) are related to Pet objects?".

**Comment by handrews** [comment]
This sort of thing is being addressed in OAS 4 Moonwalk:

* https://github.com/OAI/sig-moonwalk/discussions/30
* https://github.com/OAI/sig-moonwalk/discussions/67
* [principle of operation signatures](https://www.openapis.org/blog/2023/12/06/openapi-moonwalk-2024)

Please join the discussions there if you are still interested!
