### ISSUE TITLE
[3.0.0-RC1] description about Encoding Object seems not consistent

### ISSUE THREAD

**Issue by mission-liao** [OAI/OpenAPI-Specification#1105]
Please refer to the following two description sections:

in the description of **Special Considerations for multipart content**
> In scenarios where more control is needed over the Content-Type for multipart request bodies, an encoding attribute is introduced. This attribute is only applicable to multipart/* and x-www-form-urlencoded request bodies.

in the description field 'encoding' property in **Media Type Object**
> Encoding of the media type. The encoding object SHOULD only apply to requestBody objects when the content type is multipart.

There should be no problem that "Encoding Object" applied to multipart/* content, but is it legal to be used on x-www-form-urlencoded content, too?

**Comment by webron** [comment]
Believe it or not... this is why #954 is still open :(
