### ISSUE TITLE
Ability to have nested group tags

### ISSUE THREAD

**Issue by liftyourgame** [OAI/OpenAPI-Specification#1107]
We have an API with over 170 routes. We would like to be able to represent our api using nesting:

```
/v1/Clients
    /Addresses
    /Accounts
        /Roles
    /Documents
/v1/Organisations

```

There is no way to represent this in Swagger as we can add only one group tag.

Could we supply multiple tags?

Eg:

```
- tags
  Clients
  Addresses

```

**Comment by MikeRalphson** [comment]
Something similar was discussed in #647

**Comment by webron** [comment]
Yeah, let's try to consolidate it all under one ticket.
FWIW, you can already supply multiple tags.
