### ISSUE TITLE
Add resources and other groupings to the "information architecture"

### ISSUE THREAD

**Issue by cfineman-sfdc** [OAI/OpenAPI-Specification#1108]
I would welcome pointers to already-existing mechanisms or previous conversations around this topic but...

OAI seems largely based on a path-oriented, rather than a resource-oriented ontology. A lot of our user guides & existing documentation assets (DITA) are organized around resources and other kinds of grouping. One of our engineers has been playing around with an extension that defines groups of paths and these groups can have their own title/summary/description tags. It allows us to create an "information architecture" that our doc & ux folks are happier with. 

One might be inclined to suggest doing this via definitions, at least for the resource-based grouping but since we support different field sets for C vs R vs U we would lose that grouping ability. Inferring from the PATH does not always work well and feels a bit kludgy anyway (e.g. to infer POST is related to GET/PUT/PATCH/DELETE not to speak of subresources).

So, his proposed solution was to define the structure explicitly. I'd like to know if anyone has proposed something similar or if it warrants further discussion

**Comment by darrelmiller** [comment]
Currently in OpenAPI, resources are identified via Path Item Objects.  It is not convenient for people who want to identify resources via query string parameters.

Tags can be used at the operation level to perform a variety of different grouping tasks.

There is no reason why different schemas couldn't be used to describe the representations of the different HTTP methods (aka Operations).

I have worked with API description languages that attempt to define HTTP resources by nesting them (e.g. WADL) and my experience is that it quickly becomes painful to edit and read the document. 

Would having the ability to attach Tags to path item objects help you achieve your goals?  I can see value in that.

**Comment by cfineman-sfdc** [comment]
Regarding "resources are identified via Path Item Objects": We document of the POST as part of the same resource as the other methods. Not strictly REST where the collection of all X is a separate resource from specific instances of X but I think you'll agree it's a relatively common "gestalt" implementers use.

I believe tags alone are not adequate for my use case because I have documentation artifacts I want to associate with the group (suggesting resource is a special case of group). Doing separate swagger docs for each group is not practical either. 

The one originally proposed by my colleague @3den is shown in the attachment. This appears as a top-level section in the swagger document. [x-sfdc-resource.txt](https://github.com/OAI/OpenAPI-Specification/files/1005899/x-sfdc-resource.txt)

My original (internal) suggestion was to have each path have an x-sfdc-group element that has an arbitrary ID that is used to group the paths together but it does not allow for title/description/summary. 

Another possible approach is to have a "groups" section (similar to the definitions section) and add a "group: $ref" element to to the Patch Item Object. The Group Object would merely have a 1-to-Many relationship to Path Item Object... there would be no semantics except for the association (e.g. not suggesting common headers across the group). It's *possible* we might like nested groups and the "Group Reference" might point to in "inner" group but there's still some debate over whether we want to encourage such an approach internally.

**Comment by darrelmiller** [comment]
Tags have both a description and external docs field https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#tag-object

**Comment by cfineman-sfdc** [comment]
Wow totally missed that on an earlier reading.... it's even in 2.0. Thanks!
