### ISSUE TITLE
Clarify whether protocol-relative URLs are valid (servers.url etc)

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1109]
> A URL to the target host. This URL supports Server Variables and may be relative, to indicate that the host location is relative to the location where the OpenAPI definition is being served

Does this imply a protocol-relative URL (or [network-path reference](https://tools.ietf.org/html/rfc3986#section-4.2)) is valid, i.e. relative to the protocol/scheme used to serve the OpenAPI definition?

**Comment by darrelmiller** [comment]
That is how I read the words.  Whether that is what we want or not is a different matter.  I don't see an obvious reason why `//example.org/api` could not be a valid `url`

**Comment by MikeRalphson** [comment]
Hmm, imagine I have a relative URL in my info.termsOfService

> **Relative References in URLs**
  Unless specified otherwise, all properties that are URLs MAY be relative references as defined by RFC3986.     Relative references are resolved using the URLs defined in the Server Object as a Base URI.

How is this URL to be resolved against potentially multiple URLs from the Server Object array? Sequentially until one resolves to a 2XX status code?

I'm happy enough with the idea that relative URLs should be resolved using the Server Object URL(s) as a base, where those URLs have been resolved against the URL used to access the OpenAPI definition, but we might be heading into 'needing an example' territory.

**Comment by darrelmiller** [comment]
> How is this URL to be resolved against potentially multiple URLs from the Server Object array? Sequentially until one resolves to a 2XX status code?
I would expect to find a termsOfService relative to all of the base URLs.  The multiple server URLs are there to provide references to duplicate APIs.  I expect that if a resource is available relative to one base URL, then it should be available relative to them all.

I suspect you are correct that some more detailed example may be useful.

**Comment by qaamal** [comment]
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.9-abcd",
    "title": "Swagger Sample API",
    "description": "A sample API that uses a petstore as an example to demonstrate features in the swagger-2.0 specification",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "name": "Swagger API Team",
      "url": "http://swagger.io"
    },
    "license": {
      "name": "Creative Commons 4.0 International",
      "url": "http://creativecommons.org/licenses/by/4.0/"
    }
  },
  "host": "my.api.com",
  "basePath": "/v1",
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "text/plain; charset=utf-8",
    "application/json",
    "application/vnd.github+json",
    "application/vnd.github.v3+json",
    "application/vnd.github.v3.raw+json",
    "application/vnd.github.v3.text+json",
    "application/vnd.github.v3.html+json",
    "application/vnd.github.v3.full+json",
    "application/vnd.github.v3.diff",
    "application/vnd.github.v3.patch"
  ],
  "produces": [
    "application/json",
    "application/xml"
  ],
  "paths": {
    "/pets/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "description": "ID of pet to use",
          "required": true,
          "type": "array",
          "items": {
            "type": "string"
          },
          "collectionFormat": "csv"
        }
      ],
      "get": {
        "description": "Returns pets based on ID",
        "summary": "Find pets by ID",
        "operationId": "getPetsById",
        "produces": [
          "application/json",
          "text/html"
        ],
        "responses": {
          "200": {
            "description": "pet response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          },
          "default": {
            "description": "error payload",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Pet": {
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        }
      }
    },
    "ErrorModel": {
      "required": [ "code", "message" ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}

**Comment by webron** [comment]
@qaamal?

**Comment by earth2marsh** [comment]
It seems to me that this burden falls on the spec author. In @MikeRalphson 's example, if you have multiple servers, either make sure the ToS is avail on each or don't make it relative, no?

**Comment by webron** [comment]
Created examples in the workshop!
