### ISSUE TITLE
Minimum and Maximum values do not show up for Query Parameters such as Limit

### ISSUE THREAD

**Issue by michaelbaqadi** [OAI/OpenAPI-Specification#1118]
For example, the number 63333 does not show up in the UI for this son file.         
"parameters": [
          {
            "name": "limit",
            "in": "query",
           "description": "How many items to return at one time (max 100)",
            "minimum": 0,
            "maximum": 63333,
            "required": false,
            "type": "integer",
            "format": "int32"
          }
        ]

**Comment by webron** [comment]
This is a tooling issue, not a spec. Please open on the respective tool.
