### ISSUE TITLE
Discriminator - unclear wording

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1121]
> Here the discriminator value of dog will map to the schema #/components/schemas/Dog, rather than the default (implicit) value of Dog. If the discriminator value does not match a implicit or explicit mapping, no schema can be determined and validation should fail. Note, mapping keys MUST be string values, but tooling may response values to strings for comparison.

"**but tooling may response values to strings for comparison**".

No PR as unsure of intent.

**Comment by webron** [comment]
@MikeRalphson it's nitpicking like that that's slowing us down ;)

**Comment by fehguy** [comment]
don't assign this to me.  doc cleanup is the right time for this

**Comment by MikeRalphson** [comment]
> @MikeRalphson it's nitpicking like that that's slowing us down ;)

I feel bad now. ;)

Is "doc cleanup" a separate phase to this RC?

**Comment by ePaul** [comment]
Hmm, so what is the intend here? I don't understand the meaning.

**Comment by fehguy** [comment]
yea, that was pretty badly worded.  The intent was:

"but tooling may _convert_ response values to strings for comparison".

**Comment by webron** [comment]
Fixed by #1210.
