### ISSUE TITLE
Security Scheme Object documentation is incorrect

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#1122]
In the table here:

https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc1/versions/3.0.md#fixed-fields-22

There are *Required* fields marked throughout the table, however I believe the intent is that the `required` state is really dependent on the type of security scheme

@webron could you please help clarify the intent and we can create a PR?

**Comment by webron** [comment]
That's the `Validity` column.

**Comment by ePaul** [comment]
Hmm, I think this should be made clearer.
Maybe split the table in two with a sentence inbetween?

-----


Allows the definition of a security scheme that can be used by the operations.
Supported schemes are HTTP authentication, an API key (either as a header or as a query parameter) and OAuth2's common flows (implicit, password, application and access code).

##### Fixed Fields

Field Name | Type | Description
---|:---:|---
<a name="securitySchemeType"></a>type | `string` | **Required.** The type of the security scheme. Valid values are `"apiKey"`, `"http"`, `"oauth2"`, `"openIdConnect"`.
<a name="securitySchemeDescription"></a>description | `string` | A short description for security scheme. [CommonMark syntax](http://spec.commonmark.org/) can be used for rich text representation.

Depending on the `type` value, other fields are allowed (and possibly required):

Field Name | Type | Validity | Description
---|:---:|---|---
<a name="securitySchemeName"></a>name | `string` | `apiKey` | **Required.** The name of the header or query parameter to be used.
<a name="securitySchemeIn"></a>in | `string` | `apiKey` | **Required.** The location of the API key. Valid values are `"query"` or `"header"`.
<a name="securitySchemeScheme"></a>scheme | `string` | `http` | **Required.** The name of the HTTP Authorization scheme to be used in the [Authorization header as defined in RFC 7235](https://tools.ietf.org/html/rfc7235#section-4.2).
<a name="securitySchemeBearerFormat"></a>bearerFormat | `string` | `http` (scheme `"bearer"`) | A hint to the client to identify how the bearer token is formatted.  Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
<a name="securitySchemeFlows"></a>flows | [OAuth Flows Object](#oauthFlowsObject) | `oauth2` | **Required.** An object containing configuration information for the flow types supported. 
<a name="securitySchemeOpenIdConnectUrl"></a>openIdConnectUrl | `string` | `openIdConnect` | **Required.** OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL. 

This object can be extended with [Specification Extensions](#specificationExtensions).

**Comment by darrelmiller** [comment]
@OAI/tdc Recommends changing the Validity to be "Applicability" or "Applies To"

**Comment by webron** [comment]
Closed by #1213!
