### ISSUE TITLE
Enum value names

### ISSUE THREAD

**Issue by stuartbloom** [OAI/OpenAPI-Specification#1123]
I have the following enum:

```
namespace WebApi.Logic.CustomPages.Dtos
{
    public enum CustomPageFieldType
    {
        Text = 1,
        Numeric,
        Date,
        Numeric_Function,
        Dropdown_List,
        Checkbox
    }
}
```
However, when a class includes this as a property it is shown as `type (integer, optional) = ['1', '2', '3', '4', '5', '6']integerEnum:1, 2, 3, 4, 5, 6`,, and when exported using NSwag as a Typescript enum it has the following definition:

```
export enum CustomPageFieldResponseDtoType {
    _1 = 1, 
    _2 = 2, 
    _3 = 3, 
    _4 = 4, 
    _5 = 5, 
    _6 = 6, 
}
```
How can i get it so that the enum is exported as:

```
export enum CustomPageFieldResponseDtoType {
    Text = 1, 
    Numeric = 2, 
    Date = 3, 
    Numeric_Function = 4, 
    Dropdown_List = 5, 
    Checkbox = 6, 
}
```

Thanks

**Comment by chrsmrtn-** [comment]
I too have this same issue

**Comment by webron** [comment]
This is currently not supported by the spec, see #348. Tooling can try to use extensions to overcome it.

**Comment by stuartbloom** [comment]
@webron thanks for the info, but are there any examples?

**Comment by webron** [comment]
Examples for what? It's not supported.

**Comment by stuartbloom** [comment]
@webron I thought you said tooling and extensions can help.

**Comment by webron** [comment]
I said people can try using them, I don't know if that would work. I do not have examples for it.

**Comment by aureole82** [comment]
> This is currently not supported by the spec, see #348. Tooling can try to use extensions to overcome it.

I don't think that #348 matches exactly the question. Please reconsider your answer and take the first step. Otherwise Swashbuckle, NSwag and others will never be able to generate decent C# / Typescript / ... enums. We developers are quite desperate.
