### ISSUE TITLE
Why are not sections for text in the spec?

### ISSUE THREAD

**Issue by gsi-delmo** [OAI/OpenAPI-Specification#1128]
Why are not sections for text in the spec? I mean a text section for general purpose describing some general information not anchored to any endpoint. There may be a chance to add this to current spec 3.0.0 while it is still open.

**Comment by darrelmiller** [comment]
Would the `description` property in the `info` object work for you? https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#infoObject

**Comment by gsi-delmo** [comment]
No, it wouldn't. Suppose I want to add a general-purpose information about all the endpoints related to users and other text section about all the endpoints related to contacts. 

I have seen that render tools group all the endpoints with the same tag under a same section in the rendered document so a possible solution could be to add some section in the schema to register tags and have a field _description_ for them so the render tools can show the description for a specific group of endpoints.

What do you think?

**Comment by darrelmiller** [comment]
The [OpenApi Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#openapi-object) has a `tags` property that allows you to define tags such as `users` and `contacts` and those tag objects have a `description` property.  You can then attach the tags to the appropriate operations.

**Comment by gsi-delmo** [comment]
Thanks @darrelmiller! It was exactly as I supposed. It was not noticed by me at the first glance.
