### ISSUE TITLE
Provide a JSON example for the Server Object in the specification

### ISSUE THREAD

**Issue by ckriley** [OAI/OpenAPI-Specification#1130]
Currently the Server Object Example:

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#server-object-example

only provides a YAML definition. For consistency purposes a JSON example should be provided as is done in the License Object example:

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#license-object-example

**Comment by webron** [comment]
@ckriley Thank you for the ticket. Would you mind submitting a PR to add those JSON examples?

**Comment by ckriley** [comment]
will do @webron

**Comment by webron** [comment]
PR merged, thanks!
