### ISSUE TITLE
A quick question aAbout MIME types

### ISSUE THREAD

**Issue by cosin2008** [OAI/OpenAPI-Specification#1132]
If consumes/produces are defined as empty list, what does they mean?

For global mime types, if its value is empty list, can we treat it as undefined mime types? 
For specified mime types under an operation, it is saying that 'empty' is valid and means to override global mime types. But what is exact MIME types that allowed? How could client and server handle it based on this definition? Thanks!

**Comment by ePaul** [comment]
I would think an empty means nothing is consumed (i.e. the request takes no body/form parameters), or nothing is produced (the response has no body).

This is only useful in limited cases. (In general, I would suggest to not use the global consumes/produces definition, as this is operation-specific.)

**Comment by webron** [comment]
Pretty much what @ePaul has said. Thankfully, in 3.0 this is no longer an issue.
