### ISSUE TITLE
Where is commaDelimited in styles?

### ISSUE THREAD

**Issue by slinkydeveloper** [OAI/OpenAPI-Specification#1133]
Hi,
I've found in [Parameters Examples](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#parameter-object-examples) this: `"style": "commaDelimited"`
Where is this style defined?

**Comment by ePaul** [comment]
I think this is meant to be `simple` (which is a comma-separated style), and is a mistake in that example.

**Comment by darrelmiller** [comment]
Yeah, we went back and forward on the name and that update was missed.

**Comment by slinkydeveloper** [comment]
Ok so it works just like old "csv" in swagger 2?

**Comment by darrelmiller** [comment]
It is intended to work like "simple" in RFC6570 https://tools.ietf.org/html/rfc6570#section-3.2.2  which should be effectively equivalent to csv in OpenAPI V2.

**Comment by slinkydeveloper** [comment]
Thank you!
