### ISSUE TITLE
Config object

### ISSUE THREAD

**Issue by possibilities** [OAI/OpenAPI-Specification#1138]
I'd really like to document the API's configuration along with everything else that OpenAPI supports. From my POV values that come in via configuration are somewhat similar to other values that end up as path parameters. Perhaps I could nominate a new `in` value called `config` but it seems more convenient to declare at the top level as I do/suggest in this extension:

https://github.com/possibilities/oacxs

That said it might also be nice to allow both "top level" configuration declaration and allowing "paths" to declare dependencies on these values as needed.

Anyway food for thought. The extension is useful to me and also seems like it could be "in scope" for OpenAPI more generally.

**Comment by darrelmiller** [comment]
Would it be possible to give an example of the type of config values you would like to store?  I understand that API implementations have configuration values, but most of those values are not things that should be publicly exposed.  The OpenAPI definition is a document that is intended to be shared with consumers of the API and normally does not contain implementation details.

I have been pondering for a while the need for a complimentary definition document that can describe implementation details of an API.  I wonder if your requirement would fit better in this alternate document.

**Comment by handrews** [comment]
No response for 6+ years, closing.
