### ISSUE TITLE
Has the 'support' for websockets (ws/wss) been dropped from 3.0.0?

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1140]
I can see no mechanism for indicating that a client should initiate a websocket handshake at either the root, path or operation level (the new AsyncAPI specification notwithstanding).

**Comment by webron** [comment]
Isn't it the same as before? Just specify ws/wss as the scheme in the Server Object's url?

**Comment by MikeRalphson** [comment]
My bad. I was using a non-standard URL parser implementation. Thanks.
