### ISSUE TITLE
Problems in parameters field type for Link Object

### ISSUE THREAD

**Issue by timburks** [OAI/OpenAPI-Specification#1143]
Found in Version 3.0.0-rc2

<img width="943" alt="screen shot 2017-06-03 at 9 27 21 am" src="https://cloud.githubusercontent.com/assets/405/26755311/9e88ca16-483f-11e7-8a70-d3981cbbeda7.png">

I guess this was intended to be `Map[string, Any|{expression}]`.

But would `Map[string,{expression}]` suffice?

**Comment by darrelmiller** [comment]
The `Any` was included to allow linked operations to have certain parameters be provided with constant values.  The runtime expression syntax doesn't allow for expressing constant values.

It does the beg the question, how does tooling distinguish between a mistyped expression and literal string.  My initial thought would be to check the first character for a $ and then attempt to interpret it as an expression.  This does mean that strings that start with "$" would not be valid literal values.  Not exactly ideal.

**Comment by handrews** [comment]
PRs merged – closing!
