### ISSUE TITLE
[Contributors] Review pull requests and update

### ISSUE THREAD

**Issue by RobDolinMS** [OAI/OpenAPI-Specification#1156]
We should consider where the bar is for contributions.

@RobDolinMS to gather data on PRs/contributions/comments looking for natural breaks

**Comment by RobDolinMS** [comment]
The below data is for people who have a number of PRs (open or closed, merged or not merged) and who have at least one closed PR in the past nine months:
* >25 PRs: 
Ron    Ratovsky
Tony    Tam
Kris    Hahn
Mike    Ralphson
Darrel    Miller
* 15-18 PRs:
Rob    Dolin
Paŭlo    Ebermann
* 6-10 PRs:
Paul    Hill
Marsh    Gardiner
Erik    Wilde
David    Biesack
Jason    Harmon
* 4 PRs:
Tanya    Fesenko
Ralf    Handl
* 3 PRs:
Jeremy    Whitlock
Ole    Lensmar
* 2 PRs:
Logan    Bailey
Will    Dady
Tim    Burks
Rick    Curtis
James    Watts
Richard    Gibson
Robert    Panzer
* 1 PR - Not listed

**Comment by ePaul** [comment]
Okay, next time I'll open many tiny PRs instead of a few big ones ;-)

**Comment by MikeRalphson** [comment]
We're now discussing moving to more of an 'all-contributors' model, so closing this. Thanks all.
