### ISSUE TITLE
JSON schema for formData parameters

### ISSUE THREAD

**Issue by ktimothy** [OAI/OpenAPI-Specification#1172]
Sometimes it can be very useful to use json-encoded strings in `formData` parameters. Currently it is not possible to define a schema for such json, though schema can be defined for `body` parameters. Are there any reasons for that? Is it planned to be added to 3.0?

**Comment by darrelmiller** [comment]
All parameters can now be described by a content object which identifies a media type (e.g. application/json) and a schema. https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#parameterObject
