### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by KES777** [OAI/OpenAPI-Specification#1205]
Please add to [this](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7) section for field `name` next variant:

If "in" is "body" The parameter has no effect on the parameter itself and is used for documentation purposes only. If you need more parameters - define more `properties` in `schema`
or so

This will resolve question like [this](https://stackoverflow.com/questions/31033394/swagger-editor-multiple-parameters-in-body)

**Comment by darrelmiller** [comment]
"body" is no longer a valid value for "in" in V3, so that should solve that problem.

**Comment by webron** [comment]
And we're not making changes to the 2.0 spec.

**Comment by KES777** [comment]
It is not about changes. It is about to duplicate information from plain text into table.

**Comment by webron** [comment]
We're not making any changes to the document itself. Duplicating information = making changes.
