### ISSUE TITLE
Create a 'Best Practices' wiki page

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#122]
See: https://groups.google.com/d/msg/swagger-workgroup/PaAX10gFYFM/qdZVyP5n9tkJ

**Comment by webron** [comment]
This is something to take into account for he next version of the spec.

**Comment by drewish** [comment]
Yeah a how to write your API so it's compatible with swagger guide would be helpful. You could point the people who get frustrated trying to document existing APIs there so they'd know what they need to change in their next version to be able to use Swagger.

**Comment by webron** [comment]
As long as we replace `Swagger` with `OpenAPI` there, sure ;)

@drewish - it would be very useful if you could cover some pitfalls you encountered in your process. Knowing the spec, it's difficult to realize where those pain points may be, and we'd definitely want to cover those.

**Comment by earth2marsh** [comment]
:+1:

**Comment by webron** [comment]
Parent issue: #589

**Comment by tycho01** [comment]
I hope using `schema` (and therefore `$ref`s) in non-body parameters could be encouraged for 3.0, since this new option seems non-obvious to those upgrading, while it could e.g. enable generated docs to [cross-link](https://github.com/OAI/OpenAPI-Specification/issues/728) parameters with models used in responses.

**Comment by webron** [comment]
@RobDolinMS - I don't recall what v3.Next is. This is part of the documentation of 3.0.0 but it can come after the official release of it. It's not a post 3.0.0 feature.

**Comment by handrews** [comment]
In the intervening years we closed the wiki and created learn.openapis.org.  If there's more work to do on this, please open issues on the [OAI/learn.openapis.org](https://github.com/OAI/learn.openapis.org) repository.
