### ISSUE TITLE
Security example bug?

### ISSUE THREAD

**Issue by jimmyjames** [OAI/OpenAPI-Specification#1227]
In [securityExample.json](https://github.com/OAI/OpenAPI-Specification/blob/master/fixtures/v2.0/json/resources/securityExample.json#L56), `/pets/{id}/get` has a security definition of:

```json
"security": [
          {
            "githubAuth":[
                "user:read",
                "user:write"
              ]
          },
          {
            "internalApiKey": []
          }
```

`githubAuth`, and the two listed scopes, do not appear in the `securityDefinitions` itself (there is a `githubAccessCode` securityDefinition).

Does the required security for an operation need to be actually defined in the `securityDefinitions`, or can it be anything?

**Comment by ePaul** [comment]
This is for 2.0, right?

**Comment by jimmyjames** [comment]
Yes, https://github.com/OAI/OpenAPI-Specification/blob/master/fixtures/v2.0/json/resources/securityExample.json specifies `"swagger": "2.0"`.

**Comment by RobDolinMS** [comment]
@webron will take a look at submitting a PR to fix.

**Comment by MikeRalphson** [comment]
Closing as the version 2.0 test fixtures were removed some time ago.
