### ISSUE TITLE
[Help] Clarify how to use custom apiKey security definition

### ISSUE THREAD

**Issue by bomb-on** [OAI/OpenAPI-Specification#1229]
Hi all! I am trying to generate documentation for my API routes which require HMAC-SHA256 authentication. This means that I have to include `Authorization` header for every request which consists of API key and generated HMAC signature separated by colon (e.g. `Authorization: API_KEY:GENERATED_SIGNATURE`).

I can easily generate the needed signature with JavaScript, but I cannot figure out how to add "key" and "secret" input fields in Swagger-UI "Authorize" pop-up and how to finally add it to `Authorization` header in each request.

Is something like this possible with OpenAPI Specification v3 at all? Any help/tip/link is extremely appreciated!

**Comment by RobDolinMS** [comment]
Thanks for this question @bomb-on.

@darrelmiller suggests you use the HTTP type with a custom scheme.

**Comment by darrelmiller** [comment]
This won't work for V2 though.

**Comment by bomb-on** [comment]
@darrelmiller Since I just started with specification from the scratch, I am not worried about v2 compatibility :)

@RobDolinMS I'm not sure I understood the suggestion... I am using HTTP schema but I don't see how is this relevant :) I tried with custom `securityDefintions` but I just cannot figure out how to add 2 input fields in my UI (because I need to enter both key and secret) and a my custom header in request...

Thanks a bunch for all the help!

**Comment by darrelmiller** [comment]
I think the problem you are having is that the 'http` securityScheme creates an `authorization` header that looks like this:

```
Authorization: <scheme> <parameter>
```
Unfortunately, no-one has got around to [registering a http scheme](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) for hmac so you would have to make one up.

Therefore your header would look something like:

```
Authorization: hmac  API_KEY:GENERATED_SIGNATURE
```

This can be described by 

```yaml
components:
  securityScheme:
    hmacScheme:
      type: http
      scheme: hmac
```

This tells the OpenAPI tooling that a client must use an `Authorization` header with the scheme `hmac`.  Unfortunately, OpenAPI tooling cannot know how to format the parameter as the scheme is not an official named scheme.

**Comment by bomb-on** [comment]
@darrelmiller But my `Authorization` header does not require `hmac` "scheme"... My header should be constructed with user's API key and calculated signature only:

`Authorization: API_KEY:GENERATED_SIGNATURE`

I just came across [this issue](https://github.com/swagger-api/swagger-ui/issues/2793), might be useful for my use-case, but I'm surprised that this is such a huge issue to handle :)

**Comment by skt44** [comment]
@darrelmiller does the OpenAPI tooling only work with registered http schemes?  Or is there a way to define non-official schemes?

**Comment by darrelmiller** [comment]
@bomb-on But that is an invalid Authorization header.  See the syntax for `credentials` herer https://tools.ietf.org/html/rfc7235#appendix-C

@skt44 It remains to be seen which http schemes are implemented by common OpenAPI tooling.  It would surprise me if many tools implement stuff like digest even though it is a registered scheme.

**Comment by skt44** [comment]
@darrelmiller thanks - in your hmac example, where would the function that calculates the hash be defined (since it isn't a registered scheme)?

**Comment by darrelmiller** [comment]
@skt44  Either tooling decides to support a commonly used but non-registered scheme, or it implements a plug-in mechanism in the case of client codegen, or it is simply a documentation hint to API consumers.

**Comment by handrews** [comment]
Looks like this discussion resolved several years ago, closing.
