### ISSUE TITLE
Accommodate legacy APIs by allowing query parameters in the path

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#123]
Issue by @earth2marsh 

---

There are real APIs where a query string may determine the structure of the response, for example `verbose=true`, `metadata=1`, `action=reboot`.

However, Those cannot be expressed in Swagger 2.0 today because the path/verb maps onto a response model 1:1.

While it may be a bit of a kludge, consider a unique path where the query string is hard-wired into the path:
`"path":"/me?metadata=1"`

The order of the query params may not be determined in real situations, but for the purpose of defining methods in the spec, this may be an acceptable compromise to accommodate legacy services.

**Comment by webron** [comment]
Parent: #574.

**Comment by antrix190** [comment]
I have something similar use case to handle, do we have a solution/work around to this issue yet?

**Comment by handrews** [comment]
This is too big of a change for 3.x, but [Moonwalk's](https://github.com/OAI/Moonwalk) approach to operations might accommodate it.
