### ISSUE TITLE
Missing ] in the type of the Link Object "parameters" field. 

### ISSUE THREAD

**Issue by timburks** [OAI/OpenAPI-Specification#1234]
We'd have fewer problems like this if 3.0.md was generated from a schema :)

<img width="936" alt="screen shot 2017-06-27 at 12 54 48 pm" src="https://user-images.githubusercontent.com/405/27607233-09fafe08-5b38-11e7-9ed0-6ec256ada689.png">

**Comment by webron** [comment]
We'd also have a much harder time maintaining a doc, especially considering about 30% of the spec can't be represented by a schema.

Since this is a small fix, would you consider submitting a PR?

**Comment by timburks** [comment]
OK! Here's [the PR](https://github.com/OAI/OpenAPI-Specification/pull/1235), which you've probably already seen.

**Comment by RobDolinMS** [comment]
@timburks OK to close this issue since we have PR #1235 ?

**Comment by timburks** [comment]
Yes, closing now.

**Comment by timburks** [comment]
This is still broken in the current OpenAPI.next.
