### ISSUE TITLE
Partial path templating is not allowed message for path variable with multiple parameter

### ISSUE THREAD

**Issue by rubenlara** [OAI/OpenAPI-Specification#1248]
Hi, actually I'm implementing a rest api with a path like /api/users/{groupid}.{departmentid}.{level}

users have this composite id to identify them. Calling operations are working but I cannot define the the path in swagger. I get a:

Semantic error at paths./api/users/{groupid}.{departmentid}.{level}
Partial path templating is not allowed.

I'm using swagger annotations to define the api and in the configuration I'm using enableUrlTemplating(true) too.

**Comment by webron** [comment]
That's an issue with the tool you're using, not the spec itself. Please check the relevant tool for known issues or file a new one if you can't find it.

**Comment by rubenlara** [comment]
@webron I'm using swagger annotations with spring boot and editing the exported swagger.json in the online swagger editor which is complaining about the path. Spring boot has no problem eith it as I wrote before. This is not a "tool" issue. Please, reopen the issue since swagger obviouly can't deal with such paths.

**Comment by MikeRalphson** [comment]
@rubenlara if your problem is with swagger editor, it is a tool issue not a OAS (specification) error. Consider raising an issue here https://github.com/swagger-api/swagger-editor
