### ISSUE TITLE
Are there challenges to merge the OpenAPI.next branch into the Master branch

### ISSUE THREAD

**Issue by RobDolinMS** [OAI/OpenAPI-Specification#1250]
Known issues: 
- [ ] Prepare ReadMe.md for merge (@usarid, week of 7/10 - 7/14)
- [ ] Other issues as identified
- [ ] Merge OpenAPI.next branch into Master branch (@webron, week of 7/17 - 7/21)
- [ ] Publish release (@webron, week of 7/17 - 7/21)
    (@DarrelMiller prefers Thu, 7/20)

Also watch for announcements / calls for help in the #spec channel on Slack

Planned time off:
7/24 - 7/28: @darrelmiller and @RobDolinMS

**Comment by MikeRalphson** [comment]
Happy to help on the Travis side. Some files cleaned up in the OpenAPI.next branch will get removed by a simple git merge - though if 2.0 is frozen this may no longer be a consideration.
