### ISSUE TITLE
How can I handle an internal item?

### ISSUE THREAD

**Issue by jugaadi** [OAI/OpenAPI-Specification#1253]
```
{
	"components": {
		"schemas": {
			"transaction": {
				"type": "object",
				"required": [
					"_type"
				],
				"discriminator": {
					"propertyName": "_type"
				},
				"properties": {
					"id": {
						"type": "string"
					},
					"_type": {
						"type": "string"
					},
					"date": {
						"type": "string",
						"format": "date"
					},
					"lineItems": {
						"type": "array",
						"items": {
							"id": {
								"type": "string"
							},
							"productId": {
								"type": "string"
							},
							"rate": {
								"type": "number",
								"format": "double"
							}
						}
					}
				}
			}
		}
	}
}
```

1. Reference

> Can I use a reference `"$ref": "#/components/schemas/transaction/lineItems"` elsewhere?

2. Discriminator

> How can I create a new model using polymorphism that can extend properties of internal child objects too like `lineItems` ?

**Comment by darrelmiller** [comment]
1.  My personal preference would be to say no.  If you want something to be reusable then be explicit about it.  Make lineitems a reusable schema and then reference it from within transaction.  However, I think others probably wouldn't agree with me.  /cc @whitlockjc 
I don't believe the spec is explicit about this.  It probably should be.  My question would be, how far can this go? Is  `"$ref": "#/components/schemas/transaction/properties"` ok? and shouldn't your ref actually be `"$ref": "#/components/schemas/transaction/properties/lineitems"` ?

2.  I have no idea.  Maybe @fehguy or @webron know.  This seems like another good reason to make lineitems its own top level schema.

**Comment by webron** [comment]
1. Technically, yes, only the correct $ref value is what @darrelmiller pointed out. You can technically $ref anything in the spec (though you can't use $ref anywhere in the spec).
2. Again, what @darrelmiller said.

**Comment by handrews** [comment]
Answered more than two years ago with no further questions, so closing.
