### ISSUE TITLE
Add support for importing non yaml files as block's

### ISSUE THREAD

**Issue by jdarling** [OAI/OpenAPI-Specification#1262]
Currently there is no (easy) way to define an external file that is not a yaml file.  It would be nice to have something like the ability to include an arbitrary file as a text block into a definition.  For example you could extract the descriptions into their own .md file, or code samples into their own .<proper extension> files for inclusion.

This could be done as either an extension of $ref's ability to include files or as a new directive.

**Comment by darrelmiller** [comment]
Autorest has an interesting alternative way of blending markdown and OpenAPI descriptions. https://github.com/Azure/autorest/blob/master/Samples/3a-literate-swagger/swagger.md

For examples you can use `externalValue` to point to any kind of document.

**Comment by michael-o** [comment]
> 
> 
> Autorest has an interesting alternative way of blending markdown and OpenAPI descriptions. https://github.com/Azure/autorest/blob/master/Samples/3a-literate-swagger/swagger.md
> 
> For examples you can use `externalValue` to point to any kind of document.

This link is dead now.

**Comment by MikeRalphson** [comment]
Thanks. The reference file appears to have been moved to https://github.com/Azure/autorest/blob/master/Samples/openapi-v2/3a-literate-swagger/swagger.md

**Comment by handrews** [comment]
Does the [External Documentation ](https://spec.openapis.org/oas/v3.1.0#external-documentation-object)Object solve this problem?
