### ISSUE TITLE
link object: operationId / operationRef descriptions

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1267]
In the following:

Field Name  |  Type  | Description
---|:---:|---
<a name="linkOperationRef"></a>operationRef | `string` | A relative or absolute reference to an OAS operation. This field is mutually exclusive of the `operationId` field, and MUST point to an [Operation Object](#operationObject).
<a name="linkOperationId"></a>operationId  | `string` | The name of an _existing_, resolvable OAS operation, as defined with a unique `operationId`.  This field is mutually exclusive of the `operationRef` field.  Relative `operationRef` values MAY be used to locate an existing [Operation Object](#operationObject) in the OAS.

Should the final sentence be moved / removed / merged in with the description for `operationRef`, or is it correct to have it against `operationdId` ?

**Comment by darrelmiller** [comment]
I think the "relative" sentence should be moved into the operationRef paragraph and the "mutually exclusive" sentence should be duplicated in operationRef but for the opposite case.  I'd do the PR but I don't have time today.

**Comment by DavidBiesack** [comment]
I made a PR for this, #1268 . Note that the "mutually exclusive" sentence was already in `operationRef`. O also changes "in the OAS" (which was wrong) to "in the OpenAPI definition" (but that language may change if another term is adopted in #1247)
