### ISSUE TITLE
Simplify externalDocs.

### ISSUE THREAD

**Issue by brendo** [OAI/OpenAPI-Specification#1271]
I'm wondering if `externalDocs` could be simplified as the current definition allows for some interesting use cases when attempting to visualise it.

```json
{
  "description": "Find more info here",
  "url": "https://example.com"
}
```

By default, all `description` fields support CommonMark, so someone could easily replace the above with just:

```json
{
  "description": "Find more info [here](https://example.com)"
}
```

Right now though, `url` is a required field, so that duplicate URL would also have to be included.

From an tooling perspective, they could inspect the `description` and if there's a link, choose to ignore the `url` property, but that might produce false positives if the two links are not the same.

This highlights another interesting point, at the moment there is no way to label the URL so when visualising it the tool has to inject it's own label:

```html
<a href="https://example.com">Find out more.</a>
```

One cannot use the `description` as the label, because we have to assume that CommonMark is supported which could lead to strange scenarios like:

```html
<a href="https://example.com">
   <p>Find out more about my awesome petstore by <a href="http://google.com">searching</a></p>
</a>
```

I guess, I'm not really sure what benefits `externalDocs` brings that couldn't be achieved with the existing `description` property, especially now that CommonMark is supported.

Thoughts?

**Comment by DavidBiesack** [comment]
The main benefit is the tools can external the doc URL  from the OpenAPI document without having to parse the CommonMark. Also, via the schema we can enforce this as a URL. Without it, one could put in a description string that does not link anywhere. The expectation is that the description is text that acts as a label for the link; CommonMark may used to style that text if needed.

**Comment by brendo** [comment]
> The expectation is that the description is text that acts as a label for the link; CommonMark may used to style that text if needed.

Understood, I'll make this assumption too :+1:
