### ISSUE TITLE
Working with multiple "servers" definitions

### ISSUE THREAD

**Issue by danballance** [OAI/OpenAPI-Specification#1275]
Hi folks,

I'm currently working on a PHP component for working with version 3 of the specification. I have a question about the servers arrays which I've not managed to answer by reading the docs and searching through old issues.

I'm not particularly clear on what the practical use cases for the servers arrays are, but even leaving this aside, I'm trying to understand what my library should be doing with the possible three levels at which the servers array can be set (root, path item and operation)?

Is the idea for these arrays to overload the higher level definitions? So if the servers array is set at the level of the operation then this would overload any path item definition and similarly any definition made at the path item level would overload the root definition? Or is the idea that they would be combined in some way? Or perhaps this is left as an implementation detail and my library should provide configuration options to control this behaviour?

Any guidance here would be gratefully appreciated. Use cases for the problems solved by the servers arrays would be useful as well. Apologies if this is already explained elsewhere - I have spent quite a while searching before posting here.

**Comment by MikeRalphson** [comment]
The description of the Operation-level servers array is the most clear on this point:

> An alternative server array to service this operation. If an alternative server object is specified at the Path Item Object or Root level, it will be overridden by this value.

I believe the Path Item-level servers array overrides the root-level one in the same manner.

As to (some) use cases for multiple servers:

* specifying multiple protocols (http, https, ws, wss)
* specifying test and live endpoints
* deprecated but still functional endpoints
* hosted and on-premise/self-hosted endpoints

**Comment by danballance** [comment]
Brilliant thanks very much, I'd miss this in the description. Just what I needed! Closing.
