### ISSUE TITLE
Cannot specify example field for a path parameter

### ISSUE THREAD

**Issue by smonani** [OAI/OpenAPI-Specification#1289]
When the location of a parameter (value of "in" field) is set to path, it does not recognize or accept the example field.

I'm attaching the sample swagger JSON and screenshot as well.
[swagger info.txt](https://github.com/OAI/OpenAPI-Specification/files/1170129/swagger.info.txt)
![swagger error](https://user-images.githubusercontent.com/5275162/28528578-1e75566a-705c-11e7-9b30-a299af17561c.png)

Thanks,
Sid

**Comment by MikeRalphson** [comment]
The OpenAPI v2.0 [Parameter Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject) does not have a property `example` (though it does have a `default` property), so this error message is correct. You could use a [specification extension](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#vendorExtensions) such as `x-example` to hold this value if needed.

Also this repository is for the OpenAPI specification itself, not any particular tool, such as [swagger editor](https://github.com/swagger-api/swagger-editor).

**Comment by smonani** [comment]
Since I think it makes a lot of sense to have the ability to be able to specify example for any type of parameter, shouldn't we be adding it the the OpenAPI specification? What would be the process to request addition of this field to the specification?

**Comment by webron** [comment]
In the next version of the spec (3.0.0) it's already included.
