### ISSUE TITLE
Invalid `operationRef` in links example

### ISSUE THREAD

**Issue by tfesenko** [OAI/OpenAPI-Specification#1292]
[OperationRef Examples](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#operationref-examples) suggests a value with a missing `/` separator after the `paths` in `operationRef`: 
`'#/paths~12.0~1repositories~1/{username}/get'` , but it should be `'#/paths/~12.0~1repositories~1/{username}/get'`  == `'#/paths/<'/2.0/repositories/{username}'.encode()>/get`.

The example of an absolute operationRef correctly uses a JSON Pointer with a `/paths/<JSON Pointer-encoded path item>`.

Related to https://github.com/OAI/OpenAPI-Specification/issues/1152

**Comment by webron** [comment]
@tfesenko thanks. do you have time to submit a PR to fix it? we're getting very close to the actual release.

**Comment by tfesenko** [comment]
@webron wrote:
> do you have time to submit a PR to fix it? 

Sure! I created PR #1293 for this. Just did not know if you wanted to include this fix into the release.

**Comment by webron** [comment]
Thanks, I'll review in just a few minutes. Anything that can be fixed before the actual release is welcome. This means we'll have less patch releases which is always a good thing.

**Comment by webron** [comment]
Closed as fixed, thanks again!
