### ISSUE TITLE
The link to v2 spec is down on the main README.md

### ISSUE THREAD

**Issue by nemenemsrouge** [OAI/OpenAPI-Specification#1297]
In this section, clicking on the link send me to a github 404

> This repository also contains the OpenAPI Specification 2.0, which is identical to the Swagger 2.0 specification before it was renamed to “OpenAPI Specification”, as well as the Swagger 1.2 and Swagger 2.0 specifications.

**Comment by webron** [comment]
Thanks for the quick catch, should be fixed (re-tagged with the fix)!
