### ISSUE TITLE
Unify Number DataType

### ISSUE THREAD

**Issue by younss** [OAI/OpenAPI-Specification#1304]
Hello,
Actually in the current specification Integer is different than Number.
integer | integer | int32 | signed 32 bits
long | integer | int64 | signed 64 bits
float | number | float |  
double | number | double |  

Can you please unify numbers declaration like that.
integer | **number | integer** | signed 32 bits
long | **number | long** | signed 64 bits
float | number | float |  
double | number | double |

**Comment by darrelmiller** [comment]
JSON schema makes the distinction between integer and number and therefore we want to follow that same model.  There is value is knowing if a value is an integer.

**Comment by DavidBiesack** [comment]
OpenAPI 2.0 referenced https://tools.ietf.org/html/draft-zyp-json-schema-04#section-3.5 which defined both `number` and `integer`. OpenAPI 3.0.0 references https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.2 which lists `number` but **not** `integer`, although at least one example shows ` "type": "integer"` .@awwright can you comment on this and if `integer` is a valid type?

**Comment by darrelmiller** [comment]
Unfortunately 'integer' was accidently dropped from the -00 spec.  See https://github.com/json-schema-org/json-schema-spec/issues/311#issuecomment-296847413  It is back in -01.  
Even though we only reference -00 in our spec, I think allowing 'integer' is an exception worth making.

**Comment by awwright** [comment]
Yeah, that was an omission by the fact JSON doesn't have a distinct
"integer" production.

That draft was intended to be reverse compatible with the same meta-schema.

The next draft fixes the issue.

**Comment by DavidBiesack** [comment]
I think it is more complicated than "allowing `integer` as an exception". We'll run into problems if we use tools based on -00 to validate OpenAPI documents against the (proposed/eventual) OpenAPI 3.0.0 schema.  i.e. [swagger-api/swagger-badge](https://github.com/swagger-api/validator-badge) validates OpenAPI 2.0 docs against the 2.0 schema using the [`json-schema-validator`](https://github.com/fge/json-schema-validator/blob/master/README.md) Java library. If `json-schema-validator` (or other analogous) tool is updated to use -00, any validation of an OpenAPI document with `type: integer` will fail - such tools won't know of our exception. What is the status of -00 and tools around it (for example, [here](https://github.com/java-json-tools/json-schema-validator/issues/226)) vs. -01 ?

I can't quite decipher the Change Logs for -01 to know the impact that adopting -01 would have on OpenAPI...

**Comment by webron** [comment]
We already allowed it in OAS3, and the JSON Schema will reflect it. Regardless of the JSON Schema for OAS3, and what Draft 05 (-00) allows, `integer` is a valid type.

**Comment by handrews** [comment]
@DavidBiesack Draft 05 (wright-00) tools, if any were to exist, should allow "integer".  Spec bugs do not constrain implementations, and "integer" is actually referenced elsewhere in the spec.  It's just not clearly defined in that version.  In any event, implementations that have moved past Draft 04 (zyp-04) have all jumped straight to Draft 06 (wright-01)

**Comment by handrews** [comment]
This has all since been sorted out.  The JSON data model only has the concept of "number".  JSON Schema's `type` keyword, which does not change the JSON data model, includes "integer" as a type for convenience.  More detailed numeric types of all sorts can be found in our [formats registry](https://spec.openapis.org/registry/format/).
