### ISSUE TITLE
Link for array element

### ISSUE THREAD

**Issue by Alan-Cha** [OAI/OpenAPI-Specification#1305]
How would I create a link that uses an array element as a parameter?

Let's say I have an OAS that looks like this:

```
---
 paths:
  "/users/{username}":
    get:
      operationId: getUserByUsername
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
  components:
    schemas:
      user:
        type: object
        properties:
          fullName:
            type: string
          friendUsernames:
            type: array
            items:
              type: string
...
```

How would I communicate to the user that these `friendUsernames` could be used to find more `users`?

I do not want to a create a link to a new method that takes in an array of `usernames` and returns an array of `users`. Rather, I only want to suggest to the user that `friendUsernames` contains `usernames` that can be used to call methods that require it. 

I think what I am suggesting is implementing a system that gives more meaning to common parameters. A userId can be used to obtain so-and-so information, an employeeId can be used to obtain so-and-so information, a companyId can be used to obtain so-and-so information, etc.

In the end, I want to turn an array of `usernames` into an array of `users` so perhaps it would be easier just to create a new method, but I think explaining the logic behind how an API is implemented is good. Maybe in practice, it would not be too useful as methods often require more than one parameter but it is a thought.

**Comment by darrelmiller** [comment]
I think what you are trying to do is define a typing system using JSON Schema.  You can fake it by using JSON references to point to types. e.g.

```yaml
---
 paths:
  "/users/{username}":
    get:
      operationId: getUserByUsername
      parameters:
      - name: username
        in: path
        required: true
        schema:
          $ref: '/components/schemas/username'
      responses:
        '200':
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/user"
  components:
    schemas:
      username:
        type: string
      user:
        type: object
        properties:
          fullName:
            type: string
          friendUsernames:
            type: array
            items:
              $ref: '/components/schemas/username'
...

**Comment by MikeRalphson** [comment]
@Alan-Cha if you mean using the new [Link Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#linkObject) in v3.0.0, I think you could have an [expression](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#runtimeExpression) such as

`$response.body#/friendUsernames[0]`

to indicate that the first element of the array could be used as a parameter to another operation. As each item of `friendUsernames` has the same schema, this might be sufficient? Unfortunately JSON pointer can only reference the whole array, or an individual element, not a wildcard set.

**Comment by Alan-Cha** [comment]
@darrelmiller I really like this solution! That is a smart way to approach this problem. I'll definitely keep this in mind next time! 

@MikeRalphson Yeah, this was approach I was originally going for but it has its flaws. It's too bad JSON pointers do not have that functionality but I can't blame JSON for that. This really isn't its intended purpose. 

Thank you all for answering my question! I'm satisfied with your answers! 😄
