### ISSUE TITLE
Support for SEARCH http method

### ISSUE THREAD

**Issue by lennygran** [OAI/OpenAPI-Specification#1306]
The SEARCH http method is not supported by OpenAPI specification, although defined in few RFC, including https://tools.ietf.org/html/draft-snell-search-method-00#section-2. Although having limited use, this method is a perfect fit for getting a list of items using PII or any other secure filters. Use of GET is not possible because PII filters cannot be included to URL. The SEARCH allows to do so. Hence it would be a great enhancement.

**Comment by darrelmiller** [comment]
I was hoping that ID would make it out of draft status but as it expired almost two years ago, I fear it might never make it.  We do limit the allowed methods to the most common ones, because if we were to allow the full official list then we would have to add wacky ones like 'BASELINE-CONTROL' and 'REBIND'.  https://www.iana.org/assignments/http-methods/http-methods.xhtml

Personally, I would be open to making it an open value, but I'm not sure that would fly with anyone else.

**Comment by lennygran** [comment]
I fully understand your concern. Unfortunately relaying on the original RFC introduced SEARCH as part of WebDAV https://tools.ietf.org/search/rfc5323 might not be a better idea either as it defines too many dependencies on WebDAV schemas and flows. 

I think it is a valuable method, it would be sad to "loose" such. There is no clear alternative to do a REST API for search with secure filter (provided within body). Often folks use POST, but it conflicts with "create", introducing ambiguity. 

Would you be willing to open this topic for discussion with your team and community?

**Comment by webron** [comment]
There was actually a discussion in #325. We ended up adding TRACE, but nothing else.

**Comment by darrelmiller** [comment]
POST doesn't mean create.  It means none of the other HTTP methods were more suitable, so we had to fall back to POST.  Create just happens to be one of the more common usages of POST.

**Comment by handrews** [comment]
@darrelmiller @lennygran do either of you have any idea if anyone's started an IETF draft for an HTTP equivalent to CoAP's FETCH?  Or know if there's a reason why that's not likely to work?  

https://tools.ietf.org/html/rfc8132#section-1.1 (note that this even references the expired SEARCH draft as an inspiration)

**Comment by handrews** [comment]
@darrelmiller @webron @lennygran note that the SEARCH draft has been revived- the current draft is valid until March 23, 2019: https://tools.ietf.org/html/draft-snell-search-method-01

**Comment by handrews** [comment]
Let's track this under issue #1747 which covers all HTTP methods and includes SEARCH in its list.  Closing this in favor of that.
