### ISSUE TITLE
How do i POST attachment along with body parameter in swagger 2.0 ?

### ISSUE THREAD

**Issue by dipak84patel** [OAI/OpenAPI-Specification#1307]
I am trying to include an excel file attachment along with body in swagger 2.0 and it is not working. I am not sure if swagger support this ? I would appreciate if someone could shed some light on this -

```
"parameters": [
        {
       "name": "file",
       "in": "formData",
       "type": "file",
 		"description": "upload file"
		},
		
        {
         "name": "request",
          "in": "body",
          "type": "string",
           "description": "Enter request",
           "required": true,
           "schema": 
       {
             "$ref": "#/definitions/post"
       }
     }
     ],
```

**Comment by webron** [comment]
You can't define both a body parameter and formData parameter in one operation. If you need to upload a file, in 2.0, all parameters need to be formData.

**Comment by dipak84patel** [comment]
So how do i accomplish a scenario in which i have parameters of different types ? Does Swagger 2.0 have any way to support this ?

**Comment by webron** [comment]
With formData you can specify other primitives, but not complex types. 2.0 doesn't support that.

**Comment by dipak84patel** [comment]
Are you guys planning to included this capability in 3.0 ?

**Comment by webron** [comment]
3.0 was already released, and it's included there, yes.

**Comment by dipak84patel** [comment]
sounds good
