### ISSUE TITLE
OPENAPI 3.0 Spec is not working on UI

### ISSUE THREAD

**Issue by dipak84patel** [OAI/OpenAPI-Specification#1308]
Does OPENAPI 3.0 Spec file work on Swagger-UI ? I noticed that while i tried to use petstore.yaml i noticed that i am not able to see "Try it out" option and it seems that it is not ready for UI. Please correct me if i am wrong ?

**Comment by webron** [comment]
This is not a question for the spec. Please file these kinds of tickets on the respective tools.
