### ISSUE TITLE
byte vs base64 format

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1310]
[Data Types](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types) defines `format: byte` as base64-encoded characters.

[Considerations for File Uploads](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#considerations-for-file-uploads) and [Special Considerations for multipart Content](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#special-considerations-for-multipart-content) mention `format: base64`, which is not mentioned in Data Types. Is this a typo and meant to say `format: byte`? Or are `base64` and `byte` different formats?

**Comment by axlbonnet** [comment]
I've stumbled on the same issue and the spec is incoherent on this point.

I've found [this remark](https://github.com/OAI/OpenAPI-Specification/pull/878/files/c5380d36498247cdad0f4192e0b4d0c23f69c8b5#r99215006)  on the PR that introduces a "base64" that suggests that "byte" is the good format but there was no corrections.

**Comment by handrews** [comment]
@hkosova @axlbonnet 

JSON Schema draft-07 (which would be relevant to OpenAPI 3.1 at the earliest, possibly 4.0, assuming OAI wants to adopt it at all) adds the `contentMediaType` and `contentEncoding` parameters for general support of encoding other forms of data in JSON strings.

These were formerly the `type` and `binaryEncoding` keywords within Hyper-Schema's `media` object, but we do not think JSON Schema users should have to adopt Hyper-Schema for this functionality (or `readOnly` or `writeOnly`, both of which are also now in the validation spec).

**Comment by pbryan** [comment]
Where does this leave interpreting "format"? Based on my reading of 3.0.1, it would seem right now that "byte" and "base64" would be synonyms.

**Comment by handrews** [comment]
@pbryan in the long run, `format` should not be used for this.  OpenAPI worked around deficiencies in JSON Schema, but I'm hoping we can drop the workarounds and converge on the existing unambiguous solution.

**Comment by pbryan** [comment]
Thanks @handrews.

**Comment by hkosova** [comment]
Closing in favor of #1547.

**Comment by mma5997** [comment]
Hi @hkosova,
we are using the 3.0.0 version currently. 
So please can you help me with this query ==> [comment](https://github.com/OAI/OpenAPI-Specification/issues/607#issuecomment-796257585)
