### ISSUE TITLE
Add HOCON as supported format

### ISSUE THREAD

**Issue by swamikevala** [OAI/OpenAPI-Specification#1314]
In addition to JSON and YAML we could also suggest [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md) (Human-Oriented Config) as a format for writing an openAPI document. IMO HOCON is a very nice middle-ground between JSON and YAML. 

Example:
```
"/contact" { 
    post {
      operationId: "createContact"
      requestBody.content.application/json {
        schema: ${schemas.contact} ${components.schemas.contact-readonly}
      }
      responses { 
        200.content.application/json.type: "integer" 
      }
    } 
    get { 
      operationId: "fetchContacts"
      parameters: [
        { 
          name: "ids", in: "query", required: true, style: "simple"
          schema { type: array, items.type: "integer" } 
        }
        { name: "auditData", in: "query", schema.type: "boolean" }
        { name: "systemMap", in: "query", schema.type: "boolean" }
      ] 
      responses { 
        200.content.application/json.schema { 
          type: "array", items: ${schemas.contact}  
        }
      }
    }
  }
```

**Comment by darrelmiller** [comment]
I don't expect the OpenAPI spec to officially adopt another format.  It already is hard enough maintaining both YAML and JSON examples in the spec.  However, there is no reason that tooling cannot accept additional serialization formats of OpenAPI.  I know Kevin Swiber has played around with using [HCL](https://www.terraform.io/docs/configuration/syntax.html) as an alternative format.

**Comment by handrews** [comment]
This was solidly answered in 2017, closing.
