### ISSUE TITLE
Enum value description

### ISSUE THREAD

**Issue by BabuGiri** [OAI/OpenAPI-Specification#1316]
is there any provision in describing enum value while defining enum in OAI schema format 

for example below status property can take values "available, pending or sold" which are defined through enum, i am looking for adding description for each of these values explaining more details about each option like when corresponding option can be used etc.  same cane be picked up by API documentation tools for better documentation
status:
        type: "string"
        description: "pet status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
Giri

**Comment by webron** [comment]
See #348.
