### ISSUE TITLE
Incorrect pipeDelimited style example

### ISSUE THREAD

**Issue by Leko** [OAI/OpenAPI-Specification#1317]
Hi there.
I found incorrect style example.

See `pipeDelimited ` in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-examples

### Actual
```
R|100|G|200
```

### Expected
```
R|100|G|200|B|150
```

**Comment by hkosova** [comment]
This was fixed in 3.0.3-dev:
https://github.com/OAI/OpenAPI-Specification/blob/v3.0.3-dev/versions/3.0.3.md#style-examples
