### ISSUE TITLE
Is there a way to indicate conditional interdependencies between object properties in a model?

### ISSUE THREAD

**Issue by nomadtechie** [OAI/OpenAPI-Specification#1321]
I have a use case where if the `type` property in my object is of value `A` then I another field in the object becomes required, and can only have a specific set of values which are associated with type A. 

Is there any way of noting this type of interdependency between fields in a model?

**Comment by handrews** [comment]
@nomadtechie Is this within a single Schema Object?  If so, you can do something like:
```JSON
{
    "oneOf": [
        {
            "properties": {
                "type": {"enum": [A]},
                ...
            },
            "required": ["otherProperties"]
        },
        {
            "properties": {
                "type": {"enum": [...]},
            }
        }
    ]
}
```

If you can give a bit more context I can give a more detailed example, but this shows the general idea.  `oneOf` can be made to work as a conditional.

In later drafts of JSON Schema there is an `if` keyword to make this more intuitive, so hopefully OpenAPI will eventually be able to support that.  But everything that `if` does can also already be done with `oneOf` once you get a feel for how i works.

**Comment by handrews** [comment]
Also, for purely JSON Schema questions, there is [a Slack channel available for support](https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg)

**Comment by nomadtechie** [comment]
thanks @handrews! That's pretty helpful.

**Comment by handrews** [comment]
@nomadtechie great!  If that answers the question if you could close this that would be lovely (or I'll flag @MikeRalphson to close it as I don't have the right permissions :-)

**Comment by kennyma-eplus** [comment]
```
{
	type: "object",
	propreties: {
		uiProfile: {
			type: "object",
			properties: {
				media: {
					type: "object"
				},
				copywriting: {
					type: "object",
					properties: {
						primary: {
							type: "object"
						}
					}
				},
			},
			status: {
				type: "string",
				enum: ["active", "inactive"]
			}
		}
	}
```

How to set the `uiProfile.copwriting.primary` to required only when `status` is `active`

**Comment by akindo** [comment]
It's described in the [Inheritance and Polymorphism](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) section of the OpenAPI documentation.
