### ISSUE TITLE
Does operationRef allow linking to external 2.0 definitions?

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1324]
In link definitions, `operationRef` can refer to an operation in an external OpenAPI definition:
```
operationRef: 'https://na2.gigantic-server.com/#/paths/~12.0~1repositories~1{username}/get'
```

Is the external OpenAPI definition supposed to be in the 3.0 format or can it be 2.0?

**Comment by handrews** [comment]
While working on OASComply the idea of 2<->3 links came up and was roundly rejected by everyone, plus this issue hasn't seen further discussion since 2017.  I think we can safely say no to major-version-crossing references :-)
