### ISSUE TITLE
Pbm "failed to fetch" when execute request in swagger UI (swagger 2.0)

### ISSUE THREAD

**Issue by rocchisanijl** [OAI/OpenAPI-Specification#1328]
Hello,
I encountered a problem when I execute my request (Get with bearer auth)  with try it function.
i've got status code 400 in the chrome console and a message from swagger Editor (v 3.1.4) "Undocumented | TypeError: Failed to fetch"
but when i execute curl cmd it works and same with postman.
it works as well in swagger ui console chrome extension but not in swagger UI (local install v 3.1.5).

I add header "Access-Control-Allow-Origin →*" but still not work!!!

see my screen shot
![pbm swagger 2 0](https://user-images.githubusercontent.com/27018079/29496042-a5ed3f62-85ca-11e7-9663-e83b60bc2d01.jpg)

my yaml here > [https://pastebin.com/raw/MNu8DcdV]

thanks for your help.

**Comment by darrelmiller** [comment]
You probably want to open this issue on the Swagger tooling repo e.g. https://github.com/swagger-api/swagger-editor   This is the just a repo for the OpenAPI specification.
