### ISSUE TITLE
How do we specify secrutiyschemes or credentials for callback url ?

### ISSUE THREAD

**Issue by Malligarjunan** [OAI/OpenAPI-Specification#1341]
How do we specify secrutiyschemes or credentials for callback url ?
Now that we could pass server b callback url in request. But how do we document or pass the callback url security schemes or defined for that security schemes? some way to specify security credentials like api key during runtime?   or  do we expect callback urls to be non-protected?

**Comment by darrelmiller** [comment]
Callback objects contain Path Item objects.  Path Item objects have Operation objects and those Operation objects can have Security objects in the same way regular operations do.

**Comment by Malligarjunan** [comment]
Thank you. one more followup question, i can pass the callbackurl as query or header variable values during runtime. how do i pass the credentials?

**Comment by darrelmiller** [comment]
During the registration of a callback you can place the callback URL anywhere in the request message.  If you also want to pass other information that will be used by the callback, that would need to be an implementation detail.  There is currently no way to describe that.  

Interestingly, what you are describing is a cross between a link and a callback.

**Comment by Malligarjunan** [comment]
Thanks.
