### ISSUE TITLE
Request body cannot define multiple schemas for one media type

### ISSUE THREAD

**Issue by gentlewind** [OAI/OpenAPI-Specification#1342]
In the **RequestBody** syntax, a request body can have multiple media types, and each can define a single schema.
```json
{
  "content": { 
    "application/json": {
      "schema": {
         "$ref": "#/components/schemas/Pet"
      },
      "examples": {
        "cat" : { }, "dog" : { }
      }
    },
    "application/xml": { }
  }
}
```
In real world REST APIs, we may have additional schemas for both _cat_ and _dog_. There is no way to put multiple schemas into a single **MediaType**, though we can workaround the examples.

**Comment by webron** [comment]
You can use `oneOf`/`anyOf` to specify multiple schemas.

**Comment by darrelmiller** [comment]
In addition to the solution Ron proposed, you can also use the profile media type parameter to qualify the media type as a hint to consumers what they are actually getting in the response.

```JSON
{
  "content": { 
    "application/json;profile=https://mycompany.com/myschemas/cat": {
      "schema": {
         "$ref": "#/components/schemas/cat"
      },
      "examples": {
        "cat" : { }
      },
    "application/json;profile=https://mycompany.com/myschemas/dog": {
      "schema": {
         "$ref": "#/components/schemas/dog"
      },
      "examples": {
        "dog" : { }
      }
    },
    "application/xml": { }
  }
}
```

**Comment by gentlewind** [comment]
Thanks you @webron and @darrelmiller for the answers. The profile media type parameter seems like a bit tricky, and is out scope of OAI spec. I prefer to use **oneOf** in the schema object.
```json
{
  "content": { 
    "application/json": {
      "schema": {
         "oneOf": [
           { "$ref": "#/components/schemas/Pet"}, 
           { "$ref": "#/components/schemas/dog" }, 
           { "$ref": "#/components/schemas/cat" }
         ]
      },
      "examples": {
        "cat" : { }, "dog" : { }
      }
    },
    "application/xml": { }
  }
}
```
