### ISSUE TITLE
Update Github site to include link to calendar for TDC meetings 

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1344]
Update Readme to include link to google calendar of meetings

**Comment by tedepstein** [comment]
Update readme to include the gcal link.

**Comment by darrelmiller** [comment]
@tedepstein  Apparently I can't add you as an assignee at the moment.  Consider yourself assigned :-)

**Comment by tedepstein** [comment]
> Consider yourself assigned :-)

OK, will do. 

@webron , can you give me the access level I need so I can have issues assigned to me?)
