### ISSUE TITLE
Finish JSON Schema work

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1348]

**Comment by handrews** [comment]
@darrelmiller @webron what's the scope of this?  Compatibility issues?  Moving to a newer draft? :-)

**Comment by MikeRalphson** [comment]
@handrews I believe this issue relates to completing the JSON Schema **instance** for the OpenAPI 3.0.0 specification, see #1032, #1301 and PRs #1236 and #1270 - not the use of (a subset/superset of) JSON Schema or a particular draft **in** the spec.

**Comment by handrews** [comment]
@MikeRalphson thanks!  That makes sense.

**Comment by handrews** [comment]
First PR on the WIP schema: #1744
