### ISSUE TITLE
path specific URL endpoint using server object url

### ISSUE THREAD

**Issue by jeevarajan** [OAI/OpenAPI-Specification#1356]
In below given example, i need to have customized url for the resource "user-enableuser". i thought in openapi 3.0.0, it can be achieved through server object for each path. Please let me know what i am missing here

```json
"paths": {
    "/user-enableuser": {
      "post": {
		"servers": [{
			"url": "https://x.x.x.x/user"
		}],
        "tags": [
          "user"
        ],
        "summary": " ",
        "operationId": "user@ENABLE",
        "produces": [
          "application/xml"
        ],
        "consumes": [
          "application/xml"
        ],
        "parameters": [
          {
            "schema": {},
            "description": " ",
            "name": "body",
            "required": true,
            "in": "body"
          }
        ],
        "responses": {}
      }
    }
```

**Comment by MikeRalphson** [comment]
What errors are you getting? Your example is a mix of v2.0 and v3.0.0 syntaxes. Both produces/consumes and in:body parameters have been removed.

**Comment by jeevarajan** [comment]
yes, i didnt update any other syntax from v2.0. I will update once i understand the path specific URL.

I didnt get any errors, but still seeing the default url. 

I want https://x.x.x.x/user, not https://x.x.x.x/user-enableuser

"openapi": "3.0.0",
....
"servers": [{
		"url": "https://x.x.x.x"
  }
  ],
......
"paths": {
"/user-enableuser": {
"post": {
"servers": [{
"url": "https://x.x.x.x/user"
}],
"tags": [
"user"
],

**Comment by MikeRalphson** [comment]
Sorry, I should also have asked which tooling are you using? Perhaps it doesn't support `servers` at the path or operation level yet?

**Comment by jeevarajan** [comment]
am trying this use case in swagger-ui-master. 
I referred section "Overriding Servers" in https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by MikeRalphson** [comment]
If you check [this issue](https://github.com/swagger-api/swagger-ui/issues/3641) on the [swagger-ui repository](https://github.com/swagger-api/swagger-ui) - you can see that this functionality is still in the backlog of work to be done:

>      Path and operation-level servers are not displayed

>    Use a UI similar to the top-level servers.
    Implement functionality for Try-It-Out simultaneously.

If you need further information, you should raise an issue on the repository for the tooling concerned, not the specification itself.

**Comment by jeevarajan** [comment]
What i am trying is, i want to send 
curl -X POST https://x.x.x.x/user 
for both the resources from the below given example

"paths": {
"/user-enableuser": {
..
},
"/user-disableuser":{
..
}

**Comment by MikeRalphson** [comment]
@jeevarajan I think from your snippets (apart from the mix of 2.0 and 3.0.0 syntax) you are doing it correctly, but the swagger-ui tool just doesn't support this yet.

**Comment by MikeRalphson** [comment]
The `path` is always appended to the `servers` values which are in context. Switching `servers` is not a great solution to having more than one `POST` operation per `path`.

An alternative (unless you are documenting an existing API) might be to have a `toggleUser` operation, which is passed a property or object containing the state to set the user to?

When `swagger-ui` supports multi-level servers it will be easier for you to visualise how various approaches will work for you.

**Comment by jeevarajan** [comment]
But i am documenting existing API which is having more than one POST operation per PATH :(
Any luck?

**Comment by MikeRalphson** [comment]
I think your best bet is to describe the `requestBody` as `oneOf` an array of schemas, as presumably the server disambiguates the operation required based on the content of the body, or some `query` or `header` parameter?

Alternatively, you could use differing `content-types` for the `requestBody`.

There is also this [proposal](https://github.com/OAI/OpenAPI-Specification/issues/791) which is marked for possible future consideration.

**Comment by jeevarajan** [comment]
Thanks a lot @MikeRalphson for the info. It is really helpful.

**Comment by kanai0618** [comment]
Hi @MikeRalphson , wanted to know one thing, i have url eg: **/internal/abc/** and in UI swagger i want to show **/abc** only. how do i do that ? whats the best possible way to do this ?
