### ISSUE TITLE
Documenting model metadata

### ISSUE THREAD

**Issue by ivan-novakov** [OAI/OpenAPI-Specification#136]
Are there any best practices how to document model metadata such as hyperlinks, context, documentation? For example if I use HAL, the typical resource looks like this:

``` json
{
  "_links": {
    "self": { "href": "/employees/123456" }
  },
  "employeeId": 123456,
  "firstName": "Ivan",
  "lastName": "Novakov",
  "email": "ivan.novakov@company.com"
}
```

Now such parts like the `_links` section may be defined in the model definition, but they are not actually part of the model and sometimes the structure may be more complex and (what is worse) repeating across the different models.

Maybe there could be some general support for metadata in the Swagger specs, because most of the current JSON format/specifications use some kind of metadata, see:
http://sookocheff.com/posts/2014-03-11-on-choosing-a-hypermedia-format/

**Comment by shamoons** [comment]
+1

**Comment by oytuntez** [comment]
One thing to note about this is probably overwriting model representations. As much as I am aware of, there isn't such thing. For example, "self" link would be different in different models and it would be amazing to specify this while linking to the model (path templating).

**Comment by earth2marsh** [comment]
@webron The docs on composition and inheritance polymorphism that @oytuntez mentions is well written and succinct, but if it were possible to give an example, I'd be better positioned to prove that I understand what it declares. :) Should I file a separate issue with that request?

**Comment by webron** [comment]
@earth2marsh - apologies for the delay. Are the examples provided not enough? https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#models-with-composition and https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#models-with-polymorphism-support? I'd be happy to add clearer examples if needed, and yes please open a separate issue on the matter.

**Comment by handrews** [comment]
No further response since 2015, closing.
