### ISSUE TITLE
Conditional value for parameters

### ISSUE THREAD

**Issue by starinfor** [OAI/OpenAPI-Specification#1363]
Is it possible to have conditional values ? For example: Suppose JSON has 2 parameters, Country and States. Based on what country is selected, states is populated. Assuming all data takes a server side call.

**Comment by lornajane** [comment]
This has been open for ages, and there's no support for inter-dependent parameters. A related (but not identical) issue is here https://github.com/OAI/OpenAPI-Specification/issues/256, but I'll close this one as it hasn't had much engagement over the years.

**Comment by karenetheridge** [comment]
query parameters can be defined by a single schema (which would allow conditional dependencies), but this is not possible for header or path parameters.
