### ISSUE TITLE
Issue with nested object examples.

### ISSUE THREAD

**Issue by Doyle-kun** [OAI/OpenAPI-Specification#1365]
Hi I have a problem with adding examples to nested objects. They are not rendering, no mater which method I'm using.
My structure:
```
   AuthenticationToken:
      type: object
      properties:
        accessToken:
          $ref: "#/components/schemas/JWTToken"
        refreshToken:
          $ref: "#/components/schemas/JWTToken"
```
  
    JWTToken:
       type: object
       properties:
        token:
         type: string

My example:
```
    RefreshJWTToken:
      value:
        token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE1MDY5Mjg4ODQsImV4cCI6MTUzODQ2NDg4NCwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSJ9.LmTf-0LqFGG6ZOACtA5JOEYh0Et9eNaXsyP2QCYchRQ
        name: JWT Refresh Token example
      summary: Sample refresh Token
```
My REST response:
```
responses:
        '200':
          description: "Access token refreshed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationToken"
              example:
                accessToken: null
                refreshToken: 
                   $ref: "#/components/examples/RefreshJWTToken"
```
What exactly I'm trying to get is renderable example for both access and refresh token. 
It should look like this:
```
{
  "accessToken": {
    "token": "extremely.long.string.containing.access.token"
  },
  "refreshToken": {
    "token": "little.shorter.string.containing.refresh.token"
  }
}
```

How can I properly add examples to accessToken and refreshToken objects?

Thanks for help,
Gregory

**Comment by MikeRalphson** [comment]
Is `$ref: "#components/examples/RefreshJWTToken"` just a typo above, or are you missing the / from `#/` in the reference?

**Comment by Doyle-kun** [comment]
Actually just a typo, I've spent a while to get this done and had to made mistake... But without typo it's still not working. :/

**Comment by shockey** [comment]
> They are not rendering, no mater which method I'm using.

You say it isn't rendering - are you using a tool to display your API definition?

**Comment by Doyle-kun** [comment]
Yes, I have docker image of Swagger Editor 3.1.8.

**Comment by shockey** [comment]
@Doyle-kun, OAS 3.0 `example`/`examples`is not implemented in Swagger-UI (which is what you see in the right-hand side of Swagger-Editor), see https://github.com/swagger-api/swagger-ui/issues/3641.

Also, please note that this repository is for the OpenAPI specification itself - the Swagger-UI and Swagger-Editor tools have their own issue trackers 😄

**Comment by webron** [comment]
Closing as it's a tooling-specific question. Please file a ticket with the respective project if needed.
