### ISSUE TITLE
Word Sensitivity

### ISSUE THREAD

**Issue by NavidHeydari** [OAI/OpenAPI-Specification#1369]
Hello, All -- couple weeks ago I noticed a limitation in code generator (server-side/Spring ) which it won't generate code for classes/type with name " resource" and I assume it will basically think this "resource" word is meant to be Spring ORG Resource object. it seems the Code generator for Spring is sensitive to word " Resource". Could you please take a look at it? the same swagger definition can be processed correctly in Java client-side code gen so I used that one and cleaned that up to make itsimilar to serverside format, which means to me this is a minor issue, but I noticed probably there is a room for improvement on that.

**Comment by webron** [comment]
This repository is for the specification itself. Please file the ticket at the project you're referring to.
