### ISSUE TITLE
Make schema an npm/bower module and publish is independently 

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#137]
I want to use Schema as a bower module in Swagger Editor. It makes it easier to update the schema. Please publish `schema.json` as a bower and npm module independent from validator and make that a dependency of validator.

**Comment by RobDolinMS** [comment]
@mohsen1 It looks like this hasn't been touched since 2014.  Can it be closed?

**Comment by whitlockjc** [comment]
I think it's a great idea honestly, to support Bower/NPM builds of the official schema.  There use to be a module like this but I can't seem to find it.

**Comment by MikeRalphson** [comment]
@whitlockjc there is [this outdated package](https://www.npmjs.com/package/swagger-schema-official) but it suffers from the limitation that it is not possible to have a dependency on more than one version of the package, i.e. for the v1.2 and v2.0 schemas. Resulting in [this workaround](https://github.com/mohsen1/swagger-1.2-schema) from @mohsen1 himself.

I would prefer one package containing all (soon to be three) schemas with its own semantic version number, or separate official packages for each swagger/OpenAPI version. It would be ideal if schema changes [automatically got published to npm](https://docs.travis-ci.com/user/deployment/npm/) as part of a successful travis build.

**Comment by handrews** [comment]
This is asking for a subset of #2400, which has a detailed checklist and a linked PR.  So let's just track it there - no need for two open issues.
