### ISSUE TITLE
Security controls in OpenAPI specs

### ISSUE THREAD

**Issue by BK01** [OAI/OpenAPI-Specification#1370]
Is there any documentation or updates on how to describe different security controls within the same OpenAPI spec (json) for different resources. A more defined security model to include the resource and method level would be helpful.

We encountered this in the past as well with GET vs. POST secure.

**Comment by MikeRalphson** [comment]
You can apply securityScheme requirements at the operation level, just as you could with OpenAPI 2.0.

See [here](https://swagger.io/docs/specification/authentication/) for an example - scroll down to **Step 2. Applying security**.

Please let us know if that does not answer your question, and apologies for the delay in getting back to you.

**Comment by handrews** [comment]
Answered in 2017 with no further responses, closing.
