### ISSUE TITLE
Is OAS a safe acronym for OpenAPI Spec?

### ISSUE THREAD

**Issue by msiddiqi** [OAI/OpenAPI-Specification#1371]
Should we call OpenAPI Spec as OAS, as Organization of American States also uses the same acronym?

http://www.oas.org/en/
https://twitter.com/OAS_official

This conflict also causes issues with searching it on google or twitter. Even #OAS (hashtag) has been collectively used by people to refer to both.

https://twitter.com/search?src=typd&q=%23OAS

Thanks,
Muhammad

**Comment by webron** [comment]
Yes. And the OAI is also https://www.openarchives.org. A lot of acronyms have multiple meanings, sometimes even the same field.
