### ISSUE TITLE
Unknown security handler: apikey

### ISSUE THREAD

**Issue by praveen4554** [OAI/OpenAPI-Specification#1372]
can any one guide me in which file i need to add security definitions i am using swagger 2.0 and sails 0.12 added security definitions in Header it throws error like unknown security handler

**Comment by darrelmiller** [comment]
I'm not aware of what sails 0.12 to is.  However, if you show your OpenAPI description, we can help you verify its validity

**Comment by MikeRalphson** [comment]
No answer, came the stern reply.
