### ISSUE TITLE
Unable to add multiple operations on same path in swagger rest API documentation

### ISSUE THREAD

**Issue by saranyavinayagam** [OAI/OpenAPI-Specification#1378]
I have a scenario where different operations like update, delete and create on same resource/same endpoint has to be performed. The operation would vary by having different incoming request attributes on same resource. But swagger is throwing error if i try to add more than one body request.

Is this the limitation of swagger 2.0. If so, is there any workaround for this issue? Please give your inputs if anybody have faced this issue. Suggestions are most welcome.

**Comment by ralfhandl** [comment]
This is a limitation of Swagger 2.0.

With OpenAPI 3.0.0 you can use `anyOf` to allow alternative (JSON) request bodies for the same resource and HTTP verb.

**Comment by MikeRalphson** [comment]
Closing as above.
