### ISSUE TITLE
OperationFilter help

### ISSUE THREAD

**Issue by MontyGvMC** [OAI/OpenAPI-Specification#1379]
Hi there.

Since there seems to be a problem with Swagger UI automatically displaying model classes of kind (I)Dictionary<string, string> or ModelStateDictionary (used as the result for Bad Request) I am trying to write an OperationFilter which helps the UI to display correct values.

So, whenever the code has
[ProducesResponseType(typeof(ModelStateDictionary), (int)HttpStatusCode.BadRequest)]

the OperationFilter if the operation has a response code 404 and check if type is ModelStateDictionary it should add correct models and examples.

My question: is it possible?

I tried it on my own but all I was able to check if operation.Responses.Keys.Contains("404") and then I got stuck?

Anyone knows how to implement that OperationFilter or some parts of it?
- checking if response type is ModelStateDictionary
- setting new model
- adding examples

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. Thanks.

**Comment by MontyGvMC** [comment]
Sorry, somehow landed in the wrong respository.
