### ISSUE TITLE
Structure definition in requestBody every time?

### ISSUE THREAD

**Issue by MoYummy** [OAI/OpenAPI-Specification#1380]
Suppose I have a request with multiple request body parameters

    POST /path/to/api/@action

    {
      "paramA": {...} // might be an object
      "paramB": {...} // might be another object
    }

For this, I have to define a data structure and set in ```requestBody```

    ActionStruct {
      paramA: SomeObject,
      paramB: AnotherObject
    }

For every request like this, do I have to define a request body structure each (maybe paramC or paramD in other requests)?
In previous version, I just need to add entry in ```parameters``` stated ```"in": "body"```

**Comment by MikeRalphson** [comment]
The short answer is yes, the longer answer is you can re-use entire requestBodies using `$refs` to `components/requestBodies` and create composite requestBodies (e.g. if you mix your `ParamA`, `ParamB`, `ParamC` and `ParamD`) using `$ref`s to schemas under `components/schemas`.

See the examples at https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

Apologies for the delay in you receiving a reply.

**Comment by MoYummy** [comment]
thx
