### ISSUE TITLE
Generate 3.0 JSON examples from 3.0 YAML examples in json/yaml subfolders

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1385]

**Comment by MikeRalphson** [comment]
Refs #1357

**Comment by darrelmiller** [comment]
Yes, I should have mentioned that the PR referenced inspired this decision.  We don't want to add maintenance burden by having both formats, but we can generate them.

**Comment by cebe** [comment]
What kind of tooling would you accept into the repo? Is there any preference for language/toolchain to use?

With PHP installed, the following `Makefile` would generate JSON files from all YAML files in a directory:

```make


YAMLS := $(wildcard ./*.yaml)
JSONS := $(patsubst ./%.yaml, ./%.json, $(YAMLS))

all: vendor/bin/php-openapi $(JSONS)

vendor/bin/php-openapi:
	echo '{}' > composer.json
	composer require cebe/php-openapi 'symfony/yaml:~4.2.0'

%.json: %.yaml
	vendor/bin/php-openapi convert --read-yaml $< --write-json $@

.PHONY: all

```

If PHP is an acceptable tooling, I can send a PR with setting it up.

**Comment by SephReed** [comment]
I'd put in a request for this too.  It's not like it's hard to convert on ones own, but I was just looking for some quick test data.  Even just one json example would have been enough to save me the trouble of converting it myself.

https://onlineyamltools.com/convert-yaml-to-json

**Comment by MikeRalphson** [comment]
Closing as #2199 was merged. Thanks all.
