### ISSUE TITLE
Which meta-meta model is the OpenAPI specification built on?

### ISSUE THREAD

**Issue by reisi007** [OAI/OpenAPI-Specification#1390]
Hi,

Just researching for a university presentation and could not find the meta-model the OpenAPI specification is built on. I am relatively sure that JSON / YAML is not the correct answer as  for me these would be the platform specific models. The specification as in the Markdown file here on Github is for me the platform independent model.
So any clue which meta-meta model is used to create the description of the specification?

**Comment by darrelmiller** [comment]
The meta model is not formalized.  It consists mainly of maps, lists, strings, bool, urls, and the notion of Any.

**Comment by ralfhandl** [comment]
I wouldn't be that pessimistic: the subsections of section "Schema" pretty much describe the entity types of the meta-model, and the "Fixed Fields" table in each subsection lists the attributes and relationships of the corresponding entity type.

Btw: good job! I like the consistent structure and concise wording of the 3.0.0 specification.
