### ISSUE TITLE
Free-form query parameters does not seem to work according to spec

### ISSUE THREAD

**Issue by rbjorklin** [OAI/OpenAPI-Specification#1394]
Looking at the [style examples](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-examples) in the spec my understanding is that a free-form query parameter as described in the [parameter object examples](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object-examples) should produce a query string from a json object.

Meaning that `{ "R": 100, "G": 200, "B": 150 }` should be turned into `R=100&G=200&B=150` but this does not seem to be the case. Have I misunderstood how this is supposed to work or is it a bug?

**Comment by MikeRalphson** [comment]
`style: form` **with** `explode: true` will give you `R=100&G=200&B=150` according the examples. When you say 'bug', which tooling are you referring to? This repo is for the specification itself only.

**Comment by rbjorklin** [comment]
Sorry I meant to report this under Swagger-UI! Closing and re-opening under the correct project!
