### ISSUE TITLE
Allow optional Authorizations

### ISSUE THREAD

**Issue by jacobweber** [OAI/OpenAPI-Specification#14]
This is an enhancement request, to allow optional authorizations. Not sure if this would be useful for others, but it would be for me.

In my case, you can access my APIs with no authorization, with OAuth, or with a set of two API keys. Depending on which you use, I may give you access to different data, but you still use the same APIs.

One way to handle this would be to allow a "required" boolean for each authorization in the API's [Authorizations object](https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md#5210-authorizations-object).

If you did this, I could mark both of my oauth2 and apiKey authorizations as optional, which would allow you to select either or none of them. (It would also allow you to select both, but that's not really a problem.)

My case is also complicated by the fact that I need [two parameters](https://support.3scale.net/howtos/api-configuration/authentication-patterns) for my API key. If you wanted to treat this as a single Authorization, you'd have to allow multiple keynames for an apiKey. You could also treat it as two separate Authorizations, and just make them both optional. That's not ideal, since it wouldn't give you a way to indicate that they go together, but it would work.

**Comment by webron** [comment]
This is an old ticket, and I believe the samples have been added to the spec.

**Comment by rkarodia** [comment]
I still can't find an example of a **"no security"** option. Something like the `{"none": []}` example proposed by @wking

**Comment by mikestead** [comment]
@webron Also in need of a `none` security definition so when a token isn't provided responses are restricted to public content. Otherwise I need two endpoints for pretty much the same thing.

Should I raise a new ticket for this?

**Comment by webron** [comment]
@mikestead yup

**Comment by janjilek** [comment]
I had the same issue, so i did little hack. I have security definition called optionalBearer:

**Comment by rorisme** [comment]
+1 Also in need of `none` security definition. @mikestead would you please copy a reference to the new ticket here when you create it?

**Comment by elzii** [comment]
Was this functionality ever added? The ability to do as @rkarodia and @mikestead described with **"no security"** defaulting to public content is very needed

**Comment by rompic** [comment]
same question here :)

**Comment by webron** [comment]
Everyone, you don't need a `none` definition. The following has the same effect:

```json
"security": [
  {},
  {"oauth": […]},
  {"token-1": []},
  {"token-2": []}
]
```

**Comment by rompic** [comment]
Thx for the fast feedback. Will look into It.

**Comment by iongion** [comment]
But the swagger validator says the spec is not valid anymore ?
How do you solve this in the end ?

**Comment by webron** [comment]
@iongion if it says it's invalid, then file a ticket on that project.

**Comment by BGehrels** [comment]
Has this feature been somehow lost in 3.0?

**Comment by darrelmiller** [comment]
@BGehrels I am not aware of any conversations in the work on the V3 spec to change this behavior.  I don't think this option was very clearly spelled out in the V2 spec and we didn't do a better job in the V3 spec.  We definitely should fix that.

**Comment by BGehrels** [comment]
Since this issue targets 2.0 and is closed, should i open a seperate issue for that?
This issue is one of the first hits when one searches for "openapi optional auth", so it may be a good idea to leave a hint here how to accomplish this in the meantime. I would do it, but i still have no idea :-)

**Comment by JohannesKuehnel** [comment]
In case someone is needing optional authorization for Swagger 2.0 and YAML files, this format worked for me: `security: [ {}, JwtAuth: []]` (where `JwtAuth` is in my `securityDefinitions`).

I tried several other variants but this was the only one that worked with [`swagger-codegen-cli`](https://github.com/swagger-api/swagger-codegen) (Java okhttp-gson), `[swagger-express-middleware](https://github.com/APIDevTools/swagger-express-middleware)` for Node.js and validation with [`swagger-cli`](https://github.com/APIDevTools/swagger-cli).

**Comment by jpincz** [comment]
This works for me on version 3 with express node js

Added this on .yaml file:

security:
  - ApiKey: ['someScope']
  - {}

So the endpoint defined by that file accepts both ApiKey (defined on my security schema file) or non-authenticated requests

**Comment by musjj** [comment]
Adding an empty `{}` doesn't seem to work for me.

Nothing changes in the Swagger UI. It still lists all the security schemes, with no indication that it's optional. Am I doing anything wrong here?

This is the schema I tried (with the [swagger editor](https://editor-next.swagger.io)):

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Example API",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "https://example.com/api"
    }
  ],
  "paths": {
    "/foo": {
      "get": {
        "responses": {
          "200": {
            "description": "foo"
          }
        },
        "security": [
          {},
          {
            "cookie": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "cookie": {
        "type": "apiKey",
        "name": "api_cookie",
        "in": "cookie"
      }
    }
  }
}
```

**Comment by handrews** [comment]
@musjj Please raise issues with your tooling vendor if they do not support the specification correctly.  This is an old issue, and this repository is about the specification, not individual tools.
