### ISSUE TITLE
[v2.0 Question] Can `type` property in Schema Object be optional or not?

### ISSUE THREAD

**Issue by taxpon** [OAI/OpenAPI-Specification#1401]
### Question
Can `type` property in Schema Object be optional or not?

### Detail
I read though the [OpenAPI v2 Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md) and [Json Schema document](http://json-schema.org/latest/json-schema-core.html) and I couldn't find the description that means `type` property in Schema Object can be optional. 

But some examples in this repo do not have `type` property in Schema Object,  so I was confused a little. (For example [petstore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore.yaml) and [uber.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/uber.yaml))

Is definition of `type` prop in Schema Object not required and if the definition is skipped, does it mean that the schema has`type: object` implicitly? I'd like to know this information from third party tools developer point of view.

**Comment by taxpon** [comment]
@webron Thanks for your detail explanation 👍  I understood the specification clearly.

My concern: 
The information you mentioned is not documented as far as I know. I think it should be described in OpenAPI Spec so that people like me will not have to ask the similar question here although the question may be not popular.

What do you say?

**Comment by handrews** [comment]
@taxpon this behavior of `type` is documented as part of JSON Schema.  AFAIK OpenAPI just documents the differences between regular JSON Schema and the usage of JSON Schema within OpenAPI (such as forbidding the array form of `type` and forbidding type `"null"`).

There is [a section specifically documenting the lack of type inference](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-4.1).  That link goes to the JSON Schema version referenced by OpenAPI 3.0.  While some details have changed in subsequent versions as we have clarified concepts, the essential point remains the same.

**Comment by taxpon** [comment]
@handrews Oh, I see. You are correct. Thanks!
