### ISSUE TITLE
Print the swagger API webpage

### ISSUE THREAD

**Issue by richardzembron** [OAI/OpenAPI-Specification#1407]
When printing the Swagger API webpage, the output is more or less an empty page.

<img width="631" alt="skarmavbild 2017-11-10 kl 17 56 32" src="https://user-images.githubusercontent.com/24635468/32669479-feff4828-c640-11e7-8882-be37f95cfdb1.png">

**Comment by darrelmiller** [comment]
This is an issue that should be raised on the [Swagger UI](https://github.com/swagger-api/swagger-ui) repo.  This repo is just for the specification.
