### ISSUE TITLE
Support for markdown table in OAS 3.0 

### ISSUE THREAD

**Issue by JoeScho** [OAI/OpenAPI-Specification#1413]
In previous versions of swagger it was possible to add tables such as:

| Example | Table |
| ------:|:-----------:|
| This   | Is an example table |
| I | Would love to see them in v3.0 |
| If | This is already possible then please tell me I'm being stupid |

Running the following in [the Swagger editor](http://editor.swagger.io/) produces different results:
### this one works
```
openapi: 2.0.0
info:
  description: |
    Example | Table
    ----------------|-------------
    This | Is an example table 
    I | Would love to see them in v3.0
    If | This is already possible then please tell me I'm being stupid
```
### this one doesn't work
```
openapi: 3.0.0
info:
  description: |
    Example | Table
    ----------------|-------------
    This | Is an example table 
    I | Would love to see them in v3.0
    If | This is already possible then please tell me I'm being stupid
```
It would be great to have the feature brought across into OAS 3.0

Thanks!

**Comment by MikeRalphson** [comment]
I believe this is a related issue https://github.com/swagger-api/swagger-ui/issues/2745

OpenAPI 3.0 supports "at a minimum" commonMark 0.27 for markdown, and [tables are not part of commonMark 0.27](https://talk.commonmark.org/t/tables-in-pure-markdown/81). It is not 100% clear if "at a minimum" relates to the commonMark version, or any superset of commonMark 0.27.

Swagger/OpenAPI 2.0 supported GitHub-flavoured-markdown (gfm) which does support the pipe table syntax.

Depending on your specific tooling, you may need to use html `<table>` tags for OpenAPI 3.0 definitions.

**Comment by JoeScho** [comment]
Ok great, thanks! 👍 

I'll probably just use a list for now but I'll keep my eyes peeled for any updates. I'll close this issue.

**Comment by adnnor** [comment]
Hey @JoeScho, after quite some time I have noticed that in the API global description, top of the document, under info, the GitHub flavoured table is still not working but it is working under path > [http method] > description. Although I have used HTML table under info > description, I want to know whether it could be work in the same way as others are working?

**Comment by gervaisb** [comment]
I noticed that it works everywhere when the multiline indicator is `|-` while it does not with `>`.

openapi: "3.0.0"
