### ISSUE TITLE
Can not ref object in different yaml file.

### ISSUE THREAD

**Issue by i341534** [OAI/OpenAPI-Specification#1420]
Hi ,
    I have three yaml file ,one named api-description.yaml ,one named paramters.yaml ,and one named paths.yaml . In paths.yaml ,I can not reference entity defined in api-description.yaml, my reference is 🥇  $ref: '../api-description.yaml#/components/responses/Created'
But the swagger can only find $ref: '../api-description.yaml#/components ,How can I solve this?

**Comment by webron** [comment]
Please file tool-specific issues with their respective project. This repository is about the spec itself.
