### ISSUE TITLE
Explain the term "schema" in definition section

### ISSUE THREAD

**Issue by agnat** [OAI/OpenAPI-Specification#1423]
The term _schema_ pops up first in the format section of the specification. Since it is such a central term, I feel it should be explained in the definition section.

**Comment by MikeRalphson** [comment]
Belated thanks for bringing this up. A PR with candidate wording would be gratefully received.

**Comment by ralfhandl** [comment]
Fixed in 3.0.4 and 3.1.1: @handrews can we close this?

**Comment by handrews** [comment]
@ralfhandl yes, I thought I'd gone through and closed everything - I'll double-check.
