### ISSUE TITLE
Purpose of "servers"?

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#1431]
In #1421 @webron said:

> We don't really recommend using the servers to describe different environments (such as prod, dev, staging and so on), especially for public facing APIs. You're pretty much exposing your environments to all your users.

I also misinterpreted this due to the spec showing an example with dev/staging/prod servers.  What is the intended use, and can we change the example to suggest it more clearly?  I'm happy to take a shot at writing up a PR if that would help.

**Comment by stevendearborn** [comment]
I think that both are correct since it depends on who will be using the API documentation to try out the APIs.

What is stated make much sense for public-facing APIs.

It is possible to create two JSON documents: one for internal use-only and the other public, each pulling in the same API references via JSON Reference. The difference, namely the server definitions, can reside within the document.

**Comment by handrews** [comment]
@stevendearborn I guess my concern isn't so much eradicating this as a use case, but making the documentation a bit more clear that there is at least one other intended use (that I'm not able to figure out right now, hence this issue).  This could be done with an extra sentence, a different example, etc.

**Comment by webron** [comment]
Thanks @handrews, that's a fair point. As you can imagine, I don't like the example in the spec. 

Using `servers` to describe multiple environments isn't *wrong*, it's just *not recommended*.  You can use it to specify different geo-locations of servers for example (even though using variables might be more suitable for that).

**Comment by younss** [comment]
is this a duplication of [https://github.com/OAI/OpenAPI-Specification/issues/1421](https://github.com/OAI/OpenAPI-Specification/issues/1421) ?

**Comment by handrews** [comment]
@younss I filed it separately because it seemed tangential to #1421 at best.  But that issue did motivate this one.

**Comment by darrelmiller** [comment]
You can use servers for things like:
  - sandbox vs production
  - Optional sub-domains. e.g. "api.mydomain.com" and "mydomain.com"
  - Cloud hosting assigned names and custom domains. e.g. "mysite.azurewebsites.com" and "mycustomdomain.com"

The important thing is that OpenAPI description for all the servers is the same.

**Comment by MikeRalphson** [comment]
Another potential differentiator between servers is mentioned in #997 - though it got more tumbleweed than traction.

**Comment by ioggstream** [comment]
We are using `servers` to publish different *public environments* for the same specification (sandbox, test, prod, ..).

I think it should just be clear that implementation or private informations shouldn't be made public.

**Comment by handrews** [comment]
Closing this as I was the original reporter.  I don't think there's anything that needs doing here.
