### ISSUE TITLE
Type property for long data type is invalid and incompatible with swagger spec generated from proto3 sources

### ISSUE THREAD

**Issue by evanmcclure** [OAI/OpenAPI-Specification#1439]
The type property of the `long` data type is invalid. In the spec, `long` requires `type=integer`, but the proto3 swagger spec generator produces `type=string`.

**References:**
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types
https://developers.google.com/protocol-buffers/docs/proto3#json

**Proposed solution:**
Change the spec to accept `type=string`.

**Comment by handrews** [comment]
If this is still a concern, it needs to be raised with the Swagger generator tool.
