### ISSUE TITLE
Broken calendar link & empty schedule in Readme

### ISSUE THREAD

**Issue by tedepstein** [OAI/OpenAPI-Specification#1440]
The link to the TDC meeting calendar on the [home page](https://github.com/OAI/OpenAPI-Specification) goes to:
https://oai-technicalsteeringcommittee.groups.io/g/main/calendar
... but that bounces here:
https://oai-technicalsteeringcommittee.groups.io/g/main
With an overlaid error message saying "You are not subscribed to this group."

Also, we have provided a link to the  TDC/TSC meeting schedule in [iCal format](https://oai-technicalsteeringcommittee.groups.io/g/main/ics/860119/668774333/feed.ics), but the most recent meeting on that calendar is from August 2017.

**Comment by namdeirf** [comment]
Thanks @tedepstein We are migrating the list to https://openapi.groups.io/g/tsc/. This will allow OAI members to join a single master group and quickly join multiple groups.


New ical is here ...
https://openapi.groups.io/g/tsc/ics/0/875151966/feed.ics

**Comment by miqui** [comment]
@darrelmiller @namdeirf this - https://openapi.groups.io/g/tsc/ics/0/875151966/feed.ics   is broken, any chance i can get this so, i can join the meetings? -  thanks...

**Comment by darrelmiller** [comment]
The meeting link is here in the Agenda issue https://github.com/OAI/OpenAPI-Specification/issues/2118

**Comment by ncaidin** [comment]
@MikeRalphson , what action are you requesting for me to take on this issue? 
Thanks.

**Comment by MikeRalphson** [comment]
Again, previously assigned to Jeff. Please close if the calendar link is correct now.

**Comment by ncaidin** [comment]
Hi @miqui .  I am closing this issue, but if you still think there is a problem, please contact me and we will work through it. Thanks!
