### ISSUE TITLE
The description `Invalid Input` of 405 Responses Object is ambiguous  and leads to misunderstanding

### ISSUE THREAD

**Issue by weimengxi** [OAI/OpenAPI-Specification#1449]
As the document says, [the key of a responses object's Patterned Fields ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#patterned-fields-1) is  Http Status Code . 

and the document gives  responses object examples  like this at following part.

```
  "responses": {
    "405": {
      "description": "Invalid input",
      "content": {
        "application/json": {},
        "application/xml": {}
      }
    }
  }
```

As it defined in [ rfc7231 Specification](https://tools.ietf.org/html/rfc7231#section-6.5.5) , 405 indicates `Method Not Allowed` rather than `Invalid Input` .   

>  The 405 (Method Not Allowed) status code indicates that the method
   received in the request-line is known by the origin server but not
   supported by the target resource.  

I think we'd better follow the [ rfc7231 Specification](https://tools.ietf.org/html/rfc7231#section-6.5.5) 's definition

**Comment by weimengxi** [comment]
#1450

**Comment by MikeRalphson** [comment]
#1486 has been merged, many thanks again.
