### ISSUE TITLE
How to generate OpenAPI specification models from XML examples?

### ISSUE THREAD

**Issue by jnazander** [OAI/OpenAPI-Specification#1451]
Suppose I have some API endpoints, written in PHP on server-side, that return XML data. I want to create an OpenAPI specification for them.

Now, I could go and write the entire specification by myself, but since we're developers here and not manual laborers, we should never do anything manually that could be automated.

I know that there is "Swagger Inspector" that claims to generate the specifications by taking a specific endpoint URL, but it _only_ generates the request definition, _not_ the response data model. I'm not sure if that's a bug or just not implemented, but this is unacceptable for me.

So, is there _any_ tool that could generate the response data models within Swagger by taking XML data for example? I know that there are tools that convert XML to XSD, so I don't see why doing the same for XML -> Swagger definition would be a problem.

**Comment by jnazander** [comment]
I found _one_ tool that attempts to do that - https://github.com/mszostok/swagger-converter - but it seems abandoned and it's made to convert an entire WADL+XSD specification to Swagger, not just the data models.

**Comment by Bsplesk** [comment]
also loking for tool that allows convert "XSD object model"  to "swagger definitions model". 
Now I use XSLT, written by hand.

**Comment by javiqm12** [comment]
It would be good to have something like that.

**Comment by handrews** [comment]
This repository is for the spec rather than for new tools, so I'm closing this issue - we have a tools repository that maintains a list of tools you might want to check (see tools.openapis.org)
