### ISSUE TITLE
Link to Multiple Items of Array

### ISSUE THREAD

**Issue by tgockel** [OAI/OpenAPI-Specification#1452]
There is an API with two operations:

* `GET /foo/{fooId}`: Get some object, given its ID.
* `POST /foo`: Create _multiple_ objects and return an array of IDs for the newly-created objects.

The OpenAPI specification of this is:

    openapi: "3.0.1"
    
    info:
      description: Foo all the way!
      version: "1.0"
      title: "Foo API"
    
    paths:
      /foo/{fooId}:
        get:
          operationId: getFoo
          parameters:
            - name: fooId
              in: path
              required: true
              schema:
                type: integer
          responses:
            200:
              description: Got the Foo.
              content:
                'application/json':
                  schema:
                    type: object
                    properties:
                      fooId:
                        type: integer
                      name:
                        type: string
      /foo:
        post:
          operationId: createFoos
          description: "Create some Foos"
          requestBody:
            content:
              'application/json':
                schema:
                  type: array
                  items:
                    type: string
          responses:
            201:
              description: Created the Foos.
              content:
                'application/json':
                  schema:
                    type: object
                    properties:
                      fooIds:
                        type: array
                        items:
                          type: integer
              links:
                getFoo:
                  operationId: getFoo
                  parameters:
                    fooId:
                      '$response.body#/fooIds'

The problem is the `links` specification of the `createFoos` operation is wrong. As specified, a response to `POST /foo` of:

    {
      "fooIds": [1, 2, 3]
    }

implies the proper way to fetch the created objects would be to `GET /foo/[1,2,3]`, which is quite incorrect. I would like to inform this system that the _contents_ of the array are the linked operation, not the array itself. The is no mechanism to do this in OpenAPI, as [JSON Pointers](https://tools.ietf.org/html/rfc6901) do not appear to support doing what I want here (it is meant to point to a single object rather than a pattern of objects).

---

Not to be too prescriptive, since I'm only a user of OpenAPI, but [JSONPath](http://jsonpath.com/) is intended for this sort of thing. The equivalent specification would be `'$response.body#$.fooIds[*]'`. That said, there's no obvious way to make the switch without breaking compatibility :-(

**Comment by MikeRalphson** [comment]
See also #1327

**Comment by tgockel** [comment]
Ah yes -- that _is_ definitely the same underlying issue. Closing this due to it's redundancy.
