### ISSUE TITLE
Update README file with new iCal info

### ISSUE THREAD

**Issue by namdeirf** [OAI/OpenAPI-Specification#1455]
Change the links in the below line from https://github.com/OAI/OpenAPI-Specification/blob/master/README.md

> You can view the **TSC calendar online**, and import it to your calendar using the **iCal link.**

- TSC calendar online | https://openapi.groups.io/g/tsc/

- iCal link | https://openapi.groups.io/g/tsc/ics/0/875151966/feed.ics

**Comment by darrelmiller** [comment]
Done.
