### ISSUE TITLE
Can you provide a full petsore.yaml with openapi: "3.0.0" spec

### ISSUE THREAD

**Issue by computrade** [OAI/OpenAPI-Specification#1468]
Hi,

I can see some example [here](https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0) but they are incomplete.

It can be very useful to have the classic petstore sample with all the new spec implemented.

Thanks,
Yuval Ishay

**Comment by MikeRalphson** [comment]
@computrade thanks for the reminder, this is in progress and we'll get back to you when it's available.

**Comment by handrews** [comment]
There's now a "petstore expanded" example in the examples directory, so I'm assuming it's just that no one realized they should close this old issue.  Closing now, please comment if I'm missing something that needs doing here.
