### ISSUE TITLE
Paths > Responses > Schema > Define hierarchy of objects?

### ISSUE THREAD

**Issue by AlephZedi** [OAI/OpenAPI-Specification#1470]
Hi everyone, 

I'm in a pickle... 

I need to define an API working backwards; meaning, the API is already being used in-house but it was created **without** a specification file (I know... I joined late). Is it possible to define something like this under paths > responses > schema? Each level is an object and no object is guaranteed to be nested under the parent object; for example, Flight will only have an Image if an image is available in the database...

![image](https://user-images.githubusercontent.com/35743751/35536568-47e352b0-0515-11e8-8e19-8ecb27214556.png)

Any help will be greatly appreciated!

Regardless, thanks :)

**Comment by MikeRalphson** [comment]
This issue has just been flagged up for me by [CodeTriage](https://codetriage.com), I'm very sorry your question went unanswered.

*Presumably* you're not still waiting on an answer on this, so I'll close it now, but feel free to chase if you need to.
