### ISSUE TITLE
Type keyword has not been correctly parsed by editor if used as a property attribute in a definition in the field "additionalProperties" 

### ISSUE THREAD

**Issue by matterove** [OAI/OpenAPI-Specification#1476]
This should be a problem only in the editor validation because the client is correctly generated

In attachement you can find an example of the issue
[TypeBugExample1.txt](https://github.com/OAI/OpenAPI-Specification/files/1694977/TypeBugExample1.txt)

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. Thanks.
