### ISSUE TITLE
What is the "Default" drop down in the Swagger UI preview?

### ISSUE THREAD

**Issue by CameronGo** [OAI/OpenAPI-Specification#1478]
I'm trying to understand what this section of the rendered OpenAPI document refers to?  Once I've drafted some of the resource descriptions, there's a twist down called Default under which the resources are listed.  What does this title Default refer to?

I looked at the rendered HTML and see this:
```
<div class="opblock-tag-section is-open"><h4 class="opblock-tag no-desc" id="operations-tag-default"><a class="nostyle" href="#/default"><span>default</span></a><div></div>
```
I'd like to know what this means so I can look at renaming it.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/14074983/35839442-6e39bdf6-0abe-11e8-81d0-131ee6ceeb67.png)

**Comment by MikeRalphson** [comment]
swagger-ui groups operations by tag, if you don't have any tags defined, it will use the Default label.

**Comment by CameronGo** [comment]
Thanks that is exactly what I was trying to figure out!
