### ISSUE TITLE
Why "body" is not the possible value for the location of the parameter in v3.0.1?

### ISSUE THREAD

**Issue by AdamsLee** [OAI/OpenAPI-Specification#1484]
v3.0.1:
in	string	REQUIRED. The location of the parameter. Possible values are "query", "header", "path" or "cookie".

v2.0
in	string	Required. The location of the parameter. Possible values are "query", "header", "path", "formData" or "body".

Why "body" is not the possible value for the location of the parameter in v3.0.1?

**Comment by MikeRalphson** [comment]
Both "in:body" and "in:formData" parameters have been replaced by the [requestBody object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#requestBodyObject)
