### ISSUE TITLE
Allow session cookie auth

### ISSUE THREAD

**Issue by ajtowns** [OAI/OpenAPI-Specification#15]
Session cookies are one method of authentication available in Jira. See: https://docs.atlassian.com/jira/REST/6.2/#d2e4887

The process is that you visit a URL authenticating via some other method, and the response includes cookies that serve as your authentication for ongoing access.

A new Authorization Object type in 5.1.5 of "cookie" or "session-key" could work here, with "keyname" being required and specifying the cookie id used, and "login-url" giving a pointer to the API endpoint that needs to be accessed to set the cookie?

**Comment by retrospectacus** [comment]
Putting your cookie in the header can be done by giving your securityDefinition name "Cookie" and its actual name goes in the data. It does not yet fully work (see issue 305) and of course you must obtain the cookie elsewhere...so   +1

**Comment by BigstickCarpet** [comment]
@retrospectacus - The problem with `{type: "apiKey", in: "header", name: "cookie"}` is that there's no way to specify _which_ cookie is the API key.   The `Cookie` HTTP header can contain _many_ cookies, and a typical HTTP request will include cookies for all sorts of things - ad trackers, Google analytics, session cookies, etc.   So it's not sufficient to say that my API requires _any_ cookie.  I need to be able to say that I require a _specific_ cookie.  Like this: `{type: "apiKey", in: "cookie", name: "myAuthCookie"}`

**Comment by retrospectacus** [comment]
@BigstickCarpet I completely agree - my described method is (will be?) a very poor workaround until in:cookie is implemented.

**Comment by BigstickCarpet** [comment]
Ah, ok.  Then we're in agreement.  I'm using the same workaround right now in all my Swagger APIs.

**Comment by cemo** [comment]
+1

**Comment by earth2marsh** [comment]
While I think this is an excellent candidate for Swagger.Next consideration, I am going to argue the other side here…

Cookies may be widely used on web applications, but they aren't a good fit for modern APIs (see references below). Swagger has taken a position on API design vis-a-vis its constraints around operation signatures, which means it already has a precedent of not aspiring to describe all possible APIs. This simplifies the tooling, and helps keep Swagger nimble. Perhaps excluding cookies should be part of Swagger's general opinion on API design?

On the pros' side, it's generally a good thing for Swagger to be a more descriptive format. 

On the cons' side, supporting cookies in the spec also implies supporting cookies in the tooling, including SDK generation and Swagger-UI, etc, not to mention the documentation and example overhead. That baggage slows down future development.

References:
* Fielding's REST dissertation's [section on cookies](http://www.ics.uci.edu/~fielding/pubs/dissertation/evaluation.htm#sec_6_3_4_2)
* [Should cookies be used in a restful API?](http://programmers.stackexchange.com/questions/141019/should-cookies-be-used-in-a-restful-api#answer-141434)
* Auth0's post on [Cookies vs Tokens](https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/)

**Comment by jirkadanek** [comment]
My usecase: document the semipublic API of Duolingo.com with Swagger

Duolingo uses cookies to authenticate users. Some calls require authentication, otherwise they fail. At the bare minimum in my API I need to be able to say say "this method can be called only if the user is authenticated". and in the generated bindings I need to be able to keep a cookie-jar that would hold cookies set by previous requests.

Currently I am giving all methods that needs authentication a tag "authed". I haven't yet looked into how generated bindings handle cookies. (I am not using generated bindings). By and large this works OK for me.

**Comment by 304NotModified** [comment]
+1

**Comment by rafaelcaricio** [comment]
+1

**Comment by Santinell** [comment]
+1

**Comment by 0x62ash** [comment]
+1

**Comment by andrewzk** [comment]
+1

**Comment by jirkadanek** [comment]
See also https://github.com/swagger-api/swagger-ui/issues/461

**Comment by webron** [comment]
Parent issue: #585

**Comment by jasonh-n-austin** [comment]
For posterity, a better example of how this works https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-cookie-based-authentication

**Comment by assiso** [comment]
+1

**Comment by RobDolinMS** [comment]
@ajtowns Is this still an issue in the latest spec?

**Comment by BStramke** [comment]
as far as i have seen in 3.0rc1, the authentication still does not support that behavior, or the "in" parameter is lacking the cookie part in its description. There should atleast be an example as there isn't really an obvious way to authenticate through a session cookie.

**Comment by RobDolinMS** [comment]
Resolved with #1200.  Thanks everyone!
