### ISSUE TITLE
How to document a dynamic response?

### ISSUE THREAD

**Issue by RaulRG** [OAI/OpenAPI-Specification#1511]
My API will permit access to a "legacy" enterprise system. This system has a very useful feature where technical users can create their own queries or modify existing ones using a domain language. This means that I cannot hardcode the URIs for these queries as they are dynamic and even the response for a query itself is dynamic.

I think it is better to try to explain with samples. Let's say the uri for the GET would be

`https://base/queries`

The technical user could create a query "orders" that returns tabular information about the orders in the system. The uri could be:

`https://base/queries/orders`

The documentation for the specific query itself is easy if I use a parameter like this:

`https://base/queries/{name}`

Now my problem is that the response will quite different depending on the {name} (even the same name could be different when the user modifies an existing query).

How could I document this fact? Is there any way of documenting that I will get dynamic tabular data? I would like the response to include metadata / schema about the different columns.

Please forgive my lack of understanding. I tried to find an answer in the specification, but I couldn't find anything or I didn't see it.

**Comment by darrelmiller** [comment]
You can always specify a media type that describes a general tabular format.  In fact `text/csv` actually gives you something close to that already.

As far as defining something like JSON schema, it is a bit difficult to define a schema for columns when you don't know in advance what that schema is going to be.  Also, you should look at [collection+json](http://amundsen.com/media-types/collection/) as it might do everything you need as it allows you to embed metadata in a response about the properties of a collection item.  

Perhaps if you can give us some examples of the type of metadata you want to provide, we can help guide you on how to incorporate that into an OpenAPI description.

**Comment by RaulRG** [comment]
Thank you @darrelmiller.

OpenAPI is great to document your API if you know upfront how your responses look. In my case the responses can be modified by the technical users. Let's say I've got 

`https://base/queries/users`

That in the "standard" case returns

```
"data" : [
  {
    "id" : 23,
    "name" : "Peter Smith",
    "department" : "Sales
  },
  {
    "id" : 26,
    "name" : "Mario Jones",
    "department" : "Development"
  }
]
```

Now the technical user modifies the query using the domain language and our customizing tools so that it adds the phone.

```
"data" : [
  {
    "id" : 23,
    "name" : "Peter Smith",
    "department" : "Sales,
    "phone" : "1234567890"
  },
  {
    "id" : 26,
    "name" : "Mario Jones",
    "department" : "Development",
    "phone" : "555437609"
  }
]
```

The technical user can even create queries that I need to return. Let's say they create a query called "sales_summary". Calling

`https://base/queries/sales_summary`

could return something like this:

```
"data" : [
  {
    "month" : 1,
    "product" : "Gadget 300",
    "sales" : 12540.20
  },
  {
    "month" : 2,
    "product" : "Gadget 620",
    "sales" : 22650.70
  }
]
```

As the information for the response (and even the query names) is not known upfront I was thinking if it could be possible to dynamically document it using the OpenAPI specification mechanisms for it. My idea is to use the same metadata description that is used to statically document the APIs to document dynamic responses. Tools that understand the specification could be used for the dynamic responses. I know I could implement something myself, but my question is if there is any standard (or ideas) about how to do it.

I could document the response for /queries/{name} as:

```
description: The response for a given query
content: 
  application/json:
    schema: 
      type: array
      items:
        $ref: '#/components/schemas/DynamicType'
```

But my problem would be how to define "DynamicType". I would prefer if I could include the schema for the items as response itself.
The response could look like this:

```
"item_schema" : {
  "type": "object",
  "properties": [
    "month": {
      "type": "integer",
      "format": "int64"
    },
    "product": {
      "type": "string"
    },
    "sales" : {
      "type": "double"
    },
  ]
},
"data" : [
  {
    "month" : 1,
    "product" : "Gadget 300",
    "sales" : 12540.20
  },
  {
    "month" : 2,
    "product" : "Gadget 620",
    "sales" : 22650.70
  }
]
```

In this sample does not make so much sense, but we are returning much more metadata for the fields. Some are standard and other are custom using the x- prefix. Things like localized title and description using the user's language, pictures to show for enums instead of text, ...

**Comment by darrelmiller** [comment]
If you want to embed a schema in the response, then go ahead, do that.  OpenAPI has no issue with that.  If you are asking if there are any existing efforts that do something similar then I would suggest you look at things like `collection+json` and JSON-LD.

**Comment by RaulRG** [comment]
Thank you again @darrelmiller 

I already had a look at collection+json. I will look at JSON-LD and probably use something like what I posted before.

**Comment by handrews** [comment]
@RaulRG you can link to a JSON Schema (which is what OpenAPI's Schema Object is closely based on) with an HTTP `Link` header with rel=describedby, if you want to provide a runtime schema.

JSON Hyper-Schema is based on that and there is now a JavaScript implementation approaching feature-complete status (although no other implementations yet).  See json-schema.org for details if interested.

**Comment by RaulRG** [comment]
Thank you @handrews!!! As I said, I would like to be as close as possible to any standard. Json hyper-schema looks promising and as I see it includes an example with collection in the current draft. Using the header with the rel=describedby looks like what I need for providing runtime schema.
Again, thank you very much for pointing me in this direction.

**Comment by RaulRG** [comment]
I've got a question @handrews.

How is json schema (or hyper-schema) related to json-ld? [https://json-ld.org/](url)

My goal gets more and more complicated as I keep finding different "standards". It is difficult for me to understand all the advantages and constraints of them.

I found the following issue about rel=describedby [https://github.com/json-ld/json-ld.org/issues/197](url). As you can see is a very lengthy discussion that just confuses me. Your approach looks very good and it seems logical for me, but I must admit that I cannot follow with all these specs.

**Comment by sharathmnkla** [comment]
@RaulRG..... Where you able to resolve the issue?

**Comment by RaulRG** [comment]
Yes, at least we are happy with our solution. We dynamically create OpenAPI responses to document our customized endpoints. See the OpenAPI SDK to see how to generate the models programmatically ( [https://github.com/microsoft/OpenAPI.NET](url)).
