### ISSUE TITLE
TSC Meeting Agenda - March 23rd 2018

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1512]
In order to give some more visibility into the topics we cover in the TSC meetings we are going to try using a GitHub issue to plan the Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.

**Proposed Agenda**

| Topic | Owner |
|-------|---------|
| Security Presentation | Isabelle |
| TSC support for implementers of V3 features | Darrel |
| Revisit concept of "draft" extensions | Darrel |
| Validation test suite progress | Mike |

**Comment by handrews** [comment]
@darrelmiller is there anything posted somewhere about the '"draft" extensions' concept?  Is this an experimental feature management thing?

**Comment by darrelmiller** [comment]
@handrews I don't believe it was ever documented anywhere but it is based on a idea that Tony had suggested regarding handling experimental features.  

We have the challenging situation at the moment that lots of folks want new stuff added to the spec, but the support for V3 features is lagging where we want it to be.  So the idea is we accept proposals for new stuff, document them somewhere not in the spec as x-draft-{some-new-feature} and encourage tooling to build it.

I'd like the enthusiasm for having new features in the spec to help driving tooling implementation.  If we can get tooling to successfully implement the feature and users see the obvious benefit, then we'll pull it into the spec and drop the x-draft-.  

Full disclosure, this is just something I recently thought about and does not have any kind of official blessing, hence why I want to bring it up at a TSC meeting.

**Comment by DavidBiesack** [comment]
I recall mention of a namespace for OAI/OAS drafts, such as `x-oas-draft-{some-new-feature}`

**Comment by cmheazel** [comment]
Consider taking a micro-specification approach.  Define a core which is sufficient for most users and required for all implementations.  Then provide support for controlled extensions (micro-specs) for those who need more.  Each micro-spec would have a well defined scope.  A developer can support those extensions which are important to their user base and ignore the rest.
New requirements can go through a three step process:
1) Bring them in as a draft extension.  This allows the stake holders to mature the spec within the community process.  At this point the community can fix or kill bad ideas.
2) If a draft extension is mature, coherent with the rest of the OpenAPI suite, and has a defined user base, then it can advance to controlled extension status.
3) If a controlled extension demonstrates such universal value that everyone is implementing it, then we can consider moving it into the core.  This would be a very rare occurrence.

**Comment by darrelmiller** [comment]
@cmheazel We are currently debating the feasibility of (1).  If an draft extension meets the criteria in (2) then I think it would be valuable to just pull in into the next spec revision.  

The idea of having a generalized "controlled extension" model makes me worry that we re-invent the problems of WS-*.  The Swagger eco system was successful due to tooling and there was a low barrier of entry for tooling and a consistent user experience.  That is something we want to avoid breaking.

I believe we have no choice but to do "controlled extensions"/"plugins" for certain extensibility points like alternate schemas.  But I am reluctant to push for this approach for any type of extension.

**Comment by cmheazel** [comment]
No need to make a decision now.  I brought it up because the OGC WFS 3.0 effort (https://github.com/opengeospatial/WFS_FES) is using this approach.  We can take advantage of their lessons learned.
