### ISSUE TITLE
Multi location for parameter 

### ISSUE THREAD

**Issue by KES777** [OAI/OpenAPI-Specification#1518]
If I expect `format` parameter in query or body. Is there a way to specify it like:

```
in:
  - body
  - query
```

Or I should define `format` for both: body and query and then group them like suggested at #445 ?

**Comment by MikeRalphson** [comment]
In OpenAPI 2.0? You would have to define the parameter twice and ensure they are not `required: true`. It is not clear which proposal from #445 you mean by 'grouping' them.

In OpenAPI 3.0.x `in:body` parameters have been replaced by `requestBody objects` so the issue doesn't arise in the same way.

**Comment by KES777** [comment]
I mean OpenAPI 3.0.x. I want to escape from defining that **twice for each route**. There are interesting proposition #445 to define parameter once for query, once for body then group it. So when I define a route I just refer to group of those two definitions:

```
/some_route
  parameters:
    - $ref: "#/parameters/formatAny"
components:
  parameters:
    formatQuery:
       in: query
       sets: [ "formatAny" ]
       ...
    formatBody:
       in: body
       sets: [ "formatAny" ]
       ...
       
```

**Comment by MikeRalphson** [comment]
As I said, in OpenAPI 3.0.x `in:body` parameters have gone away, so the problem as you state it doesn't occur and the (as yet unadopted) proposal from #445 would not help.
