### ISSUE TITLE
Is it possible to reference the servers object from another OpenAPI file?

### ISSUE THREAD

**Issue by iappa1** [OAI/OpenAPI-Specification#1527]
I'm documenting a list of APIs using OpenAPI 3.0 and a separate YAML file for each API.

All APIs use the same target server, so currently I have the following in each API definition:
  `  

      servers:
          - url: www.abc.com   
            description: "Production Server" 
 `
But I don't want to repeat the servers in all API definitions. Instead, I would like to reference the servers from a single file, like so:

`

        //sample.yaml
         ...
        servers:
        $ref: 'index.yaml#/servers'
`

But Swagger UI shows the "Could not render this component" error.

Is it possible to $ref the servers in OpenAPI 3.0 definitions?

**Comment by webron** [comment]
As you can [see in the spec](https://github.com/OAI/OpenAPI-Specification/blob/v3.0.1/versions/3.0.1.md#serverObject), the Servers Object does not support using references to other places, so indeed, at the moment, you'd have to copy the object between the definitions.
