### ISSUE TITLE
Proposal - extract Swagger Examples into separate files of mappings.

### ISSUE THREAD

**Issue by ptoora** [OAI/OpenAPI-Specification#1533]
Examples (plus swagger) can be used as the basis for stubs/mocks.
If we can separate these out from the Swagger files, ideally in a Wiremock Mapping style, then the combination of the Swagger plus the Mappings will mean that, with existing open source offerings (eg. https://github.com/telegraph/swagger-stub), we can stand-up a stub/mock very quickly. This will also neatly draw design and implementation closer.

**Comment by darrelmiller** [comment]
Examples can be separated out into a different file using the `externalValue` property of the [example object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#exampleObject).  Is this sufficient for your needs?

**Comment by MikeRalphson** [comment]
Ping @ptoora

**Comment by kscheirer** [comment]
I am evaluating this as a possible use case for overlays, https://github.com/OAI/Overlay-Specification/discussions/9.

Possibly overlays could help here, examples could be defined in overlay file, that would technically meet the requirement of having examples in a separate file. Not sure that is any better than using `externalValue` mentioned previously though.

Tooling could also be used (for ex [jq](https://stedolan.github.io/jq/)) to parse a contract quickly and extract/transform the examples, to a separate file if need be. This makes overlay the wrong way to handle this use case.

**Comment by handrews** [comment]
It sounds like `externalValue` was the main answer, and further work is taking place in Overlays.  I'm going to close this as answered / part of another project.
