### ISSUE TITLE
Code Lists - A Topic for Discussion

### ISSUE THREAD

**Issue by cmheazel** [OAI/OpenAPI-Specification#1536]
A Code List is a technique for creating an extensible enumeration.  They consist of two parts:
1) A URL to the register where the codes are defined (Server)
2) Well known terms which are the code values (Path)

A common example of a code list is MIME Type.  MIME Types are maintained on the IANA Media Types register at "https://www.iana.org/assignments/media-types".

For JSON, the MIME Type is "application/json".  
Putting the Register URL and MIME Type code together gives us the URL:
https://www.iana.org/assignments/media-types/application/json
Which resolves to a description of the "application/json" media type.

Implementations of a Code List typically are only required to implement the Code List pattern and any mandatory codes.  Developers should know which codes their customers care about and will build in support for those codes as well.  Any other codes can be ignored or raise an exception.     

The National Geospatial-Intelligence Agency (NGA) maintains a set of Code List registers for U.S. systems.  They can be found at https://nsgreg.nga.mil/voc/registers.jsp

I believe the European Union INSPIRE Initiative maintains a similar registry for European systems.  I can check into that if there is any interest. 

Cheers.

**Comment by lornajane** [comment]
This issue has been open for some time and doesn't seem to have much engagement, so it will now be closed.
