### ISSUE TITLE
Use X-RateLimit instead of X-Rate-Limit

### ISSUE THREAD

**Issue by ioggstream** [OAI/OpenAPI-Specification#1539]
## I wish

  - openapi specs to use X-RateLimit instead of X-Rate-Limit in examples ;)

## Because

  - X-RateLimit seems most common in api gateways (kong, wso2) and in services (github, api.data.gov, http://zalando.github.io/restful-api-guidelines/index.html#132)

  - see http://william.holroyd.name/2014/11/02/how-do-most-apis-handle-rate-limiting/ for a comparison

**Comment by webron** [comment]
Your wish is hereby granted, you may use X-RateLimit instead.
What exactly is stopping you?

**Comment by ioggstream** [comment]
Just use a more common name in openapi examples ;)

**Comment by webron** [comment]
Closing - see https://github.com/OAI/OpenAPI-Specification/pull/1540#issuecomment-387564078.
