### ISSUE TITLE
[oas3] base64 vs byte

### ISSUE THREAD

**Issue by jwalton** [OAI/OpenAPI-Specification#1547]
The spec makes numerous references to `{format: base64}` ([here](https://github.com/OAI/OpenAPI-Specification/blob/fbe62006211838a8bb7bf2433a1d15f1a5838a03/versions/3.0.1.md#considerations-for-file-uploads) and [here](https://github.com/OAI/OpenAPI-Specification/blob/fbe62006211838a8bb7bf2433a1d15f1a5838a03/versions/3.0.1.md#special-considerations-for-multipart-content) for example).  However this format is not defined in either [the wright-00 JSON-schema spec](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-7.3), nor in [the OAS3 defined data types](https://github.com/OAI/OpenAPI-Specification/blob/fbe62006211838a8bb7bf2433a1d15f1a5838a03/versions/3.0.1.md#data-types).

**Comment by handrews** [comment]
@jwalton `format` is extensible and OpenAPI defines numerous extensions including `base64`, although per #1310 and #1544, `base64` should be handled differently in the long run with newer versions of JSON Schema.

But as far as the JSON Schema spec goes, what OpenAPI is doing with formats is valid.

**Comment by jwalton** [comment]
Oh, it's valid, it's just that [the defined data types](https://github.com/OAI/OpenAPI-Specification/blob/fbe62006211838a8bb7bf2433a1d15f1a5838a03/versions/3.0.1.md#data-types) section defines `{format: 'byte'}` as "base64 encoded characters".  It seems weird to define our own special name for base64 and then not use it.  :P

**Comment by darrelmiller** [comment]
As per @tsc meeting we are going make a decision between have a `byte` format or a `base64` but not both.  Some historical spelunking will be done by @webron before making the call.

**Comment by jwalton** [comment]
FWIW, my vote is for `base64`.  It much more clearly conveys the intent.

**Comment by ralfhandl** [comment]
I also prefer `base64`

**Comment by handrews** [comment]
In OAS 3.1, this can now be handled properly from the JSON Schema perspective.  Specifically:

```YAML
type: string
contentEncoding: base64
```
is a base64-endcode string (where base64 is per RFC 4648).  You can use any RFC 4648 or RFC 2045 encoding, so `base64url` or `quoted-printable` are also valid.

If you are encoding a specific media type, such as a PNG file:
```YAML
type: string
contentEncoding: base64
contentMediaType: image/png
```

Note that the `content*` keywords are informational, and are not validated during JSON Schema validation.

For binary transfer, use

```YAML
type: string
contentMediaType: application/octet-stream
```
or some other media type.

-------
we should probably deprecate `"format": "base64"` and `"format": "binary"` in OAS 3.1 although I don't feel strongly about it.  Well... I have lots of strong feelings about `format` but that's a rant for another time.

**Comment by handrews** [comment]
For OAS 3.1.0, since we're now dropping the `byte`/`base64` format in favor of `contentEncoding`, this is no longer a concern.

If there's going to be an OAS 3.0.4, then this should be clarified with a PR to the appropriate branch.

**Comment by handrews** [comment]
For OAS 3.1.0 this is resolved with #2200.

@OAI/tsc is there likely to be a 3.0.4 where we would fix the examples of `base64` vs `byte`?  If not, we can close this.

**Comment by MikeRalphson** [comment]
My appetite for a `3.0.4` is... limited.

**Comment by MikeRalphson** [comment]
As above, I believe we can close this.
