### ISSUE TITLE
Question: Is there hints for validator how to validate $ref?

### ISSUE THREAD

**Issue by KES777** [OAI/OpenAPI-Specification#1558]
I am trying to implement openapi validator. I am using Tim Burks [schema](https://github.com/googleapis/gnostic/blob/master/OpenAPIv3/openapi-3.0.json)

In my schema I have next definition:

```
paths:
  /test:
    post:
      parameters:
        - $ref: '#/components/schemas/Test'
```

OpenAPI schema defines that `paramters` maybe parameter definition or reference

```
"parameters": {
  "type": "array",
  "items": {
    "$ref": "#/definitions/parameterOrReference"
  },
  "uniqueItems": true
},
...
"parameterOrReference": {
  "oneOf": [
    {
      "$ref": "#/definitions/parameter"
    },
    {
      "$ref": "#/definitions/reference"
    }
  ]
},
```

In my schema I use reference and schema is validated. But it should not, because it refer to wrong resource type: `schemas` but should refer to `parameter`

In my validator implementation I may hardcode this check:  after ref resolution it should refer to parameter.

Is there a way to provide some hints to validator about type for referenced object?

```
  "oneOf": [
    {
      "$ref": "#/definitions/parameter"
    },
    {
      "$ref": "#/definitions/reference"
      "$type": "#/definitions/parameter"
    }
  ]
```
Here $type will provide hint that after resolution the schema should be validated against `"#/definitions/parameter"` schema. Would it be useful to provide such hints?

**Comment by KES777** [comment]
Or maybe this variant?
```
  "oneOf": [
    {
      "$ref": "#/definitions/parameter"
    },
    {
      "allOf": [
        {
          "$ref": "#/definitions/parameter"
        },
        {
          "$ref": "#/definitions/reference"
        },
      ]
    }
  ]
```

**Comment by handrews** [comment]
JSON Schema does not have a feature for validating the `$ref` target.

There is a proposal for such a feature at json-schema-org/json-schema-spec#141 but it's somewhat controversial and unlikely to be considered before draft-09 (we are currently working on draft-08, and OpenAPI is using draft-04).

**Comment by handrews** [comment]
Since OAS 3.1 is adopting the most recent JSON Schema draft, and this more of a JSON Schema thing, I think this is better tracked at json-schema-org/json-schema-spec#141 

Additionally, the question of requiring (rather than validating) that `$ref`s point to #/components/<correct thing> is tracked at #2084
