### ISSUE TITLE
Swagger model/parser link borken for github.

### ISSUE THREAD

**Issue by shankyty** [OAI/OpenAPI-Specification#1565]

**Comment by MikeRalphson** [comment]
(Links in [IMPLEMENTATIONS.md](../blob/master/IMPLEMENTATIONS.md) point to non-existent branch).

**Comment by darrelmiller** [comment]
Paging @webron .  Cleanup in aisle 1565.

**Comment by MikeRalphson** [comment]
This was fixed by PR #1538 - thanks.
