### ISSUE TITLE
TSC Meeting - Monday April 30th 

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1566]
**NOTE: This is Monday at 9am PT, not Friday.  We are doing a trial of a more Europe friendly meeting time!**

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner |
|-------|---------|
| Find volunteer to record action items| Jeff_EF |
| Review progress of work on official OAS JSON Schema | Ron |
| Suggestions for next steps for specification conformance tests | Ted |
| Review process for accepting draft-features proposals   | Darrel |
| Discuss requirement for developer certificate of origin / signed-off-by | Jeff |
| Review and Merge Recent PRs | TSC |
| Review issues with "review" tag | TSC |
| Make decision on Bikeshed vs Respec  | TSC |
| Conversation about top level alternative to 'paths' | Darrel |

/cc @OAI/tsc Please add items as you see fit

**Comment by namdeirf** [comment]
AI: _DUE May 14, 2018_ - Followup on OSC specification discussion from 4/30
AI: Followup on changing requirement to a CLA. Also clarify any additional steps for employees signing a CLA.

**Comment by namdeirf** [comment]
OUTCOME: Added new labels - https://github.com/OAI/OpenAPI-Specification/pull/1531#pullrequestreview-116363218
