### ISSUE TITLE
TSC Meeting - Monday May 7th

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1569]
**NOTE: This is Monday at 9am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Find volunteer to record action items| @namdeirf |  |
| Review progress of work on official OAS JSON Schema | @webron  |  |
| Results of tag naming for draft-features proposals   | @webron  & @earth2marsh  |  |
| Tag alternate-schemas proposal with newly minted tag | @OAI/tsc  |  |
|  v3.0.2 go/no-go | @OAI/tsc |  |
| Update on Bikeshed vs Respec  [voting](https://github.com/OAI/OpenAPI-Specification/issues/1564) +(GitHub Pages https celebration) | @OAI/tsc |  |
| Comparison between new "paths" alternative with JSON Hyper-schema | @handrews |  |
| Review issues with "[review](https://github.com/OAI/OpenAPI-Specification/labels/review)" tag | @OAI/tsc |  |
| Update on issue related to Overlays | @usarid / @jstoiko |  |
| Update on work related to  specification conformance tests | @tedepstein  |  |

/cc @OAI/tsc Please add items as you see fit

**Comment by webron** [comment]
@darrelmiller can I remove items as I see fit too?

**Comment by darrelmiller** [comment]
@webron Only if you can bribe^G^G^G^G^G convince another TSC member to sign off on the removal.

**Comment by earth2marsh** [comment]
AI: @earth2marsh to propose alternate language in #1571
