### ISSUE TITLE
Using $ref with info.description

### ISSUE THREAD

**Issue by simondean** [OAI/OpenAPI-Specification#1570]
Given `info.description` can contain commonmark, it would be helpful when working with large description (e.g. > 100 lines of commonmark) if the description could be placed in a separate file and then included into an `openapi.yaml` file via the `$ref` syntax.  E.g. 

```yaml
openapi: 3.0.1
info:
    title: Example API
    description: 
        $ref: includes/description.md
    version: 1.0.0
...
```

**Comment by darrelmiller** [comment]
Yes it would.  I was just thinking this the other day.  I'm not sure $ref is the right solution for it though.  It might be, but it might also be better to take the approach that we took with examples.  Thoughts @OAI/tsc ?

**Comment by darrelmiller** [comment]
Conversation in the @OAI/tsc meeting today led us to the belief that using "overlays" will be a better approach for externalizing descriptions.  Overlays are an ongoing topic that borrows from the ideas in RAML.  Look for an issue to be opened in the next couple of weeks to track progress on that.
