### ISSUE TITLE
DOC: improve formatting

### ISSUE THREAD

**Issue by KES777** [OAI/OpenAPI-Specification#1578]
On the [page](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operation-object-example)

![delete1](https://user-images.githubusercontent.com/799021/39882423-6a19b646-548c-11e8-9d91-172c33108b53.jpg)

`required` keyword is not aligned properly and makes confusion a bit.

It would be more clear if you move this keyword after `type` and before `properties`

**Comment by darrelmiller** [comment]
Thanks for spotting this.  Would there be any chance you could create a PR to fix it against the 3.0.2-dev branch?

**Comment by MikeRalphson** [comment]
It would be nice to have the `required` array positioned consistently with regard to the `type` and `properties` properties in **all** the examples. Personally I prefer it to follow `properties`, as then the `required` array isn't seen as referencing properties which haven't been introduced yet, but of course the notion of property ordering in JSON/JSON-schema is artificial.

**Comment by webron** [comment]
Fixed by #2132.
