### ISSUE TITLE
TSC Meeting - May 14th, 2018

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1580]
**NOTE: This is Monday at 9am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Find volunteer to record action items| @namdeirf |   |
| Review progress of work on official OAS JSON Schema | @webron  | Tabled |
| Results of [tag naming](https://github.com/OAI/OpenAPI-Specification/pull/1531) for draft-features proposals   | @webron  & @earth2marsh  | [Approved](https://github.com/OAI/OpenAPI-Specification/pull/1531#discussion_r187191168)   |
| Tag [alternative-schemas proposal](https://github.com/OAI/OpenAPI-Specification/pull/1532) with newly minted tag | @OAI/tsc  | Tabled till future meeting, to clarify wording. Other decision based on hosting of alternative schemas  |
| Update on Bikeshed vs Respec  [voting](https://github.com/OAI/OpenAPI-Specification/issues/1564) +(GitHub Pages https celebration) | @OAI/tsc |  The body chooses: Respec |
| Review issues with "[review](https://github.com/OAI/OpenAPI-Specification/labels/review)" tag <br> Clarify `allowEmptyValue` [#1573](https://github.com/OAI/OpenAPI-Specification/issues/1573) | @OAI/tsc |  Tables #1573 seeking community feedback  |
| Update on work related to  specification conformance tests | @tedepstein  |  |

/cc @OAI/tsc Please add items as you see fit

**Comment by handrews** [comment]
To follow up from last week, I've been thinking some about Hyper-Schema + OAS best practices but nothing concrete to report yet and no new questions, so unless there's some other schema question for which I'm needed I'll likely skip the call this week.  Hopefully @philsturgeon can make it :-)  (tag! you're it!)

**Comment by philsturgeon** [comment]
I’m it! 

--
Phil Sturgeon
@philsturgeon
