### ISSUE TITLE
I want to encode  all the data but didn't get proper url format 

### ISSUE THREAD

**Issue by babumolla** [OAI/OpenAPI-Specification#1583]
when I encode the array of  all values then URL part is encoded wrongly.
My code is--
 $post_data =array(
    				"pickup_pincode"=> "400080",
					"delivery_pincode"=> "395009",
					"order_number"=> "BOX123ABC",
					"payment_mode"=> "online",
					"insurance"=> false,
					"number_of_package"=> 1,
					"package_details"=> array(
										  "details"=> array(
													    "weight"=> 0.5,
													    "length"=> 2,
													    "height"=> 3,
													    "width"=> 5,
													    "invoice"=> 620,
													    "packagedescription"=> "Dummy"
													  	)
										),
					"delivery_address"=> array(
										  "company_name"=> "Zepo",
										  "address"=> "Ambaji Dham mandir, Mulund west",
										  "city"=> "Bombay",
										  "state"=> "Maharashtra",
										  "pincode"=> "400080",
										  "country"=> "IN",
										  "contact_no"=> "9988776655",
										  "email"=> "abv@zepo.in"
										),
					"success_callback_url"=>$succ_url,
					"failure_callback_url"=>$fail_url,
					"client_source"=>"Artpur.in"
    			);

    // $post_json = json_encode($this->getRequestObject());
          $post_json= json_encode($post_data);

and when I print tyhe $post_json then got the result is something  like this all are good but the url part getting some problem
Result----
{"pickup_pincode":"400080","delivery_pincode":"395009","order_number":"BOX123ABC","payment_mode":"online","insurance":false,"number_of_package":1,"package_details":{"details":{"weight":0.5,"length":2,"height":3,"width":5,"invoice":620,"packagedescription":"Dummy"}},"delivery_address":{"company_name":"Zepo","address":"Ambaji Dham mandir, Mulund west","city":"Bombay","state":"Maharashtra","pincode":"400080","country":"IN","contact_no":"9988776655","email":"abv@zepo.in"},"success_callback_url":"http:\/\/artpur.in\/ecommerce\/admin\/index.php\/success","failure_callback_url":"http:\/\/artpur.in\/ecommerce\/admin\/index.php\/manage_order\/failure","client_source":"Artpur.in"} 

As you see The success_callback_url-- http:\/\/artpur.in\/ecommerce\/admin\/index.php\/success
might get problem.what should I do??????????????

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI Specification itself. You may get more responses on a general purpose forum such as StackOverflow. Thanks.
