### ISSUE TITLE
Reference Response headers Open API v3.0

### ISSUE THREAD

**Issue by pyromanci** [OAI/OpenAPI-Specification#1586]
I've been experimenting trying to break my large file into smaller and easier to handle files. I may be completely miss understanding part of the documentation where it says Headers can be a reference object.

But how come this doesn't validate in the 3.0. 

```
 /Account:
    parameters:
    - $ref: #/components/parameters/userAgent
    - $ref: #/components/parameters/installationID
    get:
      tags:
      - Account
      summary: Gets a list of Accounts
      description: Returns a list containing all Accounts. The list supports paging.
      operationId: listAccounts
      responses:
        200:
          description: A list of AchAccount
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Accounts'
          headers:
            $ref: #/components/responses/DefaultHeaders/headers
        500:
          $ref: #/components/responses/StandardErrorResponse
        default:
          $ref: #/components/responses/TotallyUnexpectedResponse
      parameters:
      - $ref: #/components/parameters/offline_filter
      - $ref: #/components/parameters/limit_filter
      - $ref: #/components/parameters/page_filter
```

**Comment by pyromanci** [comment]
Oh it's a Map. For what ever reason the Map in the type column in specs just didn't register in my brain. 

Possibly in a future revision the headers for the requests could be an array. would be nicer to have to do 1 line per header instead of 2.

**Comment by bolshoydi** [comment]
@hkosova You said >>>"Note that you can only `$ref` individual headers but not the entire `headers` section."
and how to `$ref` (link) to the whole section like `security` section can?  (like this)[https://swagger.io/docs/specification/authentication/oauth2/] you can Apply the security globally to all operations, but i want to apply respnse headers to all the operations avoidin copy-paste.

**Comment by hkosova** [comment]
@bolshoydi you can't, you can only `$ref` individual response headers - as shown in the example. However, there are existing feature requests to improve header reuse:
[Share header with multiple response objects](https://github.com/OAI/OpenAPI-Specification/issues/369)
[Structural improvements: enhance headers handling](https://github.com/OAI/OpenAPI-Specification/issues/690)

**Comment by n-alex-white** [comment]
@hkosova I see that some of those feature requests have been around for three years. Excuse my ignorance of how the process works, but how long does it typically take for feature requests to be considered? Any idea whether these are active or dead? Thanks.
