### ISSUE TITLE
JSON Schema for v1.2 API Declaration authorizations is wrong

### ISSUE THREAD

**Issue by whitlockjc** [OAI/OpenAPI-Specification#159]
The way things should work, based on the [Swagger 1.2 Specification](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#52-api-declaration) is you should _define_ authorizations in the Resource Listing and then reference them using the `authorizations` property in the API Declarations and the Operations.  Based on the current schema, the `authorizations` property in the API Declaration is for defining authorizations instead of referencing them so you are unable to have authorization references at the API Declaration level.

Originally opened in [reverb/swagger-spec/issues/118](https://github.com/reverb/swagger-spec/issues/118).

**Comment by RobDolinMS** [comment]
@whitlockjc Can this issue be closed?

**Comment by whitlockjc** [comment]
I think we can close it.  My understanding is that enhancements/fixes to 1.x isn't happening right now.  @webron can reopen if he thinks we should address it.
