### ISSUE TITLE
OpenApiConfiguration -> SwaggerConfiguration unique ?

### ISSUE THREAD

**Issue by b-repo** [OAI/OpenAPI-Specification#1607]
Hi,

I am using Jetty and Apache CXF with the CXFServlet and a spring bean configuration (example : 
`<bean id="adminOpenApiCustomizer" class="org.apache.cxf.jaxrs.openapi.OpenApiCustomizer">`
`        <property name="dynamicBasePath" value="true"/>`
`    </bean>`
`<bean id="AdminOpenApi" class="org.apache.cxf.jaxrs.openapi.OpenApiFeature">`
`        <property name="title" value="Admin Open Api" />`
`        <property name="customizer" ref="adminOpenApiCustomizer"/>`
`    </bean>`
)

I have 3 jars, module1, module2, and module3. Inside of each module, I have javax controller with io.swagger.v3.oas annotations to generate the documentation.

Then, I have a war, which is using the 3 dependencies above.
This webapp allow the user to access to the controllers of the first module by the address : 

> http://xxx/project/rest/module1/path_to_method

To access to the controllers of the second module by the address : 

> http://xxx/project/rest/module2/path_to_method

And to access to the controllers of the third module by the address :

> http://xxx/project/rest/module3/path_to_method

Now that the context is described, here is my problem :
I was using swagger v2 (io.swagger.annotations). When I reached 

> http://xxx/project/rest/module1/swagger.json

The documentation of the first module appeared. Same thing for module2 & 3.

Now, I have switched for OpenApi v3 with io.swagger.v3.oas.
I read the documentation of CXF and did the right things to obtain the documentation.

Now, when I request 

> http://xxx/project/rest/module1/openapi.json

I have the documentation of the **module1**.

BUT, when I request

> http://xxx/project/rest/module2/openapi.json
> http://xxx/project/rest/module3/openapi.json

I also have the documentation of the **module1**.

I was searching in the debugger and found out that the SwaggerConfiguration (openApiConfiguration field of the OpenApiCustomizedResource class) does not change. 

Any idea for me to have 3 differents documentations in my webapp with 3 REST modules?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
