### ISSUE TITLE
Question: is putting `required` by itself in an `allOf` block valid jsonschema?

### ISSUE THREAD

**Issue by dtkav** [OAI/OpenAPI-Specification#1608]
This issue [came up](https://github.com/p1c2u/openapi-spec-validator/issues/27) when discussing the correct behavior for an OpenAPI spec validator (https://github.com/p1c2u/openapi-spec-validator).

Other issues [1, 2] mention the ability to modify whether a property is required using `allOf` like so:
```
SaveRequest:
  allOf:
    - $ref: "#/definitions/Dog"
    - required:
      - breed
      - name
```
Reading the OpenAPI spec, it sounds like each member of `allOf` must stand alone as its own schema. 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schemaObject
> allOf - Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.

and that the spec defers to json-schema for the definitions of the `required` field.

> The following properties are taken directly from the JSON Schema definition and follow the same specifications:
> ...
> **required**
> ...

However, the json-schema validation rfc makes it sound like the properties must also be present, or it is invalid.

http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.3
> 6.5.3. required
> ...
> An object instance is valid against this keyword if every item in the array is the name of a property in the instance. 

Is this behavior valid? If so, is it worth updating the spec or examples? Let me know, and I'm happy to help.

Thanks very much for your time!

[1] https://github.com/OAI/OpenAPI-Specification/issues/1562
[2] https://github.com/OAI/OpenAPI-Specification/issues/1562

**Comment by handrews** [comment]
@dtkav as one of the current editors of the JSON Schema spec, I can tell you that `required` on its own is 100% valid usage.  The important part of the wording is "in the instance".  `required` checks against the names in the instance object, independent of the `properties` object in the schema.

**Comment by dtkav** [comment]
@handrews thanks very much!

**Comment by flixx** [comment]
We have this as a common pattern in our API:

GET - every field is required
POST - some fields are required (might be solvable with `readOnly` for simple cases)
PATCH - no fields are required

Currently it seems that we can not get around repeating all properties over and over again :-(
See also the issue @dtkav already linked: https://github.com/p1c2u/openapi-spec-validator/issues/27

It would be really great to consider for a future version of the specs to change the meaning of `required`, so  that it works in combination with `allOf` and the example provided above will work as expected.

**Comment by handrews** [comment]
@flixx it is supposed to work, that's what I was pointing out in my earlier comment.  It's not even an `allOf` thing: `required` and `properties` function independently of each other anyway.  These schemas are equivalent in terms of their validation effects:

```JSON
{
    "required": ["foo"],
    "properties": {
        "foo": {},
        "bar": {}
    }
}
```

```JSON
{
    "allOf": [
        {
            "required": ["foo"],
        },
        {
            "properties": {
                "foo": {},
                "bar": {}
            }
        }
    ]
}
```

**Comment by flixx** [comment]
@handrews Perfect! Thanks for making it clear.

I think the issue lies then in the `openapi-spec-validator`. I already commented there (https://github.com/p1c2u/openapi-spec-validator/issues/27)
