### ISSUE TITLE
Support for nested examples in response body

### ISSUE THREAD

**Issue by mpazdnikova** [OAI/OpenAPI-Specification#1609]
Hi, 

I have a problem with specifying object example in a response body.
The models are: 
```
    ErrorResponse:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      description: Error information.
      type: object
      properties:
        code:
          description: Description
          type: integer
          nullable: true 
```
I'd like to specify an example of the error code in each response. Like that:
```
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error:
                  code: 10
```
It doesn't work like that. The example stays default. It works, however, if I specify object example in ErrorResponse model but that doesn't fit as I need a different example for each response.
Am I doing something wrong or is it just not supported? Thanks in advance for your help.

**Comment by darrelmiller** [comment]
What you are doing seems like valid OpenAPI to me.  However, it appears you are seeing a problem in some tooling that is based on OpenAPI.  You don't say which tooling you are using, but I would recommend filing this issue in the repo of the tool instead of the spec.
