### ISSUE TITLE
Inheritance info from "allOf" not shown in the generated model!!!

### ISSUE THREAD

**Issue by duckladydinh** [OAI/OpenAPI-Specification#1617]
Dear,

I cannot seem to find anyway to make the information from "allOf" on the left the appear in the models on the right. Is this a bug? Otherwise, what is the use of allOf then if it does not appear in the generated documentation?

![image](https://user-images.githubusercontent.com/22922064/42094287-9678f9b4-7baf-11e8-82ea-55af6695fbc5.png)

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
