### ISSUE TITLE
Adding support for classes of the same name in different packages!!!

### ISSUE THREAD

**Issue by duckladydinh** [OAI/OpenAPI-Specification#1618]
Hello,

Swagger is great and I am learning to use it with Java Implementation. However, when I have too classes of the same name, I do not know how I should handle it because Swagger only supports simple names.
Is there anyway to enable Swagger to generate YAML with full class name (package + simple name)?
Thank you.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by duckladydinh** [comment]
@MikeRalphson  This is related to the specification, about the naming of the schemas. Currently Swagger use only simple names, not full name. What I want to know is if there is any support for it?

**Comment by MikeRalphson** [comment]
Sorry, you mentioned a Java implementation and generating the YAML from your classes. That sounds like a tooling issue.

From the v3.0.1 spec (components object definition):

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$

Characters like `.` are supported, so if your tools can generate `PackageName.ClassName.modelName` or similar then there should be no problem. OAS 2.0 was even more permissive.
