### ISSUE TITLE
Support full class names for different class of the same name

### ISSUE THREAD

**Issue by duckladydinh** [OAI/OpenAPI-Specification#1619]
It would be great if there is support for different classes of the same name in different packages.

**Comment by MikeRalphson** [comment]
Please could you provide an example of an OAS document showing what you want to achieve and why you think it is currently not allowed? It still looks as if you are facing tooling challenges, not issues with the specification itself.

**Comment by duckladydinh** [comment]
Hello, @MikeRalphson this is an example, as you see this is a syntax error. If the specification allows it, there should be no "X" error here, right?
![image](https://user-images.githubusercontent.com/22922064/42162320-89c1355a-7dfe-11e8-9d79-8c459f494618.png)

**Comment by MikeRalphson** [comment]
In your example screenshot, your `$ref` value is missing `#/components/schemas/' at the start.

**Comment by handrews** [comment]
Looks like this was answered a year and a half ago.
