### ISSUE TITLE
RAML : How to require parameter A OR parameter B

### ISSUE THREAD

**Issue by M-Usama44** [OAI/OpenAPI-Specification#1621]
I have an issue. i am using raml 1.0. i have two query parameters in my raml so i want to restrict that users should input the value of one parameter atleast.
means that if user have entered the value of one parameter then other became optional but BOTH PARAMETERS CAN'T BE EMPTY. from two of them one should be necessary. 
example PFB the RAML 
/abc:
  get:
    queryParameters: 
      url:
        type: string
      image:
        type: string

user should give value of url OR image.

**Comment by MikeRalphson** [comment]
Hi, this repository is for the OpenAPI Specification, which does not incorporate the RAML spec.

Multiple ways to get support on RAML are listed [here](https://github.com/raml-org/raml-spec#how-can-i-get-in-touch).
