### ISSUE TITLE
Are empty title and version valid?

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1625]
I'm often seeing real-life (most likely, generated) OpenAPI definitions with empty `title` and `version`:

```yaml
info:
  title: ''
  version: ''
```

Is this valid?

The [Info Object description](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#info-object) says that `title` and `version` are required but does not specifically require a non-empty value. However, empty `title` and `version` don't make much sense to me.

**Comment by MikeRalphson** [comment]
Both fields are required and must be strings. As you say, the spec does not enforce a non-empty value. So the empty string value meets the current requirements. I can see a case for either dropping the required attribute or adding at least a SHOULD recommendation that empty string values be avoided.

**Comment by darrelmiller** [comment]
Ask @webron , he says yes.  Makes me feel a little dirty to be honest.

**Comment by MikeRalphson** [comment]
Closing as answered.
