### ISSUE TITLE
In Swagger 2.0, what should “default” within an array parameter actually mean?

### ISSUE THREAD

**Issue by alasdairhurst** [OAI/OpenAPI-Specification#1629]
Not an issue, but a question on the swagger in the repo:

In the well-known petstore swagger document, the findByStatus endpoint takes a status:
```
"parameters": [
    {
        "name": "status",
        "in": "query",
        "description": "Status values that need to be considered for filter",
        "required": true,
        "type": "array",
        "items": {
            "type": "string",
            "enum": [
                "available",
                "pending",
                "sold"
            ],
            "default": "available"
        },
        "collectionFormat": "multi"
    }
]
```
While the default value could be implied from this, from a programmatic perspective what should be expected as the value for "status" (and for other parameters in a similar case)?

The value is of type array, it doesn't have a default.
Each item is a string, one of available, pending or sold, and the default if not supplied is "available"
How would you use "default" for an array of arbitrary length? The default supplied is for the string, not the array so:

Does this imply that the array has no default value?
Does it imply that the array has a default value of an array with one item that is the default value for the array items?
Does it imply an array of arbitrary length where all the values are the default value for the array items?
Or is it just for UI representation of the default selected value when adding a new item to the array?

**Comment by silkentrance** [comment]
I believe that the example is just wrong. It should rather read

```
"parameters": [
    {
        "name": "status",
        "in": "query",
        "description": "Status values that need to be considered for filter",
        "required": true,
        "type": "array",
        "items": {
            "type": "string",
            "enum": [
                "available",
                "pending",
                "sold"
            ]
        },
        "default": ["available"]
        "collectionFormat": "multi"
    }
]
```

**Comment by tedepstein** [comment]
We should probably fix that example. @alasdairhurst , I cannot seem to find it in this repo. Can you point us to the source file?

**Comment by alasdairhurst** [comment]
@tedepstein I'd also like to know where to find the up-to-date one that has this example.
http://petstore.swagger.io/
https://petstore.swagger.io/v2/swagger.json

These both have the issue - I don't know where this is stored. It's slightly different from the ones in the repo here which i originally thought it was at:
https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v2.0/json

Looks like this may be the source - which is see is an extension of your examples.  I assumed you were the same team on this, and it looks like you're not?
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml

Although the question was aimed mostly at to what was expected from the spec. I'll open an issue there.

**Comment by tedepstein** [comment]
Thanks, @alasdairhurst .  The OpenAPI specification is no longer part of Swagger, so yes, these are different projects. (See [background here](https://www.openapis.org/announcement/2015/11/05/new-collaborative-project-to-extend-swagger-specification-for-building-connected-applications-and-services).)

**Comment by handrews** [comment]
Looks like the example in question is not part of this project, and no more work is being done on OAS 2 anyway, so I'm going to close this.
