### ISSUE TITLE
TSC Meeting - Thursday, July 12th, 2018

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1630]
**NOTE: Sorry for changing this again, but Monday turned out to be a bad day.  This meeting is on Thursday at 9am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Status of the CName for pretty spec | @namdeirf  | |
| Simplify Travis build steps? | @mikeralphson | |
| Update on media type registration | @darrelmiller | |
| Update on 3.0.2 | @OAI/tsc | |
| Come prepared to talk about Overlays | | |
| Review wording changes to AllowEmptyValue | Ted | |
| Merge complete PRs | @OAI/tsc | |
| Review issues with "[review](https://github.com/OAI/OpenAPI-Specification/labels/review)" tag | @OAI/tsc | | 

/cc @OAI/tsc Please add items as you see fit

**Comment by webron** [comment]
- @namdeirf will update the link on openapis.org for the specification to the newly created spec.openapis.org.
- Version 3.0.2 publishing - @webron to sync up with @MikeRalphson and work together on publishing the version by end of next week.
- @MikeRalphson will add his awesome registry work to gh-pages to be published automatically as well.
- Discussed to tentatively aim for APIStrat for the release of OAS 3.1.0. Next meeting we'll go over the list at #1466 and discuss which 2-3 features are the most important for us to get in, decision shall be made with a @OAI/tsc vote.
