### ISSUE TITLE
JsonPatchDocument<T> - Expose the Generic Type

### ISSUE THREAD

**Issue by jonmeyerson** [OAI/OpenAPI-Specification#1633]
Not sure this is the right place. When I create a API method with [JsonPatchDocument<T> ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.jsonpatch.jsonpatchdocument-1?view=aspnetcore-2.1)
The resulting json does not have an indication of what type T is. The return type is just the list of operations. I don't think this documents well the format that should be passed in. Also tools like autorest do not have the type to use to generate clients that can be called in an object oriented way. 

I think this should be possible from reading the json spec.

```
var result = new JsonPatchDocument<Model>();
result.Replace(model=>model.propertyA, "g")
result.Remove(model=>model.PropertyB)
result.Operations.Select(x => new { x.op, x.from, x.path, x.value })
```

**Comment by darrelmiller** [comment]
Hey @jonmeyerson This isn't the right repo.  Try here https://github.com/aspnet/Home/issues
