### ISSUE TITLE
Swagger converter throws error when converting 2.0 to 3.0

### ISSUE THREAD

**Issue by preithig** [OAI/OpenAPI-Specification#1639]
Hi,

We are trying to convert the swagger 2.0 to OpenAPI(3.0) using the library io.swagger.v3.parser.converter.SwaggerConverter.java. It is throwing error.
Attached the file for reference. It is a valid Swagger 2.0 file
[petStore.zip](https://github.com/OAI/OpenAPI-Specification/files/2212597/petStore.zip)

**Comment by hkosova** [comment]
Hi @preithig,

This repository is for the OpenAPI Specification itself and does not cover tools/libraries. The Swagger Parser repository is https://github.com/swagger-api/swagger-parser, please open an issue there.

**Comment by MikeRalphson** [comment]
I see @preithig has opened https://github.com/swagger-api/swagger-parser/issues/776.

Thanks @hkosova !
