### ISSUE TITLE
I think a link to the specification shoud be add to the website.

### ISSUE THREAD

**Issue by diguage** [OAI/OpenAPI-Specification#1641]
I clicked almost all menu to find the link to the specification for the first time. But I did not find. My friends sent <https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md> to me.

After a few days, a friends sent <https://swagger.io/resources/open-api/> to me. It is more readable.

I think many people have the same problem. So I think **a link to the specification shoud be add to the website.**

**Comment by MikeRalphson** [comment]
This is in progress. Will update this issue when completed.

**Comment by handrews** [comment]
This was eventually done at some point- it's the "Latest" link under the "Specifications" tab at https://www.openapis.org/ (which is the OpenAPI web site proper- swagger.io is for the Swagger tool suite).  While not identical to the formatting on the Swagger web site, it is much nicer than the GitHub document http://spec.openapis.org/oas/v3.0.2
