### ISSUE TITLE
Referenc/Link Internal Yaml File

### ISSUE THREAD

**Issue by rqdzs** [OAI/OpenAPI-Specification#1648]
So i'm using oas 3.0 to document an api but i'm having a problem. I would like to reuse  enum in model (object) inside an object propetie. Like this: 

![p](https://user-images.githubusercontent.com/19806884/43604116-514c233a-966b-11e8-8d22-7c582cc4c4ff.PNG)

If is not possible, i would like options to refenrence or link this model into this object prorpetie.

**Comment by tedepstein** [comment]
@rqdzs , I see a couple of problems here: 

1. The `$ref` value is pointing to `EquipmentModelTypes` as a root-level object in `/definitions/definitions.yaml`. Is this accurate? 
    * If `definitions.yaml` is an OpenAPI document, it would have reusable definitions in `/components/schemas`, so your full `$ref` value should be `/definitions/definitions.yaml#/components/schemas/EquipmentModelTypes`.
    * If `definitions.yaml` follows the JSON Schema convention, it would have reusable definitions under a `/definitions/` object, so your full `$ref` value should be `/definitions/definitions.yaml#/definitions/EquipmentModelTypes`
    * If `definitions` doesn't follow the structure of an OpenAPI document or a JSON Schema document, that's fine, just unconventional.
1. From your description, the `EquipmentModelTypes` schema definition contains an `enum` assertion with all of the allowed values, and you want to reuse that definition in `ApiEquipmentDT0V1` as the `model` property subschema. In that case, `model` should not have its own `type`, `description` and `examples` properties. It should only have a `$ref` property that refers to the schema definition. 

Maybe I am missing your intent here. If the above suggestions don't solve your problem, please post the contents of `definitions.yaml` so I can better understand what you're trying to accomplish.

**Comment by rqdzs** [comment]
Yes, I'm using Open API with ReDoc support ..... That helped me a lot, thanks for the quick response, very enlightening :)
