### ISSUE TITLE
Using $ref in an example block

### ISSUE THREAD

**Issue by krishamoud** [OAI/OpenAPI-Specification#1658]
Hi, I'm using a `$ref` in an example block and everything works almost exactly how I want except for this one behavior.

The definition looks like this:
```
SubscriptionType:
    [...]
    example:
      autorenew: true
      cycle_days: 30
      id: 33920
      name: "my 1337 subscription"
      terms:
        - $ref: '#/components/schemas/SubscriptionTypeTerm/example'
```

But the output looks like this

```
{
    "autorenew": true,
    "cycle_days": 30,
    "id": 33920,
    "name": "my 1337 subscription",
    "terms": [{
        "description": "every 3 months",
        "enabled": true,
        "id": 33922,
        "name": "3monthly",
        "num_cycles": 3,
        "subscription_type_id": 33920,
        "$$ref": "#/components/schemas/SubscriptionTypeTerm/example"
    }]
}
```

It's everything that I want except I don't want the `"$$ref": "#/components/schemas/SubscriptionTypeTerm/example"` at the bottom of the object.

Am I missing something obvious or am I using refs incorrectly?

Possibly related: https://github.com/swagger-api/swagger-ui/issues/4021

**Comment by silkentrance** [comment]
So what you actually want is to include the examples from your ``$ref`` to be included in your example, and recursively so.

**Comment by MikeRalphson** [comment]
What tooling are you using? The use of a `$$ref` property is non-standard (if the `$ref` value needs preserving, it should be done with an `x-` specification extension). This is probably an issue best raised on the appropriate tool repository.

**Comment by silkentrance** [comment]
@MikeRalphson I think he is using the basic swagger codegen. And, considering the fact that not to much effort is made to work on existing issues over at the swagger codegen project, raising an issue over there is like waiting for Godot.

Regardless, I still think that the use case of including an example from another definition may be a invalid use case, as it is too complex and may not be solved during code generation, nor by the existing framework.

**Comment by silkentrance** [comment]
@krishamoud as a work around, are you able to post process the file, removing all lines that include the ``$$ref``?

**Comment by krishamoud** [comment]
Sorry, I'm on holiday at the moment and won't be able to look at this for a couple day.  I'll keep this updated when I get back though.

**Comment by krishamoud** [comment]
So I found a way around this.  Instead of adding a completely separate `example` block I just add examples to every field in the component definition.  

Example:

Below works
```
SubscriptionType:
      type: object
      properties:
        store_id: 
          type: integer
        name:
          type: string
          example: my 1337 subscription
        cycle_days:
          type: integer
          example: 30
        terms:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionTypeTerm'
        auto_renew:
          type: boolean
          example: false
        id:
          type: integer
          example: 33920
```

Below results in `$$ref`
```
SubscriptionType:
    [...]
    example:
      autorenew: true
      cycle_days: 30
      id: 33920
      name: "my 1337 subscription"
      terms:
        - $ref: '#/components/schemas/SubscriptionTypeTerm/example'
```
