### ISSUE TITLE
Can I pass a ref of model to another model?

### ISSUE THREAD

**Issue by abkarino** [OAI/OpenAPI-Specification#1659]
My API respond with something like this:
```javascript
{"result":"successful","code":200,"data":{......}}
```
I wanna save that in component /schemas/ but I can't find a way to pass `data` model grammatically based on the endpoint.
Ex: If I open `/cat` it should respond with success schema as mentioned above and data of type model `cat`. But if I open `/dog` it should use success schema with data defined as `dog` model.

**Comment by silkentrance** [comment]
Why do you replicate the HTTP result code and multiple times so?
AFAIK both ``result`` and ``code`` are redundant.

Regardless, please rephrase your question, as I am not able to understand what your are asking for.

**Comment by handrews** [comment]
No response for a year and a half to the follow up question, assuming this is no longer relevant.
