### ISSUE TITLE
Describing conditions that will cause an error response 

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#166]
This is for Swagger.next

With Swagger we can define error responses but there is no way to describe what will cause an error response. Things like auth, missing or invalid parameter can easily described in the specs. Should we have a way for such description in Swagger?

**Comment by jasonh-n-austin** [comment]
FWIW, this could also be defined by specifying HTTP status codes which occur for the given errors (401/403 for auth, 400 for validation errors etc).

#236 seems to address the perceived need for more error-specific handling of responses, let's look at it from that perspective.
