### ISSUE TITLE
Q: defining order for paths

### ISSUE THREAD

**Issue by KES777** [OAI/OpenAPI-Specification#1660]
We have next schema:
```
paths:
  /timezones/general:
    get:
      ....
  /timezones/{id}:
    parameters:
      - $ref: '#/components/parameters/resourceID'
    get:
      ....

components:
  parameters:
    resourceID:
      description: Resource identificator
      in: path
      name: id
      required: true
      schema:
        type: integer
        format: int32
```

This schema fails with error:

    "In call to App::Helper::resource(), the 'id' parameter (\"general\") is not of type Int

That is because `paths` is object which keys are unordered (at least at perl). and sometimes `/timezones/{id}` path definition come before `/timezones/general` path definition and hide it.

When we define these paths in application. The order of path definition is hardcoded and such problem is not araise: definition for `/timezones/general` is always come before `/timezones/{id}`.

What would be recommendation to resolve this problem when defining  such paths with openapi3 schema?

**Comment by KES777** [comment]
Helped on forum. [DOC](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#patterned-fields):

> When matching URLs, concrete (non-templated) paths would be matched before their templated counterparts. 

Here `/timezones/general` is concrete and should be matched first.

**Comment by jhthorsen** [comment]
Maybe you want to steal this sub: https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/c7f5608a5aec0a318668070e89ca7f5a54d268fd/lib/Mojolicious/Plugin/OpenAPI.pm#L361-L365
