### ISSUE TITLE
Schema names

### ISSUE THREAD

**Issue by DmitriiTrofimov** [OAI/OpenAPI-Specification#1661]
What is schema name in discriminator context? 

1. `$ref: '#/components/schemas/Dog'` - schema name is `Dog`
2. `$ref: '../schemas/Monster.yaml'` - `Monster` is schema name or not?
3. `$ref: '../schemas.yaml#/Monster'` - `Monster` is schema name or not?

**Comment by MikeRalphson** [comment]
I would add `$ref: '#/components/schemas/Dog/properties/bark` to the list. See also https://github.com/Mermade/oas-kit/issues/75

**Comment by silkentrance** [comment]
I think that both

```
2. $ref: '../schemas/Monster.yaml' - Monster is schema name or not?
3. $ref: '../schemas.yaml#/Monster' - Monster is schema name or not?
```

are invalid as they may or may not resolve to a single entity. With ``3.`` being altogether invalid as the path is not valid. There is no top level ``Monster``, it needs to reside underneath the ``components``.

**Comment by tedepstein** [comment]
@silkentrance , 

> I think that both
>
> 2. $ref: '../schemas/Monster.yaml' - Monster is schema name or not?
> 3. $ref: '../schemas.yaml#/Monster' - Monster is schema name or not?
> are invalid as they may or may not resolve to a single entity. 

It's OK to have references to a file URL without a fragment, as long as the contents of that file conform to the expected type.  Presumably in this case we're looking for a Schema Object; so if the file contents conform to that, the `$ref` is OK.  There are examples of this in the spec.

> With 3. being altogether invalid as the path is not valid. There is no top level Monster, it needs to reside underneath the components.

A top-level `Monster` property would make the referenced file invalid as an OpenAPI document. But Reference Objects don't have to refer to values in a valid OpenAPI document.  The referents can be OAS documents, single-object files (like the ones mentioned above), JSON Schema files, or any valid JSON or YAML file, as long as the path resolves to an object within that file that conforms to the expected type.

**Comment by tedepstein** [comment]
As for the original question, AFAIK, there's no definitive "name" of a schema object. That said, it's useful to be able to assign a name for documentation purposes. In our tooling, we infer names using an algorithm similar to what you've described, but we also recognize `title` properties as name overrides. 

There are also `$id` keywords, but I don't understand those well enough to say whether they might be applicable for your use case.

**Comment by DmitriiTrofimov** [comment]
@tedepstein @silkentrance @MikeRalphson Thanks!

**Comment by handrews** [comment]
@tedepstein @DmitriiTrofimov in standard JSON Schema, `$id` is for setting a URI that can be referenced with a `$ref` elsewhere.  If the URI is not just a fragment, then it also changes the current base URI, which is where people start getting confused.  We added a lot of examples of how this works in the latest [JSON Schema Core draft](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.4).

**Comment by DmitriiTrofimov** [comment]
@handrews Thanks!
