### ISSUE TITLE
Multiple file with extra attributes for each file

### ISSUE THREAD

**Issue by zlx** [OAI/OpenAPI-Specification#1667]
Hi, guys

In some use case, we want to upload some files(eg: attachments) with extra information(eg: points).

With normal `multipart/form-data`, with can post form like a hash:

![image](https://user-images.githubusercontent.com/1835854/44250018-4b8fb900-a225-11e8-9663-a21b6ec9b5f2.png)

But I fail to describe it via OpenAPI Spec.

I tried follow this links but it not work.

[https://swagger.io/docs/specification/describing-request-body/file-upload/](https://swagger.io/docs/specification/describing-request-body/file-upload/)
[https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#parameterObject)

here is my spec gist:

```
      requestBody:
        required: true
        content:
          'multipart/form-data':
            schema:
              type: object
              properties:
                attachments:
                  type: array
                  items:
                    type: object
                    properties:
                      file:
                        type: string
                        format: binary
                      points:
                        type: integer
                      inherit:
                        type: boolean
                      destroy:
                        type: boolean
                      id:
                        type: integer
```

Am I missing some thing for this use case. Thanks for any help.

**Comment by andreas-eternach** [comment]
Hi i want to upload multiple attachments in one request.

However i do not understand how you address the binaries when implementing this solution.

Therefore i propose to have an addressing scheme, one multipart-request with one part for the json-object and for each attachment an own part:

**part 1 (json):**
{
 firstfile: "attachment: filename1",
 secondfile: "attachment: filename2"
}

**part 2: binary file for filename1**
**part 3: binary content for filename2**

**Comment by handrews** [comment]
@zlx your example looks correct - I suspect whatever tools you were using did not implement it fully/correctly at the time.  I'm going to close this, with apologies for it getting ignored for so many years.  Feel free to comment if I've missed something and I can re-open this.

@andreas-eternach you should be able to just define multiple binary fields just like multiple of any other fields.  It's not clear to me if there is something else involved here - if so, and if you're still interested after all this time, please open a new issue so we keep one topic per issue.
