### ISSUE TITLE
Provide additional detail in the documentation regarding the differences in Licensing vs. Terms of Service

### ISSUE THREAD

**Issue by crileyarch** [OAI/OpenAPI-Specification#1672]
Currently it may not be clear to OpenAPI consumers on the proper application of the License Object vs. Terms of Service. Should we provide additional detail on what a License is vs. a Terms of Service document? My interpretation is:

- Terms of Service represents the legal binding agreement you enter into using the Provider's API as a Consumer. 
- License represents the financial agreement you enter into when consuming the API

**Comment by MikeRalphson** [comment]
Clarification in the spec may be necessary, but `license` does not refer in any way to a financial agreement. I have previously referred to this as declaring the license for the **design** of the exposed API (e.g. for the content of the OAS document itself), and given as an example that it is the license you must comply with if you were to (say) re-implement the API (if I remember correctly, the rest of the TSC broadly agreed with this interpretation, but it is not gospel).

The `termsOfService` is merely metadata which indicates where the terms and conditions for the use of the API are to be found. It does not indicate in and of itself that by using the OAS document or the API that you have accepted the terms given at that URL (consider, that they may change over time) or whether or not they legally bind you.

**Comment by crileyarch** [comment]
thx @MikeRalphson for your reply.
