### ISSUE TITLE
Add allowReserved to Security Scheme Object

### ISSUE THREAD

**Issue by Raptor399** [OAI/OpenAPI-Specification#1676]
I ran into swagger-api/swagger-ui#4218 and it occurred to me that perhaps the `allowReserved` option of [Parameter Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameter-object) could also be added as an optional parameter to [Security Scheme Objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object), allowing for a definition like:

    components:
      securitySchemes:
        KeyA:
          type: apiKey
          in: cookie
          name: key-a
          allowReserved: true

If `allowReserved` serves valid use cases for query parameters in Parameter Objects, it would be consistent to also allow this this flag for similar use cases in Security Scheme Objects.

**Comment by darrelmiller** [comment]
Currently we don't limit the characters allowed in security parameters and don't think AllowReserved would add significant value.  If this is essential for your scenario we recommend using an extension to describe allowed characters.
