### ISSUE TITLE
Unclear which edition of ECMA-262 is used as regex format

### ISSUE THREAD

**Issue by dvh** [OAI/OpenAPI-Specification#1687]
While issue #880 links to http://www.ecma-international.org/publications/standards/Ecma-262.htm ([just as JSON Schema does](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html), the OpenAPI Specification [deeplinks to the 5.1 edition](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5) in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#schema-object. Is this a typo or is edition 9.0 not supported (yet)?

**Comment by MikeRalphson** [comment]
Edition 9.0 appears to have been released 11 months **after** OpenAPI 3.0.0, so it should not be a surprise that it is not supported. :slightly_smiling_face: 

It may be that a baseline version was chosen to achieve the broadest tooling compatibility :question:

**Comment by dvh** [comment]
I don't think this is made very clear in the docs. Perhaps adding the specific version to the docs (not only in the deeplink) will help.

**Comment by MikeRalphson** [comment]
A PR for discussion would be warmly welcomed.

**Comment by handrews** [comment]
This got revisited and (assuming the PR is accepted) resolved in issue #1985 and PR #1987.

**Comment by handrews** [comment]
@MikeRalphson perhaps close this in favor of #1985 since it has more details?

**Comment by MikeRalphson** [comment]
Agreed.
