### ISSUE TITLE
Use $ref in info section

### ISSUE THREAD

**Issue by SORC3r3r** [OAI/OpenAPI-Specification#1689]
In former swagger versions it was possible to use $ref in the info section as well as in the path section.
In the latest OpenAPI-Specification it ist not.
Will this be implemented again?

**Comment by MikeRalphson** [comment]
I don't believe this was ever allowed in Swagger v1.2 or Swagger / OpenAPI 2.0 - though some tooling may have taken a more lax (read: non-compliant) approach.
