### ISSUE TITLE
how to add headers to the responses?

### ISSUE THREAD

**Issue by skyxh** [OAI/OpenAPI-Specification#1697]
the comment content is to add.But

```yaml
responses:
        '200':
          description: OK
          schema: 
            $ref: '#/definitions/Application'
        '401': 
          description: Unauthorized
        '403': 
          description: Forbidden
        '404': 
          description: Not Found,  
        # description: A simple string response
        # headers:
        #   X-Rate-Limit-Limit:
        #     description: The number of allowed requests in the current period
        #     type: integer
        #   X-Rate-Limit-Remaining:
        #     description: The number of remaining requests in the current period
        #     type: integer
        #   X-Rate-Limit-Reset:
        #     description: The number of seconds left in the current period
        #     type: integer
        # headers:
        #   Cache-Control:
        #     description: no-cache, no-store, max-age=0, must-revalidate
        # Content-Security-Policy: default-src 'self'
        # Content-Type: application/json;charset=UTF-8
        # Date: Tue, 25 Sep 2018 08:19:40 GMT
        # Expires: Thu, 01 Jan 1970 00:00:00 GMT
        # Pragma: no-cache
        # Strict-Transport-Security: max-age=16000000; includeSubDomains; preload;
        # Transfer-Encoding: chunked
        # X-Application-Context: microservice:dev:20880
        # X-Content-Type-Options: nosniff
        # X-Frame-Options: SAMEORIGIN
        # X-XSS-Protection: 1; mode=block
```

**Comment by MikeRalphson** [comment]
@skyxh I have formatted your example and moved what looks like a truncated issue description from the issue title to the main body. Do you want to edit your question so we know what the 'but...' refers to?

**Comment by MikeRalphson** [comment]
As you look to be using OAS 2.0, see the examples at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#response-object-examples

**Comment by skyxh** [comment]
put:
      tags:
        - secureAccess
      summary:  修改应用的设备状态时间配置
      operationId: modifyApplicationFromNaUsingPUT_1
      x-Typical:
        - 平台根据设备上报数据时间检测设备状态，来修改应用设备状态时，需调用此API
      description: NA对单个应用下设备状态进行配置
      x-Note: |
        应用已鉴权，在header中携带参数app_key和Authorization: Bearer {accessToken}
        如明确该应用下挂都是周期性上报数据的设备类型，则必须在创建应用之后首先调用这个接口设备异常和离线周期时间，然后再添加设备。
      x-isExistException: true
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/app_key'
        - $ref: '#/parameters/Authorization'
        - name: id
          in: path
          description: 应用id
          required: true
          type: string
        - name: modifyDTO
          in: body
          description: 设备状态时间配置
          required: true
          schema: 
            $ref: '#/definitions/ApplicationModifyDTO'
      responses:
      # header:
      #   Cache-Control : no-cache, no-store, max-age=0, must-revalidate
      #   Content-Type : application/json;charset=UTF-8
      #   Date : Tue, 25 Sep 2018 08:52:10 GMT
      #   Expires : Thu, 01 Jan 1970 00:00:00 GMT
      #   Pragma : no-cache
      #   Transfer-Encoding : chunked
      #   X-Application-Context : microservice:dev:20880
      #   X-Content-Type-Options : nosniff
      #   X-Frame-Options : SAMEORIGIN
      #   X-XSS-Protection : 1; mode=block
        '200':
          description: OK
          schema:
            type: string
          headers:  //the headers are not added to response successfully
            X-Rate-Limit-Limit:
              description: The number of allowed requests in the current period
              type: integer
            X-Rate-Limit-Remaining:
              description: The number of remaining requests in the current period
              type: integer
            X-Rate-Limit-Reset:
              description: The number of seconds left in the current period
              type: integer
            enum:
              - '100'
              - '101'
              - '102'
              - '103'
              - '200'
              - '201'
              - '202'
              - '203'
              - '204'
              - '205'
              - '206'
              - '207'
              - '208'
              - '226'
              - '300'
              - '301'
              - '302'
              - '303'
              - '304'
              - '305'
              - '307'
              - '308'
              - '400'
              - '401'
              - '402'
              - '403'
              - '404'
              - '405'
              - '406'
              - '407'
              - '408'
              - '409'
              - '410'
              - '411'
              - '412'
              - '413'
              - '414'
              - '415'
              - '416'
              - '417'
              - '418'
              - '419'
              - '420'
              - '421'
              - '422'
              - '423'
              - '424'
              - '426'
              - '428'
              - '429'
              - '431'
              - '451'
              - '500'
              - '501'
              - '502'
              - '503'
              - '504'
              - '505'
              - '506'
              - '507'
              - '508'
              - '509'
              - '510'
              - '511'
        '201':
          description: Created
        '400':
          description: Bad Request
          x-Error:
            100022:
              x-Description: The input is invalid.
            100228:
              x-Description: AbnormalTime must be greater than 10 minute and less than 129590.
            100229:
              x-Description: OfflineTime must be 10 minutes longer than the abnormalTime and less than 129600.    
        '401':
          description: Unauthorized
          x-Error:
            100002:
              x-Description: Invalid access token..
        '403':
          description: Forbidden
          x-Error:
            100217:
              x-Description: The application hasn't been authorized.
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          x-Error:
            100203:
              x-Description: The application is not existed.

**Comment by MikeRalphson** [comment]
Please could you state exactly what you are trying to do and what, if any, problems you are currently seeing when trying to do it?

**Comment by kojiDev** [comment]
@MikeRalphson close it? Author clearly ain't gonna elaborate on this
