### ISSUE TITLE
Specify how relative URLs in rich text descriptions should be resolved

### ISSUE THREAD

**Issue by aibaars** [OAI/OpenAPI-Specification#1701]
For URL valued properties the specification defines that relative URLs must be resolved against the server-url. However, how relative URLs in descriptions are to be resolved is not defined. 

I think it would make sense to resolve those against the server-url as well.

**Comment by MikeRalphson** [comment]
As the markdown might perhaps be being rendered into HTML to make the links useful, do such renderers often provide the ability to specify the base URL?

**Comment by aibaars** [comment]
I don't know to be honest. I mostly use swagger UI and swagger editor for viewing, and as far as I know swagger does not provide the ability to specify a base url for links in markdown descriptions.

**Comment by handrews** [comment]
Merged to both 3.0.4 and 3.1.1 - we'll sync up 3.2.0 once those are ready to ship.
