### ISSUE TITLE
Allow shorthand $ref for parameters and responses 

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#171]
This is 2.1 proposal 

In 2.0 we have a shorthand definition for schemas. If user do not provide `#/definitions/` prefix, we will prepend it to their value in `$ref` if it's a `schema` value.

This should work for `parameters` and `responses` too

Example:

```yaml
swagger: '2.1'
info:
  version: "1.0.0"
  title: shorthand ref example
paths:
  /:
    get:
      parameters:
        - $ref: size
      responses:
        $ref: 200
        
        
responses:
  200:
    description: Success

parameters: 
  size:
    name: size
    in: query
    required: true
    type: string
```

Resolver should understand the context of `$ref` and look in proper object. 

Related to #132

**Comment by jasonh-n-austin** [comment]
Agree with @whitlockjc here. Especially with clarity recently added in `guidelines/REUSE.md`, this would clearly cause issues with file/uri issues.
With a renewed emphasis on separate files for definitions (a must in microservice environments with shared definitions), I can't see this working out.

Closing, as this is pretty old and seems like a non-starter. Re-open if you'd like to debate anything here.

**Comment by webron** [comment]
We just need to remember to put the same restriction in the current version in the next one as well (2.0 explicitly prohibits it, even though it *is* supported by JSON References).

**Comment by jasonh-n-austin** [comment]
@webron JSON Reference allows for adding root-level elements, and referring to them directly (which _maybe_ shouldn't be allowed, but @whitlockjc would probably disagree):
```
paths:
  /:
    get:
      parameters:
        - $ref: size
size:
  name: size
  in: query
  required: true
  type: string
```

The OP was suggesting something very different, which is to infer `#/definitions/parameters/` to be prepended onto `size`. This is the issue that seems to be a non-starter, due to a lack of conformance to JSON Reference, and overall tooling confusion.

**Comment by webron** [comment]
I believe the author refers to inline vs canonical dereferencing as defined at http://json-schema.org/latest/json-schema-core.html#anchor30 - and we're decided to explicitly support only canonical iirc.

**Comment by whitlockjc** [comment]
My agreement depends on what we call a reference.  If it's a JSON Reference, then a reference that does not start with a `#` is treated as a URI and a URI with a value of `size` is treated as a relative reference to a resource named `size` relative to the current document, no different than `./size`.  *(I could be wrong but I remember reading this and the URI libraries I've used seem to conform to this as well.)* If we come up with our own standard for references, I'm sure we could make shorthand make sense however we deem fit.

**Examples**

# Node.js (url.parse)

```js
URL.parse('Pet')
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: 'Pet',
  path: 'Pet',
  href: 'Pet' }
```

# Node.js (uri-js)

```js
URI.parse('Pet')
{ scheme: undefined,
  userinfo: undefined,
  host: undefined,
  port: undefined,
  path: 'Pet',
  query: undefined,
  fragment: undefined,
  reference: 'relative' }
```

**Comment by whitlockjc** [comment]
I do agree with @webron that JSON Schema muddied the waters.
