### ISSUE TITLE
Anchor Links in the spec do not work anymore

### ISSUE THREAD

**Issue by cebe** [OAI/OpenAPI-Specification#1726]
Seems github filters the `<a name="...">` tags...

**Comment by cebe** [comment]
As I am very sure that this has been working fine before it might be worth contacting github support and ask to revert the change or otherwise fix it.

**Comment by Gi60s** [comment]
It's not all links, just any links that have multiple words. For example:

Works: `#schema`
Does not work: `#infoObject`

One way to fix is to update the multi-word links to use dashes instead of camel case. For example, convert `#infoObject` to `#info-object` and links will start working again. 

I'm not sure why Github ever supported camel case links. I've haven't seen another markdown to HTML converter support that.

**Comment by cebe** [comment]
With dashes are the links that are automatically generated by github. camelCase are anchors added in the spec markdown. If you render the spec outside of github links would be working. The filtering done here is specific to github.

**Comment by MikeRalphson** [comment]
Also affects `README`s, reported on #1734

**Comment by cebe** [comment]
I have contacted github support about this.

**Comment by cebe** [comment]
Looks like they fixed it. It's working again for me. Close the issue if you confirm.

**Comment by MikeRalphson** [comment]
Thanks @cebe I'm still seeing the problem, but it may be a cacheing issue.

**Comment by Gi60s** [comment]
It doesn't work for me yet. Tried on two browsers and even disabled cache.

**Comment by ramsey** [comment]
It's still not working for me. Maybe it's cached at an edge location somewhere?

**Comment by shockey** [comment]
Still broken for me as well 😕

**Comment by webron** [comment]
I'm also in touch with GitHub's support about it, will update when I know more.

**Comment by cebe** [comment]
Got a reply from github support today:

> Hey Carsten,
> 
> Our Engineering Team shipped a fix for those anchor links.
> 
> Please let us know if you have any further trouble with it.
> [...]

**Comment by webron** [comment]
Thanks, @cebe - got the same reply. Let the anchor-following resume!
