### ISSUE TITLE
Duplication of tags in operation level, can be restricted as in API Level

### ISSUE THREAD

**Issue by r-sreesaran** [OAI/OpenAPI-Specification#1727]
Duplication of tags in operation level, can be restricted as in API Level. 

Current Specification 
A list of tags used by the specification with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. Not all tags that are used by the Operation Object must be declared. The tags that are not declared MAY be organized randomly or based on the tools' logic. **Each tag name in the list MUST be unique.**

why is the uniqueness is not mandated for operation level.

**Comment by MikeRalphson** [comment]
At first glance this appears to be an oversight. Would you like to create a PR to fix it for version 3.1.0 on the `v3.1.0-dev` branch?

**Comment by r-sreesaran** [comment]
Sure I will create a PR to fix it in 3.1.0.

**Comment by MikeRalphson** [comment]
TSC more discussion is required on the current (expected) behaviour before we take the change in #1729 further, which might break existing 3.0.x documents.

**Comment by r-sreesaran** [comment]
@MikeRalphson I have adapted the PR as per suggestion of @earth2marsh.

**Comment by earth2marsh** [comment]
This bubbled back up on today's TSC call. 

Thinking about this again, while I do think that listing the same tag twice may be considered an authoring error, I don't believe it is necessary to specific this behavior in the spec. I would agree that the duplicate tag has no meaning and could reasonably be either ignored or duplicated by any tooling according to the author's preference. I would not consider duplicate tags to cause an invalid spec, though I could imagine that a spec editor tool might helpfully flag the duplicate.

**Comment by handrews** [comment]
Seems like we decided against this in 2020, no further comment so closing.
