### ISSUE TITLE
Spark Implementation support

### ISSUE THREAD

**Issue by juliopescuite** [OAI/OpenAPI-Specification#1732]
Hello,

Is there any plans to add OpenAPI support to http://sparkjava.com/ ?

It would be very nice to have it, maybe I can even contribute to this.

Looking forward for an answer,thanks in advance, and congrats for this great specification.

**Comment by MikeRalphson** [comment]
You would need to check with that project, for example see https://github.com/perwendel/spark/issues/258

I'll leave this issue open for a week or so in case other members of the community also wish to help. Good luck!

**Comment by juliopescuite** [comment]
Thanks @MikeRalphson

**Comment by MikeRalphson** [comment]
Closing as above.
