### ISSUE TITLE
Wrong structure mapping in specification

### ISSUE THREAD

**Issue by kibertoad** [OAI/OpenAPI-Specification#1735]
https://swagger.io/docs/specification/components/ defines following mapping between old and new structures:

OpenAPI 2.0                    OpenAPI 3.0
'#/definitions/User'         → '#/components/schemes/User'
'#/parameters/offsetParam'   → '#/components/parameters/offsetParam'
'#/responses/ErrorResponse'  → '#/components/responses/ErrorResponse'

'#/components/schemes/User' is wrong, it should be 'schemas', not 'schemes'.

**Comment by MikeRalphson** [comment]
Thanks. I think the correct repo for that site is https://github.com/swagger-api/swagger.io - reporting it there will reach the right people.

**Comment by kibertoad** [comment]
@MikeRalphson Thank you for pointing into the right direction!
