### ISSUE TITLE
Reinstate validation of JSON Schemas (and examples) in build process

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1739]
This issue is a place-holder to ensure this action isn't forgotten.

If we want to validate OAS instances beyond compliance with our JSON schemas, we would need to make a choice on which validator(s) to use - this would not be an endorsement.

Can occur after the resolution of #1270 / #1236

**Comment by AllenChong** [comment]
on issue

**Comment by MikeRalphson** [comment]
Also examples against OAS schema instances, ditto.

**Comment by MikeRalphson** [comment]
Bump. Should this be reworked into a GitHub action?

**Comment by Bellangelo** [comment]
@MikeRalphson I can make the script to run in a Github action.

**Comment by handrews** [comment]
@Bellangelo we do have [this github workflow](https://github.com/OAI/OpenAPI-Specification/blob/main/.github/workflows/schema-tests.yaml) which might actually do at least some of what is needed?  I think the first step is to see what we are and aren't doing, as some work on GitHub automation might not have updated this issue.  If you can take a look at that, a PR adding anything we're still missing would be most welcome.

**Comment by handrews** [comment]
@Bellangelo btw if you are looking for other automation/build-ish ways to contribute, you might want to check out our [Automation & Infrastructure Project](https://github.com/orgs/OAI/projects/4).

**Comment by Bellangelo** [comment]
Hi @handrews, sorry for the late reply but things got busy. You are indeed correct that some thing are now covered. I have opened a [PR](https://github.com/OAI/OpenAPI-Specification/pull/3784) with a detailed explanation of what is missing and what it isn't.

> btw if you are looking for other automation/build-ish ways to contribute, you might want to check out our [Automation & Infrastructure Project](https://github.com/orgs/OAI/projects/4).

Thank you. This is also where I found this issue originally.
