### ISSUE TITLE
Schema does not enforce requirement of array items object

### ISSUE THREAD

**Issue by whitlockjc** [OAI/OpenAPI-Specification#174]
In the 1.2 and 2.0 specifications, it says this regarding the `items` property: `Required if type is "array"`.  The problem is I can create a property like this without the JSON schema validator throwing an error:

``` js
"ids": {
  "type": "array"
}
```

**Comment by whitlockjc** [comment]
I wonder if we should treat a missing `items` the way JSON Schema handles missing `additionalProperties` and default to `{}` which means it matches anything.  I think from a consistency perspective, this would make sense and it's pretty simple to support from a tooling perspective.

The only thing driving this right now is an inconsistency between the specification documentation and the JSON Schemas.  What if we were to just remove this requirement from the Swagger specification documents and support it as discussed above?

**Comment by webron** [comment]
Wish we could, but really, at this point it seems a bit late for it. I'll do my best trying to enforce it in the schema, though if I recall correctly, it was hell (and possibly impossible).

**Comment by whitlockjc** [comment]
Well, it's moot now.  If it's here, I'll continue doing what I'm doing.  I'm just saying the lack of `items` is handled inconsistently when compared with other places where JSON Schema has optional things, like `additionalProperties`.

**Comment by webron** [comment]
There are a few inconsistencies in the spec :-/ Just need to try and improve in the next version.

**Comment by handrews** [comment]
Not sure if this is still an active concern.  if anyone is still curious as to why JSON Schema works this way, it has to do with the difference between assertions, annotations, and data model keywords (which is discussed more clearly in the soon-to-be-published draft-07).

`items` is a data model keyword.  It applies a subschema to part of an instance based on the data model (in particular, if the instance is an array, it applies the subschema to ever element of an array and ANDs the results- contrast with `contains` which applies the subschema and ORs the results)  Note the "if it's an array, then apply the subschema" approach, with the implicit "else don't do anything for this keyword" clause.

`type` is an assertion.  It evaluates a constraint against the instance and produces a boolean result.

The third category, annotations, include keywords like `title` and `default`.

Data model keywords themselves never cause validation to fail.  They apply subschemas which have assertions, and it is the assertions in the subschemas which cause the pass or fail.  

This seems weird for use cases like OpenAPI.  But consider using JSON Schema to scan arbitrary data for objectionable language with a regex.  You don't know or care what data types you'll get.  Objects, arrays, strings, numbers, booleans, nulls, nested structures of arbitrary complexity, etc.  You just want to apply your regex using `pattern` to every string in the document.

If `item` behaved as an assertion, this would be very hard.  You could do it with `anyOf` but it would be very complicated.  Preserving the data model vs assertion split makes it easy to do this sort of "validation" with JSON Schema.

FWIW, JSON Schema does in fact treat a lack of `items` the same as `"items": {}`, which only works if `items` is **not** an assertion of array-ness.

**Comment by handrews** [comment]
@webron I think this is more or less a dup of #1891 although there is more information here.  Fairly certain we don't need to keep both of them open.

**Comment by handrews** [comment]
We decided not to fix this in the other issue since the schema is not intended to catch all errors, and this is against old OAS versions that aren't being worked on anymore anyway.  I think this is safe to close.
