### ISSUE TITLE
[C#] Impossible to switch content-type request to Xml

### ISSUE THREAD

**Issue by SebastienArnold** [OAI/OpenAPI-Specification#1745]
In generated API localVarHttpContentType is hardcoded to application/json.
Can't be able to specify wanted contentType using configuration.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by SebastienArnold** [comment]
Sorry, miss on the repo effectively.
