### ISSUE TITLE
Implement Endpoint with multiple parameter more than 2 parameters in laravel 5.7

### ISSUE THREAD

**Issue by PandhuWibowo** [OAI/OpenAPI-Specification#1755]
I want to create API with endpoint like my.url/products/?color=brown&brand=adidas on laravel 5.7, how i get step to create like that. I need explaining how i do in controller, how i do in route (web.php)

I'm using query builder.
Thank you.

**Comment by MikeRalphson** [comment]
Depending on how the tools you're using actually work (this repository is for the specification itself only), you either want to start or end-up with a document that looks something like this:

```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: My API
servers:
- url: my.url
paths:
  /products:
    get:
      parameters:
      - name: color
        in: query
        schema:
          type: string
      - name: brand
        in: query
        schema:
          type: string
      responses:
        '200':
         description: OK
```

For more specific help with Laravel, it would be best to use the appropriate support channels for that project, or use a general purpose support forum such as StackOverflow.
