### ISSUE TITLE
Is oneOf supported inside #/components/schemas section?

### ISSUE THREAD

**Issue by mindstretch23** [OAI/OpenAPI-Specification#1758]
I tried to answer this by reading this entire thread at https://github.com/OAI/OpenAPI-Specification/issues/333, but still not 100% sure. 

I know the oneOf keyword can be used inside the requestBody object to reference alternative schemas. However, can someone confirm if oneOf is supported within the #/components/schemas section as well? 

For example:

```
components:
  schemas:
    ID:
      oneOf:
      - $ref: '#/components/schemas/ID1'
      - $ref: '#/components/schemas/ID2'
```

👆 doesn't throw an error in SwaggerHub editor, but it does not populate the interactive documentation (i.e. the ID object is missing in the interactive documentation)

I also tried this, which throws the error "bad indentation of a mapping entry"in the SwaggerHub editor:

```
components:
  schemas:
    ID:
      type: object
      oneOf:
      - $ref: '#/components/schemas/ID1'
      - $ref: '#/components/schemas/ID2'
```
I would like to use oneOf inside a schema that is referenced by a request body (as shown above). This creates much less repetition in my case because the two alternatives schemas that could be referenced in the request body with oneOf only differ by one property. One schema needs ID1 and the other needs ID2. There's about 7 other properties that are common across the two schemas, so if I use the oneOf keyword in the requestBody to reference alternative scheams (the way I know it works), then I'm repeating those 7 common properties.

Can someone help confirm if I can instead use oneOf inside #/components/schemas to avoid this repetition?

**Comment by MikeRalphson** [comment]
`oneOf` can be used inside any `schema object`, including those under `components/schemas`.

**Comment by mindstretch23** [comment]
@MikeRalphson Thanks.

Which syntax from my original comment is correct? Both seem to have issues. 

1. When using the 1st one, SwaggerHub editor doesn't throw an error in, but it does not populate the interactive documentation (i.e. the ID object is completely missing in the interactive documentation). Is this as-expected?

2. When using the 2nd one, the editor throws the error "bad indentation of a mapping entry"in the SwaggerHub editor

**Comment by mindstretch23** [comment]
I think what I'm actually seeing is automatic examples are not populating with oneOf...

I think thats a known limitation as described here, https://app.swaggerhub.com/help/openapi-3-support

Does that make sense? If so I can close this out

automatic examples for oneOf and anyOf schemas. A workaround is to add schema examples manually:

**Comment by MikeRalphson** [comment]
Yes, I think that's the case. BTW both of your examples are technically fine.

**Comment by mindstretch23** [comment]
@MikeRalphson  Thanks. I wonder why the 2nd one throws an error in the editor then = /

**Comment by MikeRalphson** [comment]
I suspect the editor might be doing some preprocessing on the yaml, but that's just a guess, and heading off topic for this repo.

**Comment by mindstretch23** [comment]
Got it. Thanks for your help @MikeRalphson. Closing this out now.
