### ISSUE TITLE
Is it possible to define locally referenced components in external schema objects?

### ISSUE THREAD

**Issue by kbsanders** [OAI/OpenAPI-Specification#1761]
Can an externally `$ref`'d Schema Object have its own locally defined set of `#/components` (or `#/definitions`)?

For example:

File: **openapi.yml**
```
openapi: 3.0.2
...
paths:
  /Foo:
    $ref: './endpoints/Foo/paths.yml'
```

File: **./endpoints/Foo/paths.yml**
```
post:
  operationId: PostFoo
  ...
  requestBody:
    content:
      application/vnd.api+json:
        schema:
           $ref: './post/requestBody.yml'
```

File: **./endpoints/Foo/post/requestBody.yml**
```
type: object
properties:
  data:
    oneOf:
      - $ref: "#/definitions/SimpleRequest" # Locally defined below
      - $ref: "#/definitions/ExtendedRequest" # Locally defined below
definitions:
  SimpleRequest:
    type: object
    properties:
      type:
        type: string
        enum:
          - SimpleRequest
      attributes:
        type: object
        properties:
          ...
  ExtendedRequest:
    type: object
    properties:
      type:
        type: string
        enum:
          - ExtendedRequest
      attributes:
        type: object
        properties:
          ...
```

I've searched and searched but so far have found no information on the subject.

**Comment by MikeRalphson** [comment]
My understanding is yes, you can ansolutely do this. There is no requirement that externally referenced documents comply with any specific schema, so `components` , `definitions` or `portrezeebie` are all fine.

When it comes to scope and fragment ids, the rule appears to be that the whole of the included document is in scope for local `$ref` resolution, then it is constrained by the fragment id prior to inclusion.

**Comment by MikeRalphson** [comment]
I also wrote a blog post which touched on this https://dev.to/mikeralphson/defining-reusable-components-with-the-openapi-specification-4077

**Comment by kbsanders** [comment]
@MikeRalphson, thanks for the response. I did come across your blog post in my research.

What prompted my post is errors I'm receiving trying to validate using the tool `swagger-cli validate openapi.yml`.

I assume it's validating against an OpenAPI schema that says you can't have additional properties defined for Schema Objects.

```
Swagger schema validation failed. 
  Data does not match any schemas from 'oneOf' at #/paths//Foo/post/requestBody
    Data does not match any schemas from 'oneOf' at #/paths//Foo/post/requestBody/content/application/vnd.api+json/schema

      **Additional properties not allowed: definitions at #/content/application/vnd.api+json/schema**

      Missing required property: $ref at #/content/application/vnd.api+json/schema
    Missing required property: $ref at #/paths//Foo/post/requestBody
 ```

Your post got me thinking and I believe I've found a solution to my problem.

If I rework things a bit, so that my `$ref` targets a parent element inside the external document, the validation tool is happy. I called it `schema` for lack of a better word.

File: **openapi.yml**

```
openapi: 3.0.2
...
paths:
  /Foo:
    $ref: './endpoints/Foo/paths.yml'
```

File: **./endpoints/Foo/paths.yml**

```
post:
  operationId: PostFoo
  ...
  requestBody:
    content:
      application/vnd.api+json:
        schema:
           $ref: './post/requestBody.yml#/schema' # <-- Target the schema element in the external doc.
```

File: **./endpoints/Foo/post/requestBody.yml**

```
schema: # <-- Schema object is now under a parent element. The $ref targets this element.
  type: object
  properties:
    data:
      oneOf:
        - $ref: "#/definitions/SimpleRequest" # Locally defined below
        - $ref: "#/definitions/ExtendedRequest" # Locally defined below
definitions: # <-- We get to keep definitions, it doesn't get included into the parent document.
  SimpleRequest:
    type: object
    properties:
      type:
        type: string
        enum:
          - SimpleRequest
      attributes:
        type: object
        properties:
          ...
  ExtendedRequest:
    type: object
    properties:
      type:
        type: string
        enum:
          - ExtendedRequest
      attributes:
        type: object
        properties:
          ...
```

The validation tool is happy:

```
swagger-cli validate openapi.yml 
openapi.yml is valid
```

Their bundle tool that creates a single `openapi.yml` file after resolving references works as expected too.

This makes perfect sense to me now that I've worked it out, but the road to get here was a bit rough.

**Comment by MikeRalphson** [comment]
Yes, wrapping your schema to keep `definitions` out of the scope of what's actually included is the way to go. Glad you got it sorted. Some things may be in the pipeline which will help others hitting this problem going forward.

**Comment by handrews** [comment]
@MikeRalphson looks like this has been answered and can be closed?
