### ISSUE TITLE
TSC Meeting - November 29th 2018

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1768]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Discuss/merge @handrews schema fixes | @webron  |  |
| Use of jmespath for overlays | @MikeRalphson / @darrelmiller | |
| Merge registry to gh-pages with draft content? Pre-req for pretty spec | @MikeRalphson | |

/cc @OAI/tsc Please add items as you see fit

**Comment by handrews** [comment]
Issues that we considered.

* https://github.com/OAI/OpenAPI-Specification/issues/1651
* https://github.com/OAI/OpenAPI-Specification/issues/1546
