### ISSUE TITLE
Jaxrs-cxf generator generated code is not supporting different success codes

### ISSUE THREAD

**Issue by kkrhdd** [OAI/OpenAPI-Specification#1769]
Hi,

When we have defined 201 status code for POST success response. the interface is generated with return type mentioned in the response but always sends 200 status code instead of 201.

Ex:
post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Created
            content:
            application/json:
              schema:
                $ref: #/components/schemas/responseWithId
       
Generated interface looks like below:
public ResponseWithId createPets(Pet pet) {
....
}

When the implementation is returning the Pojo ResponseWithId, the response code sent is 200 instead of 201.

Maven Plugin Used for Code Generation: 
org.openapitools:openapi-generator-maven-plugin:3.3.1
&lt;language&gt;jaxrs-cxf&lt;/language&gt;

If it can include jaxrs.ws.Response instead of the Pojo, it will be good enough for usage.

Please help.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
