### ISSUE TITLE
tutorial-part-6-defining-security does not link to part 7

### ISSUE THREAD

**Issue by kristianjaeger** [OAI/OpenAPI-Specification#1770]
http://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-6-defining-security/ does not link to http://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-7-documentation/ in the conclusion section. Cheers.

**Comment by MikeRalphson** [comment]
As per other issue.

**Comment by kristianjaeger** [comment]
Whoops! Thanks anyway. Cheers.
