### ISSUE TITLE
tutorial-part-8-splitting-specification-file does not link to part 9

### ISSUE THREAD

**Issue by kristianjaeger** [OAI/OpenAPI-Specification#1771]
http://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-8-splitting-specification-file/ does not link to part 9 in the conclusion http://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-9-extending-the-openapi-specification/ . Cheers.

**Comment by MikeRalphson** [comment]
This is not that repository. I think you need https://github.com/arno-di-loreto/apihandyman.io
