### ISSUE TITLE
Support partial responses

### ISSUE THREAD

**Issue by raderio** [OAI/OpenAPI-Specification#1773]
Will be very useful to document that API support partial responses.
This will give a strong point when comparing with GraphQL.

Like `GET /api/blogposts?fields=author{name,avatar},title,detail`

https://www.leliam.com/make-rest-api-to-partial-response-just-like-graphql-@bRyL6nWufIxFXIdNWRdAwN
https://apigee.com/about/blog/technology/restful-api-design-can-your-api-give-developers-just-information-they-need

Can you please integrate partial response?

**Comment by raderio** [comment]
To add a special type like "JsonPath<SomeResponse>" to indicate that it can have predefined values.

**Comment by MikeRalphson** [comment]
No, sorry, I still can't visualise what you mean.

Can you show an example of what an OpenAPI 3 document would look like modified to include your requirements?

**Comment by raderio** [comment]
Something like fields editor from https://developers.google.com/apis-explorer/#p/blogger/v3/blogger.blogs.listByUser

Like explorer in graphql
https://www.onegraph.com/blog/2019/01/24/How_OneGraph_onboards_users_new_to_GraphQL.html#introducing-the-onegraph-graphiql-explorer

![fields](https://user-images.githubusercontent.com/4563564/51906623-2fe02f80-23cd-11e9-94e5-25b028f2ceb7.png)

**Comment by handrews** [comment]
I think you are asking about returning subsets of a resource's fields?  The OpenAPI Specification just describes what is possible, so you can describe this by making the fields optional.  But the OAS does not _implement_ the server (unlike GraphQL), so the actual returning of selected fields is outside of our scope.

Please let me know if I'm misunderstanding and I can re-open this.
