### ISSUE TITLE
Question: nullable & optional/required marks

### ISSUE THREAD

**Issue by raderio** [OAI/OpenAPI-Specification#1775]
Can we represent in specification that a field is non-nullable & optional?
this mean, or we send a data for the field, or just do not send the field in request, `null` is not allowed.
`{"foo": "bar", "baz": true}` is allowed
`{"baz": true}` is allowed, because is optional
`{"foo": null, "baz": true}` is NOT allowed, because is non-nullable

Basically `null` has the meaning of "this property existed before, and I want to nullify its value". If there's no value, or the value needs not change (for requests, for example), it just shouldn't be sent.

**Comment by MikeRalphson** [comment]
Non-nullable and optional is the default in a schema object for properties.

**Comment by raderio** [comment]
Can you please provide an example?

**Comment by raderio** [comment]
From https://swagger.io/docs/specification/data-models/data-types/
At the moment is
```
type: integer
nullable: true
```
what I am searching/needed
```
type: integer
nullable: false
required: false
```

**Comment by raderio** [comment]
As I understand, it will be like
```
{
  "type": "object",
  "properties": {
    "counter": {
      "type": "integer",
      "nullable": true,
    },
   "required": [
      "counter"
   ]
}
```
Am I correct?

**Comment by handrews** [comment]
@tedepstein is there more to say here given the `nullable` clarifications?  I think @raderio's last comment was correct so this can probably be closed?

**Comment by tedepstein** [comment]
@handrews, yes, I think it can be closed. 

@raderio, I think the [proposed clarification](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/003_Clarify-Nullable.md) of `nullable` in the 3.0.3 patch release should be helpful to explain how `nullable` interacts with other keywords. 

A few things in particular:
*  Untyped properties are nullable by default. 
* Typed properties are non-nullable by default, but can be made nullable with `nullable: true`. 
* All properties are optional by default. 
* Optionality and nullability are separate, independent behaviors. A property can be any of the four combinations of optional/required, nullable/non-nullable.

**Comment by handrews** [comment]
We agreed to close this and apparently I forgot to actually close it 🤦
