### ISSUE TITLE
Question: spec file naming questions

### ISSUE THREAD

**Issue by Ryandaydev** [OAI/OpenAPI-Specification#1777]
(If this is documented somewhere else, appreciate you pointing me there, because I couldn't find it)

Q1: Is there any reason NOT to name the OAS file specific to the API, eg. api_name.yml

Q2: Since it appears the OAS has a single version, should the OAS file name include version, e.g. api_name_v1.yml

**Comment by MikeRalphson** [comment]
The only guidance in the spec is:

> It is RECOMMENDED that the root OpenAPI document be named: openapi.json or openapi.yaml.

and by `RECOMMENDED` we mean

> This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.
