### ISSUE TITLE
Schema Missing

### ISSUE THREAD

**Issue by robbymeier** [OAI/OpenAPI-Specification#1783]
When a global consumes/produces is set after paths then the schema is not loaded when calling OpenApiStreamReader.Read. The code below replicates that issue. The original json has the consumes/produces at the end. It then produces openApiDocument3 with the missing schema. The  code then moves the 'produces' before 'paths' and produces openApiDocument4. In this case the schema is not missing. The different results are shown in the attachment. Note that some tools produce json descriptions with global consumes/produces after paths so this is not just a matter of "why don't you just move it to the front".

    string jsonDescription = "{\"swagger\":\"2.0\",\"info\":{\"description\":\"consumes/produces issue\",\"version\":\"2.0.0\",\"title\":\"Swagger Petstore\"},\"host\":\"petstore.swagger.io\",\"basePath\":\"/v2\",\"paths\":{\"/pet/{petId}\":{\"get\":{\"tags\":[\"pet\"],\"summary\":\"Find pet by ID\",\"operationId\":\"getPetById\",\"parameters\":[{\"name\":\"petId\",\"in\":\"path\",\"description\":\"ID of pet to return\",\"required\":true,\"type\":\"integer\",\"format\":\"int64\"}],\"responses\":{\"200\":{\"description\":\"successful operation\",\"schema\":{\"$ref\":\"#/definitions/Pet\"}}}}}},\"definitions\":{\"Pet\":{\"type\":\"object\",\"required\":[\"name\",\"photoUrls\"],\"properties\":{\"id\":{\"type\":\"integer\",\"format\":\"int64\"},\"name\":{\"type\":\"string\",\"example\":\"doggie\"}},\"xml\":{\"name\":\"Pet\"}}},\"produces\":[\"application/json\"]}";
   byte[] byteArray3 = Encoding.ASCII.GetBytes(jsonDescription);
   MemoryStream stream3 = new MemoryStream(byteArray3);
   OpenApiDocument openApiDocument3 = new OpenApiStreamReader().Read(stream3, out var diagnostic3);
   //Re-arrange produces. 
   Newtonsoft.Json.Linq.JObject jObject3 = Newtonsoft.Json.Linq.JObject.Parse(jsonDescription);
   Newtonsoft.Json.Linq.JProperty producesProperty = jObject3.Property("produces");
   Newtonsoft.Json.Linq.JProperty paths = jObject3.Property("paths");
   jObject3.Property("produces").Remove();
   paths.AddBeforeSelf(producesProperty);

   jsonDescription = jObject3.ToString();
   byteArray3 = Encoding.ASCII.GetBytes(jsonDescription);
   stream3 = new MemoryStream(byteArray3);
   OpenApiDocument openApiDocument4 = new OpenApiStreamReader().Read(stream3, out var diagnostic4);
![missingschema](https://user-images.githubusercontent.com/36144213/50253418-ff08e580-039e-11e9-999d-45474f3e8a82.png)

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
