### ISSUE TITLE
Question: nullable & optional/required marks

### ISSUE THREAD

**Issue by shockey** [OAI/OpenAPI-Specification#1798]
_From @raderio on December 10, 2018 10:31_

Can we represent that a field is non-nullable & optional?
this mean, or we send a data for the field, or just do not send the field in request, null is not allowed.
`{"foo": "bar", "baz": true}` is allowed
`{"baz": true}` is allowed, because is optional
`{"foo": null, "baz": true}` is NOT allowed, because is non-nullable

Basically `null` has the meaning of "this property existed before, and I want to nullify its value". If there's no value, or the value needs not change (for requests, for example), it just shouldn't be sent.

_Copied from original issue: swagger-api/swagger-ui#5071_

**Comment by raderio** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/1775

**Comment by shockey** [comment]
Aha! Closing in favor of #1775.
