### ISSUE TITLE
Full Version History

### ISSUE THREAD

**Issue by techtonik** [OAI/OpenAPI-Specification#180]
There is no information about differences between versions of Swagger. It will be nice to know why a certain version was not sufficient and new speccy appeared.
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#revision-history

**Comment by webron** [comment]
Parent: #589.

**Comment by lornajane** [comment]
Closing as outdated and somewhat addressed. Newer versions of OpenAPI specification have transparent change processes and discussion.

**Comment by techtonik** [comment]
@lornajane historical info is never outdated. I wouldn't close this issue in case there is still somebody who can fill the gap.

**Comment by handrews** [comment]
@techtonik there's no simple reason for a version to be considered in need of updating or replacement- it's the ongoing discussions documented in this repository's issues and PRs that tell that story (and the OAI/moonwalk repository for the next major version).  Existing published versions aren't changed once published, so if you really think there are specific things that need documenting, you could file issues requesting documentation of those specifics at the OAI/learn.openapis.org repository.

**Comment by techtonik** [comment]
The main reason for Full Version History information in any spec is to have information about how to (back)port tools and data from one version to another. Sometimes you need to backport things to an older spec for some complicated piece of software to do its job.
