### ISSUE TITLE
TSC Open Meeting - January 24th, 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1803]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 5pm-6pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned Agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Presentation on proposal for adding security parameters to OpenAPI  | Philippe @ 42Crunch |  |
| Contrast [RFC8188](https://tools.ietf.org/html/rfc8188) | @MikeRalphson | |

/cc @OAI/tsc Please add items as you see fit

**Comment by MikeRalphson** [comment]
Thanks I'll add it to the agenda.

**Comment by MikeRalphson** [comment]
Agenda #1814 created.

**Comment by MikeRalphson** [comment]
Meeting recording: https://zoom.us/recording/share/PBwsPKe6OprJMcAx6bWs5Y4ySGOGnOsu7-hZGAoTS2uwIumekTziMw
