### ISSUE TITLE
Evaluating request body OpenAPI 3.0.2

### ISSUE THREAD

**Issue by dhiemaz** [OAI/OpenAPI-Specification#1805]
I have create API document using OAS 3. I need to evaluate request body and give correct sample response based in one of the parameter in the request body. 

I have created script below : 
```
requestBody:
        description: payload request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleRequest'
            examples:
              success_request:
                value: {"customer_id": "12345678", "product_code": "ABC1234"}
              bad_request:
                value: {"customer_id": "12345678", "product_code": "ABC1235"}
        required: true
```

and also : 

```
requestBody:
        description: payload request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleRequest'
            examples:
              success_response:
                value: 
                  customer_id: "1234567"
              bad_request:
                value: 
                  customer_id: "1234568"
        required: true
```

but mock generated always given same response.

**Comment by MikeRalphson** [comment]
Your `requestBody` definition looks to be valid. This seems like an issue with whatever tool you're using to generate your mocks.

Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
