### ISSUE TITLE
Add custom variables

### ISSUE THREAD

**Issue by sergioabplanalp** [OAI/OpenAPI-Specification#1815]
I am using a custom template to generate an API controller based on an OpenAPI Spec. I am running into a problem where I need to disambiguate between values at a few levels. There is currently no property to attach these values to. A 'variables' property under the different levels would be helpful for this use case.
What is the likelihood of adding this to the spec?

**Comment by MikeRalphson** [comment]
I think we need an example to see what you mean by values, variables and levels.

**Comment by MikeRalphson** [comment]
Don't forget you can use specification-extensions to achieve many custom scenarios.

**Comment by sergioabplanalp** [comment]
@MikeRalphson thanks for the speedy reply. The specification-extensions seems to be inline with what my requirements are / what I meant by custom variables
