### ISSUE TITLE
Multilevel anyOf input

### ISSUE THREAD

**Issue by raderio** [OAI/OpenAPI-Specification#1816]
In our application we want to have an register endpoint, so in our app an user should choose the type _individual_ or _business_, so this is 1st level of anyOf.

The 2nd level will be, that individual can register by _email_ or by _social network_, and _business_ can only register by _email_. Fields for registering by _email_ are different for both types.

Is it possible to express this in Swagger v3?

**Comment by lornajane** [comment]
Yes, you can nest the anyOf keywords to describe the schema you need. Not all tools will handle this well, but it is supported.
