### ISSUE TITLE
ASK different between open API 3.0.0 and 3.0.2

### ISSUE THREAD

**Issue by dhiemaz** [OAI/OpenAPI-Specification#1819]
I am wondering if there any reference inform the differences between OpenAPI version 3.0.0 and OpenAPI version 3.0.2 ? 

Thank you

**Comment by MikeRalphson** [comment]
The patch releases contain only clarifications, fixes to typos and examples etc, no functional changes.

The release notes are [here](https://github.com/OAI/OpenAPI-Specification/releases)
