### ISSUE TITLE
Email validation is impossible

### ISSUE THREAD

**Issue by BelfordZ** [OAI/OpenAPI-Specification#1820]
There is no universal email validation, and I suggest that the language be loosened around [this, for example](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#user-content-contacturl). 

In many places, there have been choices to make things up to the implementation. Perhaps this is already / should be one?

**Comment by handrews** [comment]
In OAS 3.1, JSON Schema draft 2019-09 will be used, and as noted in #2093, `format` validation is disabled by default.  For [exactly this reason](https://json-schema.org/draft/2019-09/release-notes.html#format-vocabulary).

@webron @MikeRalphson I think this can be closed in favor of #2093 which will cover it.  Unless we want to do something separate in 3.0.3, I guess.

**Comment by webron** [comment]
@handrews - agreed.
