### ISSUE TITLE
Description for $ref object property

### ISSUE THREAD

**Issue by scf37** [OAI/OpenAPI-Specification#1836]
When adding descriptions for object fields, I would like to add description for field with referenced schema as well

Given following schema (from the spec):

```json
{
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "address": {
      "$ref": "#/components/schemas/Address"
    },
    "age": {
      "type": "integer",
      "format": "int32",
      "minimum": 0
    }
  }
}
```

I want to introduce description for address field:

```json
{
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "address": {
      "description": "User billing address",
      "$ref": "#/components/schemas/Address"
    },
    "age": {
      "type": "integer",
      "format": "int32",
      "minimum": 0
    }
  }
}
```

Motivation:
When generating documentation for the object, I want to add specific description to every object field, including "address"

**Comment by MikeRalphson** [comment]
Would you consider this a duplicate of #556 ? If so, we can close.

**Comment by scf37** [comment]
Yes, it is. Thanks for bringing this up.
