### ISSUE TITLE
TSC Open Meeting, Thursday 21st February 2019

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1838]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 5pm-6pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Overlays #1722 and Traits #445 | @darrelmiller / @webron / @MikeRalphson | |

/cc @OAI/tsc Please add other items as you see fit

**Comment by mkistler** [comment]
I think the Traits issue is actually #613 .

**Comment by MikeRalphson** [comment]
Meeting Recording:
https://zoom.us/recording/share/TkvgsqNSqGGbKgVBM4NoyLNpmPHFO4JERiH-3_Zn4RmwIumekTziMw
