### ISSUE TITLE
$ref to path_items and properties inheritance

### ISSUE THREAD

**Issue by bjne** [OAI/OpenAPI-Specification#1842]
When a path_items object includes a $ref to path_items, should the properties defined in the
parent path_items object be propagated to the $ref as with other path_items?

**Comment by kojiDev** [comment]
https://swagger.io/specification/#pathItemObject

> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the OpenAPI Object's components/parameters.

It says you can use ref but it also says that a ref ?shoud? point to `components`.
So if you have your parameters listed in `components` the answer to me seems clear that yes, parameters propagate.

What is hazy for me is whether you can use external refs here

**Comment by handrews** [comment]
Per #2111, yes, you can (and perhaps must) use an external ref.  I'm going to close this, please follow up in #2111 if necessary.
