### ISSUE TITLE
TSC Open Meeting, Thursday 28th February 2019

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#1844]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 5pm-6pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Continue discussion of Overlays and Traits #1843 #1722 #445 #613 | @darrelmiller / @webron / @mkistler / @MikeRalphson | |

/cc @OAI/tsc Please add other items as you see fit

**Comment by ioggstream** [comment]
I propose merging https://github.com/OAI/OpenAPI-Specification/pull/1779 as it should be straightforward now.

**Comment by MikeRalphson** [comment]
Meeting Recording:
https://zoom.us/recording/share/zE4RsZ6TM3OQk_jxPu14D55fHiRvzkY-LkvCIpLAMmSwIumekTziMw
