### ISSUE TITLE
Support for security flows on schema objects?

### ISSUE THREAD

**Issue by erunion** [OAI/OpenAPI-Specification#1845]
A common thing we have within the @vimeo API is data in an API response that requires an OAuth2 bearer token with a specific scope. There doesn't appear to be any concrete way to document this other than noting it in the description of the schema object.

I think since it's not full authentication, just a "you need this in order to get that" it'd need to be an entirely new kind of object descriptor. Possibly a slimmed down flows object.

I don't see anything regarding this in the other authentication scope change plans for the 3.1.x, but I'm be open to submitting a formal PR if there's interest.

**Comment by darrelmiller** [comment]
Currently OpenAPI only allows attaching scopes to operations.  Correlating scopes to elements of a request or response payload is not something we have attempted to address.
