### ISSUE TITLE
JSON-Metaschema

### ISSUE THREAD

**Issue by chatelao** [OAI/OpenAPI-Specification#1846]
Is there any "Meta-Schema" describing a correct OpenAPI (3.0.1) schema?

**Comment by MikeRalphson** [comment]
There is no finalised JSON Schema for an OpenAPI 3.0.x **document** (not "schema"), but see #1032 and the two WIP PRs #1236 and #1270. We hope to publish the official JSON schemas for v3.0 and v3.1 by the time v3.1 is released.

If you do only want to describe a `schemaObject` then both schema instances in the linked PRs include such a definition.

**Comment by darrelmiller** [comment]
And the JSON Schema of OpenAPI is only an approximation of a correct OpenAPI document.  Not all rules can be validated using JSON Schema.

**Comment by handrews** [comment]
> And the JSON Schema of OpenAPI is only an approximation of a correct OpenAPI document. Not all rules can be validated using JSON Schema.

Which (for the benefit of anyone who might find the above statement odd) is fine from a JSON Schema perspective.  JSON Schema meta-schemas are themselves only approximations of correct JSON Schema documents, for the same reason :-D
