### ISSUE TITLE
Where is the validation rule for components.schemas.<schema_name> in Open API Specification schema

### ISSUE THREAD

**Issue by arjunballa** [OAI/OpenAPI-Specification#1848]
I am trying to add auto suggestions feature to ace editor based on JSON Schema provided but my code is failing to handle `components.schemas.<schema_name>`.

`schemas` is map and it should have key value pairs and key conforms JSON attribute name and value conforms to `#/definitions/schemaOrReference`.

I don't see any `patternProperties` in `components.schema` which I can use to generate code as the below.

```
{
	"components": {
	    "schemas": {
	        "rename": {
	            
	        }
	    }
	}
}
```
Where is the rule which has `schemas` should have a key.

**Comment by MikeRalphson** [comment]
As per your other issue, but it may depend on which draft v3.0 schema you are using.

**Comment by arjunballa** [comment]
Here is a related question which got answered. [Answer](https://github.com/OAI/OpenAPI-Specification/issues/1849#issuecomment-468172110).

The schema for OAS v3.0 uses `additionalProperties` to specify the properties which have `schema` values.

I misunderstood `additionalProperties`.
