### ISSUE TITLE
Where is the validation rule for definitions.<definition_name> in Swagger Specification schema

### ISSUE THREAD

**Issue by arjunballa** [OAI/OpenAPI-Specification#1849]
I am trying to add auto suggestions feature to ace editor based on JSON Schema provided but my code is failing to handle `definitions.<definition_name>`.

`definitions` is map and it should have key value pairs and key conforms JSON attribute name and value conforms to `#/definitions/schema`.

I don't see any `patternProperties` in `definitions` which I can use to generate code as the below.

```
{
	"definitions": {
	    "rename": {
	    }
	}
}
```
Where is the rule which has `definitions` should have a key.

**Comment by MikeRalphson** [comment]
The schema for OAS v2.0 uses `additionalProperties` to specify the properties which have `schemaObject` values.

**Comment by arjunballa** [comment]
`swaggerschema.properties` has 
```
"definitions": {
        "$ref": "#/definitions/definitions"
 }
```
`definitions.definitions` is below object
```
{
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/schema"
      }
}
```
As per my understanding, here `additionalProperties` referring to `"#/definitions/schema"` means, for `definitions` additional properties are allowed and it can have all the properties mentioned in `schema.properties`. 
Is `schema` saying somewhere that `definitions` should have an object and that object can have all the all the properties mentioned in `schema.properties`? Am I missing something?

With my current logic all `schema.properties` appear directly under `definitions` and not under `definitions. rename`
My current logic is not able differentiate between `definitions.info` and `definitions.definitions` which is actually `definitions.schema`.

My logic get recursively goes through all the references until it finds `properties`. That is the reason  `definitions.definitions` directly points to `definitions.schema`.

`definitions.schema` is below object
```
{
      "type": "object",
      "description": "A deterministic version of a JSON Schema object.",
      "patternProperties": {
        "^x-": {
          "$ref": "#/definitions/vendorExtension"
        }
      },
      "properties": {
        "$ref": {
          "type": "string"
        },
        "format": {
          "type": "string
.....
```

**Comment by arjunballa** [comment]
@MikeRalphson Are you saying `additionalProperties` means `definitions` should have a `property-name` and the value should conform `schema`?

In other words, I should not go recursively until I find  `properties` but stop when I find `additionalProperties`?

**Comment by MikeRalphson** [comment]
As this is a JSON Schema question, rather than a question about the OpenAPI specification itself, I think the best resource is https://json-schema.org/understanding-json-schema/reference/object.html#properties

In short, `additionalProperties` is plural and defines the subschema for **each** of those properties. There is no need for a `patternProperties` which matches any property key (like `^*` in your examples).

**Comment by handrews** [comment]
@arjunballa when `additionalProperties` is on its own (without `properties` or `patternProperties`), it behaves more like it should have been named `uniformProperties` or something like that.

On its own, it is intended to describe hashtables/dictionaries/associateive arrays/maps of strings to a data structure defined by the schema value of `additionalProperties`.  So:

`{"type": "object", "additionalProperties": {"type": "integer"}}`

is a JSON object mapping strings to integers.  (JSON object keys are always strings, and the `additionalProperties` schema constrains the object values to be integers).

So, `{"x": 1, "y": 2}` is valid against that schema, but `{"y": "notaninteger"}` and `{"z": {"w": 2"}}` are both invalid.

**Comment by arjunballa** [comment]
@MikeRalphson Thanks for answering my questions. Now I understand how `additionalProperties` behave without (without `properties` or `patternProperties`) . Now I feel stupid.

**Comment by arjunballa** [comment]
@handrews Thank you very much for answering my question. It made it very clear. Now I feel stupid.

**Comment by handrews** [comment]
@arjunballa 

> Now I feel stupid.

Oh goodness, don't!  `additionalProperties` is confusingly named when used on its own.  But it's been like this for many years so it's too much trouble to change it, I'm afraid.
