### ISSUE TITLE
Mixed types Error without discriminator

### ISSUE THREAD

**Issue by Hienphamthe** [OAI/OpenAPI-Specification#1854]
Hi all, I want to have an object value of mixed types: either string or array of object. For instance,
`{"Object": "stringabc"}`
or `{"Object": [ {"a":"A"},{...} ]}`
I define my schema: 
`Object:
              oneOf:
              - type: array
                items:
                  type: object
                  properties:
                    ......
              - type: string
                example: "stringabc"`
 However, it responds error `Unable to deserialize without discriminator`

Anyone have any example solution, please help, thanks.

**Comment by MikeRalphson** [comment]
When you say "it responds", which specific tool are you referring to? It may be better to raise an issue on the repository for that tool rather than here, which is for the specification itself.

**Comment by Hienphamthe** [comment]
Ok thank you, I will create an issue in Swagger UI. However, is there any doc related on using discriminator object with mixed data type? 
Mixed data type: [https://swagger.io/docs/specification/data-models/data-types/](url)
Discriminator object: [https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#discriminatorObject](url)

**Comment by MikeRalphson** [comment]
It is perhaps not stated as clearly as it could be, but because the discriminator object uses a `propertyName` to identify the **property** which determines the schema to use, it only works where all of the alternative schemas have **properties**, which means all of the schemas must describe **objects**, not primitive types.

**Comment by Hienphamthe** [comment]
OK got it, thank you.
