### ISSUE TITLE
Support translation into object-related operations

### ISSUE THREAD

**Issue by pedro93** [OAI/OpenAPI-Specification#1866]
It is currently possible to take an OpenAPI specification and create server/client stubs for such an API. Swagger code generators are the foremost examples of this.
However, the generated code lacks in readability from an object-orientated standpoint. Take the petstore example and look at how the python generator (as an example) outputs an SDK. The methods that map to each endpoint of a particular Path Item have a poor heuristic-based name generation.

The idea here would be to extend the OpenAPI schema, especially in the **pathItemObject** to include a "method name" or similar that provides this additional readability factor in a code-based SDK.

Not sure if this exists or not, apologizes if it does.

**Comment by hkosova** [comment]
Method names can already be specified using [`operationId`](https://spec.openapis.org/oas/v3.1.0.html#operationId).

**Comment by MikeRalphson** [comment]
Thanks @hkosova - @pedro93 please let us know if this does not answer your query, and we can re-open.

**Comment by pedro93** [comment]
Hello @hkosova and @MikeRalphson and thank you for your responses! I believe operationId is exactly what I wanted!
