### ISSUE TITLE
Is security `scheme` value lowercase or case-insensitive?

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#1876]
The [`scheme`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#user-content-securityschemescheme) field of the Security Scheme Object is defined as follows:

> The name of the HTTP Authorization scheme to be used in the [Authorization header as defined in RFC7235](https://tools.ietf.org/html/rfc7235#section-5.1).

and subsequent [examples](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#security-scheme-object-example) use  `scheme: basic` and `scheme: bearer` - with lowercase scheme names.

However, the [Authentication Scheme Registry](http://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml) defines the scheme names starting with an uppercase letter:
* Basic
* Bearer
* Digest
* ...

Could you please clarify if the `scheme` value must be lowercase, or if both `scheme: basic` (as in the current examples) and `scheme: Basic` (as in the Auth Scheme Registry) are valid and equivalent?

**Comment by darrelmiller** [comment]
@hkosova As per RFC7235 auth scheme is case insensitive:

> 2.1.  Challenge and Response
> 
>    HTTP provides a simple challenge-response authentication framework
>    that can be used by a server to challenge a client request and by a
>    client to provide authentication information.  **It uses a case-**
>    **insensitive token as a means to identify the authentication scheme,**
>    followed by additional information necessary for achieving

https://tools.ietf.org/html/rfc7235#section-2.1
