### ISSUE TITLE
Response schema validation message is not clear for arrays

### ISSUE THREAD

**Issue by ashpekvs** [OAI/OpenAPI-Specification#1890]
**Use case description.**
Inside my schema yaml file I've specified that response from some URL handler would be an array of objects, e.g.:

```
      responses:
        "200":
          description: An array of provisioned Resource Records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ResourceRecord'
```
I've also described what is ResourceRecord inside the same yaml file

For some reason the code returns an object, not an array
in this case the exception message from OpenAPI framework is a bit strange:

```
SchemaValidationError: Mimetype invalid: Value id is not of type SchemaType.OBJECT
```

id from error is the 1st attribute of my object (specified in yaml spec)

**What is expected.**
The expected error message is to complain that no array specified, array is missed, etc

**Comment by tedepstein** [comment]
@ashpekvs , 

> For some reason the code returns an object, not an array
> in this case the exception message from OpenAPI framework is a bit strange:

This project is for the OpenAPI _specification_ itself, not for issues with specific tools, libraries, or frameworks. Those would be OpenAPI _implementations_, which are out of this project's scope.

You've declared the array type correctly. So it seems there are issues with the code generator or runtime framework you are using. I would recommend closing this issue, and opening a new issue in that specific project.

**Comment by ashpekvs** [comment]
Thanks for hints and fast answer, closing
