### ISSUE TITLE
TSC Open Meeting - April 25th, 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1896]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 5pm-6pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Alternative Schema | Chuck | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by cmheazel** [comment]
Agenda item: Alternative Schema Pull Request and discussion of its' approach for proposed extensions.

**Comment by darrelmiller** [comment]
Ted proposed using labels to link issues and PRs to a proposal #1905
Suggested the convention of PNNN  for the label
Need to make regular TDC members as collaborators on the repo.  Need input from @webron 
Need to protect branches.
