### ISSUE TITLE
Error on executing ./gradlew openapi3

### ISSUE THREAD

**Issue by SwapnilBVaidya** [OAI/OpenAPI-Specification#1898]
I am getting this error when executing ./gradlew openapi3 -
java.lang.NoSuchMethodError: org.yaml.snakeyaml.DumperOptions.setSplitLines(Z)V

My build.gradle have these components
1. dependencies - classpath("com.epages:restdocs-api-spec-gradle-plugin:0.8.1")
2. dependencies - classpath "org.asciidoctor:asciidoctor-gradle-plugin:1.5.3"
3. dependencies - classpath "com.github.jruby-gradle:jruby-gradle-plugin:1.6.0"
4 .  apply plugin: "org.asciidoctor.convert"
       apply plugin: "com.epages.restdocs-api-spec"
      apply plugin: "com.github.jruby-gradle.base"

**Comment by marmax** [comment]
@svaidya401 imho this is totally unrelated to OpenAPI **specification**
You should report to https://github.com/ePages-de/restdocs-api-spec which is most probably the source of your problems ;)

**Comment by MikeRalphson** [comment]
Closing as above, thanks @marmax
