### ISSUE TITLE
Incorrect JSON object in HTTP request multipart form data

### ISSUE THREAD

**Issue by Beaurpi** [OAI/OpenAPI-Specification#1902]
Hi there,

I've figured out that there is an issue with the code generated, when using a multipart/form-data object.
Declare a POST method with the following requestBody:

```
'/test/upload':
post:
requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                title:
                  type: object
                  properties:
                    en:
                      type: string
                    fr:
                      type: string
                fileName:
                  type: string
                  format: binary
```

the generated service will have a good signature:
`public uploadFile(id: string, name?: string, title?: UploadTitle, .....`

But the HTTP post, will not pass a JSON for the parameter 'TITLE'.
It will actually encode the object as string.
As a result the 'title' parameter will be

```
-----------------------------8302951520691
Content-Disposition: form-data; name="title"

[object: Object]
```

**Comment by topce** [comment]
@Beaurpi thank you for reporting 
Is this connected to angular typescript 
or to all clients?

**Comment by Beaurpi** [comment]
@topce , yes thanks
It's related to the generated code in angular typescript.
in the generation command line i'm using the following:
`-g typescript-angular`

**Comment by darrelmiller** [comment]
@Beaurpi This is a repo for the OpenAPI specification and not related to any specific tooling.  I would recommend reporting this on the repo related to the tooling you are using.
