### ISSUE TITLE
How to specify Roles OR Permissions needed to authorize an API?

### ISSUE THREAD

**Issue by avanathan** [OAI/OpenAPI-Specification#1903]
Sorry, I couldn't find a way to specify `role(s)` or `permission(s)` needed to authorize an API. In OAuth world this may be `scope(s)`, but how could we support similar authorizations with a specific Authentication Type. For eg. Basic Auth?

**Comment by MikeRalphson** [comment]
In progress as part of #1829

**Comment by MikeRalphson** [comment]
Released in v3.1.0
