### ISSUE TITLE
New link type for URLs

### ISSUE THREAD

**Issue by artemananiev** [OAI/OpenAPI-Specification#1904]
When a link is defined, it can map source response attributes either to a new request params or a new request body. However, if response contains an attribute, which is an URL to be used by clients, such a link cannot be clearly described in OAS.

Here is an example:

```
paths:
  /create:
    post:
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
  /status/{requestId}:
    get:
      operationId: statusQuery
      responses:
        200:
          description: OK
components:
  schemas:
    response:
      type: object
      properties:
        statusUrl:
          type: string
          format: uri
```

Response of POST /create will contain a link to query for status updates, like `https://server/status/12345`. Not just an ID of a status object, but a full URL. There is no way to define a link like this currently. Something like this would be great:

```
components:
  links:
    StatusUpdates:
      operationId: statusQuery
      requestUrl: "$response.body#/statusUrl"
```

`requestUrl` is an alternative to existing `parameters` and `requestBody`.

**Comment by lornajane** [comment]
We've had this one open for quite some time but since we don't have much discussion or interest, it will now be closed.
