### ISSUE TITLE
Use designated labels in proposals to link to related issues & pull requests

### ISSUE THREAD

**Issue by tedepstein** [OAI/OpenAPI-Specification#1905]
PR #1868 introduces a new workflow for _proposals_. As described in [my comment](https://github.com/OAI/OpenAPI-Specification/pull/1868#issuecomment-478245938) on that PR, I think proposals should evolve through discussion in multiple related issues and pull requests. 

To manage this evolution more easily I suggest we create a designated GitHub label for each draft proposal. Apply that label to relevant issues and PRs. Specify that label towards the top of the draft proposal, followed by two links:

1. Open issues related to the draft proposal (filtered by label)
2. Open pull requests related to the draft proposal (filtered by label)

**Comment by tedepstein** [comment]
We now seem to have an approach to this. A small group of community members has labeling privileges, so we can manage this. I'll go back to my proposal and put this to use now. Assuming it works nicely, I'll also submit a PR to update the proposal template.

**Comment by MikeRalphson** [comment]
@tedepstein what changes to the proposals template did you have in mind?

**Comment by tedepstein** [comment]
@MikeRalphson , this would be easier to illustrate if I could show an example, but that requires creating a new label. I can only apply labels, not create them. Could you create a new label called "Proposal: clarify-nullable" so I can show how this would work?

**Comment by tedepstein** [comment]
@MikeRalphson , to answer your question directly, I would suggest modifying the proposal template as shown here: 

https://github.com/tedepstein/OpenAPI-Specification/commit/ecf1ee95c5649a7e206bd2a22c605f9141a3f4ea

**Comment by MikeRalphson** [comment]
Looks good to me.

**Comment by handrews** [comment]
@lornajane recently updated the proposals documentation -if there is still something needed here, please open an issue based on the current state of things.
