### ISSUE TITLE
Is 'Schema' required for Media Type Object ? 

### ISSUE THREAD

**Issue by ChristopherAparicio** [OAI/OpenAPI-Specification#1910]
I'm working on a parser for the OAS V3 and I would like to know is the property "schema" is required inside the Media Type object ? 
For me that doesn't make sense to get a Media Type without a schema and only example(s) and the encoding property is based on a Schema Object. So I would say yes.
If that is the case, it's not better to write '**REQUIRED**' explicitly ?

**Comment by darrelmiller** [comment]
It is definitely not required.  There are many media types where a OAS Schema has no value.  e.g.   `text/html`  Also, there are some media types that have the semantics fully defined such as `application/http-problem+json`

**Comment by ChristopherAparicio** [comment]
Thanks for your response I'm going to close this issue
