### ISSUE TITLE
How to reduce the Response Object properties of an OpenAPI path?

### ISSUE THREAD

**Issue by mvermand22** [OAI/OpenAPI-Specification#1919]
How can I reduce/limit the response of an OpenAPI path in case of a complex response component.

Lets say I have an `Order` Component which is for a `Customer` and has `OrderItems` as children. Each `OrderItem` points to a `Product` and each `Product` has a `Vendor`.

I tried to represent this as a Model (this is not Yaml, '-' is used to represent a Member/Field/Property)

    Order
    - id
    - customer => Customer
                  - id
                  - name
                  - email
    - items => OrderItem
               - id
               - description
               - price
               - product  => Product
                             - id
                             - vendor => Vendor
                                         - name

So if I now have a path

    /orders/{id}
        get:
            operationId: getOrder
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Order'

Then this would mean (I think) that the implementation of this definition would have to return the complete tree of objects from `Order` over `Customer` and `OrderLine` until `Vendor` upon request for a given Order by its id. Right?

(How) is it possible to indicate that the implementation only needs to return parts of the tree. Such as for example the `OrderLine` Objects may be included but the `Product` should not be included. Instead of the product, it should return a product Id or a Link object. Same goes for the `Customer`.

I know I could create a dedicated response Schema with its own reduced properties, but then, by the time I defined all paths, there is no defined component used anymore.

So is it possible to have something like 

    /orders/{id}
        get:
            operationId: getOrder
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                allOf
                                    - $ref: '#/components/schemas/Order'
                                    - type: object
                                        properties:
                                            ??? something to indicate that the OrderLines objects of Order should return a productId and not a Product object. 
                                            ??? something to indicate that the Customer object should not be returned but instead a customerId or Link object.

Or do I have to go the other way around, where I create `Order` with an orderLines property as an array of id's? But if I go that route, then what is the purpose of $ref to other components as they will not be used anymore.

**Comment by handrews** [comment]
@mvermand22 if you're still interested in this (sorry for the delay), what you want is the `required` keyword from JSON Schema.  By default, all properties are optional, so just writing the `properties` without `required` indicates that you can leave things out.

I think this answers the question, and given that it's quite old I'm going to go ahead and close this issue.  Please re-open or file a new issue if more information is needed.
