### ISSUE TITLE
Two variables in one query parameter?

### ISSUE THREAD

**Issue by IBrokeYourCode** [OAI/OpenAPI-Specification#1920]
I have an endpoint that returns an array of objects, and it can return them sorted.
I'd call it like this:
`/endpoint/list?sort=name,asc&sort=date,desc`
The result is that they will be sorted by name, ascending; and then date, descending.
So we have two variables in one query param - the name of the field to use for sorting and the order.
Is there a way to include these two variables in an OpenAPI spec, other than explaining the usage in `description`?

**Comment by philsturgeon** [comment]
You could try and use `style` on the parameter and explain its an array of two values but i think its easier to just use the description like you said.

**Comment by vvanpo** [comment]
You're describing an array of arrays, using `explode: true`. But neither the 3.0 standard nor the URI template RFC specify what is supposed to happen when you passed nested arrays to form-style parameters, so I don't think you can count on this being possible.

**Comment by handrews** [comment]
Since it's been more than half a year and no further questions or discussions, I'm going to close this.
