### ISSUE TITLE
Add support for definitions property in Schema Object

### ISSUE THREAD

**Issue by pintux** [OAI/OpenAPI-Specification#1921]
Having the possibility to use the "definitions" property in a Schema Object file (as in JSON Schema) allows to better define all the shared properties in one point and only in the scope of that specific schema. This avoids the need to move shared definitions in another schema file or referencing them with relative paths to the same doc, pointing to "properties" sub-paths, which makes readability and maintenance worse.

**Comment by ikokostya** [comment]
Similar issue https://github.com/OAI/OpenAPI-Specification/issues/1761

**Comment by handrews** [comment]
This is fixed by #1977 (although `definitions` became `$defs` in JSON Schema draft 2019-09 as part of standardizing core schema keywords with a `$` prefix).

@webron @MikeRalphson I think this can be considered closed by #1977.

**Comment by webron** [comment]
Yup!
