### ISSUE TITLE
Feature request: Group schemas.

### ISSUE THREAD

**Issue by hajnalmt** [OAI/OpenAPI-Specification#1924]
In a lot of times, the number of schemas used can grow significantly. It would be really cool, to be able to group them somehow. Like the paths can be tagged, the schemas could be too.

**Comment by philsturgeon** [comment]
Could you try and dream how how this might actually look? Visual examples help some brains click, definitely mine. 

You can use folders already and $ref them, so I can't separate what you are suggesting with that based on this description.

**Comment by handrews** [comment]
With #1977 going in for OAS 3.1, `$defs`, `$id`, and `$anchor` provide numerous ways to organize and reference schemas both inside and outside of the OAS document.  So I think this can be considered fixed- paging @webron and/or @MikeRalphson for closure.

**Comment by webron** [comment]
@handrews - actually not sure what the OP intended in this case to know if what you're saying satisfies their needs.

@hajnalmt - can you please provided additional clarification?

**Comment by hajnalmt** [comment]
I close the issue. I think $defs and $anchos is enough for now.
