### ISSUE TITLE
Question: How do I configure base path in web.xml for openapi 3?

### ISSUE THREAD

**Issue by Kiolali** [OAI/OpenAPI-Specification#1926]
Hey,

I'm writing a REST-Service with JAX-RS (Jersey), which is deployed on a Tomcat.
Before, I was using the servlet-class `io.swagger.jaxrs.config.DefaultJaxrsConfig` in web.xml to configure `swagger.api.basepath`. How to do this with openapi 3? 

Best, 
kiolali

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
