### ISSUE TITLE
TSC Open Meeting - May 16th, 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1928]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 5pm-6pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Proposed Agenda**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Guidance on use of type in schema | Ron | Add wording to clarify use of type property in Schema |
| Optional Response object  | Darrel | Darrel to create proposal |
| Enable active TDC members ability to label tasks  | TSC |  Ron to investigate. |
| How do we make proposals editable by TDC members? | TSC | Ping TSC on PR and we will merge at indiscriminately. |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by earth2marsh** [comment]
Note that on May 21st next week, we're having a spec unconference at GlueCon in Broomfield, Colorado (near Denver). Please register and attend if you can!

> @OpenApiSpec invites you to our Unconference the day before GlueCon Tuesday, May 21 from 1-6 pm. We will cover... anything you want related to the spec! That's what an Unconference is. Registration is free but space is limited. http://bit.ly/oai_unconference … For questions @OpenAPISpec

From: https://twitter.com/OpenApiSpec/status/1123946760592941056
