### ISSUE TITLE
TSC Open Meeting - May 30th

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1929]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 5pm-6pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
|Payloads in GET/DELETE | TSC | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
There is a request to discuss allowing request payloads on GET and DELETE for compatibility with OpenAPI v2 https://github.com/OAI/OpenAPI-Specification/issues/1801#issuecomment-496477077

**Comment by n2ygk** [comment]
See #1937. I look forward to your review.

**Comment by asbachb** [comment]
@darrelmiller I guess the meeting was already hold? I'm missing the outcome howto proceed with #1801

**Comment by handrews** [comment]
The issues/PRs mentioned here have been merged or are in progress and tracked in more current meeting agendas.
