### ISSUE TITLE
Optional property per operation

### ISSUE THREAD

**Issue by marcortw** [OAI/OpenAPI-Specification#1935]
I am trying to reuse a schema similar to the 'reusable bodies' section described [here](https://swagger.io/docs/specification/describing-request-body/), with the difference that I'd like to reuse the same schema in the requestBody and in the response:

```yaml
  /pets:
    post:
      summary: Creates a new pet
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/PetBody'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetBody'
```
This works, but I'd like to make an exception for an 'id' property of the PetBody. Assuming that a Pet's unique identifier gets created after the POST on the server, I wonder how I could split or compose the PetBody schema such that an 'id' could be marked `required: true` _only_ in the response?

Something like this works, but I'd also like to reference the id parameter and possibly a few more through additional references which doesn't seem to work according to https://github.com/OAI/OpenAPI-Specification/issues/1467 

```yaml
    PetBodyResponse:
      allOf:
        - $ref: '#/components/schemas/PetBody'
        - type: object
          properties:
            id:
              type: string
```
Thanks in advance for any good suggestions,
Marco

**Comment by hkosova** [comment]
There's no need for separate schemas. You can use a single `PetBody` schema and define `id` as required and [`readOnly: true`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#user-content-schemareadonly):

> Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. **If the property is marked as `readOnly` being `true` and is in the `required` list, the `required` will take effect on the response only.**

**Comment by marcortw** [comment]
Great, this is exactly what I needed! Thank you very much for the hint.
