### ISSUE TITLE
2.0 version: Using specific properties while referencing to schema

### ISSUE THREAD

**Issue by AyoubKhial** [OAI/OpenAPI-Specification#1938]
I'm using swagger 2.0 and I have the following schema(definition) :
```
"User": {
    "type": "object",
    "properties": {
        "firstName": {
            "type": "string",
            "example": "Tom"
        },
        "lastName": {
            "type": "string",
            "example": "Hanks"
        },
        "email": {
            "type": "string",
            "example": "Tom.Hanks@gmail.com"
        },
        "password": {
            "type": "string",
            "example": "azerty@123456"
    }
}

```
and i want to refer to this schema in one of my responses, so i do the following:

```
"responses": {
    "201": {
        "description": "Created.",
        "schema": {
            "$ref": "#/definitions/User"
        }
    }
}
```
Until now everything works perfectly, but i don't want to expose the password property in the response schema. is the anyway to choose exactly the properties i want to use from the User definition ?

**Comment by philsturgeon** [comment]
You can have a User without the password property, then make a CreateUser which extends the normal user, using an allOf $ref to the user and adding the property. 

OpenAPI v2 won't let you allOf though so better upgrade to OpenAPI v3. :)

**Comment by MikeRalphson** [comment]
OpenAPI 2.0 **does** support [allOf](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism).

What it does not support is the `writeOnly` property which was added in v3.0 and would allow you to more simply declare that the `password` property was not returned in the response.

**Comment by handrews** [comment]
@MikeRalphson any reason to keep this open as there's been no further discussion for six months?

**Comment by webron** [comment]
I believe this can be closed indeed.
