### ISSUE TITLE
Schema reference having a same name as the schema in parent document

### ISSUE THREAD

**Issue by r-sreesaran** [OAI/OpenAPI-Specification#1940]
Consider having two open api documents.

```openapi: 3.0.0
 info:
  title: Common Data Types
  version: "1.0"
paths:
  /subscriptions:
    get:
      summary: read all of the active subscriptions for the app.
      operationId: getSubscriptionsById
      parameters:
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK (Successful)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          $ref: './issue-1108-1.yaml#/components/responses/E500'
        '501':
          $ref: '#/components/schemas/ProblemDetails' 
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem
        status:
          type: integer
          description: The HTTP status code for this occurrence of the problem.
    Subscription:
      type: string
```
  

Open api document for sample.yaml
```openapi: 3.0.0
info:
  title: Common Data Types
  version: "1.0"
paths: {}
components:
  responses:
    E500:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
  schemas:
   ProblemDetails:
      type: object        
```
Here there are two schema having the same name.  Can this be referenced like wise. 
Open API cannot have duplicate schema under components.
By this there totally two schema with the same. 

can you point me towards the part of the specification that clarifies the part about referencing schema with name as in original document or can you shed some light as to the correctness of my understanding and validate where this is correct ?.

**Comment by handrews** [comment]
@r-sreesaran references like

`$ref: '#/components/schemas/ProblemDetails'`

are URI fragments, which are resolved purely within the context of the current document**.  That form of reference cannot ever resolve against a second OpenAPI document.

Please close this if that answers your question :-)

**technically within the current "base URI", but for OpenAPI that means the current document.

**Comment by handrews** [comment]
It's been more than 2 weeks so I'm assuming the answer was sufficient.
