### ISSUE TITLE
 TSC Open Meeting - June 13th

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#1941]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 4pm-5pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
|  || |
| | | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by philsturgeon** [comment]
Can we talk about Alternative Schemas? I sat down for a few days and tried coming up with how we'd actually implement this at Stoplight, and noticed that it's going to be awfully hard.

https://github.com/OAI/OpenAPI-Specification/issues/1943

**Comment by philsturgeon** [comment]
Also https://github.com/OAI/OpenAPI-Specification/pull/1946

**Comment by ahl** [comment]
There were some loose ends from the meeting a couple of weeks ago; could we follow up on those? https://github.com/OAI/OpenAPI-Specification/issues/1928

**Comment by tbarn** [comment]
A note for future weeks, it should say 4pm-5pm UTC. Not 5-6pm.

**Comment by handrews** [comment]
I think this doesn't need to be kept open.  I'm sure @philsturgeon can be relied on to keep track of his open PR 😁
