### ISSUE TITLE
Response schema Objects of type Object not coming

### ISSUE THREAD

**Issue by reddyonlinenow** [OAI/OpenAPI-Specification#1947]
Response Object 

class ResponseObject {
Object object1;
Object object2;
}

in the schemas(Swagger-UI)  its showing the object2 only and object1 is missing in the Schema

**Comment by tedepstein** [comment]
Hi @reddyonlinenow , this project is for the OpenAPI specification itself. Swagger-UI is a separate project:

https://github.com/swagger-api/swagger-ui

It sounds like your issue is specifically with Swagger-UI's interpretation of your class. If that's the case, kindly close this issue here and report your problem in a new issue on the Swagger-UI project.

**Comment by reddyonlinenow** [comment]
Hi tedepstein, I am not using Swagger-ui, however I am using the jar dependency `     <groupId>org.webjars</groupId> <artifactId>swagger-ui</artifactId>`

I am using OpenAPIDefinition 
 @ApiResponse(content = @Content(schema = @Schema(implementation = ResponseObject.class)

**Comment by tedepstein** [comment]
@reddyonlinenow , 

> `<groupId>org.webjars</groupId> <artifactId>swagger-ui</artifactId>`

That looks like a maven dependency on Swagger-UI, hosted on webjars.org. 

> I am using OpenAPIDefinition
> @ApiResponse(content = @content(schema = @Schema(implementation = ResponseObject.class)

Those looks like [Swagger-Core annotations](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations) on a Java class to map your implementation to OpenAPI. 

Swagger-UI and Swagger-Core are open source projects, each with its own GitHub repo, that _work with_ the OpenAPI specification. The [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md) itself, maintained in this repo, is the standard object model, represented in JSON or YAML, that defines your API and its message schemas.

To be clear, there is nothing in the OpenAPI specification that "shows" (or fails to show) your schemas. There is nothing in the OpenAPI specification that defines Java annotations, or any other means of mapping your classes into an OpenAPI model. These are all implementation issues, specific to the tooling that you're using.

**Comment by MikeRalphson** [comment]
Closing, as above. Thanks @tedepstein
