### ISSUE TITLE
Is it possible to expose 2 different APIs for the same method and path, just changing the query params?

### ISSUE THREAD

**Issue by hjpbarcelos** [OAI/OpenAPI-Specification#195]
I have 2 possible signatures for an API, something like:

```
GET someurl?param1=val1
GET someurl?param2=val2&val3
```

I know I can declare it as a single entry point for my API, making all parameters optional and then programmatically verify which of them my application is trying to reach.

I could not find in the docs if it is possible to do this on the swagger spec file.
I've tried to put 2 GET entries under the same path, but when I do this, only the first one is valid.

**Comment by iambingoNJU** [comment]
Hi, I come across the same problem, and I wan't to know if this feature has been added to the latest swagger spec. @webron
