### ISSUE TITLE
Behaviour when multiple parameters with explode true or mix explode false/true

### ISSUE THREAD

**Issue by ChristopherAparicio** [OAI/OpenAPI-Specification#1955]
The Specification is unclear about the way to use explode and if there is the possibility to mix parameters with Explode stetted at true and false. 

My question is : Is it possible to have at least two parameters stetted a true in the same operation ?  Or an object parameter setted at true and simple parameters with explode at false ?

In both case, it must be written somewhere in the specification under the Operation Object Section to be clearer

If it's possible,  It's maybe possible to have some conflict between parameters setted at true.
 
Case 1 : Two objects parameters with the same property **Foo** and explode true. It's ambigous and makes impossible the rendering at the parameter level due to the property name conflict.

Case 2 : One object parameter with explode setted at true and a property **Foo** and a parameter with the name **Foo** in the same location 'in' as the object and explode setted at false. In this case it's still ambiguous because there is a conflict between the property object named **Foo** and the Parameter name with the name **Foo** 

Best Regard,

**Comment by ChristopherAparicio** [comment]
Any news ?

**Comment by webron** [comment]
Can you provide a sample definition showcasing the issue? It's a bit difficult to follow from the worded examples.

**Comment by ChristopherAparicio** [comment]
Sure, 

Case 1 : 
The problem in this case is, there is two objects with explode setted at true. So we can have two times the same property in two different parameters

?foo=hello&bar1=world&foo=foo&bar2=5

Case 2 : 

One parameters is an object with a property foo and the other parameter has a name foo.
?foo=5&foo=hello&bar2=world

There are no explanation in case of conflict in the documentation.

![case2](https://user-images.githubusercontent.com/1843154/61803317-39a19780-ae32-11e9-9439-ff8d2cf8045f.png)
![case1](https://user-images.githubusercontent.com/1843154/61803318-3a3a2e00-ae32-11e9-986c-36b362800470.png)

**Comment by ChristopherAparicio** [comment]
Any news ?

**Comment by webron** [comment]
There isn't actually a conflict here. Query parameters with the same name can repeat, that's perfectly legal. If they have different types, theoretically the producer can detect which one is meant from the type. If they're the same type, the again, it's up to the producer to decide which is which. 

So technically, it's up to the producer. Doing something like that generally feels like a bad practice, but if the user ends up defining it that way, they should also know what behavior they want to see.

**Comment by handrews** [comment]
This was answered in 2019 with no further questions, closing.
