### ISSUE TITLE
TSC Open Meeting - June 27th

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#1962]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 4pm-5pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
|  Latest JSON Schema updates and compatibility with OAS Schema | Phil S.  | |
| Message level security | Phillipe (if available) | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
Suggested topic https://github.com/OAI/OpenAPI-Specification/issues/1953

**Comment by handrews** [comment]
Seems safe to close.
