### ISSUE TITLE
TSC Open Meeting - July 11th (Cancelled)

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#1963]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 4pm-5pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

**NOTE: The meeting on July 4th has been cancelled.**

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
|  |  | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
Due to no suggested agenda items and a backlog of actually GitHub based work to do, we decided to use the meeting time to deal with issues instead.

**Comment by handrews** [comment]
Seems safe to close.
