### ISSUE TITLE
Same $ref for properties of multiple objects, but different object descriptions?

### ISSUE THREAD

**Issue by GrahamHannington** [OAI/OpenAPI-Specification#1966]
The "no siblings" restriction on `$ref` is a problem for me.

I'm documenting an API (not my design) where several objects in the response have the same set of properties. I've used `$ref` to "single source" that set of properties as a component, but I've had to push the object descriptions to the parent object.

Here's a snippet of the response. Some of the objects are singletons, others are arrays. I've fictionalized the object and property names:

```json
"parts": {
  "partA": {
    "processName": "string",
    "containerName": "string",
    "processId": 1
  },
  "partB": {
    "processName": "string",
    "containerName": "string",
    "processId": 2
  },
  "partC": {
    "processName": "string",
    "containerName": "string",
    "processId": 3
  },
  "partD": {
    "processName": "string",
    "containerName": "string",
    "processId": 4
  },
  "partE": {
    "processName": "string",
    "containerName": "string",
    "processId": 5
  },
  "partF": {
    "processName": "string",
    "containerName": "string",
    "processId": 6
  },
  "partG": {
    "processName": "string",
    "containerName": "string",
    "processId": 7
  },
  "partH": [
    {
      "processName": "string",
      "containerName": "string",
      "processId": 8
    },
    {
      "processName": "string",
      "containerName": "string",
      "processId": 9
    }
  ],
  "partI": [
    {
      "processName": "string",
      "containerName": "string",
      "processId": 10
    },
    {
      "processName": "string",
      "containerName": "string",
      "processId": 11
    }
  ],
  "partJ": {
    "processName": "string",
    "containerName": "string",
    "processId": 12
  }
}
```

Here are the related snippets of the OpenAPI 3.0.2 definition. The `parts` definition:

```yaml
parts:
  type: object
  description: |
    Information about each part:
    
    - `partA`: Description of part A
    - `partB`: Description of part B
    - `partC`: Description of part C
    - `partD`: Description of part D
    - `partE`: Description of part E
    - `partF`: Description of part F
    - `partG`: Description of part G
    - `partH`: Description of part H
    - `partI`: Description of part I
    - `partJ`: Description of part J
    
  properties:
    partA:
      $ref: '#/components/schemas/part'
    partB:
      $ref: '#/components/schemas/part'
    partC:
      $ref: '#/components/schemas/part'
    partD:
      $ref: '#/components/schemas/part'
    partE:
      $ref: '#/components/schemas/part'
    partF:
      $ref: '#/components/schemas/part'
    partG:
      $ref: '#/components/schemas/part'
    partH:
      type: array
      items:
        $ref: '#/components/schemas/part'
    partI:
      type: array
      items:
        $ref: '#/components/schemas/part'
    partJ:
      $ref: '#/components/schemas/part'
```

The referenced component:

```yaml
components:
  part:
    type: object
    properties:
      processName:
        type: string
        description: Process name of this part.
      containerName:
        type: string
        description: Name of the container in which this part is running.
      processId:
        type: integer
        description: Process identifier of this part.
```

Pushing the descriptions of each part into the description of the parent `parts` object is a kludge.

I'd prefer to have the description of each part _with the definition each part_, but then I wouldn't be able to use `$ref`, because of the "no siblings" restriction.

Am I missing something? Is there a more elegant way to do this, while keeping those properties single-sourced?

I can imagine, if that restriction was lifted, being able to do this:

```yaml
    partA:
      description: Description of part A
      $ref: '#/components/schemas/part'
```

but I can also imagine that the OpenAPI designers thought long and hard about that restriction, and have very good reasons for it.

**Comment by handrews** [comment]
@GrahamHannington The restriction comes from JSON Schema (or JSON Reference which was at one point proposed as a separate spec.

This restriction is lifted in the [very soon to be published next draft](http://json-schema.org/work-in-progress), which also defines a way for applications to decide how to handle situations such as a `description` or `title` field appearing both beside a `$ref` and in the target of the `$ref`.

There are several efforts towards allowing the use of this next draft in OpenAPI.  @philsturgeon is working with the TSC on it.

**Comment by GrahamHannington** [comment]
@handrews,

Thanks for the reply. Sounds good; I look forward that.
