### ISSUE TITLE
Path Templating: is there a restriction on the path parameter name?

### ISSUE THREAD

**Issue by jmini** [OAI/OpenAPI-Specification#1969]
According to [the specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-10), each defined path parameter must correspond to a same-named variable placeholder in the path:

> **name:** If [`in`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterIn) is `"path"`, the name field MUST correspond to the associated path segment from the path field in the Paths Object. See [Path Templating](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#pathTemplating) for further information.

There is no information about what is a valid name. Is there any restriction/recommendation about the characters that should or must be used?

For example, for:

```
GET <server>/api/231
```

`231` corresponds to the path parameter.

In the following example with the name is `todoID`:

```yaml
openapi: 3.0.1
info:
    title: Todo Backend
    version: '1.0'
paths:
    '/api/{todoID}':
        get:
            parameters:
                -  name: todoID
                   description: The id of the todo
                   schema:
                        format: int64
                        type: integer
                   in: path
                   required: true
            responses:
                '200':
                    description: OK
            summary: Get one todo
```

An other example with `todo-id`:

```yaml
openapi: 3.0.1
info:
    title: Todo Backend
    version: '1.0'
paths:
    '/api/{todo-id}':
        get:
            parameters:
                -  name: todo-id
                   description: The id of the todo
                   schema:
                        format: int64
                        type: integer
                   in: path
                   required: true
            responses:
                '200':
                    description: OK
            summary: Get one todo
```

Are both names (`todoID` and `todo-id`) allowed?

**Comment by MikeRalphson** [comment]
OAS 3.0 imposes no restrictions on parameter names, whether in: path or not. Even the empty string should be valid.

That said, use of { and } characters in path parameter names could lead to confusion, so you might want to avoid this.

Certainly your two examples are both fine.

**Comment by handrews** [comment]
This was answered with no further questions, so closing as resolved.  For improving the requirements of path templating, see issue #3256.
