### ISSUE TITLE
`type` on `operation` object vs `responseMessage.responseModel`

### ISSUE THREAD

**Issue by STRML** [OAI/OpenAPI-Specification#197]
When it comes to defining the return type of an operation, it appears that there are two valid ways to go. 

The first is to define a `type` on the operation, e.g. like so:

``` json
{
  "path": "/user/login",
  "operations": [{
    "method": "POST",
    "nickname": "login",
    "parameters": [],
    "type": "User",
    "summary": "Log in."
  }]
}
```

The other is to define a `responseModel` as part of a `responseMessage`. This could be useful if multiple types of responses are possible. We discuss this in this [loopback-explorer issue](https://github.com/strongloop/loopback-explorer/pull/61#issuecomment-59032661):

``` json
{
  "path": "/user/login",
  "operations": [{
    "method": "POST",
    "nickname": "login",
    "parameters": [],
    "responseMessages": [{
      "code": 200,
      "message": "Request was successful",
      "responseModel": "User"
    }],
    "summary": "Log in."
  }]
}
```

Which is the preferred style? If it is to use `type`, and to use `responseMessages` only for errors, could it be made more clear in the 1.2 spec that `type` is required?

**Comment by rajab57** [comment]
@webron 
To clarify, for version 1.2 , is there a way to use type to return 2 models ? Or the response can only return 1 model ( can be nested ) ?

**Comment by webron** [comment]
@rajab57 - no matter which version of Swagger you use, you can only return 1 type of model. If you want to return several models that have a common ground (that is, at least one property that's common to them and can be used to distinguish between them), then you can use inheritance. Otherwise, only one model.
