### ISSUE TITLE
Requirements around responses property and object lead to bloated specification file

### ISSUE THREAD

**Issue by VitaliyKurokhtin** [OAI/OpenAPI-Specification#1975]
Specification explicitly says that `responses` property is required in `Operation Object`:
![image](https://user-images.githubusercontent.com/990083/61414072-e794cb00-a8a1-11e9-8145-a550e8524848.png)

At the same time `Responses Object` itself has these requirements:

- The `default` MAY be used as a default response object for all HTTP codes that are not covered individually by the specification.

- The `Responses Object` MUST contain at least one response code, and it SHOULD be the response for a successful operation call.

And `Response Object` has this to say about it's properties:
![image](https://user-images.githubusercontent.com/990083/61414335-8cafa380-a8a2-11e9-9959-4f8a7c31013a.png)

This is all fine when OpenAPI specification is actually complete and properly written, but unfortunately this is not always the case, by far. It is often that you have to deal with specifications that are incomplete and lack any description of operation responses entirely. Sometimes this is done by omission, sometime responses are considered not to be important for the use case. When that is the case to make specification complete and validate against schema one has to add such bloat to every operation in there:

```
"responses": {
    "200": {
        "description": ""
    }
}
```

Which doesn't seem helpful at all. Later on while reading such spec these blocks would only provide a distraction and obstruct actual meaning behind the spec.

Hence the proposal to make `responses` not required property for an operation.

**Comment by MikeRalphson** [comment]
`responses` is optional in OAS v3.1.0 - thanks for the issue.
