### ISSUE TITLE
Hyperlink support in Swagger

### ISSUE THREAD

**Issue by Shulamite** [OAI/OpenAPI-Specification#198]
It will be nice to provide support for link relations in swagger.

**Comment by ashokmalhotra** [comment]
There has been no action on this since Nov 28.   If we want to use Swagger as a description language, this is a deal-breaker.

**Comment by webron** [comment]
@ashokmalhotra - unlike the tooling, the spec doesn't change too often. We've released 2.0 back in September so you shouldn't expect seeing a new version this soon.

**Comment by ashokmalhotra** [comment]
Is there enough interest to add Link support to the spec?
Can you give me a rough date?

**Comment by webron** [comment]
Really too early to say. There's definitely interest in it and we'll discuss it when the time comes.

And no, I cannot give you a rough date.

**Comment by webron** [comment]
Parent: #555.

**Comment by Shulamite** [comment]
We are currently using x-links in swagger, and the content of x-links is pretty much the json hyper schema's links. 
http://json-schema.org/latest/json-schema-hypermedia.html

**Comment by awwright** [comment]
How are hyperlinks currently implemented?

**Comment by darrelmiller** [comment]
@awwright In v3 operations can be related via the links object (some description here https://www.openapis.org/blog/2016/11/14/tdc-protocol-and-payload-explaining-the-3-0-spec-part-4 ).  However this is purely a design time concept.
Any operation request or response can be described using a hypermedia enabled media type.  But OpenAPI makes no attempt to describe what links may or may not appear in those hypermedia payloads.

**Comment by philsturgeon** [comment]
So what do we think about this one? Is links enough, are we leaving the rest to the hypermedia formats of the world, or is there ever likely to be further work on hypermedia.

**Comment by darrelmiller** [comment]
The only other work I see is the ability to define path Item Objects that don't have a fixed URL.  And we sort of are doing that with making Path Item Objects components.  I don't think there is anything novel in this issue to warrant keeping it open.
