### ISSUE TITLE
Prevent serialisation of null properties

### ISSUE THREAD

**Issue by setzamora** [OAI/OpenAPI-Specification#1984]
Is there a way to define in the spec to exclude optional properties upon serialisation when they're null?

e.g.

```
{
    "Name": "First Last",
    "Age": 17,
    "Ethnicity": null
}
```

In this case, I don't want to serialise the property _Ethnicity_.

In C#, it's easily achieved by decorating with a `[DataMember (EmitDefaultValue = false)]`

**Comment by webron** [comment]
This is not a spec concern, but rather a tooling one. Whichever tool you use should provide you with that option.
