### ISSUE TITLE
Clarification on pattern regex literals

### ISSUE THREAD

**Issue by ricellis** [OAI/OpenAPI-Specification#1985]
The [specification for pattern](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#properties) says
>This string SHOULD be a valid regular expression, according to the ECMA 262 regular expression dialect

I think this is extracted verbatim from the [JSON Schema validation draft](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.3.3) as per #880

However, the section of [ECMA262 linked to](https://www.ecma-international.org/ecma-262/5.1/#sec-7.8.5) describes the regular expression literal i.e. `/ RegularExpressionBody / RegularExpressionFlags` so it is unclear whether "valid regular expression" means the body or the literal.

There are no example usages of regex patterns in the OAS 3.0.2 document that I can see. However, another example of patterns used in OpenAPI that I have found **does not** include the `/`  characters around the regex e.g.:
* `pattern: '^\d{3}-\d{2}-\d{4}$'` from [swagger doc](https://swagger.io/docs/specification/data-models/data-types/#pattern)

I think it is unclear from the specification (either OAS or JSON schema validation) whether the pattern field is expected to be a complete ECMA 262 regular expression literal, including the `/` characters and optionally including flags, or whether it is saying that only a regular expression body is expected.

Tooling behaviour seems a little inconsistent on this too, so I think a clarification would be useful to help tooling developers know which of these 3 types of pattern values should be supported:
1. `myregexbody`
1. `/myregexbody/`
1. `/myregexbody/myregexflags`

**Comment by handrews** [comment]
@ricellis it is definitely 1. `myregexbody`.  The correct reference is [ECMA 262 Annex A.7, "Regular Expressions"](https://www.ecma-international.org/ecma-262/5.1/#sec-A.7), although given that that section is informative rather than normative there might be some complications on exactly how to cite that.  Referencing `RegularExpressionBody` for clarity would probably be a good idea.

This should really be filed on the JSON Schema spec repo.

I'll try to remember to clarify that i

**Comment by ricellis** [comment]
I've opened https://github.com/json-schema-org/json-schema-spec/issues/774 for a clarification in the JSON Schema validation spec. I guess there may still be work here to update the link in the OAS spec or also cite that only a `RegularExpressionBody` is expected.

**Comment by ricellis** [comment]
Note that the JSON Schema spec has been updated (targetting draft-08) to clarify this via https://github.com/json-schema-org/json-schema-spec/issues/775.

As per that clarification; the correct ECMA 262 section to link is 15.10.1 - I've opened PR #1987 to correct the OpenAPI spec link to also point to that section.

**Comment by handrews** [comment]
[JSON Schema 2019-09](http://json-schema.org/specification.html) (formerly known as "draft-08") has been published, and OAS PR #1977 is about updating the Schema Object to be compatible with it in OAS 3.1.  I think the PR mentioned above is still useful for OAS 3.0, as the JSON Schema draft there will not be changing.

**Comment by philsturgeon** [comment]
This was fixed in #1977 so we can close this.

**Comment by akimking-86** [comment]
ok
