### ISSUE TITLE
Unable to get Record while using the double backslash in swagger using get function With Parameters 

### ISSUE THREAD

**Issue by Jeegen** [OAI/OpenAPI-Specification#1994]
I've two parameters like Register No. and UserName. I Entered Register No. Like "*\*\*\*###$$$$%%%%" and UserName Like "TESTPC\\\\TEMP" than result is successful but no record shown.  
Instead of above if I Entered. Like 
UserName. I Entered Register No. Like "\*\*\*\*###$$$$%%%%" and UserName Like "TESTPC\\TEMP" than record is displayed.

Question: What is the difference between that. Because I posted record with double slash but in SQL server its shown single. so how do i specify a value for UserName at run time.

Thanks.
Jeegen

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
