### ISSUE TITLE
Clarification Of `allOf` Support Within OpenAPI Version

### ISSUE THREAD

**Issue by bhreinb** [OAI/OpenAPI-Specification#1996]
I notice discrepancies between documentation I’m seeing on this repository and another source.

I notice on this page 

`https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md`

That properties `allOf` were adjusted to the swagger specification. However when I go to this page 

`https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/`

It mentions that properties within that page (for example `allOf`), applies to OpenAPI 3 – the latest version of the OpenAPI Specification.

So my question is if a parser is build to parse swagger OpenAPI 2 specification should it be able to support parsing of `allOf` properties. The swagger link would indicate to me that it shouldn’t as they are claiming it to be a version 3 item.

Thanks in advance.

**Comment by MikeRalphson** [comment]
The GitHub markdown is the source-of-truth for the specification, thus OpenAPI 2.0 does support `allOf`.

The swagger.io link you reference says it applies to OpenAPI 3.0, but it does not say that `allOf` was **introduced** in OAS 3.

If you follow the links to https://swagger.io/specification/v2/ `allOf` is also documented there.

**Comment by bhreinb** [comment]
Thanks @MikeRalphson for the clarification.
