### ISSUE TITLE
Not getting null values in JSON response in openspec 3.0.0

### ISSUE THREAD

**Issue by kishoretangudu** [OAI/OpenAPI-Specification#1997]
Description: In DB some columns has null values. I am getting the null data till controller layer in spring-boot application. But in response the null valued fileds getting filtered. I think this magic done by ResponseEntity Class(org.springframework.http.ResponseEntity).
OpenSpec API default Response Class is : ResponseEntity. Not sure how to change this. 
I am defining my openspec like this for returning response: 
```yaml
responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyPojoClass'
components:
  schemas:
    MyPojoClass:
      description: PrimeBroker Short lending availability
      type: object
      properties:
        field1:
         description: xyz
         title: xyz
         type: string
        field2:
          description: xyz
         title: xyz
         type: string
        field3:
          description: xyz
         title: xyz
         type: string
```
I am getting response but null values are skipping during response build. I need null values also part of my JSON response. Please tell me is there a work around or its limitation?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by kishoretangudu** [comment]
Could you please let me know where to post this issue., as I dont have permissions to raise this conern in stackoverflow?

**Comment by kishoretangudu** [comment]
Could you please let me know where to post this issue other than stackoverflow?

**Comment by MikeRalphson** [comment]
Presumably on the repository for the spring-boot framework or one of its plugins?
