### ISSUE TITLE
Handle creation files in Scala

### ISSUE THREAD

**Issue by sviatoslavRSV** [OAI/OpenAPI-Specification#1999]
I implemented inheritance in scala using `sealed trait`, that means location of all childs in same file with trait. Generated list of files:
Pet.scala
```
sealed trait Pet
case class Cat() extends Pet
case class Dog() extends Pet
```
Cat.scala
```
case class Cat()
```
Dog.scala
```
case class Dog()
```

As we can see, classes generated twice, that caused duplicates conflict.
How can I handle creation of files, either exclude generated files or avoid their generation at all?

p.s: When I used 4.1.1 v., it is also created AllOf files that is known problem. 

Thanks.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
