### ISSUE TITLE
[Question] Formatting of header parameters based on media type

### ISSUE THREAD

**Issue by jdegre** [OAI/OpenAPI-Specification#2008]
Hi,
OpenAPI 3.0.x defines 2 ways to specify the formatting of parameters:
- using "schema" plus "style", for simple parameters
- using "content" plus a media type, such as "application/json", for complex parameters

My doubt is: can the second option ("content") be used as well with "header" parameters?

In other words, is the following excerpt allowed? (**from spec point of view**, regardless of tooling support):

```
name: token
in: header
description: token to be passed as a header
required: true
content:
  application/json:
    schema:
      $ref: '#/components/schemas/Token'
```

Any view?

Thanks in advance!

**Comment by lornajane** [comment]
I think this use case is technically correct, but is unlikely to be well supported in tooling (which I think you know). Also since this issue has been open some time without engagement, I'll now close it.
