### ISSUE TITLE
Open TSC Meeting - September, 26th 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2010]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 4pm-5pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  

/cc @OAI/tdc Please suggest items for inclusion

**Comment by tedepstein** [comment]
* [#1977](https://github.com/OAI/OpenAPI-Specification/pull/1977) (Update Schema Objects to JSON Schema Draft 2019-09)  - On closer reading, the 3.0.2 specification is ambiguous about the meaning of `nullable: false`. That's a good thing, because we now have a much happier resolution to the whole `nullable` conundrum.

**Comment by handrews** [comment]
* #2017 (`$schema` guidance for OAS 3.1) is a follow-on issue to PR #2016.  I don't expect anyone to have read it in the next 10 minutes before the meeting starts, but if we have time and there is interest, I can walk folks through the idea which might make reading it in detail later easier.

**Comment by handrews** [comment]
#1977 got merged!  No other major things in this agenda issue, closing.
