### ISSUE TITLE
How to add a new format definition?

### ISSUE THREAD

**Issue by ruozhixian** [OAI/OpenAPI-Specification#2013]
The data type, for example, `string`, has an optional modifier property: `format`. the format can be `date`、`date-time`、`password`, and so on.
So, how to add a new format definition for string、integer or other data types?

**Comment by MikeRalphson** [comment]
From the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types):

>  OAS uses several known formats to define in fine detail the data type being used. However, to support documentation needs, the format property is an open string-valued property, and can have any value

If you need tooling interoperability, it may be worth looking at the `pattern` property for strings too.

The TSC is also in the process of formalising a `format` registry, see https://github.com/OAI/OpenAPI-Specification/issues/845
