### ISSUE TITLE
OpenAPI 3.0 does not support csv-serialized form-data arrays

### ISSUE THREAD

**Issue by mkistler** [OAI/OpenAPI-Specification#2018]
## The OpenAPI 2.0 behavior

In OpenAPI 2.0, a parameter defined as `in: form` with `type: array` defaulted to `collectionFormat: csv` — meaning that the values of the array should be joined into a comma-separated string and passed in a single form data element [ref][oas2].

[oas2]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7

## The OpenAPI 3.0 behavior

In OpenAPI 3.0, the default for arrays in a request body appears to be the equivalent of `collectionFormat: multi` — pass each element of the array in its own form data element.
This was hard to track down but here's my step-by-step reading of the spec:

### Details -- feel free to skip

In OpenAPI 3.0, form parameters are now described as properties in a request body.

An [encoding attribute](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object) can be used to specify the serialization of parts of multipart request bodies.

Within the encoding object is a `style` property which
>  Describes how a specific property value will be serialized depending on its type. See Parameter Object for details on the style property. The behavior follows the same values as query parameters, including default values. This property SHALL be ignored if the request body media type is not `application/x-www-form-urlencoded`.

So when the media type is other than `application/x-www-form-urlencoded`, the serialization will be handled using the default `style` for query parameters, which is 'form' [ref][style].

[style]: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#fixed-fields-10

In [Style Values](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#style-values), `style` of `form` means:
> Form style parameters defined by RFC6570. This option replaces collectionFormat with a csv (when explode is false) or multi (when explode is true) value from OpenAPI 2.0.

So what is `explode`? Back to the encoding object: 
- This property SHALL be ignored if the request body media type is not `application/x-www-form-urlencoded`.
- When `style` is `form`, the default value is `true`.  

So when media type is other than `application/x-www-form-urlencoded`, all properties of the request body are serialized as `style: form, explode: true` -- the equivalent of `collectionFormat: multi` in OpenAPI 2.0.

## Conclusion

So the default value changed.  That's not great but would probably be acceptable in a new major release of the spec, except that there appears to be _no way_ to specify the OpenAPI 2.0 default behavior (`collectionFormat: csv` ) for properties in`multipart` request bodies in OpenAPI 3.0. Both the `style` and `explode` properties in `encoding` are explicitly restricted to media type `application/x-www-form-urlencoded`, so only the default serialization -- `style: form, explode: true` is possible.

**Comment by mkistler** [comment]
Here is my high-level proposal for how to fix this issue.

I think it is highly desirable to fix this in a point release of 3.0, so it must be done compatibly.  And I think that means that
- we can't change any defaults, e.g. the default `style` for query params
- we can't change any instance where the spec stipulates that a property "SHALL" be ignored, e.g.  `style` and `explode` SHALL be ignored if the request body media type is not `application/x-www-form-urlencoded`.

In light of this, I think we have to use new keywords to specify this behavior. For example, we could add two new keywords to the `encoding` object, `multipart-style` and `multipart-explode`, that have the same basic meaning as `style` and `explode` but are ignored if the if the request body media type is not `multipart`.  This would effectively eliminate the ignoring of `style` and `explode` for `multipart` request bodies, but in a compatible way.

I'll be the first to admit that this is not a pretty solution, and I'd be happy for suggestions on better names than `multipart-style` and `multipart-explode`, but I believe this corrects the basic problem in the spec and does it in a compatible way.

Feedback welcome!

**Comment by mkistler** [comment]
A little more context: An example of this issue is the `classify` operation of IBM Watson Visual Recognition service.  The OpenAPI 2.0 version of VR's API doc, `classify` accepts a form parameter:
```
    {
      "name": "classifier_ids",
      "in": "formData",
      "description": "Which classifiers to apply.",
      "required": false,
      "type": "array",
      "items": {
        "type": "string"
      }
    }
```
In OpenAPI 2.0, because no "collectionFormat" is specified, the default is to encode this as a csv string.

When we updated our API docs to OpenAPI 3.0, this form parameter became a property in the "multipart/form-data" request body:
```
      "classifier_ids": {
        "description": "Which classifiers to apply.",
        "type": "array",
        "items": {
          "type": "string"
        }
      }   
```
By the reasoning explained in the issue description, this property defaults to `style=form` and `explode=true`, and these characteristics cannot be changed in the `encoding` object because the 
media type is not `application/x-www-form-urlencoded`.

**Comment by mkistler** [comment]
Based on the discussion in the 10/10 OpenAPI TSC meeting, there may be more flexibility in how we address this issue than I previously stated.  So here's my "ideal" solution to this issue:

Remove the sentence "This property SHALL be ignored if the request body media type is not `application/x-www-form-urlencoded`" from both the `style` and `explode` properties of the `encoding` object.

I understand that these sentences were originally added because of concern for how `style` and `explode` might be interpreted for request bodies of other media types like `application/json`, but the spec already states:
> The _encoding_ attribute ... is only applicable to `multipart` and `application/x-www-form-urlencoded` request bodies.

Removing those qualifying sentences will make it possible to define array properties in multipart/form-data request bodies as `explode: false` -- the equivalent of the old (and default) OpenAPI 2.0 `collectionFormat: csv`.

**Comment by mkistler** [comment]
After the TSC meeting last week, @webron reached out to me on Slack regarding this issue.

@webron believes (apologies if I captured this incorrectly) that the OAS 3.0.x spec _does not specify_ how arrays should be serialized in multipart request bodies.

In particular, the statements
> This property SHALL be ignored if the request body media type is not `application/x-www-form-urlencoded`.

in the description of `style` and `explode` in the `encoding object` (and `allowReserved` for that matter) really mean:
> This property has no effect on the encoding of properties if the request body media type is not `application/x-www-form-urlencoded`.

Further, the encoding object is intended to be consistent with the way parameters are defined, using either a `schema` or a `content` object:
> A parameter MUST contain either a `schema` property, or a `content` property, but not both.

Note that a query parameter for passing an array of strings can be defined as:
```
in: query
name: collection_ids
content:
  application/json:
    schema:
      type: array
      items:
        type: string
```
but when defined this way there is _no way to specify_ how the array is serialized.

So array parameters defined with a `content` object have the same problem as array properties in `multipart` request bodies in that the serialization style cannot be specified.

@webron believes that a proper fix would address both these problems in a consistent way.

**Comment by mkistler** [comment]
Not sure how to engage others in this discussion, so I guess I will just continue my monologue.

I want to point out that the `contentType` attribute in the `encoding` object _does not_ state that it is mutually exclusive with `style`\ `explode`, so this is NOT like parameters where only one or the other may be used.  In other words, `contentType` and `style`/`explode` _must_ be compatible for `application/x-www-form-urlencoded` request bodies.  I see no reason why they cannot also be compatible for `multipart/form-data` request bodies.

I failed to mention in my previous post that @webron believes that for an array property, `contentType` applies to the _entire array_, and not the individual items of the array.  At the very least, we should clarify the spec on this detail.

I contend that @webron’s interpretation is inconsistent with the way the default values are described: > for array – the default is defined based on the inner type.

Further, if we adopted @webron’s interpretation, I don’t know this would work in practice.  Consider a request body containing an array whose individual items are of contentType `image/jpeg`.  You could not describe the entire array as being of `image/jpeg`, since the array contains multiple images and `image/jpeg` describes a single image.

So I believe our clarification should be that `contentType` specifies the content type of the individual items when a property is an array.

And if we make that clarification, they why not allow the `explode` attribute to be specified for _any_ request body type that can have an `encoding` object?

**Comment by handrews** [comment]
@mkistler I'm kind of parachuting into the middle here, but isn't part of the point of `multipart/form-data` that each part has its own subsidiary media type?  Or am I confusing it with something else?

**Comment by mkistler** [comment]
@handrews Thank you for joining the discussion!!

Agreed that a key feature of `multipart/form-data` is the ability to specify a media-type with each form part.  What we still need to determine is what data goes into what form parts.

In OpenAPI 2.0, the _default_ behavior was to concatenate array items into a csv, all in one form part.  In OpenAPI 3.0, the behavior is either _unspecified_, if you accept @webron's interpretation, or that each item is passed in a separate form part _with no ability to specify csv concatenation into a single form part_, using the interpretation I gave at the top of this issue.

**Comment by darrelmiller** [comment]
Following conversations in the TSC meeting, we are leaning towards allowing the style, explode and allowReserved properties in the encoding object to be used for multipart/form-data.   multipart-form data is just a different serialization of url-encoded form and therefore should support the same set of behaviors.

**Comment by webron** [comment]
Closing as #2066 was merged! 🎉

**Comment by coolaj86** [comment]
Would someone kindly provide an example of what a CSV API looks like in a config file?

Or point to the relevant documentation?

I'm just picking up OpenAPI for the first time after over a decade of designing APIs and this is the first result when I search for "openapi 3.0 csv": https://search.brave.com/search?q=openapi+3.0+csv

I see that the issue is closed, and I see that some SHOULD and SHALL phrases were changed in a PR, but I'm not clear as to how I specify that an API accepts or responds with CSV from what I'm seeing here and there.

I've tried looking at some other search results and I haven't found a clear example yet.

**Comment by handrews** [comment]
@coolaj86 are you trying to put the CSV in a URL query string or in the HTTP message content (body)?

**Comment by coolaj86** [comment]
@handrews HTTP message content - up and down.

Ideally I'd like to be able to define the struct / model both for the text/csv upload and the download - the same as with JSON, but using non-nested kv pairs.

(or possibly simple nested lists where the value is separated by `;` like `foo,bar,"baz;grault;qux;quux",corge,grault` or a specific field actually is JSON as a bonus - similar to how it would be represented in Postgres and other DBs that support lists and json for fields).

**Comment by handrews** [comment]
@coolaj86 great- could you open an issue for this in the [OAI/spec.openapis.org](https://github.com/OAI/spec.openapis.org) repository?  This is where our [registries](https://spec.openapis.org/registry/index.html) live, including our recently-added [media type registry](https://spec.openapis.org/registry/media-type/).  I will add the "regstries" label after you file it.

Please open a request to add `text/csv` to the registry, and include any information about your use case that would seem to be helpful.  Don't worry about exactly what the solution will look like when filing it.  Usually we try to map the media type to the JSON Schema data model, and we can discuss that in the new issue.

Do mention any variations on the format (such as using semicolons instead of commas), or complex use cases (embedding JSON in a CSV cell and wanting to model that JSON).

BTW, it's best if we get issues from outside of our maintainers, which is why I'm asking you to file it instead of filing it myself.  Having it filed by a user helps us keep track of the demand.

Adding `text/csv` (or similar) to the registry won't guarantee that tools will support it, especially for older releases like 3.0, but it is the easiest way to get official guidance.  Other than that, you'd probably want to look at the documenation for whatever tools you are using.  Some implementations support media types we don't describe in the specification, but of course we can't advise you on how that works as we don't keep track of such things.

**Comment by karenetheridge** [comment]
FWIW, this is how I would declare a `text/csv` body in an OpenAPI document:

```yaml

...
  text/csv:
    examples:
      'simple example':
        dataValue: [ [ fieldname1, fieldname2, fieldname3 ], [ foo, bar, baz ], [ alpha, beta, gamma ]
        serializedValue: |-
fieldname1,fieldname2,fieldname3
foo,bar,baz
alpha,beta,gamma
    content:
      schema:
        type: array
        prefixItems:
          - $comment: the header line
            type: array
            const: [ fieldname1, fieldname2, fieldname3 ]
        items:
          $comment: the content lines
          type: array
          items:
            $comment: you could be more specific here with the expected format of the individual fields, using prefixItems
            type: string
          minItems: 3
          maxItems: 3
```

**Comment by handrews** [comment]
@karenetheridge if @coolaj86 is using 3.0, this won't work b/c of `prefixItems`, but let's dive into that in the new issue for the registry rather than continuing on a closed issue (yes, I know, I answered on a closed issue... I recognize I'm being a little inconsistent here).

**Comment by coolaj86** [comment]
@handrews https://github.com/OAI/spec.openapis.org/issues/40

I'm not sure if that's the kind of thing you're looking for... but it's the kind of thing I created. :)

**Comment by karenetheridge** [comment]
I believe this is wrong:

> So when media type is other than application/x-www-form-urlencoded, all properties of the request body are serialized as style: form, explode: true -- the equivalent of collectionFormat: multi in OpenAPI 2.0.

When all of `style`, `explode` and `allowReserved` are absent (or effectively absent, which is what "ignored" means), _style encoding is not used at all_ -- rather, we fall back to `contentType` (and its default behaviour when absent).

ref. https://spec.openapis.org/oas/v3.0.4.html#fixed-fields-for-rfc6570-style-serialization

So was this issue (and PR #2066 which resolves it) predicated on a misreading of the spec, which led folks to believe that `style` needed to be handled for multipart/form-data messages when this is actually not so?
