### ISSUE TITLE
Open TSC Meeting - October, 10th 2019

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#2023]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 4pm-5pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Semantic versioning in the spec | @OAI/tsc | |
| Publishing 3.1.0-RC0 | @OAI/tsc | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by mkistler** [comment]
Pls add: Support for csv-serialized form-data #2018

**Comment by earth2marsh** [comment]
In support of the `RC0` topic, we should review #2025.

**Comment by chainhead** [comment]
I am working on a feature request with the `v3.1.0-dev` branch. The `schemas` folder does not have a `v3.0` sub-folder. Which `.yaml` should I use to propose the specification change?

**Comment by handrews** [comment]
@chainhead hopefully you got this answered somewhere else, but there should be a `versions` directory with a `3.1.0.md` document in it on that branch.

Everything else here has been handled, so closing.
