### ISSUE TITLE
Swagger error : Structural error What should I modify?

### ISSUE THREAD

**Issue by serban123-beep** [OAI/OpenAPI-Specification#2030]
I am building an API documentation, I`m new to programming in general and this is the first time I work in Swagger.

This is my code:

    /stareMesaj:
    post:
    tags:
    - Metode disponibile
    summary: Stare mesaj
    description: Call de verificat stare mesaj. More soon.
    operationId: stareMesaj
    responses:
     '200':
      description: Ultimele 60 zile -  Nu aveti drept de interogare     stare pentru mesaj
      headers:
        X-Rate-Limit:
          description: calls per hour allowed by the user
          schema:
            type: integer
            format: int32
        X-Expires-After:
          $ref: '#/components/headers/ExpiresAfter'
        content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value: Hello world!
         application/xml:
          schema:
            type: string
          text/csv:
           schema:
            type: string

On the responses tag I get the following error:

    Structural error at paths./stareMesaj.post.responses
    should only have three-digit status codes, `default`, and vendor      extensions (`x-*`) as     properties
    Jump to line 395

I dontknow what to do. I googled the error but cant find it. What is the problem here ?

Thanks in advance

**Comment by MikeRalphson** [comment]
I think you need more indentation beneath the '200' tag, to make the following tags (eg description) properties of that object.

**Comment by MikeRalphson** [comment]
Closing as above, as hopefully resolved, and not an issue with the specification itself.
