### ISSUE TITLE
Usage at client?

### ISSUE THREAD

**Issue by goldingdamien** [OAI/OpenAPI-Specification#2032]
OpenAPI is generally used for server APIs.
However, can it be used for standardizing the API calls from the client(browser, etc.)?
If yes, are there any examples(preferably js). If no, what are the reasons? If there are any known alternatives, please state here.
My case is that I want to generate documentation for API calls from the client that can be shared with people developing the server API as some parts of development are ahead at the client while other parts are ahead at the server.

**Comment by MikeRalphson** [comment]
The OpenAPI Specification allows you to produce machine-readable documentation which describes an (HTTP) Application Programming **Interface**. It does not define or describe either the server or the client, but the common contract between the two.

The OpenAPI Specification doesn't mandate, recommend or provide any tooling or examples for the **implementation** of the server or client, this is outside its scope.

Your described use-case, however, seems already covered by much tooling which supports the specification.

Please feel free to chase this issue if I have misunderstood.
