### ISSUE TITLE
Add example before the specification

### ISSUE THREAD

**Issue by fulldecent** [OAI/OpenAPI-Specification#2034]
Regarding the OpenAPI homepage.

The specification goes directly into grammar and details. But nobody has shown me what the OpenAPI specification looks like. An example text file/device/robot/planet/other thing which complies with the specification should be shown as a specimen to explain what OpenAPI is.

**Comment by aghorpade** [comment]
@fulldecent  -  I guess you need to take a look at https://petstore.swagger.io/ to understand what OpenAPI specification looks like once you use them.

**Comment by fulldecent** [comment]
Proposed fix at https://github.com/OAI/OpenAPI-Specification/pull/2299

**Comment by lornajane** [comment]
I think we could signpost the (newer than this issue) resources at https://learn.openapis.org to support this request.

**Comment by handrews** [comment]
PR for the part of this warranting a spec change is merged for 3.0.4 and ported to 3.1.1 via PR #3921!
As noted above, the rest of this belongs with the Learn repo.
