### ISSUE TITLE
Is it possible to define request body as generated XSD class

### ISSUE THREAD

**Issue by cotnic** [OAI/OpenAPI-Specification#2035]
Is it possible to define a requestBody as a generated XSD class? Or is it possible to not specify properties for an object that will be accepted in the requestBody so it will can be seen as `HttpServletRequest` in generated code.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
