### ISSUE TITLE
OpenAPI TSC Meeting - October 24th, 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2041]
**NOTE: This meeting is on Thursday at 9am - 10am PT, 4pm-5pm UTC**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Publishing 3.1.0-RC0 | @OAI/tsc | |
| CSV-serialized form-data arrays #2018 | Mike |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
Action Items:
@philsturgeon  : Add wording to explicitly allow JSON Schema keywords from additional vocabularies and other additional keywords.

**Comment by handrews** [comment]
@darrelmiller @philsturgeon issue #2017 is about this, I've put it on several agendas and attached it to checklists and put it in the slack channel and have gotten zero acknowledgement much less any response.

Please carry it over to the next meeting issue (maybe I should just file one?).

**Comment by philsturgeon** [comment]
This is what the conversation was referencing. The #1977 needs updated text which resolved the situation. People are ok with letting arbitrary keywords in so long as we explain to tooling vendors that they should ignore unknown words.

**Comment by handrews** [comment]
@philsturgeon let's merge #1977 and deal with this separately, unless you're absolutely certain that it's a one-liner.  I dislike letting a bunch of stuff keep stacking up.
