### ISSUE TITLE
OpenAPI TSC Meeting - October 31st, 2019

### ISSUE THREAD

**Issue by philsturgeon** [OAI/OpenAPI-Specification#2047]
_Sorry if stepping on any toes @darrelmiller but wanted to get this one started. Yes, I have a vested interest in all of the below._

**Agenda**

- Nullable Clarification in v3.0.3 - https://github.com/OAI/OpenAPI-Specification/pull/2046
- Callback Example Improvement for v3.0.3 - https://github.com/OAI/OpenAPI-Specification/pull/2048
- JSON Schema 2019-09 in v3.1.0 - https://github.com/OAI/OpenAPI-Specification/pull/1977
- Parameter examples do what now v3.0.3 - https://github.com/OAI/OpenAPI-Specification/pull/2042
- Webhooks Proposal, how to progress? @lornajane 
- v3.1.0-RC1

**Comment by tbarn** [comment]
Make sure to add these to these issues: 

NOTE: This meeting is on Thursday at 9am - 10am PT
Zoom Meeting link: https://zoom.us/j/975841675
