### ISSUE TITLE
Schema property alternative names

### ISSUE THREAD

**Issue by netbeansuser2019** [OAI/OpenAPI-Specification#2055]
I would like to suggest to extend schema property by "alternativeName":

```yaml
"type" : "object",
"properties : {
     "property1" : {
            "type" : "string",
            "alternativeNames" : [
                  "Property1"                   
            ]
     }
}
```

That to me seems advantage in case of generation clients for 3rd-party-API that it is even not describe by openapi.json especially to reuse "objects type" that just differentiated in case of letters in properties.

**Comment by webron** [comment]
How would this help client generation though?

**Comment by netbeansuser2019** [comment]
In context of Java client that call returns JSON you can have just one object field that could eat any variant of property name. That can happens e.g. when service is not developed with taking to acccount openapi specifcation and/or is some development history instead of creation different schema for one group of calls (e.g. old style) and other (new style).
...

As another example see: https://github.com/swagger-api/swagger-codegen/issues/9858

**Comment by handrews** [comment]
This has been floated at the JSON Schema project as a sort of schema evolution feature.  We're unlikely to act on it but it could be done in an extension vocabulary.

**Comment by netbeansuser2019** [comment]
> This has been floated at the JSON Schema project as a sort of schema evolution feature.  We're unlikely to act on it but it could be done in an extension vocabulary.

In ideal world yes, but you have to have possibility to describe it even that third-party-no-so-ready or even you have to connect to old thing that it is not even expect to be even touched (rather died after years). Or side of this problem is code convention or even worst limits about variables naming on client side. Could you more explain what you mean by such "extension vocabulary" or even better write down some example.

**Comment by bougar** [comment]
This would make sense in case I wanted to rename a property name without breaking compatibility with previous versions.
The behavior, at least in my use case, would be similar to [JsonAlias](https://www.logicbig.com/tutorials/misc/jackson/json-alias-annotation.html) in Java.

**Comment by Loicgeo-pro** [comment]
Hi all, I have a need also to digest a JSON having some strange names as input and I don't have the hand to change its specification.

**Comment by mehmeteyesin** [comment]
@bougar were you able to find a workaround?

**Comment by jkoorts** [comment]
Here eagerly hoping this feature is now supported

**Comment by handrews** [comment]
You would need to handle the alternative names at the same level as the regular names, because keywords for a single property cannot be applied to the whole object (which would be needed to find the alternate name).  The `property1` schema won't even be examined if there isn't a `property1`, so the proposed approach won't work.

The simplest way to do this is to just ref both property names to the same definition, which can include a canonical name for code generators to use (I'm making up the `canonicalName` keyword on the spot- as an annotation, it's trivial to implement as an extension vocabulary for OAS 3.1 / JSON Schema 2020-12 because in 2020-12 unknown keywords are automatically treated as annotations):

```JSON
{
    "$defs": {
        "property1": {
            "type": "string",
            "canonicalName": "property1"
        }
    },
    "type" : "object",
    "properties": {
        "property1": {"$ref": "#/$defs/property1"},
        "Property1": {"$ref": "#/$defs/property1"}
    }
}
```

**Comment by Noyabronok** [comment]
Based on the last post, I was able to get the behavior I needed (curly brackets do the trick!). Thanks!
```
components:
  schemas: 
    property1: 
      type: string
    Property2: { $ref: "#/components/schemas/property1" }
```

**Comment by handrews** [comment]
OAS 3.1 has full JSON Schema support, and this is really a JSON Schema feature request.  Now that the OAS doesn't define a custom JSON Schema variant, this is out of scope for us.
