### ISSUE TITLE
Support unit of measurement 

### ISSUE THREAD

**Issue by HunorMarton** [OAI/OpenAPI-Specification#2061]
I would love to see a possibility to add unit of measurement for data type definition. Something like this:
```
speed: {
  type: 'number',
  default: 0,
  unit: 'km/h'
}
```

**Comment by neluzhin** [comment]
Use `description` field for that or custom fields (`x-*`) in your specification viewer. This is overhead and I don't see any use cases except visualization.

**Comment by sm-Fifteen** [comment]
I would argue that there are interesting use cases specifying units besides simply visualization by humans, such as unit uniformization or verifying that the input units are compatible with a formula, possibly. Specifying the units as arbitrary strings wouldn't be very helpful, but the CLDR unit format which covers [most of the base units](https://github.com/unicode-org/cldr/blob/main/common/supplemental/units.xml) in NIST SP811. ECMA-402 also now defines [a subset of these units](https://402.ecma-international.org/8.0/#sec-issanctionedsimpleunitidentifier) to use for number formatting (which browsers expose as `Intl.NumberFormat`), which can be used to a limited degree for unit conversion. That format is also composable, such that something like `gigalux-per-100-ounce-troy` is a valid unit identifier.

```js
let amount = 3500;
let formatter = new Intl.NumberFormat('en-US', {style: 'unit', unit: 'liter-per-kilobit'});
formatter.format(amount); // 3,500 L/kb
```

That could be an interesting way to specify number units in an API, even though the tooling for this is currently limited.

**Comment by silverwind** [comment]
This concerns JSON Schema, not OpenAPI. See https://github.com/json-schema-org/json-schema-vocabularies/issues/46 for discussion.

**Comment by sm-Fifteen** [comment]
@silverwind: Now that OpenAPI 3.1 is out and in sync with JSON Schema, you're probably right.
