### ISSUE TITLE
Open TSC Meeting - November 21st, 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2062]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| OpenAPI 3.0 does not support csv-serialized form-data arrays | MikeK | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
Action Items:

Mike Kistler will create PR to allow style,explode and allowreserved to impact multipart/form-data content as was possible in V2.
Ted will create/update PR for changing the definition of nullable based on his proposal.
Darrel will move proposals into a new repo.

Once the PRs are created we would like to get TSC approval offline as we will be missing the TSC meeting next week.

**Comment by handrews** [comment]
I think all of the action items in this issue are now done.
