### ISSUE TITLE
Swagger 2.0: Reusable Enums feature for additional value in enum

### ISSUE THREAD

**Issue by JMARK0** [OAI/OpenAPI-Specification#2067]
I have  requirement  I need use enums  for few fields  which repeats in other fields too in swagger 2.0   i tried  using anchor  concept in YAML to avoid  repeating enums  but as new requirement we had only 2 or 3 enum value to added other  fields , which  forced me define it separately.

My Swagger sample:

```
swagger: '2.0'

paths:
  /test:
    get:
        parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Colours'
       responses:
       
definitions:
  Color:
    type: string
    enum: &COLOR
      - red
      - blue
      - yellow
       - pink
  Color1:
    type: string
    enum: &COLOR
      - red
      - blue
      - yellow
      - pink
      -green
  Colours:
    type: object
  properties:
      color:
        type: string
        enum: *COLOR
      colorUpdate:
        type: string
        enum: *COLOR1
```

**NOTE: this  is sample not my actual swagger** 

If you  note  the difference between  color and color1 is just one  color   green  other enum value are similar ,similar this  i  too have  requirement where i have  100  enum  under one field and 101 or 102 enums values in another  field 

Thanks in  Advance!!

**Comment by MikeRalphson** [comment]
No new work is on-going on OpenAPI (fka Swagger) 2.0. Please consider upgrading to 3.x if you can.

**Comment by JMARK0** [comment]
Thanks  Mr. Mike for quick  response!!

Do we have  any  option  in OpenAPI 3 to  resolve above requirement
