### ISSUE TITLE
TSC Open meeting - December 5th, 2019

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2072]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  

/cc @OAI/tdc Please suggest items for inclusion

**Comment by akuckartz** [comment]
2014 ?

**Comment by ncaidin** [comment]
I would like to talk about turning on DCO.

**Comment by darrelmiller** [comment]
@akuckartz  Not sure what happened there :-)

**Comment by darrelmiller** [comment]
Steps so far:
- Fixed versioning wording
- Changed nullable behavior to prevent breaking change in 3.1
Steps to 3.1:
- Ron to ensure no more changes need to enable JSON Schema draft 2019/09 support
- TSC Vote: 3.0.3
- Publish 3.0.3
- See Smaller List of Actualities
   - Talk to people at APIDays about the notion of Scopes for non-OAuth2 schemes.
- Find acceptable Overlay solution before end of January.
- TSC vote
- Publish 3.1 RC before end of February

**Comment by philsturgeon** [comment]
> Publish 3.1 RC before end of February

Didn't we commit to 30 days about two months ago? This is a long time away.

**Comment by darrelmiller** [comment]
Yup, but that was without Overlays.  We will discuss Overlays at ApiDays Paris and decide if that needs to be in 3.1  If it is decided that Overlays can be done as a separate spec, then maybe we don't need to hold up 3.1 for that.
