### ISSUE TITLE
How to serialize query object with custom delimeter

### ISSUE THREAD

**Issue by Mazas17** [OAI/OpenAPI-Specification#2075]
I have yaml file:

```
openapi: 3.0.1
info:
  title: My API
  version: v1
paths:
  # /users;id=3;id=4?metadata=true
  /users:
    get:
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of items to return
        - in: query
          name: origin
          style: form
          explode: false
          schema:
            type: object
            properties:
              city:
                type: string
              zip:
                type: string
      responses:
        '200':
          description: A list of users
```
When I click "execute", the generated Curl looks like this:
`curl -X GET "https://editor.swagger.io/users?offset=2&limit=12&origin=city,atlanta,zip,303" -H "accept: */*"`
However, I need it to be like this:
`curl -X GET "https://editor.swagger.io/users?offset=2&limit=12&origin=city:atlanta|zip:303" -H "accept: */*"`

Is it possible to do this? I could not find any info in documentation about setting custom delimeters.

**Comment by MikeRalphson** [comment]
As you demonstrate, the `style` field is a property of the `parameter` object, and it is this which along with `explode` which controls the parameter serialisation.

So you could achieve various combinations of separators as listed [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#style-examples) but there is no way to attach custom delimiters to the keys and values or to each individual property (this would be ambiguous with regard to optional object properties).
