### ISSUE TITLE
Define encoding type for multipart/form-data file upload is not possible according to the 3.0 Specification

### ISSUE THREAD

**Issue by sameena-s** [OAI/OpenAPI-Specification#2076]
According to the "https://swagger.io/docs/specification/describing-request-body/multipart-requests/", there's a possibility to define the content type to the multipart/form-data body part.
<img width="607" alt="Capture2" src="https://user-images.githubusercontent.com/58764192/70598216-576c6f00-1c10-11ea-9384-7a1aa4c8a2e6.PNG">

I tried with different jaxrs annotations, but can't able to generate the YAML in the expected format.
Here's my sample code:
<img width="770" alt="code" src="https://user-images.githubusercontent.com/58764192/70605849-46782980-1c21-11ea-8cc5-d3dfd0f903fd.PNG">

And the following is the generated YAML for the above code:
<img width="390" alt="Actual" src="https://user-images.githubusercontent.com/58764192/70605868-5132be80-1c21-11ea-9663-2c78eba32ac7.PNG">

But I would like to generate the YAML in the following format.
<img width="392" alt="Expected" src="https://user-images.githubusercontent.com/58764192/70606079-c56d6200-1c21-11ea-8d23-87bf9d0e41aa.PNG">

Tried in many different ways. The following file contains all the samples.
[IOpenApiRestService.txt](https://github.com/OAI/OpenAPI-Specification/files/3949173/IOpenApiRestService.txt)

Can someone please explain what annotations have to use exactly to generate the YAML in the expected format?

Thanks in adavance.

**Comment by sameena-s** [comment]
I tried in different ways. Attach file contains all samples.
[IOpenApiRestService.txt](https://github.com/OAI/OpenAPI-Specification/files/3949167/IOpenApiRestService.txt)

**Comment by webron** [comment]
This is a tooling issue and not a spec one. Please file the question at the respective tool you're using.

**Comment by sameena-s** [comment]
In our project we are using following maven dependencies.
<img width="338" alt="MavenDependencies" src="https://user-images.githubusercontent.com/58764192/71060470-9314b500-218b-11ea-924b-824cc6d5712d.PNG">


Does it mean to create the issue in https://github.com/swagger-api/swagger-core/issues?

**Comment by webron** [comment]
Yup, and I see you've filled a ticket there. Thanks.

**Comment by sameena-s** [comment]
Created issue in swagger core https://github.com/swagger-api/swagger-core/issues/3387
