### ISSUE TITLE
Open TSC Meeting, December 19th, 2019

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#2078]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
|Webhooks Proposal | @lornajane | |
|JSON Schema support update | @philsturgeon | |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by lornajane** [comment]
I don't have edit rights on issues but I'd like to add the [Webhooks proposal](https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/002_Webhooks.md] to the agenda. The Decision is whether it can merge or if not, the NextStep is to identify what the blockers are for this proposal to be merged. I'd like to move forward especially as we see more tools adopting the standard.

**Comment by earth2marsh** [comment]
With the next two holiday weeks, we should also clarify when the next meeting will be... guessing Jan 9?

**Comment by handrews** [comment]
How about a roll call- who is actually available to be on this call?  It would be good to avoid another failed quorum.

I am available.  Sounds like @lornajane is.

**Comment by philsturgeon** [comment]
@handrews 👋

**Comment by philsturgeon** [comment]
Let's talk about https://github.com/OAI/OpenAPI-Specification/pull/1977

**Comment by darrelmiller** [comment]
Action: Extend current PR for making paths optional to create a collection of Path Item Objects in components. [Ron/Mike]
Action: Update Webhooks proposal to allow a reference to a path item object instead of just an inline Path Item Object  [Lorna]
Action: Review possible conflict between key of callback object and webhook object [Darrel]

**Comment by earth2marsh** [comment]
Confirmed: 2019.12.19 was the last TSC meeting of the year. 
The next meeting will be on January 9th, 2020.

**Comment by handrews** [comment]
I have to apologize, folks- after making a big deal about committing to show up I forgot to set an alarm and slept through it 😅 😬

**Comment by Relequestual** [comment]
I should make an effort to try and make these now.
I can probably usually make the first half hour if my timezone shifting calculations are correct!
Is there an event invite I can be added to? =]

**Comment by webron** [comment]
@Relequestual - you can the meeting using the link available in https://github.com/OAI/OpenAPI-Specification#participation.
