### ISSUE TITLE
Should Path Template replaceable sections be required in parameters section?

### ISSUE THREAD

**Issue by jcoyne** [OAI/OpenAPI-Specification#2079]
The spec does not say that replaceable sections in a path template must be in the parameters section (or at least I'm not seeing it).  Some clarifying text would be helpful.

When I use  this document:
```
openapi: 3.0.0
info:
  title: Sample
  version: v1
paths:
  "/pets/{id}":
    get:
      responses:
        200:
          description: "OK"
```

and put it in http://editor.swagger.io/

I get this error:

```
Semantic error at paths./pets/{id}
Declared path parameter "id" needs to be defined as a path parameter at either the path or operation level
Jump to line 6
```

It seems either the spec is missing this requirement or the editor is imposing requirements that are not in spec.

**Comment by MikeRalphson** [comment]
Related discussions in #1830 and PR #1831

**Comment by webron** [comment]
As #1831 is merged, it should now be clearer that indeed it's required.
