### ISSUE TITLE
Swagger.next: Let's not use hashes anymore 

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#208]
Putting `paths` and `operations` in a hash made all sort of problems. The biggest problem is keeping order status of paths and operations. Tags can help organize the paths and operations but that's not enough. Most of people expect Swagger document keep it's order status when they are authoring one. 
Other problem with using hashes is that we are using keys as a data storage. This makes it impossible to have other keys in `paths` or `operation` because every key is a path or operation. 

Lets use arrays for the next version and make life easier for everyone. It will not make specs uglier. Here is an example:

```yaml
# Example YAML for the bare minimum of required elements
# See petstore.yaml for a more comprehensive example
swagger: '3.0'
info:
  version: "1.0.0"
  title: petstore
paths:
  - 
    path: /pets # maybe path can have multiple endpoints like `path: [ "/pets", "/animals"]
    consumes:  # path level consumes 
      - "text/html"
    operations:
      - method: get # maybe we can define a batch of operations in one operation i.e. `methods: [ "post", "head"]
        responses:
          - 
            code: "200" # ability to have responses defined by code OR other means (solving response overloading issue)
            description:  Describe the 200 response in more detail

```

**Comment by fehguy** [comment]
Reference #560

**Comment by fehguy** [comment]
@OAI/tdc propose closing this with no action, please approve / reject

**Comment by webron** [comment]
Voting to close.

**Comment by DavidBiesack** [comment]
I see this as tied to #146 for which arrays instead of maps (hashes) was proposed.
is there a solution for #146 that does not change the paths map to an array?

**Comment by ePaul** [comment]
@DavidBiesack for #146 I would prefer not to repeat the same path twice, but have the consumes/produces distinction under the operation level.
