### ISSUE TITLE
Examples table with wrong table cell content

### ISSUE THREAD

**Issue by hrennau** [OAI/OpenAPI-Specification#2087]
In the OpenAPI spec, section "Link Object", 
   https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#linkObject

the "Examples" table following after the text
   "The table below provides examples of runtime expressions and examples of their use in a value:"

in the second row, first column ("Source Location"), the text is
    "Requested media type"

but I think it should be:
    "Request header"

**Comment by lornajane** [comment]
Thanks for opening this issue! I've taken a look at the section you pointed out and I think we should leave it as it is. The example indicates the Accept header and I think it is clear enough.
