### ISSUE TITLE
To Allow specify (at least) description in response definition when $ref is used

### ISSUE THREAD

**Issue by ratermir** [OAI/OpenAPI-Specification#2089]
It would be very useful to be able to add (at least) description to the $ref in case of (at least) response part of the API specification.

It would allow me to specify generic reusable response that could be refined for every concrete use case. Because there are a lot of cases of responses that have the same structure, only the difference is the information why / when the error occurred.

Oxample of the use case:
![image](https://user-images.githubusercontent.com/52619304/71994469-141a1600-3239-11ea-9e06-d1e8effdd847.png)

In more generic perspective, it could be useful to allow to "override" some parts of references (examples, parameters ...).

**Comment by handrews** [comment]
For Schema Objects, this is addressed by PR #1977 for OAS 3.1

I'm not sure what the plan is for `$ref` outside of Schema Objects.

**Comment by handrews** [comment]
This should probably be tracked in #2099.  While not technically a JSON Schema issue, it is an example of the sort of question that will come up once JSON Schema keywords are allowed adjacent to `$ref` in OAS 3.1.

**Comment by ratermir** [comment]
Originally I posted [this request](https://github.com/swagger-api/swagger-editor/issues/2084) to the swagger editor group, but they redirected me here - they can't make such changes to this tool (= editor) if the schema says things different. That's why I posted it also here.

**Comment by handrews** [comment]
@ratermir yes, this is the correct repo.

@whitlockjc @webron more `$ref` fun that we should track for OAS 3.1.  I think it falls under things we're already talking about.

**Comment by MikeRalphson** [comment]
PR: #2181
