### ISSUE TITLE
How to customize the page title of swagger page

### ISSUE THREAD

**Issue by anksngp** [OAI/OpenAPI-Specification#2091]
Hi,

While using swagger 2 wih spring boot, we used to put @Configuration
@EnableSwagger2 annotation on top of a class with 
@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).directModelSubstitute(ZonedDateTime.class, String.class).select()
				.apis(RequestHandlerSelectors.basePackage("com.test")).paths(PathSelectors.any()).build()
				.enable(environmentProperties.isEnableSwagger());
	}

But the same way is not working with swageger 3 , i still get the same default tile as 

OpenAPI definition
 v0 
OAS3
/v3/api-docs

How can i customise this page title?

**Comment by webron** [comment]
This is the repository of the spec itself. Please file the ticket at Springfox.
