### ISSUE TITLE
Enumeration of data model properties

### ISSUE THREAD

**Issue by gbisaga** [OAI/OpenAPI-Specification#21]
I have a case where I have an enumeration that can return different String values. The @ApiModelProperty's allowableValues is close, but I need to have metadata associated with each possible value. Something like this:

@ApiModelProperty(...., allowableValues={
  @ApiModelPropertyValue( value="registered", description="Yada yada...", discriminator="PUT" ),
  @ApiModelPropertyValue( value="active", description="Yada yada...", discriminator="PUT,POST" ),
  @ApiModelPropertyValue( value="closed", description="Yada yada...", discriminator="POST" )
});

It seems like any time there is a value, you'd need to at least describe the possible values.

**Comment by webron** [comment]
Closing in favor of #348.
