### ISSUE TITLE
Open TSC Meeting - Feb 6th 2020

### ISSUE THREAD

**Issue by philsturgeon** [OAI/OpenAPI-Specification#2125]
Zoom link: https://zoom.us/j/975841675

**Agenda** 

What | Who | Where
------|-----|--------
Nullable clarifications from v3.0.3 missed in #1977 | @tedepstein | https://github.com/OAI/OpenAPI-Specification/pull/2115
patternProperties for v3.0 meta schema is confusing? | @handrews  | https://github.com/OAI/OpenAPI-Specification/pull/2127
allow, but discourage, requestBody for GET, HEAD, DELETE but for v3.1.0? | @philsturgeon  |  https://github.com/OAI/OpenAPI-Specification/pull/2117
$ref updates | @handrews  |  https://github.com/OAI/OpenAPI-Specification/pull/2107

**Comment by stevendearborn** [comment]
Is there a meeting link for this?

**Comment by handrews** [comment]
@stevendearborn I think it's the same every week https://zoom.us/j/975841675

**Comment by darrelmiller** [comment]
Action: Ron is going to prep 3.0.3 release.
Action: Mike is going to check for approved PRs against 3.0.3
