### ISSUE TITLE
[Release] v3.0.3 preparation checklist

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2130]
@webron Please edit with any tasks you need to document here.

### Stale/Open [PRs against **v3.0.2-dev** ](https://github.com/OAI/OpenAPI-Specification/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Av3.0.2-dev) to be reviewed

| Title | Link | Who | Approved | Next action? |
|---|---|---|---|---|
| Clarify spec wrt readOnly and writeOnly in referenced schemas  | #1638 | @tedepstein  | | https://github.com/OAI/OpenAPI-Specification/pull/1638#issuecomment-583354398 @MikeRalphson to forward port only the xmlObject change to 3.1 |

### Open [PRs against **v3.0.3-dev**](https://github.com/OAI/OpenAPI-Specification/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Av3.0.3-dev) to be reviewed

Bear in mind I think we should try to get some of these in if possible, because we will be asking the OP to do additional work if we have to postpone them (i.e. the PR will need retargetting at both a new base branch and file).

| Title | Link | Who | Approved | Next action? |
|---|---|---|---|--|
Explain unclear semantics of property `$ref` in Path Item Object | #1964 | @cebe | Changes requested | @oai/tsc member with longest memory to weigh in and provide guidance to @cebe / @tedepstein 
Clarify the spec to allow optional or unspecified OAuth scopes | ~~#1888~~ | @tedepstein | Changes requested | My thought is that we could cover this in a FAQ or technical note outside the spec. Required Maps/Arrays can always be empty unless we specify otherwise.
Clarify empty Security Requirement Object usage and validity | ~~#1886~~ | @tiangolo | Modified and merged | LGTM just a quibble about changing the existing examples
Clarify constraints on Security Scheme Object Scheme Property | ~~#1880~~ | @darrelmiller | Approved and merged | LGTM but @darrelmiller is this still WIP?
fix a typo in the Security Filtering section | ~~#1837~~ | @seiyab | Modified and merged | @MikeRalphson added suggested change
Path Templating Clarification - proposed fix for #1830 | ~~#1831~~ | @tedepstein | Changes requested | Semver issue. @tedepstein could we go for SHOULD rather than MUST?
Server Variable Object clarifications | ~~#1809~~ | @webron | Approved and merged | @webron to reword or re-target?
minor clarification for operationId usage in link objects | ~~#1733~~ | @dret | Modified and merged | The PR description is a little confusing but the change itself LGTM. @darrelmiller can you confirm ok?
Clarified supported Ecma edition for regex | ~~#1725~~ | @dvh | Approved and merged | @MikeRalphson resolved conflict. @earth2marsh are you happy with Ecma capitalisation?

### Other activities

* @webron to manage the release
* @MikeRalphson generate ReSpec version for 3.0.3 - the cleanest way to automate this may now be a GitHub action to auto-raise a PR against the `gh-pages` branch. Thoughts on moving away from Travis-CI entirely? Should we make relative links to examples absolute or copy examples to `gh-pages` / openapis.org? Actions agreed TSC call 2020/02/13
@MikeRalphson to inform @ncaidin to update the "Latest" link on openapis.org

cc @OAI/tsc

**Comment by darrelmiller** [comment]
@OAI/tsc passed by majority the release of 3.0.3 patch update to the OpenAPI Specification

**Comment by webron** [comment]
@MikeRalphson 3.0.3 has been merged into master and master has been tagged.

**Comment by MikeRalphson** [comment]
Post-release activities have been completed.
