### ISSUE TITLE
Json schema 3.0 is missing in 3.0.X release assets

### ISSUE THREAD

**Issue by yanavasileva** [OAI/OpenAPI-Specification#2133]
Hi,

I noticed that `v3.0` directory is missing under `OpenAPI-Specification-3.0.2\schemas\` in the released assets (e.g. https://github.com/OAI/OpenAPI-Specification/archive/3.0.2.zip), only the older versions are there - `v1.2` and `v2.0`. Is it on purpose?

Best regards,
Yana

**Comment by MikeRalphson** [comment]
The schema was not finalised when v3.0.2 was released. This should be addressed in the upcoming release of v3.0.3

**Comment by yanavasileva** [comment]
Great, thank you for your prompt reply.
