### ISSUE TITLE
Question - Official Json Schema support

### ISSUE THREAD

**Issue by B-Teague** [OAI/OpenAPI-Specification#2136]
Why is OpenAPI not supporting full JSON schema specifications (reinventing the wheel)?  Why not just have components link to an external JSON schema file that can be used by JSON validation libraries based on the official JSON schema specifications. (Or just support the json schemas inline to provide consumers a single file using the existing JSON specifications)

**Comment by webron** [comment]
Actually, OpenAPI 3.1.0 (not released yet), already supports full JSON Schema. No wheel is being reinvented anymore.
