### ISSUE TITLE
how to specify minimum for a date

### ISSUE THREAD

**Issue by lxzhu** [OAI/OpenAPI-Specification#2138]
I have a schema, which has a property of type date time. it is type string and format date-time in openapi. That is no problem. However, when i specify a minimum for it. Tools like SwaggerEditor reports error:  should be number

here is an example:
membershipStartDate:
          type: string
          format: date-time
          title: membershipStartDate
          minimum: '1900-01-01T12:00:00'
          description: ''
          example: '2020-02-14T17:34:37.6675908+01:00'

After google, i can not find openapi example of minimum for date time. Is it supported?

**Comment by handrews** [comment]
@lxzhu the JSON Schema `minimum` keyword only applies to numbers, so its value must be a number.

There is currently no standard way to set date-time minimums, and that won't change in OAS 3.1 (the next version).  Given that there are many problems with the `format` keyword (most notably that it's completely unreliable as to whether validators validate it), we will hopefully move to better solutions in this area post-OAS 3.1, but it's not a quick fix.

**Comment by handrews** [comment]
Also, that work on `format` improvement / replacement will happen in the JSON Schema Specification repository, and then get picked up in a future OpenAPI release, as this is more of a JSON Schema issue than an OpenAPI issue.
