### ISSUE TITLE
Open TSC meeting, Thursday February 20th

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2144]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| v3.0.3 release / post-release actions #2130  | @webron  | |
| What [fields](https://gist.github.com/MikeRalphson/d3b6bdbc3c4a9f2e69310a356824e174) can be siblings of `$ref` | @MikeRalphson | PR #2181 |

/cc @OAI/tdc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
$ref siblings plan:

RC0
Summary and Description are a GO!!!!!   They override equivalent in $ref'd object.

RCn?
Required and deprecated are a maybe, maybe not. 
examples - Henry says yes. Mike(R|K) are for! Ron is a maybe.
x-  ????

**Comment by MikeRalphson** [comment]
Would someone like to take on the ref siblings PR, then I can concentrate on forward porting the 3.0.x changes into 3.1 for RC0
