### ISSUE TITLE
Swagger Schema 2.0  ApiKey

### ISSUE THREAD

**Issue by lidonis** [OAI/OpenAPI-Specification#215]
I just read  schema.json for swagger v2.0 after trying swagger editor.

I have a problem with apiKeySecurity because there is only  "header" and "query" but no "path" param.

I need to put my apiKey as path param. How can i do that ?

**Comment by webron** [comment]
Parent: #585.

**Comment by LasneF** [comment]
@webron, @MikeRalphson   

looks very corner case, not seeing any API Management tooling doing like that 

should the issue be closed to narrow down the feature list ?  as not retains for OAS 3.0 neither 3.1  ?

**Comment by handrews** [comment]
2.0 is long past the point of patch releases, and the use case seems too small to track given the lack of engagement in the past 8 years.  If there is a clear use case with enough support, this is probably best considered under Moonwalk and re-opened there.
