### ISSUE TITLE
Schema Object and JJSON Schema Specification Wright Draft 00.

### ISSUE THREAD

**Issue by blendsdk** [OAI/OpenAPI-Specification#2155]
Hi,

Is the Schema Object still based on JSON Schema Specification Wright Draft 00?
It looks like that Wright Draft 00 is very outdated.

Please advise.

**Comment by MikeRalphson** [comment]
Draft Wright 00 was current when OAS 3.0.0 was published. OAS 3.1 will be based on JSON Schema Draft 2019-09 or a likely Draft 2020-03/04. See https://github.com/OAI/OpenAPI-Specification/blob/v3.1.0-dev/versions/3.1.0.md#schema-object
