### ISSUE TITLE
OAS 3 JSON schema is invalid. Encoding object only allows headers to be Header objects and not Reference objects.

### ISSUE THREAD

**Issue by alasdairhurst** [OAI/OpenAPI-Specification#2157]
https://github.com/OAI/OpenAPI-Specification/blob/9218ce60424b03794411a8c6d0454c1c6d31aba0/schemas/v3.0/schema.json#L1631

This causes OAS 3 documents that are valid against the spec to fail. (and breaks tooling that relies on the schema for validation)

Here's an example encoding object which fails validation:

```yaml
          encoding:
            url:
              headers:
                id:
                  $ref: '#/components/headers/id'
```

The schema should be 

```json
          "additionalProperties": {
                "oneOf": [
                    {  "$ref": "#/definitions/Header" },
                    {  "$ref": "#/definitions/Reference" },
                ]
               
          }
```

I'll submit a PR with this change for you.

**Comment by alasdairhurst** [comment]
https://github.com/OAI/OpenAPI-Specification/pull/2158

**Comment by MikeRalphson** [comment]
Closing as #2158 was merged. Thanks all.
