### ISSUE TITLE
[4.0 Scope] Make readOnly and writeOnly fully aligned with JSON Schema

### ISSUE THREAD

**Issue by tedepstein** [OAI/OpenAPI-Specification#2169]
This is a placeholder for a follow-up task to consider in the next major release cycle. 

In #1622, we discussed the new definition of `readOnly` and `writeOnly` annotations in JSON Schema. OpenAPI 3.1 cannot simply defer to this definition, because it has different semantics that would amount to a breaking change. But we should consider making this change in 4.0.

**Comment by handrews** [comment]
wait, does that mean that @OAI/tsc has decided to make these incompatible with JSON Schema in OAS 3.1?

**Comment by tedepstein** [comment]
@handrews, OpenAPI 3.0 specifies that a `required` property that is also `readOnly` or `writeOnly` becomes required in one direction, but not the other. This is not expressible in JSON Schema. In #1622, I explained that I'd like to change OpenAPI to remove this incompatible behavior, but it's a breaking change, so I don't think we can do it in 3.1. 

So yes, OAS 3.x is incompatible in this one case because it assumes context-sensitive validation, which JSON Schema doesn't support. 

In [this comment](https://github.com/OAI/OpenAPI-Specification/issues/1622#issuecomment-591962328), I described three possible workarounds, assuming we don't magically solve this JSON Schema compatibility issue in 3.1. In [this comment](https://github.com/OAI/OpenAPI-Specification/issues/1622#issuecomment-592056342), @MikeRalphson says we should publish those workarounds somewhere, and (presumably) accept that we can't fix it in 3.1.

If other TSC members want to weigh in, or if anyone has a better idea of how to handle this, please chime in.

**Comment by handrews** [comment]
@tedepstein that is not how I interpreted @MikeRalphson's comment.  I will follow up over there.

**Comment by MikeRalphson** [comment]
Believe this can be closed, as resolved for 3.1
