### ISSUE TITLE
Diagramming specification using mind map

### ISSUE THREAD

**Issue by starjasmine** [OAI/OpenAPI-Specification#2174]
I worked on depicting OAS v3.0.2 using [mind meister](https://www.mindmeister.com/folders).
And, after finishing my [draft version of this work](https://www.mindmeister.com/1434608454/openapi-obj), I found that this could be useful for you and other users.

It's easy to trace and easy to associate related objects.

I propose to have this work go together with the official documentation works.

**Comment by MikeRalphson** [comment]
See also http://openapi-map.apihandyman.io/

**Comment by starjasmine** [comment]
@MikeRalphson Thanks, Mike.  I admit that handyman's job is briefer.  I should've asked here about whether earlier works exist. Who would compensate my time today 😭😭😭
