### ISSUE TITLE
Cannot specify content type parameters

### ISSUE THREAD

**Issue by michael-o** [OAI/OpenAPI-Specification#2177]
I am either blind or this is completely missing.

I am currently designing an API atop of `multipart/related` according to RFC 2387. After describing `requestBody/content/"multipart/related"` I see no way to describe the related parameters like `start`, `type`, etc.

Please add support to add arbitrary content type parameters for headers and well as the request body.

**Comment by handrews** [comment]
@michael-o to you need to be able to define a schema (set of acceptable values) for the content-type parameters, or just specify the parameter values?  e.g.

`requestBody/content/"multipart/related type=application/json"`

(I have no idea if this works with any tooling, I'm just brainstorming here)

**Comment by michael-o** [comment]
The former actually. This is how it looks with extensions:

```yaml
  /api/v1/jobs:
    post:
      tags:
        - Jobs
      summary: Schedules a new module job
      operationId: scheduleJob
      requestBody:
        required: true
        description: |
          A module job contains all necessary information about a module and its input to complete
          a calculation successfully. A minimal, but complete module job must be structured as
          specified by RFC 2387.
        content:
          multipart/related:
            x-parameters:
              start:
                $ref: "#/components/x-headerParameters/start"
              type:
                $ref: "#/components/x-headerParameters/type"
```

and 

```yaml
components
  x-headerParameters:
    start:
      required: false
      description: |
        Denotes the root body part of a multipart message via its content ID. If not provided the
        first body part is assumed to be the root.
      schema:
        $ref: "#/components/schemas/contentId"
    type:
      required: true
      description: The content type of the root body part.
      schema:
        type: string
        format: content-type
```

I hope you get the idea now. I don't see a difference to a request parameter, specificationwise.

**Comment by handrews** [comment]
@michael-o yup, thanks.  Was just curious as to the level of flexibility needed.  In JSON Hyper-Schema (which is not a practical alternative, just an example) we solved this by referencing a proposal on mapping HTTP headers into JSON and applying JSON Schema to them.

**Comment by handrews** [comment]
It turns out that we have an issue filed requesting this

* #2342 

I'm going to close this one in favor of that one which has more discussion.
