### ISSUE TITLE
externalValue type is missing MUST be URL language

### ISSUE THREAD

**Issue by michael-o** [OAI/OpenAPI-Specification#2179]
[Example Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#example-object) defines that `externalValue` shall contain a URL, but defines string as type. With that kind of definition it is not subject to relative URL resolution against a server object.

Please reconsider the type or clarify.

**Comment by MikeRalphson** [comment]
All url fields in the OAS are defined as type 'string', including the `server` object `url` property itself. Why do you think the `example` object `externalValue` is not subject to

> Unless specified otherwise, all properties that are URLs MAY be relative references as defined by RFC3986. Relative references are resolved using the URLs defined in the Server Object as a Base URI.

is it because the wording "MUST be in the format of a URL." is not present?

**Comment by michael-o** [comment]
> 
> 
> All url fields in the OAS are defined as type 'string', including the `server` object `url` property itself. Why do you think the `example` object `externalValue` is not subject to
> 
> > Unless specified otherwise, all properties that are URLs MAY be relative references as defined by RFC3986. Relative references are resolved using the URLs defined in the Server Object as a Base URI.
> 
> is it because the wording "MUST be in the format of a URL." is not present?

Thank you, for pointing out. It is somewhat a misread from my side, but you brougt up a valid point:

* Documentation could be better on these properties
* All examples depict fully qualified URLs, none of them are relative. This gives the impression that only absolute URLs are valid unless you spot the proper section referencing RFC 3986.

**Comment by MikeRalphson** [comment]
> All examples depict fully qualified URLs, none of them are relative. This gives the impression that only absolute URLs are valid

Examples are non-normative, and cannot be exhaustive.

**Comment by michael-o** [comment]
> 
> 
> > All examples depict fully qualified URLs, none of them are relative. This gives the impression that only absolute URLs are valid
> 
> Examples are non-normative, and cannot be exhaustive.

Granted, what about the other point?

**Comment by MikeRalphson** [comment]
If you have time to submit a PR to improve the consistency of the wording regarding URLs, that would be great.

**Comment by michael-o** [comment]
> 
> 
> If you have time to submit a PR to improve the consistency of the wording regarding URLs, that would be great.

Will pick this up next week and see whether I can come up with a better documentation.

**Comment by michael-o** [comment]
@MikeRalphson Went through the entire document. I think my previous understanding was too strict. I wan't able to come up with a better description as the one provided.
