### ISSUE TITLE
Support file upload for arbitrary mime types

### ISSUE THREAD

**Issue by jmoraleda** [OAI/OpenAPI-Specification#2185]
Currently swagger ui guesses, based on mime type, whether to, display a file upload button, or a text input box.

For example the following code from https://swagger.io/docs/specification/describing-request-body/file-upload/

``` yaml
    requestBody:
      content:
        image/png:
          schema:
            type: string
            format: binary
```
produces an upload buton, but changing the type to `application/pdf` 

``` yaml
    requestBody:
      content:
        application/pdf:
          schema:
            type: string
            format: binary
```

produces a text box and I have not been able to make it produce an upload button (See discussion at https://github.com/springdoc/springdoc-openapi/issues/515). 

 I feel a mechanism that can override the auto-detected default of whether to use an upload button or an input text box would be very useful, since there is a large and growing, number of media types and use cases and, in addition, any application can define its own custom media type `application/x-foobar`.

Thank you.

**Comment by hkosova** [comment]
@jmoraleda this Swagger UI issue is tracked here: https://github.com/swagger-api/swagger-ui/issues/5636.

**Comment by jmoraleda** [comment]
Thank you @hkosova I will close this issue and consolidate the discussion to that other issue.
