### ISSUE TITLE
Open TSC Meeting, Thursday April 2nd 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2188]
**NOTE: This meeting is on Thursday at 9am - 10am PT**
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting*

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| $schema in Schema Object | Someone |  |
| ReadOnly / WriteOnly | TSC |  |
| Continue: discriminator (Live or Die)?  |  TSC |  |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by Relequestual** [comment]
FYI `discriminator` is part of ~JSON Schema Language~ ~JSON Data Definition Format~ JSON Type Definition: https://github.com/jsontypedef and has caused confusion for one StackOverflow user this week: https://stackoverflow.com/questions/60959556/using-discriminator-keyword-in-json-schema?noredirect=1#comment107861479_60959556

**Comment by darrelmiller** [comment]
Notes from meeting:
- We should add text to identify the schema as using the OpenAPI vocabulary with URI as the Id.  The Id could be,  https://spec.openapis.org/oas/3.1/schema-object   This conversation can continue in the spec channel.
- Schema objects should be assumed to identify as using the $schema of the id defined in the last bullet point.
- For external tools to process the JSON Schema as using an OpenAPI vocabulary users would need to include this id in the schema.

**Comment by darrelmiller** [comment]
Discussed readOnly/writeOnly.  Acknowledged that to be compatible with JSON Schema we do need to make what could be considered a breaking change.  We need to investigate the impact of this change as we believe it would primarily affect people who use request payload validators that are OAS aware.  We are not sure they actually exist.
