### ISSUE TITLE
Only one URL with a "token" in response for authentication

### ISSUE THREAD

**Issue by chadyred** [OAI/OpenAPI-Specification#2189]
Hello,

I have an URL which give me the token : `/Token`(I have to set an `Authorization header` needed to get the token, with a hard-code value).

So I want to inject this token receive in response for each request. I **have** only `/Token` : no refresh, or authorize URL.

In this article I try this two possibility : https://jolicode.com/blog/jane-v5-3-performances-authentication-openapi-2

But it seems that this two case don't reply to my goal . 

So how programmatically or in configuration do : 
- Go to this `/token` url with this `Authorization header` 
- get the return value `{"token": "value"}` 
- then for each URL use the return in each request, by setting for each request this header custom `Authorization: axe token_value_receive` ?

And do it at each request as we don't have any other information about the token created...

Maybe, by using callable to insert in request header could do the trick ? So Is it possible with Jane and Open Api to do this things ?

Thanks.

**Comment by philsturgeon** [comment]
I'm sorry I don't understand the question. Is this a bug report or a support request for working with a specific tool?

OpenAPI allows any sort of tokens to be used. If its a Bearer token you can use "scheme: Bearer" but it looks like you've got "axe" which isn't something I've seen. You can probably scheme: "axe" if its a valid IANA scheme. 

Anyhow, maybe your question could be answered better if you provide an OpenAPI document to work from, showing what you have tried.

Then mention what were you expected, along with what the outcome was, so we can see what it is you'd like to behave differently.

**Comment by chadyred** [comment]
I think it is more like a Client issue who not using a standard request token....I create my own header custom.
