### ISSUE TITLE
Document links are broken on https://swagger.io/specification/

### ISSUE THREAD

**Issue by gkalnytskyi** [OAI/OpenAPI-Specification#2193]
When I try to follow internal and external links on [Swagger Specification](https://swagger.io/specification) page I receive 404 error, because links have github document prefix.

Here is an example for "JSON schema ruleset" from Format section of the document:
https://github.com/OAI/OpenAPI-Specification/blob/master/https://github.com/OAI/OpenAPI-Specification/blob/master/https://yaml.org/spec/1.2/spec.html#id2803231

Or for "JSON Schema Specification Wright Draft 00":
https://github.com/OAI/OpenAPI-Specification/blob/master/https://github.com/OAI/OpenAPI-Specification/blob/master/https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.2

I believe that this issue is similar to the following one https://github.com/OAI/OpenAPI-Specification/issues/1726

**Comment by MikeRalphson** [comment]
Thanks. I believe the correct place to report this would be https://github.com/swagger-api/swagger.io - this repo is for the canonical version of the specification only.

**Comment by mloskot** [comment]
Copied to https://github.com/swagger-api/swagger.io/issues/277
