### ISSUE TITLE
The need for a dynamic client registration endpoint under OAuth2 security.

### ISSUE THREAD

**Issue by nuwand** [OAI/OpenAPI-Specification#2194]
OAuth2 security specifications in the OpenAPI spec currently allow defining the authorizationUrl and the tokenUrl of the relevant authorization server. An application consuming the API would need to initiate the auth_code login flow using this information to get an access token for this API. The application however would need a valid client_id and client_secret to use this flow. The OpenAPI spec currently does not have a mechanism for API users to know how they can get a client_id, client_secret pair for their applications.

Authorization servers that support OAuth2 usually would support the Dynamic Client Registration Management (DCRM) [1] or the DCR [2] protocol. If the OpenAPI spec could include the URL of the registration endpoint available on the authorization server, this would help users to figure out how to register their applications. I propose that this information be included in the spec along with the authorization and token URLs.

[1] - https://tools.ietf.org/html/rfc7592
[2] - https://tools.ietf.org/html/rfc7591

**Comment by darrelmiller** [comment]
@nuwand Currently it is assumed that clients will obtain the client registration details out of band.  

If a service supports Dynamic Client Registration then it would make sense to advertise that in a OpenID connect discovery document using the "[registration_endpoint](https://openid.net/specs/openid-connect-discovery-1_0.html).  OAS does support pointing to this discovery document.  That is the recommended approach.  It would be unwise for OAS to slowly add all the possible OpenID/OAuth2 configuration values into the OAS considering there is a standardized way to represent this information.

**Comment by nuwand** [comment]
@darrelmiller I agree partially :). So what if, instead of the OAS spec advertising the authorizationUrl and the tokenUrl only, it advertised the OIDC discovery URL instead? That way instead of partially exposing details of the OIDC provider, the spec would support a mechanism that gives the full details of the OIDC provider.

**Comment by nuwand** [comment]
@darrelmiller Super! I didn't know OAS also supported the openIdConnectUrl. Thanks.
