### ISSUE TITLE
How to perform multi select in open API using springdoc-openapi-ui

### ISSUE THREAD

**Issue by javaHelper** [OAI/OpenAPI-Specification#2195]
How to perform multi select in open API using springdoc-openapi-ui? I've posted question here: https://stackoverflow.com/questions/61006409/open-api-spec3-how-to-display-a-drop-down-or-a-way-to-select-an-input-from-mul, expecting quick response

**Comment by MikeRalphson** [comment]
Expectations notwithstanding, this issue is off-topic for this repo which only deals with the OpenAPI specification itself.

You could also raise your issue on the relevant `springdoc` repository.
