### ISSUE TITLE
Polymorphism in Response.schema

### ISSUE THREAD

**Issue by mission-liao** [OAI/OpenAPI-Specification#220]
In [this example](https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/models/modelWithComposition.json), If I want to instantiate a 'Cat' Schema object, I would need to assign 'Cat' to 'petType' property to make others know it's a Cat object.

If I have a Responses object like this, when I need to convert the return value based on its Schema object, what value should I assign to 'petType'?

``` json
{
  default: {
    schema: {
      allOf:[
        { $ref: #/definitions/Pet }
        { properties: {...} }
      ]
    }
  }
}
```

**Comment by webron** [comment]
IIRC, we discussed this in the mailing list (which is why you opened the issue here). Obviously the quick answer is to not define these things inline, but we may have to end up bringing back the `id` field.

**Comment by webron** [comment]
Parent: #579.

**Comment by webron** [comment]
Tackling PR: #741

**Comment by handrews** [comment]
I'm pretty sure that this 5+ year old issue, if still relevant, would need to be updated to fit in with what's gone on since then in 3.0 and 3.1.  So I'm going to close this.  Please open a new issue with an updated description if it's still a concern for 3.1.
