### ISSUE TITLE
Mentioning of not allowing unescaped slashes in path parameters.

### ISSUE THREAD

**Issue by dumka** [OAI/OpenAPI-Specification#2204]
According to this discussion https://github.com/OAI/OpenAPI-Specification/issues/892 unescaped slashes are not allowed in path parameters. But OpenAPI itself doesn't mention it. Is possible to add it to the specification in order to avoid any further confusion?

**Comment by philsturgeon** [comment]
@dumka I took a swing at this over here. https://github.com/OAI/OpenAPI-Specification/pull/2218

**Comment by MikeRalphson** [comment]
Closing as #2218 was merged. Thanks all.
