### ISSUE TITLE
USPTO Data Set API no longer available

### ISSUE THREAD

**Issue by dragetd** [OAI/OpenAPI-Specification#2208]
The example API is no longer available and thus results in an error when trying to use it.

```
Exception when calling SearchApi#performSearch
org.setlog.client.ApiException: Not Found
```

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/uspto.yaml

I would suggest removing it or moving it into some subdirectory or using some other mean of marking it as no longer functional.

**Comment by dragetd** [comment]
Same for https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

**Comment by MikeRalphson** [comment]
Are you sure it's not your end? Both APIs are returning data for me now.

**Comment by dragetd** [comment]
https://developer.uspto.gov/ds-api (as written in the spec) is giving a 404 for me.

Looking through the other examples one could argue that the examples should only show how the OpenAPI document is written and do not serve the purpose to result in a functional client. Tho I think it would be nice if the examples would result in working code. What do you say?

**Comment by MikeRalphson** [comment]
`https://developer.uspto.gov/ds-api/` with the trailing slash appended from the `/` `path` works fine. There is no expectation that a raw `servers` `url` will be reachable.

Paging @webron / @hkosova re: updating examples to `https://petstore.swagger.io/v2/...`
