### ISSUE TITLE
Multiple cases not being displayed in one http code in swagger editor

### ISSUE THREAD

**Issue by rssubham88** [OAI/OpenAPI-Specification#2220]
Hi, I have multiple error cases under http status 400.  But swagger editor is not displaying it properly rather it is fetching it from the reference defined
I want it should display the structure I am creating :

        '400':
          description: 'Failure - Bad request'
          schema:
            $ref: '#/definitions/faultResponse'
          examples:
            No Chain:
              fault:
                code: '-1'
                message: 'Mandatory request header(s) not found or invalid'
                httpStatus: 400  
            No Chain2:
              fault:
                code: invalidRequest
                message: Invalid request
                providerCode: '400'
                failures:
                  - message: 'Invalid type,  abcid (value as provided in request)'
                    providerCode: '-4'
                httpStatus: 400
            No Chain3:
              fault:
                code: invalidRequest
                message: Invalid request
                providerCode: '400'
                failures:
                  - message: 'Invalid type, xyzid (value as provided in request)'
                    providerCode: '-5'
                httpStatus: 400

**Comment by handrews** [comment]
Hi- this repository is for the specification only.  Please raise tooling issues with the tooling vendor (Swagger / SmartBear in your case).  Thanks!
