### ISSUE TITLE
Examples - Pet store different from petstore.swagger?

### ISSUE THREAD

**Issue by Axeka379** [OAI/OpenAPI-Specification#2228]
In the example specification, petstore.yaml/petstore-expanded.yaml does not correspond to the one hosted on [petstore.swagger](https://petstore.swagger.io/). Is there reason for this or would it not be better to keep them coherent?

**Comment by MikeRalphson** [comment]
@Axeka379 do you mean the example is not identical with the one on petstore.swagger.io, or that it is not a proper subset of it (i.e. it doesn't accurately describe a part of that API surface)?

Maybe @webron or @hkosova could comment?

**Comment by aghorpade** [comment]
@MikeRalphson - @Axeka379  would like to point that example mentioned under OpenAPI-Specification/examples/v3.0/petstore-expanded.yaml location does not match with https://petstore.swagger.io 
e.g. resource pet should be pural which is in example while on UI it is /pet which doesn't seems to be correct. Also there is not get method available to retrieved all pets on https://petstore.swagger.io which is mentioned on petstore-expanded.yaml file.

![image](https://user-images.githubusercontent.com/5318345/88819723-4761c980-d1b8-11ea-9537-4e5b4c51b569.png)

I hope this gives better picture

**Comment by lornajane** [comment]
As far as I can tell, the OpenAPI version of this file was expanded to give some more use cases, and I don't think there's a need to keep the two in sync so I will close this (rather outdated!) issue.
