### ISSUE TITLE
Feature suggestion: Server object add name property

### ISSUE THREAD

**Issue by tanmen** [OAI/OpenAPI-Specification#2229]
Hello.
I think should be server object add name property.
because server object identification only url.
I think short identify properties should be created for generated code.

I am Japanese and have never learned English.
I'm sorry if i have rude remark.

**Comment by MikeRalphson** [comment]
Hi @tanmen, your issue is definitely not rude and is completely understandable. However, this issue has been raised before and so this is a duplicate of issue #1821. Please join in the conversation / add a reaction on that issue.

**Comment by tanmen** [comment]
Thank you:)
its ok.
