### ISSUE TITLE
Issue with Server Object Variables

### ISSUE THREAD

**Issue by jshankhwar-mdsol** [OAI/OpenAPI-Specification#2231]
Having the default value of a server Object as an empty string throws the null pointer exception.
An empty string is also a string So it should be fine 

servers:
 url: https://hostexample{stage}.companyName{region}.{tld}{basePath}
    variables:
       stage:
         default: sandbox
       region:
         `default: ''`

**Comment by jshankhwar-mdsol** [comment]
<img width="931" alt="Screen Shot 2020-05-14 at 4 35 44 PM" src="https://user-images.githubusercontent.com/40658172/81927291-06b6d300-9601-11ea-8d8b-103df71b5b0c.png">

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. Thanks.

**Comment by jshankhwar-mdsol** [comment]
I have written the Validator using this like

  private val openApiValidator = OpenApiInteractionValidator
    .createFor(new File(openApiFilePath).getCanonicalPath)
    .withLevelResolver(LevelResolver.create().withDefaultLevel(ValidationReport.Level.ERROR).build())
    .build
