### ISSUE TITLE
Re-use schema definition in request body

### ISSUE THREAD

**Issue by liamkeily** [OAI/OpenAPI-Specification#2234]
I am using a complex schema to define an API response, but i also need to use this schema as the request body. Duplicating this schema would be hard to maintain

The problem is that not every single field from the Schema needs to be included. There are a few (such as ID) which should not be sent in the request body. 

Is there a nice way of including a subset of a Schema in a request body?

**Comment by handrews** [comment]
@liamkeily it's a constraint system so there are two options, depending on whether you are using `additionalProperties` as well (usually `"additionalProperties": false`)

If you're using `additionalProperties: false`, then write the schema with ID present but not required.  For your request schema do an `allOf` with the schema `{"not": {"required": ["ID"]}` (which reads oddly but means "ID is forbidden") and for your response schema, if ID is required, do `allOf` the basic schema with `{"required": ["ID"]}`

I'm not sure how code gen tools will handle it if "ID" is defined but in some cases forbidden.  If you're not using `additionalProperties: false`, then you have more flexibility- define your basic schema without ID being present at all, and just add it to the response schema with `allOf`.

You can, of course, set up the request and response schemas (that use `allOf`) under `#/components/schemas` if they show up in multiple places as well.
