### ISSUE TITLE
How to not include ID in the request body

### ISSUE THREAD

**Issue by liamkeily** [OAI/OpenAPI-Specification#2235]
I am having an issue that is also demonstrated in the Swagger Petstore example https://petstore.swagger.io/

When creating an Order it doesn't make sense to pass an ID in the request, as this is generated on the server-side. Yet because the request body references the Order schema (which includes an ID) it shows the ID as a suitable property. 

Is there any way in the OpenAPI spec to avoid including certain properties in the request body without having to define a separate request body.

**Comment by handrews** [comment]
@liamkeily didn't see that you opened this and closed the other- need caffeine 😴 )  Copying over my reply to the other issue:

JSON Schema is a constraint system so there are two options, depending on whether you are using `additionalProperties` as well (usually `"additionalProperties": false`)

If you're using `additionalProperties: false`, then write the schema with ID present but not required.  For your request schema do an `allOf` with the schema `{"not": {"required": ["ID"]}` (which reads oddly but means "ID is forbidden") and for your response schema, if ID is required, do `allOf` the basic schema with `{"required": ["ID"]}`

I'm not sure how code gen tools will handle it if "ID" is defined but in some cases forbidden.  If you're not using `additionalProperties: false`, then you have more flexibility- define your basic schema without ID being present at all, and just add it to the response schema with `allOf`.

You can, of course, set up the request and response schemas (that use `allOf`) under `#/components/schemas` if they show up in multiple places as well.

_NOTE:_ if you really dig into the 3.0 spec there's some request/response-specific behavior described for `required`- this is (I believe) inconsistently implemented and is being removed in 3.1, so the schema design techniques I describe here will continue to work in 3.1, while relying on request/response context to change the behavior of `required` will not work in 3.1.

**Comment by handrews** [comment]
Since it's been more than a week I'm assuming the answer sufficed.  Please comment/reopen if not and I'll see it and reply.
