### ISSUE TITLE
[Question] Object parameters for query

### ISSUE THREAD

**Issue by DanteSparda** [OAI/OpenAPI-Specification#2237]
Before we start -> Love your work <3 awesome idea and implementation.

As far as I see Query Parameters must be primitive types, since you can't query json (my best guess)
I'm using .net core as backend and vue / ts for FE
eg
In the backend I have 
```
GetAll(QueryObject` obj)
=> QueryObj{ Ids int[], userId string}
```
The code generated by my swagger is 
```
`getAll(ids?: Array<number>, userId?: string){
if (ids) {
                localVarQueryParameter['Ids'] = ids;
            }
}
...
```

But what if the api specification can say 
```getall -> parameters: 
- name: X
          in: query
          type: [pointer to the exposed object (QueryObject)]
```
After that the script generating can see if the params are object and change the generating ifs to
```
getAll(QueryObject queryObject){
if(queryObject){
if (queryObject.ids) {
                localVarQueryParameter['Ids'] = queryObject.ids;
            }
}
}
```
Is there any reason for this not to happen? Currently if I have two objects in the GetAll method and add a property in the first one, the order shifts and I break the front end.
I know that you're taking care of 50 different script languages and there are pleanty of bugs and features to be added, so best of luck to y'all!

**Comment by MikeRalphson** [comment]
Apologies for the length of time this has been open.

You say "The code generated by my swagger is ..." this leads me to think this is essentially a tooling problem.

Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
