### ISSUE TITLE
Add support for BeanParam for generated classes CXF

### ISSUE THREAD

**Issue by mohanaraosv** [OAI/OpenAPI-Specification#2240]
Please add support for generating BeanParam instead of lengthy parameters. It also violates the [https://wiki.c2.com/?TooManyParameters](Too Many Parameters).

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
