### ISSUE TITLE
Example YAML for 3.0 Requests not Working

### ISSUE THREAD

**Issue by NikitaVr** [OAI/OpenAPI-Specification#2245]
I have tried using the YAML in the following example, but when clicking "Try it Out" the request has an error `blocked:mixed-content`

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

When I change the server URL to use https, there are just 404 not found errors on all the requests

**Comment by philsturgeon** [comment]
This seems like a problem with Swagger UI not the specification itself. :)
