### ISSUE TITLE
Make jsonschema completion friendly

### ISSUE THREAD

**Issue by rmannibucau** [OAI/OpenAPI-Specification#2249]
JSON-Schema is a nice tool to validate a payload but it also enables to get completion (in vscode and most modern editors).

Current openapi3 jsonschema does not work at all with completion and has 2 pitfalls:

1. no description
2. written in a way it does not enable an IDE to discover much the completion due to a lot of regex (Pathitem patternproperties for verbs is a good example)

This ticket is about ensure at all stage some completion or at least description is enabled to make it user friendly.

**Comment by MikeRalphson** [comment]
See (approved) PR #2127 for `pathItem` `patternProperties` and (closed) issue #1948 for adding descriptions to the official schema.

**Comment by MikeRalphson** [comment]
As the PR for the operation methods (regex -> oneOf) was merged and the issue involving adding descriptions was closed as a `won't-fix`, closing this issue (but it can always be re-opened if necessary).

**Comment by rmannibucau** [comment]
Hi @MikeRalphson ,

Do you have the description related PR link handy? Would be great to fix it since it really helps when writing specs by hand or reviewing generated ones.

**Comment by rmannibucau** [comment]
ok so let's continue on https://github.com/OAI/OpenAPI-Specification/issues/1948 then. Thanks.
