### ISSUE TITLE
How to use parameters list from the schema?

### ISSUE THREAD

**Issue by erickskrauch** [OAI/OpenAPI-Specification#2259]
Hello. Is there is any way to define the `parameters` list of the `path` by extending parameters from the `schema`?

```yaml
openapi: "3.0.0"
info:
  title: Demo
  version: 1.0.0

paths:
  /api/v3/places/poi:
    get:
      tags:
        - places
      summary: 'Get POI data'
      operationId: poi
      parameters:
        # This causes an error
        $ref: '#/components/schemas/POIRequest'
      responses:
        '200':
          description: Success

components:
  schemas:
    POIRequest:
      title: 'Points of intereset search request'
      required:
        - lat
        - lng
      properties:
        lat:
          description: 'Point''s latitude'
          type: number
          format: float
          maximum: 90
          minimum: -90
        lng:
          description: 'Point''s longitude'
          type: number
          format: float
          maximum: 180
          minimum: -180
        lang:
          description: 'Prefered language for results'
          type: string
          default: en
          example: ru
      type: object
```

**Comment by MikeRalphson** [comment]
This is currently not possible, as a `schema` object has a very different structure to an array of `parameter` objects. There is no shorthand mapping between the two because there is not enough information in a `schema` object to declare whether a `parameter` is (say) `in:path` or `in:query` nor its `style` or `explode` values.

Closing as not supported, but if this is more a feature request, and especially if you have a proposal for how it might be implemented going forward, we can always re-open.

**Comment by hkosova** [comment]
@erickskrauch Do you maybe mean something like this?

```yaml
      parameters:
        - in: query
          name: poi
          schema:
            $ref: '#/components/schemas/POIRequest'
          style: form
          explode: true
```

This is considered a single parameter with an object value, but this object will be sent as individual `property=value` query parameters in the request URL:

```
GET /api/v3/places/poi?lat=10&long=20&lang=en
```

**Comment by erickskrauch** [comment]
@hkosova, thanks for your suggestion, but Swagger don't understand this syntax :(
![](https://erickskrauch.ely.by/monosnap-09-06-2020-at-14-35-10.png)

@MikeRalphson, I think the `parameters` syntax should be extended to allow object definition. For example:

```yaml
parameters:
  in: query
  # Other common params
  schema:
    $ref: '...'
  # Or
  schema:
    oneOf:
      - $ref: '...'
      - $ref: '...'
```

So the syntax should allow the same params declaration, as it possible for `requestBody`.

**Comment by hkosova** [comment]
@erickskrauch you seem to be using an old version of Swagger UI. Here's how it looks in the latest version.

Also, tooling issues (issues with doc renderers, code generators, etc.) should be reported in that tool's repository, not here. This repository is for the OpenAPI Specification itself.

![image](https://user-images.githubusercontent.com/8576823/84145239-328f7200-aa62-11ea-8bb5-0e3c68f80192.png)

**Comment by erickskrauch** [comment]
@hkosova, yep, upgrading the Swagger to the latest build given me the same result. Rendered not perfectly, but at least the "Try it out" button works fine. Thanks!

The issue is still here because the syntax for such declaration currently is very tricky and it should be made more direct.

**Comment by hkosova** [comment]
@erickskrauch check out the syntax guide on swagger.io, it has many examples:
https://swagger.io/docs/specification/describing-parameters/
https://swagger.io/docs/specification/serialization/
