### ISSUE TITLE
Generating Generic Value from Swagger for autogeneration

### ISSUE THREAD

**Issue by aymanarif97** [OAI/OpenAPI-Specification#2261]
I am autogenerating my models using Swagger autogen tool in Java.
I am trying to create a generic type for a member variable. In the example below I am trying to create a generic value `genericValue` for my employee class.

    public class Employee<T>  {
        @NotEmpty
        Long id;
        @NotBlank
        String employeeName;
        @NotNull
        T genericValue;
    
    }

This is my `swagger.yaml`: 

    Employee:
      type: object
        properties:
          id:
            type: integer
            example: '123'
          employeeName:
            type: string
            example: 'Jon Doe'       
          genericValue:
            type: generic
Is it possible to create a generic variable or is it not supported in swagger autogeneration?

Note that I am using OpenAPI version 3.0.0.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
