### ISSUE TITLE
Property name alias

### ISSUE THREAD

**Issue by bougar** [OAI/OpenAPI-Specification#2262]
Hello,
I would like to see in the specification any option alias a property with multiple names. Would it be possible in future releases of the specification?

Thanks in advance.

**Comment by MikeRalphson** [comment]
Could you expand on your use-case / potential solution. It could be this is a duplicate of #2055

**Comment by MikeRalphson** [comment]
Could you expand on your use-case / potential solution. It could be this is a duplicate of #2055

**Comment by bougar** [comment]
I would like to have any option to reference the same property. For example:
```
"type" : "object",
"properties" : {
     "name" : {
            "type" : "string",
            "aliases" : [
                  "alias"                   
            ]
     }
}
```
In this case "alias" field should be serialized as "name". This makes sense for me if I want to rename a property name without breaking compatibility with previous versions.

**Comment by MikeRalphson** [comment]
This does very much sound like a duplicate of the other issue. Please continue the conversation there.
