### ISSUE TITLE
Correct way to use patch method to update resources?

### ISSUE THREAD

**Issue by theodoresi** [OAI/OpenAPI-Specification#2264]
Hey, I have a question here, can someone help?

https://stackoverflow.com/questions/62358406/how-to-update-resources-with-patch-method-using-openapi-correctly

**Comment by MikeRalphson** [comment]
I would use formats such as JSON Patch or JSON Merge Patch, which do not directly use your Person schema/representation.

You can think of a translation from the Person schema as having taken place but that translation can happily drop the `required` constraint on omitted properties.

**Comment by MikeRalphson** [comment]
Please let us know if the above does not answer your question, and we can re-open this issue.
