### ISSUE TITLE
TypeLoadException could not find type in dll file

### ISSUE THREAD

**Issue by tcss450group3** [OAI/OpenAPI-Specification#2272]
Hi, I have this error while generating the OpenAPI documentation for my project in Azure Devops pipeline.
Since the Domain.TrackerVersion is located in another project in the same solution, how can I add it to myproject.dll so that it won't complain about not finding the object in the XML?
Thanks

This is the exception I got :
**POST /api/tracker/updateorcreate || ExceptionType: TypeLoadException || Message: Type "Domain.TrackerVersion" could not be found. Ensure that it exists in one of the following assemblies: myproject.dll Newtonsoft.Json.dll**

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
