### ISSUE TITLE
Multiple openapi endpoints with multiple JAX-RS applications

### ISSUE THREAD

**Issue by Blubb324** [OAI/OpenAPI-Specification#2274]
Hello guys,

last time I was wondering about a deployment of 2 artefacts which are using open-api.

The server log said that only one open-api endpoint is possible. After googling around I have read this:

"**Before you proceed, note that the 1.0 version of the MicroProfile OpenAPI specification does not define how the /openapi endpoint may be partitioned in the event of multiple JAX-RS applications running on the same server. In other words, you must stick to one JAX-RS application per server instance as the behaviour for handling multiple applications is currently undefined.**"

Source: [https://github.com/OpenLiberty/guide-microprofile-openapi](https://github.com/OpenLiberty/guide-microprofile-openapi)

Is there already a solution or a plan to specify this?

The current solution is that I have to deploy 1 artefact at 1 server. But e.g. there are 10 simple micro services it would be totally overhead to start 10 servers. Addionally I cannot combine them into 1 file, because of bounded contexts.

Btw. I really like openapi but at the moment this state is a bit impractical.

I hope it´s the right place for adressing this issue. 
Thank you in advance!

**Comment by MikeRalphson** [comment]
Unfortunately, no this is not the right place for this issue. This repository is for the OpenAPI specification itself only. I would suggest raising your issue in one of these repositories: https://github.com/OpenLiberty
