### ISSUE TITLE
External Object References for Enum Values

### ISSUE THREAD

**Issue by aschechter88** [OAI/OpenAPI-Specification#2275]
I want to be able to specify that a schema is an `enum` but that the list of available values is external (and possibly complex) and potentially not in openapi format. 

I have reference data:
```
“Countries”: [
    {
        “name”: “United States of America”,
        “code3”: “USA”,
        “code2”: “US”
    },
    {
        “name”: “Canada”,
        “code3”: “CAN”,
        “code2”: “CA”
    },
    {
        “name”: “Mexico”,
        “code3”: “MEX”,
        “code2”: “MX”
    }
]
```

and I want to specify that the correct enumerable value set on an openapi operation is one of the values specified by `#/countries/code2`. I know that the below is wrong -- but is there an actual answer?
```
“get”: {
    “parameters”: [
        “countryCode2”: {
            “in”: “query”,
            “schema”: {
                “$ref”: “referencefile.json/#/Countries/code2”
            }
        }
    ]
}
```

**Comment by karenetheridge** [comment]
The destination of your `$ref` must be a valid subschema. This is sufficient:

`{ "enum": [ "US", "CA", "MX" ] }`

..so you just need something that will transform your list of countries into that form and provide it as a definition that can be pointed to in a `$ref`.

**Comment by aschechter88** [comment]
That's what I hoped wouldn't be true. I want to avoid post-processing my reference data files.

**Comment by aschechter88** [comment]
I guess then that the necessary feature request would be JSONPath support in the `values` field for an `enum`?

**Comment by MikeRalphson** [comment]
I think the key words from this issue are "not in openapi format" and "they aren't schemas". These are the standards involved, so I can't see any reasonable way around your problem without further processing your non-schemas. As OAS uses the [JSON Schema specification](https://github.com/json-schema-org/json-schema-spec), you could raise your feature request there.
