### ISSUE TITLE
Confirm the licence of the schema files

### ISSUE THREAD

**Issue by tuxayo** [OAI/OpenAPI-Specification#2280]
It's a followup of this issue https://github.com/swagger-api/swagger.io/issues/281 in which was raised the need for a confirmation that the schema files are indeed under the same license as the whole repo.

**Comment by MikeRalphson** [comment]
It is not clear who this "confirmation" should be made from or to who. Nor would a GitHub issue statement be a matter of legal fact. As you say the whole repository is under the Apache-2.0 license, with no exclusions.

The OpenAPI Initiative [charter](https://www.openapis.org/participate/how-to-contribute/governance) states:

> 7. IP Policy
    All new inbound specification or code contributions to the OAI shall be made under the Apache License, Version 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0) accompanied by a Developer Certificate of Origin sign-off (http://developercertificate.org);
    All outbound specifications or code will be made available under the Apache License, Version 2.0.
    All documentation will be received and made available by OAI under the Creative Commons Attribution 4.0 International License.

**Comment by tuxayo** [comment]
> It is not clear who this "confirmation" should be made from or to who. Nor would a GitHub issue statement be a matter of legal fact. As you say the whole repository is under the Apache-2.0 license, with no exclusions.

That was my though also that the fact being in a repo that has a global license (and no exception it seems) is enough. But the conclusion of https://github.com/swagger-api/swagger.io/issues/281 made feel like having to ask here.

Thanks for you help. Now I can reach downstream (https://metacpan.org/release/JSON-Validator) and it's downstream (https://packages.debian.org/buster/libjson-validator-perl) ^^
