### ISSUE TITLE
Security filtering and templated paths - clarification needed

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#2287]
The [Path Item Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#path-item-object) section says:

> A Path Item MAY be empty, due to [ACL constraints](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#securityFiltering). The path itself is still exposed to the documentation viewer but they will not know which operations and parameters are available.

This allows things like

```yaml
paths:
  /users: {}
```

But what about templated paths? Is the following definition _supposed_ to be valid?

```yaml
paths:
  /users/{id}: {}
```

<br/>

According to the [Path Templates](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#pathTemplating) section:

> Each template expression in the path MUST correspond to a path parameter that is included in the [Path Item](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#path-item-object) itself and/or in each of the Path Item's [Operations](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#operation-object).

which suggests that empty templated path items are considered invalid, and we need to explicitly define any path parameters:

```yaml
paths:
  /users/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
```

However, this requirement conflicts, in a way, with OpenAPI's concept of security filtering where "viewer ... will not know which ... parameters are available."

<br/>
I wonder if the "Path Templates" section was meant to say:

> Each template expression in the path MUST correspond to a path parameter ... **unless the path item is empty due to [ACL constraints](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#securityFiltering).**

**Comment by darrelmiller** [comment]
Thanks for raising this issue.  We discussed this in the TSC call and agree that some clarification is needed.  We are not yet convinced of whether it is better to add the empty path item exception or require the minimal parameter description.  /cc @OAI/tsc  for thoughts and suggestions.

**Comment by darrelmiller** [comment]
Ron decided we should allow empty paths.  /cc @OAI/tsc bowed to his opinion.

**Comment by darrelmiller** [comment]
@hkosova Would you be able to create a PR that allows the empty path exception?
