### ISSUE TITLE
gradle-wraper.jar corrupted in Generator 5.0.0 snapshot

### ISSUE THREAD

**Issue by ThomasRBurke** [OAI/OpenAPI-Specification#2307]
I am using these tools at my company Guidewire Software to generate REST Client APIs and when I upgraded from Generator 4.3.1 the gradle-wrapper.jar it creates is corrupted.   The cause is that jar when copied it is being converted into a string array instead of byte[].   
The problem starts in DefaultGenerator 
 private void generateSupportingFiles(List<File> files, Map<String, Object> bundle) {    

if you go to this call 
File written = processTemplateToFile(bundle, support.templateFile, outputFilename, shouldGenerate, CodegenConstants.SUPPORTING_FILES);
Then 
if (shouldGenerate) {
                return this.templateProcessor.write(templateData, templateName, target);
then 
TemplateManager
public File write(Map<String, Object> data, String template, File target) throws IOException { 
This gets the jar file as a string.   
String templateContent = this.engineAdapter.compileTemplate(this, data, template);

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
