### ISSUE TITLE
Unidimensional list of keywords as a first class member of the Info object

### ISSUE THREAD

**Issue by jmachen** [OAI/OpenAPI-Specification#2308]
Given that APIs are increasingly aggregated into API management solutions and presented as an aggregate within development portals it would be useful to be able to specify keywords (ideally rendered as highlighted text below the API description) which highlight arbitrary characteristics of the API.  For example:

```yaml
info:
  title: Some API
  description: Returns an arbitrary data object
  keywords: [ OIDC, public, critical, always_on, <responsible party/owner>, pilot ]  
```

This is of definite and immediate utility in an enterprise facing environment where the consumers are known entities and the relationship between consumer and producer is more intimate than in the eCommerce setting, but I suspect that there are ample use cases in a more public forum to justify its application there.

There need not be support for anything more complex than a one dimensional array of strings to satisfy the intent of this request.

**Comment by MikeRalphson** [comment]
Have you trialled this with a specification extension (`x-` property) ?

**Comment by jmachen** [comment]
> Have you trialled this with a specification extension (`x-` property) ?

Yes, we are experimenting with this for CI/CD purposes, but would prefer not to have to implement custom parsing and display logic within the developer portal.

**Comment by lornajane** [comment]
Do we have some examples of using this "in the wild" as an extension? If we see something like this being adopted successfully, then it's more likely that the project can consider a proposal to add it to the main specification.

**Comment by jmachen** [comment]
Apologies, changed jobs and this is no longer personally relevant.

I'm a little puzzled as to how I would demonstrate it being adopted in the wild when it's an unsupported feature of the spec, but I guess that's moot now.

**Comment by lornajane** [comment]
It might be moot for you, but I still think it's a good question that deserves a good answer.

OpenAPI supports extensions, such as `x-internal`, so this question is about whether we can see the thing you're requesting (or something along the same lines) commonly served by some extension. If it is, then it makes it easier to see both that it's important to cover in the spec, but also how it can be used by actual users. For example, `x-experimental` is widely used, and adding an `experimental` keyword is under consideration for a future release now.

Hope that adds some context.

**Comment by jmachen** [comment]
I didn't mean to seem cavalier, I just meant that I am no longer operating in this space in quite the same way and my current duties limit the extent to which I can explore the topic.
