### ISSUE TITLE
Auto generated code does not add XmlRootElement to my model files

### ISSUE THREAD

**Issue by jothi-prasad** [OAI/OpenAPI-Specification#2309]
Hi,
i wanted to support both Json and xml for my content type for producing output.
i am adding both the content type to my openapi 3.0 spec. pls check the link below to see the spec file.
https://github.com/jothi-prasad/openapi/blob/master/user-openapi.yaml

But the auto code generated by swagger-cli (java -jar swagger-codegen-cli.jar generate -i ./user-openapi.yaml -l jaxrs-jersey)
is not adding the xml annotations(@javax.xml.bind.annotation.XmlRootElement) to my model files. do i have to add them manually?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
