### ISSUE TITLE
Data Mocking Official Interfaces

### ISSUE THREAD

**Issue by ybelenko** [OAI/OpenAPI-Specification#2310]
Hey, OAI members!

Long story short. On December 2019, I didn't find any PHP package or a tool to mock data from OpenAPI 3.0 Schema. I think it's crucial tool for unit testing, so I decided to develop my own and here is the result of three repos:
* [ybelenko/openapi-data-mocker-interfaces](https://github.com/ybelenko/openapi-data-mocker-interfaces)
* [ybelenko/openapi-data-mocker](https://github.com/ybelenko/openapi-data-mocker)
* [ybelenko/openapi-data-mocker-server-middleware](https://github.com/ybelenko/openapi-data-mocker-server-middleware)

I've noticed recently [canvural/php-openapi-faker](https://github.com/canvural/php-openapi-faker) package made by another developer for the same reason. It's a bit different because it parses complete spec, while my library has direct methods to generate fake data.  

As a conclusion, maybe you should provide official interfaces to implement mocking feature? Let's say abstract interface which can be implemented with any modern programming language. [`PHP-FIG`](https://www.php-fig.org) project already declares HTTP related interfaces(`ServerRequestInterface`, `ResponseInterface`, etc.) and maybe you could do the same?

_Anyway, let me know if I'm wasting my time with my packages and my developing is going nowhere._

**Comment by MikeRalphson** [comment]
Developing code (including standard interfaces) is outside the scope of this organisation and its charter.

I suggest you submit your projects to sites such as https://apis.guru/awesome-openapi3 (by adding the GitHub topic `openapi3`) and https://openapi.tools (by PR).

> Anyway, let me know if I'm wasting my time with my packages and my developing is going nowhere.

I'm sure you're not wasting your time, and thank you for working on OAS tooling implementations.
