### ISSUE TITLE
Create a complete meta schema for 3.1

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2314]

**Comment by jdesrosiers** [comment]
I'll take a stab at this.

**Comment by MikeRalphson** [comment]
@jdesrosiers thanks, this is fantastic! Do you intend to rework the complete 3.0 OAS metaschema (i.e. not just the `schemaObject`) to reference this dialect?

**Comment by jdesrosiers** [comment]
@MikeRalphson I was going to, but @philsturgeon beat me to it https://github.com/OAI/OpenAPI-Specification/pull/2474.

**Comment by MikeRalphson** [comment]
Closing as the PR has been merged. Thanks all!
