### ISSUE TITLE
Language polishing 

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2315]
PR #s to be added

- [x] * #1829 security / scopes
- [x] * #2181 $ref siblings   [There has been no strong case made for other properties that should be allowed as sibilings.]

**Comment by darrelmiller** [comment]
@MikeRalphson   Unless you feel strongly that we should consider adding other properties as potential siblings of $ref then I propose we defer adding more until later releases.

**Comment by karenetheridge** [comment]
I don't understand 2181 - isn't v3.1 now supporting JSON Schema draft 2019-09 (which allows $ref to be a sibling to any other keyword)?

**Comment by MikeRalphson** [comment]
#2181 addresses `$ref` outside schema objects.
