### ISSUE TITLE
Revisit Implementations update PRs

### ISSUE THREAD

**Issue by lornajane** [OAI/OpenAPI-Specification#2320]
We maintain `IMPLEMENTATIONS.md` which is described as

> Below is a list of known tooling that implements the 3.0.0 specification

With 3.1 coming, should we start a new list of implementations as the tools start to add support?

Is the `IMPLEMENTATIONS` file still useful, with other lists such as https://openapi.tools also being maintained?

There are a number of open Pull Requests to add implementations to the list, that all probably need rebasing at once. I can immediately see:
 * #2285 
 * #2278 (does need a minor update)
 * #2206 (approved but not merged)
 * #2203 
 * #2187 
 * #2182 
 * #1680 (changes requested)
 * #1668 
 * #1662 (does need a minor update)
 * #1600 (a tool with "openapi" in the name)
 * #1506 (includes a tool with "openapi" in the name)

(late additions)
 * #2323  
 * #2353

Are there some guidelines by which we can evaluate these PRs and either merge or close them? 11 of the current 39 total PRs relate to this one file and are all minor updates that don't affect the spec itself. I'm happy to do the actual wrangling to make a single set of updates if I can get some guidance on this.

**Comment by MikeRalphson** [comment]
Thanks @lornajane - we have finally begun moving from `IMPLEMENTATIONS.md` to https://tools.openapis.org
