### ISSUE TITLE
Investigate possibility of removing the constraint that paths must start with "/"

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2327]
Related #2316 

[Edit: `x-` specification extensions are currently allowed within the `paths` object]

**Comment by darrelmiller** [comment]
Closing as it would be too disruptive to the tooling ecosystem and doesn't add sufficient value.

**Comment by char0n** [comment]
Removing `/` from patterned fields would allow to use asterisk-form which serves just one single use-case described here: usecase https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#identifying_allowed_request_methods
