### ISSUE TITLE
Tooling to generate a diff report for incremental builds of an api

### ISSUE THREAD

**Issue by domenique** [OAI/OpenAPI-Specification#233]
It would be nice to be able to generate diff reports on the documented api. 

We are building a REST interface in a fairly large application and it would be nice if the swagger-ui would incorporate a diff with a comparison to a previous version of the deployed application. 

This could, imho be implemented by keeping snapshots of the api-docs and compare them with the current api-docs in the ui.

The diff should be fairly dumb: It should just report added/removed operations, modified request/response objects, etc. So not trying to detected operations that got moved/merged etc...

**Comment by lattewalk** [comment]
Vote to this

**Comment by DavidBiesack** [comment]
There are a number of existing open source tools that do something in this space - a simple search shows.
Look on swagger.io : http://swagger.io/using-swagger-to-detect-breaking-api-changes/

https://github.com/civisanalytics/swagger-diff (a Ruby tool)

See also a node package, https://www.npmjs.com/package/swagger-diff (
Supports only swagger spec 2.0)

I've not evaluated the effectiveness of any of these.

**Comment by nissimpradhan** [comment]
I would love this feature as well. And it seems that it has been done on 
[mendeley api.](https://api.mendeley.com/apidocs/changes). Would be awesome if this feature could be built into swagger. Ability to compare every swagger file inside a folder incrementally based on time.

**Comment by webron** [comment]
Closing as out of scope for the spec.
