### ISSUE TITLE
Open TSC Meeting, Thursday 03 September 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2333]
**NOTE: This meeting is on Thursday at 9am - 10am PT** - [click for local time](https://mermade.org.uk/tz?d=2020-09-03+09:00:00&tz=America%2FLos_Angeles)
Zoom Meeting link: https://zoom.us/j/975841675

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| JSON Schema feedback process | @Relequestual | |
| Implementations PRs, #2320 | @lornajane |  Awesome-openapi3 tools list to move to OAI repo for mechanically generated list.  Openapi.tools is the list with opinions. @webron to create repo.  @MikeRalphson  to move tools.  Lorna to close PRs to implementations.md and remove file. |
AOB | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=org%3Aoai+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |
| Getting Started guide PR feedback ||  Moar feedback required.  |
| Geo support|||

/cc @OAI/tsc Please suggest items for inclusion

**Comment by lornajane** [comment]
Can we spend a few minutes discussing the implementations list? Issue #2320 for a list of PRs and a thread about taking ownership of awesome-openapi.

**Comment by a-akimov** [comment]
Hello, smart people! Don't know if this is the right place to leave a comment, but can you probably also review #348 in one of the upcoming meetings?

**Comment by segfaultxavi** [comment]
The reviews of the Getting Started guide PRs are very slow, forcing me to juggle several interdependent branches. I'd like to discuss the possibility of working directly on master and make comments through issues.
