### ISSUE TITLE
@project.version@ variable not working

### ISSUE THREAD

**Issue by rboughani** [OAI/OpenAPI-Specification#2344]
Hi,
i try to use my old code from swagger-ui 2.5.0 in openApi 1.4.3, 

     
     <dependency>
		    <groupId>org.springdoc</groupId>
		    <artifactId>springdoc-openapi-ui</artifactId>
		    <version>1.4.3</version>
      </dependency>
      
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     

currently when i run my web service, it's faild, without error, and after many debugging, i noticed that openApi don't accept the syntax @project.version@ !

i use this syntax to get with spring boot the project version from pom.xml.
this syntax work in swagger 2.5.0, and not in 2.9.2.

i'm using yml file.

     swagger:
     enabled: true
     title: REST APIs for breakdown calculator
     description: REST APIs for breakdown calculator
     version: @project.version@
     terms-url:
     license:
     license-url:
     name: WORLD-LIST-REG
     email: lis@soc.mn
     url:

Did you have an idea ?
Thank you in advance.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by rboughani** [comment]
The question is already in stackoverflow, if you can help, Thank you.
https://stackoverflow.com/questions/63815390/spring-boot-project-version-variable-not-working-with-openapi
