### ISSUE TITLE
Open TSC Meeting, Thursday 17 September 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2348]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Status of getting started guide | @segfaultxavi / @ncaidin |  Need to determine deployment mechanism (@ncaidin to ask around LF projects)  Marjukka to investigate and provide recommendations  |
| `examples` in 3.1 #2336 | @philsturgeon | |
AOB (see below?) | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=org%3Aoai+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by philsturgeon** [comment]
Can we talk about this https://github.com/OAI/OpenAPI-Specification/pull/2336

**Comment by nlundquist** [comment]
Could https://github.com/OAI/OpenAPI-Specification/issues/2338 also be discussed?

**Comment by MikeRalphson** [comment]
@nlundquist have labelled #2338 for review. Hopefully we will get to it. Thanks.

**Comment by handrews** [comment]
I would like some information on the rough timeline for OAS 3.1 final.  Within the next month?  Within the next two months? 
 I do not want to find out that it's going out the door in a few days and we have not finished the JSON Schema draft.  I am also balancing a lot of other things personally so I need to know the urgency in order to make some trade-offs.

**Comment by handrews** [comment]
PR #2351 is a short but significant fix/streamlining of the `content*` that clearly separates what OAS controls vs what JSON Schema controls.  I'll keep an eye on slack- poke me there if you would like for me to jump on the call and answer questions.
