### ISSUE TITLE
GitHub sample media types misleading

### ISSUE THREAD

**Issue by letmaik** [OAI/OpenAPI-Specification#2350]
In the 3.1 spec the following media types are listed as examples:

  text/plain; charset=utf-8
  application/json
  application/vnd.github+json
  application/vnd.github.v3+json
  application/vnd.github.v3.raw+json
  application/vnd.github.v3.text+json
  application/vnd.github.v3.html+json
  application/vnd.github.v3.full+json
  application/vnd.github.v3.diff
  application/vnd.github.v3.patch

I find all the github media types misleading as those are not actually used in the `content-type` header, merely in `accept` for negotiation purposes. See https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.yaml. 

Also, following from https://github.com/OAI/OpenAPI-Specification/issues/2349, even if those media types were used as actual content type, then the OpenAPI spec would be silent about how those are mapped to the JSON Schema data model since it only knows application/json.

**Comment by MikeRalphson** [comment]
The list is of media-types, which as you say apply to `Accept` headers as well as `Content-Type` so I don't necessarily see why this would be confusing. The `requestBody` has a `content` object with media-type keys.

> even if those media types were used as actual content type, then the OpenAPI spec would be silent about how those are mapped to the JSON Schema data model since it only knows application/json.

As per https://github.com/OAI/OpenAPI-Specification/issues/2349#issuecomment-693242791 this interpretation is not correct. Where in the specification do we state that we "only know [about] `application/json`" ?

I'm not saying the specification can't be improved in this area (PRs are always welcome) but perhaps we can close one of these issues and concentrate on wording improvements?
