### ISSUE TITLE
Download pdf and excel is giving empty content

### ISSUE THREAD

**Issue by saravanavel891** [OAI/OpenAPI-Specification#2354]
We are using openapi as middle layer between Java REST API and Client.

Request flow: Client -> OpenAPI -> JAVA REST API
Response flow: JAVA REST API -> OpenAPI -> Client

When we hit Java API directly in browser valid document is getting downloaded. Below are the headers we are getting from **Java response**.

Content-Disposition: attachment; filename="Test.pdf"
Content-Type: application/octet-stream

When we try to get the content through OpenAPI it is giving empty file. Below are code which is writing the response in openAPI.

**Code:**
```java
res.writeHead(200, {
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': 'attachment; filename="Test.pdf"'
      });
      res.write(data, 'binary');
      res.end();
```

**Swagger Response Configuration:**

        "responses": {
          "200": {
            "description": "Successful request.",
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "string", "format": "binary"
                }
              }
            }
          }
}

Can someone help us to identify the problem here?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
