### ISSUE TITLE
Clarify the relationship between OpenAPI 3.1 and the JSON Schema version

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2363]
The current 3.1 spec says,

> The Schema Object allows the definition of input and output data types. These types can be objects, but also primitives and arrays. This object is a superset of the JSON Schema Specification Draft 2019-09.

We should agree on wording to clarify that future versions of JSON Schema (assuming non-breaking) are also usable with OpenAPI 3.1. (wordsmithing required)

In order to achieve forward compatibility with JSON Schema, we need to define the OpenAPI keywords as a vocabulary.  And define how the OpenAPI vocabulary is applied to the JSON.

**Comment by darrelmiller** [comment]
Wait to see if JSON Schema 2020 makes it out to meet our schedule.  We can decide on wording at the last minute.

**Comment by MikeRalphson** [comment]
#2399 is merged.
