### ISSUE TITLE
How to execute the generated files?

### ISSUE THREAD

**Issue by shahidkarimi** [OAI/OpenAPI-Specification#2367]
Ok, everything went fine. But I did not find a way to view the doc in the browser. How to do that?

**Comment by MikeRalphson** [comment]
This sounds like a tooling issue rather than an issue with the specification. Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
