### ISSUE TITLE
Open TSC Meeting, Thursday 08 October 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2368]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Approve 3.1rc1 release notes | @webron | Ship It.  Send email to members to try rc1.  Call it "implementers draft" in email. Ask for feedback before Nov 8th. |
AOB (see below) | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=org%3Aoai+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by Relequestual** [comment]
"Important announcement!"
