### ISSUE TITLE
Allow override of $ref parameter min /max /default values

### ISSUE THREAD

**Issue by savage-alex** [OAI/OpenAPI-Specification#2372]
I am referencing a shared parameter from an external file. (In this situation it is offset and limit query parameters for pagination)
It would be really useful to be able to override their min, max and perhaps even default values within the operation that references them as they would ideally be tuned per collection:

![image](https://user-images.githubusercontent.com/25430683/95713911-3f65e180-0c5f-11eb-8eac-d56d2f3d4511.png)

Is that something that would interest people?

**Comment by MikeRalphson** [comment]
The `minimum` and `maximum` properties of a `parameter` object are held within the `schema` property. This would mean in OAS 3.1+ we would have to allow `schema` as a sibling to a `$ref`. The JSON Schema folks have taught us that merging schemas is a difficult process. This is not a "no", just a little background.

**Comment by savage-alex** [comment]
Thanks Mike for the speedy response. For now my guidance is: Ref a parameter from a shared domain. Live with the min and max that it has. Will stick with that.
