### ISSUE TITLE
Improved Discriminator documentation

### ISSUE THREAD

**Issue by ferologics** [OAI/OpenAPI-Specification#2376]
I think that the discriminator syntax could be clarified by giving specific examples of the output JSON. 
The **how a discriminator is defined** confuses the **what it resolves to**. (This is partially due to the nature of how the schema reads.)

The most common confusion being whether the schema from #2143 ([link to comment](https://github.com/OAI/OpenAPI-Specification/issues/2143#issuecomment-659551578)):

```
{
  type: 'object', // required!
  required: ['objectType'], // also required!
  discriminator: { propertyName: 'objectType' },
  oneOf: [{
    properties: { objectType: { const: 'obj1' } },
    $ref: '#/components/schemas/Object1'
  }, {
    properties: { objectType: { const: 'obj2' } },
    $ref: '#/components/schemas/Object2'
  }, {
    properties: { objectType: { const: 'system' } },
    $ref: 'sysObject.json#/sysObject'
  }]
}
```

Dose the schema resolve to:
1. `{ "obj1" : { properties... } }` or to
2. `{ "objectType" : "obj1", properties... }` and I've seen
3. `{ "objectType" : "obj1", "properties": { properties... } }` as well

These are ambiguities that can be clarified easily by adding more schema examples JSON to the [discriminator documentation](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#discriminator-object). Of coarse the correct JSON schema is possible to figure out with a little bit of plug and play but it's not a straightforward process per se. As it stands I have spent a few days looking into the discriminator syntax and I'm still a little bit puzzled as to what is the EXACT resolved JSON from the above defined schema spec.

I think that what the documentation is really missing is a few **counter examples of how the schema should NOT look like**. So in the case of the above example we could add:

```diff
+ valid: `{ "objectType": "obj1", properties... }`

- invalid: `{ "obj1" : { properties... } }`
- invalid: `{ "objectType" : "obj1", "properties": { properties... } }`
```

And though I understand that the specification might be clear to some people, it is not to the newcomers.

**Comment by handrews** [comment]
@ferologics if you are still interested in this, it's not clear to me what you mean by what the schema "resolves to."  Are you talking about how those adjacent `$ref` and `properties` keywords work if you try to remove the references?  If so, that is purely a JSON Schema thing and not specific to `discriminator`.
