### ISSUE TITLE
missing fully functional example code on how is actually being used

### ISSUE THREAD

**Issue by aeonSolutions** [OAI/OpenAPI-Specification#2377]
Hi,
the website is all good for those who have time to have a good read and digest it for a while.
imho is missing code snipets in the most common programming languages such as java, c#, php, ...

more,  is missing here on github full mobile app / desktop  : android / IOS / windows / MacOs/ Linux  than can enable the possibility of copy&paste and providing a #boost to new developers !!! it does not need to be a too elaborate App, ust to showcase the core functionalities while displaying data on a screen .

#KISS #FORDUMMIES

**Comment by MikeRalphson** [comment]
Thanks for the issue. As the OAI publishes only the specification, and not any tooling, it would be difficult for us to include code-samples (and keep them up to date) without knowing which tooling our consumers are using. Plus the specification is only of limited use to tooling until it is given an OpenAPI document to consume or instructions to produce one.

Production of a mobile or desktop app (with whatever functionality) is outside the scope of this repository and the charter of the OAI.

**Comment by aeonSolutions** [comment]
Hi
i get what you're saying. But it sounds, at least to me, as an excuse than rather an opportunity to facilitate coders on developing custom APPs using the API by shortening immensely the time needed to study how to implement the API it self into their APPs.

In regards to maintain the code, is not also a huge question, if, and only if, you provide on code smaples using vanilla variants of the most common languages, which are 
-  android(java)
- C#
- PHP
- SWIFT

tell you something. Send me one of them, for instance, android and i'll upload in the other languages
what do you say ?

**Comment by MikeRalphson** [comment]
It is **not** an excuse. Please consider that the *volunteers* here also have enough on their plates with the current scope.

This organisation publishes a specification for writing API descriptions, every description would have different generated code. There are already multiple projects in the code-generation and documentation space which generate or show code samples based on entire OAS documents or portions of them. See https://apis.guru/awesome-openapi3/category.html#sdk https://apis.guru/awesome-openapi3/category.html#documentation

If you feel you have identified a gap in the OAS tooling world, be lucky in exploring it.

**Comment by aeonSolutions** [comment]
get out of town dude.

i'm offering my help. and you give me that answer. !!!
come'ón.... you can do a lot better!
