### ISSUE TITLE
Json Schema draft compatibility limit

### ISSUE THREAD

**Issue by tomsfernandez** [OAI/OpenAPI-Specification#2382]
Hi! is there an upper and lower bound to which json schema drafts can be used from an OAS 2.0 or OAS 3.0?

Thanks!

**Comment by MikeRalphson** [comment]
`schema` objects in OAS 2.0 are an extended subset of [JSON Schema draft 4](http://json-schema.org/specification-links.html#draft-4). In OAS 3.0.x they are an extended subset of [JSON Schema draft Wright-00, aka draft 5](http://json-schema.org/specification-links.html#draft-5).

There is no mechanism for using other JSON Schema drafts as a base for schema objects in these OAS releases.

In OAS 3.1, schema objects will be entirely compatible with JSON Schema draft 2019-09 or the upcoming draft 2020-XX. See the OAS 3.1 RC release notes for more details.

**Comment by tomsfernandez** [comment]
So I can only reference draft 4 json schemas from an OAS 2.0 API?

**Comment by MikeRalphson** [comment]
Yes, whatever schema you `$ref` from an OAS 2.0 document will be interpreted as OAS 2.0 schema objects, which are based on JSON Schema draft 4.

**Comment by MikeRalphson** [comment]
Closing after a week, but feel free to continue the conversation if necessary and we can re-open.
