### ISSUE TITLE
String data type accepts boolean and integer values.

### ISSUE THREAD

**Issue by Parkerkent** [OAI/OpenAPI-Specification#2383]
Declaring any attribute as String type in the request payload is accepting boolean (0,1,true,false) and any integer (22,3).
It's converting the boolean and integer values into string and then creating the request body.

The above scenario is tested in OAS 3.0 and which I feel not valid.
Is there any fix available for this?

**Comment by MikeRalphson** [comment]
You say you have tested "it" which leads me to think this is a tooling-related issue. Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by Parkerkent** [comment]
Thank you!
