### ISSUE TITLE
new.api.gh

### ISSUE THREAD

**Issue by koenbnl** [OAI/OpenAPI-Specification#2396]
![image](https://user-images.githubusercontent.com/26348249/98184047-b9f5ea00-1f09-11eb-8fda-5ef1fa7ca3e7.png)

**Comment by koenbnl** [comment]
# Search StackOverflow for selected text

import editor
import webbrowser

text = editor.get_text()
s = editor.get_selection()
selection = text[s[0]:s[1]]
if len(selection) > 0:
	from urllib import quote
	q = quote(selection)
	search_url = 'http://stackoverflow.com/search?q=' + q
	webbrowser.open(search_url)
else:
	from console import alert
	i = alert('No Selection', 'Do you want to open the StackOverflow homepage?', 'StackOverflow')
	if i == 1:
		webbrowser.open('http://stackoverflow.com')

**Comment by MikeRalphson** [comment]
Do you have a question?
