### ISSUE TITLE
Support Messaging/Event Object

### ISSUE THREAD

**Issue by DanielYWoo** [OAI/OpenAPI-Specification#2410]
In a real application, event schema is as important as APIs. Open API does a great job on REST APIs, but we also want to define schema for events.

To do that, we need some concepts: 

1) message: including the headers and payload. I think we can reuse the component.schema to represent message.
1.1) type: a unique name of the message type
1.2) headers: AMQP or Kafka headers, including the schema type (e,g. JSON or AVRO), maybe routing keys for AMQP.
1.3) properties: the actual payload schema.

2) topic(queue), a unique name with some properties.
2.1) name: the unique topic name
2.2) properties: including some properties of the topic like durability, etc. Depends on the actual implementation.
2.3) message_types: referencing what kind of messages (component.schema) can be queued in this topic.

what do you think?

**Comment by MikeRalphson** [comment]
Have you seen https://www.asyncapi.com/ ?

**Comment by DanielYWoo** [comment]
@MikeRalphson yes, but I am still confused with the scope of OpenAP spec, do you have intention to support messaging? Or it's out of scope and we just leave it to the AsyncAPI?

**Comment by MikeRalphson** [comment]
Though the [OAI charter](https://www.openapis.org/participate/how-to-contribute/governance) allows for the development of specifications other than the OpenAPI Specification, the scope of OAS is HTTP and HTTP-like APIs.

Things can change, but the AsyncAPI folks are doing a fine job, and I personally don't see much value in duplicating that effort or folding the two specs into one, which will just add huge chunks you need to skip depending on whether you are implementing an HTTP API or a messaging API.

**Comment by DanielYWoo** [comment]
I just kind of hope we have one spec and one set of supporting libraries like springfox, anyway, you are right, let's have both. Thanks, Mike.
