### ISSUE TITLE
Paths Object missing explicit Reference Object to allow referencing of Path Items

### ISSUE THREAD

**Issue by AgustinBettati** [OAI/OpenAPI-Specification#2412]
Within [Paths Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#paths-object) it appears that it is not possible to reference Path Items defined in components or external files. 

If this is not intentional, the possibility of using a Reference Object should be added as defined in [Callbacks](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#callback-object), as well as webhooks in [OpenAPI Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#openapi-object)

**Comment by miqui** [comment]
@AgustinBettati  - can you provide an example?

**Comment by AgustinBettati** [comment]
This would be an example of the use case i am mentioning:
```
components:
  pathItems:
    petsPathItem:
      get:
        description: Returns all pets from the system that the user has access to
        responses:
          '200':
            description: A list of pets.
            content:
              application/json:
                schema:
                  type: array
paths:
  "/pets":
    "$ref": "#/components/pathItems/petsPathItem"
```
If this seems like a logical use case, it should be reflected in specification modifying the type defined in Paths Object to '_Path Item Object | Reference Object_'. I can create the PR if needed.

**Comment by orubel** [comment]
Technically, any endpoint can be a HOOK so this is a bit redundant. Literally you would just have to add a boolean (ie Hook: true) to the endpoint to define it as such or a list of ROLES that could access it as such.

**Comment by MikeRalphson** [comment]
The `pathItem` object has a [fixed field](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#fixed-fields-7) called `$ref` (which has subtly specific rules which make it **not** a `referenceObject`). Because of this, your example is already valid.
