### ISSUE TITLE
Open TSC Meeting, Thursday 03 December 2020

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2414]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Code of Conduct PR #2416 | @MikeRalphson / @OAI/tsc | |
| Respond to "break semver once" issue | @pimterry | |
AOB (see below) | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=repo%3Aoai%2Fopenapi-specification+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by Relequestual** [comment]
JSON Schema 2020-12-rc-1.
It's the last RC.
https://json-schema.org/work-in-progress
We plan to publish on 2020-12-08.

Please read and feedback ASAP if you haven't already.
