### ISSUE TITLE
URL for schema v3.0 no longer served

### ISSUE THREAD

**Issue by merkys** [OAI/OpenAPI-Specification#2420]
It seems that the URL for schema v3.0 is no longer served: https://spec.openapis.org/oas/3.0/schema/2019-04-02. Is this intentional?

**Comment by MikeRalphson** [comment]
That schema identifier is a URI not a URL. It has never been available at that URL. The schema is available at https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json

**Comment by merkys** [comment]
Got it, thanks!

**Comment by akuckartz** [comment]
Forwarding should be possible.
