### ISSUE TITLE
validating openAPI spec with reusable requestBodies gives "should be object" error

### ISSUE THREAD

**Issue by mewalig** [OAI/OpenAPI-Specification#2427]
The below spec, as far as I can tell, conforms to OpenAPI 3.0.3 per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#requestBodyObject.

However, trying to validate at https://editor.swagger.io/ yields the following error at the line containing '$ref'. 

```
Structural error at paths./test.put.requestBody
should be object
```

Here's the spec. What am I doing wrong?
```
openapi: 3.0.3
info:
  version: 1.0.0
  title: request body test
  
components:
  requestBodies:
    myRequestBody:
      description: request body
      content:
        application/json:
          schema:
            type: object

paths:
  /test:
    put:
      summary: put test
      requestBody:
        - $ref: '#/components/requestBodies/myRequestBody'
      responses:
        200:
          description: OK
```

![image](https://user-images.githubusercontent.com/8260442/102522871-d3d83000-4064-11eb-8390-b930cfe86971.png)

**Comment by MikeRalphson** [comment]
You have a stray hyphen, causing the $ref to be treated as being within an array.

**Comment by mewalig** [comment]
Oh my, feeling very dumb. Thank you!!
