### ISSUE TITLE
How do i pick the anyOf sub schema to use in an existing hierarchy of object based on whether it is in request or response property of the endpoint

### ISSUE THREAD

**Issue by tzejun** [OAI/OpenAPI-Specification#2428]
Hi, i have a question which i would like to seek enlightenment. 

I have an endpoint documented in OAS 3.0 

like for example: 

/endpoint1 

1. this endpoint has both a request and response.
2. the request body and response body both takes in a schema where there are sub components  which make up the schema.

Here is the example: 
For the request schema we have Schema Payment, which inherits allOf "BasePayment" schema. Within the "BasePayment schema" there is a property called "Credit" which uses the allOf "Credit schema". Within the Credit Schema, there is another property called beneficiary, which takes in oneOf "structured" and "unstructured" schema. 

This is used in both the request and response schema as BasePayment is the schema used by both of these endpoints.
My problem is, if i define the required property in the "structured" schema, this required field will be present in both the request and response. I do not want the required property to be in the response schema. 

I have then written a new schema "structuredResponse", on top of "structured" which does not include the "required" property. 

How can i control which beneficiary to use in the request and response endpoints so i can choose to use "structuredResponse" in the response tag of the endpoint, without duplicating a similar set of the hierarchy of objects defined above, specially for the response ?

**Comment by handrews** [comment]
@tzejun if this is still of interest, I _think_ that what you are trying to do here can be done in OAS 3.1 with [dynamic references](https://json-schema.org/blog/posts/dynamicref-and-generics), which allows changing an internal structure within an envelope or container.  Although I might be misunderstanding your question.
