### ISSUE TITLE
webhook need a paths?

### ISSUE THREAD

**Issue by christianfds** [OAI/OpenAPI-Specification#2430]
I was reading the changelog of the 3.1.0-rc0 and it says:
``While previous versions required paths, now a valid OpenAPI Document can describe only webhooks, or even only reusable components. Thus, an OpenAPI Document no longer necessarily describes an API.``

But on the file examples/v3.1/webhook-example.yaml it states that:
``OpenAPI documents all need a paths element``

 So can i have a openapi only with a ``webhooks`` in it?

**Comment by MikeRalphson** [comment]
The release notes are correct, the `webhook-example.yaml` file was created before that change was proposed and merged. Good spot! Would you like to raise a PR to fix the example?

To confirm the answer to your question, yes you can have an OpenAPI document with only `openapi`, `info` and `webhooks` in it.
