### ISSUE TITLE
Support for AsyncAPI spec?

### ISSUE THREAD

**Issue by jkbpvsc** [OAI/OpenAPI-Specification#2431]
Are there any plans to support the [AsyncAPI](https://www.asyncapi.com/) spec within OpenAPI?

The AsyncAPI spec is attempting provide the same utility as OpenAPI for systems build on event/messaging driven architecture.

Since asynchronous messaging is an important and common communications model in modern systems architecture, there is a need for standardised documentation of API interfaces.

Regards, JP

**Comment by MikeRalphson** [comment]
The AsyncAPI specification is complementary to the OpenAPI specification. There are no current plans to merge the two.

**Comment by jkbpvsc** [comment]
Thanks you for the fast response!

cc @ctomc
