### ISSUE TITLE
Query String in Paths

### ISSUE THREAD

**Issue by EmDee** [OAI/OpenAPI-Specification#2438]
The spec doesn't seem to define, if query strings are allowed in paths or not.

According to the [docs](https://swagger.io/docs/specification/paths-and-operations/) on swagger.io (section `Query String in Paths`) this is not allowed.

There are some related issues that doesn't seem to have a definitive answer either, e.g. https://github.com/OAI/OpenAPI-Specification/issues/123.

Are there official specs regarding this problem?

**Comment by darrelmiller** [comment]
The phase path is based on the [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.3) definition.  Therefore, paths can't contain query parameters.

**Comment by EmDee** [comment]
Is this something that should be made more explicit in the specification?

When reading the specification regarding the [paths object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#paths-object) it states `Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical.` which would be the case for paths which only differentiate in their query params, however, the next sentence states `In case of ambiguous matching, it's up to the tooling to decide which one to use.` which seems to nullify the previous sentence or am I misunderstanding this?

**Comment by SteveNay-vz** [comment]
I think you're overlooking the distinction between paths and query strings, which is pretty explicit in RFC3986. The path stops where the query string starts; even if a request contains query strings, they are not considered part of the path. The description of the paths object in the specification is about paths only; it should not be understood to apply to query strings at all.

Your statement about "paths which only differentiate in their query params," confuses the two concepts. Two paths which only differentiate in their query params would be one and the same path, not two different paths.

**Comment by MikeRalphson** [comment]
> which would be the case for paths which only differentiate in their query params

In

> Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical.

The key word is **templated**. The guidance refers to paths such as `/users/{name}` and `/users/{id}`.

Closing, as the spec currently as written conveys the intent.
