### ISSUE TITLE
Supporting properties only for read or write

### ISSUE THREAD

**Issue by shenji** [OAI/OpenAPI-Specification#2440]
What is the best way to support properties such as _id or createAt that should only exist in GET but never POST.

**Comment by hkosova** [comment]
You can define such properties as `readOnly: true`. There's also `writeOnly` for write-only properties.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#user-content-schemareadonly

**Comment by MikeRalphson** [comment]
Thanks @hkosova exactly right. Please also note that in the upcoming 3.1 release, we have the notion of *annotations* inherited from JSON Schema, and the interaction between `readOnly` / `writeOnly` and the `required` keyword will no longer apply.

Please chase if this doesn't resolve your issue.
