### ISSUE TITLE
Please provide json examples in addition to yaml in the documentation

### ISSUE THREAD

**Issue by jimshowalter** [OAI/OpenAPI-Specification#2445]
Not everyone is a YAML shop, and we wind up having to copy/paste the yaml into an online converter to get the corresponding json.

You could have tabs like Gradle has for groovy vs. kotlin: https://docs.gradle.org/current/userguide/multi_project_builds.html

**Comment by MikeRalphson** [comment]
Can you clarify where you mean by "in the documentation". I *think* in the spec. itself each yaml example block has corresponding json one, and we automatically create `.json` versions of the `.yaml` files in the `/examples` folder.

Personal note: all OAS tooling should accept both YAML and JSON documents to comply with the spirit of the spec.

**Comment by jimshowalter** [comment]
Apologies. It must have been some documentation I thought was part of the formal spec.
