### ISSUE TITLE
Add support for templatedRef in Reference Object

### ISSUE THREAD

**Issue by jerstlouis** [OAI/OpenAPI-Specification#2453]
Proposing to add support for "$templatedRef" to Reference Objects supporting templated references, allowing referencing dynamic schemas that could be retrieved by substituting the template variables by the selected value for earlier path parameters
so that later path parameters can be defined differently based on earlier path parameters.

Example:
```
  "parameters" :
   {
      "collection-styleId" :
      {
         "name" : "styleId",
         "schema" :
         {
            "$templatedRef" : "./api/collections-styles/{collectionId}"`
         }         
      }
   }
```

As it was initially suggested that this would require to first extend JSON schema, an initial discussion took place in https://github.com/json-schema-org/json-schema-vocabularies/issues/36 . However reading on https://swagger.io/specification/ that the Reference Object is defined by the [JSON Reference](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03), rather than by JSON Schema, it seems that this could rather simply be extended with`$templatedRef`, following https://tools.ietf.org/html/rfc6570 (or a simpler subset of it).

The `{collectionId}` template would be replaced by a selected value like `collection1`.
(e.g. in this example, this "$templatedRef" is used to define the valid values for `{styleId}` in a path `/collections/{collectionId}/styles/{styleId}`).

The `{collectionId}` would have previously been validated against another potentially dynamic list like `"$ref" : "./api/collections"`.

`./api/collections` would return something like:
```
{
   "type" : "string",
   "enum" : [
      "collection1",
      "collection2",
      "collection3"
   ]
}
```
and `./api/collection-styles/collection1` would return something like
```
{
   "type" : "string",
   "enum" : [
      "style234",
      "style235",
      "style236"
   ]
}
```
while `./api/collection-styles/collection2` would return something like
```
{
   "type" : "string",
   "enum" : [
      "style454",
      "style455",
      "style456"
   ]
}
```
The context being that available/compatibles styles depend on the selected collection.

Such a capability would allow to define much more interoperable APIs, where the specifics of a particular instance / deployment would be left to the templated references. In turn this would allow to automatically generate clients from an API definition that will work with multiple instances of the same templatable API, therefore extending the usability of clients automatically generated from OpenAPI definitions beyond on-the-fly client generation, more suitable for compiled programming languages.

**Comment by handrews** [comment]
As of OAS 3.1, this pattern [can be implemented with JSON Schema's `$dynamicRef`](https://json-schema.org/blog/posts/dynamicref-and-generics) in Schema Objects.  I think that means this can be closed as resolved, please comment if not.

**Comment by jerstlouis** [comment]
@handrews Please correct me if I'm wrong, but I don't believe `$dynamicRef` addresses my use case at all.

I want a **single path** that can have two parameters, e.g. `{collectionId}` path parameter and `properties` query parameter, and I want the ability to define the valid values with an enum for properties based on the value that the user selects for `{collectionId}` in a drop down.

Ideally, this would even support a network fetch of an enum from e.g. `/api/valid-properties-per-collection/{collectionId}` as a result of the user changing the value of the drop-down (so that this would work well with thousands of collections).

But a first step would be for this to work by prefetching a map of collectionId -> properties with a `$ref` from `/api/valid-properties-per-collection`.

I don't think `$dynamicRef` makes either of those use cases possible?

Thank you!

**Comment by handrews** [comment]
@jerstlouis ah, I see- yes, `$dynamicRef` does not support this, but I think this is well outside of the scope of what we would do here.  Adding requirements around network interactions and dynamic UI seems like a dramatic expansion of scope to me.  But I'll leave this open so @OAI/tsc can weigh in.

**Comment by jerstlouis** [comment]
Thank you @handrews .

>  Adding requirements around network interactions and dynamic UI seems like a dramatic expansion of scope to me. 

For the first use case (a pre-fetched map of collectionId -> properties), the entire thing can still be resolved only once at loading, so no network interactions are needed, and the dynamic UI is something for the tools to implement rather than OAS.

For the second use case (thousands of collections), what would be needed is the ability to re-evaluate (including re-evaluating those templatized references) by resolving again (and re-fetching the new references). The tools would also need to support this in terms of dynamic UI, and explicitly invoking the re-evaluation of the active path of course.

For me, this seems like an absolutely essential/basic capability for APIs with paths having more than a single path parameter.

**Comment by handrews** [comment]
@jerstlouis if you see a good way to do this with new fields, one option you might consider is [registering an extension](https://spec.openapis.org/registry/extension/) and lobbying tool providers to support it.  Extensions that see real-world use are much more likely to become adopted in some form in the future (I believe webhooks and tag kinds/parents both started as extensions, for example).

But note also that while the Reference Object (and the `$ref` in the Path Item Object) is under the control of OpenAPI, `$ref` in JSON Schema is under the control of JSON Schema, recently revived at the IETF with a [new draft](https://www.ietf.org/archive/id/draft-dusseault-json-schema-00.html), although that document does not change functionality from the currently-used draft 2020-12.  It does indicate that JSON Schema is once more active under the auspices of the IETF, though.

**Comment by jerstlouis** [comment]
Thanks @handrews .

Related to JSON Schema, I think it would need to be a new keyword like `$templatedRef`.

I had opened that separate related issue on json-schema.org:

https://github.com/json-schema-org/json-schema-vocabularies/issues/36
