### ISSUE TITLE
Limiting OAS3.1 to RFC7231 status codes?

### ISSUE THREAD

**Issue by ioggstream** [OAI/OpenAPI-Specification#2471]
## I expect

To reference all registered status codes

## Instead

The spec says

> The available status codes are defined by RFC7231

## Note

It is not clear  to whether the current formulation limits the available status codes to the one in 7231

**Comment by philsturgeon** [comment]
What else would it mean? You can use any status codes defined in RFC 7231. Using custom status codes is undefined and therefore undefined behavior is to be expected.

Was there a particular status code you were looking to use thats not in 7231 or are you trying to use custom codes? 

For extra context, the JSON Schema validates the following:
```
patternProperties:
          '[1-5](?:\d{2}|XX)':
```

So you could go using custom status codes if you wanted to, but if its outside of those rules some validators will barf errors at you.

**Comment by ioggstream** [comment]
429 status code is rfc6585, but not in 7231 ;) 

I'm just saying that there are http-extensions beyond 7231 and they are standards too.

**Comment by hkosova** [comment]
OAS refers not only to RFC 7231 but also to the IANA registry:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#http-status-codes
> **HTTP Status Codes**
> The available status codes are defined by [RFC7231](https://tools.ietf.org/html/rfc7231#section-6) and registered status codes are listed in the [IANA Status Code Registry](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml).

RFC 7231 itself [points to](https://tools.ietf.org/html/rfc7231#page-50) the IANA registry for the complete list of codes:

>  Note that this list is not exhaustive -- it does not include extension status codes defined in other specifications.  The complete list of status codes is maintained by IANA.

<br/>

Maybe the intended meaning here is that _definition_ of "HTTP status code" is taken from RFC 7231 (i.e. it's a 3-digit integer in the 100-599 range), and for specific registered status codes the reader should refer to the IANA registry?

**Comment by philsturgeon** [comment]
@hkosova sounds good!

**Comment by ioggstream** [comment]
@hkosova exactly, the text just need a slight rewording. Feel free to PR with your text... or I'll do it tomorrow if you don't have time.

**Comment by MikeRalphson** [comment]
@ioggstream @hkosova woudl one of you like to take a go at that proposed PR?

**Comment by ioggstream** [comment]
The httpwg is  releasing the new http spec. I will create a PR next week but we could even wait for the new spec to be released so that we have the latest references.

**Comment by MikeRalphson** [comment]
#2630 was merged. Thanks all.

**Comment by ioggstream** [comment]
@MikeRalphson sorry for the delay. The PR is ok. Thanks!
