### ISSUE TITLE
additionalProperties at a composed schema level, interpretation guidance for v3.0.0 spec?

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#2478]
Hi there,
I am unsure of how to interpret this v3.0.0 specification and would appreciate expert guidance.
Given this spec:
```
    ShapeInterface:
      properties:
        shapeType:
          type: string
      required:
        - shapeType
    TriangleInterface:
      properties:
        triangleType:
          type: string
      required:
        - triangleType
    IsoscelesTriangle:
      allOf:
        - $ref: '#/components/schemas/ShapeInterface'
        - $ref: '#/components/schemas/TriangleInterface'
      additionalProperties: false
```
additionalProperties is True by default in ShapeInterface + TriangleInterface
but we set it to False in IsoscelesTriangle

Some questions:
1. Is this a valid spec?
2. Will validating this payload as an IsoscelesTriangle succeed?
```
{
    'shape_type': 'Triangle',
    'triangle_type': 'EquilateralTriangle',
    'unknown_property': 'a-value'
}
```
3. If validation will not succeed then this also has implications to validating oneOf/anyOf composed schemas, right? First one would need to validate to all oneOf/anyOf schemas, then if additionalProperties is False at the composed schema level only, one would need to check that all the assigned properties exist as properties in the chosen oneOf/anyOf schemas.

**Comment by MikeRalphson** [comment]
I believe this question has been [asked](https://json-schema.slack.com/archives/C5CF75URH/p1613937923034800) and answered on the JSON Schema slack. Let me know if not and we can re-open.

**Comment by spacether** [comment]
From Slack the answer is
additionalProperties only operates at the schema level where it's located. Because there is no properties (or patternProperties) keywords defined in IsoscelesTriangle, there is no data that can validate against that schem
