### ISSUE TITLE
Open TSC Meeting, Thursday 25 February 2021

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2480]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Presentation on the SLA4OAI working group progress | @pjmolina | |
| Post 3.1 [ancillary](https://github.com/OAI/OpenAPI-Specification/milestone/9) milestone items | @OAI/tsc | |
AOB (see below) | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=repo%3Aoai%2Fopenapi-specification+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by kadeatfox** [comment]
Hello,

Can we please discuss the "Links" topic again? I have a write up about why it's important to include this feature here: 
#1594

**Comment by luckybroman5** [comment]
Hello,

It looks like was previously discussed however I'm not sure what the outcome was. Might we re-address the "Links" suggestion here: #1594 ?

I have left a detailed comment as to _why_ this is needed that also includes common and practical use cases.

Thanks!

**Comment by kadeatfox** [comment]
I second what @luckybroman5 is asking here. What he/she suggests applies to a lot of use cases I have came across, and he/she brings up great points

**Comment by sabs231** [comment]
I agree with @luckybroman5 he/she brings some interesting point that is worth considering

**Comment by hectorivanramos** [comment]
I also agree with @luckybroman5 he/she have good arguments to consider

**Comment by MikeRalphson** [comment]
I'm not sure we will definitely get to it this week, as, as above, we have a presentation from the community and there will be related discussion.

When we come to discuss the shape of 3.2 this would be an excellent topic, among many, to focus on.

**Comment by kadeatfox** [comment]
> I'm not sure we will definitely get to it this week, as, as above, we have a presentation from the community and there will be related discussion.
> 
> When we come to discuss the shape of 3.2 this would be an excellent topic, among many, to focus on.

Thanks @MikeRalphson,

What was discussed about that issue during the previous TSC meeting? I'm also looking around the docs, and aside from seeing your calendar, I can't seem to find the timeline for when you're going to discuss items for 3.2.

Additionally, how might I go about about raising this topic further up the list of priorities?

Thank you kindly.

**Comment by dlombard-fox** [comment]
Based on my experience, I think that it could be a good idea to consider the issues @luckybroman5 raised because due to practical issues with such an implementation, at best, some may avoid using Links within their specification otherwise.

**Comment by Relequestual** [comment]
Hey all. Agenda item:
The JSON Schema team have some questions regarding `discriminator`, especially the language.
I appreciate I should have pushed others to review, but I know I personally didn't have time to review the whole spec! =D

It's a fair long list, and I'll try to pick out what I think are the key questions before the meeting.

These questions are coming from the first two 2020-12 implementers and members of the core team.

**Comment by MikeRalphson** [comment]
@relequestual can we bump that to next week please?

**Comment by Relequestual** [comment]
> @Relequestual can we bump that to next week please?

Yeah, I haven't been able to compile the list today, and I might have to skip this week anyway.

**Comment by MikeRalphson** [comment]
[Recording](https://zoom.us/rec/share/B5Sh_bOG1A6XiEhdLpDV2X0-BgQ6AhbJw1ak_pWxEXccSpfzqXZabyMvenfcYRTa.fuG3pQ0xkui5npbq) of this week's call for those unable to attend.
