### ISSUE TITLE
Community (TDC) Meeting Agenda backlog

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2482]
@OAI/tsc please add items here for future discussion.

| Topic | Owner | Date Discussed/Issues/PRs - recording link |
|-------|---------|---------| 
| Presentation on SLA4OAI work | @pjmolina | [2021-02-25](https://zoom.us/rec/share/B5Sh_bOG1A6XiEhdLpDV2X0-BgQ6AhbJw1ak_pWxEXccSpfzqXZabyMvenfcYRTa.fuG3pQ0xkui5npbq) |
| `links`, backlinks and `requestBody` properties #1594 | @mkistler / @luckybroman5  | 2021-03-04 |
| `overlays` | @darrelmiller  / @MikeRalphson | [2021-04-01](https://zoom.us/rec/share/-Ag8u6petOu81MylA7gaf2lqbhPrbSTYDQmmSzur3fjErB6Yq6yje_RWqeHkJBlF.qV1qPdBZhNbDNp8G) / 2021-04-22 |
| "Housekeeping" of existing issues | @webron | 2021-04-15 |
| Codegen vocabulary #2542 | @mkistler | 2021-04-22 |
| Big list of post 3.1 possibilities | @earth2marsh | [2021-05-13](https://zoom.us/rec/share/gE8_RTtptKjX3GQu72Sf9RMLkahc9EAUNVQU969OpWBxFpbMjnb-lqSZAU7RzhG0.16eS8fiv83S9IgOA) |
| `discriminator` deprecate or improve? | @Relequestual  / @philsturgeon | [2021-05-20](https://zoom.us/rec/share/4Td9Ir4-t2Se4taUAXTMqx1X_H3hR-n8WoF-_o3CIhfXZIi2nWeOngeaD9hdhgK4.gkQkbGwBWqYDTvC8?startTime=1621526294000) |
| `format` and extension registry | @MikeRalphson | [2021-05-27](https://zoom.us/rec/share/HXwIyRdbKwMcbFrJL0ZhEpsUblEtT5Qi_C0gs4Ky6XUn-3LZ9jy8Lx4Bf8rJlx6R.E0BqVi9l_te9weam?startTime=1622131117000)|
Diversity & Inclusion training | @ncaidin | [2021-06-10](https://zoom.us/rec/share/r2-hIafeBPskKI8hD6DEcm_A2lTHGBFd7rHoZkhvrgmR1yrnbs4NIU3eTX80WboE.ZwMydcq18q1mcIwe?startTime=1623340689000)
Discriminator improvements and bundling | TDC | [2021-06-17](https://zoom.us/rec/share/PyrQZsum_R_1LwGHRGZgL7WRNHjHpLPAI8P3Z2AQzaZgIHD8Ds1Srf_iX_u4d7B8.9T7mRNjxbmt3BLCX?startTime=1623945661000)
`$ref` in `pathItem` Objects | @char0n | [2021-07-08](https://zoom.us/rec/share/9re-PjrS-Lk3I2tqotEzVrOWDIW4n8kjBZEiZsDK9lmDg5Vfu1xPnHkQXcX76szD.WmEdpXG4dGO5kYzh?startTime=1625759968000)
Optional and multi-segment path parameters | @darrelmiller | [2021-07-15](https://zoom.us/rec/share/Up1RhSnHWO7ZIcSDq_W_oq96uRUl-4esTXQ8t1IoDDXqsmO080ne4Y2G4bxTctBn.hEw6hYFULG1SQCz-?startTime=1626364647000)
SIG reports and milestone review | @darrelmiller | [2021-07-22](https://zoom.us/rec/share/bGddztDRafJjVe94bvxvnBnzagUS3KEfTkiHDq3ruW-tqspwsRiVJt1xa7rLOvoU.9-Ga7UbftaYcJxzY?startTime=1626969838000)
`discriminator` next steps | @OAI/tsc | 2021-07-29 |
SIG updates, schema PR reviews | @OAI/tsc  | [2021-08-19](https://zoom.us/rec/share/0e9JsSdv_19jiWoEJx734qYTz9XMyl7zBe5W-n5EOZsPpQhM_sqj7VAWtoYWIFs.IrVtox1ctL4MN3Lk?startTime=1629388722000)

Wider TDC, please comment below with items you'd like us to cover on future TDC calls.

**Comment by luckybroman5** [comment]
@MikeRalphson Simply put, that was an amazing presentation. Things were very well thought out, and the feedback was unimaginably intelligent.

For the item you have listed for me and @mkistler above, what sort of preparation work might I do to have a similar conversation around that improvement?

Thank you kindly,

**Comment by MikeRalphson** [comment]
We're not always that focussed, i.e. with a presentation, but any examples you might want to put together of `link` improvements either as new syntax or a proposal/extension would be welcome. It's always good to have something concrete to look at. Sorry we didn't get to introductions this week, we normally give new attendees a bit of floor space at the top of the meetings.

**Comment by luckybroman5** [comment]
@MikeRalphson No problem, I was just glad to listen in. I will work on preparing something such that when the time comes and there is availability we'll be ready.

**Comment by mkistler** [comment]
@luckybroman5 There is a formal "proposal process" that the TSC put together a while back.  I don't see it described in the repo but the basic idea is to create a proposal from this template:

https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/000_OAS-proposal-template.md

The idea is to use the proposal process to get general consensus a feature change before trying to put together a PR to spec itself.  I think this is probably the path we should take with improvements to links.

**Comment by luckybroman5** [comment]
Thanks @mkistler, I am working on putting something together now and will post here when complete, unless you all ready have something?

**Comment by mkistler** [comment]
I had the best intentions to start on this but life got in the way, so I'll gladly yield to you to get things rolling.

**Comment by karenetheridge** [comment]
> @MikeRalphson Simply put, that was an amazing presentation

bummer, I missed it -- was it recorded?

**Comment by MikeRalphson** [comment]
> bummer, I missed it -- was it recorded?

Sorry it's not obvious, see the dated link above or in last week's agenda issue.

**Comment by luckybroman5** [comment]
@mkistler It took me some time, [but here is my proposal](https://github.com/luckybroman5/OpenAPI-Specification/blob/master/proposals/005_RequestBody-Links.md). Any feedback is welcomed from anyone willing to give it.

@MikeRalphson I'm planning on attending the TSC meeting tomorrow, however it's very understandable if it's too late to get this into this week's agenda. When there is time and if desired, I'm happy to go over the [proposal](https://github.com/luckybroman5/OpenAPI-Specification/blob/master/proposals/005_RequestBody-Links.md) whenever the TSC deems fit.

**Comment by mkistler** [comment]
@luckybroman5 Thanks.  This looks like a great "strawman" to get the discussion started.  I do have some feedback and will try to organize my thoughts for today's meeting or, if we don't get to it today, will give feedback directly.

**Comment by josephgardner** [comment]
Is there an updated list of recordings?

**Comment by Saud96525** [comment]
baywet:feature/formats-abstract

**Comment by EllaMartinez1981** [comment]
> @luckybroman5 There is a formal "proposal process" that the TSC put together a while back. I don't see it described in the repo but the basic idea is to create a proposal from this template:
> 
> https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/000_OAS-proposal-template.md
> 
> The idea is to use the proposal process to get general consensus a feature change before trying to put together a PR to spec itself. I think this is probably the path we should take with improvements to links.

**Comment by LasneF** [comment]
@MikeRalphson  , @Relequestual , @philsturgeon 

in this one there is the mentionned of discriminator  , is there any clarification toward 
the statement

discriminator deprecate or improve? 

my personal opinion this should be fully dropped , and push to a json schema concern 
it would be even cleanner to have data modeling in JSon Schema (we could even have think about XSD! ) and keep OAS specification to Path  / Body / header and so on 

this would have also avoid the issue about XML mapping than none of the linter / gateway support (Redocly / Spectral / Vaccum etc) 

https://github.com/Redocly/redocly-cli/issues/1276#issuecomment-1738760467

**Comment by spacether** [comment]
When there is time, can we discuss this issue?
`Proposal: Create new repo for openapi tests, similar to json schema test suite`
https://github.com/OAI/OpenAPI-Specification/issues/3486

**Comment by lornajane** [comment]
Closing this issue since we rarely check it, and it would be better to bring items to the weekly meeting, for whichever week you would most like your suggestion to be discussed.
