### ISSUE TITLE
Support for Reason Phrase in ResponseObject

### ISSUE THREAD

**Issue by cjaccino** [OAI/OpenAPI-Specification#2484]
### Proposal

An additional ResponseObject attribute called `reasonPhrose` to support specifying the status line's reason phrase.

### Explanation
An HTTP response's status line provides a status code (e.g. 201) and a reason phrase (e.g. "Created").  While the meanings are semantically normalized and the status phrases tend to be stable, they can vary.  OpenAPI provides a _description_ field, but no way to specify it.  This creates a small problem when using documentation generators: they often resort to presenting the status code and the description together.  Worse, a long or multi-line description may be presented as if it were the status string.

While this is arguably a tool problem, the author of a doc generator would likely prefer not to assume the value when the spec author could rightly intend to provide a different reason phrase.  

The `x-summary` ResponseObject extension provides a way to set the reason phrase.  More importantly, it unambiguously makes the ResponseObject description field appropriate for long form prose.  However, `x-summary` or `summary` aren't specific about what is being specified, it's just a short description.  While a `summary` attribute may be justifiable on its own merits, `reasonPhrase` is semantically unambiguous.

### Examples

```yaml
responses:
  '201':
    x-summary: Created
    description: |
      A new pet has been created.
      Once created, the pet will require care and feeding.  
      This can be performed using the `/pets/{id}/care` 
      and `/pets/{id}/feed` endpoints.
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string

  '202':
    description: |
      A new pet will be created at some point in the future.
      If you don't want to wait, trying searching for a pet 
      that already exists using `GET /pets?exists=true`.

```
Redoc demonstrates the ambiguity and the opportunity for better handling by having an additional attribute.  As can be seen in the image, the `201` example has associated a reason phrase taken from x-summary, and the description is rendered appropriately where the viewer would expect a description.  `202` shows long-form description placed inline.  By having two separate fields, Redoc is able to articulate both the reason phrase and the description.

![image](https://user-images.githubusercontent.com/31144642/109197495-0e4c0080-776b-11eb-8921-e1dde94b0cd1.png)

**Comment by MikeRalphson** [comment]
Can you expand a little on the benefit of having this additional property? ReDoc (for example) renders a commonly-accepted reason phrase for the various status codes, regardless of whether an `x-summary` or `description` field is present. So does swagger-ui.

Would the presence of a `reasonPhrase` mean that the `response` was only valid if that reason-phrase was sent? How would this work, given that duplicate status-code keys are not allowed in the `responses` object? Or is your use-case more for cases such as i18n?

It's also worth noting this text from [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.1.2):

> The reason-phrase element exists for the sole purpose of providing a
   textual description associated with the numeric status code, mostly
   out of deference to earlier Internet application protocols that were
   more frequently used with interactive text clients.  A client SHOULD
   ignore the reason-phrase content.

and I believe HTTP/2 and QUIC/HTTP3 both drop the reason-phrase entirely. COAP similarly has no such field.

**Comment by cjaccino** [comment]
It's less a matter of functionality.  More about tying up a loose end in OpenAPI's ability to express flexibility that HTTP provides, and also about removing the ambiguity.  There are indeed two text fields to produce values for, but just one attribute (description) from which to draw.   

There would be no ambiguity if generators assumed the standard reason string, as they probably will when working with HTTP 2, 3, and CoAP, but the example image, which matches example openapi objects, demonstrates the ambiguity in practice.  It came from Redoc 2.0.0-rc.50, the latest, and one can make several observations.
* The generator does not assume the value of the reason phrase.
* When provided the _x-summary_ extension, it uses the value for the reason phrase.
* The description field is rendered in a different place.  Instead of rendering inside the green box, it renders underneath, consistent with other description field rendering using the tool

Swagger Editor (and I assume Hub) does not render a reason phrase at all.  And it ignores _x-summary_, as you say.

In terms of having purely informational attributes, _summary_ may be a good precedent.  Adding a summary field doesn't change the interpretation of an object, but it facilitates generation of documents, the short descriptions for operations in test tools, etc.  Likewise, reasonPhrase would be purely for presentation.

> Would the presence of a reasonPhrase mean that the response was only valid if that reason-phrase was sent?

I would expect the client to obey RFC7230 and use only the status code to interpret the semantics of the response.

> How would this work, given that duplicate status-code keys are not allowed in the responses object?

I would imagine no change.  The status code would be the key. 

> Or is your use-case more for cases such as i18n?

Drivers for me are a) to remove the ambiguity for doc generators and b) to support HTTP 1.1's flexibility for this value.  I can't cite drivers for HTTP's flexibility beyond what you've already provided, but support for non-English users may have been one.  Since the reason phrase is pretty much just ASCII, there is limited opportunity for non-English support.

If not _reasonPhrase_, a _summary_ field would also reduce the ambiguity without tying directly to the HTTP feature.

**Comment by ioggstream** [comment]
I quote @MikeRalphson for this issue. Moreover an API MUST NOT be tied to a specific HTTP messaging version (1.1, 2.0, 3.0) because you do not have any guarantee that a proxy does not translate a message to HTTP/2.

I'd avoid to re-state HTTP stuff in your APIs: this would need to be done on every single response...
