### ISSUE TITLE
Minor typo in JWT Bearer Sample

### ISSUE THREAD

**Issue by dslik** [OAI/OpenAPI-Specification#2486]
The JWT Bearer Sample has an extra "," after "bearerFormat": "JWT".

See https://github.com/OAI/OpenAPI-Specification/blame/master/versions/3.0.3.md#L3236

This exists in all 3.x.x specs.

**Comment by ankitaggarwal23** [comment]
@dslik Can I work on this issue, I will fix this typo.

**Comment by dslik** [comment]
Go for it. Note that this typo may exist in multiple revisions of the standard.

**Comment by MikeRalphson** [comment]
Please not we don't alter published versions of the spec. Please wait until we create a branch for 3.1.1 dev.

**Comment by ankitaggarwal23** [comment]
@MikeRalphson Sure!

**Comment by ankitaggarwal23** [comment]
@MikeRalphson and @dslik  Can I work on this issue now.

**Comment by MikeRalphson** [comment]
Again, please wait until there is a dev branch open for 3.1.1

**Comment by ankitaggarwal23** [comment]
Sure Sir

**Comment by ankitaggarwal23** [comment]
@MikeRalphson and @dslik Can I work on this issue now.

**Comment by MikeRalphson** [comment]
Have at it!

**Comment by MikeRalphson** [comment]
@ankitaggarwal23 did you find time to make this edit?

**Comment by handrews** [comment]
PR merged, closing
