### ISSUE TITLE
HTML versions of 3.x.x incorrectly display some "Style Values" examples

### ISSUE THREAD

**Issue by hkosova** [OAI/OpenAPI-Specification#2488]
Compare 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#style-examples
with
https://spec.openapis.org/oas/v3.1.0.html#style-examples

The HTML version displays some characters incorrectly:
* displays `|` as `¦` 
* displays `color[R]=...` as `color\R=...`

The problem is with all 3.x.x HTML versions.

Screenshots:
![image](https://user-images.githubusercontent.com/8576823/109666048-dd5f3780-7b7f-11eb-909b-97e7c2385511.png)

**Comment by MikeRalphson** [comment]
Thanks, the pipe character difference is known about, I'm just struggling to remember what particular issue required the workaround.

I will look into the other issue.

**Comment by MikeRalphson** [comment]
@hkosova could you check https://mermade.github.io/static/v3.1.0.html#style-examples to check the issues are fixed and everything else looks ok?

**Comment by hkosova** [comment]
Hi @MikeRalphson, sorry for the late reply. The link https://mermade.github.io/static/v3.1.0.html seems to have expired, it's 404. Is there another preview page?

**Comment by MikeRalphson** [comment]
Apologies, let me fix that now.

**Comment by hkosova** [comment]
@MikeRalphson your fixed version looks OK to me 👍

**Comment by MikeRalphson** [comment]
Thanks @hkosova, will PR to fix all published versions.
