### ISSUE TITLE
parameter datatype correlation

### ISSUE THREAD

**Issue by YamenJun** [OAI/OpenAPI-Specification#2493]
Hi~

There is a parameter's type is **array** in swagger json. When I convert it into python apilib, the type transfer into **list[int]**.

I use it to define method like this:

```python
def get_receipts_by_ids_with_http_info(self, authorization:str, request_body:list[int]):
	pass
```

Python does'nt support parameter define in this way. If I verify it like bellow, it works:

```python
def get_receipts_by_ids_with_http_info(self, authorization:str, request_body:List[int]):
	pass
```

How can I transfer **array** type into **List[int]** in python apilib?

Thanks.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
