### ISSUE TITLE
Meta-schema for v3.1?

### ISSUE THREAD

**Issue by gwerbin** [OAI/OpenAPI-Specification#2499]
Hello OAI team! Thanks for the very useful (and constantly improving) specification.

Is there any plan to release a JSONSchema meta-schema for validating OAS v3.1 schemata? Currently only [v3.0](https://github.com/OAI/OpenAPI-Specification/tree/master/schemas) is available.

**Comment by MikeRalphson** [comment]
Yes, it is in progress, see PR #2489
