### ISSUE TITLE
Open TSC Meeting, Thursday 18 March 2021

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#2501]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TSC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TSC meeting**

The agenda backlog is currently maintained in issue #2482

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| An announcement | @Relequestual | |
| Home for OpenAPI projects | Marques | |
| Metaschema | Jason| |
| JSON Type Serialization Registry | Darrel | |
| Housekeeping | @webron | |
|AOB (see below) | TDC | |
|New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
|[New issues](https://github.com/search?q=repo%3Aoai%2Fopenapi-specification+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by darrelmiller** [comment]
Let's get confirmation that these two are probably functionally equivalent, but the first is more explicit.

```yaml
security:
  - {}
```
and

```yaml
security: []
```

**Comment by MikeRalphson** [comment]
They are *in isolation*, but

```yaml
security:
  - {}
```

means optional security (which could be used in combination, AND'd or OR'd, with other security requirements). Whereas

```yaml
security: []
```

means there is no security requirement for this operation at all.

**Comment by yanavasileva** [comment]
Could you please let me know how to bring to your attention #2479?

**Comment by Relequestual** [comment]
This issue needs pinning in place of last weeks meeting issue =]

**Comment by Relequestual** [comment]
I would, if I may, like to start by taking 5 minutes (at most) to give a quick JSON Schema announcement!

**Comment by MikeRalphson** [comment]
> This issue needs pinning in place of last weeks meeting issue =]

@darrelmiller will be reprimanded sternly.
