### ISSUE TITLE
Spelling: WebHook -> Webhook

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#2503]
3.1.0 talks about "WebHook" (confusingly in the section on callbacks, but that's a different issue). the correct spelling is "Webhook" (https://en.wikipedia.org/wiki/Webhook). i couldn't quite figure out what to create a PR against, but if somebody points me in the right direction, i'd happily do that.

**Comment by MikeRalphson** [comment]
@dret we now have a `v3.1.1-dev` branch containing a `versions/3.1.1.md` file which would be the target of this PR.

I think the "WebHook" (sic) wording pre-dates the introduction of the `webhooks` object (containing callbacks which are registered out-of-band) - so it might be better to find rewording for this sentence as you noted, but a first PR just correcting the capitalisation would also be a fine first step.

**Comment by handrews** [comment]
PR merged!
