### ISSUE TITLE
Can't show multiple API in one URL

### ISSUE THREAD

**Issue by soylomass** [OAI/OpenAPI-Specification#2507]
I'm creating a documentation API for my Nest.JS rest API, but I'm unable to create a main URL with a selector for all the APIs, I can only create a separate path for each API.

Is there any way or configuration to get a main path, with a link to each subpath?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
