### ISSUE TITLE
Does OAS3 callbacks also relate about the Service implementation part, because if at all this callback endpoint might be a part of different Swagger as well ?

### ISSUE THREAD

**Issue by mma5997** [OAI/OpenAPI-Specification#2508]
Hi folks,
So my query is, lets say I have OAS3 based Swagger101.json that has a subscription endpoint operation which is configured with a callbacks operation for callbacks URL.

So apart from invocation of callback, does the callbacks definition for this mean that the callbacks URL belongs to some other Service Swagger spec or basically another Swagger JSON. There might be a possibility that this callbacks endpoint operation might be part of whole different Swagger spec that has a lot of operations and endpoints to offer.

Does this make sense ?

**Comment by lornajane** [comment]
I'm not sure if it's useful to answer such an old open issue but I'll share my thoughts in case they are useful before I close it! If I understood your question, it doesn't matter whether the callbackURL is part of another API description or not - you can describe the subscription endpoint and its callback here and it's up to you whether the other related parts are described elsewhere, or not at all.
