### ISSUE TITLE
Proposal: add a new format: plain for type: string

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#2519]
My proposal is that we add a new string type format:
```
type: string
format: plain
```
Which limits strings to non-binary strings.
The reason that I think this would be helpful is that
```
type: string
```
With format unset is generally used as a generic string. However, it should allow in both string and binary string types.
Here are some schemas that demonstrate that:
Binary is a more specific format constraint on string, so one can have this schema:
```
composedSchema:
  allOf:
    - type: string
    - type: string
      format: binary
```
Which will validate for python `b'hi'`

Can one have a binary date and binary date-time? I suspect not because we don't know the encoding to go from a sample
default/sample/enum string value to an encoded binary value.
Do people agree with this point about binary date and datetimes not existing?

What is missing is the ability to constrain a string to only non-binary types.
If we had that, then we could reject binary string values and only allow in non-binary strings.

```
type: string
```
Allows in 'hi' and b'hi'

```
type: string
format: binary
```
Allows in b'hi' only

```
type: string
format: plain
```
Would allow in 'hi' only and exclude b'hi'

All json payloads that are sending plain text and not binary file data are sending:
```
type: string
not:
  type: string
  format: binary
```
which is equivalent to:
```
type: string
format: plain
```

**Comment by karenetheridge** [comment]
How would this be different than simply leaving off the `format` keyword entirely?

**Comment by spacether** [comment]
Format unset allows any type of string. My proposalis to add a formatthat describes only simple strings which are notddates datetimes uuids. Format plain wouldn't validate fora dateor datetime or uuid.

**Comment by LikeLakers2** [comment]
But leaving out the `format` keyword would do exactly what you want, which is to avoid validating it. By not specifying how to validate it, the parser would know that it could be a string of *anything*, and thus wouldn't know what to use to validate it.

**Comment by spacether** [comment]
Never mind about this
My intention was to define type string format unset as
oneOf:
- type: string
  format: date
- type: string
  format: datetime
- type: string
  format: uuid
- type: string
  format: plain
To allow a value to always deterministically be placed into one of those sub schemas. But from thinking about this more when we have type string format unset it sounds like we instead treat it as a vanilla string.

**Comment by spacether** [comment]
Re-opening this ticket because I think that there is a valid use case here
Update: my proposal for the plain format could be combined with date/datetime/uuid etc other string formats.

**Comment by karenetheridge** [comment]
Could you explain, in technical terms, how I might determine whether a string is "plain" or "binary"? What am I looking for?

**Comment by spacether** [comment]
Sure, my definition of binary is coming from the openapi spec v 3.0.2:
```
any sequence of octets
```
And in my examples above I give examples of binary data in python, b'hi' if the data is of type bytes, it is binary data.
Examples of this are the data that we receive from a file download:
```
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                description: file to download
```
And for a string be of format plain it must conform to the draft-wright-json-schema-00 string definition:
`A string of Unicode code points, from the JSON "string" production`

**Comment by handrews** [comment]
@spacether `format: binary` and `format: byte` no longer exist in OAS 3.1, having been replaced by JSON Schema's more flexible `contentMediaType`, `contentEncoding`, and `contentSchema`.

The only time you are dealing with an actual octet-stream is when the media type specified in the HTTP `Content-Type` header or as a part of a multipart form.  This is outside of the JSON data model, and not a `type: string` in the normal sense.

Open API's Media Type Object and Encoding Object cover whatever aspect of this is not covered by JSON Schema.

When working with a media type compatible with the JSON data model, raw binary is not possible, only encoded binary as indicated by `contentEncoding`.  If there is no `contentEncoding`, then the string is assumed to be regular JSON string data without any encoding to decode.

I don't think this proposal applies anymore.  `format: binary` was never a good fit for `format` (but in fairness to OpenAPI, at the time of OAS 3.0, there weren't any better options).
