### ISSUE TITLE
Discriminator: how properly detect valid reference

### ISSUE THREAD

**Issue by Logioniz** [OAI/OpenAPI-Specification#2520]
Suppose we have such OpenAPI document which served by location http://example.com/openapi/desc

```yaml
servers:
    - url: 'http://example.com/'
components:
    schemas:
        Pet:
          type: object
          required:
          - petType
          properties:
            petType:
              type: string
          discriminator:
            propertyName: petType
            mapping:
              dog: Dog
        Cat:
          allOf:
          - $ref: '#/components/schemas/Pet'
          - type: object
            # all other properties specific to a `Cat`
            properties:
              name:
                type: string
        Dog:
          allOf:
          - $ref: '#/components/schemas/Pet'
          - type: object
            # all other properties specific to a `Dog`
            properties:
              bark:
                type: string
        Lizard:
          allOf:
          - $ref: '#/components/schemas/Pet'
          - type: object
            # all other properties specific to a `Lizard`
            properties:
              lovesRocks:
                type: boolean

```

it is not clear what mean Dog in the mapping subscheme.
Variants:
1. http://example.com/openapi/Dog (accroding to base uri http://example.com/openapi/desc)
2. #/components/schemas/Dog

If i have subschema in another url (http://example.com/openapi/Dog) thеn Dog is relative link.
If i have subschema in components thеn Dog is #/components/schemas/Dog (which is also a relative link, but different)

How to correctly determine that Dog is a relative link or subschema in #/components/schema?

Sorry for bad english.

**Comment by Logioniz** [comment]
Any recommendations?
Not sure how to properly handle this kind of situation.

**Comment by jdesrosiers** [comment]
My understanding is that the values of `mapping` are _not_ a reference. The value is used to construct references such as `#/components/schemas/Dog`.

**Comment by jdesrosiers** [comment]
(Note: I deleted my previous wrong response)

I believe is example has a bug. The values of `mapping` are URIs that must match the URI of one of the schemas being discriminated. I don't think OpenAPI has a concept of an identifier the way JSON Schema does. In that case, `Dog` doesn't have anything to resolve against and that is an invalid reference. If OpenAPI does have a concept of an identifier, then it would resolve to `http://example.com/openapi/Dog`, which doesn't exist. Constructing `#/components/schemas/Dog` should only happen when auto mapping, not with `mapping`.

The discriminator in the example should be,

```yaml
discriminator:
  propertyName: petType
  mapping:
    dog: '#/components/Dog'
```

**Comment by Logioniz** [comment]
> I believe is example has a bug. 

This example is taken from the specification (see the example in the end of [discriminator object](https://swagger.io/specification/#discriminator-object)), i.e. I have not invented it. I understand correctly that you want to say that this is a bug in the documentation description (or bug in example in documentation)? 

If the construction of the `#/components/schemas/Dog` will be done only with auto-mapping, then in my opinion this will solve the problem too.

**Comment by jdesrosiers** [comment]
I didn't think you made it up. I recognized it as the example is from the documentation. Yes, I believe the example from the documentation has a bug.

I don't think that OpenAPI has a concept of a base URI, so I don't think you can resolve `Dog` against `http://example.com/openapi/desc`. I think `Dog` is just an invalid reference. It needs to be an absolute URI. I could be wrong about that part.

**Comment by Logioniz** [comment]
@jdesrosiers thanks for your reply.

> I don't think that OpenAPI has a concept of a base URI

Hmm... Maybe i misunderstood the documentation. Pay attention to part of the specification [Relative References in URLs](https://swagger.io/specification/#relative-references-in-urls). For me, this part is not very clear and requires clarification. 
From specification:

> Relative references are resolved using the URLs defined in the Server Object **as a Base URI**.

I think what is meant here is about url in the subscheme `paths` (i do not know of any other examples of what this might mean, for me it is not clear).
There is a special note for `$ref`:

> Relative references used in $ref are processed as per JSON Reference, using the URL of the current document **as the base URI**

Thus, if OpenAPI is served by url http://example.com/openapi/desc, then it is the base url for `$ref`.

**Comment by jdesrosiers** [comment]
I agree with your conclusion. This is what I missed,

> Relative references are resolved using the URLs defined in the Server Object as a Base URI.

That is very clear. So, I agree that in the previous example, `Dog` would resolve to `http://example.com/openapi/Dog`.

**Comment by MaceWindu** [comment]
No, it wasn't. Last example still use `Dog`

BTW, I've come here, because I've stumbled upon real openapi document which use this notation https://github.com/LandRegistry/digital-street-conveyancer-api/blob/master/src/main/resources/openapi.json#L730-L731

and expect it resolved to `#/components/schemas/<name>` ...

**Comment by jdesrosiers** [comment]
I was wrong that "schema names" are not allowed in `mapping`. The spec says `mapping` is  "an object to hold mappings between payload values and _schema names or references_". (The spec never defines what "schema names" means, but it's assumed that it means the property names used under `/components/schemas` which is equivalent to `#/components/schemas/{schema name}`.) Since a schema name is also a valid URI, there definitely seems to be an ambiguity in the spec.

I think the most reasonable thing to do would be to assume it's a schema name if it looks like a schema name and fallback to treating it like a URI if that schema doesn't exist. It would be nice if there was a linting rule to flag the use of schema names in `mapping` as something to be avoided.

**Comment by handrews** [comment]
PRs merged!  closing.
