### ISSUE TITLE
White background in logo in readme in dark mode

### ISSUE THREAD

**Issue by mwomick** [OAI/OpenAPI-Specification#2522]
[Cosmetic] Change to transparent background for compatibility with dark mode

**Comment by MikeRalphson** [comment]
Thanks for reporting this. PRs welcome.

**Comment by Shiva9801** [comment]
Hello @MikeRalphson  , I could resolve this issue . Can you make me Assignees?

**Comment by Shiva9801** [comment]
We can change to a transparent background for the image.
I'm facing an issue i.e. the image is attached via URL and I can't make changes to it; so for trial purposes, I downloaded and edited the image and got a URL from a website and the issue seems to be resolved in dark mode.

**Comment by LasneF** [comment]
@MikeRalphson , @handrews  given the PR has been merged , looks we can close the issue isn't it ?

**Comment by handrews** [comment]
@LasneF yup, not sure how I missed your comment earlier.  Closing as complete!
