### ISSUE TITLE
AsyncAPI as part of OpenAPI ?

### ISSUE THREAD

**Issue by bufferoverflow** [OAI/OpenAPI-Specification#2527]
I'm not sure if this has been discussed already. However, I did not find related discussion so just asking here now. [AsyncAPI](https://www.asyncapi.com) is reusing the basic concepts from OpenAPI, see also https://www.asyncapi.com/docs/getting-started/coming-from-openapi and I was thinking about why AsyncAPI was never integrated into OpenAPI spec. I personally think this would be a perfect match. Was this considered already?

Of course also in regard of tooling such a combination could become beneficial for many people, e.g. https://github.com/swagger-api/swagger-ui/issues/6632

**Comment by MikeRalphson** [comment]
See #2431 - one of the reasons for not merging the specs is that doubling the size of the spec would make it harder for new users to get to grips with it.

**Comment by bufferoverflow** [comment]
thanks for the super fast feedback @MikeRalphson ! I agree, it might hinder development velocity a bit. However, as the core elements are very close and OpenAPI has been extended with SLA, webhooks, json schema I was thinking that this could be valuable. Also considering use cases were you have full blown APIs based on OpenAPI including webhooks and some async endpoints in a single spec.

**Comment by MikeRalphson** [comment]
You succinctly explain the counter point!

**Comment by MikeRalphson** [comment]
@fmvilas has thoughts on this area - when he returns from parental leave, maybe we can schedule a discussion.

**Comment by bufferoverflow** [comment]
@fmvilas Could you maybe share your thoughts on this?

**Comment by fmvilas** [comment]
😊 You actually raised a common topic and I presented a few times about it: https://www.youtube.com/watch?v=z3nA_2Wu91A&list=PLbi1gRlP7pihtIxQOd51YMqtUn_htgsrj&index=3. Hope this sheds some light on why we're not merging the two specs.

That said, it's in our [roadmap](https://www.asyncapi.org/roadmap) to let users embed OpenAPI, GraphQL, and other API specifications (or parts of it) inside AsyncAPI. So, eventually, you should be able to use AsyncAPI and OpenAPI together using the same tools.

**Comment by bufferoverflow** [comment]
Thanks for the insights and the link to your presentation on the topic!

**Comment by rafalkrupinski** [comment]
Looking at https://github.com/APIs-guru/asyncapi-directory there isn't much interest in AsyncAPI

**Comment by handrews** [comment]
@rafalkrupinski I think that's an artifact of who tends ot look at APIs.guru rather than lack of interest in AsyncAPI.

**Comment by rafalkrupinski** [comment]
@handrews Might be the case. But there was traffic in that repo, just died three years ago...

**Comment by lornajane** [comment]
I'm closing this issue as I don't think there's anything directly actionable here that merits being on our backlog. OpenAPI as an organisation stays in touch with the other API specification standards and of course the topic is always open for discussion.

**Comment by lchik22** [comment]
Is there any way to unite OpenAPI and AsyncAPI so that it is possible to create api documentation for WebSockets with other http requests?
