### ISSUE TITLE
RSS feed from an open api url

### ISSUE THREAD

**Issue by Tasty213** [OAI/OpenAPI-Specification#2538]
Hi,

Is there any way to link an RSS reader to an open api site? For instance, i'm making a library for https://developer.parliament.uk/ which is documented in Open API (https://members-api.parliament.uk/swagger/v1/swagger.json). In order to make sure the library is up to date is there a way to have an RSS feed notify me whenever the specification updates?

**Comment by MikeRalphson** [comment]
This is probably out of scope for this repo, though it's an interesting tooling **idea** so I'd be happy to leave this open for a short while in case someone wants to run with linking an OAS diff tool to an RSS feed. Simply, you could use something like https://www.followthatpage.com/ to track changes to any publically accessible URL. [apiwatch.io](https://www.apiwatch.io/) is also launching soon which may do what you need. Paging OAS Ambassador @dvh

**Comment by dvh** [comment]
Hi @Tasty213, are you looking for a way to let consumers discover which version of the API is  the latest and if OAS provides a way to describe this? Currently it's out of scope of OAS, but I have been thinking about making a feature request and proposal for this as well ;-)

**Comment by Tasty213** [comment]
Hi,

I want a way to be notified automatically when there are new features
added to an api.

**Comment by MikeRalphson** [comment]
You could subscribe to the APIs.guru OpenAPI Directory [RSS feed](http://api.apis.guru/v2/list.rss) - there you will find all the `.parliament.uk` APIs:

```xml
<item>
    <title>Members API</title>
    <link>https://members-api.parliament.uk/swagger/v1/swagger.json</link>
    <description>An API which retrieves Members data.</description>
    <category>APIs</category>
    <guid isPermaLink="false">parliament.uk:members</guid>
    <pubDate>Wed, 07 Apr 2021 10:21:40 GMT</pubDate>
</item>
```

The `pubDate` will update when the API changes, and this will currently be within a week of the source API definition changing - we hope to get this down to 24 hours very soon.

**Comment by Tasty213** [comment]
Can confirm this works closing now, thanks for the help.
