### ISSUE TITLE
Well-known URL for spec files?

### ISSUE THREAD

**Issue by elliotdickison** [OAI/OpenAPI-Specification#2540]
I just learned about [.well-known URLs](https://en.wikipedia.org/wiki/List_of_%2F.well-known%2F_services_offered_by_webservers). I'm not sure if this is the right place for the suggestion, but I think it would be cool if there was a well known path to serve OpenAPI docs. Something like `<host>/.well-known/open-api.json`. If not a standard, then at least a conventional path would help with tooling, discoverability, etc.

**Comment by MikeRalphson** [comment]
Please see issues #724 and #2128
