### ISSUE TITLE
TOB nominations are underway

### ISSUE THREAD

**Issue by ncaidin** [OAI/OpenAPI-Specification#2550]
It is time for the annual TOB elections. Please email me your nominations by this Friday, April 23th, 7 pm Pacific to ncaidin@linuxfoundation.org .

Fortunately, all the existing TOB members in this election cycle have volunteered to serve again. If there are no additional nominations, they will serve another term. Here are the four folks kind enough to stand again for nomination: @isamauny @usarid @earth2marsh @webron

Please let me know if you have any questions or concerns.

**Details**

From the project charter - "The TOB shall be composed of individuals elected for their expertise and contribution to the advancement of API-related technologies. Anyone may be elected to the TOB, regardless of whether the individual is an OAI Member or OAI TSC participant. It is intended that TOB members shall be technical experts that are considered thought leaders in the ecosystem. An elected TOB member is elected as an individual and not as a representative of their employer. TOB members may not designate alternative representatives."

[https://github.com/OAI/OpenAPI-Specification/blob/main/TOB.md](url)

**Comment by ncaidin** [comment]
The TOB nomination period is over. No additional nominations have been received. Please join me in thanking @isamauny @usarid @webron @marsh  for their ongoing service on the TOB for another two years.

**Comment by MikeRalphson** [comment]
`TOB.md` has been updated.
