### ISSUE TITLE
allOf | Primitive types Support.

### ISSUE THREAD

**Issue by ChaitanyaBabar** [OAI/OpenAPI-Specification#2551]
### Question
Does `allOf` construct support the use of primitive types under it , similar to `anyOf` or `oneOf` examples [here](https://swagger.io/docs/specification/data-models/data-types/#any).

### Example
Consider the below example (i.e. attached here as [allOf_Primitive_type.txt](https://github.com/OAI/OpenAPI-Specification/files/6344619/allOf_Primitive_type.txt)) I have verified Swagger/OpenAPI [here](https://apitools.dev/swagger-parser/online/) and it parsed schema correctly without any errors.

```
{
  "schemas": {
    "Pet": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NewPet"
        },
        {
          "type": "string"
        }
      ]
    }
  }
}
```
So my question is is the above schema valid OAS 3 schema ?
If yes , then how the Pet object represented in actual run time and second parameter does not have `name` attribute ?
(i.e. Meaning how come multiple **primitive** data types under `allOf `represented in Pet object as they do not have `name `attribute)

**Comment by darrelmiller** [comment]
Yes that is valid OAS.  How that request/response body is handled in a programming language is out of scope for the OpenAPI specification.

**Comment by ChaitanyaBabar** [comment]
> Yes that is valid OAS. How that request/response body is handled in a programming language is out of scope for the OpenAPI specification.


```
{
  "schemas": {
    "Pet": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NewPet"
        },
        {
          "type": "string"
        }
      ]
    }
  }
```


@darrelmiller ,
Apologies if I am getting this wrong , Can you please suggest how the request payload will look like for above schema ?

Thanks,
Chaitanya

**Comment by MikeRalphson** [comment]
See your other issue. How it will look in any given tool is pretty much a question for that tool, not the specification itself. You might want to ask a JSON Schema related question on a site such as Stackoverflow.
