### ISSUE TITLE
Request PayLoad | allOf Json construct

### ISSUE THREAD

**Issue by ChaitanyaBabar** [OAI/OpenAPI-Specification#2557]
### Question
I am new to OAS schema and I am trying out the various valid OAS schema for `allOf `JSON contruct.
Please find the attached JSON schema [gitHub_allOf_array_complex_type.txt](https://github.com/OAI/OpenAPI-Specification/files/6384003/gitHub_allOf_array_complex_type.txt) , which is valid OAS according to online swagger parser [here](https://apitools.dev/swagger-parser/online/).

### Example
Given the fact that is valid OAS schema , How would the below **Pet** object represented in real **request/response** payload ?

```
      "Pet": {
        "allOf": [
          {
            "$ref": "#/components/schemas/NewPet"
          },
          {
            "type": "array",
            "$ref": "#/components/schemas/NewPet"
          }
        ]
      }
```

Or even it is valid OAS schema (i.e. as per Online Swagger Parser) after all , we need to bit more diligent while constructing the schema (i.e. may be introduce another **object** of with name **_NewPets_**, which has property **_pet_** which is array of **_NewPet_** , and just $ref the **_NewPets_** directly inside **_allOf_** )

**Comment by MikeRalphson** [comment]
Looking at your example you are saying a `Pet` instance must match **all of** the sub-schemas. In one of which `NewPet` must be `type: object` and in the other, you have a sibling property of the `$ref` (only valid in OAS 3.1) where you say the `type` must be an `array`.

Is what you intended:

```yaml
pet:
  oneOf:
    - $ref: "#/components/schemas/NewPet"
    - type: array
       items:
         $ref: "#/components/schemas/NewPet"
```

I apologise for trying to answer a different question than the one you asked, but to come back to your query, yes this is valid OAS syntax, but it **may not do what you want**. 

How such a schema (yours or mine) is represented in a real request/response is largely a function of tooling, not the specification itself and thus is out of scope for this repository.

**Comment by MikeRalphson** [comment]
I see you have opened a similar issue over at JSON Schema, so I'll close this now.
