### ISSUE TITLE
Open Community (TDC) meeting, Thursday May 13th 2021

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#2559]
**NOTE: This meeting is on Thursday at 9am - 10am PT**

**NOTE: There is no community meeting on the 6th of May 2021**

Zoom Meeting link: [https://zoom.us/j/975841675](https://zoom.us/j/975841675?pwd=SUh4MjRLaEFKNlI3RElpWTdhRDVVUT09). Dial-in passcode: 763054

In order to give some more visibility into the topics we cover in the TDC meetings here is the planned agenda for the next meeting.  Hopefully this will allow people to plan to attend meetings for topics that they have an interest in.  And for folks who cannot attend they can comment on this issue prior to the meeting.  Feel free to suggest other potential agenda topics.

**Please submit comments below for topics or proposals that you wish to present in the TDC meeting**

The agenda backlog is currently maintained in issue #2482

| Topic | Owner | Decision/NextStep |
|-------|---------|---------|  
| Big list of possibilities for v3.2 #2572 | @earth2marsh | |
| Overlay Spec progress | @darrelmiller / @webron | |
| Diversity and Inclusion Training | @ncaidin | |
| Automating the agenda issue #2571 | @MikeRalphson | |
| Automating the ReSpec HTML version #2574 | @MikeRalphson | |
| Moving to an "all contributors" model | @MikeRalphson | |
| [CodeTriage](https://www.codetriage.com/oai/openapi-specification) suggestion for interested contributors, add ![badge](https://www.codetriage.com/oai/openapi-specification/badges/users.svg) badge to README? | @MikeRalphson | |
AOB (see below) | TDC | |
New issues / PRs labelled [review](https://github.com/OAI/OpenAPI-Specification/labels/review) | @OAI/triage | |
[New issues](https://github.com/search?q=repo%3Aoai%2Fopenapi-specification+is%3Aissue+comments%3A0+no%3Alabel+is%3Aopen) without response yet | @OAI/triage  | |

/cc @OAI/tsc Please suggest items for inclusion

**Comment by ncaidin** [comment]
Diversity and Inclusion Training interest?

**Comment by MikeRalphson** [comment]
[Meeting recording](https://zoom.us/rec/share/gE8_RTtptKjX3GQu72Sf9RMLkahc9EAUNVQU969OpWBxFpbMjnb-lqSZAU7RzhG0.16eS8fiv83S9IgOA)
