### ISSUE TITLE
Broken link (iCal) in README

### ISSUE THREAD

**Issue by dvh** [OAI/OpenAPI-Specification#2560]
The link to the iCal feed in https://github.com/OAI/OpenAPI-Specification/blob/main/README.md#participation is broken. I'd suggest to either remove the link or have it fixed by the mailing list. Perhaps it's not publicly accessible, but then it could use some clarification in the README or it needs to return a different status code ;-)

**Comment by MikeRalphson** [comment]
Thanks @dvh believe this was fixed in #2561
