### ISSUE TITLE
How do I denote timestamp in Open API 3 specification

### ISSUE THREAD

**Issue by smitit173** [OAI/OpenAPI-Specification#2565]
I am trying to create a field that contains the timestamp. The data type is an integer since it is a timestamp but not sure whether we have any format that can be used distinctively to identify a timestamp in OAI 3.0.x

Currently I am denoting it as - 

`            created_at:
                  type: integer
                  format: int64
                  minimum: 1
`

**Comment by MikeRalphson** [comment]
I've seen examples such as:

format
|---|
timestamp
timestamp without time zone
timestamp with time zone
TIMESTAMP
unix timestamp to millisecond
Unix timestamp
timestamp ISO8601
unix timestamp
unix-time
unixtime
unix-epoch
Unix timestamp
unixtime list
unixMillis
epoch

Which is one of the reasons we started working on a `format` [registry](https://spec.openapis.org/registry/format/) #845

**Comment by smitit173** [comment]
thanks for the quick response :)
