### ISSUE TITLE
info object version

### ISSUE THREAD

**Issue by satuday** [OAI/OpenAPI-Specification#2567]
according to the [open api spec](https://spec.openapis.org/oas/v3.1.0#fixed-fields-0), info version is string, but the [example ](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/api-with-examples.yaml#L4)is using number.

**Comment by MikeRalphson** [comment]
`2.0.0` isn't a number, as it contains more than one full-stop. Thus in YAML it parses as a string without needing to be quoted.

**Comment by satuday** [comment]
thanks for the clarification. you are right, Ithe issue I am facing maybe is from NSwag instead, since I set the document version to 1.0, the generated yaml is not quoted.
