### ISSUE TITLE
Guidance for float and double max and min values

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#2570]
Hi there
Can we get some guidance on
```
type: number
format: float
```
and
```
type: number
format: double
```

Maximum and minimum values?
It sounds like `Some floating point formats use an unrepresented hidden 1 bit in the mantissa (this allows for one extra bit of precision in the mantissa` per https://softwareengineering.stackexchange.com/questions/294269/how-to-calculate-min-max-values-of-floating-point-numbers

1. Should float be a single-precision 32-bit IEEE 754 floating point?
2. Should double be a double-precision 64-bit IEEE 754 floating point?

**Comment by MikeRalphson** [comment]
I believe the intention was to refer to the IEEE754 definitions, but we should make this explicit. Do you have time to work up a PR against the `v3.1.1-dev` branch? A more full description should also go into new entries in the [formats registry](https://spec.openapis.org/registry/format/) - this would be a PR against the `gh-pages` branch.

**Comment by spacether** [comment]
Right now I don't have time to do this sorry.
It would also help to specify if the floats are binary32 and are not decimal32.

**Comment by handrews** [comment]
This has since been addressed by multiple additions to the formats registry around floating point and decimal representations.
