### ISSUE TITLE
Issue with v3.1.0 using Visual Studio Code

### ISSUE THREAD

**Issue by Tasselhoff** [OAI/OpenAPI-Specification#2581]
Hi,

In Visual Studio Code with the 42Crunch extension, I'm getting the following error for my openapi.yml file (but no others) for:

openapi: '3.0.2'

```
String does not match the pattern of "^3\.1\.\d+(-.+)?$".

{
	"resource": "/d:/<path>/openapi.yml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "String does not match the pattern of \"^3\\.1\\.\\d+(-.+)?$\".",
	"source": "yaml-schema: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json",
	"startLineNumber": 1,
	"startColumn": 10,
	"endLineNumber": 1,
	"endColumn": 17
}
```

So it appears to try to impose 3.1.x, but only for the openapi.yml root file.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by Tasselhoff** [comment]
> 
> 
> Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

The source of the error is "source": "yaml-schema: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json"

**Comment by MikeRalphson** [comment]
No, the tooling is using the 3.1 metaschema when you're trying to validate a 3.0 document. That is a tooling error.

**Comment by petermarcoen** [comment]
@Tasselhoff I have the same problem, what did you do to solve this? I switched to 3.1 to bypass the error but I don't want to up my version every couple of months, especially if the spec might change.
