### ISSUE TITLE
Interdependent request body properties on validation

### ISSUE THREAD

**Issue by alexfriedl** [OAI/OpenAPI-Specification#2595]
### Problem

Say I have this model with interdependent properties:

```
{
  "password": "blaa",
  "passwordConfirm": "blaa"
}
```

I want to validate password against passwordConfirm via openAPI specification.
I did not find a solution in the documents.

Is this feasible with openAPI 3?

Thanks for your help everyone!

**Comment by handrews** [comment]
This is not possible with the standard keywords.  Changing this for 3.1 or later would be done through JSON Schema (either the spec or an extension vocabulary such as @gregsdennis's `data` vocabulary).  I'm going to close this as out of scope for OAS proper.
