### ISSUE TITLE
webhook path/query parameters

### ISSUE THREAD

**Issue by jrihtarsic** [OAI/OpenAPI-Specification#2611]
We would like do define a webhook, with path and query parameters. 

The specification for the webhooks does not specify "path pattern" as they are defined for Paths. 
What would be the preferred workaround for describing "path pattern"?
Reusing the webhook name like this

```
  "webhooks": {
    "messaging/{param1}/{param2}/?messageId={param3}": {
      "get": {
        "parameters": [
             {  "name": "param1",
                 "in": "path",
                 "required": "true"
             },
             {  "name": "param2",
                 "in": "path",
                 "required": "true"
             } ,
            {  "name": "param3",
                 "in": "query",
                 "required": "true"
             }
      ...
```
Or to add extension parameter for:

```
  "webhooks": {
      myWebHook: {
      "x-path": "messaging/{param1}/{param2}/?messageId={param3}",
      "get": {
        "parameters": [
             {  "name": "param1",
                 "in": "path",
                 "required": "true"
             },
             {  "name": "param2",
                 "in": "path",
                 "required": "true"
             } ,
            {  "name": "param3",
                 "in": "query",
                 "required": "true"
             }
              ...
```

In both cases, I can also prepare a proposal to extend OpenAPI if that is needed.

**Comment by orubel** [comment]
*sigh* Every endpoint can be a webhook. You don't need to define them separately. Just put a toggle into existing API definitions (I have been doing this forever)

Example:

`			    "create": {
			     	"METHOD":"POST",
			    	"DESCRIPTION":"Create new Person",
			    	"ROLES":{
				    "BATCH":["ROLE_ADMIN"],
				    "HOOK":["ROLE_ADMIN"]
				},
			        "REQUEST": {
			            "permitAll":["username","password","email","firstName","lastName"]
			        },
			        "RESPONSE": {
			        	"permitAll":["id","version","username","email","enabled","accountExpired"]
			        }
			    },

POOF! Now only the 'ROLE_ADMIN' role can register to get notified by this endpoint

Whether tou use Kafka or your own internal postinterceptor`, this can check the security and then notify via registered URL

**Comment by lornajane** [comment]
The webhook feature serves the case where the paths are set as part of the subscription, which is outside of the scope of the OpenAPI specification. Our webhook feature describes the payloads that are available and how to respond; registering to receive those webhooks, and which paths they will be sent on, is done out of band.

If the subscription has limitations, such as requiring particular paths for particular webhook payloads, that's of course fine, but that's part of the registration process and won't be covered in the OpenAPI description.

**Comment by jrihtarsic** [comment]
Firstly, I'd like to commend you on your excellent work on this project. It's been very beneficial for us developers, thank you for it.

However, I'm a little disappointed that you won't be adding support for partial URLs, paths, and query parameters to your OpenAPI specification webhook element. This feature would enable "callback" to receive simple status updates in a callback without the need for a particular payload definition, which can be overkill in some cases. Additionally, it would allow callback implementers to use the same code generators for implementing webhook/callback services, and service/transaction designers to fully define in one OpenAPI file the message exchange flows between multiple parties.
