### ISSUE TITLE
Unsigned Integers

### ISSUE THREAD

**Issue by hampgoodwin** [OAI/OpenAPI-Specification#2617]
We would like to provide the `type` of  integer with additional `format` types of uint8, uint16, uint32, and uint64.

**Comment by MikeRalphson** [comment]
As per the [JSON Schema spec](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.2.3) `format` is an open-ended keyword, so you can define your own values.

In this issue https://github.com/OAI/OpenAPI-Specification/issues/845#issuecomment-378139730 we have discussed creating a `format` registry either for the OAS or across multiple specs which use JSON Schema.

We're very interested in feedback on what format (!) that registry should take and how people would want to use it.

`uint64` would have some interoperability issues with some languages (e.g. Javascript) which map JSON numbers to an internal format which can only support up to 53 bits of integer precision (signed), so some people use `type: string` in these cases.

Please feel free to continue the discussion on #845
