### ISSUE TITLE
Is `:` a valid delimiter for the path parameter?

### ISSUE THREAD

**Issue by jjtang1985** [OAI/OpenAPI-Specification#2619]
Dear OpenAPI specification experts,

I have a question regarding "path pattern" and "path parameters". The questionis whether this path pattern `/somePath/{param1}:{param2}` is valid.

Let's split the whole "path pattern" (`/somePath/{param1}:{param2}`) into multiple parts with `/`, so the original "path pattern" contains two parts:
1.  `/somePath`
2. `/{param1}:{param2}`

Usually, every part contains one parameter like this example `/cars/{carId}/drivers/{driverId}`, where the `{carId}` and `{driverId}` are located in different parts. However, `/{param1}:{param2}` contains two parameters connected with a delimiter `:`.

This [doc](https://swagger.io/docs/specification/serialization/) shows how `style` keyword is related to the delimiters, which does not tell that `:` is a valid delimiter.

As `:` is not mentioned as one of the supported delimiters, I would assume, my example is an invalid "path pattern".
Could you please share your opinion and maybe point out some docs that I might miss.

Thank you very much in advance.

Best regards,
Junjie

**Comment by MikeRalphson** [comment]
The only delimiters in a URL path are `/`, `?`, `&` and `#`. The `:` character here doesn't function as a delimiter between path segments, nor, as it is not within a path parameter, does it act as part of the name of a parameter, or a delimiter for the purposes of the `style` keyword.

It **is valid** to have multiple `in: path` parameters within one URL path segment, but they may not 'cross' a path segment boundary, by containing an unescaped `/` character.

Please feel free to update this issue if you think the spec. or `examples` subdirectory should be updated to make this clearer.

**Comment by jjtang1985** [comment]
Hi @MikeRalphson ,

thanks for your quick response.

For me, it seems the path `/somePath/{param1}:{param2}` is valid, if both parameter `param1` and `param2` are defined like:
```
        "parameters": [
          {
            "name": "param1",
            "in": "path",
            ...
          },
          {
            "name": "param2",
            "in": "path",
            ...
          }]
```
Could you please confirm?

Of course, similar question would be whether the path pattern below are valid:
- `/somePath/{param1}-{param2}`
- `/somePath/{param1}={param2}`
- `/somePath/{param1}.{param2}`
-  other variants with special characters

Best reagards,
Junjie

**Comment by MikeRalphson** [comment]
Yes, you need to define both `in: path` parameters to match the path templated items. Each `in: path` parameter must have `required: true`.

All of your other examples are valid. 

I'm not sure what you mean by "special characters" though. `?` and `#` cannot appear unescaped in a path key, `%` introduces a hex-coded character... were you thinking of these or some other characters?

**Comment by jjtang1985** [comment]
@MikeRalphson ,

For the "special characters", in addition to the ones mentioned (`?`, `#` and `%`), please fine more examples below, where `(`, `)`, `'`, `&`, `$` are used:
- `/somePath/({param})`
- `/somePath/'{param1}'`
- `/somePath/{param1}&{param2}`
- `/somePath/{param1}${param2}`

Best regards,
Junjie
