### ISSUE TITLE
OpenAPI 3 Specification $ref documentation gives a bad example for URL reference

### ISSUE THREAD

**Issue by jmorgannht** [OAI/OpenAPI-Specification#2624]
![image](https://user-images.githubusercontent.com/77861184/122591092-b2f69480-d01f-11eb-840f-c620d41a3bb1.png)

Example syntax will produce the following validation error in the editor, $ref paths must begin with `#/`

Example syntax should be:
The specific element of the document stored on the different server – $ref: 'http://path/to/your/resource.json#/myElement'

**Comment by MikeRalphson** [comment]
I believe you're referring to documentation on `swagger.io`. That documentation isn't held in this repository or under our control.

Pinging @hkosova at Smartbear.

**Comment by hkosova** [comment]
@jmorgannht please open a ticket over at https://github.com/swagger-api/swagger.io/issues, thanks.
