### ISSUE TITLE
Parsing error with date default

### ISSUE THREAD

**Issue by SCSreekanth** [OAI/OpenAPI-Specification#2651]
Hi team,

Please find the attached yml file contents. The Swagger editor validates this yml file to indicate no errors; however, I get the following error when I use the parser to parse this file's contents. Failed. Reason: [attribute paths.'/test/{id}'(get).parameters.[id].schemas.default=`2012-12-11T18:30:00.000+0000` is not of type `date`]

```
openapi: 3.0.1
info:
  title: hello
  version: "1.0"
servers:
- url: http://abc.com
paths:
  /test/{id}:
    get:
      operationId: get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: date
            default: "2012-12-12"
      responses:
        200:
          description: OK
```

I have tried this with swagger-parser-v3-2.0.24. Please let me know if it has already been fixed.

Thanks,
Sree

**Comment by MikeRalphson** [comment]
You might want to try using `format: date-time`, looking at the value in the error message.

In general though, please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

**Comment by SCSreekanth** [comment]
Thanks, Mike. Will raise this to the swagger parser repository. Btw, even the format:date-time ends up with an error.
