### ISSUE TITLE
require `consumes` or `produces`?

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#266]
Without requiring to state what is consumed or produced by a server, it's really up to the client to guess what format to send/receive, and up to the server to handle all the types it doesn't support with proper, known error responses.  A simple work around would be to require that `consumes` is required whenever a parameter of type `body` or `formData` are supplied, and `produces` is required whenever a `schema` is attached to a response code or the default response.

**Comment by webron** [comment]
`schema` doesn't mean model anymore, it could also be a primitive. We can say it's mandatory of the type is `object`. 

We could definitely not validate it using basic json schema as the values propagate.

**Comment by ePaul** [comment]
If the response has a `schema` property, this means the content is in the body of the HTTP response, right? So if there is a response, there should be a `produces` property.

**Comment by webron** [comment]
@ePaul - really? we should force people to define `text/plain` if they return a numeric value?

**Comment by ePaul** [comment]
If the numeric value is in the body, it needs some media type (i.e. `Content-Type` header of the HTTP response). This could be `text/plain`, of course, or `application/x.single-number-in-ascii`, or even some JSON type (because a single number is also a valid JSON value in [RFC 7159](https://tools.ietf.org/html/rfc7159)).

**Comment by webron** [comment]
But is RFC 7159 accepted? It looks like it's a proposal. http://json.org/ suggest that only objects and arrays are valid JSON, while RFC 7159 suggests the change that JSON values are also valid JSON text. And indeed, many JSON parsers die if you pass a simple string value to them.

It looks like IANA refers `application/json` to be  [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt) which suggests that simple types are not officially supported for the mime type.

And let's face it, when was the last time you saw an API use `application/x.single-number-in-ascii`? :)

**Comment by ePaul** [comment]
I don't really want to discuss which media-type is appropriate here, but just mention that one should be used. (I also think an API returning a single number/string/boolean is not a good idea.)

[RFC 7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5) says that each response with body should have a Content-Type header, except if the server has no idea what it is. I would guess in the case of an API described by an OpenAPI description you can't really say "I have no idea what this is".

**Comment by webron** [comment]
Well, you can, and you do. You don't necessarily describe all the responses for example (in many cases it doesn't make sense). We can say that we're not going into the discussion of which mime-type is appropriate here, but if we end up saying `produces` and `consumes` are required in some cases, we need to address this as we *will* get support questions about it, or people would end up doing crazy things and the tools will suffer.

**Comment by whaley** [comment]
any news on this?

**Comment by webron** [comment]
@whaley too bad GitHub's reactions don't have the one that I want.

**Comment by handrews** [comment]
@webron `produces` and `consumes` were dropped in 3.0, right?  I think this issue is no longer relevant.

**Comment by philsturgeon** [comment]
Since v2.x is not being worked on, and produces and consumes were dropped in v3.0 as @handrews has said, let's get this outta here.
