### ISSUE TITLE
Include JSend in OpenAPI Spec

### ISSUE THREAD

**Issue by pascencio** [OAI/OpenAPI-Specification#2664]
Hi guys!

Today a coworker shared with us this repository: https://github.com/omniti-labs/jsend.

Always developers have to deal with this kind of decisions or consume APIs with little bit documentation. So, with this kind of specs ours APIs can be self explanatory for convention.

You could considerate include this in a next version of Open API Spec?

**Comment by darrelmiller** [comment]
The OpenAPI specification is intended to provide support for any kind of HTTP APIs.  It tries not to provide opinions on how you should design your API.  

Anyone is free to use jsend with OpenAPI.  Personally, that is not a pattern I would recommend, but OpenAPI should do nothing to prevent it, nor encourage it.

**Comment by pascencio** [comment]
Thanks for the answer @darrelmiller. Which pattenr do you recommend?

**Comment by darrelmiller** [comment]
I recommend that developers use the HTTP capabilities as they were designed.  HTTP status codes and HTTP headers can be used to return metadata about the request/response.  The response body should be used for the data.  Duplicating HTTP capabilities inside the response body causes people to re-invent wheels that have been tried, tested and proven over a long period of time.

**Comment by pascencio** [comment]
> I recommend that developers use the HTTP capabilities as they were designed. HTTP status codes and HTTP headers can be used to return metadata about the request/response. The response body should be used for the data. Duplicating HTTP capabilities inside the response body causes people to re-invent wheels that have been tried, tested and proven over a long period of time.

Thanks @darrelmiller
