### ISSUE TITLE
Api End point is exposed even if PropertyValue bool = false of Navigational property

### ISSUE THREAD

**Issue by dilipmurugeshkumar** [OAI/OpenAPI-Specification#2688]
*Short summary (3-5 sentences) describing the issue.*
Swagger displays API on the UI even if PropertyValue bool = false
OData validation rules do not currently check if annotations containing properties of navigation or property paths are valid or reachable

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

![image](https://user-images.githubusercontent.com/81243054/131499869-4f414a17-0dff-4349-a5d3-5c84e5544861.png)
![image](https://user-images.githubusercontent.com/81243054/131499903-5c2307f1-7936-4712-904c-35de975e87a6.png)

We see that even though property value bool = false, we still see the API end points exposed on the swagger UI

The above IEdmModel is parsed and converted to OpenApiDocument and later which is displayed in swagger
 
![image](https://user-images.githubusercontent.com/81243054/131499988-6fe7f249-a670-4766-8dc9-a9b30703cf56.png)

![image](https://user-images.githubusercontent.com/81243054/131500049-8a29e0c3-ed75-43cb-807d-a0e98ac570d3.png)
 
The End points Put, Post and Delete should not be displayed as it is not reachable. This may be because of the property value attribute bool = false.
This causes an issue when trying to invoke these api’s
For Example If I try to post 
 
 
![image](https://user-images.githubusercontent.com/81243054/131500077-d042c399-e649-46df-9c29-1bb19b4de754.png)
![image](https://user-images.githubusercontent.com/81243054/131500105-565f5c15-c7ab-4390-865b-c6b7a8de638d.png)

As we can see the endpoint does not exists and there by we get 405 exception. Is the exception occurring due to property value attribute bool = false? And the swagger displaying the endpoint. What should be done to hide such API's

### Expected result

All the API End points which are not reachable should not be displayed on swagger. 

### Actual result

The API End points which are not reachable are displayed on swagger. 

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by webron** [comment]
This issue should be filed with the library you're using to generate your API definition. In my experience it is not an issue with Swagger UI as that just renders what it's provided, so if it renders something you don't expect, it means whatever is generating the API definition provides it.
