### ISSUE TITLE
Does the date format not support the nanosecond format?

### ISSUE THREAD

**Issue by Azunyan1111** [OAI/OpenAPI-Specification#2701]
Does the date format not support the nanosecond format?

In the Go language, the nanosecond format exists in the standard package.

There is no description in json scheme and RFC3339.
So OpenAPI will never support nanoseconds?

https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.1

  
https://pkg.go.dev/time#RFC3339Nano
```
RFC3339     = "2006-01-02T15:04:05Z07:00"
RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
```

**Comment by karenetheridge** [comment]
In the ABNF for RFC3339, that you linked to: `   time-secfrac    = "." 1*DIGIT` means that any number of digits after the decimal point are valid.

**Comment by MikeRalphson** [comment]
Please chase if the above didn't answer your question.
