### ISSUE TITLE
format extensions are poorly specified

### ISSUE THREAD

**Issue by karenetheridge** [OAI/OpenAPI-Specification#2715]
In https://spec.openapis.org/oas/v3.1.0#data-types, a few new formats are introduced, but they are not defined. How are implementations to validate these?

- is "password" purely informational? Perhaps it should be deprecated and replaced with a suggestion to use "writeOnly: true".
- the others all pertain to numbers and/or integers, and should be easy to specify, but the implementor should not have to guess what the semantics are. e.g. "integers with the int32 format must be greater than or equal to -2**32 and less than or equal to 2**32" (I have intentionally introduced an error in this definition to force the reader of this issue to think about it more, rather than copy my work) :)

**Comment by darrelmiller** [comment]
The goal has been to move the definition of these formats into a registry and not have them part of the specification.

**Comment by handrews** [comment]
@karenetheridge is the current state of the [format registry)[https://spec.openapis.org/registry/format/) sufficient?
