### ISSUE TITLE
Proposal: Allow deprecated on attributes that use $refs

### ISSUE THREAD

**Issue by crosbyb-apothesource** [OAI/OpenAPI-Specification#2716]
The title sums it up: permit the use of `deprecated` on an object attribute that uses `$refs`. Sometimes I need to deprecate an object attribute that is defined by a schema, _but not not the schema itself_, and that's not currently possible directly.

I think a workaround would be using switching to an anonymous/in-line object definition and deprecating that, but that would also change the code generation for some of my clients so is not preferable.

**Comment by hkosova** [comment]
This is already supported in OpenAPI 3.1 - you can have any sibling properties alongside a `$ref` in a schema.

```yaml
type: object
properties:
  foo:
    $ref: '#/components/schemas/Foo'
    deprecated: true
```

**Comment by crosbyb-apothesource** [comment]
Oh that is GREAT..thanks for pointing it out!
