### ISSUE TITLE
Refresh token URL

### ISSUE THREAD

**Issue by myalban** [OAI/OpenAPI-Specification#272]
Hi,

On the securityDefinitions, I see the field "tokenUrl"  to call the url to get the access_token in case of Oauth 2.0 password for exemple.

But is it possible to add also the "tokenUrlRenew" to describe the URL to call to renew the access_token with the refresh_token

Thanks

**Comment by webron** [comment]
Unfortunately, this did not get into the Swagger 2.0 spec. However, you can use the vendor extension definitions to add that information for now.

**Comment by RobDolinMS** [comment]
@myalban Is this sufficiently resolved in the latest OpenAPI Spec v3 release?  https://github.com/OAI/OpenAPI-Specification/releases

**Comment by LasneF** [comment]
@webron  should this ticket be closed and not part of the OpenAPI.next Label as it looks to me correctly addressed in the OAS 3.1 
https://spec.openapis.org/oas/latest.html#oauth-flow-object

**Comment by handrews** [comment]
@LasneF yup, this got done!  🎉
