### ISSUE TITLE
JSON Reference mention in 3.1.0

### ISSUE THREAD

**Issue by char0n** [OAI/OpenAPI-Specification#2738]
Hi all,

There is a single occurrence of `JSON reference` words withing the 3.1.0 spec:

> Note that in the use of operationRef, the escaped forward-slash is necessary when using JSON references.

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operationref-examples

This might be confusing, as it's not clear what JSON references really means here. I assume it is refereing to https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03, but I'm not really sure.

IMHO it would be more appropriate to have following sentence:

>  Note that in the use of operationRef, the escaped forward-slash is necessary when using JSON Pointer in fragment identifier part of the URI

...and have JSON Pointer link to [JSON Pointer specification](https://datatracker.ietf.org/doc/html/rfc6901).

**Comment by handrews** [comment]
You may be interested in the general [referencing discussion](https://github.com/json-schema-org/referencing) that has recently started, partially in response to the continued use of the decade-old JSON Reference draft (and yes, in this case and in AsyncAPI, it is referring to draft-pbryan-zyp-json-ref-03).

**Comment by handrews** [comment]
Yeah this should point to JSON Pointer.  Added to 3.1.1.

**Comment by lornajane** [comment]
Fixed by @handrews in #3731, #3747 and #3748 so I'll resolve.
