### ISSUE TITLE
"path parameters MUST NOT contain any unescaped “generic syntax” characters"

### ISSUE THREAD

**Issue by karenetheridge** [OAI/OpenAPI-Specification#2804]
at https://spec.openapis.org/oas/v3.1.0#path-templating:

> The value for these path parameters MUST NOT contain any unescaped “generic syntax” characters described by [RFC3986]: forward slashes (/), question marks (?), or hashes (#).

Is this referring to the *name* of the path parameter, or the *value itself*?

For example, for the path template `/pets/{petId}`, is it "petId" itself (which is the `name` clause in the parameter specification) that cannot contain these characters -- that is, a restriction on the openapi document itself? or is it the *value* of this parameter, at runtime, that cannot contain these characters, for example "cat_01" in the URI `/pets/cat_01`?

Either way, the language in the specification here could do with a little tightening.

This question has also come up in https://github.com/OAI/OpenAPI-Specification/issues/2564.

**Comment by hkosova** [comment]
The value. See [#892#issuecomment-281170254](https://github.com/OAI/OpenAPI-Specification/issues/892#issuecomment-281170254). That sentence was added to indicate that the scenario from #892 is currently not supported.

**Comment by hkosova** [comment]
I wonder if the _names_ of path parameters are supposed to be restricted to the [`varname`](https://datatracker.ietf.org/doc/html/rfc6570#section-2.3) ABNF from RFC 6570, URI Template. OAS itself currently places no restrictions on path parameter names so technically a space " " can be considered be a valid name.

**Comment by karenetheridge** [comment]
In that case, commit ce732af10 should be reverted, and possibly replaced with something else - even if just `^[^}]+$` (the name of path parameters can be anything as long as it doesn't contain a closing curly brace).

(I see quite a lot of discussion in old tickets about supporting more of the RFC 6570 syntax in the path specification -- iI hope it is still under consideration!)

**Comment by handrews** [comment]
@karenetheridge did PR #3415 getting merged address everything for this issue?

**Comment by handrews** [comment]
Looking at this more closely, it was definitely fixed by PR #3415.  Closing!
