### ISSUE TITLE
3.0 JSON schema does not allow $ref in property

### ISSUE THREAD

**Issue by hauntingEcho** [OAI/OpenAPI-Specification#2824]
Per the [documentation](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schemaObject):

"properties - Property definitions MUST be a Schema Object and not a standard JSON Schema (inline or referenced)."

Currently, the 3.0 schema does not allow properties to be a $ref to a schema.  My reading of the documentation is equivalent to "Property definitions MUST be an inline or referenced Schema Object, not an inline or referenced JSON Schema".

* The spec should probably be clarified between my interpretation and something like "Property definitions MUST be an inline Schema Object, not an inline or referenced JSON Schema".
* If my interpretation is correct, the schema in this repo should be updated

**Comment by jdesrosiers** [comment]
The schema already does allow you to reference properties, https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.yaml#L295..L300

**Comment by hkosova** [comment]
Also, this paragraph means that property definitions can be $ref'erenced:

> Alternatively, any time a Schema Object can be used, a [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#referenceObject) can be used in its place. This allows referencing definitions instead of defining them inline.

**Comment by webron** [comment]
Seems like the issue has been answered.

**Comment by hauntingEcho** [comment]
You're right.  Not sure if I had an old version cached in my IDE or what my issue was, but it doesn't seem to be complaining today.
