### ISSUE TITLE
What is the regex dialect used by springdoc-openapi?

### ISSUE THREAD

**Issue by du-it** [OAI/OpenAPI-Specification#2830]
OpenApi uses springdoc-openapi but I can find any information about the implemented regex dialect anywhere? 
Where can I get this information from?

**Comment by karenetheridge** [comment]
https://spec.openapis.org/oas/v3.1.0#schema-object

OpenAPI 3.1 uses JSON Schema draft2020-12, which is defined here:  https://json-schema.org/specification.html

Regular expressions in particular are specified here: https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.6.4

**Comment by webron** [comment]
The regex dialect is defined in each version of the spec. You'd need to look at the version you're using to figure it out. We have no affiliation with any tools and can't comment as to what springdoc-openapi supports specifically (would be better to ask them).
