### ISSUE TITLE
JSON Schema for Responses object is incorrect in light of extensions

### ISSUE THREAD

**Issue by ahl** [OAI/OpenAPI-Specification#2833]
The 3.0.3 spec says this about the Responses object:
> The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.

3.1.0 says something similar:

> The Responses Object MUST contain at least one response code, and if only one response code is provided it SHOULD be the response for a successful operation call.

Here's the JSON Schema for 3.0.3:

```json
    "Responses": {
      "type": "object",
      "properties": {
        "default": {
          "oneOf": [
            {
              "$ref": "#/definitions/Response"
            },
            {
              "$ref": "#/definitions/Reference"
            }
          ]
        }
      },
      "patternProperties": {
        "^[1-5](?:\\d{2}|XX)$": {
          "oneOf": [
            {
              "$ref": "#/definitions/Response"
            },
            {
              "$ref": "#/definitions/Reference"
            }
          ]
        },
        "^x-": {
        }
      },
      "minProperties": 1,
      "additionalProperties": false
    },
```

Note that the `minProperties` attempts to enforce the restriction noted above, but it inadvertently counts extensions. In other words, the following is valid according to the schema, but not according to the spec:

```json
{
  "x-no-responses-at-all": "muahaha"
}
```

Note that 3.1 doesn't appear to try to enforce this in the schema:

```json
    "responses": {
      "type": "object",
      "properties": {
        "default": {
          "$ref": "#/$defs/response-or-reference"
        }
      },
      "patternProperties": {
        "^[1-5](?:[0-9]{2}|XX)$": {
          "$ref": "#/$defs/response-or-reference"
        }
      },
      "$ref": "#/$defs/specification-extensions",
      "unevaluatedProperties": false
    },
```

**Comment by karenetheridge** [comment]
related: https://github.com/OAI/OpenAPI-Specification/pull/2799

**Comment by ahl** [comment]
@karenetheridge how did you address this in #2799? It seems like extension properties would satisfy your `minProperties: 1`, no?

**Comment by karenetheridge** [comment]
Yes, there is no `contains`-like keyword for objects that specifies that a property matching a particular regex must be present.

Actually, I thought of a way... I have submitted it as https://github.com/OAI/OpenAPI-Specification/pull/3093. \o/
