### ISSUE TITLE
Support API mounting

### ISSUE THREAD

**Issue by MaxenceMaire** [OAI/OpenAPI-Specification#2854]
This follows [a comment on issue #647](https://github.com/OAI/OpenAPI-Specification/issues/647#issuecomment-444612891).

It would be great to be able to mount API specs onto another spec for service composition.

As an example, I have two independent services A and B, both having their own OAS files. I would like to 'merge' A and B together into a single, centralized spec.

If both services have, say, a `/resource` endpoint, I would like to discriminate them by prefixing their paths with the name of the services, `/A` and `/B` respectively (resulting in `/A/resource` and `/B/resource`).

One naive solution would be to list and redefine each path in the root OAS file and `$ref` the related A or B content, but changing the design of either A or B would require updating the root OAS file.

A possible alternative would be to support path nesting (discarded [here](https://github.com/OAI/OpenAPI-Specification/issues/647)):

```
paths:
  '/A':
    '/resource':
       get:
           # ....
  '/B':
    '/resource':
       get:
           # ....
```

I suggest considering introducing a `mount` field under [Path Item Objects](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#path-item-object) and taking a [Paths Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#paths-object):

```
paths:
  '/A':
    mount:
      $ref: 'A.yaml#/paths'
  '/B':
    mount:
      $ref: 'B.yaml#/paths'
```

**Comment by SmallhillCZ** [comment]
I have the same use case, but I would rather show in some way, that under this path there is another API with its own spec and reference not the paths included in its OAS, but the full OAS file.

**Comment by nickshoe** [comment]
Another possibility could be to allow multiple `$ref` right under `paths`:

```yaml
...
info: ...
tags: ...
...
paths:
  $ref: './service-a.yaml#/paths'
  $ref: './service-b.yaml#/paths'
```
Assuming that the content of the referenced file is the following:
```yaml
# service-a.yaml
...
paths:
  '/service-a/foo':
    ...
```
```yaml
# service-b.yaml
...
paths:
  '/service-b/bar':
    ...
```

The root spec content would finally be rendered as:
```yaml
...
info: ...
tags: ...
...
paths:
  '/service-a/foo':
    ...
  '/service-b/bar':
    ...
```
Is this simplistic? Am I missing some hidden aspect about why it could be done this way?

**Comment by MaxenceMaire** [comment]
> I have the same use case, but I would rather show in some way, that under this path there is another API with its own spec and so I would rather reference not the paths included in its OAS, but the full OAS file. So more like a link to another API than a $ref.

@SmallhillCZ You make a good point. Especially since mounted APIs can live on different servers (or to specify useful metadata), I think it makes sense to include a complete OAS and not just the paths. A `$ref` could still work though I guess? (e.g. `$ref: 'A.yaml'` instead of `$ref: 'A.yaml#/paths'`).

**Comment by nickshoe** [comment]
@MaxenceMaire thanks for clarifying the use of `$ref`.

My example was an alternative proposal. Anyways, I like your proposal too (I've put a thumbs up).

We ended up defining separate OpenAPI documents for each microservice and using them independently. It would be nice to be able to squash together separate specs, without having to break them down according to the root keys of the spec. If conflicts arise, then one should handle them by changing one of the sub-specs.

**Comment by gimbimloki** [comment]
@nickshoe @MaxenceMaire

I asked "Reference Objects in Paths Object". 
As a rsult, it is duplicated keys and it is not allowed in YAML/JSON.
I think we should find another? altinative? way.

- https://github.com/OAI/OpenAPI-Specification/pull/2657#issuecomment-1456541755

**Comment by handrews** [comment]
I believe this is addressed by OAS 4 Moonwalk's [separation of concerns principle](https://www.openapis.org/blog/2023/12/06/openapi-moonwalk-2024).  Specifically:

* https://github.com/OAI/sig-moonwalk/discussions/66

I'm going to close this as "moved to moonwalk", but please join the linked discussion if you are still interested!
