### ISSUE TITLE
passing boolean but receiving string 

### ISSUE THREAD

**Issue by abhishekdhadwal** [OAI/OpenAPI-Specification#2855]
"/Profile/other_user/report_block": {
    "put": {
        "tags": [
            "Profile"
        ],
        "summary": "User report block users Api",
        "requestBody": {
            "content": {
                "application/x-www-form-urlencoded": {
                    "schema": {
                        "type": "object",
                        "properties": {
                            "user_id": {
                                "description": "Pass here user _id",
                                "type": "string",
                                "format": "string"
                            },
                            "is_blocked": {
                                "type": "boolean"
                            },
                            "is_reported": {
                                "type": "boolean"
                            },
                            "language": {
                                "description": "valid languages are ENGLISH & ARABIC",
                                "type": "string",
                                "format": "string",
                                "enum": [
                                    "ARABIC",
                                    "ENGLISH"
                                ],
                                "default": "ENGLISH"
                            }
                        },
                        "required": [
                            "user_id",
                            "language"
                        ]
                    }
                }
            }
        },
        "responses": {
            "default": {
                "description": "successful operation"
            }
        },
        "security": [
            {
                "access_token": [
                    "access_token"
                ]
            }
        ]
    }
}
[openapi_3.1.0_issue.txt](https://github.com/OAI/OpenAPI-Specification/files/7837314/openapi_3.1.0_issue.txt)

**Comment by handrews** [comment]
Your `is_blocked` and `is_reported` fields look to be correctly specified as booleans.  This sounds like an issue with the tools that you are using to parse the body —`application/x-www-form-urlencoded` is a text format, so I am assuming you are using a tool that parses the body using these schemas.  I would suggest raising this issue with the maintainers of that tool.

I don't see any specification issue here, so I am closing this.  Please do re-open/re-file and clarify where you think the specification has a problem if I have misunderstood.
