### ISSUE TITLE
[Feature Request] Reusable groups of parameters for operations

### ISSUE THREAD

**Issue by jmcanterafonseca-iota** [OAI/OpenAPI-Specification#2871]
Rationale:

There can be situations where a group of parameters is needed for multiple operations. Currently you can reuse the definitions by enumerating them by using the $ref construct.

```yaml
parameters:
  - $ref: '#/components/parameters/p1'
  - $ref: '#/components/parameters/p2'
```
 but  you would need to duplicate the same enumeration across all the operations where the same parameter group is required. 

A possible solution would be to allow the parameters element to be able to point to another JSON element that contain the parameters enumeration, for instance one operation can declare that its parameters are just the same as another operation, see below

```yaml
   parameters:
      $ref: '#/paths/%2Fanotheroperation/parameters' 
 ```

**Comment by webron** [comment]
Closing in favor of #445.
