### ISSUE TITLE
Is media type text/calendar supported?

### ISSUE THREAD

**Issue by atye** [OAI/OpenAPI-Specification#2876]
https://datatracker.ietf.org/doc/html/rfc5545

Are there plans to support media type `text/calendar`? Or is there an existing media type that satisfies this?

**Comment by webron** [comment]
It's supported!

**Comment by atye** [comment]
@webron 

I couldn't find any examples of it. Is this right? I don't see any errors with this but I am not 100% sure.

```
responses:
  "200":
    description: A successful response
    content:
      text/calendar:
        schema:
          description: Calendar response.
```

**Comment by webron** [comment]
Yup, that works. You don't even need the `schema` in this case.

**Comment by atye** [comment]
@webron 

What is the correct syntax without the schema? The swagger editor gives me a `should be object` error with the following specification on `text/calendar`.

```
responses:
  "200":
    description: A successful response
    content:
      text/calendar:
```

**Comment by webron** [comment]
This should work:
```
responses:
  "200":
    description: A successful response
    content:
      text/calendar: {}
```

**Comment by atye** [comment]
@webron 

I see that works. Thank you for your help!
