### ISSUE TITLE
OpenAPI Generator doesn't add "suspend" keyword when response is array of string. Kotlin, Reactive

### ISSUE THREAD

**Issue by alxdv97** [OAI/OpenAPI-Specification#2882]
I have two similar REST method described in openapi .yaml, **/api/statuses** responses an object wrapping array of strings, **/api/statuses/flow** responses plain array of strings:

openapi: 3.0.3
info:
  title: 'Some title'
  version: 5.0-oas3
servers:
  - url: 'http://localhost:8880/'
    description: 'localhost'
paths:
  /api/statuses:
      get:
        tags:
          - controller
        summary: List of statuses
        operationId: getStatuses
        responses:
          '200':
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/StatusesResponse'
          '400':
            description: Bad Request

    /api/statuses/flow:
      get:
        tags:
          - controller
        summary: List of statuses as Flow
        operationId: getStatusesFlow
        responses:
          '200':
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          '400':
            description: Bad Request

components:
  schemas:
     StatusesResponse:
        type: object
        description: Wrap for array of string
        properties:
          statuses:
            type: array
            items:
              type: string
              example: APPROVED
              description: Array of statuses

So, OpenAPI generator generates interfaces due to this spec like this:

` @RequestMapping(
            value = ["/api/statuses"],
            produces = ["application/json"], 
            method = [RequestMethod.GET])
    suspend fun getStatuses(): ResponseEntity<StatusesResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @RequestMapping(
            value = ["/api/statuses/flow"],
            produces = ["application/json"], 
            method = [RequestMethod.GET])
    fun getStatusesFlow(): ResponseEntity<Flow<kotlin.String>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

data class StatusesResponse(

    @JsonProperty("statuses") var statuses: kotlin.collections.List<kotlin.String>? = null
) {

}`

Note that method, that returns ResponseEntity<StatusesResponse> marked as **suspend** but method, that returns ResponseEntity<Flow<kotlin.String>> **doesn't** marked as **suspend**.

So, I can't override getStatusesFlow() in my class, because if I use kotlinx.coroutines.flow.Flow in method, method must be suspend in all its hierarchy:

`
case A:
override fun getStatusesFlow(): ResponseEntity<Flow<String>> {
        return satstusService.getStatusesFlow().toResponseEntity() } //compilation error here - satstusService.getStatusesFlow() returns Flow<String>, demands calling from coroutine or suspend context
 
case B:
override suspend fun getStatusesFlow(): ResponseEntity<Flow<String>> { //compilation error here - demands adding **suspend** to all method's hierarchy, but I can't due to fact that interface is auto-generated by OpenAPI Generator
        return satstusService.getStatusesFlow().toResponseEntity() }
`

My pom spec:

`
<properties>
        <oas-plugin.version>4.3.1</oas-plugin.version>
        <openapi.inputSpec>${project.basedir}/src/main/resources/static/openapi-spec-api.yaml</openapi.inputSpec>
        <openapi.basePackage>com.alxdv.status</openapi.basePackage>
</properties>

<plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.3.1</version>
                <executions>
                    <execution>
                        <id>spring</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${openapi.inputSpec}</inputSpec>
                            <generatorName>kotlin-spring</generatorName>
                            <apiPackage>${openapi.basePackage}.api</apiPackage>
                            <modelPackage>${openapi.basePackage}.model</modelPackage>
                            <addCompileSourceRoot>true</addCompileSourceRoot>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generatorName>kotlin-spring</generatorName>
                            <typeMappings>
                                <mapping>file=org.springframework.http.codec.multipart.FilePart</mapping>
                                <typeMapping>double=java.math.BigDecimal</typeMapping>
                            </typeMappings>
                            <configOptions>
                                <enumPropertyNaming>original</enumPropertyNaming>
                                <gradleBuildFile>false</gradleBuildFile>
                                <useTags>true</useTags>
                                <interfaceOnly>true</interfaceOnly>
                                <reactive>true</reactive>
                                <exceptionHandler>false</exceptionHandler>
                                <swaggerDocketConfig>false</swaggerDocketConfig>
                                <modelMutable>true</modelMutable>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
`
SpringBoot version 2.4.2, kotlin version 1.5.10, jvm version 11, openApi spec plugin version 4.3.1

**Comment by alxdv97** [comment]
Yaml pastes incorrectly, so put it here 
openapi: 3.0.3
info:
  title: 'Some title'
  version: 5.0-oas3
servers:
  - url: 'http://localhost:8880/'
    description: 'localhost'
paths:
  /api/statuses:
      get:
        tags:
          - controller
        summary: List of statuses
        operationId: getStatuses
        responses:
          '200':
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/StatusesResponse'
          '400':
            description: Bad Request

    /api/statuses/flow:
      get:
        tags:
          - controller
        summary: List of statuses as Flow
        operationId: getStatusesFlow
        responses:
          '200':
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
          '400':
            description: Bad Request

components:
  schemas:
     StatusesResponse:
        type: object
        description: Wrap for array of string
        properties:
          statuses:
            type: array
            items:
              type: string
              example: APPROVED
              description: Array of statuses

**Comment by webron** [comment]
The OpenAPI Initiative does not provide, support or endorse any specific tool around the spec. Please file the issue with the respective project.

**Comment by gellaig** [comment]
@alxdv97 
Did you find any solution to this? I am curious as i have the same issue.

Thanks!
