### ISSUE TITLE
the SecuritySchemeIn param in SecurityScheme annotation

### ISSUE THREAD

**Issue by situkangsayur** [OAI/OpenAPI-Specification#2894]
Hello,
I am using kotlin and springboot with the openAPI, then want to use the security scheme to lock the swagger UI with a specific security scheme (Ex. basic). But when I want to choose the value for parameter **"in"** in the SecurityScheme annotation (_io.swagger.v3.oas.annotations.security.SecurityScheme_) with SecuritySchemeIn the build process gave me an error for "kotlin mixing named and positioned arguments" or the gradle expecting an expression, it expecting ')' just like looping expression.

Could you change the name of the parameter to be more unique maybe like _securitySchemeIn_ or _schemaIn_ to make it different from the expression term in kotlin-lang?

Or maybe there is another way to use **in** param in SecuritySchema but still use annotation? 

Thank you.

Regads,

**Comment by webron** [comment]
This looks like a tooling question. Please file the issue with the tool that you use.
