### ISSUE TITLE
How about generate types from json-schemas

### ISSUE THREAD

**Issue by diveDylan** [OAI/OpenAPI-Specification#2897]
Hi, i forked [typescript DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo and want to add `@types/openapi-specification` for typescript user who want to make tool depend on OpenAPI Specification.

Can i use `@types/openapi-specification` name for types ， if you allowed to do that  ：)

**Comment by handrews** [comment]
Naming something "openapi-specification" that is not the OpenAPI Specification, is not owned by the OpenAPI initiative, and is in fact only an implementation of one aspect of the spec (and not really even OpenAPI, but JSON Schema), would be considered impolite (at best).  I am not a lawyer and do not know whether there are legal trademark issues involved or not.  But you should find a name that will not lead to confusion regarding whether this project owns it.
