### ISSUE TITLE
Is it possible to use constants in Swagger XML documentation?

### ISSUE THREAD

**Issue by Harmyder** [OAI/OpenAPI-Specification#2898]
Is it possible for me to avoid code duplication like this by using the constant right in the Swagger doc?

```
/// <response code="422">Logical conditions are not satisfied. The following error codes can be returned.
/// <ol>
/// <li>5555 - Failed to ....</li>
/// </ol>
/// </response>
```

I also have this error description stored in a variable:

`string error5555 = "Failed to ...."`

https://stackoverflow.com/questions/71515577/code-duplication-in-swagger-xml-doc-and-actual-c-sharp-code

**Comment by webron** [comment]
This may be a tool specific question, and in that case you should open the ticket on the tool you're using. Generally speaking, OpenAPI does not have an XML representation.
