### ISSUE TITLE
[request] Add not example to the spec

### ISSUE THREAD

**Issue by spacether** [OAI/OpenAPI-Specification#2911]
How about adding a not composition example to the spec?

**Comment by handrews** [comment]
@spacether what would be the purpose of including such an example?  `not` is a JSON Schema keyword and OpenAPI has no opinion on what you do with it.

**Comment by spacether** [comment]
Just because there are allOf, anyOf, and oneOf examples but no not example.

**Comment by handrews** [comment]
One of the reasons to have full JSON Schema compatibility in OAS 3.1 was to get OAS _out_ of the business of educating people about JSON Schema.  JSON Schema can do that.

While there are examples using `allOf`, `anyOf`, and `oneOf`, they are all done in the context of other OpenAPI functionality such as `discriminator`.  There is no usage of `not` that is specific to OpenAPI, so such an example does not belong in the OAS spec.
