### ISSUE TITLE
Generate datastructure out of openAPI JSON schema.

### ISSUE THREAD

**Issue by arunkumar413** [OAI/OpenAPI-Specification#2913]
Hello Team,

I'm trying to generate openAPI document generator but facing issues trying to parse the specification. Could you please create a small tool that parses the spec doc and generates data structures relevant to various programming languages.  Such data structures helps users write UI components to document the API.  Although JSON schema can be considered a data structure but it would much easier if we convert/parse into native data structures of the programming languages. 

Example below is the JavaScript data structure that we can create out the JSON Schema. Then using react and or any UI tool we can just map through the data structure to create the api document. If we directly parse JSON schema (without the JS data structure)  and create UI we might have to do a lot checking if the variable is a string or object before looping and have to deal with the complexity created by the nested objects.

Thanks,
Arun

```
let getPet = {
    path: '/pet',
    method: 'get',
    queryParams: [{ id: 33434, name: 'Tommy' }],
    requestInfo: [
        {
            contentType: 'application/json', schema: { name: 'username', id: 34343 },
            responseType: 'application/json', schema: { name: 'username', id: 34343 },
            responseCodes: [{ code: 200, description: "OK" }, { code: 404, description: 'Not found' }]
        },
        {
            contentType: 'application/xml', schema: { name: 'username', id: 34343 },
            responseType: 'application/xml', schema: { name: 'username', id: 34343 },
            responseCodes: [{ code: 200, description: "OK" }, { code: 404, description: 'Not found' }]

        }

    ]
}



let postPet = {
    path: '/pet',
    method: 'post',
    queryParams: [{ id: 33434, name: 'Tommy' }],
    requestInfo: [

        {
            contentType: 'application/json', schema: { name: 'username', id: 34343 },
            responseType: 'application/json', schema: { name: 'username', id: 34343 },
            responseCodes: [{ code: 200, description: "OK" }, { code: 404, description: 'Not found' }]
        },
        {
            contentType: 'application/xml', schema: { name: 'username', id: 34343 },
            responseType: 'application/xml', schema: { name: 'username', id: 34343 },
            responseCodes: [{ code: 200, description: "OK" }, { code: 404, description: 'Not found' }]

        }

    ]
}

export const paths = [getPet, postPet]

```

**Comment by webron** [comment]
This is out of scope for OAI as we don't actively develop or host any tools. The JSON Schema folks are working on additional code/form generation efforts around JSON Schema, you can find out more information in their repo(s).
