### ISSUE TITLE
[Documentation] Analytcs image at the bottom of readme is broken.

### ISSUE THREAD

**Issue by omartarek206** [OAI/OpenAPI-Specification#2915]
In the [Licensing](https://github.com/OAI/OpenAPI-Specification#licensing) section at the bottom of the readme file, the analytics image is broken.

![image](https://user-images.githubusercontent.com/40853054/163893187-0fb480d4-5c77-4689-ab80-bf8b7bfa997d.png)

Clicking on the link to the image itself shows the error message "Error Fetching Resource".

**Comment by LasneF** [comment]
@handrews  this one can be closed 

it has been solved with this commit 
https://github.com/OAI/OpenAPI-Specification/pull/2956/files

**Comment by handrews** [comment]
Thanks, @LasneF - we're almost down to 350 issues in the backlog!
