### ISSUE TITLE
websockets?

### ISSUE THREAD

**Issue by JC3** [OAI/OpenAPI-Specification#2947]
is there a proposal to add websocket endpoint descriptions?

i couldn't find anything about them in the spec (which actually seems kind of strange...), although this is my first time looking through it.

**Comment by darrelmiller** [comment]
OpenAPI describes HTTP APIs.  WebSockets is a different protocol and therefore out of scope.

**Comment by JC3** [comment]
> OpenAPI describes HTTP APIs. WebSockets is a different protocol and therefore out of scope.

makes sense, but also, websockets are so common that omitting them leaves kind of a big gap in the spec universe. 

openapi's scope could be expanded; the definition of the scope _is_ in our control, after all.

**Comment by webron** [comment]
Given our focus currently, it's unlikely that we'll change the scope of the OpenAPI. The scope is actually not within our control but is part of the charter which is a bit more involved to modify (not impossible, just takes more work). We're not saying there's no gap, but at least to some extent, other specs like AsyncAPI may be better suited to fill the gap (if they haven't already).
