### ISSUE TITLE
Add Security Considerations section

### ISSUE THREAD

**Issue by ioggstream** [OAI/OpenAPI-Specification#2950]
## I expect

- a Security Consideration section / document

## Instead

- there is not
- some security hints are scattered throughout the document

See https://github.com/ietf-wg-httpapi/mediatypes/pull/49/files#diff-b22c3a369e1499074590046ad01b71334e21c491c64ccf045f8858e2d3036e56R543

cc: @darrelmiller

**Comment by MikeRalphson** [comment]
Link #3037

**Comment by handrews** [comment]
@OAI/tsc / @darrelmiller is this done?  Should we add the currently-separate Security Considerations document into 3.0.4 and 3.1.1 as a section?

**Comment by ralfhandl** [comment]
> Should we add the currently-separate Security Considerations document into 3.0.4 and 3.1.1 as a section?

Yes, please, and add links to corresponding specification sections to the text.

**Comment by miqui** [comment]
@ralfhandl , @handrews I would like to up vote Ralf's suggestion.

**Comment by darrelmiller** [comment]
TDC consensus to move this content into the patch updates. Suggestion to add headings to make it clearer.

**Comment by handrews** [comment]
PR merged for 3.0.4 and ported to 3.1.1 via PR #3921!
