### ISSUE TITLE
OpenApi Spring Boot - Show date as yyyyMMdd

### ISSUE THREAD

**Issue by dbnex14** [OAI/OpenAPI-Specification#2957]
In my request model, I have a field like

    @NotNull
    @Schema(example = "19680228", type = "String", format = "yyyyMMdd", pattern = "([0-9]{4})(?:[0-9]{2})([0-9]{2})", required = true, nullable = false)
    @JsonDeserialize(using = CustomDateDeserializer.class)
    private OffsetDateTime birthDate;

My `birthday` is of `OffsetDateTime` type, however, request comming in contains only date portion in format yyyyMMdd.  This is requirement and cannot be changed.  And this is OK, I already take care of that with my `CustomDateDeserializer` and it is all working fine.

Based on OpenAPI documentation and some post (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#data-types, https://stackoverflow.com/questions/49379006/what-is-the-correct-way-to-declare-a-date-in-an-openapi-swagger-file), I know that OpenAPI supports ISO8601 `date` and `date-time`, in which case, no `pattern` is needed and type should be provided as `date` or `date-time`.

However, in case you require some other format, the documentation states that `type` should be `String`, `format` should specify which format the date is in, and `pattern` should be provided as regex.

And this is exactly what I am doing in the above `@Schema` annotation.  

However, when I go to https://editor.swagger.io/ and paste my .**yaml** file into it, the API generated for both my request model and my controller still contain incorrect formatting for `birthdate` and the `example` is not even taken into consideration:

Here is how it shows in my model:
[![enter image description here][1]][1]

As you can see, the `format` is still getting the format for `OffsetDateTime` and there is no example at all.

Same for my controller:

[![enter image description here][2]][2]

How do I make birthday show up as `yyyyMMdd`?  For example, how to make it show as `19720226` in swagger editor?

I am using OpenApi/Swagger 3 in a Spring Boot application.

  [1]: https://i.stack.imgur.com/2jSOq.png
  [2]: https://i.stack.imgur.com/yFxul.png

**Comment by dbnex14** [comment]
What is the relevant repository?  This is releted to OpenApi, Swagger did not have this limitation.
I would not come over here without making lots of research and asking on SO, there are even same related quesions on SO re this from me and others.  Thanks

**Comment by dbnex14** [comment]
> Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.

What is the relevant repository? This is releted to OpenApi, Swagger did not have this limitation.
I would not come over here without making lots of research and asking on SO, there are even same related questions on SO re this from me and others. Thanks

**Comment by MikeRalphson** [comment]
swagger-ui and/or spring-boot repos would be appropriate. This repository is to do with the specification itself. You don't seem to have a problem with the spec or your OAS snippet (though I haven't checked your regex). You generally do not need to provide a `regex` **and** a `pattern`.

**Comment by dbnex14** [comment]
> swagger-ui and/or spring-boot repos would be appropriate. This repository is to do with the specification itself. You don't seem to have a problem with the spec or your OAS snippet (though I haven't checked your regex). You generally do not need to provide a `regex` **and** a `pattern`.

Thanks for explaining.
