### ISSUE TITLE
OpenApi not picking up 'example' from @Schema

### ISSUE THREAD

**Issue by dbnex14** [OAI/OpenAPI-Specification#2961]
In my request model, I have a field like

```
    @NotNull
    @Schema(description = "blahblah", example = "19680228", type = "Date", format = "String", pattern = "([0-9]{4})(?:[0-9]{2})([0-9]{2})", required = true, nullable = false)
    @JsonDeserialize(using = CustomDateDeserializer.class)
    private OffsetDateTime birthDate;
```

As you can see, I have `example = "19680228"` in `@Schema`.

When I go to https://editor.swagger.io/ and paste my .yaml file into it, I would expect that it would pick the `example `up and show the `birthDate `in example section of my endpoint and in my model schema as 19680228.  I would else expect that `example` was generated in yaml when I hit the /api-docs.yaml endpoint but it is not:
![image](https://user-images.githubusercontent.com/8755679/176225007-a3d10acd-b946-4957-ab2c-81f6b4946950.png)

Here is how it shows in my model:
![image](https://user-images.githubusercontent.com/8755679/176228214-53fe19fe-36b1-4c0f-8a01-7d58479a9fec.png)

And here is how Example value of my controller looks:
![image](https://user-images.githubusercontent.com/8755679/176228045-254fd7c7-9453-4bf5-9bcf-c3f2f2357c60.png)

As you can see, the format is still getting the format for `OffsetDateTime `and there is no `example `at all.

However, if I modify yaml in https://editor.swagger.io/ and add example as below:
![image](https://user-images.githubusercontent.com/8755679/176229106-b2e70c94-48a0-4479-817f-bbf118070d85.png)

, then my schema model shows it
![image](https://user-images.githubusercontent.com/8755679/176229275-09e2db76-bf87-4641-b4f4-6422c3f3d1ea.png)

, and also example in controller shows it as 19680210:
![image](https://user-images.githubusercontent.com/8755679/176229514-4fe5b3ac-d3e3-49d5-8a23-c9b2b5bb4a33.png)

So, it looks like OpenApi is not processing `@Schema` properly.

**Comment by erunion** [comment]
Hey you might want to post this in https://github.com/swagger-api/swagger-core. This repo you're in is for the OpenAPI specification, not the generation library you're using where this issue is happening.

**Comment by dbnex14** [comment]
> Hey you might want to post this in https://github.com/swagger-api/swagger-core. This repo you're in is for the OpenAPI specification, not the generation library you're using where this issue is happening.

Thanks
