### ISSUE TITLE
Is this line correct? YAML LSP says the scheme is not valid because of this

### ISSUE THREAD

**Issue by cpkio** [OAI/OpenAPI-Specification#2969]
https://github.com/OAI/OpenAPI-Specification/blob/aa91a19c43f8a12c02efa42d64794e396473f3b1/schemas/v3.0/schema.yaml#L211

**Comment by hkosova** [comment]
Looks correct to me. OAS 3.0's JSON Schema is defined using Draft 4, where the [`exclusiveMinimum`](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.1.3) keyword is a boolean. The `exclusiveM*imum` keywords were [changed from booleans to numbers](https://json-schema.org/draft-06/json-schema-release-notes.html) in JSON Schema Draft 6.

**Comment by MikeRalphson** [comment]
Closing as above.
