### ISSUE TITLE
Error 'required' should not have fewer than 1 items

### ISSUE THREAD

**Issue by sourabhagrawal23** [OAI/OpenAPI-Specification#2985]
Hi,
Is there any way to make the body optional in **Swagger v2**?

I am getting error as the required array is empty in the "Formatting" definition:

["Formatting": {
      "required": [],
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        }
      }
    },](url)

The endpoint does not necessarily need any body. hence, there are no required fields as such.

![image](https://user-images.githubusercontent.com/44314046/181190753-23ab8924-d124-430d-aa63-4e7687fb2c1a.png)

**Comment by hkosova** [comment]
**If all properties are optional, do not include the `required` keyword.**
```json
"Formatting": {
  "type": "object",
  "properties": {
    "code": {
      "type": "string"
    }
  }
},
```

OpenAPI 2.0 uses a version of JSON Schema where the `required` list, if specified, [cannot be empty](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.15) so you would only include this keyword if a schema has at least 1 required property.

An empty list `required: []` is allowed in later JSON Schema versions, such as the one that's used by default in OpenAPI 3.1.

**Comment by MikeRalphson** [comment]
Thanks @hkosova. @sourabhagrawal23 please chase if the above didn't answer your question.
