### ISSUE TITLE
How to add condition to display a schema based on the user type that runs the API?

### ISSUE THREAD

**Issue by adiraz1** [OAI/OpenAPI-Specification#2994]
let say reposne is compound of 
schema1
and right after schema 2

but schema 2 appears only for a specific user that runs the API

**Comment by handrews** [comment]
JSON Schema is not aware of the context in which the schema is used.  Generally, your schema needs to work for all contexts, and your application does any additional context-specific checks.

**Comment by handrews** [comment]
Closing due to no further response.
