### ISSUE TITLE
Updated (draft 2020-12) json schema for openapi v3.0 spec

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [OAI/OpenAPI-Specification#2996]
Currently the [openapi v3.0 schema](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json) is using `draft-04` of json schema. Would it be possible to get an updated version of the schema using `Draft 2019-09` or `2020-12`?  

We are currently using openapi v3.0 and would like to validate the specifications using json schema, but the libraries tend only only support a limited number of json schema versions, having a more recent version of the specification available would help.

**Comment by jdesrosiers** [comment]
You can use this new tool to automatically transform a draft-04 schema to a newer version. https://alterschema.sourcemeta.com/

**Comment by chris-smith-zocdoc** [comment]
That looks promising, thanks @jdesrosiers

**Comment by jeremyfiel** [comment]
There's an appetite to move to newer specs but draft 4 will  be supported for quite some time and most all tooling should still support it.  There are some very large projects on draft 4 still, like MongoDB

**Comment by lornajane** [comment]
Discussed in TDC and agreed that the version of JSON Schema for our schemas should match the version of JSON Schema that is in the version of OpenAPI specification.
