### ISSUE TITLE
Allow extending of parameters (at least renaming them)

### ISSUE THREAD

**Issue by kaznovac** [OAI/OpenAPI-Specification#3003]
assume schema has this paths:

- `/store`
- `/store/{store_id}`
- `/store/{store_id}/offers`
- `/store/{store_id}/offers/{offer_id}`

and the `{store_id}` and `{offer_id}` are id's that are generated in the same manner (e.g. `string($uuid)`)

it would be beneficial if `pathId` schema could be defined in the `components/parameters`
```json
    "parameters": {
      "pathId": {
        "name": "id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "format": "uuid"
        },
        "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    }
```

and then later reused for the `parameter` definition in the `paths` section

**Comment by hkosova** [comment]
Related (or duplicate of): https://github.com/OAI/OpenAPI-Specification/issues/2026

**Comment by kaznovac** [comment]
Duplicate of #2026 

thanks @hkosova this is subset of the mentioned issue

**Comment by kaznovac** [comment]
sibling to #2498
