### ISSUE TITLE
Media type examples map pattern

### ISSUE THREAD

**Issue by adamaltman** [OAI/OpenAPI-Specification#3013]
Examples map keys defined in components must adhere to a `pattern: '^[a-zA-Z0-9._-]+$'`. (Source: https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.1/schema.yaml)

However, no such restrictions are defined on the examples map defined inside of a media type object. This media type object seems allowed (but questionable if it was intended to be allowed):

```yaml
openapi: 3.1.0
info: 
  title: Path examples is this a bad map?
  version: error-case
paths:
  /foo:
    get: 
      responses: 
        '200': 
          description: OK
          content: 
            application/json: 
              schema: 
                type: object
              examples:
                My invalid example (because space and parentheses are not allowed):
                  value: 
                    foo: bar
                A_valid_example:
                  value: 
                    baz: quz
```

None of the examples in the docs use any characters outside of the pattern allowed in the various component maps. Is this an oversight in the `schema.yaml`? Or is it truly intended to be allowed in the media type examples map but not in the components examples map?

**Comment by RomanHotsiy** [comment]
I believe @webron already commented on it here: https://github.com/swagger-api/swagger-parser/issues/1309#issuecomment-582585253

**Comment by handrews** [comment]
The linked answer was that this is intentional, and there were no further questions - closing.
