### ISSUE TITLE
[org.springframework.http.converter.HttpMessageNotWritableException: No converter for[...]with preset Content-Type 'application/zip']

### ISSUE THREAD

**Issue by dineshmerck** [OAI/OpenAPI-Specification#3016]
Hi,

I am getting the below error while using open API...

[org.springframework.http.converter.HttpMessageNotWritableException: No converter for[...]with preset Content-Type 'application/zip']

I generate API used to download the zip file.

/recipe/downloadOfflineRecipeEditor:
    get:
      description: '**Security @PreAuthorize expression:** hasAuthority(ORE_DOWNLOAD)'
      tags:
        - recipe-data
      summary: Download offline recipe editor
      operationId: downLoadOfflineRecipeEditor
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDownloadFileResponse'
        '404':
          description: Not Found

RecipeDownloadFileResponse:
      type: object
      allOf:
        - $ref: '#/components/schemas/RecipeStatusDescriptionResponse'
      properties:
        result:
          type: object

RecipeStatusDescriptionResponse:
      type: object
      properties:
        statusCode:
          type: integer
        description:
          type: string
        translationKey:
          type: string
        params:
          $ref: '#/components/schemas/Params'
    Params:
      type: object
      additionalProperties:
        type: string

could you please help me to resolve this issue

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
