### ISSUE TITLE
Support for multipart/mixed Content-Type

### ISSUE THREAD

**Issue by grokify** [OAI/OpenAPI-Specification#303]
I have a use case to support the `multipart/mixed` content type as defined in RFC 2049. Use of this content type includes support for:
- multiple parts in sequence
- each part with its own content type and data 
- each part separated by a boundary value included in the HTTP request `Content-Type` header

It seems like it would be ideal if Swagger could enable defining each part as a parameter with content type and, on submission, have Swagger UI create the MIME boundary, add the boundary to the HTTP request `Content-Type` header, and assemble the multipart parameters into a multi-part request body using the boundary.

It would be great to support this in Swagger natively.

**Comment by gaillard** [comment]
:+1: for implementing this :)

**Comment by gaillard** [comment]
Is there some way that a work around to at least allow a user to hand enter (or use the example to enter) the http body (including sub requests with their headers etc) and get them all back for multipart/mixed request/response?

**Comment by grokify** [comment]
As a workaround for a `multipart/mixed` request, I'm currently hardcoding a boundary value for example use. For example:

    "consumes" : ["multipart/mixed; boundary=Boundary-----1234567890"],
    "parameters" : {
         "in": "body",
         "default" : "--Boundary-----1234567890\n ... EXAMPLE HERE ... \n--Boundary-----1234567890--"
    }

**Comment by gaillard** [comment]
@grokify that's good to know thanks i'll try this out first thing tomorrow, how about the response though? So far I haven't been able to get it to show a response with multipart/mixed at all.

**Comment by gaillard** [comment]
The above doesn't pass the validator,you have to add `"schema": { "type": "string" }` for that, and then the default field is at odds with the validator too, looks like a bug.

**Comment by webron** [comment]
@gaillard - when you say 'allow the user to hand enter', do you mean via swagger-ui or in general?

**Comment by gaillard** [comment]
Yes I mean in the UI. It would be great if the user could choose content type, body and headers of each multi part, but as a work around if we could let the user hand enter that like @grokify showed it would help tremendously. His way works unless you also want it to run through the validator, can that bug be fixed?

**Comment by webron** [comment]
@gaillard you have to add `schema` to the parameter. While I'd normally discourage the following definition, as a workaround you can try this:

```js
"consumes" : ["multipart/mixed; boundary=Boundary-----1234567890"],
"parameters" : {
     "in": "body",
     "schema": { "type": "object" },
     "default" : "--Boundary-----1234567890\n ... EXAMPLE HERE ... \n--Boundary-----1234567890--"
}
```

**Comment by gaillard** [comment]
That does not pass the validator though. I'm running the validator locally.

**Comment by webron** [comment]
What error do you get from the validator?

**Comment by gaillard** [comment]
That the schema doesn't match. `[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 2)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/parametersList/items"},"instance":{"pointer":"/paths/~1{version}~1batch/post/parameters/1"}}]`

**Comment by gaillard** [comment]
Also an example of the response does not work.

**Comment by webron** [comment]
@gaillard - let's take this to the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket) as it's not directly related to the issue (this is just a workaround we're trying to employ, it won't change the issue at hand). There, just provide me with the definition of the POST /{version}/batch path, what you expect to see in the ui and what you actually experience.

**Comment by gaillard** [comment]
Ok posted, thanks

**Comment by tleyden** [comment]
Feature request: `multipart/related` (merging https://github.com/swagger-api/swagger-spec/issues/520 into this)

**Comment by perotom** [comment]
Any updates on Content-Type and boundary?

**Comment by fehguy** [comment]
See #878

**Comment by handrews** [comment]
Has anyone involved in this thread used `multipart/mixed` with OpenAPI 3?  If so, how did you correlate the parts with the named properties in the schema?  This has come up several times recently without any clear answer, which led me to essentially re-file this issue as #3721.  But if there is a pattern that works as-is, even if it's only in some circumstances, we should document that in the 3.0.4 and 3.1.1 patch releases.
