### ISSUE TITLE
Support QUERY operation (http method)

### ISSUE THREAD

**Issue by SVilgelm** [OAI/OpenAPI-Specification#3033]
It would be great if the openapi spec will support the http QUERY method ([draft](https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/)) in v3.1

The QUERY method is very useful and we use it in couple of projects. Is it possible to extend the spec v3.1 or v3.2?

**Comment by hkosova** [comment]
Related: #1747

**Comment by SVilgelm** [comment]
oh, thank you!
