### ISSUE TITLE
Same path and different parameters and each params different java method, but ui display in the same api

### ISSUE THREAD

**Issue by npsakthi** [OAI/OpenAPI-Specification#3036]
I have 3 different api, but swagger v3 ui display as single api and expected both of params need to pass(its required param). how to display 3 different api. what changes required in the parameters/tags/operation annotation.

Get - api/bond/security
Get - api/bond/security?date=2022-09-22
Get api/bond/security?cusip=123'

swagger display 
api/bond/security
parameters
1. date 
2. cusip
![image](https://user-images.githubusercontent.com/2189747/192487523-0509c6ba-b478-42e0-be2b-bdeaa6dfd550.png)

**Comment by rafalkrupinski** [comment]
OpeAPI operations are identified by a method and a path, so you have here, from OAS perspective, one operation with two optional query parameters.

**Comment by MikeRalphson** [comment]
Please chase if the above didn't answer your question.

**Comment by npsakthi** [comment]
thanks for your reply.
