### ISSUE TITLE
Can the Discriminator Object be extended with specification extensions?

### ISSUE THREAD

**Issue by fariadev22** [OAI/OpenAPI-Specification#3038]
I'm doing some research related to validation of OpenAPI v3.0 specification documents and noticed that nearly all objects defined in the standard have the following line  at the end:
> This object MAY be extended with [Specification Extensions](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#specificationExtensions)

This is however not the case for the [Discriminator Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#discriminator-object). Is it correct to assume that this object indeed cannot be extended or is it just an oversight in the standard document? I tried looking through the issues logged already as well as various forums but could not find anything so any clarity would be appreciated.

Thanks!

**Comment by hkosova** [comment]
Discriminator can have extensions in [OpenAPI 3.1](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#discriminatorObject) (the latest version of the spec), but not in 3.0.x.

**Comment by fariadev22** [comment]
Thank you for the clarification @hkosova. Just curious, but is there a particular reasoning behind this though?

**Comment by hkosova** [comment]
Most likely an oversight after changing `discriminator` from a string (in OAS 2.0) to an object (in OAS 3.0).

**Comment by fariadev22** [comment]
@hkosova Makes sense. Thank you again!
