### ISSUE TITLE
Ambiguities Regarding Parameter Example Validation

### ISSUE THREAD

**Issue by fariadev22** [OAI/OpenAPI-Specification#3041]
As part of a spec validation related research, I have run into some confusions in the OpenAPI v3.0.3 specification document [Parameter Object section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#parameterObject), in particular the one shown below:
![Conflict](https://user-images.githubusercontent.com/20472892/194554852-e84cd65a-ad70-4338-895e-bc54fc18c5e8.PNG)

Let's assume that a parameter `example` is present next to a `schema` property.

> The example SHOULD match the specified schema and encoding properties if present.

This indicates that the example is **RECOMMENDED** to be valid against the schema and encoding. By encoding I'm assuming it implies `style`, `explode` and `allowReserved`.

> When example or examples are provided in conjunction with the schema object, the example MUST follow the prescribed serialization strategy for the parameter.

Here, we are told that it is **MANDATORY** for the example to be valid against the serialization strategies specified for the parameter. I'm assuming again that the serialization strategies implies a combination of schema + style + explode at the very least. At least, that is what I understood from the rest of the text in this section and examples. 

The two statements are clearly clashing with each other as one is making something mandatory while the other is simply recommending things. I'm using this [section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#version-303) for interpretation of the words SHOULD and MUST.  

Is my understanding of things correct or have I missed something? Any clarity on this would be much appreciated.

Thank you.

**Comment by handrews** [comment]
See also [this Slack thread](https://open-api.slack.com/archives/C1137F8HF/p1675197255857239) which discusses whether examples should be shown pre or post-encoding.

**Comment by handrews** [comment]
As you can see in PR #3893, I dug into the history and it looks like SHOULD is correct.

**Comment by handrews** [comment]
PRs merged for 3.0.4 and 3.1.1!
