### ISSUE TITLE
Broken navigation on https://spec.openapis.org/oas/{version}.html

### ISSUE THREAD

**Issue by arno-di-loreto** [OAI/OpenAPI-Specification#3054]
On https://spec.openapis.org/, for all versions of the specification, there's a conflict between user-defined anchors (`<a name="infoObject"></a>` in MD) which appear both in the navbar and in the main document (they are turned into `<span id="infoObject"...`) making quite complicated the navigation between objects when reading the specification.

To reproduce the bug:
- Go to https://spec.openapis.org/oas/v3.1.0.html
- Scroll to the OpenAPI object (or click on it in the navbar)
- Click on Info Object (which targets `#infoObject`) 
- Instead of having the document scrolling to the Info Object section, it's the navbar that scrolls to its Info Object header (both containing a 

Note that using the [link with the anchor](https://spec.openapis.org/oas/v3.1.0.html#infoObject) in a new tab works: the document scrolls to the right section.

**Comment by jlevers** [comment]
This issue is also present when using the markdown spec files themselves, e.g. https://github.com/OAI/OpenAPI-Specification/blob/3.0.2/versions/3.0.2.md

**Comment by handrews** [comment]
This is finally fixed!  🎉
