### ISSUE TITLE
Overriding object keys in allOf - valid or undefined behaviour?

### ISSUE THREAD

**Issue by Southclaws** [OAI/OpenAPI-Specification#3069]
Hey all! I build fairly large APIs but always try to keep the schemas 1. reusable and 2. logically separated.

One requirement I often run into is the ability for the representation of a field to differ slightly to the mutable version. One example would be prices or monetary values in general.

When doing patch calls, I want to accept numbers but when getting the data, I want to return strings (or, in my case, a more complex object that contains a currency, a pre-formatted representation, the raw/inaccurate Float32/Number value, etc)

So what I've settled on is something like this:

```yaml
openapi: 3.0.0
info:
  title: "Example of allOf key precedence"
  version: "0.0.0"
  contact: {}
paths: {}
components:
  schemas:
    ProductImmutable:
      type: object
      properties:
        price:
          type: string

    ProductMutable:
      type: object
      properties:
        price:
          type: number

    Product:
      type: object
      allOf:
        - { $ref: "#/components/schemas/ProductMutable" }
        - { $ref: "#/components/schemas/ProductImmutable" }
```

Now this works, my code generates as expected. My PATCH endpoint can use *just* the mutable schema and the GET endpoint can use the full "Product" schema and show everything at once. All the validators and UIs render this correctly and as desired, the most recent entry into the `allOf` list overrides earlier conflicting keys.

![image](https://user-images.githubusercontent.com/1636971/199770487-12b4b13e-7b71-4593-9a8b-a96dd8fd30f2.png)

But what I want to know is, is this a valid and acceptable way to do this? It's really concise and I'd hate to have to define these schemas twice (one for the patch and one for the get).

I don't want to be relying on undefined behaviour. I can't find any definitive answer in the reference. Both my frontend and backend code generation tools are generating valid code though.

Thanks!

**Comment by rafalkrupinski** [comment]
Not sure what code you generate from it, but in json no value can be a string and a number at the same time, which is what your schema tries to validate.
I think you want to use oneOf (or anyOf, since the types you here are disjoint), and you can add readOnly and writeOnly as required.

**Comment by Southclaws** [comment]
> Not sure what code you generate from it

Golang (with oapi-codegen) and TypeScript (with orval)

The Go code produces the desired result, the "Mutable" payload is a struct with a float32 type field and the "Immutable" payload is a struct with a string type field. And the TypeScript code produces a type union, which is less than ideal tbh but still valid.

> in json no value can be a string and a number at the same time

This is for two independent operations: a read and a write. When reading the information, there's additional calculated information based on context (in the price example, this is a currency sign and some rounding etc) and when writing you want to accept number types since the other metadata seen when reading is computed on the fly, rather than stored.

`oneOf ` or `anyOf` would mean copy-pasting the entire request object (opportunity for forgetting to add/remove fields in both) I think, unless there's a way to easily merge and override for different operations like this.

But thanks for the answer, it sounds like this is just undefined behaviour and possibly a bug in the codegen tooling/validators for not throwing an error for these conflicting keys.

**Comment by Southclaws** [comment]
I suppose one valid approach would be three type definitions, one would be all the fields that remain the same then one would be the fields with mutable simplified forms and the other would be the hydrated read forms of those fields.


```yaml
openapi: 3.0.0
info:
  title: "Example of allOf key precedence"
  version: "0.0.0"
  contact: {}
paths: {}
components:
  schemas:
    ProductImmutable:
      type: object
      properties:
        price:
          type: string

    ProductMutable:
      type: object
      properties:
        price:
          type: number

    Product:
      type: object
      properties:
        name:
          type: string
      oneOf:
        - { $ref: "#/components/schemas/ProductMutable" }
        - { $ref: "#/components/schemas/ProductImmutable" }
```

**Comment by rafalkrupinski** [comment]
Either that or just
```yaml
properties:
  price:
    oneOf:
      - type: string
      - type: number
```
Depending on your use case

**Comment by Southclaws** [comment]
The problem with this is it generates simple type unions, allowing developers to make mistakes. My ideal end goal is two distinct types so the HTTP handler bindings and API client generated code makes it impossible to accidentally send the wrong type. A `oneOf` generates in TypeScript a `T = string | number` meaning you can submit either one or the other via the API. If you submitted a string in the above example, the API server would respond with an error since it's the incorrect type and it's expecting a number.

I'll have a further think about better solutions that are within the spec, thanks again!

**Comment by rafalkrupinski** [comment]
```yaml
schemas:
  ProductCommon:
    properties:
       name:
         type: string
  ProductMutableParts:
    properties:
      price:
        type: string
  ProductImmutableParts:
    properties:
      price:
        type: number
  ProductMutable:
    allOf:
    - ProductCommon
    - ProductMutableParts

**Comment by handrews** [comment]
@Southclaws anything that does any sort of overriding or merging of schema assertions (any keyword that can cause validation to fail) or applicators (any keyword that applies a schema to an instance location, including `$ref` and all the keywords with subschemas in their values) is not compliant with the JSON Schema specifications.

Some code generation tools in particular seem to impose semantics on the ordering of keywords like `allOf` but that behavior is implementation-specific.

Annotation keywords (like `title`) defer handling of multiple values to the application (from JSON Schema's point of view, both the OpenAPI specification and all implementations of it are "applications").  But those are the only keywords that do that.  And some annotations (like `readOnly` and `writeOnly`) have pretty clear semantics that applications shouldn't change (e.g. if any schema marks a field as `readOnly` it should be considered read-only).

Generally what you want to do is factor out the properties that vary and only pull them in at the point where they are needed.

Handling variations that depend on HTTP context (e.g. PATCH vs GET) is a very complex topic without a clear solution.  It's something we're discussing a lot for 4.0 (although I think an extension could be done for 3.1 as well).

**Comment by handrews** [comment]
No further replies after the answer in 2022, closing.
