### ISSUE TITLE
How to defined non-restful api

### ISSUE THREAD

**Issue by Anthony-Dong** [OAI/OpenAPI-Specification#3076]
question: 
```shell
curl 'http://localhost:8080/api/query?action=UserList&version=1.0&name=xxx&page=1&page_size=10'
curl 'http://localhost:8080/api/query?action=UserInfo&version=1.0&id=10001'
```

Like graphql, we define all the resources through an api, separated by the action and version fields. 

As above, the request parameters and response content of `UserList` and `UserInfo` are different.

There are also cases where the action and version fields might be passed through the request body, for example

```shell
curl 'http://localhost:8080/api/query'  --header 'content-type: application/json' --data-raw '{"action": "UserInfo", "version": "1.0",  "id": 10001}'
```

**Comment by darrelmiller** [comment]
@Anthony-Dong Please take a look at https://github.com/OAI/moonwalk as it attempts to address many of the issues you raised.  Please provide us feedback in the discussions area.

**Comment by Anthony-Dong** [comment]
> @Anthony-Dong Please take a look at https://github.com/OAI/moonwalk as it attempts to address many of the issues you raised. Please provide us feedback in the discussions area.

thanks!
