### ISSUE TITLE
How to resolve possibly infinite nesting?

### ISSUE THREAD

**Issue by mabar** [OAI/OpenAPI-Specification#3083]
Parameter/Header content contains MediaType
MediaType encoding contains Encoding
Encoding headers contains Header

This structure allows possibly infinite nesting of Header->MediaType->Encoding->Header. Unfortunately I have not found in specification how should validators behave in case this occurs in a schema. Should it be allowed because Reference to a MediaType containing Header may be used in Header as well as other places? If occurance of Header is found in Header, should it be validated or ignored? Or should it be not allowed at all to have nested headers?

Another infinite nesting possibility is in Callback expression -> Path Item operation -> Operation callbacks -> Callback. In this case, it may make sense - callbacks can result in other callbacks. But I believe it should be explained by specification so implementators don't have to find it themselves. 

Also references should have rules for recursion. e.g. in Schema recursive references may be valid in anyOf/oneOf and other conditional structures and in multi-level arrays (e.g. array<string|self> where self references array<string|self>). In other Schema structures and other objects recursive references should be probably forbidden.

**Comment by karenetheridge** [comment]
The [JSON Schema spec](https://json-schema.org/draft/2020-12/json-schema-core.html#section-9.4.1) says:

> A schema MUST NOT be run into an infinite loop against an instance. For example, if two schemas "#alice" and "#bob" both have an "allOf" property that refers to the other, a naive validator might get stuck in an infinite recursive loop trying to validate the instance. Schemas SHOULD NOT make use of infinite recursive nesting like this; the behavior is undefined.

It would be reasonable to insert similar language into the OpenAPI spec.

**Comment by mabar** [comment]
Json schema note is about infinite looping due to data schemas referencing each other. This issue is about unlimited spec nesting. It just does not make a lot of sense to me, that a header may define its media type if the header is already defined under a media type

e.g this media type is not explicitly considered invalid by the openapi specs, but it is complete non-sense, as media type in X-Example header can't ever happen and even if it could, it shouldn't.

```yaml
# media type object
application/json:
  encoding:
    # encoding object
    exampleEncoding:
      headers:
        # header object
        X-Example:
          content:
            # media type object again
            application/xml: {}
```

I would simplify this issue and solve just the nesting and cyclical references in case of that nesting in openapi objects. 

For the part about Schema object specifically I will probably create an issue in json schema spec repository, because recursive nesting is possible under conditions that could be defined and so behavior should not be undefined.  [Here](https://github.com/orisai/object-mapper/blob/6f344a131dc991c3e48a1e1323847b1c1a5561df/tests/Unit/Processing/DefaultProcessorTest.php#L424-L532) is an example of recursive nesting where structure is successfully printed and validated.

**Comment by karenetheridge** [comment]
> Json schema note is about infinite looping due to data schemas referencing each other.

It's the same as what you described -- we can have an infinite loop with various components referencing each other.

If they don't reference each other, then there must be some finite end, then there isn't any problem. But an implementation may still want to specify a maximum recursion depth, say 100 levels, to avoid resource contention issues.

**Comment by handrews** [comment]
@mabar in practice this shouldn't be a major concern, as it's hard to come up with a scenario in which this would nest deeply.  Media Type Objects only include Encoding Objects to handle multipart media types like [`multipart/form-data`], which uses an internal structure of headers and media types for each part.  But I'm not even sure _how_ you could nest `multipart/form-data` inside `multipart/form-data`, much less why you'd do such a thing.

I'd try to find an actual use case or real-world example of deep nesting before worrying about it.  As @karenetheridge already pointed out, a max recursion level is an easy way to avoid problems in practice.

**Comment by mabar** [comment]
@handrews

> Media Type Objects only include Encoding Objects to handle multipart media types like [multipart/form-data]

That's exactly what I missed, thank you! Only for `multipart/*` and `application/x-www-form-urlencoded` nesting makes sense and so only for it should be allowed. (specification says SHALL instead of MUST, which I would prefer, but good enough)

And multipart should not be nested since RFC 7578 [deprecated it](https://www.rfc-editor.org/rfc/rfc7578#section-4.3). It was also never well supported by tooling.

Only one level of nesting and only for multipart and form media types :) Thank you for your help
