### ISSUE TITLE
Allow Json Schema meta properties within api spec documents

### ISSUE THREAD

**Issue by designermonkey** [OAI/OpenAPI-Specification#3089]
In advance, apologies if this has already been asked and addressed, there are over 1k of issues referencing `$schema` that I simply can't read through all of.

I am using the Stoplight Studio to build up an API specification where we already have Json Schema documents describing a huge amount of the actual data objects like request and response objects as we use them to validate data at storage as well as incoming requests and outgoing responses within our application.

Stoplight is listing a huge amount of errors pertaining to Json Schema specific properties including (but not limited to) `$schema` `$id` and many others.

Is there a way to get OpenAPI to play nicely with Json Schema documents, and save us the headache of having to duplicate thousands of lines of specification code?

**Comment by designermonkey** [comment]
It turns out I was using an older version of the spec (`3.0.3`), though saying that I get a warning about `$defs` (with `3.1.0`):

> Object must not have unevaluated properties.

**Comment by handrews** [comment]
@designermonkey JSON Schema support in 3.0 and 3.1 is completely different.

3.0 uses a restricted-but-also-extended variation of JSON Schema draft-04 (or technically draft-wright-json-schema-00, sometimes called "draft-05" but for complicated reasons there's not really a "draft-05").

In 3.0, you cannot use `$schema` or `$id` (or its predecessor in draft-04, `id`).  You can't use `$defs` (and probably can't use its predecessor in draft-04, `definitions`, but I don't recall offhand).  You also can't use any additional keywords unless they start with `x-`.

3.1 is fully compatible with JSON Schema 2020-12.  You can use any of its keywords, including `$schema` to use a custom vocabulary (although I have no idea how many tools support that).

**Comment by handrews** [comment]
I don't know why 3.1.0 would warn you about `$defs`, but that's an issue to file with Stoplight.  It doesn't sound like there is an OpenAPI spec issue here, so I'm closing this, but feel free to comment/re-open/re-file (I can't remember if the permissions are set to allow re-opening) if you disagree.
