### ISSUE TITLE
OAUTH2 Password flow examples

### ISSUE THREAD

**Issue by TaniaDianne** [OAI/OpenAPI-Specification#3098]
The current published openAPI 3.0 specification does not contain examples of the OAUTh2 password flow. Can they be provided please?
I am getting high level fortify security alert when using this

security:
  - OAuth2: []
  
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://oauth.pp.xxxxxxxxxx.com/oauth/oauth20/token'
          scopes: {}

**Comment by TaniaDianne** [comment]
Any update as to when this can be provided?

**Comment by handrews** [comment]
There is now [an OAuth2 example](https://learn.openapis.org/specification/security.html) on the security page of learn.openapis.org.  I'm going to close this issue- if there are more things to do with this sort of example, please [open a new issue at the Learn site's repository](https://github.com/OAI/learn.openapis.org/issues).
