### ISSUE TITLE
Proposal: Promote date, time, and datetime to `type` so `format` becomes usable for them

### ISSUE THREAD

**Issue by mattholden** [OAI/OpenAPI-Specification#3106]
One shortcoming of the `type` and `format` options relates to dates and times. Currently, I need to specify `type: string` and a `format` of either `date`, `datetime`, or `time`. That's great that we can specify those values, but there is nothing that allows me to specify to my API users what date or time format we use. Is it a unix timestamp, or ISO 8601, or MySQL format, or....? Are timestamps included? Do we cut off times at the minute, second, millisecond? 

Every modern language has a whole library for dealing with the complexities of this because it's not trivial. But, in OpenAPI, all I can do is say it's a date, and it's up to you to figure out how it's formatted. I can provide an `example`, but that doesn't help much with validation and tooling. My best option is to stick a `pattern` in there, repeat it for every date in my app, and hope users recognize the regex as "Oh, that's ISO 8601."

I'd propose that `date`, `datetime` and `time` be promoted from `formats` to `types` in their own right, such that `format` becomes viable. Common formats can be provided for in the same way that formats for things like `email` and `uuid` are today, and for anything not covered by one of those constants, a format string similar to what language libraries use could be employed. This could then be supported by tooling for more flexible validation.

Examples:

```
type: datetime
format: iso8601
```

```
type: datetime
format: "H:i:s A F j, Y"
```

**Comment by karenetheridge** [comment]
Those formats have strict definitions: they don't just mean "a timestamp in any format". ref. https://json-schema.org/draft/2020-12/json-schema-validation.html#section-7.3.1

If you want to allow a timestamp in a different format, you can use a regex, e.g.

```yaml
components:
  schemas:
    mysql_datetime:
      type: string
      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$
```

**Comment by karenetheridge** [comment]
The idea of specifying a custom date-time format is an intriguing one; the place to explore that would be in a custom JSON Schema library, at https://github.com/json-schema-org/json-schema-vocabularies.

**Comment by GabenGar** [comment]
`"type"` keyword (almost) means JSON types, adding additional ones will add more burden on implementations. It kinda sorta works for `"integer"` because it's easy to differentiate it from a float in any language, but the meme strings like date will only contribute to interop issues.
And don't return formatted strings in your endpoints, just return an `ISO 8601` datetime string with a timezone and let the formatting decision on the consumer.

**Comment by lornajane** [comment]
I think the explanation from @karenetheridge  (thanks!) answers the question here such that further changes aren't needed, so I'm closing the issue.
