### ISSUE TITLE
GET with null field

### ISSUE THREAD

**Issue by roukmoute** [OAI/OpenAPI-Specification#3121]
Hello,

I'm lost on the possibilities of a GET API that respects OpenAPI 3.1.

I will use this example:

```
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
          enum:
            - available
            - pending
            - sold
```

If for example there are no categories and/or status, currently when I do a GET on /pets, what should the API answer?

```json
{
  "id": 10,
  "name": "doggie",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ]
}
```

Is an API supposed to always return all fields, even if they are null?

```json
{
  "id": 10,
  "name": "doggie",
  "category": null,
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": null
}
```

If not, what property of the OpenAPI allows to say that the field is optional?
I saw that there was a `required` property, but I have the impression that it only applies to POST and PUT.

I'm more of the opinion that the API should always return all fields, even if they are null, but others are of the opinion that the API should only return fields that have a value to send only the bare necessities and send the shortest json possible.

Could you please enlighten me and send me some documentation about this subject?

I thank you in advance.

**Comment by MikeRalphson** [comment]
Schema properties are optional by default (i.e. if they are not present in a `required` array). API design is up to you, but generally it is not necessary to send optional properties (with a `null` value). A `PUT` or `PATCH` requestBody padded out with `null`s could cause problems with inadvertent data deletion.

`required` can be used in any schema, regardless of the HTTP method, allowing for the fact that `GET`/`HEAD`/`DELETE` requests do not generally support a `requestBody`.

**Comment by handrews** [comment]
As @LasneF noted, the above schema does not actually allow `null` values.

I've noticed that folks who work in loosely typed languages that allow object properties to be absent tend to omit those properties in JSON, while folks who work in strictly typed languages tend ot require everything and use `null` values.  It's one of the more difficult impedance mismatches when trying to define data models across all languages.

I personally find `null` values irritating to manage, and they can add to confusion when using [JSON Merge-Patch](https://www.rfc-editor.org/rfc/rfc7396) as your PATCH request media type.  But YMMV.

Regardless, the key thing is to be consistent about handling different false-y / missing values throughout your API.

**Comment by handrews** [comment]
The answer back in February addressed the question and there was no further reply from the OP.  Closing.
