### ISSUE TITLE
Abstract class not bring generated in OAS.yaml

### ISSUE THREAD

**Issue by DeepikaBalasubramanian** [OAI/OpenAPI-Specification#3125]
I am using SwaggerAPI to generate my OAS.yaml.

OpenAPI generator version 6 is used to generate pojos from generated OAS.yaml

The abstract classes in my module are not being generated as abstract.

example : 
public abstract class example 

is being generate as 
public class example.

Is there any annotation / specific extension / property that can be used to mention the class as abstract in Open API Specification ?

I have tried

x-abstract : true 
also
abstract : true

none worked.

Any help is appreciated.
Thanks in advance.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
