### ISSUE TITLE
Specification extensions link is broken in Markdown file

### ISSUE THREAD

**Issue by SensibleWood** [OAI/OpenAPI-Specification#3132]
The Specification Extensions link is broken through the specification file:

* [This is the broken link](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#specificationExtensions)
* [This is the correct link](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#specification-extensions)

It would nice for readability of the specification if this worked.

**Comment by fariadev22** [comment]
For me as well, all links in the Table of Contents in this document are broken:

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md

**Comment by SethAngell** [comment]
Hey! I noticed the same thing and performed a slight refactor to resolve the issue! Waiting on reviews currently. See https://github.com/OAI/OpenAPI-Specification/pull/3128

**Comment by kexoth** [comment]
Noticed this issue as well & refactored the links https://github.com/OAI/OpenAPI-Specification/pull/3160 
Noticed now that mine is duplicate work with @SethAngell's PR.

**Comment by handrews** [comment]
Consolidating all broken link issues into issue #3054 and PR #3408
