### ISSUE TITLE
Unclear portion of openIdConnectUrl for openIdConnect securitySchema

### ISSUE THREAD

**Issue by shiup** [OAI/OpenAPI-Specification#3152]
https://spec.openapis.org/oas/v3.1.0

```
Security Scheme Object
Defines a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter or as a query parameter), OAuth2's common flows (implicit, password, client credentials and authorization code) as defined in [RFC6749](https://tools.ietf.org/html/rfc6749), and [OpenID Connect Discovery](https://tools.ietf.org/html/draft-ietf-oauth-discovery-06).
```

the link above points to oauth discovery.

**Does it apply to the openIdConnectUrl for openIdConnect securitySchema ?**  Should the openIdConnectUrl be driven by https://openid.net/specs/openid-connect-discovery-1_0.html ?

<img width="846" alt="image" src="https://user-images.githubusercontent.com/24717424/215216296-fac25328-e537-4009-9db6-51565a2b348c.png">

Please help clarify, thanks

**Comment by handrews** [comment]
This just seems like a bug where the link is wrong.  If the link for openIdConnect did not point to OAuth would this otherwise be clear?

**Comment by handrews** [comment]
I think the only thing left to do here is to forward-port the change to v3.1.1 and v3.2.0, correct?

**Comment by AxelNennker** [comment]
Yes

**Comment by handrews** [comment]
@AxelNennker @shilpa-padgaonkar:  In 3.1.1 it looks like the draft IETF RFC you replaced was already replaced by RFC 8414.  Is it still appropriate to replace 8414 with what you did in 3.0.4?

**Comment by handrews** [comment]
@AxelNennker ah, that change was PR #3718, and thanks for reminding me because it needs to be backported to 3.0.4.  I was asking about PR #3607 for this issue.

**Comment by AxelNennker** [comment]
Yes, https://github.com/OAI/OpenAPI-Specification/pull/3607 should be in all version since openidConnectUrl was introduced to OAI
