### ISSUE TITLE
Generator restbed-server 

### ISSUE THREAD

**Issue by Fangel29** [OAI/OpenAPI-Specification#3166]
hello,i use generator for restbed-server use cmd like this:
**openapi-generator-cli generate -i F:\openapi\test\TestDef.yml -g cpp-restbed-server -o F:\openapi\test\test**

Then get a folder contais  cmakelist like this:
[CMakeLists.txt](https://github.com/OAI/OpenAPI-Specification/files/10783135/CMakeLists.txt)

After,using cmake to build the lib.But i just get a .dll  that have no .lib.
caused that by all source codes have no __declspec(dllexport).

so i want to konwn that whether the source code is correctly or that i should use other cmd args?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant [repository](https://github.com/OpenAPITools/openapi-generator). This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
