### ISSUE TITLE
3.0.4 patch release

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3176]
Motivated by the many confusing corners revealed in PR #3167 and after a quick check with @webron in PR #3171 , I've been tagging issues with 3.0.4 that are related to clearing up obscure form and parameter serialization/encoding ambiguities.  And occasionally errors (e.g. issue #3174).  Some of these things would apply to a 3.1.1 as well.

I'm filing this just to call attention to it more clearly.  Keeping in mind that this is a _patch_ release (which  might cause some of the issues I just filed to get rejected or scaled back), if there are other clarifications that seem necessary, now is the time to get them in.

Most of what I'm labeling for 3.0.4 is stuff I've wanted to improve for quite a while.  The rest are issues I found while checking to see what was already filed that seemed to fit nicely.

@webron can we get a v3.0.4-dev branch?  I will then start adding PRs to it (and perhaps @jeremyfiel can rebase #3171 to target it as well).  And perhaps a v3.0.4 milestone if that's needed?

**Comment by webron** [comment]
https://github.com/OAI/OpenAPI-Specification/tree/v3.0.4-dev has been created, with an initial file for 3.0.4.

**Comment by handrews** [comment]
Thanks @MikeRalphson , I'd forgotten about that!  Yes, I've found quite a few 3.0.4 that should be forward-ported.

Thanks for the branch, @webron - I notice that there are some commits to the 3.0 schemas on main post-3.0.3 tag.  Are the schemas published from main or the branch (given that the schemas are not patch-versioned)?

**Comment by webron** [comment]
The schema is managed outside the scope of the spec (so changed go directly to `main`).

**Comment by handrews** [comment]
Note that my work on this stalled first because of some other urgent priorities and then because I got COVID and now I'm a month behind on everything and trying to catch up.  I do plan to round up the remaining 3.0.4 tagged things and sort them out as soon as I can.

**Comment by handrews** [comment]
I feel like this issue has done its job - the TDC call is focusing on the 3.x line and patch releases in general are being discussed in #3528.  As the original filer, I'm closing this.
