### ISSUE TITLE
Example for externalDocs in Ymal

### ISSUE THREAD

**Issue by Ckim15** [OAI/OpenAPI-Specification#318]
Hi,

Could you please provide a working sample for externalDocs?

**Comment by mohsen1** [comment]
petstore has externalDocs http://petstore.swagger.io/v2/swagger.json

**Comment by psinghsp** [comment]
Is there an example like swagger 1.2 where I can put an entire resource in a separate file? For example I wanto put /pet in a separate file like this:
/pet:{
    $ref: pet.json
}

**Comment by webron** [comment]
https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json

**Comment by psinghsp** [comment]
Thanks. Can that be relative url with respect to base path so that I do not have to put explicit server address in there?

**Comment by webron** [comment]
It has nothing to do with the base path. Gotta be a full url.

**Comment by mohsen1** [comment]
@webron shouldn't relative `$ref`s resolve based on where the document is located?

**Comment by psinghsp** [comment]
Thanks for the answers. Also, does swagger-UI support these ref urls? I will try and see if relative urls can be resolved by swagger UI.

**Comment by webron** [comment]
@mohsen1 is right that it doesn't have to be a full URL, but it actually follows the URI rules. It is not related to the basePath though. Whether swagger-ui or other tools support it or not is a question that should be opened on the respective project.

**Comment by psinghsp** [comment]
Swagger UI does not work at all whether it is a full URL or relative URL. I will post the question on this support there. Thanks for all the answers.

**Comment by RobDolinMS** [comment]
@Ckim15 Is this sufficiently resolved in the latest OpenAPI Spec v3 release?  https://github.com/OAI/OpenAPI-Specification/releases

**Comment by philsturgeon** [comment]
Seems like we got lots of examples around the place and its been 3 years since we asked if they were good. Let's consider it done! 🙌
