### ISSUE TITLE
Required false is not working with Map

### ISSUE THREAD

**Issue by PraveenDhasarathan** [OAI/OpenAPI-Specification#3192]
I have created the Spring boot project and added openApi "springdoc-openapi-ui (1.6.14)". when I create a rest endpoint with below syntax:
    @PostMapping("/test")
    public void testing(@RequestParam String name,
                               @RequestParam(required = false) Map<String, String> maps,
                               @RequestParam(required = false) String key
                               ) {
     }
     
I dont see the "maps" attribute in the swagger UI. It is totally getting missed. But I see the "key" attribute. Even though both are required false, I see key attribute but not the maps attribute in the UI.

Note: If I remove the required false in the maps attribute then it comes in the UI.
     
Excepted:
key and maps both should come in swagger UI without any required label

Actual:
key is coming without any required label but maps is not coming in the UI at all.

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository, e.g. spring-boot or swagger-ui. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
