### ISSUE TITLE
3.0.4: rephrase now-outdated statement on minor spec version compatibility

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#3195]
Section [Versions](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#versions) claims

> Each new minor version of the OpenAPI Specification SHALL allow any OpenAPI document that is valid against any previous minor version of the Specification, within the same major version, to be updated to the new Specification version with equivalent semantics. Such an update MUST only require changing the `openapi` property to the new minor version.
>
> For example, a valid OpenAPI 3.0.2 document, upon changing its `openapi` property to `3.1.0`, SHALL be a valid OpenAPI 3.1.0 document, semantically equivalent to the original OpenAPI 3.0.2 document. New minor versions of the OpenAPI Specification MUST be written to ensure this form of backward compatibility.

Now 3.1.0 is out, uses a different JSON Schema draft, and this statement does not reflect reality.

The first paragraph in this section explicitly allows correcting errors in the specification document with a patch version:

>  Typically, *`.patch`* versions address errors in this document, not the feature set.

So the two now erroneous paragraphs could simply be removed.

**Comment by ralfhandl** [comment]
@MikeRalphson could you please add the `3.0.4` label?

**Comment by MikeRalphson** [comment]
@ralfhandl would you be interested in an official OAI triage team hat? It would allow you to label and close issues.

**Comment by ralfhandl** [comment]
@MikeRalphson I would not object to that honor 😄
