### ISSUE TITLE
Same ref example in methods not working

### ISSUE THREAD

**Issue by petrkasnal** [OAI/OpenAPI-Specification#3198]
Hi,

i'm try use same example over ref in few methods and it isn't work. 

Example.yml
`test: 'ok'`

items.yml
```
post:
  summary: Import items 
  responses:
    '401':
      description: 'Unauthorized'
      content:
        application/json:
          schema:
            $ref: '../BaseSchemas/ApiResult.yml'
          example:
            $ref: '../BaseExamples/UnauthorizedExample.yml'

get:
  summary: Get all items
  responses:
    '401':
      description: 'Unauthorized'
      content:
        application/json:
          schema:
            $ref: '../BaseSchemas/ApiResult.yml'
          example:
            $ref: '../BaseExamples/UnauthorizedExample.yml'
```

And result show this
Post:
![image](https://user-images.githubusercontent.com/90285874/224145295-1b209948-bc95-429c-a945-6f499687ff00.png)

Get:
![image](https://user-images.githubusercontent.com/90285874/224145404-ff3d9916-2023-41a8-8a57-b2c7c1a6e027.png)

**Comment by MikeRalphson** [comment]
What tool are you using which doesn't work? This repository is for the OpenAPI specification itself.

**Comment by petrkasnal** [comment]
@MikeRalphson Swagger but i dont know if openapi write correctly

**Comment by hkosova** [comment]
@petrkasnal The `example` keyword (singular form) does not support `$ref`, you need to specify the entire example value inline.

The [`examples`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#user-content-mediatypeexamples) keyword (plural form) supports both `$ref` (to reference an [Example Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#example-Object) definition) and `externalValue` (to "import" the example value from an external file). The syntax for `examples`+`$ref` is:

```yaml
      content:
        application/json:
          schema:
            $ref: '../BaseSchemas/ApiResult.yml'
          examples:
            UnauthorizedExample:
              $ref: '#/components/examples/UnauthorizedExample'

components:
  examples:
    UnauthorizedExample:
      summary: An example of a 401 Unauthorized response
      value:
        code: 401
        message: The 'Authorization' header is missing or contains an invalid value.
```

and the `externalValue` syntax is as follows (but Swagger UI [does this support this](https://github.com/swagger-api/swagger-ui/issues/5433) yet):
```yaml
      content:
        application/json:
          schema:
            $ref: '../BaseSchemas/ApiResult.yml'
          examples:
            UnauthorizedExample:
              summary: An example of a 401 Unauthorized response
              externalValue: '../examples/UnauthorizedExample.json'
```
```
// UnauthorizedExample.json

{
  "code": 401,
  "message": "The 'Authorization' header is missing or contains an invalid value."
}
```

**Comment by petrkasnal** [comment]
@hkosova ok thank you very much for your help :)
