### ISSUE TITLE
Clarify if header is required to be sent in the response

### ISSUE THREAD

**Issue by Maks3w** [OAI/OpenAPI-Specification#321]
Given the headers section has a definition for a given header (let's say ETag) the question is:

Is the header required to be present in the response sent by the server?

> headers: A list of headers **that are sent** with the response.
> https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#fixed-fields-10
> 
> Headers object: Lists the headers that **can be** sent as part of a response.
> https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#headersObject

Reading the first definition I understand that is _REQUIRED_.
Reading the second definition I understand that is _OPTIONAL_.

Spec should be rephrased clarifying this aspect.

**Comment by Maks3w** [comment]
IMO should be treated as *REQUIRED*

**Comment by webron** [comment]
That's an interesting and fair question. I'll have to dig into the discussions about it to see if we mentioned anything specific about it. However, even the first definition doesn't necessarily mean it is required, but rather suggested. Normally, when something is required, the term `MUST` is normally used across the spec to mention something is REQUIRED. However, I agree it is not clear enough and should be revised.

**Comment by Maks3w** [comment]
The argument because I think MUST be REQUIRED is that the header is linked to the response HTTP Code. 

So it's specific enough to assume these headers will be received always for this HTTP Code.

**Comment by webron** [comment]
I'm not disagreeing, but if the intent wasn't clarified originally, I may not be able to clarify it in this version of the spec as well. The current wording implies OPTIONAL over REQUIRED, but as said, I'll look into it.

**Comment by nfroidure** [comment]
What about a required=true attribute in the headers object definition?
https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#headersObject

I think it strongly depends on each headers type.

**Comment by Maks3w** [comment]
I only suggest when possible use the same validation rules as JSON-Schema. `required: boolean` is not a valid attribute.

**Comment by nfroidure** [comment]
Wasn't aware of the JSON-Schema compliance, but any property indicating the requirement would be great as well.

**Comment by nfroidure** [comment]
Say, minLength=1 when required ? http://json-schema.org/latest/json-schema-validation.html#anchor25

**Comment by Maks3w** [comment]
`minLength` and the rest of those validators are related with the value. i.e if the header value has a minLengh of 1.

**Comment by arno-di-loreto** [comment]
Totally agree with @nfroidure proposal (add a required property in header object).
We already have that for parameters (headers and non body parameters objects have a lot in common) , why couldn't we have the same thing on returned headers?

**Comment by webron** [comment]
Parent: #560

**Comment by webron** [comment]
The Header Object now follows a similar pattern to the Parameter Object and contains a `required` field which is by default `false`.

**Comment by cataggar** [comment]
> The Header Object now follows a similar pattern to the Parameter Object and contains a required field which is by default false.

https://swagger.io/specification/v2/ does not show that the `Header Object` has a `required` field like `Parameter Object`. It would be great if it did. I didn't find very many results in my initial search for examples:

- https://github.com/spec-first/connexion/pull/1293/files#diff-e4ea03dfac177f5d76a7f6662e64bdef20ef417cf76eb31cd762e1844427f5f3R1161

**Comment by cataggar** [comment]
In the currently spec, a `Header Object` includes it as it is almost the exact same as a `Parameter Object`.
https://spec.openapis.org/oas/latest.html#header-object
