### ISSUE TITLE
Empty value problem again (OpenAPI 3.0.3)

### ISSUE THREAD

**Issue by Ziggizag** [OAI/OpenAPI-Specification#3217]
Hi!

I read:

"In PR https://github.com/OAI/OpenAPI-Specification/issues/1573, targeted for the 3.0.2 patch revision, we have made use of allowEmptyValue NOT RECOMMENDED"

So, what is the right way to declare the API where:

- passing a given request body parameter with explicit value, updates the respected property on the server side.
- passing a given request body parameter with an "empty" string leaves the respected property intact on the server side.

Of course - for security reasons, I don't want to declare `additionalProperties: true`.

Any suggestions?

**Comment by MikeRalphson** [comment]
Probably best to explicitly set the `minLength` of your parameter to `0` if it is a string. You will have to document the intent of zero-length parameters and the effect it has within your API (i.e. leaving the value intact rather than emptying it).

**Comment by Ziggizag** [comment]
I have finally solved that this way:

status:
  description: Employee's activity status. 1 = active, 0 = inactive. You may leave it empty if it is supposed to be left intact.
  oneOf:
       - type: integer
          enum: [0, 1]
       - type: string
          maxLength: 0

**Comment by MikeRalphson** [comment]
Thanks - your solution will be searchable for others hitting the same problem.
