### ISSUE TITLE
Issue with StreamingResponse Media Type multipart/x-mixed-replace

### ISSUE THREAD

**Issue by Tamburasca** [OAI/OpenAPI-Specification#3227]
I seem to have missed a detail in defining the correct response type in the code below and I may require some assistance. The StreamingResponse is utilizing a multipart/x-mixed-replace media type and images are bmp,
could make them also be jpg, though.

I am receiving an error: "Unrecognized response type; displaying content as text."

Any suggestions welcome. Thanks.

OpenAPI v3.0.2
Firefox v.111.0.1
on Ubuntu 18

```python
@app.get("/stream/start",
         tags=["Pointing Camera Image"],
         name="Start streaming bmp frames\nNote: exposure times must not be <50 ms",
         description="Set all required features beforehand",
         responses={
             200: {
                 'content': {'multipart/x-mixed-replace':
                                 {'schema': {'type': 'string',
                                             'format': 'binary',
                                             'properties': {'profileImage': {}}
                                             },
                                  'encoding': {'profileImage':
                                                   {'type': 'string',
                                                    'contentMediaType': 'image/bmp',
                                                    }
                                               }
                                  }
                             }
             }
         },
         )
async def stream_start(
        cameraid: CameraEnum = Query(description="Camera ID"),
):
    def queue_fetch(t: BackgroundTasks) -> Iterable:
        while not t.is_stopped():
            try:
                frame = t.queue.get(block=True, timeout=30.)  # after timeout releases the screen
                frame.convert_pixel_format(PixelFormat.Mono8)
                buffer = cv2.imencode('.bmp', frame.as_opencv_image())[1]
                yield (b'--frame\r\n' b'Content-Type: image/bmp\r\n\r\n' +
                       bytearray(buffer) +
                       b'\r\n')
            except Empty:
                pass

    t = BackgroundTasks(daemon=True,
                        camera_id=cameraid.value,
                        c=app._cameras[cameraid.value])
    t.name = cameraid.value
    t.start()
    thread_list.append(t)

    return StreamingResponse(content=queue_fetch(t=t),
                             media_type='multipart/x-mixed-replace;boundary=frame',
                             )
```

**Comment by MikeRalphson** [comment]
Can you share a snippet of the actual generated OpenAPI document for those not familiar with that tool?

**Comment by Tamburasca** [comment]
I did not utilize the openapi-generator-cli

**Comment by MikeRalphson** [comment]
I didn't say you did :grin: But you have a bunch of annotations like `tag`, `name`, and `description` which look like they are there to generate an OpenAPI document.

**Comment by Tamburasca** [comment]
Ah yeah, forget about those. My focus is on the response, though, whether it is correct. On the interactive API documentation tool it does not stream bmp images throwing an error: "Unrecognized response type; displaying content as text.". Supposedly it is not even designed to do so. Single images don't show that issue.

**Comment by MikeRalphson** [comment]
What version of OpenAPI does your toolchain spit out?

**Comment by handrews** [comment]
Is there a spec for `multipart/x-mixed-replace` other than WHATWG?  WHATWG is useless unless you're writing a browser, and their media type registration template doesn't bother to say what the media type is meant for.

**Comment by Tamburasca** [comment]
No, sorry, I don't have it.

**Comment by handrews** [comment]
I don't think there's anything we can do here.  This repository is for the specification, not any tools, and this is about tooling behavior (whatever it is that's raising the "unrecognized media type" error).  I don't see a specification issue in this example.  Tooling support for media types not explicitly discussed in the OAS are at the discretion of tool vendors.
