### ISSUE TITLE
all schemes MUST be satisfied for a request to be authorized using annotation

### ISSUE THREAD

**Issue by LeonCai1** [OAI/OpenAPI-Specification#3236]
The documentation said "When a list of Security Requirement Objects is defined on the OpenAPI Object or Operation Object, only one of the Security Requirement Objects in the list needs to be satisfied to authorize the request." The example provided is 
```
security:    # A AND B
  - A
    B
``` 
how to do this using swagger annotation?

**Comment by MikeRalphson** [comment]
Please raise tooling-related issues on the relevant repository. This repository is for the OpenAPI specification itself. You may also receive more answers on a general support forum such as StackOverflow. Thanks.
