### ISSUE TITLE
Support for conditional and or in the body.

### ISSUE THREAD

**Issue by ameyergs1** [OAI/OpenAPI-Specification#3246]
I am new to OpenAPI so forgive the question please. In response to a request I have a need to require either a telephone number or an email address or both a telephone number and an email address. Is there a way to require at least one or both in OpenAPI?

**Comment by MikeRalphson** [comment]
There's nothing to forgive - this is the right place (or in Discussions) for specification related questions.

What you need is a schema combining keyword, in this case [`anyOf`](https://json-schema.org/understanding-json-schema/reference/combining.html#anyof):

```yaml
anyOf:
  - required: [ "telno" ]
  - required: [ "email" ]
```

**Comment by ameyergs1** [comment]
> There's nothing to forgive - this is the right place (or in Discussions) for specification related questions.
> 
> What you need is a schema combining keyword, in this case [`anyOf`](https://json-schema.org/understanding-json-schema/reference/combining.html#anyof):
> 
> ```yaml
> anyOf:
>   - required: [ "telno" ]
>   - required: [ "email" ]
> ```

Thank you for your answer.

**Comment by handrews** [comment]
Closing as the answer was accepted by OP.
