### ISSUE TITLE
Clarification on Path Item Servers

### ISSUE THREAD

**Issue by charjr** [OAI/OpenAPI-Specification#3248]
If "servers" are specified at the Path Item level, do they override Root level servers?

On an Operation Object it is explicitly stated that:
 _"If an alternative server object is specified at the Path Item Object or Root level, it will be overridden by this value."_

Do Path Item servers override Root level servers in the same manner? If not I assume it must add to the list of available servers (for that path only).

I would request that the PathItem servers Description be more explicit on whether it overrides, or adds to the Root level servers.

I'd be happy to put in a PR for this if I know what the correct behaviour is.

**Comment by MikeRalphson** [comment]
They do.

> An alternative server array to service all operations in this path.

I can see it would be beneficial to have the language in both places tidied up for consistency.

A PR for review would be great, thanks!

**Comment by handrews** [comment]
@charjr are you adding this to 3.0.4 as well?  This should stay open until it is merged in both branches.

**Comment by handrews** [comment]
@charjr no worries, it also goes in 3.1.1!

**Comment by charjr** [comment]
This has now been merged into 3.0.4 and 3.1.1
