### ISSUE TITLE
Expand Style Examples

### ISSUE THREAD

**Issue by charjr** [OAI/OpenAPI-Specification#3250]
Looking at the [Style Examples](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#style-examples) I cannot see what style I should use in the following instance:

A parameter `in: query` of `type: array` such that I could accept the following query string: `?param[]=X&param[]=Y`

If someone could enlighten me on this (and any other examples you can think of that might be missing) I would be happy to make a PR that adds them.

**Comment by MikeRalphson** [comment]
Is that querystring format defined somewhere?

**Comment by handrews** [comment]
Looks like this has been answered, so I'm going to close this - please open a new issue if there are remaining questions.

Note that `[` and `]` are technically not allowed in URLs (except in IPv6 literals), but that doesn't seem to stop people using them 🤦 and I guess it mostly works?  I'll be addressing this in the PR for #3759 so no need to track it here.
