### ISSUE TITLE
Required array of objects generates empty array when not being passed to req body

### ISSUE THREAD

**Issue by ivanovb3** [OAI/OpenAPI-Specification#3280]
I have an API endpoint which accepts an object.

```
paths:
  '/':
    post:
      tags:
        - organization-data
      summary: Create organization
      description: Create organization
      operationId: createOrganization
      requestBody:
        description: Create spec for an organization
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/OrganizationData'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationData'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
servers:
  - url: /organization-data
components:
  schemas:
    OrganizationData:
      $ref: 'api-defs.yaml#/OrganizationData'
```

The schema of the object consists of multiple fields, one of which is an array of objects.

```
OrganizationData:
  title: OrganizationData
  type: object
  required:
    - id
    - name
    - status
    - justArray
  properties:
    id:
      type: string
      description: The ID of the organization
    name:
      type: string
      description: The name of the organization
    justArray:
      type: array
      description: JustArray of objects
      items:
        $ref: '#/JustObject'
    status:
      $ref: '#/OrganizationStatus'
      description: Internationalized state name

JustObject:
  title: JustObject
  type: object
  required:
    - value
  properties:
    value:
      type: integer
      description: JustInteger
```

By specifying all of the fields as `required` I expect that not providing any of them would result in some form of validation error (which indeed happens for `id`, `name `and `status `in our case). However, upon not providing the `justArray` field as part of the `OrganizationData` in the request body, instead of any errors, OpenAPI seems to generate an empty array `[]` for its value. I have reproduced the issue multiple times and it seems to happen specifically for an array of objects. 
If `justArray` is removed from the list of required fields, the value is not populated and is `null` (which is expected)

My question is: Is this a bug or it is intended behaviour?

**Comment by karenetheridge** [comment]
> instead of any errors, OpenAPI seems to generate an empty array [] for its value
> If justArray is removed from the list of required fields, the value is not populated

"generating values" is not something that the OpenAPI spec describes. Is this some sort of documentation generation? Regardless, this is not something that can be solved in the issue queue for the specification itself, but rather that of whatever implementation you're using (you didn't say).

**Comment by ivanovb3** [comment]
I understand, but the implementation, in this case, does not seem to impact the property `justArray` being initialized without it being passed in the request body.

**Comment by handrews** [comment]
@ivanovb3 what you're talking about here is that the implementation is not implementing the spec correctly (but the spec itself already mandates the behavior that you want).  This repo is only for specification problems.  You need to file this bug against the implementation you are using.  Please let me know if I have misunderstood and I can re-open the issue.
