### ISSUE TITLE
tbarn:coc-enforcement-doc

### ISSUE THREAD

**Issue by Saud96525** [OAI/OpenAPI-Specification#3288]

**Comment by Saud96525** [comment]
tbarn:coc-enforcement-doc

**Comment by Saud96525** [comment]
| Header | Header |
|--------|--------|
| Cell | Cell |
| Cell | Cell |

**Comment by Saud96525** [comment]
https://github.com/OAI/OpenAPI-Specification/issues/3288#issuecomment-1567222667

**Comment by lornajane** [comment]
It's not clear what this issue is for. If you still need something from us, please re-open and add a description.
