### ISSUE TITLE
Is this supposed to be a string or a JSON value?

### ISSUE THREAD

**Issue by gregsdennis** [OAI/OpenAPI-Specification#3289]
https://github.com/OAI/OpenAPI-Specification/blob/9dff244e5708fbe16e768738f4f17cf3fddf4066/examples/v3.0/api-with-examples.yaml#L52

The YAML here yields a multiline string, but the other `value`s use a JSON value.  Was the string a mistake?

I note that in the [corresponding `.json` file](https://github.com/OAI/OpenAPI-Specification/blob/9dff244e5708fbe16e768738f4f17cf3fddf4066/examples/v3.0/api-with-examples.json#L56), it's also an encoded string, so it's probably correct.  Why would this be?

**Comment by handrews** [comment]
@jeremyfiel didn't this come up in one of our Slack discussions?

**Comment by jeremyfiel** [comment]
I believe we did have some discussion on it but can't find anything at the moment. 

The `value` keyword expects a `string` and the only way to define an object schema is to encode it as a string. `value` doesn't allow schemas if that were the example representation

**Comment by gregsdennis** [comment]
> The `value` keyword expects a `string` and the only way to define an object schema is to encode it as a string.

https://github.com/OAI/OpenAPI-Specification/blob/9dff244e5708fbe16e768738f4f17cf3fddf4066/examples/v3.0/api-with-examples.yaml#L91

This line is the exact same keyword, but this is parsed as an object, not a string.  Why is there a difference?

**Comment by darrelmiller** [comment]
@jeremyfiel The `value` property is defined as Any.

> To represent examples of media types that cannot naturally represented in JSON or YAML, use a string value to contain the example, escaping where necessary.

There is nothing to stop someone representing a JSON or YAML as a string also.  A consumer would have to do some reconciliation between the expected datatype of the parameter/content and the data type of the example value.

**Comment by gregsdennis** [comment]
> There is nothing to stop someone representing a JSON or YAML as a string also.

I would say that text implies that JSON/YAML _should not_ be embedded in a string.  I understand that it's not a hard requirement, but the implication seems quite apparent to me.

**Comment by handrews** [comment]
This is answered here:

* https://github.com/OAI/OpenAPI-Specification/issues/3041#issuecomment-1449051507

and that issue is in the 3.0.4 milestone to be clarified.  Closing this as a duplicate.
