### ISSUE TITLE
The return value type of `v3/api-docs` is byte array.

### ISSUE THREAD

**Issue by tszxxx** [OAI/OpenAPI-Specification#3319]
Hi there,

We're using openAPI to present our RESTful APIs. And we found an issue when we try to use that.
Spring Boot version: 2.7.12
Spring framework version: 5.3.25
Open API version: 1.7.0

When we don't use @EnableWebMvc annotation, and if we access `localhost:8080/v3/api-docs`, it will return an array of integers, which I'm pretty is the ascii code of the expected json file. And once we add @EnableWebMvc annotation, it could work, but it will also override the configuration inside the `application.xml`, so we don't really want to add @EnableWebMvc annotation.

Currently we are using @EnableWebMvc and override the `extendMessageConverters()` method to add the desired `ObjectMapper` in the class which implements the `WebMvcConfigurer` interface, but it looks weird, and we're looking for other good solutions.

Could you please give us some hints on how to find the really issue, or even how to solve it.

Thanks!

**Comment by handrews** [comment]
Hello!  This repo is for work on the specification itself.  Please open tooling issues with the tooling vendors (Spring Boot and/or framework), as that is where you will find folks with the knowledge you need to answer this.
