### ISSUE TITLE
White Label 404 error 

### ISSUE THREAD

**Issue by LorenzoPiombini** [OAI/OpenAPI-Specification#3333]
Good morning everyone, 

I am struggling with Open APi docs

I have the dependency in my pom file:
<img width="755" alt="Screenshot 2023-07-21 at 7 18 33 AM" src="https://github.com/OAI/OpenAPI-Specification/assets/69109614/a9edbe7d-422b-45dc-9039-d129753fe31e">

however it does not create any docs. The same dependency in another project works, I've tried to compare the two in order to understand what i am doing wrong, no luck so far.
the folder of my project is organized as follow: 

<img width="298" alt="Screenshot 2023-07-21 at 7 17 21 AM" src="https://github.com/OAI/OpenAPI-Specification/assets/69109614/9e81937f-c3f9-42c0-b48c-04577bf22383">

when i navigate to this links : 
http://localhost:9090/v3/api-docs
http://localhost:9090/swagger-ui/index.html

i have this error in both cases : 

<img width="618" alt="Screenshot 2023-07-21 at 7 31 02 AM" src="https://github.com/OAI/OpenAPI-Specification/assets/69109614/5e60725c-1c93-4191-9b36-e2f0f7170f7a">

<img width="717" alt="Screenshot 2023-07-21 at 7 35 22 AM" src="https://github.com/OAI/OpenAPI-Specification/assets/69109614/7d26ea68-4f3f-4219-a5df-053b4c3bcab1">

i checked the server port in the URL but it matches the one i configured for the app.

this is the link to the project https://github.com/LorenzoPiombini/schedule-builder
I apologize if this is not the right place to post this type of issues , I have read posts on Stack over flow and the FAQ from OpenApi 3, i could not find anything or I missed it.

thank you for your help 

Lorenzo

**Comment by handrews** [comment]
Hi Lorenzo - this repository is for the specification itself.  It looks like you're using Swagger UI, so you'll need to open this issue with them.  Particularly as this sort of dependency configuration is not determined by the OpenAPI spec.

**Comment by LorenzoPiombini** [comment]
I’m sorry !

Will do and thank you!

**Comment by handrews** [comment]
@LorenzoPiombini no worries, it's a very common misunderstanding! 🙂
