### ISSUE TITLE
[continue] Is there a way to indicate conditional interdependencies between object properties in a model?

### ISSUE THREAD

**Issue by kennyma-eplus** [OAI/OpenAPI-Specification#3339]
more on  #1321

For 3.0.3
I have a more complex question about this.. can someone help ?
for example:

```
{
	type: "object",
	propreties: {
		uiProfile: {
			type: "object",
			properties: {
				media: {
					type: "object"
				},
				copywriting: {
					type: "object",
					properties: {
						primary: {
							type: "object"
						}
					}
				},
			},
			status: {
				type: "string",
				enum: ["active", "inactive"]
			}
		}
	}
```

How to set the `uiProfile.copwriting.primary` to required only when `status` is `active`

**Comment by jdesrosiers** [comment]
In OpenAPI 3.0, where you don't have the `if`/`then` keywords, you can use the [Implication Pattern](https://json-schema.org/understanding-json-schema/reference/conditionals.html#implication)

**Comment by handrews** [comment]
Closing due to no further questions after the answer was given six months ago.
