### ISSUE TITLE
Example contains deprecated property

### ISSUE THREAD

**Issue by energister** [OAI/OpenAPI-Specification#3349]
Schema Object example [contains](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#model-with-example) `example` property that [has been deprecated](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-20).

**Comment by LasneF** [comment]
@handrews  ; Most of the job has been done 

there is one remaiing 
https://github.com/OAI/OpenAPI-Specification/blob/v3.1.1-dev/versions/3.1.1.md?plain=1#L1991 

but still we could close it ... or fix the last one

**Comment by handrews** [comment]
@LasneF thanks for checking!  Those two are actually the `example` field in the Media Type Object, which supports both `example` and `examples`, which are distinct from the JSON Schema `examples` or the OAS legacy Schema Object `example` 🤦 

The whole mess has been explained better with PR #3895, so I'm going to close this as it should be as clear as it gets at this point.

I did search 3.1.1.md for `/examples?"?:/` and didn't find anything that looked incorrect to me.
