### ISSUE TITLE
string type has only password format in docs

### ISSUE THREAD

**Issue by david-w-t** [OAI/OpenAPI-Specification#3353]
[data types](https://spec.openapis.org/oas/v3.1.0#data-types) has only one string type and is given the password format, which seems odd.  I would think there would be a general string type, right?

**Comment by david-w-t** [comment]
PR created: https://github.com/OAI/OpenAPI-Specification/pull/3354

**Comment by handrews** [comment]
See PR for comments on closing it - it looks like all necessary formats are in the format registry, so I'm going to close this.  Please open a PR against the format registry (not the spec) if anything is truly missing.
