### ISSUE TITLE
TOB update?

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#3356]
It seems like the TOB info on https://github.com/OAI/OpenAPI-Specification/blob/main/TOB.md is a bit outdated. If there is an update to the board, maybe add the updated info there?

**Comment by darrelmiller** [comment]
There has been no need for the TOB since its inception, so the process around it has been been neglected.  Not sure if we should continue with it or not.

**Comment by MikeRalphson** [comment]
+1 on disolving the TOB and up-delegating its responsibilities directly to the BGB.

**Comment by handrews** [comment]
I'm going to close this in favor of #3482 (also submitted by @dret, who clearly wants somehing done here! 😄 ) which has slightly more discussion going.
