### ISSUE TITLE
Adding a feature in schema configuration

### ISSUE THREAD

**Issue by vamsi-6579** [OAI/OpenAPI-Specification#3357]
If we want to hide the field in a schema i.e., if we don't want to show the field in swagger UI, what is the property we need to add to that field in yaml file 
example:
properties:
  id:
    type: integer
    hidden: true

like this

**Comment by S0PH0S** [comment]
is this the notation you are looking for:

 requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: integer
                secretField:
                  type: string
                  x-ms-visibility: internal  # Use this extension to hide the field


________________________________
From: vamsi-6579 ***@***.***>
Sent: August 22, 2023 03:25
To: OAI/OpenAPI-Specification ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OAI/OpenAPI-Specification] Adding a feature in schema configuration (Issue #3357)


If we want to hide the field in a schema i.e., if we don't want to show the field in swagger UI, what is the property we need to add to that field in yaml file
example:
properties:
id:
type: integer
hidden: true

like this

**Comment by vamsi-6579** [comment]
but is also not working

**Comment by vamsi-6579** [comment]
components:
  schemas:
    Customer:
      title: Customer
      type: object
      properties:
        customerId:
          type: array
          items:
            type: string
        entitlementId:
          type: string
          x-ms-visibility: internal


this is my configuration but still it is showing entitlementId?

**Comment by handrews** [comment]
@vamsi-6579 this repository is for the specification itself.  It sounds like you need to open this issue with your tooling vendor (swagger UI).

**Comment by vamsi-6579** [comment]
Yes, basically not only in swagger UI..if this specification works, we need to use the OAS in some other places like apigee developer portal where the complete flow depends on OAS

**Comment by handrews** [comment]
Format registry- meant to include in previous comment https://spec.openapis.org/registry/format/

**Comment by handrews** [comment]
The specification part of this issue was answered some time ago with no further responses, so I'm closing this as resolved.
