### ISSUE TITLE
Kotlin client code generator with `jvm-ktor` library having compile time error

### ISSUE THREAD

**Issue by kamal-github** [OAI/OpenAPI-Specification#3361]
When we generate client using `jvm-ktor` library, the generated client is having compile time error.

It passes the extra argument - `jsonBlock` along with 3 required args with all of the APIs under `api/` directory.

```
    open class AgentPoolApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(baseUrl, httpClientEngine, httpClientConfig, jsonBlock) {
  // redacted
}
```

But the superclass contract is as below with 3 expected parameters
```
open class ApiClient(
        private val baseUrl: String,
        httpClientEngine: HttpClientEngine?,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
) {
 // redacted
}
```

For your information, the gradle task:

```
plugins {
    // redacted
    id "org.openapi.generator" version "7.0.0"
}

openApiGenerate {
    inputSpec = "api/petstore/api.yaml"
    generatorName = "kotlin"
    outputDir = "$buildDir/generated"
    apiPackage = "petstore.api"
    modelPackage = "petstore.model"
    packageName = "petstore"
    configOptions = [
            library: "jvm-ktor",
            serializationLibrary: "kotlinx_serialization"
    ]
}
```

**Comment by darrelmiller** [comment]
This is not the right place for reporting issues with tooling. The OpenAPI Initiative does not produce tooling, just a specification.  The OpenAPI Generator project has no affiliation with this organization. They just chose their name poorly.

**Comment by cobertvc** [comment]
open class AgentPoolApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    ) : ApiClient(baseUrl, httpClientEngine, httpClientConfig, jsonBlock) {
  // redacted
}
