### ISSUE TITLE
Maybe choose a different name? We already have Python versions shipped where `RESUME_QUICK` means "quickened `RESUME` instruction". Perhaps something that indicates it's suitable for higher tiers, such as `RESUME_OR_DEOPT` or `RESUME_OPTIMIZED`? I don't know, naming is hard...pip install Markdown

### ISSUE THREAD

**Issue by Giangpro89** [OAI/OpenAPI-Specification#3362]
Maybe choose a different name? We already have Python versions shipped where `RESUME_QUICK` means "quickened `RESUME` instruction". Perhaps something that indicates it's suitable for higher tiers, such as `RESUME_OR_DEOPT` or `RESUME_OPTIMIZED`? I don't know, naming is hard...

_Originally posted by @brandtbucher in https://github.com/python/cpython/pull/108630#discussion_r1309312395_

**Comment by Thomasdr06** [comment]
Blackpython

**Comment by Thomasdr06** [comment]
Resume

**Comment by handrews** [comment]
This seems like a bot gone wrong; closing.
