### ISSUE TITLE
Good or Bad Practice? Referencing requestBodies in Schemas

### ISSUE THREAD

**Issue by Jeroen-01** [OAI/OpenAPI-Specification#3383]
Hi all,

I have been playing around with the OpenAPISpec v3.0.3, and have a question on good or bad practice.

**Context**
APIs often expose methods to get or create resources. Normally, we had to create separate objects for Create and Get-operations, as not all attributes are part of the Request Body when creating an object, e.g. the ID.

Example below for listing all Pets:

````
GET /pets

{
  "pets" : 
        [
            "id" : "f7b918dc-c520-4ca1-bbfc-0105477500a0",
            "name" : "Fluffy",
            "petType" : "cat"
        ]
}
````

Example for creating a Pet:

````
POST /pets

{
      "name" : "Charlie",
      "petType" : "dog"
}
````

The smallest common denominator for the Pets-object is described by the `RequestBody` for the resource and method `POST /pets`. Would it therefore be a good or a bad practice to define a Schema for the Pets-object, referencing the Request Body specified for creating a Pet?

Example below:

````
components:
  requestBodies:
    CreatePet:
      description: Create a Pet
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the Pet
              petType:
                type: string
                description: Type of Pet

  schemas:
    Pet:
      allOf:
        - type: object
          properties:
              id:
                type: string
                description: Identifier of the Pet
        - $ref: '#/components/requestBodies/CreatePet/content/application~1json/schema'
````

Note that `openapi v3.0.3` **allows** this specification, albeit only in SwaggerEditor. Other API Design tools I've tested do not (yet) support referencing of `requestBodies`.

**Comment by handrews** [comment]
@Jeroen-01 typically you want to put all of your re-usable schemas (or other components) directly under `#/components`, and `$ref` from wherever they are used.  The way you have it above, `$ref`-ing into a schema under a request body, is totally legal, but it makes the re-use patterns a little less clear.

So what I would do would look more like this:

```YAML
components:
  requestBodies:
    CreatePet:
      description: Create a Pet
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MinimalPet'
  schemas:
    MinimalPet:
      type: object
      properties:
        name:
          type: string
          description: Name of the Pet
        petType:
          type: string
          description: Type of Pet
    Pet:
      allOf:
        - type: object
          properties:
              id:
                type: string
                description: Identifier of the Pet
        - $ref: '#/components/schemas/MinimalPet'
```

I'm guessing you might also want to add `required: [id]` under `#/components/schemas/Pet/allOf/0`?

**Comment by darrelmiller** [comment]
I would not do it.  As Henry suggested, I would only reference things that live in the components section.
