### ISSUE TITLE
Many of the links within the OpenAPI docs do not work

### ISSUE THREAD

**Issue by colingcresset** [OAI/OpenAPI-Specification#3388]
I have been looking at https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md and noticed many of the links don't navigate, such as https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#pathsObject.

This is just one example of many for this document.

The Firefox browser (version 118.0.1) on Windows 11 has been used to check the links.

**Comment by handrews** [comment]
Dup of #3197 (see last comment there for recent update)
