### ISSUE TITLE
`password` data type redaction should not be limited to UI

### ISSUE THREAD

**Issue by mgrafl** [OAI/OpenAPI-Specification#3404]
The `password` setting of the modifier property `format` is described in the _Data Types_ section as "A hint to UIs to obscure input."

https://github.com/OAI/OpenAPI-Specification/blob/ddcab423f5d440f4574d5c37eea8daab864806ef/versions/3.1.0.md?plain=1#L160

Since the OpenAPI Specification is also relevant for backends, the description should be generalized, e.g., "A hint to UIs and backend systems to obscure/redact the value."

An example for the necessity of redacting the value of a `password` field is in the `toString` method generated by the _openapi-generator_ tool: https://github.com/OpenAPITools/openapi-generator/issues/16851

**Comment by MikeRalphson** [comment]
This looks like a useful improvment, thank you. Do you have time to work up a PR on the `v3.1.1-dev` branch?
