### ISSUE TITLE
Global/common parameters

### ISSUE THREAD

**Issue by noirbizarre** [OAI/OpenAPI-Specification#341]
Global parameters are common in API definition.
Authentication paramters were made specifics with the ``security`` property but there is no way to define global common paramters.

Most of the time global parameters are business-less parameters and it make sense to define them globally.

I know it's possible to define reusable parameters through the root ``parameters`` property but it's not the same thing, it does not respond to the need.

I have a lot of entry point in the API and I don't want to repeat parameters like ``lang``, ``pretty`` or ``fields`` which are global and not functionnaly related to each endpoint.

Is there a way I'm not aware to do that like a ``globalParameters`` property ?

If not, is it possible to add that for the next specification release as it's a common use case.

**Comment by webron** [comment]
One problem with that feature is that users may then request a way to 'ignore global parameters' and that's going to complicate things. We've thought about adding it to 2.0 but it was rejected.

That said, it does not mean it shouldn't be a proposal for the next version.

**Comment by noirbizarre** [comment]
I understand. But maybe it should be explicit that's only non ignorable parameters, API-wide parameters.

I will be glad if this can be proposed proposed and discussed for the next version.

I agree, there shouldn't be a way to ignore these: it's over-complicated and most of the time it's bad usage of global parameters (if someone have a counter example)
Global parameters shouldn't be considered as a facility to avoid repetition, but as real global parameters independent from the business, so not overridables.

I maintain multiple APIs and it's a very common and recurrent use case (with at least the following examples: ``lang``, ``pretty``, ``fields``, ``format``, ...).
Each time they have the following attributes:
- optional query-string parameter, have a sane default value.
- non-business related (it does not modify the functionality of operations) 
- transport or format related
- technically, they are not handled by the same piece of software, so difficult to declare on every operation in code-to-specs approach

If some want to ignore a parameter on an operation, it should be seen as "rare exception" and shouldn't prevent the existence of global parameters in the specifications.
For them, I would say it's easier to set optionnal parameter or parameters with default value and on the ignoring operation, simply add a note that the parameter won't have effect.

**Comment by 4thex** [comment]
Perhaps if the parameters were linked with a tag, it could apply to all operation objects with the same tag. If the tag was left out, it would be global.

**Comment by webron** [comment]
Parent issue: #560.

**Comment by fehguy** [comment]
Closing in favor of #633

**Comment by hkosova** [comment]
Why is this closed? https://github.com/OAI/OpenAPI-Specification/pull/633 (`components` object) is not the same as global parameters.
