### ISSUE TITLE
Conditional Response Class

### ISSUE THREAD

**Issue by cancan101** [OAI/OpenAPI-Specification#342]
[Post from Group](https://groups.google.com/d/topic/swagger-swaggersocket/7vgdAgBzHB0/discussion):
Is there any support in swagger for expressing the Response Class conditional on a query parameter?

For example, if `deep=1` is set, then to expect deeper nesting of data instead of just the URL/ pk?

In the case of my `deep=1` example, this would be whether to use a `$ref` for a model property or just a primitive.

This idea is supported in JSON API, see [Inclusion of Related Resources](http://jsonapi.org/format/#fetching-includes).

The simplest approach would be to indicate the that a given field has two types: either a primitive pk/URL or the deeper nested type along with a description of what distinguishes the return.

``` yaml
$ref: Product
type: string
format: uuid
conditional: deep==1
```

**Comment by jasonh-n-austin** [comment]
$.02: This has big value in mocking.

**Comment by handrews** [comment]
@cancan101 if this is still of interest (yikes, nearly 5 years old? 😬 ) can you explain the conditional a bit more?  When you say `deep=1` is set, what does that mean and how would a validator figure it out?  Is that supposed to come from request parameters or is it some other sort of thing?

**Comment by handrews** [comment]
This is being addressed in OAS 4 Moonwalk by the [principle of operation signatures](https://www.openapis.org/blog/2023/12/06/openapi-moonwalk-2024).  Please join the [discussions](https://github.com/OAI/sig-moonwalk/discussions) in that repository if you are interested!
