### ISSUE TITLE
Clarification on `discriminator` usage on `allOf` schemas.

### ISSUE THREAD

**Issue by iglosiggio** [OAI/OpenAPI-Specification#3424]
Hi, the spec says:
> The discriminator object is legal only when using one of the composite keywords `oneOf`, `anyOf`, `allOf`.

What's the meaning behind something like this?
```yaml
components:
  schemas:
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - $ref: '#/components/schemas/Furry'
      - $ref: '#/components/schemas/Cute'
      discriminator:
        propertyName: "petType"
    # ... descriptions of other schemas
```

I don't see an obvious intepretation for an schema that has both `discriminator` and `allOf`.

**Comment by karenetheridge** [comment]
`allOf` (or `anyOf` or `oneOf`) are expected, but they don't have to be at the same level -- there is one example in the spec at the same level and one where they are in separate definitions. The schema that requires them together is a mistake - see https://github.com/OAI/OpenAPI-Specification/pull/3405.

**Comment by handrews** [comment]
I think the `oneOf` or `anyOf` need to be in the same schema object as `discriminator`, but the `allOf` use case is different and is always in a different schema object.  I think.

**Comment by LasneF** [comment]
is there a use case of having discriminator and allof ? 

to me discriminator should only be use for the oneOf  the usage of it inside an anyOf beeing quite alredy limited/corner case

discriminator could even be dropped 
pushing that  schema with a oneOf must be completly exclusive by nature (ie a content cannot match 2 schema)

**Comment by iglosiggio** [comment]
> The schema that requires them together is a mistake - see #3405.

Sorry but what does _"The discriminator object is legal only when using one of the composite keywords"_ means then?

**Comment by handrews** [comment]
@LasneF OAS 4.0 a.k.a. Moonwalk is [definitely separating concerns more thoroughly](https://www.openapis.org/blog/2023/12/06/openapi-moonwalk-2024), including better separation between content schema formats and OAS "proper".  There aren't any specifics on what that means yet, but it will be addressed in the coming year (note that there is a separate OAI/Moonwalk repository for that project).

Doing any such thing would be too big of a change for a 3.1.x, or even a 3.2, although of course in 3.1 JSON Schema is at least theoretically extensible with 3rd-party keywords.

**Comment by handrews** [comment]
PRs merged!  closing.
