### ISSUE TITLE
Clarification on `servers` fixed field overrides

### ISSUE THREAD

**Issue by char0n** [OAI/OpenAPI-Specification#3427]
Hi everybody,

I'm seeking for clarity related to `servers` fixed field in **OpenAPI 3.x.y**. `servers` fixed field can be defined on following specification objects:

- **OpenAPI.servers**

**Description:**

> [Server Object]	An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of `/`.

- **PathItem.servers**

**Description:**

> An alternative server array to service all operations in this path.

- **Operation.servers**

**Description:**

> An alternative server array to service this operation. If an alternative server object is specified at the Path Item Object or Root level, it will be overridden by this value.

---

Given this, I would assume that if I would define `PathItem.servers = []` or `Operation.servers = []`, there is no implicit default Server Object creation with a url value of "/". It's just going to be defined as empty array, right (exactly as I defined it)? Only the `OpenAPI.servers` has this ability to create default Server Object - Am I correct in my assumptions?

---

Related https://github.com/OAI/OpenAPI-Specification/issues/3248

**Comment by char0n** [comment]
For OpenAPI spec to work properly, I assume the following must apply to every servers fixed field, not just OpenAPI.servers:

> If servers is an empty array, the default value would be a Server Object with a url value of `/`

**Comment by char0n** [comment]
Empty server list

**Input**
```
OpenAPI.servers = []
PathItem.servers = []
Operation.servers = []
```

**Output**
```
OpenAPI.servers = [{url: '/'}]
PathItems.servers = <copyOf>OpenAPI.servers
Operation.servers = <copyOf>OpenAPI.servers
```

Not defined server list


**Input**
```
<missing field>OpenAPI.servers
<missing field>PathItem.servers
<missing field>Operation.servers
```

**Output**
```
OpenAPI.servers = [{url: '/'}]
PathItems.servers = <copyOf>OpenAPI.servers
Operation.servers = <copyOf>OpenAPI.servers
```

---

The description of PathItem.servers talks about "If an alternative `server object` is specified at the Root level, it will be overridden by this value."

The description of Operation.servers talks about "If an alternative `server object` is specified at the Path Item Object or Root level, it will be overridden by this value."

These descriptions refer to server object  in singular, which makes me infer that defining those fields as empty array is the same as not defining them at all and confirms the above input/output pairs.

**Comment by handrews** [comment]
@char0n does the [API Servers](https://learn.openapis.org/specification/servers.html) page on the Learn site answer your question?
