### ISSUE TITLE
Validation of the default keyword in ParameterObject

### ISSUE THREAD

**Issue by pipermerriam** [OAI/OpenAPI-Specification#343]
I would like to continue a discussion that began [here](https://github.com/pipermerriam/flex/issues/76) regarding the proper way to validate the `default` keyword in the [`ParameterObject`](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#parameterObject).

According to the 2.0 version of swagger, the value of the `default` keyword _"MUST conform to the defined type for this parameter."_

The issue I would like to discus centers around how to validate the `default` keyword for a parameter with the following schema.

``` javascript
"parameters": [
  {
    "name": "status",
    "in": "query",
    "type": "array",
    "items": {
      "type": "string"
    },
    "collectionFormat": "multi",
}
```

Consider the following two query strings.
- `/?status=available&status=pending`
- `/?status=available`

Given that the `type` of the `status` parameter is `"array"`, they should parse roughly into the following values.
- `/?status=available&status=pending > ["available", "pending"]`
- `/?status=available > ["available"]`

However, in most frameworks, it is also reasonable to parse the second as `/?status=available > "available"`.

So, the question is whether or not one or both of the following should be considered valid for the `default` keyword.
- A: `"default": ["available"]`
- B: `"default": "available"`

I believe that `A` is pretty clearly valid since it is of the `type` `"array"`.  I am curious what others think about whether `B` should be considered valid.  

While many frameworks/languages tend to parse singular query parameters to the singular version of that value, they often do so without prior knowledge of the `type` declared for that value.  However, when validating a swagger schema, we have context and full knowledge of the `type`, and thus it seems odd to me to allow the singular string `"available"` when it does not match the type signature of the parameter.

**Comment by pipermerriam** [comment]
Still hoping to get some feedback on this.

**Comment by webron** [comment]
@pipermerriam - sorry for the delay, but here's my take.

As you said, when it comes to Swagger, the type is predefined and known, and we should treat it as such.

In case of an array, regardless of the collectionFormat, the value should be a JSON array with the value. In the example you gave:

```js
"default": [ "available" ]
```

**Comment by lornajane** [comment]
I think the answer from Ron answers the original question, and we haven't had much interaction for a while so I'm closing
