### ISSUE TITLE
Set-Cookie header to write two cookies

### ISSUE THREAD

**Issue by razb-viola** [OAI/OpenAPI-Specification#3446]
I want to write `accessToken` cookie and `csrfToken` as well - at one response.
I tried many things but nothing works.

**Comment by handrews** [comment]
@razb-viola this repository is for the specification itself, not any particular implementation.

As far as the specification is concerned, you can do this by defining two cookie parameters, one named `accessToken` and one named `csrfToken`.  If the implementation you are using does not do what you want with those, you should raise that issue with whoever makes the implementation.

**Comment by Ewind218** [comment]
// Declaration
class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
}

// Expression; the class is anonymous but assigned to a variable
const Rectangle = class {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
};

// Expression; the class has its own name
const Rectangle = class Rectangle2 {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
};
