### ISSUE TITLE
Clarification regarding reflecting rest parameters in OpenAPI specification

### ISSUE THREAD

**Issue by SachinAkash01** [OAI/OpenAPI-Specification#3448]
Hi Team!

I am working with Ballerina OpenAPI tool, specifically utilizing rest parameters in the path of a resource function, where they act as an array. For example:
```ballerina
resource function get albums/[string... title]() {}
```

This allows us to send a request like:
`GET albums/title1/title2/title3`

In the resulting URL, these parameters are concatenated with `%2F` (encoded value for `/`), and it looks like:
`http://{hostName}:{port}/albums/title1%2Ftitle2%2Ftitle3`

I am seeking guidance on how to accurately reflect this behavior in the OpenAPI specification. Specifically, I would like to understand how to handle parameter serialization using the `style` and `explode` attributes in this scenario.

Could you provide insights or examples on how to properly represent this scenario in the OpenAPI specification. Is there a proper way to do that?

[#1459](https://github.com/OAI/OpenAPI-Specification/issues/1459)

**Comment by commonism** [comment]
https://spec.openapis.org/oas/v3.1.0#style-values
Examples for `titles = ["no 1","best of"]`
Array Query Parameters can be encoded as Simple (no%201,best%20of) Label (`.no%201.best%20of`) or Matrix (`;titles=no%201,best%20of`) none of which match your encoding.

Explode true for matrix ends up with `;titles=no%201;titles=best%20of`

```
import sys

import httpx

from aiopenapi3 import OpenAPI

spec = """
openapi: "3.0.0"
info:
  title: titles
  version: 1.0.0
  description: https://github.com/OAI/OpenAPI-Specification/issues/3448

servers:
  - url: http://127.0.0.1/api

paths:
  /albums/{titles}:
    parameters:
    - name: titles
      description: ""
      required: True        
      in: path
      style: matrix
      explode: true
      schema:
        type:
          array
        items:
          type: string
      
    get:
      operationId: albums
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items: 
                  type: string
"""

def test_loader_format(httpx_mock):
    titles = ["no 1","best of"]
    httpx_mock.add_response(headers={"Content-Type": "application/json"}, status_code=200, json=titles)
    api = OpenAPI.loads("http://127.0.0.1/openapi.yaml", spec, session_factory=httpx.Client)
    api._.albums(parameters={"titles":titles})
    request = httpx_mock.get_requests()[-1]
    print(request.url)
    return None
```

**Comment by lornajane** [comment]
Hi everyone, sorry about the noise on this pull request, we have some new automation and apparently it is still settling in! I think I've removed the label that was causing this behaviour, please accept our apologise and proceed as normal.

@baywet Could you take a look at this please? I just added the author feedback label today and it immediately started adding the recent-activity thing, repeatedly :scream:

**Comment by baywet** [comment]
@lornajane sorry about the confusion this caused here. Here is a PR to address the many issues https://github.com/OAI/OpenAPI-Specification/pull/3457

**Comment by SachinAkash01** [comment]
> https://spec.openapis.org/oas/v3.1.0#style-values Examples for `titles = ["no 1","best of"]` Array Query Parameters can be encoded as Simple (no%201,best%20of) Label (`.no%201.best%20of`) or Matrix (`;titles=no%201,best%20of`) none of which match your encoding.
> 
> Explode true for matrix ends up with `;titles=no%201;titles=best%20of`
> 
> ```
> import sys
> 
> import httpx
> 
> from aiopenapi3 import OpenAPI
> 
> spec = """
> openapi: "3.0.0"
> info:
>   title: titles
>   version: 1.0.0
>   description: https://github.com/OAI/OpenAPI-Specification/issues/3448
> 
> servers:
>   - url: http://127.0.0.1/api
> 
> paths:
>   /albums/{titles}:
>     parameters:
>     - name: titles
>       description: ""
>       required: True        
>       in: path
>       style: matrix
>       explode: true
>       schema:
>         type:
>           array
>         items:
>           type: string
>       
>     get:
>       operationId: albums
>       responses:
>         '200':
>           description: ok
>           content:
>             application/json:
>               schema:
>                 type: array
>                 items: 
>                   type: string
> """
> 
> def test_loader_format(httpx_mock):
>     titles = ["no 1","best of"]
>     httpx_mock.add_response(headers={"Content-Type": "application/json"}, status_code=200, json=titles)
>     api = OpenAPI.loads("http://127.0.0.1/openapi.yaml", spec, session_factory=httpx.Client)
>     api._.albums(parameters={"titles":titles})
>     request = httpx_mock.get_requests()[-1]
>     print(request.url)
>     return None
> ```

Thank you @commonism for the prompt response and the provided example. I've reviewed the example with explode-style encoding and explode set to true. However, it still doesn't quite match with the behavior I'm observing with Ballerina rest parameters in the resource path. 

After having some discussions, we decided to map this scenario in another way using wildcard path in OAS. You can refer the issue I have created regarding this here: [ballerina-platform/ballerina-library/issues/5816](https://github.com/ballerina-platform/ballerina-library/issues/5816)

**Comment by handrews** [comment]
This also falls under #2653 and is likewise being addressed through the Moonwalk project (see links in that issue's last comment).
