### ISSUE TITLE
NWAGStudio - Duplicate class created when oneOf is defined in the model

### ISSUE THREAD

**Issue by TaniaDianne** [OAI/OpenAPI-Specification#3450]
Hello,

I am using oneOf in a recent schema and finding duplicate classes are being generated by nSwagstudio when the oneOf is part of the schema instead of the query. Is it valid to use oneOf in the referenced schema?

Example: Here the query references the schema

![image](https://github.com/OAI/OpenAPI-Specification/assets/87718383/69e77b96-3b49-4d0b-9aa0-94390e494ba4)

and the schema is defined using oneof:

![image](https://github.com/OAI/OpenAPI-Specification/assets/87718383/fdacd8c8-1c3b-49a6-903a-a15af855ac6a)

We were able to resolve this by moving the mapping to the query but I wanted to check if both scenarios were valid and if it is a codeGen issue rather than a schema issue

![image](https://github.com/OAI/OpenAPI-Specification/assets/87718383/1f4baec2-245c-427b-a177-d78fed20f866)

**Comment by LasneF** [comment]
to me looks more a code gen issue than a schema issue

**Comment by handrews** [comment]
Agreed - @TaniaDianne this repository is for specification-writing.  You will need to raise this issue with NSWAGStudio.

(@LasneF thanks for your comments on various issues like this, it makes it easy for the triage team- which we are trying to revive as of the last weekly call of 2023 -  to find and close them).
