### ISSUE TITLE
Update DEVELOPMENT.md to explain labels and processes

### ISSUE THREAD

**Issue by earth2marsh** [OAI/OpenAPI-Specification#3452]
Following the merge of  #3437 , might we want to update the DEVELOPMENT.md to explain our labeling system and process, including what is automated and what is manual?

**Comment by baywet** [comment]
you can assign this to me if you want, happy to update things. I didn't know this document existed.

**Comment by earth2marsh** [comment]
That would be great, @baywet , thanks! I'm happy to be a reviewer if you want to assign it to me when you're ready.
