### ISSUE TITLE
Request body is not on the swagger

### ISSUE THREAD

**Issue by TingNLP** [OAI/OpenAPI-Specification#3460]
**environment**
python 3.8
flasgger 0.9.7.1

**hello.yaml**
`
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          id:
            type: string
            example: 1
responses:
  200:
    description: return hello world
    type: string
`

**main.py**
`
@app.route('/hello', methods=['GET'])
@swag_from('yaml/hello.yaml')
def hello():
    return "hello world"
`

**swagger interface**

![image](https://github.com/OAI/OpenAPI-Specification/assets/54096137/ef46d3dc-3d5d-4efb-b39d-61c167fbb82f)

according to  https://editor.swagger.io/ settings.
I dont't know why **Request body** does not show on the swagger.
Does anyone know where my settings are wrong?

thanks.

**Comment by handrews** [comment]
Hi @TingNLP – This repository is for specification-writing.  It looks like you are having an issue with the Swagger tool from SmartBear.  You should raise this issue with them.
