### ISSUE TITLE
OneOf property is failing during OAS  Schema Validation

### ISSUE THREAD

**Issue by RPS044** [OAI/OpenAPI-Specification#3461]
Hello Team,

Requesting you to please check this issue and help. Performing schema validation with oneOf, discriminator and mapping property in oas3.0.

_**Error:**_
{
"fault": {
"faultstring": "OASValidation MAM-EXT-SpecValidation with resource "oas://openapi.yaml": failed with reason: "[ERROR - An error occurred during schema validation - com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException.: []]"",
"detail": {
"errorcode": "steps.oasvalidation.Failed"
}
}
}

**_yaml file looks like:_**

![image](https://github.com/OAI/OpenAPI-Specification/assets/96113675/aa3eb3d1-f2fc-4542-849a-665456042b38)
![image](https://github.com/OAI/OpenAPI-Specification/assets/96113675/0ae23bd2-1ff5-4f95-89ca-dc7b456db62d)

**_json payload looks like:_**

`--data '{
  "billableHeader": {
    "sourceSystem": "UPSTREAM_APP",
    "sourceTransactionType": "INVOICE",
    "eventType": "BATCH",
    "messageCreationDatetime": "20220811140203",
    "timeZoneCode": "GMT",
    "isBulkProcessing": true,
    "product": "Airlcl"
  },`

**Comment by RPS044** [comment]
Any updates

**Comment by RPS044** [comment]
@timburks @danhorst @duncanbeevers @elazar Please provide your feedback

**Comment by LasneF** [comment]
not sure your are in the right place here it is about the OAS specification itself  , rather than you mentionned more a tooling issue 

still looks strange to me to have this contruction 

![image](https://github.com/OAI/OpenAPI-Specification/assets/12461661/7885be1d-6c6f-47a9-b5e2-c0950543d2ac)

and kind of break the law of 
"The discriminator object is legal only when using one of the composite keywords oneOf, anyOf, allOf. "

**Comment by handrews** [comment]
This definitely looks like a tooling issue.  You may or may not be using `discriminator` correctly.  If you are using it with `allOf`, then it's not clear where the `allOf`s are for anyone to judge.  If you are using it with `oneOf` or `anyOf`, those must be in the same schema object with `discriminator` and neither are shown here.

However, misusing `discriminator` should not cause a NullPointerException.  That is a tooling bug that you need to raise with the tooling vendor.
