### ISSUE TITLE
oneOf behaviour clarification

### ISSUE THREAD

**Issue by SAPRD2** [OAI/OpenAPI-Specification#3477]
We were going through the oneOf explanations given in the [swagger](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/) website.
![image](https://github.com/OAI/OpenAPI-Specification/assets/125257937/97d3f248-666b-44d4-a85a-60fd87bedd33)
As mentioned above, in the case of oneOf, the input
```
{
  "bark": true,
  "breed": "Dingo" 
}
```
is a valid input. But, looking closely at the given spec, we see that it is a valid input for both the schemas, since neither the `required`, nor the `discriminator` keyword is defined in any schema (Cat or Dog), which means that the above input is a valid input for both the schemas.
Can you please clarify if the above input is a valid input for the given schema or not ?
Thanks.

**Comment by iglosiggio** [comment]
It should not be: `oneOf` requires that validation succeeds against **exactly one** schema. Adding a discriminator should not change this behavior.

**Comment by SAPRD2** [comment]
So based on that, should the documentation be changed to say that it is NOT a valid input for the given oneOf example ?

**Comment by LasneF** [comment]
you are right , but notice that the website you refer belong to SmartBear , and ont OAS specficiation. That said you can ping them for sure .  The OAS spec could have this kind of sample, but this would also be the duty of JsonSchema 
if you want to have more around that you can have a look there 
https://json-schema.org/blog/posts/applicability-json-schema-fundamentals-part-1#putting-everything-together-avoiding-oneof-pitfalls 

Try to grab SmartBear Folks to fix it will be indeed good for the community as they are an important actor over there

**Comment by handrews** [comment]
Since there is no problem with the specification here (which is what this repo is for), I'm going to close it.  But I join the other folks in encouraging you to file this issue with SmartBear/Swagger!  Thank you for asking about it :-)
