### ISSUE TITLE
I developed an openapi ui document that supports swagger2 and openapi3. I hope everyone can improve it together

### ISSUE THREAD

**Issue by rookie-luochao** [OAI/OpenAPI-Specification#3492]
repo is: https://github.com/rookie-luochao/openapi-ui
![12](https://github.com/OAI/OpenAPI-Specification/assets/22948077/aff8634f-a0c5-4fa1-b5cd-8e6befb3f779)

**Comment by rookie-luochao** [comment]
thanks

**Comment by handrews** [comment]
Yes, this should be directed to tool trackers like openapi.tools, so I'm closing this issue- thank you for your work in the OpenAPI ecosystem!

**Comment by handrews** [comment]
@rookie-luochao I forgot that we also have the [OAI/Tooling](https://github.com/OAI/Tooling) repo for tracking tools - you might want to offer a PR there.

**Comment by rookie-luochao** [comment]
> @rookie-luochao I forgot that we also have the [OAI/Tooling](https://github.com/OAI/Tooling) repo for tracking tools - you might want to offer a PR there.
thanks for you, this repo seems to automatically capture data, right?
