### ISSUE TITLE
Anchor links broken in 3.0.x Markdown specification documents

### ISSUE THREAD

**Issue by jlevers** [OAI/OpenAPI-Specification#3494]
The anchor links in the Markdown specs for versions 3.0.0, 3.0.1, and 3.0.2 are broken. The links point to `camelCase` anchors, but the anchors themselves are `kebab-case`. For instance, in the [3.0.2 spec](https://github.com/OAI/OpenAPI-Specification/blob/3.0.2/versions/3.0.2.md), the **Media Types** index link points at the `#mediaTypes` anchor, but the actual **Media Types** heading has the anchor `#media-types`. This issue is present throughout the documents.

There are also some minor naming inconsistencies. I haven't done a thorough check, but I noticed that the **OpenAPI Document** index link points to the `#oasDocument` anchor, when the actual anchor is `#openapi-document` (so even if `#oasDocument` were changed to `#oas-document`, the anchor link still wouldn't work).

Not sure if the spec files are autogenerated or written manually. Happy to submit a PR if someone can point me in the right direction.

**Comment by handrews** [comment]
This is being addressed.   There are some rather thorny logistical challenges involved in terms of change management process and deployment, which is why it's taking so long, but it's being addressed in the PR I linked.

**Comment by jlevers** [comment]
Got it – thanks! Appreciate the quick response and sorry for the dupe.

**Comment by handrews** [comment]
Consolidating all broken link issues into issue #3054 and PR #3408
