### ISSUE TITLE
Issue automation failures

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3534]
@baywet I'm being inundated with failed automation run emails:

```node
Run scripts/label-no-recent.ps1
InvalidArgument: /home/runner/work/OpenAPI-Specification/OpenAPI-Specification/scripts/label-no-recent.ps1:6
Line |
   6 |          $lastCommentDate = [datetime]$null
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot convert null to type "System.DateTime".

Error: Process completed with exit code 1.
```

Please help?

**Comment by lornajane** [comment]
Did you fork the repo? I turned off actions on my fork after having a similar experience

**Comment by handrews** [comment]
@lornajane I have actions disabled, I think?  Is there more to it than this?

<img width="653" alt="Screen Shot 2024-01-30 at 2 36 53 PM" src="https://github.com/OAI/OpenAPI-Specification/assets/2358015/3c564682-0003-4b17-ba20-550179934ae2">

**Comment by baywet** [comment]
Hey @handrews  @lornajane 
Sorry about that.
First off, your main branch in your fork is probably behind main here. 
We already added a condition for the script not to execute outside of this very repository.
https://github.com/OAI/OpenAPI-Specification/blob/e4ddb5eb7cd7cb9c67d3d652503ac23f3220f387/.github/workflows/inactive-issues.yml#L28

Then, I authored #3537 to address the underlying issue. What used to be a warning apparently now fails. I'm not sure if PowerShell configurations changed somewhere or what, but better safe than sorry.
