### ISSUE TITLE
vallidate-markdown failure: How should we maintain scripts across branches?

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3542]
The validate-markdown check is currently failing on all branches but main because main now has a _very_ different JavaScript configuration from the branches.  Those branches should have GitHub actions that match their environments, but currently on v3.1.1-dev and v3.2.0-dev, the JavaScript package that validate-markdown runs fails even if you just ask it for help output:

```console
(.venv) handrews@ixat OpenAPI-Specification % npx mdv versions/3.*.md
Unexpected token '.'
(.venv) handrews@ixat OpenAPI-Specification % npx mdv --help         
Unexpected token '.'
(.venv) handrews@ixat OpenAPI-Specification %
```

**Comment by lornajane** [comment]
That's a fun problem. I have a horrible feeling that it really means we should split the repo into tools and specs ... But for now I'm happy to commit to cherry pick the tools changes into the active branches of that's useful? (Make me an issue if we choose this outcome)

**Comment by handrews** [comment]
@baywet I was looking at cherry-picking changes to `package.json`, `scripts/...`, and `.github/...` and realized your issue labeling automation is there.  Are there things we should _avoid_ putting on the branches?  It seems that we need the PR automation to run on each branch independently, but I don't want to somehow trigger extra issue runs.

**Comment by baywet** [comment]
You can safely include the changes I've made in the labelling automations. It only runs from main.
You can also safely ignore those changes, probably the safest choice if we ever have to merge those branches back to main for whatever reason.

**Comment by miqui** [comment]
@handrews  - noted the version of node is quite old. I also opened an issue against the mdv repo asking how to display line numbers where a syntax issue occurs.

**Comment by handrews** [comment]
If someone wants to update things that can be a separate issue/PR.  I'm just trying to clear out all of the things that are broken, and all of the things that are blocked from merging because of broken things.
