### ISSUE TITLE
Figure out if we need to update peter-evans/create-pull-request from 5 to 6

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3553]
Dependabot filed PR #3539 for this, but there are [breaking changes](https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md) that may or may not be relevant to us.  I'm going to close the PR so it's not sitting there adding clutter as there doesn't seem to be any urgent need for this.  We can update it if/when someone figures out what should happen.

**Comment by lornajane** [comment]
Version updated in #3671 so I'll close this one.
