### ISSUE TITLE
Extra closing bracket in getting started webhook documentation

### ISSUE THREAD

**Issue by mohammadalikassem** [OAI/OpenAPI-Specification#3577]
![image](https://github.com/OAI/OpenAPI-Specification/assets/91822043/35fe6a74-8035-4b05-afc8-1e0b424ada2d)

**Comment by mohammadalikassem** [comment]
Fixed but not merged in main branch.

**Comment by handrews** [comment]
@mohammadalikassem to explain a bit more, we don't change the published documents except if links break because the link target moved.  That's why you see it fixed in 3.1.1 but not the published 3.1.0.
