### ISSUE TITLE
version/3.0: Add a 'time' format

### ISSUE THREAD

**Issue by wking** [OAI/OpenAPI-Specification#358]
Spun off from #355 to [avoid PRs which don't attract comments ;)](https://github.com/swagger-api/swagger-spec/pull/356#issuecomment-99928987).

Having human-readable times that are not associated with dates is
frequently useful.  For example, this lets you say things like:
- "tea is at 3:15pm" (localtime)
- "the weekly meeting is at 12:00 UTC"

Using the ISO 8061 [time](http://en.wikipedia.org/wiki/ISO_8601#Times) [formats](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) should make it easy for both
people and software to interact with the values.

Since Swagger-specified APIs are often consumed and produced from
JavaScript, and since JavaScript has limited time-handling
capabilities, I thought I'd dig a bit deeper in that direction.
Support for date-less ISO 8601 times in native JavaScript is [unclear](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Parameters),
but Firefox 31.5 in seems to support times with a 'T' prefix:

> new Date('12:34')
>   Invalid Date
> new Date('T12:34')
>   Date 1970-01-01T20:34:00.000Z
> new Date('T12:34Z')
>   Date 1970-01-01T12:34:00.000Z

which, in conjunction with [Date.prototype.toTimeString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toTimeString) and other
time-specific maniplations is probably sufficient for most purposes.
Chromium 41.0, on the other hand, gave 'Invalid Date' warnings for
each of those cases, so JavaScript consumers may want to pad their
times with dummy date information.  Moment.js also requires a date
part and [doesn't support stand-alone times](http://momentjs.com/docs/#supported-iso-8601-strings).

On the other hand, there are [time-only pickers in JavaScript](https://angular-ui.github.io/bootstrap/#/timepicker).

Python also has a [time-only format](https://docs.python.org/3/library/datetime.html#datetime.time) as [does](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetTime.html) [Java](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html).  Go just
has a date-time type, but it [can parse time-only strings](http://golang.org/pkg/time/#Parse).

**Comment by ralfhandl** [comment]
+1: OData also has a TimeOfDay primitive type which can now only be represented as a string

**Comment by webron** [comment]
Tackling PR: #741

**Comment by webron** [comment]
Will be tackled in #845 instead.

**Comment by webron** [comment]
Closing as all issues will be tackled there.
