### ISSUE TITLE
version/3.0: Add a 'duration' format

### ISSUE THREAD

**Issue by wking** [OAI/OpenAPI-Specification#359]
Spun off from #356 to [avoid PRs which don't attract comments ;)](https://github.com/swagger-api/swagger-spec/pull/356#issuecomment-99928987).

On IRC today, Tony Tam pointed out that folks currently work around
the lack of durations by using an int64 for millisecond offsets, but
that's not very human readable.  And we care about human-readability
or we'd all be using protobufs instead of JSON, right?  ;).

The support for [ISO 8601](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#iso.8601.collected.abnf) [durations](http://en.wikipedia.org/wiki/ISO_8601#Durations) in native JavaScript is
unclear, but both Firefox 31.5 and Chromium 41.0 give:

```
> new Date('P3D')
Invalid Date
```

So the millisecond approach may be easier to use in JavaScript
applications, where date-times are stored as [millisecond offsets from
the epoch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Description), you can [instantiate Dates from those millisecond
offsets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Syntax), and [durations are in milliseconds by default](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Example:_Calculating_elapsed_time).

The Moment.js library [supports durations based on millisecond offsets](http://momentjs.com/docs/#/durations/creating/):

```
moment.duration(100);
```

explicit units:

```
moment.duration(2, 'seconds');
```

and `[{day}.]{hour}:{minute}[:{second}[.{fraction}]]` strings:

```
moment.duration('23:59');
moment.duration('23:59:59');
moment.duration('23:59:59.999');
moment.duration('7.23:59:59.999');
```

And it [renders ISO 8601 durations](http://momentjs.com/docs/#/durations/as-json/), but it
doesn't appear to parse that format.

Java parses ISO 8601 durations [with an extension to support negative
durations](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-).

Go parses durations [from its own format](http://golang.org/pkg/time/#ParseDuration).

Python has a duration type, but [does not parse ISO 8601 durations](https://docs.python.org/3/library/datetime.html#timedelta-objects).

**Comment by ralfhandl** [comment]
Would be useful for OData and its Duration primitive type

**Comment by webron** [comment]
Tackling PR: #741

**Comment by webron** [comment]
Will be tackled in #845 instead.

**Comment by webron** [comment]
Closing as all tickets will be tackled there.

**Comment by nasht00** [comment]
Reviving an old thread here, wanting to tackle a bunch of issues within the same ticket is fine, but reading through that long ticket gave me no clue at to what the conclusion was, or how to use ISO 8601 durations in my OpenAPI document...

**Comment by MikeRalphson** [comment]
Sorry, in a bit of a rush, but basically:
* `format` is an open-ended keyword, you can use any value
* `duration` was added to JSON Schema as a `format` value to indicate ISO-8601 durations in [Draft 2019-09](https://json-schema.org/draft/2019-09/release-notes.html#format-vocabulary). OAS will not define conflicting behaviour

**Comment by wking** [comment]
> duration was added to JSON Schema as a format value to indicate ISO-8601 durations in Draft 2019-09.

Wonderful :)  Even better than something OpenAPI-specific.

**Comment by nasht00** [comment]
Thanks, does OpenAPI already support JSONSchema's Draft 2019-09? If so from what version?

**Comment by MikeRalphson** [comment]
OAS 3.1 (in RC stage) supports JSON Schema draft 2019-09, 3.1 final should hopefully support JSON Schema draft 2020-XX (which is as-yet unpublished).

There is a wrinkle, in that JSON Schema 2019+ defines `format` as an annotation, not a validation keyword, so **by default** compliant tools will not enforce ISO-8601 duration patterns against a `format: duration` annotation. Like JSON Schema, the OAS leaves the choice of whether to do a best-effort validation of `format` up to tooling.

You can use `format: duration` now in OAS 2.0/3.0.x (just without tooling support).

**Comment by handrews** [comment]
@nasht00 note that the "not a validation assertion by default" is due to `format` never having been implemented consistently for validation.  The date and time formats tend to be well-supported, but others tend to be partially supported (e.g. validation of `email` being done as just checking for an `@` sign)  or use inconsistent definitions (e.g. validation of `regex` being done according to whatever regex syntax is supported by the implementation language, even if that doesn't quite align with the ECMA standard cited in the spec).

The expectation is that the new modular extension vocabulary support will result in well-defined validation keywords being created that don't staple completely unrelated concepts together.  A date and time vocabulary with well-defined validation keywords would be very easy to add, as those concepts have very clear specifications from IETF and/or ISO.
