### ISSUE TITLE
How the connection pool is work?

### ISSUE THREAD

**Issue by harshalizode** [OAI/OpenAPI-Specification#3604]
Hello Everyone,
I am using the 3.0.3 version of Open API. I am facing an issue because the maximum recursion depth has exceeded, due to the open API client not closing the connection after using it.

# I am creating the api instance as follow:
```
with openapi_client.ApiClient(configuration) as api_client:
       # Create an instance of the API class
       api_instance = sse_client.ApiApi(api_client) 
       api_response = api_instance.get_all()
       return api_response.to_dict()
```

After ending the bock, it should keep a living connection, which causes the problem of maximum recursion depth exceeding.
Can anyone assist me in understanding what I am doing incorrectly?
Thanks.

**Comment by harshalizode** [comment]
The socket connection  has the status as CLOSE_WAIT. It is not closing the connection.

**Comment by handrews** [comment]
@harshalizode You will need to raise this issue with your tooling provider.  This repository is just for the specification itself, not any software.

**Comment by harshalizode** [comment]
Ok, thank you for your response.
