### ISSUE TITLE
NPM Package missing repository tag

### ISSUE THREAD

**Issue by Jorricks** [OAI/OpenAPI-Specification#3616]
Dear community,

The swagger schema official NPM package <
https://www.npmjs.com/package/swagger-schema-official> is missing the 'repository' tag. 
Unfortunately that makes it harder to find this Github repository, also it is being highlighted in vulnerability scanners.

**Comment by handrews** [comment]
Note that while this specific question was closed, #151 and #2400 continue to track the larger issue of publishing the schemas through NPM.
