### ISSUE TITLE
Data Type Primative of boolean missing from v3.1.0 only

### ISSUE THREAD

**Issue by enigmaticaljedi** [OAI/OpenAPI-Specification#3628]
This relates to the following section: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#data-types

For some reason the "boolean" primative type no longer appears in the list despite existing in all previous versions, and various examples throughout the spec using the type

Assuming that to be backwards compatible version 3.1.0 should also support boolean and that this is just a typo

**Comment by handrews** [comment]
Thanks, @enigmaticaljedi !  That table is just for formats, which only apply to certain types.  The normative part of that section defers the type list to JSON Schema draft 2020-12, which still includes boolean (and the type "null" which is also not in that table).

(If i've misunderstood your report please comment and I will re-open this)
