### ISSUE TITLE
respec runs failing

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3629]
<div class="mt-1 mb-3 px-3" style="box-sizing: border-box; margin-top: var(--base-size-4, 4px) !important; margin-bottom: var(--base-size-16, 16px) !important; padding-right: var(--base-size-16, 16px) !important; padding-left: var(--base-size-16, 16px) !important; color: rgb(230, 237, 243); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mx-0 mx-md-1" style="box-sizing: border-box; margin-right: var(--base-size-4, 4px) !important; margin-left: var(--base-size-4, 4px) !important;"><h2 class="text-bold h4" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; font-size: var(--h4-size, 16px) !important; font-weight: var(--base-text-weight-semibold, 600) !important;">Annotations</h2><div class="color-fg-muted text-small" style="box-sizing: border-box; color: var(--fgColor-muted, var(--color-fg-muted)) !important; font-size: var(--h6-size, 12px) !important;">1 error and 2 warnings</div></div></div>
respecCannot read properties of undefined (reading 'number')
--
respecNode.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, peter-evans/create-pull-request@v5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.Show less
respecThe following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/Show less

Annotations
1 error and 2 warnings
[respec](https://github.com/OAI/OpenAPI-Specification/actions/runs/8235564001/job/22519943085#step:7:527)
Cannot read properties of undefined (reading 'number')
[respec](https://github.com/OAI/OpenAPI-Specification/actions/runs/8235564001/job/22519943085)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, peter-evans/create-pull-request@v5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
[respec](https://github.com/OAI/OpenAPI-Specification/actions/runs/8235564001/job/22519943085)
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

<img width="940" alt="Screen Shot 2024-03-11 at 9 40 35 AM" src="https://github.com/OAI/OpenAPI-Specification/assets/2358015/a580cf24-a665-4040-b7c3-2bb52a29f76c">

**Comment by lornajane** [comment]
Looks like this is a known bug with the action we're using, but newer releases fix it (see https://github.com/peter-evans/create-pull-request/releases/tag/v6.0.1).

I'll bump the version of both that package and the checkout one (the older version we're using makes these warnings) and see where that gets us.
