### ISSUE TITLE
Add "descriptions" fixed field to Swagger Object

### ISSUE THREAD

**Issue by adpextwindong** [OAI/OpenAPI-Specification#368]
According to the specification theres no way to define descriptions.

I've found myself rewriting descriptions for path responses a lot. I assume this begins to happen with other types of descriptions as well.

I propose adding a "descriptions" fixed field to the Swagger Object would increase overall maintainability and quality of life.

**Comment by mohsen1** [comment]
Do you mean a general `descriptions` hash to refer to from other places?

Something like this?

```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    get:
      responses:
        200:
          description:
            $ref: '#/descriptions/ok'
descriptions:
  ok: 'HTTP 200 OK'
```

**Comment by adpextwindong** [comment]
Yeah exactly like that actually.

**Comment by darrelmiller** [comment]
Thank you for submitting this proposal, however the community has not shown sufficient interest in implementing this feature, therefore we are closing this issue.
