### ISSUE TITLE
ReSpec HTML generation needs to use correct revision of MAINTAINERS.md

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3693]
As seen in PR #3688, `scripts/md2html` fails to use the correct revision of the MAINTAINERS.md file for the 3.0 and 3.1 specifications.  Specifically, `build.sh` [uses a specific revision for the 2.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/main/scripts/md2html/build.sh#L13), but [not for the later specs](https://github.com/OAI/OpenAPI-Specification/blob/main/scripts/md2html/build.sh#L23).  Also, the [collection of emeritus members](https://github.com/OAI/OpenAPI-Specification/blob/main/scripts/md2html/md2html.js#L124) in `md2html.js` seems to no longer work with the current file format.

**Comment by lornajane** [comment]
Would it make sense to version the maintainer files?

**Comment by ralfhandl** [comment]
The build script expects "Emeritus" to be the second unordered list:
https://github.com/OAI/OpenAPI-Specification/blob/64111cc3aa5a59ffc631a4987a87550691a35584/scripts/md2html/md2html.js#L121-L125

Now the second list is "Provisional".

Should provisional maintainers be
1. ignored, or
2. treated identical to "Active"?
