### ISSUE TITLE
Reference schema property within a response

### ISSUE THREAD

**Issue by Helder-Henderson** [OAI/OpenAPI-Specification#3700]
Hi guys.

I would like to have a base schema, with multiple output options for it.

Example: 

```
components:
  schemas:
     DataResponse: 
      type: object
      properties:
        Data:
          type: object
          oneOf:
            $ref: '#/components/schemas/ResponseA'
            $ref: '#/components/schemas/ResponseB'
```
          
However, when I set up a response for my endpoint based on this standard schema, I can't change the example schema
  ```
responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataResponse" <<<<< --------- 
```  

The swagger editor always shows the ResponseA schema as the default response example value, but I'd like it to be B
   Any ideas on how to solve this?

**Comment by handrews** [comment]
@Helder-Henderson That's a tool-specific implementation choice, so I'm afraid you'll need to raise it with the Swagger-Editor team (this repo is just for the specification itself).

I would imagine that you can use the `example` or `examples` keyword next to `oneOf` (depending on which OpenAPI version this is) to set an explicit example, but if that doesn't work or if you don't want to have to add an explicit example, you'll need to raise that with Swagger.

**Comment by handrews** [comment]
(although maybe just put `responseB` first as it shouldn't matter for anything else?)
