### ISSUE TITLE
Add appendix "Informative references" to published spec documents

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#3740]
Check existing non-RFC links whether they are normative or informative, for example links to the YAML specification, or links to the JSON Schema specifications.

Add appendix "Informative references" for selected external links that we deem non-normative and worth mentioning.

See [IESG Statement: Normative and Informative References
](https://datatracker.ietf.org/doc/statement-iesg-iesg-statement-normative-and-informative-references-20060419/)

Candidates (default: normative)
- ABNF
- CommonMark
- HTML 4.01
- IANA registries
- JSON Schema
- JSON Schema Validation
- OpenAPI learn - informative
- OpenAPI registries - normative as it is a defined extension point
- OpenID Connect Core
- OpenID Connect Discovery
- SPDX
- WhatWG URL
- XML Namespaces
- YAML

Preview: https://ralfhandl.github.io/OpenAPI-Specification/oas/latest.html#informative-references

**Comment by handrews** [comment]
For those wondering why this is in "Automation & Infrastructure", the "Normative References" appendix seems to be added by the HTML generation script- it is not present in our (allegedly normative) Markdown document.  Which strikes me as odd- are not normative references a normative part of the spec?

**Comment by ralfhandl** [comment]
Just noted this inconsistency:

![image](https://github.com/OAI/OpenAPI-Specification/assets/951576/2cc70cef-de55-495e-b216-6ab15115f9bf)

The Markdown spec source already has an "Appendix A" with the version history, which is rendered in HTML as chapter 5, and the normative references are added as second Appendix A.

**Comment by handrews** [comment]
ReSpec has syntax for informative references.  We don't consistently use its syntax for references, and we possibly should.  That might be more predictable than relying on inferences and heuristics.

**Comment by lornajane** [comment]
Discussion concludes that the OpenAPI Learn is the only informative link from the collection

**Comment by karenetheridge** [comment]
I think we might to also add the RFC describing URIs (3986?) because although `"format": "uri"` is managed by JSON Schema, we do also have URI references (via `$ref`) in OpenAPI itself. Although, this could be considered covered by "an openapi schema must be valid according to the JSON Schema specification here".

**Comment by karenetheridge** [comment]
Yes, sorry, I called it out because I didn't see it in the candidates list at the top of this issue.
