### ISSUE TITLE
Codify the meaning of "undefined" and "implementation-defined"

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3775]
We already use these terms a bit in the spec, but with PRs like these:

* #3732 
* #3772 
* #3758 

we are relying more on such descriptions to define areas of interoperability and expected compliance.  A new subsection under the _Definitions_ section seems like the best approach.

**Comment by handrews** [comment]
Thanks to @kevinswiber for suggesting this - Kevin (and anyone) please feel free to add suggestions or closely related terms that we should consider.  I'll make a PR for this soon.

**Comment by miqui** [comment]
> Thanks to @kevinswiber for suggesting this - Kevin (and anyone) please feel free to add suggestions or closely related terms that we should consider. I'll make a PR for this soon.

Agreed. Looking forward to the PR

**Comment by handrews** [comment]
All PRs merged, closing!
