### ISSUE TITLE
We should not keep a minified version of respec.js

### ISSUE THREAD

**Issue by Bellangelo** [OAI/OpenAPI-Specification#3845]
## Problem
There are 2 minified versions of `respec.js` for 3.x and for 4.x versions. These files exists in the `gh-pages`:
1. `/js/respec-oai.js`
2. `/js/respec-arrazzo.js`

These files are basically unmaintainable and should instead try to store a human-readable version of it.

## Proposed solution
There is a `respec-oai.build.js.map` which might help us decouple the minified version `respec-oai.js`. 
After we succeed in decoupling the file and keep only the source code in our repo, we need to add a build step in our deploy process so we can push the minified version again.

## Alternative Proposal

Do not use a modified fork of ReSpec, instead use the unmodified original, see #3944.

**Comment by ralfhandl** [comment]
In addition we should update to the latest version of [ReSpec](https://github.com/w3c/respec/) and have a documented process to refresh our snapshot.

Which also means we should not "fork" or otherwise modify the original ReSpec, and use the same snapshot for OpenAPI and Arazzo.

**Comment by ralfhandl** [comment]
Differences between OAI snapshots of ReSpec 21.0.1 and the original:

* Added Apache2 license
  * doesn't seem to have any visible effect in the rendered spec
* Tweaked Copyright line
  * can (now) be done per document
* Changed linter defaults
  * can be done via respecConfig
* Changed logo image and url
  * can be done via respecConfig
* Changed section heading of "abstract"
  * can (now) be done per document
  * this is the only difference between the OpenAPI and Arazzo clones of ReSpec
* Changed DateTimeFormat from Australian English to British English
  * what's the difference?
