### ISSUE TITLE
Document milestone usage in DEVELOPMENT.md

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#3847]
Splitting off from #3509, I've been using the milestones as follows:

* Issues go in the oldest open milestone to which they are relevant, _if_ it seems likely that they could get addressed.  This usually means either someone has volunteerd (and the issue is assigned to them) or there's an agreement in a TDC call or in response to the `review` label that it should be done
* PRs go in the milestone to which they are targeted

Before we publish a release, we should migrate any unfinished issues to the next milestone, or decide to take them out of active consideration (no milestone)

**Comment by lornajane** [comment]
Milestones section added to the contributing file
