### ISSUE TITLE
Inconsistent or unclear string format : byte or base64

### ISSUE THREAD

**Issue by sjbenoist** [OAI/OpenAPI-Specification#3886]
The OpenAPI 3.0.3 specification states in section 4.4 that it defines formats "byte" as base64 encoded characters and "binary" as any sequence of octets.

However, section 4.7.14.3 Considerations for File Uploads, mentions two alternative options for content transfer, either with base64 encoding or in binary.  The values used for "format" are "base64" and "binary".

Section 4.7.14.5 Special considerations for multipart conten also mentions  format:binary and format:base64 as markers implying that the default content-Type is application/octet-stream

"base64" as a possible value for format is not defined by the specification and is therefore ambiguous. Is it a synonym of the "byte" value ? Why should implementations support two different values if they are synonyms ?

**Comment by handrews** [comment]
@sjbenoist this has been fixed for 3.0.4 which will be published soon, and entries have been added in the formats registry for managing compatibility across versions (in 3.1, the `byte` and `binary` formats were replaced with `contentEncoding`):

* #3182 
* #3184 
* #3187 
* #3167 
* #3184
