### ISSUE TITLE
In v3.1.0 creating a $ref to schema component in a nested object field inside responses schema yields in a Resolver Error. The exact same code works in v3.0.3

### ISSUE THREAD

**Issue by radanjovic** [OAI/OpenAPI-Specification#3936]
I need a custom response for 200 code. The code is as follows:

```json
{
  "200": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "properties": {
            "message": {
              "type": "string"
            },
           "data": {
             "type": "object",
             "properties": {
               "total": {
                 "type": "integer"
               },
               "items": {
                 "type": "array",
                 "items": {
                   "$ref": "#/components/schemas/Product"
                 }
               }
             }
           }
          }
        }
      }
    }
  }
}
```

I have clearly omitted the fields that are not needed, and Product does exists and is valid inside components/schemas. This works in v3.0.3 but I like the formatting better in v.3.1.0 and want to use that version, but I get Resolver Error for this ref:

Resolver error at responses.200.content.application/json.schema.properties.data.properties.items.items.$ref
Could not resolve reference: URI malformed
Resolver error at responses.200.content.application/json.schema.properties.data.properties.items.items.$ref
Could not resolve reference: URI malformed

**Comment by radanjovic** [comment]
On a close inspect, this example from the official swagger site seems to not work:
Example:

```json
{
  "/pets": {
    "get": {
      "description": "Returns all pets from the system that the user has access to",
      "responses": {
        "200": {         
          "description": "A list of pets.",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/pet"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

For link click [here](https://swagger.io/specification/#paths-object).

**Comment by handrews** [comment]
@radanjovic this repository is for the OpenAPI Specification (OAS) itself, and as far as the specification is concerned this looks fine.  To debug the error you're getting from your tool, please open an issue with the tooling vendor.
