### ISSUE TITLE
Clarification about the meaning of an empty security array

### ISSUE THREAD

**Issue by MathieuVeber** [OAI/OpenAPI-Specification#3938]
Hi, while I was trying to implement the specification, I ran into some existential questions about security requirements!

It's unclear to me if an empty security array (`[]`) is equivalent to a security array with an empty object (`[{}]`)... The spec doesn't even mention if it would be valid to have an empty security array at the OpenApi Object level and what would that mean...

- [OpenAPI Object](https://spec.openapis.org/oas/v3.1.0#openapi-object)
> A declaration of which security mechanisms can be used across the API. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. Individual operations can override this definition. To make security optional, an empty security requirement ({}) can be included in the array.

- [Operation Object](https://spec.openapis.org/oas/v3.1.0#operation-object)
> A declaration of which security mechanisms can be used for this operation. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. To make security optional, an empty security requirement ({}) can be included in the array. This definition overrides any declared top-level security. To remove a top-level security declaration, an empty array can be used.

**Comment by handrews** [comment]
The empty object here is just a normal Security Requirement Object that doesn't have any entries.  And therefore does not require any security requirements to be fulfilled.  It does not have any special behavior - it is just the natural outcome of how the Security Requirement Object works that an empty object allows everything.

Since the OpenAPI Object and the Operation Object take arrays of Security Requirement Objects which are logically OR'd, an empty requirement list also allows everything.

You can stuff as many empty Security Requirement Objects into the array as you want, they still all get evaluated the same way, which means that `[]`, `[{}]`, and `[{}, {}, {}, {}, {}]` all behave the same.  It's like adding multiple `true`s to an OR.  `true OR true OR true` is still true.

**Comment by MathieuVeber** [comment]
Thanks for your explanation 💡 

We thought for a moment that an empty security array `[ ]` meant that nothing is allowed whereas an empty security requirement object `[{}]` allowed everything 😅

@rvedotrc here is your answer

**Comment by rvedotrc** [comment]
> Since the OpenAPI Object and the Operation Object take arrays of Security Requirement Objects which are logically OR'd, an empty requirement list also allows everything.

So you're saying logical-OR is defined for zero operands, and the result of that is "true", right?

I'm just checking because it seems like a fairly commonly accepted thing that _if_ one defines "AND" or "OR" for zero operands, then the result is the opposite of what you just said.

For example, in Ruby, where "all" / "any" are analagous to "AND" / "OR":

```ruby
irb(main):001:0> [].all?
=> true
irb(main):002:0> [].any?
=> false
```

or indeed in Javascript:

```js
❯ node
Welcome to Node.js v22.5.1.
Type ".help" for more information.
> [].every(Boolean)
true
> [].some(Boolean)
false
>
```

_If_ one is going to define AND/OR for zero operands, then conventionally one defines AND-of-nothing to be true, and OR-of-nothing to be false.

So, I'm just checking. Thoughts?

**Comment by handrews** [comment]
There seems to be a fair amount of debate on this in #3995, so let's not consider this resolved just yet.

**Comment by rafalkrupinski** [comment]
It's not about what's allowed, it's about what's required
'[]' - no security requirement
'[{}]' - a single 'allow anyone' security requirement

**Comment by rvedotrc** [comment]
The list `[ ... ]` is about what's allowed.

The object `{ ... }` is about what's required.

**Comment by rafalkrupinski** [comment]
Isn't English funny?

> The list [ ... ] is about what's allowed.

This way `[]` would mean nothing is allowed, which is not the case. It means that nothing is required.
One could say, it's a list of gate keepers. You can go thru either one, and if there's not gate keeper, you're free to enter.

**Comment by ralfhandl** [comment]
> `[]` would be an equivalent of `[{}]`

Current consensus: no, these are not equivalent, see https://github.com/OAI/OpenAPI-Specification/pull/3995#issuecomment-2276266713

> The correct behaviour for an empty array is unclear. We think it is widely used to mean that there's no security applied ("allow all") - but logically it means that there are no security rules that can be fulfilled to permit access.
> 
> We do need to update wording to explain that the empty security array is ambiguous in the current spec versions.

Current proposal:
* #4007

**Comment by handrews** [comment]
> Don't use this unless you have verified that all tools in your tool chain (and the tool chains of your partners, customers, ...) interpret it the same way

This is exactly why we added "implementation defined" as a description.  Which I think is where we ended up in the TDC call?  (For 3.0.4 and 3.1.1 anyway).

**Comment by mikekistler** [comment]
I spent some time this weekend thinking this through and I now believe that the current spec as written is clear and requires no changes. The key to understanding the current wording is to view it in the context of the "Open World" philosophy we have adopted for OpenAPI descriptions.

"Open World" vs "Closed World" was discussed and debated extensively way back in the day in Issue #568. The conclusion was that OpenAPI descriptions are a contract that describe "what works and how", but _do not_ preclude things not described from working. So for example, if a path is not listed in the set of paths, this does not mean it does not work. Likewise, if a parameter is not listed in the parameter list for an operation, this does not mean that the operation will not accept it / use it.

Extending this to security / security requirements (perhaps "requirement" is a bad name in this regard), this means that "if a security requirement is listed, it should work", but _not_ "if a security requirement is not listed, then it does not work". In other words, there is no way to define when a security requirement will not work in OpenAPI, just as there is no way to define a path that does not work, or an operation parameter that does not work.

At both the OpenAPI level and operation level, the description of the security field says:
> The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. 

This is consistent with the "Open World" philosophy. It says "these are things that work". It does not and _should not_ say "things not in this list do not work".

In this list, I think we can clearly answer the question that started all this unambiguously based on the current language in the spec:

An empty security array means "No security requirement is declared to work". It does not mean "none work".

The absence of a security field means the same thing:  "No security requirement is declared to work", but operations _may_ accept security requirements as OpenAPI definitions are "Open World" contracts.

**Comment by rafalkrupinski** [comment]
> I have to say that I agree with your logic here, and I'm also trying to figure out why it feels a bit odd.

@handrews Haha I have the same experience.
I think for me it's the fact you can make a story (open world concept, gate keepers) that makes anything logical.

@mikekistler Notice how you write `(perhaps "requirement" is a bad name in this regard)`... well perhaps that "requirement" name exempts it from the Open World concept?

How about "there are no keys to open these doors"? Sounds logical, doesn't it.

I agree with @ralfhandl, it should remain undefined.

**Comment by mikekistler** [comment]
@handrews You say:
> I'll also note that we're not consistent with the open world: the set of HTTP methods is, according to the HTTP spec, open, yet we have closed it.

I don't see it quite that way. OpenAPI says that you may describe only a certain set of HTTP methods. It _does not say_ that your service _must not_ accept any undescribed HTTP methods.

**Comment by handrews** [comment]
@mikekistler Fair enough.  It bothers me to have a part of our spec that is philosophically inconsistent with another spec (allowing only a fixed subset for an open set), but you are correct that it can be framed within an open world assumption.

**Comment by rvedotrc** [comment]
> I now believe that the current spec as written is clear

I'm trying to square that statement with the amount of discussion that has happened under this issue / the PRs. If the current spec is clear, how is it that we have spent so long discussing what it means?

I don't think it's clear.

**Comment by ralfhandl** [comment]
I agree with @mikekistler's reasoning and the conclusion that

> the current spec as written [...] requires no changes

Adding some _explanation_ probably would not hurt, given the length of this discussion.

**Comment by handrews** [comment]
We could add something along the lines of:

Unless explicitly stated otherwise, OpenAPI Descriptions are _not_ assumed to be complete.  Additional endpoints, authentication or authorization mechanisms, parameters, headers, methods, data formats, etc. MAY be present within the API without being described.  Use cases for this assumption include but are not limited to [Security Filtering](#security-filtering).

**Comment by handrews** [comment]
I think the current wording around using `{}` in the array to make security "optional" is sufficient to indicate that `[{}]` is unambiguously "you don't need to passy any security, and we're not telling you anything about how you would do such a thing if you wanted to."

**Comment by ralfhandl** [comment]
Clarified in 3.0.4 and 3.1.1, port to 3.2.0 in progress. Closing the issue.
