### ISSUE TITLE
Improve accessibility of OpenAPI specification documents

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#3946]
[Recommendation](https://github.com/OAI/OpenAPI-Specification/pull/3944#issuecomment-2212055692) by @stringtheory

- use [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview/) in the Chrome Developer Tools

Findings
- [x] Background and foreground colors do not have a sufficient contrast ratio.
  - Syntax highlighting of JSON and YAML: string orange, comment grey, and other colors are too bright
    - [x] Fall back to current ReSpec default colors and nudge the problematic ones a little
  - The bright green headlines are problematic
    - [x] Choose a different green, see [this and the following comment](https://github.com/OAI/OpenAPI-Specification/issues/3946#issuecomment-2264801734) for choices
- [x] Links rely on color to be distinguishable.
  - [x] RFC references - make them bold and underlined?

Additional findings (not strictly accessibility)
- [x] Inconsistent headline formatting
  - h1 and h2 are normal and green
  - **h3 is bold** and black
  - _h4 is italicized_ and black
  - h5 is small-caps and black
- [x] empty line at start of each code block

Accessible preview: https://ralfhandl.github.io/OpenAPI-Specification/oas/latest-a11y.html
![image](https://github.com/user-attachments/assets/e4a55a01-bdf5-4436-9d2c-7e39ab120259)

Currently published: https://spec.openapis.org/oas/latest.html
![image](https://github.com/user-attachments/assets/f2eab1a2-dda1-46d2-afd6-172a309a8a5b)

**Comment by ralfhandl** [comment]
Findings:
- Background and foreground colors do not have a sufficient contrast ratio.
  - [ ] The bright green headlines are problematic - switch to a darker OAI green?
  - [ ] Syntax highlighting of JSON is problematic - fixed with latest respec version, probably by rendering delimiters in black instead of red
- Links rely on color to be distinguishable.
  - RFC references - make them bold?
- Links do not have a discernible name
  -  
- Touch targets do not have sufficient size or spacing.

**Comment by stringtheory** [comment]
Just wanted to throw in some general comments. 

@ralfhandl Amazing work using lighthouse and going through. 

Agree that the bright green headlines are problematic. Your style guide is also problematic in the way it specs out colors. It is in CMYK - so the colors you are picking from don't even really match. I played with correct conversions here. https://codepen.io/stringtheory/pen/VwJYjWP
I am glad to provide a couple of alternative colors that meet the current spec and also future-proof you to the new spec. 

I went up the chain a bit with the Accessibility Spec people - since there is less of a definitive answer on the color formatting for syntax highlighting // and am awaiting to hear back. 

For distinguishable links - a very common way to handle them is with an underline. You will have bold for other things in the spec so you don't want to add confusion. 

I am swamped until late this week - but glad to go into more detail and help further then - if you don't mind waiting.

**Comment by ralfhandl** [comment]
> Your style guide is also problematic in the way it specs out colors. It is in CMYK - so the colors you are picking from don't even really match. I played with correct conversions here. https://codepen.io/stringtheory/pen/VwJYjWP

Thanks, I wondered how the Pantone colors **7737 C**, **574 C**, and **375 C** mentioned in the [OpenAPI Style Guide](https://github.com/OAI/OpenAPI-Style-Guide/blob/main/graphics/Pantone%20Color%20Swatches.pdf) are correctly translated to hex colors.

Trying four different "Pantone to hex" converters on the web I ended up with three different sets of hex colors 😁. The two that agreed are slightly different from your conversion:

Pantone | Hex
-- | --
7737 C | ![#6BA539](https://placehold.co/15/6BA539/6BA539.png) 6BA539
574 C | ![#4E5B31](https://placehold.co/15/4E5B31/4E5B31.png) 4E5B31
375 C | ![#97D700](https://placehold.co/15/97D700/97D700.png) 97D700

So which ones are correct? I don't want to create a user for accessing https://www.pantone.com/color-finder ☹️

**Comment by ralfhandl** [comment]
Tried both colors:
* Hex: #677C46 https://ralfhandl.github.io/OpenAPI-Specification/oas/latest-a11y-left.html
* Hex: #578000 https://ralfhandl.github.io/OpenAPI-Specification/oas/latest-a11y-right.html

**Comment by ralfhandl** [comment]
* Hex: #677C46 https://ralfhandl.github.io/OpenAPI-Specification/oas/latest-a11y-left.html

![image](https://github.com/user-attachments/assets/024c26f1-94ff-4a7f-817f-4c74685d5025)

**Comment by ralfhandl** [comment]
* Hex: #578000 https://ralfhandl.github.io/OpenAPI-Specification/oas/latest-a11y-right.html

![image](https://github.com/user-attachments/assets/97a95d22-ccd8-4cbb-bf8c-e756a60df42f)

**Comment by ralfhandl** [comment]
Current: https://ralfhandl.github.io/OpenAPI-Specification/oas/latest.html

![image](https://github.com/user-attachments/assets/f812c7d9-9c61-4a56-a228-234b28f90394)

**Comment by lornajane** [comment]
The right hand option is chosen.
