### ISSUE TITLE
Register field name prefixes reserved by OAS 3.1.0?

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#3979]
[OAS 3.1.0 Section 4.9 Specification Extensions](https://spec.openapis.org/oas/v3.1.0.html#specification-extensions) states that
> Field names beginning `x-oai-` and `x-oas-` are reserved for uses defined by the [OpenAPI Initiative](https://www.openapis.org/).

Should we add these to the [Namespace Registry](https://spec.openapis.org/registry/namespace/index.html)?

**Comment by miqui** [comment]
@ralfhandl I don't see a problem with this. At least it raises visibility on the OAI/OAS side.
