### ISSUE TITLE
Multiple types support for parameters

### ISSUE THREAD

**Issue by buremba** [OAI/OpenAPI-Specification#401]
I have a parameter that can be more than one type. (Consider an endpoint that takes an arbitrary key (string) and value (string, number or boolean) parameters and store them in a database.) It seems "parameter" object requires "type" field name and the value of "type" field must be one of "string", "number", "integer", "boolean", "array" or "file". Currently, I'm stuck with this problem since there's no workaround.

**Comment by jasonh-n-austin** [comment]
Link to parent #565

**Comment by jharmn** [comment]
Now that we're working to include full JSON Schema support #741, and we have schema support for parameters #654, wouldn't we be able to handle this in the schema definition? 
e.g. if string or integer were allowed for a parameter:

`swagger.json`
``` json
...
  "parameters": [
    {
      "name": "myParameter",
      "in": "query",
      "schema": {
        "$ref": "parameterSchema.json"
      }
    }
   ]
```

`parameterSchema.json`
``` json
{
  "oneOf":
  [
    {
      "type": "string"
    },
    {
      "type": "integer"
    }
  ]
}
```

**Comment by webron** [comment]
This can now be done with `oneOf`.

**Comment by akindo** [comment]
It's described in the [Inheritance and Polymorphism](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) section of the OpenAPI documentation.
