### ISSUE TITLE
Change collectionFormat default from csv to multi

### ISSUE THREAD

**Issue by whitlockjc** [OAI/OpenAPI-Specification#405]
The current default for `collectionFormat` is `csv` but my opinion is that it should be `multi`.  My reasoning behind this is that `multi` seems to be the default handling by most web frameworks I've ever used.  In fact, my quick research on the matter shows the following support `multi` out of the box _(I tried to look into best of breed and core language support only)_:
- [Django](https://www.djangoproject.com/) _(Python)_
- [Express](http://expressjs.com/) _(Node.js)_
- [Flask](http://flask.pocoo.org/) _(Python)_
- [Java Servlets](http://www.oracle.com/technetwork/java/index-jsp-135475.html) _(Java)_
- [JAX-RS](https://jax-rs-spec.java.net/) _(Java)_
- [Node.js HTTP](https://nodejs.org/) _(Node.js)_
- [Rails](http://rubyonrails.org/) _(Ruby, they do seem to require you append `[]` behind the parameter name but in the end, it's still the same.)_ 

As a tooling developer, having to go out of my way to support a default that is not the same default as the server environment I'm working within does not make sense to me.  Seeing that most _(all environments I looked at and use)_ support what Swagger calls `multi` by default seems to suggest that maybe Swagger too should consider using `multi` for its `collectionFormat` default.

**Comment by who** [comment]
+1 to change from csv to multi

There is a corresponding swagger-core issue (currently marked as a P1 bug) here: https://github.com/swagger-api/swagger-core/issues/1160 

A PR has been opened to fix the issue, but doesn't look like it has any traction: https://github.com/swagger-api/swagger-core/pull/1216

**Comment by whitlockjc** [comment]
I don't see the swagger-core stuff being accepted until the swagger-spec changes but I don't run either project so I can't say for sure.

**Comment by webron** [comment]
I tend to agree with the suggestion, because as you say, it's the default in many frameworks. The only catch I can think of is that we need to decide the default value per parameter type. `multi`, for example, is not applicable for path or header parameters. So to make the suggestion complete, we should come up with the default per type.

**Comment by whitlockjc** [comment]
That makes sense to me.

**Comment by cbornet** [comment]
Since the PR has been merged in swagger-core, maybe it is time to update the doc ?

**Comment by webron** [comment]
Entirely different. The PR for swagger-core describes the default behavior of arrays in jax-rs libraries and does not affect the behavior of the spec. The spec cannot be changed in that manner. We'll definitely look into it in the next version of the spec.

**Comment by cbornet** [comment]
@webron the PR #1216 has set the default behaviour to multi for form and query params for all the libraries, not only for jax-rs. See getDefaultCollectionFormat() in FormParameter.java and QueryParameter.java in swagger-models.

**Comment by webron** [comment]
That's still Java, and still an implementation. The spec as it is now cannot change. There's really not contradiction between the two.

**Comment by fehguy** [comment]
See #804
