### ISSUE TITLE
I hate this. I don't even know what's going on

### ISSUE THREAD

**Issue by agamemnus** [OAI/OpenAPI-Specification#4102]
```
          {
            "name": "mainText",
            "in": "query",
            "description": "The main text of the label. Sets are acceptable, with each item's text separated by one pipe (|).",
            "required": true,
            "schema": {"type": "array", "items": {"type": "string"}},
            "style": "pipeDelimited",
          }
```

I'm following the specification. The bot insists on using a literal array or possibly JSON array (not 100% sure). I even put this in the instructions: "The query arrays are pipe-delimited.".

It will not follow the schema until I ask it to look at the instructions. Beyond frustrating. Did I do this wrong or is it something else?

**Comment by agamemnus** [comment]
I suppose that the schema should simply say 'schema": {"type": "string"}' for pipes? I mean, it's a string, but it's an array, too. But is that in the specification? I don't think so.

**Comment by handrews** [comment]
@agamemnus I'm afraid this repository is for working on the specification itself, so we don't have the resources to help with tooling issues.  You'll need to contact the maintainer of the tool you are using.

From a spec perspective, the only thing I can see here that might be confusing is where the pipe for `pipeDelimited` comes from.  If you want to end up with something like `?mainText=these|are|pipe|delimited`, then the input would be `["these", "are", "pipe", "delimited"]`.  That JSON would be validated by the schema, and then the array items concatenated with the pipe separator.  If you want the _input_ to be `"these|are|pipe|delimited"`, then you just need a schema of `{"type": "string"}`.

Do be aware that some HTTP clients expect the `|` character to be percent-encoded, although others allow it.  This sort of thing is clarified in the 3.0.4 and 3.1.1 patch releases that will be published within the next two weeks or so.

**Comment by agamemnus** [comment]
To be more clear, I'm creating a schema on the openAI site for a custom GPT that is accessing my server. In this case, nothing do with input but with output.

**Comment by handrews** [comment]
@agamemnus Got it.  Yeah, you're going to have to talk to them (OpenAI / GPT) about that.  OpenAPI and OpenAI are not at all related (we've been around and using the "OAI" abbreviation for much longer!)
