### ISSUE TITLE
Multidimensional arrays as parameters.

### ISSUE THREAD

**Issue by IvanGoncharov** [OAI/OpenAPI-Specification#412]
Currently Swagger 2.0 support specs like that:

``` json
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Simple API"
    },
    "paths": {
        "/{foo}": {
            "parameters": [
                {
                    "name": "foo",
                    "in": "path",
                    "type": "array",
                    "items": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    }
                }
            ],
            "get": {
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}
```

By default `collectionFormat` is `csv` and this create problems with interpreting strings like 'a,b,c,d'.
Should it be interpreted like:

``` json
[
  ["a","b","c","d"]
]
```

Or maybe like this:

``` json
[
  ["a", "b"],
  ["c", "d"]
]
```

It should be forbidden to create nested arrays with same `collectionFormat`.
This change will prevent undefined behaviour situation and could be done in `2.0` as bugfix.
JSON Schema couldn't enforce such constraints, but it could be specified in spec.

**Comment by jasonh-n-austin** [comment]
Link to parent #565

**Comment by fehguy** [comment]
Done in https://github.com/OAI/OpenAPI-Specification/pull/804

**Comment by ePaul** [comment]
@fehguy I don't actually see this in the specification ... where do we forbid this (which would be the corresponding structure to what @IvanGoncharov posted):

```yaml
parameters:
  - in: path
    name: foo
    schema:
      type: array
      items:
        type: array
        items:
          type: string
    example: 'a,b,c,d'
    required: true
```

**Comment by fehguy** [comment]
we don't forbid this, we support it by allowing a schema object as the type for the parameter.

**Comment by ePaul** [comment]
The original issue said

> It should be forbidden to create nested arrays with same `collectionFormat`.

Now there isn't a `collectionFormat` anymore, but the `style` property, which only applies on top level.

So for `style: simple` (which is the default for path parameters) there is still no way of knowing whether `/a,b,c,d` would be parsed as `[["a","b"],["c","d"]]`, as `[["a","b","c","d"]]` or as any other structure.

There doesn't even seem to be a way of using different styles for both levels of array (which could solve this potentially).

So I think the issue is still open.
