### ISSUE TITLE
schema updates for 3.1.1

### ISSUE THREAD

**Issue by karenetheridge** [OAI/OpenAPI-Specification#4122]
The 3.1.1 schemas need a review pass for accuracy.

At a minimum, all the `$comment` keywords need to be updated as currently they point to v3.1.0 URIs.

**Comment by karenetheridge** [comment]
- [] update $comment URIs
- [] compare specification and schema diffs from 3.1.0 and 3.1.1, thinking about any spec changes that haven't yet been reflected in the schemas, and what changes have been made to the schemas already and confirm they are accurate
- [] ensure the .json and .yaml files are consistent

**Comment by handrews** [comment]
There are definitely improvements to be made to the 3.1 schemas, but there aren't any schema-impacting differences between 3.1.0 and 3.1.1.  The only version-ish thing that should change is the date in the `$id` of the schemas.  Even if it seems like there might be 3.1.0 vs 3.1.1 differences, anything that applies to 3.1.1 also applies to 3.1.0.  All comments or other text in the schema should _only_ mention 3.1 (no patch release number) regardless of the date in the `$id`.

Schemas can be viewed [on the spec site](https://spec.openapis.org/#non-normative-json-schemas).

**Comment by handrews** [comment]
Also, the 3.1 schemas that don't have dates in their `$id`s need to be given dates when updated.

**Comment by karenetheridge** [comment]
Note that the PR coming from this issue will be a blocker for 3.1.1. I have some of the more trivial fixes completed already, so please poke me if I should PR those now.

**Comment by handrews** [comment]
@karenetheridge same question about why it will be a blocker here as for [3.0.4](https://github.com/OAI/OpenAPI-Specification/issues/4125#issuecomment-2405866388).
