### ISSUE TITLE
Update link to json-schema specification

### ISSUE THREAD

**Issue by AxelNennker** [OAI/OpenAPI-Specification#4127]
OpenAPI specifications link to json-schema specification in e.g.
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#data-types
https://github.com/OAI/OpenAPI-Specification/blob/v3.2.0-dev/versions/3.1.0.md#data-types

The links point to an expired IETF draft https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.2.1
which has an update to -01 which is also expired.
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01 

Maybe update OpenAPI specs to link to https://github.com/json-schema-org/json-schema-spec/tree/2020-12 ?
Maybe update to a newer version of json-schema?

I saw that @handrews is a contributor to https://github.com/json-schema-org/json-schema-spec/tree/draft-07 and runs https://modern-json-schema.com/ 

I assume you have a recommendation to which link to change the link in OpenAPI spec?

I am willing to create a PR if a better link is proposed. To which OpenAPI version should that PR go?

**Comment by handrews** [comment]
@AxelNennker I think this is mostly a dup of #3934.
I have not been involved with JSON Schema since the end of 2022.

**Comment by handrews** [comment]
In 3.2 we'll update to the more recent expired draft, as it is like a patch release - no functional changes.  Any other change would have to be done in Moonwalk, but there have not been any further publications from the JSON Schema team to date and they are no longer using the IETF process (you'll have to check with them about the current state of their new process).

**Comment by AxelNennker** [comment]
Sorry, I did not find https://github.com/OAI/OpenAPI-Specification/issues/3934 
Github search was not working for me yesterday "You hit some secondary rate limit".

I think this issue is not really the same though.

I wished that json-schema.org would publish the different versions on json-schema.org or github pages so we could link to that.
I do not intent to demand anything or tell people how they run their project.
I wished json-schema.org did something like https://github.com/ietf-tools/xml2rfc/blob/main/.github/workflows/docs-publish.yml . That is, use github actions to run xml2rfc and then publish the result(s). Either on github pages, or on json-schema.org or as a github release.
Then there would be a file (txt, html, ...) for each version of the "standard" and could link to the version OpenAPI needs.
There seems to be something similar https://github.com/json-schema-org/json-schema-spec/actions in ci.yml but the artififacts are not "published".

If those "standards" are then published as IETF RFC, then all the better. But  that is extra work.

**Comment by handrews** [comment]
@AxelNennker you'll need to take those requests to JSON Schema's repo - it doesn't sound like there is anything in your list that we can do so I'm going to close this in favor of #3934, although please comment if I have misunderstood and I can re-open.
