### ISSUE TITLE
Remove/replace/migrate the CONTRIBTORS file

### ISSUE THREAD

**Issue by handrews** [OAI/OpenAPI-Specification#4148]
The CONTRIBUTORS.md file seems to be a manually maintained list of people who have opened more than 25 PRs (to a released spec? in general?  not sure).  @ralfhandl confirms it is not used by the build system.

In OAI/Overlay-Specification#80, @lornajane suggested removing it because this PR metric does not capture community contribution very well.  I would support that (and we could come back to figuring out a better metric and place to credit later on. one that works for all of our projects).

Alternatively, if we are not comfortable just immediately deleting it, let's migrate the info to a page on spec.openapis.org with some context.

Bonus:  Removing CONTRIBUTORS.md will make it far less confusing to find CONTRIBUTING.md, and will make auto-complete easier.

**Comment by lornajane** [comment]
Discussed in the TSC meeting this week, we will remove this file (@lornajane has the action)
