### ISSUE TITLE
Expand 'example' support

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#418]
Later on I'll try to add the history behind the issue, but for now, here's an explanation of what's needed:
- Allow providing examples at the parameter level. Right now it's limited to definitions which affect only body parameters. This also means that the same example would be used for all operations referencing it.
- Allow providing examples based on mime-type. This will become even more critical with the added support for versions and other mime-type based features in the future.

**Comment by Fival85** [comment]
@ApiParam(value = "The Ordernumber", example = {"1234", "5678"}) @PathParam("orderNumber")

That would be nice and easy to use :)

**Comment by jasonh-n-austin** [comment]
Link to parent #565

**Comment by webron** [comment]
Done.
