### ISSUE TITLE
host: .uber.com should be disallowed

### ISSUE THREAD

**Issue by mohsen1** [OAI/OpenAPI-Specification#429]
The host regex was not able to catch invalid `.uber.com` host name

**Comment by webron** [comment]
Not sure this is really important enough to validate with the schema.

**Comment by mohsen1** [comment]
There should be some out of the box regex for this

**Comment by webron** [comment]
Perhaps, but that doesn't mean it's worth it. I have a glorified regex to match mime types too but we decided to drop it altogether. It's not necessarily a real concern.

**Comment by lornajane** [comment]
Closing as out of scope for the specification
