### ISSUE TITLE
json array support for collectionFormat

### ISSUE THREAD

**Issue by dtorok** [OAI/OpenAPI-Specification#437]
The spec lists several possible formats in the `collectionFormat` field for an array parameter.
My suggestion is to include `json` too because
- we use json everywhere, no need to introduce a new serialization format here
- json serializer is there already on both the client and server side
- it's as simple as csv (2 more bytes)

The swagger fragment would look like this:

``` json
        - name: id__in
          in: query
          required: false
          type: array
          collectionFormat: json
          items:
            type: integer
            format: int64
```

The URL would look like this:

``` url
https://example.com/api/users/?id__in=[1,2,3]
```

**Comment by mohsen1** [comment]
Are you proposing that `items` can be any JSON Schema also?

**Comment by webron** [comment]
We actually considered adding support for it around 2.0, but a substantial set of libraries that actually support this format.

**Comment by jasonh-n-austin** [comment]
Link to parent #565

**Comment by fehguy** [comment]
This has been added by https://github.com/OAI/OpenAPI-Specification/pull/804
