### ISSUE TITLE
Use version in basepath

### ISSUE THREAD

**Issue by stratosgear** [OAI/OpenAPI-Specification#438]
Maybe a bit nit-picking but I would like to use the version number as part of my basepath:

```
info:
  version: 0.9.1
  title: My API
host: localhost:5000
basepath: /api/0.9.1
```

Apparently I could edit both `0.9.1` instances of the api version, but I would like to just edit the `version` definition once and then reuse it in the `basepath` definition (I would never have different values for these two strings (unless of course I forget to edit both places))

Is this implemented? I thought I could use some kind of `$ref` but it seems I cannot.

Thanks!

**Comment by webron** [comment]
You can't do that now, and I doubt you will be able to using this method. At best, we may allow templating in the basePath, but that's not exactly what you're looking for.

**Comment by stratosgear** [comment]
I think this issue should be addressed somehow, because I cannot think of a use-case where the ```info.version``` number would be different from the ```basepath``` version number (**if** I choose to include a version number in the basepath) and this invites the potential to have a misconfiguration if I forget to update one of the two values.

As I said before, not a show-stopper, but something in the "nice-to-have" category.

**Comment by jvpernis** [comment]
> At best, we may allow templating in the basePath

Using a versioned API is currently really tedious and prone to breaking, so this is definitely something I could see myself using in our APIs:
```yaml
info:      
  version: 0.9.1
  title: My API
host: localhost:5000
basepath: /api/{info.version}/
```

Or, for OAS 3:
```yaml
info:
  version: 0.9.1
  title: My API
servers:
  - url: localhost:5000/api/{info.version}/
```

**Comment by nogates** [comment]
The [server object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#server-object-example) supports variables, which you can use to insert the version inside the `base path`.

**Comment by handrews** [comment]
The last comment seems to have provided the answer for OAS 3, so I'm closing this as resolved.
