### ISSUE TITLE
subtypes & discriminator would benefit from more info

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#44]
Swagger 1.2 lets you specify a discriminator and possible subtypes, but it doesn't relate the `value` of the discriminator and the model that should be instantiated.  It would be convenient if this could be expressed in the spec.

**Comment by webron** [comment]
@fehguy - Is this still relevant?

**Comment by KrzysztofMadejski** [comment]
I'm wondering how to structure API schemas that use polymorphism and not to put all of them in swagger.json. 

Specifying external schema urls in `discriminator` property would be a way to go: Following cat example, that would be a sample object:

```json
{
  "name": "Felix",
  "petType": "http://example.org/schemas/cat.json"
}
```

That would be understandable for clients as well, even without building a tree of definitions. What do you think? Could such values be allowed?

**Comment by webron** [comment]
Closing it as it's related to 1.2. 2.0 changes things a bit, and we'll tackle the topic in the related modeling issue.

**Comment by KrzysztofMadejski** [comment]
Could you provide the link to the related modelling issue?

**Comment by ePaul** [comment]
@webron 

> I don't think we need to do anything. It's implicit. Any schema that uses allOf
> and includes the parent with the discriminator is applicable.

That still doesn't tell me which of those schemas now is the one to choose, or do I miss something?

Ah, here:

> Field Name | Type | Description 
> -----|----------|------
> discriminator | `string` | Adds support for polymorphism. The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. The property name used MUST be defined at this schema and it MUST be in the `required` property list. When used, the value MUST be the name of this schema or any schema that inherits it.

So this discriminator property must match the name which is used as key in the definitions object for defining the schema (and inline schemas can't be subtypes). I guess the original request by @fehguy was to make this mapping a bit more flexible by not linking the schema keys (which otherwise can be swapped out without changing anything in the API, as long as the refs are changed too) directly to the on-the wire content.

**Comment by webron** [comment]
@ePaul if you can remember full intent of comments you've made a year and a half ago, I salute you ;)

**Comment by natke** [comment]
I realize that this issue is closed but what was the resolution here?

Do the values of the discriminator field have to exactly match the name of the subType?

Otherwise, how does the client know specifically which value of the discriminator generates which subtype?
