### ISSUE TITLE
We can't access the spec doc of greeting

### ISSUE THREAD

**Issue by cmoulliard** [OAI/OpenAPI-Specification#459]
Hi,

The wiki page ("https://github.com/swagger-api/swagger-spec/wiki/Hello-World-Sample") - see maven section explains that we can start a local jetty web container to access swagger-ui. This is the case if I open this link into my browser ("http://localhost:8000") but I don't see how I can visualize the swagger spec doc defined for the listing/greeting project

What is displayed within the ui web page

![screenshot 2015-09-10 09 10 03](https://cloud.githubusercontent.com/assets/463790/9782233/de49314a-579b-11e5-89c6-90930df7c04f.png)

Link to the resource file

![screenshot 2015-09-10 09 10 15](https://cloud.githubusercontent.com/assets/463790/9782231/daa42d2e-579b-11e5-91dc-b0e4a5fd2668.png)

Do I miss something

**Comment by cmoulliard** [comment]
The link to be used is "http://localhost:8000/api-docs". Should be great to add it to the Readme file and wiki page too

**Comment by webron** [comment]
Yeah, I'm sorry about that. I really need to update the hello world sample to 2.0. Hope to get it done sometime next week.

**Comment by handrews** [comment]
This is really old and seems to apply to the old swagger site before the openapi site was created?

If there's still anything here please re-file w.r.t. the OpenAPI site.
