### ISSUE TITLE
Consistant basePath for resource-listings

### ISSUE THREAD

**Issue by abraithwaite** [OAI/OpenAPI-Specification#46]
We've found some issues with resource listings that are static.  The spec defines that the `path` attribute *should* be relative.  However this produces a conflict when hosting the spec statically.  It's solved in your examples by listing the full url to the path.

However, I think it would be appropriate to include a `basePath` attribute that would reference what you need to prepend to the resource object `path` to get to the rest of the listings.  Having to try two URLs for the `path` attribute (fully qualified and relative) just doesn't feel clean, even if you check for http in the variable or something like that.

https://github.com/wordnik/swagger-spec/blob/master/versions/1.2.md#512-resource-object
https://github.com/wordnik/swagger-spec/blob/master/samples/helloworld/static/api-docs#L5

**Comment by webron** [comment]
@abraithwaite - have you seen the changes we made in Swagger 2.0 around this?

**Comment by abraithwaite** [comment]
Been a long time since I looked at this.  Are you referring to the separation of the `basePath` and `host` field now?  I think that makes sense.

**Comment by webron** [comment]
Yes, I do. Much if it is now optional and can be derived. I'd appreciate it if you can review it so we can see whether to close this issue or mark it as a proposal for the next version.

**Comment by webron** [comment]
Not quite relevant to the next version anymore.
