### ISSUE TITLE
Security Schema definition in the spec is not clear.

### ISSUE THREAD

**Issue by guptasu** [OAI/OpenAPI-Specification#461]
Reading [security field in Swagger object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#swagger-object), I interpret it as there is a _logical OR_ between the security requirement objects.
Then reading [security requirement object](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-requirement-object), I interpret it as, it is an object with multiple fields (which reference to schemas defined security schema definition) and there is a _logical AND_ between them. 
Is my understanding right ?

For example:

```
                "security": [
                    {
                        "petstore_auth": [
                            "write_pets",
                            "read_pets"
                        ],
                        "api_key" : []
                    },
                    {
                        "petstore_advance_auth": [
                            "write_pets",
                            "read_pets"
                        ]
                    }
                ]
```

would mean required authentication for the operation is either 
(petstore_advance_auth) OR (petstore_auth AND api_key)

**Is my understanding correct, if so an example for that in the spec would be really helpful.**

If I am not right, then what is the recommended way to specify if an operation needs 2 auth and both are required, else its treated as unauthorized.

**Comment by webron** [comment]
Your understanding is correct.

**Comment by handrews** [comment]
Answered more than 6 years ago with no further comment.  Closing.
