### ISSUE TITLE
Relative refs in externally $ref documents should throw an error from example but doesn't

### ISSUE THREAD

**Issue by joewhite101** [OAI/OpenAPI-Specification#467]
This example is broken because the imported reference only exists in the parent document:
In this example:
https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions.json

The $ref imports a remote json document at:
"$ref": "https://raw.githubusercontent.com/swagger-api/swagger-spec/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions_part1.json"

But that is an invalid external reference:
"$ref": "#/definitions/ErrorModel"

**Comment by RobDolinMS** [comment]
@webron Would you mind taking a look at this?  

Given the date (Sept 2015) this might no longer apply.

**Comment by webron** [comment]
It probably is, but it's related to 2.0 and I'm not going to focus on that for now.

**Comment by whitlockjc** [comment]
@joewhite101 is right.  Any local reference is to be resolved against the document containing it.  In this case, https://raw.githubusercontent.com/swagger-api/swagger-spec/master/fixtures/v2.0/json/resources/resourceWithLinkedDefinitions_part1.json has a local reference pointing to `#/definitions/ErrorModel` which is not in the containing document.

**Comment by handrews** [comment]
@webron since there won't be any updates to the 2.0 spec can this be closed?

**Comment by MikeRalphson** [comment]
Closing as we removed the `fixtures` directory some time ago.
