### ISSUE TITLE
Swagger 2.0: Document paths uniqueness requirement. 

### ISSUE THREAD

**Issue by IvanGoncharov** [OAI/OpenAPI-Specification#483]
@webron  According to [this comment](https://github.com/apigee-127/sway/issues/32#issuecomment-146330855) Swagger 2.0 doesn't support paths which defendant only in path parameters. It can't be enforce by JSON Schema but it definitely should be documented in specification.

**Comment by MikeRalphson** [comment]
The OpenAPI 3.0.x specification includes the wording 

> Templated paths with the same hierarchy but different templated names MUST NOT exist as they are identical. In case of ambiguous matching, it's up to the tooling to decide which one to use.

Does this address your issue? The 2.0 specification is now fixed and will not change.

**Comment by pbarker** [comment]
@MikeRalphson do you understand what the purpose of this is? Shouldn't the unique identifier be verb+path?
