### ISSUE TITLE
Proposal: make pathItem oneOf object, array

### ISSUE THREAD

**Issue by claylo** [OAI/OpenAPI-Specification#487]
The Swagger 2.0 schema defines [pathItem](https://github.com/swagger-api/swagger-spec/blob/master/schemas/v2.0/schema.json#L290) as an object. 

If either an object or an array were supported via `oneOf` or `anyOf`, all of the assorted requests about how to handle query string params or overloading of endpoint behavior could be dealt with in one shot.

This could be added to 2.0 without breaking backwards compatibility, and seems as though it would require only minor tooling changes. (I say this having gone through [swagger-codegen](https://github.com/swagger-api/swagger-codegen) pretty thoroughly.)

**Comment by ePaul** [comment]
OpenAPI 2.0 will not be changed, but this could be one possible solution of #146 and related issues for 3.0.

Parent Issue: #574 .

**Comment by webron** [comment]
FWIW, as voiced in other tickets, I'm pretty much against the usage of `oneOf`, `anyOf`, `allOf` or any JSON Schema construct usage outside the scope of the Schema Object to express such things. There are simpler ways to do it without making the structure of the spec a pain to write. Granted, it may not be cover *all* use cases, but it's a trade off.

**Comment by fehguy** [comment]
As opposed to what @webron is against, we've merged the above constructs for 3.0.  Closing this.

**Comment by gmcelhanon** [comment]
@fehguy Where can I see this change manifested?  I've look through the 3.0 spec on the _OpenAPI.next_ branch, but don't see anything obvious related to this.  In https://github.com/OAI/OpenAPI-Specification/issues/487, it is proposed that the [pathItem](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#path-item-object) definition be changed to use `oneOf`, `allOf`, etc., but I still see the individual operations defined as single [Operation Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#operationObject) instances.

What am I missing?
