### ISSUE TITLE
Host specification does not seem to support ipv6 host format

### ISSUE THREAD

**Issue by testn** [OAI/OpenAPI-Specification#489]
Take a look at https://www.ietf.org/rfc/rfc2732.txt for more detail.

**Comment by hornc** [comment]
FWIW, when I made changes for #420 I was only looking at IPv4 host definitions too. The underlying RFCs that json schema references I think are pre ipv6?, and the Swagger docs made no mention of ipv6 either, so this feels new, but :+1: for adding support. The docs should be updated too.

**Comment by fehguy** [comment]
Tagging this under #560

**Comment by fehguy** [comment]
see https://github.com/OAI/OpenAPI-Specification/pull/646.  We will support ipv6 via documentation updates.
