### ISSUE TITLE
Add support for query param array format

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#49]
There is no standard for handling arrays as query parameters.  We should be able to add a format structure to let the API server specify what it expects, and have swagger-js + codegen produce the correct structure.

**Comment by packpaul** [comment]
Hi! I've also had recently a problem representing this:
productID1=1&productID2=2&...
I'm rewriting a hand-written API spec. as swagger.yaml

**Comment by ePaul** [comment]
@packpaul that URI syntax can't be represented in OpenAPI (neither in version 2.0 nor what is currently proprosed in 3.0, as far as I understand).

**Comment by packpaul** [comment]
I didn't know it. So here's a proposal to implement it in the following version.

**Comment by ePaul** [comment]
Please open a new issue (with a more detailed proposal how you imagine it to be represented). Commenting on closed issues doesn't help.

**Comment by Download** [comment]
> the brackets will be encoded by default

Isn't this the bug?
Encoding characters that need not be encoded is just... wrong is it not?

**Comment by aleksbrgt** [comment]
> Isn't this the bug?
>Encoding characters that need not be encoded is just... wrong is it not?

Actually, the encoded brackets work (at least with PHP), so `?array[]=1&array[]=2` is the same as `?array%5B%5D=1&array%5B%5D=2`
