### ISSUE TITLE
Batter documentation for running Swegger-ui locally 

### ISSUE THREAD

**Issue by npadhya** [OAI/OpenAPI-Specification#493]
The Documentation says, Just pull the repo and put you Sweggr.json file in "Dist" and stop here.

It would be helpful, if it says
1> Which folder in Dist, the user should put their JSON file. (As there are multiple folders)
2> Do we need to put a specific filename. (e.g. Putting "MyAwesomeSweggerJsonFile.json" will not work )
3> What if we get "Cross origin request error"

**Comment by webron** [comment]
What documentation are you referring to?

**Comment by fehguy** [comment]
Closing as this is specific to swagger-ui.
