### ISSUE TITLE
Swagger $ref does not display referenced JSON file using paths

### ISSUE THREAD

**Issue by kulkarniankita** [OAI/OpenAPI-Specification#511]
I have a swagger.json that has paths in the following structure:
 ```json
"paths": {
     "myRef": { "$ref": "http://<hostname>:<port>/api/ref.json" }
}
```

MY ref.json looks like this:
```json
{
  "/dom": {
      "get": {
      ..
      }
   },
   "/restcalls: {
      "post": {
      ...
       }
    }
}
```
Does this work ? It didnt for me. If current spec does not support this then its a good feature addition. If it does then how can I make above work?

We have many servers publishing their own docs and this would be useful to just refer doc.

**Comment by webron** [comment]
You can reference specific http verb operations, not full sets of paths. If you have different services publishing their own docs, it sounds like it's more likely that those servers expose different APIs?

**Comment by kulkarniankita** [comment]
Above ref.json is the result of the doc that server has published and for some other server on different port that ref.json can be a different name publishing it's docs. So I want to display this as a path. Hence suggesting this as a feature add on if this does not exist

**Comment by webron** [comment]
Not really sure I follow. As a stand alone document, that's not a full Swagger spec, as it doesn't contain some mandatory information. Just not sure what the full use case here - is it a single API that's spread around multiple servers, each exposing only a subset of the API, and all are supposed to be collated under one definition in a central location?

**Comment by kulkarniankita** [comment]
The main swagger docs is quite huge hence I am using $ref to refer to individual documents. We have a main server that listens to all connected servers so if a app gets published in all the connected servers, it will listen and add the swagger to its main docs. That main server right now has huge swagger docs. Hence I wanted to differentiate every sub-server swagger APIs using $ref. That document will have partial document enough to be referred as valid Swagger. But the above example does not work. 

Would doing this work?
```
"paths": {
     "$ref": "https://<hostname>:8090/api/server1.json",
    "$ref": "https://<hostname>:8091/api/server2.json",
}
```
server1.json would look like:
```json
{
  "https://server1:8090/api/dom": {
      "get": {
      ..
      }
   }
}

server2.json would look like:
{
  "https://server1:8091/api/dom": {
      "get": {
      ..
      }
   }
}
```

**Comment by webron** [comment]
I'm afraid, as you've already found out (the issue you voted on), that that's not possible (and it's better to keep the discussion on that issue). There are several problems supporting what you ask. Structure-wise, JSON References just won't allow that structure. On the logical aspects, there are several potential issues (conflicts/duplication) and we need to define the behavior well, especially the edge cases, before we can accept such a change.

**Comment by fehguy** [comment]
This has been covered in other tickets, so closing to avoid clutter.
