### ISSUE TITLE
Proposal: Allow for ranges of response codes to be defined

### ISSUE THREAD

**Issue by linead** [OAI/OpenAPI-Specification#516]
In the schema under responses the properties are defined like this:

>"^([0-9]{3})$|^(default)$": {
>         "$ref": "#/definitions/responseValue"
>},

It would be nice if we could define ranges here for example

400-499: //client error
500-599: //server error

We've also tried the less graceful 5xx an 4xx, but this throws an error in the swagger editor and we lose the nice formatting (e.g red for 500, yellow for 400).

**Comment by fehguy** [comment]
Parent issue #560

**Comment by DavidBiesack** [comment]
For closure (!) #638 will allow using `'4xx'` so ranges such as `400-499` are not necessary.
