### ISSUE TITLE
Question: does swagger spec support root nodes

### ISSUE THREAD

**Issue by mirrec** [OAI/OpenAPI-Specification#522]
Hey there,

I am writing documentation for rails application. And I am struggling with root nodes in responses.

Here is the example to describe what I mean by that.

`GET /orders/` # get all orders

``` json
{
  "orders": [
    {
      "id": 28,
      "customer_name": "Peter"
    },
    {
      "id": 29,
      "customer_name": "Tomas"
    }
  ]
}
```

I came up with the workaround and so far I was creating artificial model Orders, that reference real model Order.

``` yaml
paths:
  /orders:
    get:
      summary: Get all orders
      description: Get All orders
      responses:
        '200':
          description: An array of orders inside root node
          schema:
            type: object
            $ref: '#/definitions/Orders'

definitions:
  Orders:
    type: object
    required:
      - orders
    properties:
      orders:
        type: array
        items:
          $ref: '#/definitions/Order'

  Order:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific order
      customer_name:
        type: string
        description: The customer that the order is for
```

But I guess there has to be better way to do it. Because this is not the only endpoint (for instance `/order/:id` has root node 'order' etc.). So I will have to have a lot of artificial models. So my question is.

How am I supposed to write specs for responses that contains root node?

Thank you for any ideas.

**Comment by fehguy** [comment]
You would do this in your definition if you don't want an `Orders` object:

```yaml
paths:
  /orders/{id}:
    get:
      description: gets a single order
      parameters:
      - name: id
        in: path
        type: integer
        format: int32
      responses:
        200:
          description: the order you wanted
          schema:
            $ref: '#/definintions/Order'
  /orders:
    get:
      summary: Get all orders
      description: Get All orders
      responses:
        '200':
          description: An array of orders inside root node
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
```

**Comment by mirrec** [comment]
Thank you @fehguy for you suggestion.

But now I lost root node name `orders` (and `order` in `/orders/:id` endpoint) and it also changes response class in swagger UI.
from:
![with_root_node](https://cloud.githubusercontent.com/assets/544111/11724597/4c402444-9f75-11e5-8654-edeec68d9556.png)

to:
![without_root_node](https://cloud.githubusercontent.com/assets/544111/11724601/52b80f26-9f75-11e5-844d-e6eb70df74d7.png)

So this is not correct I guess. Any other suggestions?

**Comment by fehguy** [comment]
I misread your post.  It looks like what you described _is_ a good way to do so, if you want the `orders` key to hold the array.  Sorry for the confusion!

**Comment by Retistic** [comment]
We have the same issue. This seems like a feature that Swagger really should support. This is a fairly common pattern for modern APIs now. Creating an Orders object seems more akin to a hack than a solution.

**Comment by webron** [comment]
The problem isn't really clear, so not sure what support is missing.

**Comment by fehguy** [comment]
Really not sure what the question is, apologies.  You are going to always want to describe your `Order` object.  If it's stuffed inside another object, you have two choices:

1.  Define a holding object, if it's going to be reused across many places.  That's what is described in the first post with the `Orders` holder, which has an array of type `order` 

2.  Define the response in-line so that the `order` attribute points to the `Order` array:

```yaml
responses:
  200:
    description: the order you wanted
    schema:
      type: object
      properties:
        order:
          type: array
          items:
            $ref: '#/definintions/Order'
```

**Comment by jasonh-n-austin** [comment]
This seems to fit in with #519. The ability to define a "collection" wrapper, which can be reused for various resources avoids creating bespoke 'wrappers' for each collection in a CRUD resource pattern. 

That said, this example design is somewhat flawed from taking advantage from that type of approach...if `orders` were `items`, this would be a reusable collection format.

**Comment by fehguy** [comment]
Parent issue #586

**Comment by handrews** [comment]
Discussions relevant to this general idea are happening in the Moonwalk project, specifically:

* OAI/sig-moonwalk#30

Since I cannot imagine that we could fit this into the 3.x line (too much change would be required), I'm going to mark this as "moved to moonwalk."  Please feel free to join the conversation there!
