### ISSUE TITLE
[Operation Object] - contain Deprecated field why isn't a [Schema Object] contain such

### ISSUE THREAD

**Issue by rajeshkamal** [OAI/OpenAPI-Specification#524]
Hi,

I was able to deprecate the operations using the deprecated field name from the Operation Object.

When I tried to deprecated the model/some fields/properties of a model. The Swagger Spec's Schema Object doesn't seem to have a way to accommodate it.

Any inputs will be helpful. I bumped into this issue on the Springfox project - https://github.com/springfox/springfox/issues/1098

**Comment by webron** [comment]
I don't really see the use case of deprecating models. APIs are driven by operations, and it makes sense that you may want to declare a given operation as deprecated. When would you end up deprecating a model without deprecating what uses it?

**Comment by rajeshkamal** [comment]
I agree, but API's are not only driven by Operations, It is the Operations + Models put together. Models can potentially get shared across operations.
-- Deprecating an Operation doesn't necessarily have to mean that it's associated Model should also get deprecated. The Model could very well be used/referenced in another Operation.
-- I might not be interested in deprecating an Operation, but I would want to deprecate just some properties/fields of a Model alone.

My use-case was specifically around when the API's(Operations/Models/Models Properties) get's versioned. We should be able to deprecate just a field in a Model. That doesn't necessarily mean anything to the Operation.

**Comment by webron** [comment]
Okay, so you're not talking about deprecating the model, you're talking about deprecating the fields, and that can make sense. I want to say there's already a feature request for it, but can't find it right now. Marking this one as potential for the next version, thanks for the suggestion.

**Comment by MikeRalphson** [comment]
It would certainly be helpful to be able to mark a parameter as deprecated (i.e. deprecate at a more granular level).

**Comment by fehguy** [comment]
Parent issues #560, #579
