### ISSUE TITLE
Body parameter failure

### ISSUE THREAD

**Issue by Cbenh** [OAI/OpenAPI-Specification#526]
Hi, i'm working on a RESTful API using swagger-api and swagger-editor for routes.
I can't figure out why the JSON i am sending through body, never reach my controller.

here is my YAML

```

schemes:
  - http
  - https
consumes: [application/json, multipart/form-data, application/x-www-form-urlencoded]

produces: [application/json, multipart/form-data, application/x-www-form-urlencoded]

paths:
 /projects:
    x-swagger-router-controller: project
    post:
      description: create a new project
      operationId: postProjects
      parameters:
        - name: param1
          in: body
          description: description
          required: false
          schema:
            $ref: "#/definitions/Project" 
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Project" 
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"

definitions:
  Project:
    properties:
      name:
       type: string
    required:
      - name

```
an exemple of the post request i'm sending.

```
curl -v -X POST -H "Content-Type: application/json" -d '{"name":"test"}' http://127.0.0.1:10010/projects
```
and the response

```
{"message":"Request validation failed: Parameter (param1) failed schema validation","code":"SCHEMA_VALIDATION_FAILED","failedValidation":true,"results":{"errors":[{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","message":"Missing required property: name","path":[]}],"warnings":[]},"path":["paths","/projects","post","parameters","0"],"paramName":"param1"}
```

If i set the parameter "name" as not required, i just received an empty response like this 

```
{ param1: 
   { path: [ 'paths', '/projects', 'post', 'parameters', '0' ],
     schema: 
      { name: 'param1',
        in: 'body',
        description: 'description',
        required: false,
        schema: [Object] },
     originalValue: {},
     value: {} } }
```

I have no clue why since other format such as header, path or formdata works fine.

**Comment by fehguy** [comment]
You would want the type to be 'formData' with a serializable data type. The current specification doesn't allow complex data types as formData parameters so you would use a simple type like 'string' in this case. 

In addition the parameter name would be 'name' and you would pass data like "name=test"

**Comment by Cbenh** [comment]
Thanks for your fast answer !
i can indeed use form data but my point was to send a raw json through post request. 
If i use formdata, the request must be formated with www-form-urlencoded or multipart/form-data which doesn't fit with my frontend specificities. It could fit but it's really much more convenient with raw json.

When you said,  "The current specification does not allow complex structure",  you meant Swagger editor  or my YAML  ?
I am a bit confused. I was thinking using the body parameter allows to create a schema you can use for json parameter validation .

**Comment by fehguy** [comment]
Hi, if you want to send www-form-urlencoded body parameters, you would not use `in: body` for the definition.  You need to use `in: formData`.

If you want to send complex data, like a JSON structure, you indeed would use `in: body` but with `content-type: application/json`.  So I suggest you remove your top-level `consumes

**Comment by Cbenh** [comment]
So i deleted the top-level `consumes, and now my post looks like this :
```
/projects:
    x-swagger-router-controller: project
    post:
      description: create a new project
      operationId: postProjects
      consumes: [application/json]
      parameters:
        - name: param1
          in: body
          description: description
          required: false
          schema:
            $ref: "#/definitions/Project" 
      responses:
        "200":
          description: Success
          schema:
            type: object 
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
```

With or without consumes, i alway receive an empty object.  "req.swagger.params" as no value.
I tried several schema but even the simplest is not woking.
i can tell from the header that  'content-type': 'application/json'.
So the content type is set, the schema validate a simple string argument named "name". Everything should be ok.. but still not.

**Comment by webron** [comment]
This is more of a tool issue than the spec itself. Your spec seems valid and if a specific tool gives you an error, you should place a ticket on it. Based on the details I assume this would be [swagger-editor](https://github.com/swagger-api/swagger-editor) but if it's anything else, please open it there.
