### ISSUE TITLE
Only using @JsonIgnore during serialization, but not deserialization

### ISSUE THREAD

**Issue by AdelineJolie** [OAI/OpenAPI-Specification#533]
I have come to a point where I need to display a field for the input model but hide it for the output model.

I have tried using @JsonIgnore coupled with @JsonProperty like this:
(http://stackoverflow.com/questions/12505141/only-using-jsonignore-during-serialization-but-not-deserialization)

class User{
@JsonIgnore
private String password;

@JsonIgnore
public String getPassword() {
return password;
}

@JsonProperty
public void setPassword(String password) {
this.password = password;
}
}

But swagger still shows password for both model. Is the stackoverflow answer (2012) still valid with with the actual version of jackson and swagger? Or is there something else in my project that is causing this not to work ?

I'm using Jackson 2.6.4 and springfox-swagger2 2.2.2

**Comment by fehguy** [comment]
Can you please open this in [swagger-core](https://github.com/swagger-api/swagger-core)?  This repository is just for the specification itself, and looks like you're interested in java code.
