### ISSUE TITLE
Rebranding the spec

### ISSUE THREAD

**Issue by m-a-wilson** [OAI/OpenAPI-Specification#538]
Since the Swagger 2.0 specification has become the OpenAPI Specification (OAS), shouldn't the spec be edited to incorporate the change? It would certainly add an air of legitimacy to the standard.

**Comment by webron** [comment]
You mean like https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#openapi-specification?

**Comment by fehguy** [comment]
@m-a-wilson if you're thinking about changing here:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields

Then we explicitly decided not to, since it'll break all the tooling around the spec.  The next version, which is in the kick-off stage, will be a real upgrade of the spec and worthy of the tooling updates that are required.

**Comment by m-a-wilson** [comment]
I was mostly refering to the textual references e.g. "The Swagger representation of the API..." and "Primitive data types in the Swagger Specification..." .  I understand that it may take some time to adapt the URLs without breaking the examples. I can't see that modifying the text would break any tooling.

**Comment by webron** [comment]
Not sure if it would not add to the confusion. The term `swagger` (marking the version) will remain there. I don't want to go and modify the spec with an elaborate explanation of the change. However, it may make sense to change the reference to Swagger in most places to OpenAPI/Swagger to show the transition.

**Comment by m-a-wilson** [comment]
I'm sure that leaving Swagger everywhere but the title adds to confusion. Using OpenAPI/Swagger isn't much better nor is it any more or less effort than changing 'Swagger' to 'OpenAPI. As for an elaborate explaination of the change, how elaborate is "Edited to reflect the change from Swagger to OpenAPI"? 

Regardless, this suggestion was disposed of by edict.
