### ISSUE TITLE
how to map >> Map<String, BigDecimal> in java using "@ApiModelProperty"

### ISSUE THREAD

**Issue by mibrahim-iti** [OAI/OpenAPI-Specification#542]
Note: "[ equals to <"         and       "] equals to >"
Actually i want to map "Map of [String, BigDecimal]" property using " @ApiModelProperty" to generate it right in swagger.json file,
i did it as:
@ApiModelProperty(name  ="Data", notes = "Data", dataType = "Map[string,string]")
	public Map[String, String] getData() {
		return data;
	}
and i got this in swagger.json file
"Data": {
					"type": "object",
					"additionalProperties": {
						"type": "string"
					}
				},
but i think this mapping is wrong, am i right?
and if this is wrong, what should i do?

thanks

**Comment by webron** [comment]
Please open the issue on [swagger-core](https://github.com/swagger-api/swagger-core/).
