### ISSUE TITLE
$ref in response example

### ISSUE THREAD

**Issue by paulprogrammer** [OAI/OpenAPI-Specification#544]
I would like to use `$ref` in the response example in order to break up my specification into more readily manageable chunks.  Examples also benefit from being externalized because they can be easily revisioned, and included verbatim in reference implementations.

desired structure:

``` yaml
      responses:
        200:
          description: Success
          schema:
            $ref: 'profile-models.yaml#/ProfileSearchResponse'
          examples:
            application/json:
              $ref: 'ProfileExample.yaml#/ProfileSearchResponseExample'
```

Today, the children of examples are included directly, meaning the example itself using this example is:

``` json
{
  "$ref": "ProfileExample.yaml#/ProfileSearchResponseExample"
}
```

**Comment by paulprogrammer** [comment]
This issue arose from a discussion on swagger-ui:

https://github.com/swagger-api/swagger-ui/issues/1882

**Comment by crankydillo** [comment]
Hi,

Does this same issue exist for the example field within [the schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject)?  If so, will that be addressed as well?

Basically, we'd like the option to $ref in examples everywhere an example can be specified.

Thanks!

**Comment by jasonh-n-austin** [comment]
The revised guidelines for external file usage should help clarify this once merged: https://github.com/OAI/OpenAPI-Specification/pull/535

**Comment by fehguy** [comment]
Parent issue #560

**Comment by paulprogrammer** [comment]
We resolved this during build process by using the [json-refs](https://github.com/whitlockjc/json-refs) tool to resolve references before delivery of the final artifacts.

**Comment by webron** [comment]
You can do that now! 😱
