### ISSUE TITLE
Translate into Chinese

### ISSUE THREAD

**Issue by wizardbyron** [OAI/OpenAPI-Specification#546]
Hi, Is there any translation plan? I'd like to translate the 2.0 Specification into Chinese then commit a PR. the filename would be `2.0-zh_cn.md`.

**Comment by webron** [comment]
We don't have an official translation plan at the moment. You're welcome to do the translation - it seems like a lot of work.

I'd only ask to add a disclaimer at the top that the source of truth is still the original file. We won't have the capacity to maintain the translation ourselves.

**Comment by wizardbyron** [comment]
Thanks for replying, I'll add the disclaimer in the translation.

**Comment by wanghaisheng** [comment]
@wizardbyron  any update?
