### ISSUE TITLE
Relative URL for tokenUrl and authorizationUrl

### ISSUE THREAD

**Issue by cbornet** [OAI/OpenAPI-Specification#557]
It is not clear whether relative tokenUrl and authorizationUrl are authorized.
It would be great if we could set them as relative to host (or host+basePath ?). Or do you see an issue with that ?

**Comment by webron** [comment]
It's undefined by the spec, so there's no clear answer there. I wouldn't rely on existing implementations to support that. We should clarify it in the next version.

**Comment by fehguy** [comment]
parent issue #585

**Comment by darrelmiller** [comment]
Wording has been added to permit the use of URLs relative to the OpenAPI document.

**Comment by webron** [comment]
Closing as resolved.

**Comment by ksac1** [comment]
How and where can i See token URL?
