### ISSUE TITLE
Break up the spec into a set of documents

### ISSUE THREAD

**Issue by pmackay** [OAI/OpenAPI-Specification#558]
Such that it can be displayed on a site like https://readthedocs.org/ or built into a doc set with a generated index. 

This is a more significant change than that proposed by #464, but its a long spec and hard to digest currently.

**Comment by fehguy** [comment]
Parent issue #560

**Comment by webron** [comment]
@fehguy - I've erased the link you created to the meta issue. This is not about splitting OpenAPI definition file into multiple ones, this is about splitting the specification document itself to sub-section documents.

**Comment by fehguy** [comment]
Sure thing--can you tie it to the appropriate meta issue?

**Comment by webron** [comment]
I'll create a meta documentation issue that isn't related to what the spec supports but rather how the spec is documented and the support documents we may want to provide.

**Comment by webron** [comment]
Parent issue: #589

**Comment by webron** [comment]
We've ended up deciding to not split the spec.
