### ISSUE TITLE
Support multiple response class depending on an input parameter

### ISSUE THREAD

**Issue by perabello** [OAI/OpenAPI-Specification#56]
I have a get operation that return two different classes (and it could be more) depending on a parameter input.
I could resolve it separating to multiple operations. One for each result class.
But it forces me to add a path for the GET.
Example: /persons/{id}/info=?
It returns PersonDto or EmployeeDto for BASIC or EMPLOYEE parameter. 
The result are two classes totally different.
And I don't want to publish something like: /persons/{id}/full

**Comment by webron** [comment]
Parent: #574.

**Comment by RobDolinMS** [comment]
@perabello Is this still an issue with the latest OAI v3 draft?

**Comment by webron** [comment]
@RobDolinMS - There's no solution for this in 3.0. Given that this didn't get much traction, I'll close it now. We can revisit if we get more requests for it.

**Comment by madorb** [comment]
Stinks that this is closed. This would be so incredibly useful. 

being able to treat:
`GET /foo?view=full` returning a list of fully hydrated foos vs
`GET /foo?view=compact` returning say, a list of ids for instance would be incredibly useful to have in the spec

as distinct endpoints would be incredibly useful.
