### ISSUE TITLE
[Meta issue] Structural improvements

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#560]
As we look at the next version of the Open API specification, there are structural improvements that can definitely be made.  This is a meta issue for tracking improvements for the basic OpenAPI specification structure.

Please don't add comments to this issue--rather open new tickets, if they apply, and reference this as the parent.

**Comment by handrews** [comment]
This meta-issue has served its purpose, and any remaining items are being tracked under new labeling now, mostly the various `re-use: *` lables and/or `metadata`.  Major structural changes are now being considered in the sig-moonwalk repository.
