### ISSUE TITLE
[Meta issue] Restructure request parameters

### ISSUE THREAD

**Issue by jharmn** [OAI/OpenAPI-Specification#565]
This is a meta issue for tracking improvements for the structure of request parameters.

Please don't add comments to this issue--rather open new tickets, if they apply, and reference this as the parent.

**Comment by jasonh-n-austin** [comment]
Link to parent #560

**Comment by fehguy** [comment]
Unlinking this from #560, it's worthy of it's own meta issue.

**Comment by webron** [comment]
Oh, they're restructured.
