### ISSUE TITLE
[Meta issue] Improve error handling/documentation

### ISSUE THREAD

**Issue by jharmn** [OAI/OpenAPI-Specification#566]
This is a meta issue for tracking improvements for the structure of errors in OAS.

Please don't add comments to this issue--rather open new tickets, if they apply, and reference this as the parent.

**Comment by fehguy** [comment]
I'm removing the Meta Issue tag and linking to this issue:

https://github.com/OAI/OpenAPI-Specification/issues/563

**Comment by handrews** [comment]
We are no longer using meta-issues, the two remaining open issues can be tracked individually.
