### ISSUE TITLE
[Meta Issue] Unique path definition

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#574]
~~Until now, a unique operation has been considered to be a combination of a path and the HTTP verb.~~

Edit: Changed the title slightly - we can go into the discussion of path vs operation as well, but issue should cover all - path structures and unique operations, they seem to go hand in hand.

This meta issue is for tracking requests related to changing that view and allow more properties to be taken into account.

Please don't add comments to this issue--rather open new tickets, if they apply, and reference this as the parent.

**Comment by handrews** [comment]
All of the tracked issues are now closed, and in quite a few cases moved to Moonwalk.  So I am closing this and marking it moved to moonwalk as well.
