### ISSUE TITLE
Further formalize the use of YAML as document stucture

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#575]
In 2.0 we introduced support for YAML as a first-class document structure. We did so without investigating or understanding the implications of it. 

There are parts of the YAML spec that are not supported by JSON, or rather that the translation to JSON is not really defined and is up to interpretation. For example, a numeric key in YAML is allowed, but would be translated normally to a string key in JSON. However, it is legal in YAML to have both the numeric and its string counterpart to be defined together, and that cannot be translated to JSON.

We also need to be explicit as to which version of the YAML spec we support. There's work being done on YAML 1.2 right now.

**Comment by fehguy** [comment]
Parent issue #560

**Comment by webron** [comment]
Done!
