### ISSUE TITLE
Schema object namespaces

### ISSUE THREAD

**Issue by ikitommi** [OAI/OpenAPI-Specification#578]
With 2.0, the schema object names in `definitions` clash easily. For example, there can be several `User` definitions in a codebase, and if all api-docs are squashed into a single open-api doc, those schema names will clash if there is no namespace information of the model.

I propose a guide and a promotion how to manage namespaces with Schemas. Simplest thing would be to advise using full namespaced names with schemas, e.g. `myservice.reporting.User` & `mydomain.auth.User`. Client libs would do this automatically and tools like swagger-ui (openapi-ui?) would render those nicely. 

Currently, the ui works with full names, but long names break the layout. And the swagger.json examples & client libs seem to enforce just the short names without namespaces.

**Comment by fehguy** [comment]
We might consider this as optional but ensure that client generators and UIs support it.  Previously we were not specific about the name of models in the definitions, and saw stuff like high-level characters.

**Comment by fehguy** [comment]
Parent issues #560, #579

**Comment by ralfhandl** [comment]
+1 

OData Schema object names an fully qualified with namespaces using dot notation. This seems to work fine in Swagger UI, Swagger Editor, and the validators I tried, so I assumed that most/all tools support it.
