### ISSUE TITLE
[Meta Issue] Expanding JSON Schema/JSON References

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#579]
JSON Schema and JSON References are mostly well defined, but they are not necessarily fully fit for API documentation. We'll collect the requests to break out of some of the restrictions.

Please do not add comments directly to this issue.

**Comment by fehguy** [comment]
I'm going to tag this as #586 and remove the meta issue label (even though, JSON schema is very meta).

**Comment by handrews** [comment]
Everything here has been closed except one issue which is actually about enums and AFAICT not about referencing at all.  So I'm closing this meta-issue as resolved.
