### ISSUE TITLE
Swagger Issue with Api listing

### ISSUE THREAD

**Issue by jithinanneri** [OAI/OpenAPI-Specification#580]
If have two apis under two namespaces
Contact.GetContacts
Employee.GetEmployees

Swagger UI lists this as 
Contact.GetContacts
Contact.GetEmployees
Employee.GetContacts
Employee.GetEmployees

Kindly help

Thanks
Jithin

**Comment by ePaul** [comment]
Please note that this repository with its discussions is about the evolution of the specification, not about any specific tool. You could ask at [Swagger UI](https://github.com/swagger-api/swagger-ui/issues), but then please include an example API definition file so people can reproduce this and help you better.
