### ISSUE TITLE
Clarify when consumes/produces take effect

### ISSUE THREAD

**Issue by ePaul** [OAI/OpenAPI-Specification#581]
The 2.0 specification has the top-level `consumes` and `produces` properties, as well as for each operation.

When the operation is one whose HTTP method's definition doesn't include a payload semantic (most prominently GET, but also HEAD and DELETE, maybe OPTIONS), there is no point in saying the operation "consumes" anything (and there is no point in sending a Content-Type header when there is no body.)

On the operation level thus "consumes" should be forbidden for such operations, and the top-level "consumes" property should be declared in the description to not apply for such operations.

_This was triggered by Issue https://github.com/swagger-api/swagger-codegen/issues/2254._

**Comment by QianJin2013** [comment]
+1

**Comment by webron** [comment]
Not getting into the argument of whether it makes sense to send a payload to a GET but at the end of the day, the HTTP spec does not explicitly prohibits sending a payload with GET operations, and the fact is that some APIs do that. Saying that GET requests don't consume anything is not always true (and also DELETE, HEAD and OPTIONS).

As for the codegen, as long as there's no body parameter, the `consumes` value is meaningless, regardless of which HTTP verb is used (including POST, PUT), and that should be the guiding line.

**Comment by ePaul** [comment]
@webron The guideline "consumes only applies where there is a body parameter" (and maybe in extension also "produces only applies for responses with a schema") sounds good. My proposal is to include an explicit mention of this in the next version of the specification.

**Comment by webron** [comment]
Sure thing, that makes perfect sense, and the part about produces is accurate as well. I've changed the title to reflect the intent here. Note that this is just a clarification and not a change in behavior really - I'd expect existing tools to behave that way with the current version as well, including the codegen.

**Comment by webron** [comment]
Parent issues: #589, #560

**Comment by webron** [comment]
Well, both `consumes` and `produces` have been removed and replaced by better mechanisms for their respective representations.
