### ISSUE TITLE
Add ability to deprecate properties and parameters

### ISSUE THREAD

**Issue by emirkin** [OAI/OpenAPI-Specification#584]
It appears that there is no way to deprecate a parameter or property in swagger spec. The `deprecate: true` statement applies only at operation level

**Comment by whitlockjc** [comment]
This is a duplicate of #584.  *(I know it's hard to tell by the issue subject but there is an explicit request in that issue to allow deprecating parameters and properties.)*

**Comment by emirkin** [comment]
@whitlockjc you seem to have made a reference to current issue instead of another.

**Comment by whitlockjc** [comment]
Woops.

**Comment by whitlockjc** [comment]
Thanks for the update.  It's a duplicate of #524.  I crossed my streams.
