### ISSUE TITLE
[Meta issue] Security

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#585]
This is a meta issue of security-related tickets. Please don't add comments to it, but create new tickets for issues that don't already exist and link to this one.

**Comment by Bonscho** [comment]
SSL client certificate authentication is missing in the list and would be definitively nice. We use it a lot for auth against API enspoints.

**Comment by webron** [comment]
@Bonscho - looks like we missed the description in this issue which exists in the other meta issues (just added it). Please open a ticket instead of commenting here.

**Comment by handrews** [comment]
This meta-issue has served its purpose, and any remaining items are being tracked under new labeling now.
