### ISSUE TITLE
Starting the OAI specification

### ISSUE THREAD

**Issue by fehguy** [OAI/OpenAPI-Specification#596]
To use the Swagger 2.0 Spec as the starting point for the OAI Specification, we can start the documentation from scratch or iterate on the previous version.  I find it'll be easier to iterate and show changes rather than commit new content as-we move along.

**Comment by whitlockjc** [comment]
I also see the benefit in starting with where Swagger 2.0 was at and iterating to make change tracking easier.

**Comment by fehguy** [comment]
I fully expect that at some point we will possibly completely rewrite the docs.  But I do think this is a good intermediate step, since it makes it much easier to see what is changing.

**Comment by webron** [comment]
It's good to use as a starting point for sure, but I suspect at some point the changes will be breaking enough to require something a bit more drastic. We'll tackle as needed.

**Comment by darrelmiller** [comment]
:+1:

**Comment by fehguy** [comment]
We're well along the way, closing this.
