### ISSUE TITLE
Validation: Unreadable error message if an error occurs inside a parameter.

### ISSUE THREAD

**Issue by IvanGoncharov** [OAI/OpenAPI-Specification#598]
JSON Schema for `2.0` to validate method parameter use two `oneOf` one inside each other.
This leads to an unreadable error message if an error occurs inside a parameter.
And it's true for all tools which are use official JSON Schema for validation.
I used Swagger Editor as example of such behaviour:
![selection_026](https://cloud.githubusercontent.com/assets/8336157/13833530/64665676-ebef-11e5-8c44-2e635f2361fc.jpg)

I think it's very important issue since it can push away newcomers who just want to try OpenAPI 2.0 for the first time.

I have a solution for this problem which requires making few changes in current JSON Schema.
As a nice bonus, it reduces duplication in parameters definitions and overall size of JSON Schema.

But before submitting such changes I want to test them thoroughly.
That is why I want to finish my work on unit test.

**Comment by IvanGoncharov** [comment]
@whitlockjc As an expert on OpenAPI validation can you please provide your feedback.

**Comment by webron** [comment]
Just submit a PR with the proposed changes. JSON schema validation is unfriendly to users one way or another, but if you think it can be simplified without changing the intent, please do so. We've accepted PRs before, but rejected ones that changed the intent for the sake of readability.
