### ISSUE TITLE
Allow more extension patterns in addition to ^x-, e.g. @

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#600]
Both OData and JSON-LD use an at (`@`) character in property names to distinguish "metadata" properties from "data" properties.

OData models can be freely annotated with semantic metadata in addition to the pure structural metadata. When translating OData models into OpenAPI descriptions the semantic metadata needs to be represented in the `/definitions` block. Currently we nest these in an `x-annotations` wrapper object, here to express that the `Budget` property will always contain monetary amounts in US Dollars:

```
            "Budget": {
                "type": [
                    "number",
                    "string"
                ],
                "format": "float",
                "x-annotations": {
                    "@Org.OData.Measures.V1.ISOCurrency": "USD",
                    "@Org.OData.Measures.V1.Scale": 2
                }
            },
```

It would be nicer to have these annotations without the wrapper:

```
            "Budget": {
                "type": [
                    "number",
                    "string"
                ],
                "format": "float",
                "@Org.OData.Measures.V1.ISOCurrency": "USD",
                "@Org.OData.Measures.V1.Scale": 2
            },
```

**Comment by ePaul** [comment]
Unrelated to the proposal, I would prefer to include the currency inside the payload instead of fixing it in the API definition.

**Comment by IvanGoncharov** [comment]
@ralfhandl I don't understand why you can use `x-@` as a prefix.
Supporting one more prefix is meant many existing tools need to just for it.
And there is no guarantee that will end there, people would ask for `#` as prefix or any other symbol.
It's better to adjust OData related tools to do this substitution, instead of stressing an entire OpenAPI ecosystem.

**Comment by ralfhandl** [comment]
Using an x- wrapper as depicted above is a viable workaround, but OData annotations are an important part of a service's model/description, and in JSON data payloads OData annotations use just that @ syntax and are right next to the data they describe.

So from an OData perspective an x- prefix for each annotation would be inconsistent, and the x-annotations wrapper is bloat for the service description.

As JSON-LD shows the @ is not uncommon for marking annotations, and JSON Schema doesn't restrict the lexical space of extension keywords.

I understand the rationale of limiting the lexical space of extension keywords and thus make it easier to evolve a specification, but just `x-` is overly restrictive.

An alternative to having a potentially growing list of allowed extension keyword patterns OpenAPI could define a new keyword `extensionPattern` that would allow a service description to announce which pattern it uses.

**Comment by IvanGoncharov** [comment]
> allow a service description to announce which pattern it uses.

IMHO, it worse possible decision.
Since it mean you can't validate specs, you can misspell property name and there is no way to find such mistake. Many Swagger files are written by hand using tools like `swagger-editor` or simply in a text editor.
For my project, I scrape the web for OpenAPI specs on a mass scale and 80% of them have mistakes in them.
If specs will allow arbitrary properties it would mean I don't have any way to know if it simple spelling error or vendor extension.

**Comment by ralfhandl** [comment]
@IvanGoncharov In practice you would still look for `x-logo` because at some point in time you made a private contract with someone that `x-logo` has a meaning that you understand. I on the other hand would look for e.g. `@Core.Immutable` to watch out for properties whose values can be set upon creation and not changed afterwards.

In addition I would give a hint to validation tools that my documents use `@` extensions instead of / in addition to `x-` extensions.

I do not suggest to arbitrarily switch the prefix, or to treat extension keywords that differ only in the extension prefix as identical, on the contrary: only extension keywords that are literally identical MAY have the same meaning. Currently no one can guarantee that your use of `x-logo` and my use of `x-logo` have anything in common beyond those six characters.
