### ISSUE TITLE
Additional properties for describing restrictions on number values

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#602]
Sometimes the data provided or accepted by an API ultimately resides in a (relational) database, and most databases have a NUMBER type that allows storing numbers with decimal mantissa. The potential values of a NUMBER column are restricted by
- precision: number of significant decimal digits
- scale: the place where the decimal point resides, counted from the right

This can of course be expressed with `minimum`, `maximum`, and `multipleOf`, e.g.

``` yaml
minimum: -9999999.999
maximum: 9999999.999
multipleOf: 1e-3
```

Yet it would be nicer to just say

``` yaml
precision: 10
scale: 3
```

This could also be used for DECFLOAT values:

``` yaml
precision: 34
# scale is variable
```

is a long DECFLOAT, the short one would have `precision: 16`

**Comment by mspiegel** [comment]
Request to amend the proposal such that the following formats are valid:

```
precision: variable
scale: variable
```

This corresponds to a true arbitrary precision number. This is also a plain old JSON "number" type according to the JSON specification. It is basically equivalent to the java.lang.BigDecimal type with the caveat that BigDecimal supports at most 2,147,483,647 digits to the right of the decimal point. 

```
precision: variable
scale: 5
```

This corresponds to a FixedPoint number. The Scala Spire library has a [FixedPoint type](https://oss.sonatype.org/service/local/repositories/releases/archive/org/spire-math/spire-extras_2.11/0.11.0/spire-extras_2.11-0.11.0-javadoc.jar/!/index.html#spire.math.FixedPoint).

CC: @non he has a lot of experience working with weird number types.

**Comment by ralfhandl** [comment]
Would we want to explicitly state variable/unlimited precision or scale, or would this rather be expressed by not stating a finite precision or scale?

The latter would be in style with `miminum`, `maximum`, and `multipleOf`.

**Comment by mspiegel** [comment]
I'd like to have a special value ('variable', 'unlimited', not picky on the name) that can be used to explicitly document unlimited precision or scale. Do the fields 'precision' and 'scale' only apply when 'type' is number and 'format' is decimal? Do they also apply when 'type' is number and 'format' is unspecified? I think at one point I understood the difference between (number, decimal) and (number, not specified) but I can't recall now. What is the difference?

**Comment by ralfhandl** [comment]
Good questions! Similar to `minimum` etc. `precision` and `scale` should apply to `type:number` without requiring a specific format.

Given the issues mentioned in #704 they might also apply to `type:string` and imply that the string will contain a number.

OpenAPI Specification already defines formats `double` and `float` for floating-point numbers with binary mantissa, so the new format `decimal` would denote numbers with decimal mantissa, and the new validation keywords `precision` and `scale` would further restrict the allowed values .

**Comment by webron** [comment]
Tackling PR: #741

**Comment by ralfhandl** [comment]
We've opted for "vendor-specific" extension keywords [`x-sap-precision`](https://github.com/SAP/openapi-specification/tree/main/sap-schemas/v3.0#x-sap-precision) and [`x-sap-scale`](https://github.com/SAP/openapi-specification/tree/main/sap-schemas/v3.0#x-sap-scale).
