### ISSUE TITLE
responses in the petstore swagger spec do not specify atleat one positive response

### ISSUE THREAD

**Issue by amarzavery** [OAI/OpenAPI-Specification#605]
As per the [explanation in the Responses section] (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object)

Responses Object

A container for the expected responses of an operation. The container maps a HTTP response code to the expected response. It is not expected from the documentation to necessarily cover all possible HTTP response codes, since they may not be known in advance. **However, it is expected from the documentation to cover a successful operation response and any known errors.**

The  default  can be used a default response object for all HTTP codes that are not covered individually by the specification.

**The  Responses Object  MUST contain at least one response code, and it SHOULD be the response for a successful operation call.**

However, the petstore swagger spec does not obey this in several places.
For example:
```
"/pet": {
      "post": {
        "tags": [
          "pet"
        ],
        "summary": "Add a new pet to the store",
        "description": "",
        "operationId": "addPet",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],
        "responses": {
          "405": { <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
            "description": "Invalid input"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "pet"
        ],
        "summary": "Update an existing pet",
        "description": "",
        "operationId": "updatePet",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Pet object that needs to be added to the store",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Pet"
            }
          }
        ],
        "responses": {
          "400": { <<<<<<<<<<<<<<<<<<<<<<<<
            "description": "Invalid ID supplied"
          },
          "404": { <<<<<<<<<<<<<<<<<<<
            "description": "Pet not found"
          },
          "405": { <<<<<<<<<<<<<<<<<<<<
            "description": "Validation exception"
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    },
 ```

**Comment by webron** [comment]
@amarzavery which pet store are you referring to? the one hosted at http://petstore.swagger.io or one of the samples in this repository?

**Comment by amarzavery** [comment]
@webron - Yes I am talking about this one  http://petstore.swagger.io/v2/swagger.json hosted at http://petstore.swagger.io.

**Comment by amarzavery** [comment]
@webron , @fehguy, @whitlockjc any inputs on this issue ?

**Comment by fehguy** [comment]
@amarzavery that's an implementation of the spec, not the authority on the OpenAPI spec.  Please open a ticket on the implementation of that API, which is under https://github.com/swagger-api/swagger-samples

**Comment by amarzavery** [comment]
@fehguy - Thanks for directing me to file this issue in the right repo. I have filed one over there: https://github.com/swagger-api/swagger-samples/issues/54. Hope this gets fixed soon as many people use petstore as an example to understand the concepts of open api spec. Hence having a correct example of the spec is very important :).

**Comment by fehguy** [comment]
I understand, and thank you for posting the issue there.
