### ISSUE TITLE
support for type string, format base64url

### ISSUE THREAD

**Issue by amarzavery** [OAI/OpenAPI-Specification#606]
Open API Spec supports base64 formatted string via ["byte" format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types). However, it would be better if Open API Spec supports base64url instead of base64.

Base64Url is very similar to Base64, except that the value encoding for characters 62 and 63 is different as it is explained in https://tools.ietf.org/html/rfc4648#page-7. 

This is much safer than base64. What do you guys think about this?

Some of our customers have requested support for this. Please find the corresponding issue over [here](https://github.com/Azure/autorest/issues/805).

**Comment by ralfhandl** [comment]
+1: OData represents binary data in base64url encoding so that clients can take payload values and use them in `$filter` conditions without having to percent-encode the forwards slash.

**Comment by webron** [comment]
Tackling PR: #741

**Comment by ePaul** [comment]
I guess the advantage is only relevant for path and query parameters, not so much for things encoded in JSON. (I'm not sure about header parameters + response headers.)

(This is not an argument against this, just one consideration which might need to be mentioned.)

**Comment by fehguy** [comment]
See #878
