### ISSUE TITLE
Endpoints Not In Service

### ISSUE THREAD

**Issue by fargozhu** [OAI/OpenAPI-Specification#608]
How to mark an endpoint out of service kind of thing?

**Comment by ePaul** [comment]
Could you explain a bit more what you are trying to do?

I can see the need of noting deprecation for parts of an API (which could be a path or an operation, or even parameters), with a "planned end of service" date or similar.

**Comment by ejaigom** [comment]
I have some services are defined but not implemented that and I would like to have a flag that could inform the consumers of my API about it.

**Comment by shilka** [comment]
Maybe just return 501 http code for that endpoints?

**Comment by IvanGoncharov** [comment]
I think a better solution is to not include those endpoints in your OpenAPI spec.
Or you can provide two versions of your OpenAPI spec.

In any case I don't think these should go to core of OpenAPI spec since OpenAPI represent your API and not your workflow.

**Comment by handrews** [comment]
This discussion seems like it was resolved in 2016 - closing.
