### ISSUE TITLE
Redefine allowEmptyValue

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#611]
Currently the spec provides `allowEmptyValue` which is valid for `query` or `formData` parameters.

When sending query parameters, they can have no value (acting as a flag) or a an empty value. That is `?foo&bar` or `?foo=&bar=` respectively. Current spec doesn't allow specifying the difference

This issue is derived from #81.

Parent: #565.

**Comment by fehguy** [comment]
@webron I think this has been handled in the 3.0 draft.  Can you please confirm?

**Comment by webron** [comment]
Yes, it's indirectly explained (depends on `style`).
