### ISSUE TITLE
Support XML simple type lists

### ISSUE THREAD

**Issue by jbreich** [OAI/OpenAPI-Specification#612]
From what I understand it is not possible to use an XML document containing a simple type list like this one:

```
<xs:element name="root">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="list">
        <xs:simpleType>
          <xs:list itemType="xs:string" />
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
```

A valid xml is:
`<root><list>value1 value2</list></root>`

With Swagger it is only possible to represent an `array` using a repeated XML element with an optional XML element wrapper. It would be nice to also support this

**Comment by RobDolinMS** [comment]
@jbreich Can you add a comment on if there is an implementer or customer that is interested in this?

**Comment by handrews** [comment]
This was a 2.0 question and the question to the OP in 2017 has been unanswered.  I'm going to close this - please feel free to open a new issue if a similar problem exists in 3.1.  But I'm fairly sure this ends up being a subset of or at least closely related to #630
