### ISSUE TITLE
Swagger specification XML array example incorrect

### ISSUE THREAD

**Issue by swlinn** [OAI/OpenAPI-Specification#615]
There is an example in the specification of xml wrapped arrays showing the external xml property with wrapped having a value of false, and yet it wraps the output XML anyway.  The specific example is preceded by the text "Affecting both internal and external names:"  The YAML and JSON definitions should have wrapped as true for the XML shown.

**Comment by webron** [comment]
This has been fixed in both 2.0 and 3.0.
