### ISSUE TITLE
Enunciate generated swagger json throws "Not a valid parameter definition" exception and unable to generate client library

### ISSUE THREAD

**Issue by murugaraja** [OAI/OpenAPI-Specification#618]
Hello,

I am using Enunciate 2.2 to generate docs and swagger UI. I want to include client library in swagger UI. **Is it possible to generate client library and access it in swagger UI.**

Enunciate generates swagger.json file, I uploaded this file in editor.swagger.io but it throws "Not a valid parameter definition" exception.

Please help me on this.

Thanks in advance.
Raja.M

**Comment by webron** [comment]
Either open the question on Enunciate's support forum or Swagger's [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket). This issue is unrelated to the spec itself.
