### ISSUE TITLE
How to describe request json body in depth?

### ISSUE THREAD

**Issue by ivansky** [OAI/OpenAPI-Specification#623]
Hm?!

https://github.com/swagger-api/swagger-core/issues/1723

**Comment by webron** [comment]
@ivansky - that's not really a way to open tickets that encourage discussions. If you'd like to raise an issue and discuss possible changes, please do so in a manner that helps the community, don't just send people chasing threads on other projects.

**Comment by webron** [comment]
Closing as tackled in other tickets.
