### ISSUE TITLE
Inheritance and Substitutability

### ISSUE THREAD

**Issue by ralfhandl** [OAI/OpenAPI-Specification#627]
OAS represents inheritance with the `allOf` construct, e.g.           

```
definitions:
  Animal:
    type: object
    properties:
      commonName:
        type: string
  Cat:
    allOf:
      - $ref: '#/definitions/Animal'
      - type: object
        properties:
          isFurry:
            type: boolean
```

This reflects that a cat has all properties of an animal, but it doesn't reflect that I can substitute a cat (and only a cat if my model doesn't define more sub-types of animal) wherever an animal is declared:

```
paths:
  /Animals:
    get:
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Animal'
    post:
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Animal'
      responses:
        '201':
          description: Successful response
```

This currently has at least two problems:
- Swagger Editor will complain about unused definition `#/definitions/Cat`, see swagger-api/swagger-editor#765
- I cannot use `additionalProperties: false` on either of the two definitions

The first may be mitigated by a refined/relaxed check in Swagger Editor, the second is a source of surprise for clients as the API seems to claim allowing additional properties but in fact refusing to accept any `POST` request that provides them.

**Comment by arno-di-loreto** [comment]
Sound it's related to issue [403](https://github.com/OAI/OpenAPI-Specification/issues/403) (*Support for polymorphic types is unclear in the spec*).
You should add a `discriminator` field to Animal indicating which field use to differentiate the animals but has explained in issue 403, the value of discriminator is not clearly defined. Therefore, the support of inheritance is not fully complete in the current version of the spec. But the API consumer could at least relied on discriminator using solutions proposed by @webron (even if the editor will still complain about Cat definition not being used).

**Comment by webron** [comment]
Tackling PR: #741

**Comment by handrews** [comment]
@ralfhandl in OAS 3.1, `unevaluatedProperties` from the latest JSON Schema draft will solve your unable-to-use-`additionalProperties` problem.

If any of the rest of this is still relevant, I think the swagger issue belongs in the swagger repo, and as noted in another comment, issue #403 addresses the `discriminator` part.  I think that means all of this has been addressed that can be addressed here, so closing.
