### ISSUE TITLE
Enhancement: Multiple custom authorization headers in Swagger UI

### ISSUE THREAD

**Issue by jykae** [OAI/OpenAPI-Specification#642]
## Behaviour

<img width="534" alt="nayttokuva 2016-04-11 kello 17 35 35" src="https://cloud.githubusercontent.com/assets/293452/14430871/df6ec2d8-000b-11e6-85db-49a4e6cb6649.png">
## Suggestion
- New type "customHeader"
- Button texts "Authorize" -> "Attach/Detach"

Overall functionality works, but when there are multiple custom headers, the name "apiKey" is not clear in user perspective.

**Comment by ePaul** [comment]
Sorry, your issue is not clear. Are you suggesting a change in the specification? If so, which one?
Or are you suggesting a problem in Swagger-UI? If the latter, please post it at [swagger-api/swagger-ui](https://github.com/swagger-api/swagger-ui), not here.

**Comment by jykae** [comment]
I am suggesting a better way to define custom headers for spec. The latter is though more Swagger-UI specific, how to represent that in UI.

Maybe even own section for defining possible headers for API requests?

**Comment by jykae** [comment]
I try to remember edit the issue description tomorrow morning. I am on mobile currently. 
I leave out UI specific things, and post that to Swagger UI.

**Comment by webron** [comment]
How is that different than specifying API keys? Granted, the name of the authorization scheme should probably change, but other than that it does what you want?

**Comment by jykae** [comment]
@webron I get the functionality that I want by adding multiple "apiKey" type headers. So no actual difference there. Maybe if I could define securityDefinition type "customAuth", and include definitions of those two headers to that? How does that sound?

Though we come then to the question if it's necessary for OpenAPI specification to support custom authorization schemes, it's up to you :)
