### ISSUE TITLE
Remove references to `vendor extensions` in favor of `extensions` or `x-extensions`

### ISSUE THREAD

**Issue by earth2marsh** [OAI/OpenAPI-Specification#643]
During the working group 2.0 spec process, extensions were proposed to suit vendor usecases, and therefore were initially referred to as `vendor extensions.` 

However, there are plenty of reasons to extend the spec without being a vendor, hence the name is too narrow. This proposal recommends deprecating any reference to `vendor extensions` in favor of `extensions` or `x-extensions`.

**Comment by IvanGoncharov** [comment]
@earth2marsh Totally agree with you.
Moreover, it motivates vendors to create their own dialects like `x-ms-*`(see [this](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Enum-x-ms-enum)).
And the same true for other vendors, see #616 

Please also consider adding following **recommendations**:
 * to reuse existing extension
 * create more generic extensions, and provide a public specification for them.
 * add vendor namespace only if an extension is specific to this particular vendor.

**Comment by DavidBiesack** [comment]
agree dropping 'vendor' is good. (I suggest the term 'specification extensions' over x-extensions, but it's not hugely important.)

*Namespaces* for extension names perhaps should be addressed as a separate issue, though. Vendors or other non-vendor organizations will still likely use some x-mynamespacehere- prefix to avoid conflict. That will happen regardless of the term OAS uses (extension or vendor extension).

**Comment by fehguy** [comment]
Fixed in #492
