### ISSUE TITLE
Collection Json objects as parameters for POST request

### ISSUE THREAD

**Issue by NH7** [OAI/OpenAPI-Specification#644]
Hi,
I am facing the following issues with swagger API

1.  I have an API which is a POST request and it takes a collection of objects  as parameters:
```java
	@POST
	@Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
	@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
	@ApiOperation(value = "Create customers", notes = "Create input customers", response=CustomerTO.class, responseContainer = "List")
public Response create(@ApiParam(value="Customers", required = true) final Collection<Customer> customers)
```
Now when the Swagger doc for this is generated , I see "#/definitions/Customer" in dataType for the body Parameter instead of something which is like Collection<Customer> or List<Customer>
Due to this problem the **model and model schema for the body param is also not being generated.
**

2.  I am using @ApiResponses on a get function as : 
```java
         @ApiOperation(value = "Get customer", notes = "get customer details", response=CustomerTO.class)
        @ApiResponses(value = {
			@ApiResponse(code = 200, message = "Get customer details successfully", response=CustomerTO.class),
			@ApiResponse(code = 409, message = "Could not get customer details", response = Error.class) }
```
In this case, I am able to see only response code 409 in swagger and **200 is not visible.** However, due to some reason, if I remove response=CustomerTO.class from the @ApiResponse of 200 code, I can see 200 error code as well but without any corresponding response model. 
I want to display both 200 and 409 in the swagger doc generated with corresponding responseModel classes as well.

**Just for info, I am trying out this swagger doc generation in a web brower(chrome, also tried safari) and I face above issues. However, if I try the same url on petstore.io, the responses change and some of the issues are not faced. Why is this discrepancy? **
Can you help me render proper swagger doc on a browser only as that is my requirement.

**Comment by webron** [comment]
Issue moved to https://github.com/swagger-api/swagger-core/issues/1745.
