### ISSUE TITLE
Allow for header parameters to be objects

### ISSUE THREAD

**Issue by Sauradyuti** [OAI/OpenAPI-Specification#652]
Currently, Swagger 2.0 specifies a header parameter " is limited to simple types (that is, not an object)". Please allow header parameters to be of object type.

**Comment by ePaul** [comment]
The simple types being allowed are those that have a simple string representation (without needing quotes or similar), and arrays of such have some ways of formatting (see `collectionFormat`).

How would such an object be represented? Simply one line of JSON?

**Comment by Sauradyuti** [comment]
Preferably, the way it is specified for a body parameter, ie, to have a schema field.

**Comment by ePaul** [comment]
I just found that there currently is an [Internet draft discussed in the HTTP working group](https://tools.ietf.org/html/draft-ietf-httpbis-jfv-00). This basically defines a format to transport JSON arrays (while omitting the brackets) in HTTP headers.

I guess this could work for custom headers with OpenAPI schema definitions for them.

**Comment by fehguy** [comment]
FYI we have accepted the change to allow schemas for _all_ payloads, please see https://github.com/OAI/OpenAPI-Specification/pull/654

**Comment by wparad** [comment]
(RFC only applies to newly created headers, as in the format for the header must already be defined as one that is a json representation, interesting consequence for yaml and other non json body media types)

**Comment by ePaul** [comment]
@fehguy But as I understand, there is not yet a definition which says how to serialize a JSON object/array/... into a header. My proposal was to adopt the one from the RFC, when it is done.

@wparad yes, this only applies to new headers ... I was mainly thinking about custom headers defined by an API (which would fit "newly created headers"), or new standard headers which refer to that RFC (after it is published), and then need to be described in an API definition.

This doesn't solve describing existing headers, for them we need a different solution.

**Comment by fehguy** [comment]
@ePaul sure, but let's put that on the appropriate ticket.  This one is requesting that header parameters can be objects, which is accepted.
