### ISSUE TITLE
HTTP Method REPORT not supported

### ISSUE THREAD

**Issue by aparvis** [OAI/OpenAPI-Specification#658]
Hi
According to [http://www.iana.org/assignments/http-methods/http-methods.xhtml](http://www.iana.org/assignments/http-methods/http-methods.xhtml) REPORT is a valid HTTP method. It's not supported by OAI/Swagger specification, probably because it's less known method. Will future spec releases support it?

REPORT is similar to GET method because it's safe and idempontent. More importantly it fully supports parameters in request body. Such paramaters aren't recommended in GET requests (response caching) and parameters in URI have their limitations (e.g. request-line length).

swagger-api/swagger-core#1760

**Comment by ePaul** [comment]
I guess this is a special case of #325.

**Comment by webron** [comment]
It is, and it's covered in a way in the comments there. Let's consolidate it. Thanks @ePaul.

**Comment by AtosNicoS** [comment]
TRACE has been implemented for a while, but what about REPORT?
