### ISSUE TITLE
Swagger paths do not allow multiple consumes/produces branches

### ISSUE THREAD

**Issue by Nthalk** [OAI/OpenAPI-Specification#659]
Many rest frameworks support multiple implementations of Accept/Content-Type branches beneath shared urls.

For instance, the following two URL's may have completely different call specs:
Accept: applicaiton/vnd.api.1.0+json GET /api/versions 
Accept: applicaiton/vnd.api.2.0+json GET /api/versions

For swagger, I thought that specifying a unique API name (ApiVersionsV1_0 and ApiVersions) would allow me to do this, however, the swagger specification is based on the path, and one overwrites the other.

And the 2.0 spec doesn't recognize:
`{{paths: "/api/versions": [{DEFINITION1}, {DEFINITION2}]}`

Are there any plans on allowing the path's to accept an array of tagged operations?
What are the chances of this being allowed?

**Comment by webron** [comment]
Please follow #146 - aka, the content-negotiation thread.

**Comment by ePaul** [comment]
@Nthalk The thread mentioned by webron also has [a workaround](https://github.com/OAI/OpenAPI-Specification/issues/146#issuecomment-117288707) which works with 2.0 tooling.
