### ISSUE TITLE
Provide a Contributing.md guide for TDC and others

### ISSUE THREAD

**Issue by DavidBiesack** [OAI/OpenAPI-Specification#662]
This project would benefit some guidance on how the Technical Development Community can/should contribute. See [this comment](https://github.com/OAI/OpenAPI-Specification/pull/464#issuecomment-212046485) for example:

> Could you rebase your Pull request against current master (or maybe even better, current OpenAPI.next)? There the specs are in the versions folder.

A [Contributing.md](https://github.com/OAI/OpenAPI-Specification/blob/master/Contributing.md) guide (linked to from the README.md page) would contain information such as (these are suggestions) what branches should be used for pull requests for OAS 3.0 (**[OpenAPI.next](https://github.com/OAI/OpenAPI-Specification/tree/OpenAPI.next)**?), what constitutes a good pull request, what tags one should use for issues and what those tags mean (with links to the issues, by tag such as **[OpenAPI.Next Proposal](https://github.com/OAI/OpenAPI-Specification/issues?q=is%3Aissue+is%3Aopen+label%3A%22OpenAPI.Next+Proposal%22)**), what is the workflow/process that the OAI and committers uses for evaluating proposals and pull requests, who the principal committers are and what their roles are, etc. Some of this info (OAI etc.) may be located elsewhere but links to such material would be sufficient.

A central guide such as this on this GitHub project would really help the TDC.

**Comment by fehguy** [comment]
Hi @DavidBiesack, I tried to cover that here, on the main README.md:

![image](https://cloud.githubusercontent.com/assets/249413/14651375/8d248be2-0624-11e6-9fbb-382975af9c18.png)

Which brings you to the [OpenAPI.next branch](https://github.com/OAI/OpenAPI-Specification/tree/OpenAPI.next).  In that README, there's a [participation](https://github.com/OAI/OpenAPI-Specification/tree/OpenAPI.next#participation) section which says how to contribute.

If you think that could be improved, please let me konw how.

**Comment by ePaul** [comment]
The good thing about having a CONTRIBUTING.md file is that [Github links it from the issue (or pull request) creation form](https://github.com/blog/1184-contributing-guidelines).

**Comment by DavidBiesack** [comment]
Thanks, @fehguy - from that I also found https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/DEVELOPMENT.md which helps.
