### ISSUE TITLE
Describe parameters uniformly with location

### ISSUE THREAD

**Issue by DavidBiesack** [OAI/OpenAPI-Specification#663]
Do not use the term "parameter type\* to refer to parameter _locations_ (`#parameterIn`), just used _location_ uniformly. _Parameter type_ should only refer to the `type` field (`#parameterType`)

Use same order and values/case in the list as in the description and allowed values for `in`.

**Comment by DavidBiesack** [comment]
See PR #651

**Comment by ePaul** [comment]
This is a purely editorial change which reduces confusion. :+1:

**Comment by ePaul** [comment]
I created a new PR #923 which should solve this.

**Comment by webron** [comment]
Closed as #923 is merged.
