### ISSUE TITLE
Add support for referencing an example from within an example specification?

### ISSUE THREAD

**Issue by jterry75** [OAI/OpenAPI-Specification#666]
```js
{
    "type": "object",
    "required": [
        "Test",
        "Nested"
    ],
    "properties": {
        "Test": {
            "type": "string"
        },
        "Nested": {
            "$ref": "#/definitions/TestSubObject"
        }
    },
    "example": {
        "Test": "A value",
        "Nested": {
            "$ref": "#/definitions/TestSubObject/example"
        }
    },
    "definitions": {
        "TestSubObject": {
            "type": "object",
            "properties": {
                "Test2": {
                    "type": "string"
                }
            },
            "example": {
                "Test2": "A nested value."
            }
        }
    }
}
```

Consider the above object schema. Would it be possible to support such a way to consume examples? This avoids having to rewrite complex example documents where the "reference object" already has an example in its declaration and could simply just inline that example by reference a lot like what happens already when using $ref in the property declarations.

-Justin

**Comment by ePaul** [comment]
But what happens if your example actually already contains a `$ref` field (or a JSON reference object)? Whoever is parsing this, doesn't know if this is a use of this reference feature of OpenAPI, or if it is a reference inside the example.

**Comment by jterry75** [comment]
Ah interesting. I didn't realize that the "example" key word wasn't treated differently and that ```$ref``` was allowed at all. I can see how this would conflict if we took this proposal.

**Comment by webron** [comment]
Not sure how this is going to work. The `example` field has a type of `Any` and is not really JSON specific. In case of an XML it'd just be a string representing that, it just so happens that it's easy to represent JSON as... JSON. The values should be treated as-is with no additional processing to them, I don't think it's reasonable to expect the tools to support that.

**Comment by jterry75** [comment]
No worries. Thanks for thinking through it. Just found myself duplicating a lot of examples with smaller resource sets and thought it would be neat. But as you pointed out has issues. Feel free to close.

**Comment by jasonh-n-austin** [comment]
Closing as requested (and due to lack of technical feasibility with `Any` typed examples).
