### ISSUE TITLE
JSON Object serialization with root object name or without?

### ISSUE THREAD

**Issue by vnalla** [OAI/OpenAPI-Specification#671]
What is recommended by the Swagger/OpenAPI Specification for serialization of JSON request/response objects? With root object name? or without? or is it left to provider/consumer of the API and JSON Provider used like Jackson or Jettison both provide a mechanism to turn on/off root object name serialization? Does not it create an interoperability issue if it is left to actual implementation?

thanks,
Venkat

**Comment by ePaul** [comment]
As I understand the specification, the request/response body should have just the object/array (or potentially also primitives) which is defined in the schema.

So for this path example from the spec:

```yaml
/pets:
  get:
    description: Returns all pets from the system that the user has access to
    produces:
    - application/json
    responses:
      '200':
        description: A list of pets.
        schema:
          type: array
          items:
            $ref: '#/definitions/pet'
```

A possible response would look like this:
```json
[ { "name" : "Puma", "id": 7}, {"name": "Dog", "id": 5}, {"name": "Elephant", "id": 11} ]
```

If you want to wrap it into an object with a name, you need to change the definition like this:

```yaml
/pets:
  get:
    description: Returns all pets from the system that the user has access to
    produces:
    - application/json
    responses:
      '200':
        description: A list of pets.
        schema:
          type: object
          properties:
            petList
              type: array
              items:
                $ref: '#/definitions/pet'
```
Then the response could look like this:

```json
{ "petList": [ { "name" : "Puma", "id": 7}, {"name": "Dog", "id": 5}, {"name": "Elephant", "id": 11} ] }
```

**Comment by vnalla** [comment]
What is recommended by specification? the pet object can be serialized in two ways:

{"name": "Puma", "id": 7}  or 

{"pet": {"name": "Puma","id":7} }

definitions:
  pet:
    properties:
       name: 
          type: string
       id: 
          type: string

**Comment by fehguy** [comment]
Actually just one way--the `pet` name as a key isn't part of the serialization process.  The first example would be a more correct example of serializing a pet

**Comment by webron** [comment]
@vnalla - it's not really up to OAS to say which is better - it's an API design issue which you need to decide on your own. Personally, I wouldn't include the object name as it adds no value and just bloats the request/response.
