### ISSUE TITLE
Please add an Index to the specification

### ISSUE THREAD

**Issue by germanp** [OAI/OpenAPI-Specification#673]
This will make easier searching and reading.

**Comment by fehguy** [comment]
Parent issue #589

**Comment by RobDolinMS** [comment]
Do we want to number the spec sections as well?  /cc @fehguy @webron @darrelmiller

**Comment by RobDolinMS** [comment]
I've started on this in a branch: https://github.com/RobDolinMS/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md  

Would welcome any feedback (or a thumbs-up) from more experienced spec contributors /cc @fehguy @webron @darrelmiller

**Comment by webron** [comment]
Thanks @RobDolinMS, looking good. I'd suggest waiting with this for a bit longer though as content may easily shift around or even be renamed, giving you extra work at the end.

**Comment by RobDolinMS** [comment]
I figured it would be good to get this added now so folks can use it (and comment on level of detail, if numbering would be useful, etc.)

I'm glad to pick-up an issue to do an edit/update pass as part of finalizing the spec.

**Comment by webron** [comment]
Done!
