### ISSUE TITLE
All ids and names are missing in swagger spec html

### ISSUE THREAD

**Issue by jvivs** [OAI/OpenAPI-Specification#675]
[Swagger.io](http://swagger.io/specification/) is currently the place where most of my coworkers go to read the OpenAPI spec and the linking structure appears to have changed. It's frustrating to have links break, especially when you're trying to link to someone in a document as long as this one: http://swagger.io/specification/

Is it possible to add github-style linking to headers like the markdown file has on [github](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md)? Also if there are anchors internally in the document, can we have an index or at least put some text in them so they can be found without having to view the source code?

I can open a PR if it is welcome.

**Comment by webron** [comment]
Issue was moved to https://github.com/swagger-api/swagger.io/issues/104.
