### ISSUE TITLE
Add fabric8.io to Sites and Services wiki

### ISSUE THREAD

**Issue by christian-posta** [OAI/OpenAPI-Specification#678]
```
diff --git a/Sites-and-Services.md b/Sites-and-Services.md
index 8c162fa..d3ff662 100644
--- a/Sites-and-Services.md
+++ b/Sites-and-Services.md
@@ -25,6 +25,7 @@ The following provide Swagger support to their software or services.
 * [Elastic.io](http://www.elastic.io/)
 * [Espresso Logic](http://docs.espressologic.com/docs/live-api/api-docs/)
 * [Evercam APIs for Cameras](http://www.evercam.io/develop/docs)
+* [Fabric8.io](http://fabric8.io)
```

**Comment by webron** [comment]
Done.

**Comment by christian-posta** [comment]
Thanks!

On Mon, May 2, 2016 at 1:30 PM, Ron <notifications@github.com> wrote:

> Done.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OAI/OpenAPI-Specification/issues/678#issuecomment-216353529>
>



-- 
*Christian Posta*
twitter: @christianposta
http://www.christianposta.com/blog
http://fabric8.io
