### ISSUE TITLE
Support for $ref in securityDefinitions

### ISSUE THREAD

**Issue by richvdh** [OAI/OpenAPI-Specification#680]
In a similar vein to #677: I'd also like to see support for references in `securityDefinitions` - again I have several APIs scattered across a number of files, and it would be helpful to share the definitions between them.

**Comment by webron** [comment]
Parent: #560

**Comment by handrews** [comment]
This is about a structure in 2.0 that is no longer relevant.  Security Schemes have been in the Components Object since 3.0, and see
* #1972 
* #3776 

for more recent similar requests.  Closing.
