### ISSUE TITLE
Structural improvements: enhance consumes and produces handling 

### ISSUE THREAD

**Issue by arno-di-loreto** [OAI/OpenAPI-Specification#689]
Following my ideas from #684 and extending the #660 idea, we could modify `consumes` and `produces` handling.

On spec's current version, you handle the produced and consumed media types this way:

Produced and consumed media type can be declared on root level for all paths and operations:

``` YAML
consumes:
  - application/json
produces:
  - application/json
```

And they can be overridden on operation level:

``` YAML
paths:
  /resources:
    get:
      consumes:
        - application/xml
      produces:
        - application/xml
```

The idea is to enable definition/overriding at each level (whole API, path, operation) for both `produces` and `consumes` and also add `produces` on response level (as proposed in #660)

``` YAML
paths:
  consumes:
    # apply to all path and operations
  produces:
    # apply to all path and operations
  /resources:
   produces:
     # apply to this path's operations and override upper level
   consumes:
     # apply to this path's operations and override upper level
   get:
     produces:
       # apply to this operation and override upper levels
     consumes:
       # apply to this operation and override upper levels
     responses:
       200:
         produces:
           # apply to this response and override upper levels
```

**Comment by arno-di-loreto** [comment]
parent #560

**Comment by MikeRalphson** [comment]
`produces`/`consumes` were removed/reworked in v3.0 and I think the `content` approach covers the issue here.
