### ISSUE TITLE
Question: OpenAPI tools

### ISSUE THREAD

**Issue by Vanuan** [OAI/OpenAPI-Specification#691]
Is there a list of tools that support OpenAPI/Swagger?
I saw this page to be very appealing: http://raml.org/projects/projects

Can we build a website like this?

**Comment by Vanuan** [comment]
Ok, I've found this: http://swagger.io/tools/
But would swagger.io be renamed to OpenAPI.io?

**Comment by MikeRalphson** [comment]
The official tooling list is now available at https://tools.openapis.org
