### ISSUE TITLE
Linking to meta-issue validated by TDC member?

### ISSUE THREAD

**Issue by arno-di-loreto** [OAI/OpenAPI-Specification#692]
It's not clear for me who decide to link issues to meta-issue?
If I create an issue can I link it (by adding a `parent #{parent issue number}` comment in it) to a parent meta-issue myself or must it be done by a TDC member?

**Comment by ePaul** [comment]
Not being a TDC member myself, I have added some parent issue links already, and nobody scolded me until now for doing this.

I guess the TDC members (on the virtue of having admin access to this repository) can remove the links again if they consider them wrong.

**Comment by arno-di-loreto** [comment]
OK thanks.
