### ISSUE TITLE
info.version string format?

### ISSUE THREAD

**Issue by jeromu** [OAI/OpenAPI-Specification#697]
Although the info.version is a string, is the info.version expected to be of the following format:  "#.#.#.#"?  For example: "2.0.1.4".  I noticed that all examples I've seen and the code generators expect that format.   If so... can the spec be updated to reflect that requirement?

**Comment by DavidBiesack** [comment]
Rather than just "#.#.#.#", should that be specified as Sematic Version?
I prefer using semantic versioning, but I don't know if OAS and related tools can/should mandate that APIs use it.

**Comment by ePaul** [comment]
Semantic versioning doesn't really make sense for the documentation of a remote API, more for an implementation or for a library. (What would be a bugfix change?)

We (my company in its guidelines) adopted [a scheme which uses three numbers in a different way to indicate draft versions](http://zalando.github.io/restful-api-guidelines/compatibility/Compatibility.html#should-provide-version-information-in-openapi-documentation).

**Comment by fehguy** [comment]
Yes, we don't want to enforce the versioning scheme.  There's no single, right way to do so, and enforcing one of the "wrong" ways will just cause headaches.

**Comment by webron** [comment]
Agree with @fehguy - this is not a concern for the spec.

**Comment by wparad** [comment]
Even aws has decided to use dates as the api versions, given that piece of information it would seem limiting to make this a version string.  @DavidBiesack what would be the advantage of such a change?

**Comment by fehguy** [comment]
OK Info is a string and is [described as such](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-1).  There is no required `format` for the string for the reasons above.

**Comment by DavidBiesack** [comment]
I agree we should not mandate a specific format for the version string. I was simply suggesting that if considered, semantic versioning would be preferable over "#.#.#.#" (Another option would be to add a separate but optional semanticVersion field)
