### ISSUE TITLE
* endpoint

### ISSUE THREAD

**Issue by Auxolust** [OAI/OpenAPI-Specification#698]
Following this post http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html , why do we not use * as the endpoint for describing the API rather than using openapi.json or openapi.yaml? We can then support the OPTIONS method per resource with a documentation fragment, as well as for the entireity of the server

**Comment by ePaul** [comment]
Just a note: the current HTTP 1.1 spec is RFC's 7230ff, in this case [RFC 7231, section 4.3.7](https://tools.ietf.org/html/rfc7231#section-4.3.7).

So you are suggesting to deliver the/an OpenAPI document (the definitions for all supported paths, likely) when doing an OPTIONS request on `*` (and fragments thereof for OPTIONS requests on specific paths). I guess this is possible (likely just when a sensible Accept: header is set), but I'm not sure how useful it would be in the general case, and whether it would interfere with other uses of OPTIONS.

**Comment by webron** [comment]
There are two issues with doing that. As @ePaul mentioned, some APIs use OPTIONS as part of their API. Not going into whether that's a good decision or not, removing support to that seems like an unnecessary limitation.

The other issue is fragments - we've toyed with the idea before (and it's not necessarily a spec concern) but it could be an issue with references. It's true that while serving the fragments, references can be dereferenced, but that takes away some obvious benefits.

**Comment by Auxolust** [comment]
So ignoring the fragment case of using OPTIONS per resource which I can agree might be a sore spot for people who are currently using the OPTIONS method in their existing APIs, the OPTIONS * request is still a viable choice?

**Comment by fehguy** [comment]
I think hijacking OPTIONS and tying them to a specific use case would be a very bad idea and create more problems than solutions.
