### ISSUE TITLE
Allow a new attribute ReasonCode as part of Responses

### ISSUE THREAD

**Issue by venkypayasam** [OAI/OpenAPI-Specification#699]
Code | ReasonCode | Description
------------ | ------------- | -------------
200|1	|Items Found
200|2	|Items Found with warnings
401|1	|Authentication Failed
401|2 	|Authorization Failed
500|100|System Failure
500|101|Underlying System Failure

**Comment by earth2marsh** [comment]
The fields described here are for documenting the HTTP response codes, not any custom error codes you might return. I'd suggest documenting the response schema with any custom error code and ideally include a link to that code's documentation on your developer site. If you really must tuck it into the responses for your own purposes somehow, consider using an `x-extension`.

**Comment by whitlockjc** [comment]
I agree with @earth2marsh but another idea is you could put this into your response schema.  Since this is most likely a case specific to your application, to me it makes sense being in your response schema instead of having some native support within OAS.

**Comment by venkypayasam** [comment]
Well, we have started API development by modeling the APIs with Swagger.yaml and we want to document as much as we can while modeling the API specs. We have already modeled a detailed response schema to support errors including returncode, reasoncode, and tokens. Understood that we can use custom X- headers as part of responses but am still struggling to model **multiple** responses/variations for the standard **HTTP Status Codes**.

**Comment by whitlockjc** [comment]
OpenAPI does not allow you to have multiple implementations of the same response, whether error or other.  So based on your example, if the only difference is the `reasonCode` property on the response object, you do not have a separate schema and are not impacted by this limitation.  But if your response object is different for each reason code, other than the `reasonCode`, then you have asked for something OpenAPI doesn't support.

In the end, the importance of your `Reason Code` is user space and should be put in the appropriate place.  That place, at least based on the OpenAPI perspective as the specification exists right now, would be in the `description` field of the response.  Here you can throw in GitHub flavored Markdown which can go into further detail about the `Reason Code` and such.

If I misunderstood, let me know.
