### ISSUE TITLE
add language metadata into "info" object

### ISSUE THREAD

**Issue by gioppoluca** [OAI/OpenAPI-Specification#70]
It could be useful to have a language element in the info object to represent the language used in the API data: it could be expressed using classical IT, ES, etc codes this way it can be used to translate or deal with the content of the API

**Comment by webron** [comment]
Parent: #560.

**Comment by gioppoluca** [comment]
This request comes form use of Swagger within European Projects whre cross country API usage is fostered.
Knowing the language of the content returned by the API could be helpful to send it to a translator for example.

**Comment by ePaul** [comment]
But is the content language actually static enough to be described in the swagger definition? Isn't this more of a runtime property? (Like what would be in the `Accept-Language` and `Content-Language` headers.)

**Comment by gioppoluca** [comment]
Usually yes I tipically have an API that return data from a DB and on the majority of the cases the text inside is in a single language.
When we publish the API we need a way to inform the consumer that the text information that he is getting is in language XX.  This will allow him to process the text as he please.
Is something that need to be described and is not just a runtime property.
The field could be optional so if not used there is not information about the textual content oer it could accept an array to allow for declaring that the content is in a set of languages.
Than during runtime there could be the way to dclare the actual language of the return, but the information in the decription can be used in other contexts.
