### ISSUE TITLE
find service by id makes weird exports.(right side yaml, left side generated server) https://gyazo.com/a03bb391d8fcb2e0df9a0cbb86514772

### ISSUE THREAD

**Issue by TOMOAKI12345** [OAI/OpenAPI-Specification#705]

**Comment by wparad** [comment]
Seems like a problem with the generator, I would probably suggest that the `operationId` be a string without spaces, but this isn't the right place to debug issues with the specific generator you are using.

**Comment by TOMOAKI12345** [comment]
thanks, I have move to https://github.com/swagger-api/swagger-editor/issues/954
