### ISSUE TITLE
Mime type -> Media type

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#712]
while many people still say "mime type" (and everybody knows what they're talking about), the correct term now is "media type" (https://tools.ietf.org/html/rfc6838). if nobody objects, i'll create a PR to make this terminology change.

**Comment by darrelmiller** [comment]
I certainly have no objections :-)

**Comment by dret** [comment]
closed by https://github.com/OAI/OpenAPI-Specification/commit/d9dc7fd4e0a7f61d49e787c29a705487fa5a319b
