### ISSUE TITLE
Request to add API stability index in schema

### ISSUE THREAD

**Issue by liushuping** [OAI/OpenAPI-Specification#719]
API stability indexes (such as "Frozen", "Stable", "Unstable", "Experimental") tells the maturity of the API to client, suggest to add it in schema

**Comment by ePaul** [comment]
Are those keywords from some specification we could look at?

I guess the actual lifecycle varies too much between users of OpenAPI for it to be useful to define a fixed set of values.

Also, where in the API definition do you want to add this? For the whole API (like in the `info` object), for a path, an operation, or an model schema?

**Comment by liushuping** [comment]
I got API stability idea originally from Node.js product, you can find information from page: https://nodejs.org/dist/latest-v6.x/docs/api/all.html#documentation_stability_index

Although the Node.js API is not in swagger schema, but the stability index idea is quite good. Allowing API owner to add a stability index to API enables the API owner a way to tell how the API will evolve and the API users will adapt their product based on the stability. it reduces the possibility of breaking software.

I would like to add the stability index in operation level.

**Comment by darrelmiller** [comment]
Personally, I think these kind of dynamic characteristics of an API belong more in something like [APIs.json](http://apisjson.org/format.html) rather than OpenAPI.  I don't think an OpenAPI spec document should itself change when an APIs implementation becomes designated as stable.

This is the same reasoning I used when I voted against using the hosts object to describe different deployment environments like dev,test and stage.  This is valuable meta-data, but I don't believe it belongs in the OpenAPI spec.

**Comment by wparad** [comment]
I agree with @darrelmiller, there is already the version of the spec, which should give you enougt freedom to sperify the values you want.

I think things like this fall into the SLA category, which could be argued are part of the API, but would have to be really thought about before adding them.

The values you want indicate the agreement to uphold the SLA, which is just a second degree away from the API.  Can you talk about your use case, why you would want to do something like this, and how it could help clients use the API?

**Comment by ePaul** [comment]
Also, the SLA might differ for different API consumers.

**Comment by liushuping** [comment]
@wparad by adding the API stability indexes, I want publish the APIs to clients as early as possible and get feedbacks earlier while letting clients know the potential changes of APIs indicated by the stability indexes. I agree with @darrelmiller , may be this is something like APIs.json.
