### ISSUE TITLE
Allow to specify which's the success response for an endpoint

### ISSUE THREAD

**Issue by frojasg** [OAI/OpenAPI-Specification#725]
As API designer I want to use this specification to explain to my clients how to use my API. For some endpoints, a success status will be a 2xx, for some other a 3xx.

The current specification just lists all the possible responses. The responsibility to know what's a success status is delegated to the client.

I was wondering if it makes sense to allow to the API designer to specify what's the success status of an endpoint

**Comment by wparad** [comment]
Generally speaking "success" is determined by the client depending on if the response code is expected.  For HTTP 2XX are success, and that is the end of the story, if you weren't using a RESTful API, and instead designed your own methodology/protocol then it is unlikely this specification can help you.  I would expect this spec to respect the meanings of the status codes as dictated by the HTTP standard.

**Comment by handrews** [comment]
The last answer (in 2016) seems pretty definitive so I'm going to close this.
