### ISSUE TITLE
Vendor extension link is broken

### ISSUE THREAD

**Issue by diyfr** [OAI/OpenAPI-Specification#731]
on this page 
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
The vendor extension section doesn't exist. 
I find an reference here
https://github.com/swagger-api/swagger-codegen/wiki/Vendor-Extensions

**Comment by webron** [comment]
The link is fine - it's just lower in the page so can't appear at the top part of your browser.

**Comment by wparad** [comment]
Hmmm I think I'm with @diyfr on this one, something is definitely off.

**Comment by webron** [comment]
Can't solve it without actually seeing the problem, so if you can provide more details, I'll look into it.

**Comment by wparad** [comment]
Nvm, this totally works, it just didn't link to where I thought it was going to.

**Comment by diyfr** [comment]
Yes,where is vendor extension section?

**Comment by webron** [comment]
Exactly at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#specification-extensions - the title is just `Specification Extensions`.

**Comment by ePaul** [comment]
I guess the problem is that the link title is "Vendor extensions", while the title of the section is "Specification Extensions", which is confusing for some people.
