### ISSUE TITLE
Add reference section

### ISSUE THREAD

**Issue by dret** [OAI/OpenAPI-Specification#732]
i am wondering if it would make sense to collect references to other documents at the end of the spec. currently they are directly linked from where they are mentioned, and that makes it hard to understand the dependencies.
i am not sure if/how MD could help with that, but even if it doesn't, it shouldn't be too hard to have some simple guideline on how to use references with an explicit references section.

**Comment by MikeRalphson** [comment]
The HTML rendered versions of the spec (linked to from openapis.org) now include a [references](https://spec.openapis.org/oas/v3.0.3.html#references) section.

**Comment by dret** [comment]
thanks, that's awesome!
