### ISSUE TITLE
Why components?

### ISSUE THREAD

**Issue by andydude** [OAI/OpenAPI-Specification#744]
I like `hosts`, but I do not like `components`.

From a readability perspective, is there really any difference between

``` yaml
components:
  $ref: 'components.json'
```

and

``` yaml
definitions:
  $ref: 'components.json#/definitions'
parameters:
  $ref: 'components.json#/parameters'
responses:
  $ref: 'components.json#/responses'
responseHeaders:
  $ref: 'components.json#/responseHeaders'
securityDefinitions:
  $ref: 'components.json#/securityDefinitions'
```

?

**Comment by fehguy** [comment]
Not really sure what you mean.  The idea behind the `components` section is to house a number of reusable, yet structured pieces of information.  Currently in the 2.0 spec they're sprinkled around, the notion of components puts them in one spot.  The keys inside the components allow us to make sure they can be validated by the schema correctly, reducing the risk of errors.

**Comment by fehguy** [comment]
Closing as no response.
