### ISSUE TITLE
Question: Reusing Path Parameters

### ISSUE THREAD

**Issue by veleek** [OAI/OpenAPI-Specification#745]
I've got a series of paths that use the same path parameter:

    paths:
      /catalog/items/{id}:
        ...
      /catalog/items/{id}/children:
        ...
      etc.

I would like the {id} parameter to be defined once with a description and type so that I can reuse it, but this appears to be invalid:

    paths:
       ...
    parameters:
      catalogItemId: # <-- Not a valid parameter definition
        name: id
        in: path 
        description: The ID of the catalog item to update.
        required: false
        type: integer
        format: int64

It doesn't _seem_ like this should be invalid according to the schema linked by the editor (http://swagger.io/v2/schema.json#), but for some reason this is rejected by the online editor.  

Is there anyway to share path parameter definitions?

**Comment by webron** [comment]
Path parameters in 2.0 must **always** be required. Change it to `required: true` and you're good to go.

**Comment by veleek** [comment]
Doh!!!! Looking at this for FAR too long before finding this.  I wish the schema could give a better error in cases like this, but c'est la vie.
