### ISSUE TITLE
securityDefinitions not found in swagger.json

### ISSUE THREAD

**Issue by ElXDi** [OAI/OpenAPI-Specification#750]
Dear Sirs,
I'm trying to use latest version Swagger UI (2.1.5 pulling from github). But for some reason the 'Authorize' button is hidden. I made quick investigation and found that 'securityDefinitions' parameter is not passing inside swagger.json file (like in this example: http://petstore.swagger.io/v2/swagger.json).
I'm using JAX-RS 1 by Jersey 1. Here is generation code:
java -jar swagger-codegen-cli-2.2.1.jar generate -i http://petstore.swagger.io/v2/swagger.json -l jaxrs --library=jersey1 -o ~/petstore
(if you import http://petstore.swagger.io/v2/swagger.json file to Swagger Editor you can see the 'securityDefinitions').
I'm running this test example by using mvn package jetty:run.

So the main question how I can (or can I) use authorization functionality of Swagger UI with my apiKey (it is JWT, I know, that does not Support it yet, but I'm using it like simple api token). 

In addition, I can make calls without active authorization button simply setting the api key authorization like: 
var jwt = new SwaggerClient.ApiKeyAuthorization( 'Authorization', 'Bearer ' + 'JWT', 'header' );
window.swaggerUi.api.clientAuthorizations.add( 'jsonWebToken', jwt );
BUT I have red exclamation marks in front of each endpoint. 

So do I need to just implement my own authorization or how I can use standard api key approach?

I do really appreciate your work!

**Comment by ePaul** [comment]
It is not really clear to me with which tool you have an issue ... with the code generator ([swagger-codegen](https://github.com/swagger-api/swagger-codegen/)) or [Swagger-UI](https://github.com/swagger-api/swagger-ui). Please post the issue to one of those project's issue trackers.

This repository (and issue tracker) is about the Swagger Specification (now called OpenAPI Specification), not about any tools working with it.

**Comment by ElXDi** [comment]
The problem is regarding both of project, I guess (mb it is more related to codegen project).
Thank you for your answer!
I'll post my question to correct place.

Cheers!

**Comment by webron** [comment]
@ElXDi if you're not sure which tool is the source of the problem, you can always use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).

**Comment by ElXDi** [comment]
@webron Thank you very much!
