### ISSUE TITLE
Missing 1.1 spec

### ISSUE THREAD

**Issue by checat** [OAI/OpenAPI-Specification#752]
At the moment. the only semi-formal definition of the specification version 1.1 is available from the old wiki revisions.
https://github.com/swagger-api/swagger-core/wiki/Resource-Listing/4da1dfa32d38f1a23b2d6ba680d51bfeb4262132
https://github.com/swagger-api/swagger-core/wiki/API-Declaration/4da1dfa32d38f1a23b2d6ba680d51bfeb4262132
https://github.com/swagger-api/swagger-core/wiki/Parameters/4da1dfa32d38f1a23b2d6ba680d51bfeb4262132
https://github.com/swagger-api/swagger-core/wiki/Datatypes/4da1dfa32d38f1a23b2d6ba680d51bfeb4262132
https://github.com/swagger-api/swagger-core/wiki/Errors/4da1dfa32d38f1a23b2d6ba680d51bfeb4262132

These should be compiled together as an existing document even if not formal and of historical value.

The 1.2-transition document may have some additional clarifications https://github.com/OAI/OpenAPI-Specification/wiki/1.2-transition

If anybody knows location of 1.0 specs, 1.0 could be added too, but that has less value.

**Comment by webron** [comment]
1.0 and 1.1 were never written as specs. 1.2 was reverse engineered from wiki pages, code and other resources. There's almost no way to do that for 1.0 and 1.1 anymore (the wiki pages are far from being enough).

**Comment by RobDolinMS** [comment]
@checat Given @webron's comment, can this issue be closed?

**Comment by checat** [comment]
Well, it would be good if someone revived at least those wiki pages.
But in general, as I understand, it may be closed with a resolution "won't fix".

**Comment by webron** [comment]
Yup, I'm afraid this is a "won't fix".

**Comment by MikeRalphson** [comment]
@checat I had a need for some more information on 1.0 and 1.1 and have done a little 'digital archaeology' and put the results [here](https://github.com/mermade/swagger1).
