### ISSUE TITLE
Parameter Object cleanup removed collectionFormat

### ISSUE THREAD

**Issue by pkriens** [OAI/OpenAPI-Specification#754]
Thanks for cleaning up Parameter Object by moving the body to RequestBodyObject, made sense.

However, the old spec allowed the collectionFormat (csv, multi, pipe, etc.) for parameters and this option is now gone. It is also not completely clear now how to validate a header/parameter against a schema object? Should it be treated as a primitive or can the header/parameter/cookie also contain JSON?

**Comment by pkriens** [comment]
Notice that the example still contains collectionFormat

**Comment by webron** [comment]
It's because it will be handled by #665 in a different way.

**Comment by jharmn** [comment]
Actually `collectionFormat` still exists in the `Items` object. That said, it probably needs a revisit with parameter serialization strategy.
https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#items-object

**Comment by fehguy** [comment]
See #804
