### ISSUE TITLE
Use of Java/C and other languages reserved words

### ISSUE THREAD

**Issue by pkriens** [OAI/OpenAPI-Specification#755]
The spec contains a number of field names that are reserved words in Java. It would be quite convenient if these words are not used. Is there an interest in making this easier for Java developers? If so I can crawl through the spec to find the locations.

Examples: default, enum

**Comment by ePaul** [comment]
I don't really see any problem with mapping those fields to other names. (Also, those just a problem for people implementing the spec directly, not really for people just using libraries which have OpenAPI definitions as input.

**Comment by zeeshanejaz** [comment]
Hi @pkriens, as @ePaul suggested, mapping reserved words used names of parameters and fields to other names is easily achievable. Let me know if you need help in a particular case, I might be able to help with implementation. BTW, this mapping can be done automatically (for example APIMATIC does this), I like the approach used in Objective-C of using a 1/2-letter prefix to avoid naming conflicts.

**Comment by pkriens** [comment]
Well, it is not a problem perse but it means an unnecessary mapping layer ... if there was no use of reserved words from Java (which are very similar to other languages) then I could have a mapping free implementation since the field name in a Java object can then be the JSON field name. Just simpler, less work, and less error prone. Since OpenAPI tends to be an open standard I thought it would be a good idea to minimize the impedance mismatch towards other languages than Javascript?

**Comment by darrelmiller** [comment]
@pkriens If we avoided all the reserved words in all the languages that we targeted, we may find ourselves being forced to use fairly obscure words to describe common concepts.  Also, I would recommend against attempting to map OpenAPI specs directly to native types using any kind of automatic deserializer.  Any Open API deserialization library has to deal with uses of $ref and resolution of overridden definitions in nested scopes.  It should also deal with both YAML and JSON.

**Comment by pkriens** [comment]
I think the list of reserved words in the most popular languages you probably end up with 30-40 reserved words. Most reserved words come from C. So I am not sure this is a real problem, there are only a few places where this is a problem.

Being able to use the actual field/method names for serializing deserializing is an enormous time and error saver because you get rid of a lot of boilerplate code. I can handle the reserved words, it is just kind of ugly.
