### ISSUE TITLE
Support for type: object for formData parameters

### ISSUE THREAD

**Issue by fdstevex** [OAI/OpenAPI-Specification#758]
Currently the specification doesn't support complex formData parameters. For example, our API uses this format (appropriately escaped):

`body={"name1": "value", "name2": "value2"}`

With the current spec we'd have to specify the body parameter as type: string and pass the JSON as an opaque string. This negates a lot of the value of the Swagger definition for our API.

As also described here:
https://groups.google.com/forum/#!topic/swagger-swaggersocket/Eftccv6z5Ss

and

https://groups.google.com/forum/#!searchin/swagger-swaggersocket/formData$20schema%7Csort:relevance/swagger-swaggersocket/6QxOTKLZyM0/49o4FRR8IgAJ

**Comment by ePaul** [comment]
Related: #665.

**Comment by fehguy** [comment]
@fdstevex FYI complex parameters have been added to the spec.  What @ePaul mentions is that we haven't formalized _how_ we describe the serialization strategy.  But what you're asking for has been accepted conceptually.

Please reopen with any questions.
