### ISSUE TITLE
Enhancement - Code Samples for multiple languages

### ISSUE THREAD

**Issue by maneeshsahu** [OAI/OpenAPI-Specification#767]
I was using a new utility - ReDoc (https://github.com/rebilly/redoc)  that auto-generates documentation, including language specific bindings. They use a vendor extension called - `x-code-samples` https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-code-samples that is used in-line along with the swagger specification. 

My suggestion is to enhance the OpenAPI specification by separating the samples section from the specification, and putting it in a separate file: `<name>-samples-<lang>.json/yml` 

So a JSON sample would be `<name>-samples-json.json`, while a Swift sample would be `<name>-samples-swift.json`.

Within the sample JSON, there will be a link to the operationId and the sample. 

`
{
"info": {
  "lang": "Swift",
  "specification": "<name>.json"
},
"samples": {
   "<operationId>": "<Swift Code Example for operationId>"
}
}
`

This allows the samples for the different languages to be managed independently.

**Comment by webron** [comment]
That sounds very much out of scope for the spec. It's meant to be implementation-agnostic.

**Comment by maneeshsahu** [comment]
Thats why I wanted to externalize it and not include the sample section in the swagger spec.

**Comment by webron** [comment]
But then, it has nothing to do with the spec.
