### ISSUE TITLE
Multiple security requirements at once, or neither

### ISSUE THREAD

**Issue by jacobweber** [OAI/OpenAPI-Specification#771]
Say you have two types of authorization: oauth2 and apiKey. But when using apiKey authorization, you require two headers to be present. So you need to specify something like `(A OR (B AND C))` in your security requirements. Is this possible?

The [comments in #14](https://github.com/OAI/OpenAPI-Specification/issues/14#issuecomment-59094027) make reference to this, but I don't see a way to do it. This is needed, for example, if you want to support [3Scale's](https://support.3scale.net/docs/api-authentication/authentication-patterns) "Application Identifier and Key pairs" and "OAuth 2.0" patterns at the same time.

**Comment by webron** [comment]
Yup, you can do that. Say you have 3 security requirements defined `A` for oauth2, `B` for apiKey 1, `C` for apiKey 2 (it's a header, let's face it), then your `security` would be defined as:

```json
security: [
  { "A": [] },
  { "B": [], "C": [] }
]
```
Didn't add scopes for oauth2, but that's the general idea.

**Comment by jacobweber** [comment]
Thanks, that's very helpful.
