### ISSUE TITLE
Body parameter should be able to coexist with other parameters

### ISSUE THREAD

**Issue by remcohaszing** [OAI/OpenAPI-Specification#775]
An API call may be able to consume multiple formats. This format could be for example `multipart/form-data` or `application/json`.

However, following the spec, these fields are mutually exclusive. The following is considered invalid by [Swagger editor](http://editor.swagger.io):

```yaml
info:
  title: demo
  version: 1.0.0
paths:
  /:
    post:
      consumes:
        - application/json
        - multipart/form-data
      parameters:
        - name: payload
          in: body
          schema: {}
        - name: attachment
          in: formData
          type: string
      responses:
        200:
          description: asd
swagger: '2.0'
```

**Comment by darrelmiller** [comment]
V3.0 of the spec introduces a new requestBody object and this PR https://github.com/OAI/OpenAPI-Specification/pull/761 changes the way media types are mapped to request/response bodies.

**Comment by darrelmiller** [comment]
@remcohaszing Can I close this?  I do believe OpenAPI 3.0 will address this requirement.
