### ISSUE TITLE
InlineModelResolver drop all vender extensions for any Schema Object

### ISSUE THREAD

**Issue by zhengcan** [OAI/OpenAPI-Specification#776]
The spec told me "Allows extensions to the Swagger Schema."
ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#patterned-objects-9

When I define some schema objects in `definitions` section, and use $ref to reference it in response, I've noticed that all vender extensions works well.
But when I use the vender extensions in 'schema' section in `response` directly, all vender extensions gone.

I've debugged my generator code, and confirmed that the `InlineModelResolver` used by `DefaultGenerator` drops all vender extensions when it try to `flatten` all response schema objects to inline schema.
For example:
```
    public Model modelFromProperty(ObjectProperty object, String path) {
        String description = object.getDescription();
        String example = null;

        Object obj = object.getExample();
        if(obj != null) {
            example = obj.toString();
        }
        String name = object.getName();
        Xml xml = object.getXml();
        Map<String, Property> properties = object.getProperties();

        ModelImpl model = new ModelImpl();
        model.setDescription(description);
        model.setExample(example);
        model.setName(name);
        model.setXml(xml);

        if (properties != null) {
            flattenProperties(properties, path);
            model.setProperties(properties);
        }

        return model;
    }
```

I'm not sure why it work like this, but it seams like a kind of bug.

As workaround, I have to `cache` all vender extensions for response schema in `preprocessSwagger(Swagger)`, and set them back in `fromOperation(String, String, Operation, Map<String, Model>, Swagger)`.

**Comment by ePaul** [comment]
This looks like not a problem with the OpenAPI specification, but with some tooling working on it. Please submit your issue to the issue tracker of the tool which you are using. (I would guess [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen)?)

**Comment by zhengcan** [comment]
Yes, you are so right :)
I should move this issue to codegen.
