### ISSUE TITLE
Combine swagger Definition files

### ISSUE THREAD

**Issue by UPADHYA28** [OAI/OpenAPI-Specification#781]
Hi,

 am generating a swagger definition for all the my APIs by annotating the source code.

I was wondering if there is any way for make possible merge all the APIs in one single `json` file?

Note: I am using `Swagger 2.0` definitions.

**Comment by darrelmiller** [comment]
If all the APIs live under the same basePath then there is no reason you could not include all operations for all the APIs in a single OpenAPI 2.0 document.  You could use tags to identify which original APIs the operations belonged to.

**Comment by UPADHYA28** [comment]
@darrelmiller Thank you for the response. I have all the 'json' definitions in a single location. I dont want to modify any UI component of Swagger. 

My idea is to merge all the definition in  a single file and feed this 'json' to UI.

Could you please provide some additional info on you comment any example.

**Comment by jhprks** [comment]
@UPADHYA28 Recently I've been looking into OpenAPI/Swagger for REST API development and came across [swagger-parser](https://github.com/BigstickCarpet/swagger-parser). Your question reminded me of its [bundle method](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#bundleapi-options-callback), but I'm not sure if it's what you're looking for.

**Comment by webron** [comment]
This is a tooling question that should be opened on the project being used.
