### ISSUE TITLE
Add clientAuthorizationType property to Security Scheme Object

### ISSUE THREAD

**Issue by MugeSo** [OAI/OpenAPI-Specification#785]
## Background

[RFC6749](https://tools.ietf.org/html/rfc6749#section-2.3) allows authorization server to implement client authentication, which is used when a credential client access to token endpoint. 

>  If the client type is confidential, the client and authorization
>    server establish a client authentication method suitable for the
>    security requirements of the authorization server.  The authorization
>    server MAY accept any form of client authentication meeting its
>    security requirements. 

RFC6749 also describes 2 typical client authentication method in [§2.3.1](https://tools.ietf.org/html/rfc6749#section-2.3.1).
However it allows any other  suitable HTTP authentication scheme in [§2.3.2](https://tools.ietf.org/html/rfc6749#section-2.3.2)
## Proposal

To follow this spec, I propose to add a `clientAuthorizationType' property to Security Scheme Object.

OR

Add `clientAuthorization` property which is an Object like Security Scheme Object.

**Comment by lornajane** [comment]
Since this issue hasn't had much interaction or engagement, it will be closed.
