### ISSUE TITLE
[Question] Equivalent path already exists

### ISSUE THREAD

**Issue by pkupilas** [OAI/OpenAPI-Specification#788]
Is it any way to difference two similar paths with different parameter?
Swagger returs error:
_Equivalent path already exists: /api/integration/message/v1/suppvouch/{id}_
Example:
```
  '/api/integration/message/v1/suppvouch/{message}':
    post:
      parameters:
        - type: string
          name: message
          in: path
          required: true
          x-nullable: false
        - type: string
          name: correalationKey
          in: query
          required: true
          x-nullable: true
      responses:
        '200':
          description: ''
          schema:
            type: integer
          x-nullable: false
```
```
  '/api/integration/message/v1/suppvouch/{id}':
    put:
      parameters:
        - type: integer
          name: id
          in: path
          required: true
          x-nullable: false
        - name: newStatus
          in: body
          schema:
            type: string
          x-nullable: true
      responses:
        '204':
          description: ''
```

**Comment by ePaul** [comment]
In OpenAPI 2.0, no (though there is a workaround: https://github.com/OAI/OpenAPI-Specification/issues/146#issuecomment-117288707). Related issues: #146, #164, #270.

In your example, I guess the server could distinguish both variants from the presence of the query parameter or the request body, but I don't know how this would work in a general case.

**Comment by darrelmiller** [comment]
@pkupilas I'm assuming you are trying to describe an existing system that can't be changed rather that one that you are building.  But just in case I'm wrong, allow me to suggest that using the type system of the implementation language to determine which operation to match is opening the door to a world of edge cases.

Different languages to completely different things when it comes to coercing string literals into native types.  You don't want to expose behaviour of your chosen language through your HTTP interface.

Consider the following URLs and which operation they would map to:

    /api/integration/message/v1/suppvouch/1.0
    /api/integration/message/v1/suppvouch/1%20001
    /api/integration/message/v1/suppvouch/232,200

Using an extra constant path segment to identify the desired operation is more reliable, more understandable and will perform better.  Forgive me if I'm "preaching to the choir".

**Comment by fehguy** [comment]
Yes, while this is technically possible to route on a server, it's impossible, from a URI, to determine if a path segment /1/ is a string ("1") or number (1).

For now, this is not supported, and it is expected that these paths are equivalent.

One could provide formatting requirements to a path parameter, for example, and say that `{message}` can either be an integer or an email address, which are easy to discern.  But that's a very contrived example, and pretty much all tooling will get it wrong.  So for now, no that is not supported.  Path segments of different types will be treated to be equivalent and fail the spec.
