### ISSUE TITLE
User Key option in definitions object

### ISSUE THREAD

**Issue by mchaitanyababu** [OAI/OpenAPI-Specification#790]
I have a DB table on my app server and I have an abstraction layer to the DB table. In this layer, I am providing user to specify a set of multiple fields as user key.

There can be multiple user keys and for each user key, there will be a sequence number which tells us in which order these User Keys need to be validated. Also, there is a provision to inactivate an user key.

To successfully insert a record in to the DB, I would have to satisfy a set of user keys or any one of them (these multiple user keys may not be at DB level but at the level which acts as an abstraction to the DB table).

I think, as of now there is no provision to specify user keys required for this definitions object.

It would be beneficial to add user keys to definitions object and validating them based on the defined sequence. Because, the 3rd party who is using the API, would be aware of all data requirements to complete this operation and hence can avoid server round trips to successfully complete this operation. Meaning, it would be easy to identify why this data operation is failing if there are user key definitions in front of you rather than on the target server.

IMO, this would be an enhancement to the standard.

**Comment by fehguy** [comment]
It's really hard for me to follow your comment, but I think you're saying that you want to have a map, with required keys in it.

This is easy.  Define the properties and make them required.  Then enable `additionalProperties` in the object to allow other keys to exist.
