### ISSUE TITLE
[Question] @ApiParam example

### ISSUE THREAD

**Issue by Trialer1** [OAI/OpenAPI-Specification#795]
Hi,

I am wondering why my specified example value in @ApiParam at an @PathVariable in my Spring REST controller doesn't exist in my Swagger JSON.
`public Collection<Foo> getFoo(@ApiParam(value = "My bar value", example = "bar123", required = true) String bar) {`
I am expecting "bar123" to appear as an example under the parameter "bar" in my Swagger JSON.

So now my questions is if the absence of the example is a bug or if I am using the example field wrong?

Thanks
Dennis

**Comment by ePaul** [comment]
Hi, this repository is for the OpenAPI specification, which is just about the API definitions and possibly about the actual JSON being exchanged.

It looks like you have a problem with a specific implementation, maybe [swagger-core](https://github.com/swagger-api/swagger-core)? Please open your issue there. (Though a bit more context will be helpful there too, e.g. a full example file with the wrong output.)

**Comment by Trialer1** [comment]
Ok thanks for you hint. I had a look at the issue at swagger-core and found this one: https://github.com/swagger-api/swagger-core/issues/1940
This is exactly my problem.

Best regards
Dennis

**Comment by webron** [comment]
As @ePaul pointed out, this is not an issue with the spec but with the tooling.
