### ISSUE TITLE
Add description to ContentTypeObject and remove layer from requestBody

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#803]
This issue is based on suggestions from @jharmn regarding simplifying the use of `content` objects in the `requestBody`

Instead of a `requestBody` looking like this,

```
post:
  requestBody:
    description: user to add to the system
    required: true
    content:
      text/plain:
        schema:
          type: array
          items:
            type: string
```

we could move the description into the _contentTypeObject_ and remove the `content` object.  Then `requestBody` effectively because a `content` object but with a different name.

```
post:
  requestBody:
    text/plain:
      description: user to add to the system
      schema:
        type: array
        items:
          type: string
```

The two downsides are we lose the place to put `required` and for some people the descriptions will be redundant.  The upside is **one less layer** and people who really want different descriptions for different content types can have it.

**Comment by ePaul** [comment]
Hmm, maybe we can invent some dummy content type for "empty", and have the convention that the request body is not required when the "empty" version is included.

**Comment by darrelmiller** [comment]
@ePaul  The `requestBody` property is not required, so if you have no body, then you don't need to include the property.

**Comment by ePaul** [comment]
@darrelmiller My comment was a reply to this (sorry, should have made that clearer):

> The two downsides are we lose the place to put `required` [...]

I understand that this is problematic in the case where an operation (likely a POST) has an optional request body – i.e. you can either send some `application/json` value (with a specific schema) or nothing (no request body). Before we could have used `required: false` in the requestBody level, now we can't do anymore.

My dummy content type would be kind of a workaround for this.

(We could also say that required: false is the default, but then we get the problem of not being able to indicate that the body is not optional.)

We could also make `requestBody` have both a boolean `required` property and any number of "media-type named" properties with the ContentTypeObjects. (Similar to how a path in OpenAPI 2.0 has both an parameters array and several operations as properties.)

**Comment by darrelmiller** [comment]
Ahh, I'm just being really slow today.  I think I prefer the `required` property in the `requestBody`. I did like the symmetry of the request content and response content, but that is just the lazy coder in me :-)

**Comment by jharmn** [comment]
This issue is moot with the current spec. `description` is at the Request & Response Object level, not in `content` or `content type` at all.
@darrelmiller closing, reopen if I missed something.
