### ISSUE TITLE
No concept of authorization/permissions for security schemes other than oauth2?

### ISSUE THREAD

**Issue by ryshep111** [OAI/OpenAPI-Specification#809]
While attempting to build middle-ware that works for all three supported security schemes, I noticed that there seems to be no concept of authorization/permissions built into the spec, other than the 'scopes' property for oauth2. Is there a reason why permissions are not available for the other two schemes as well? Was it a conscious decision to have security in the spec be purely a means of authentication? Would love to hear thoughts on this.

**Comment by ckriley** [comment]
I second the need for a more generic / flexible security model such as SAML2 or future specifications as they become applicable. We have a client using OAuth 1.0a for REST APIs and the current spec wouldn't be able to support that either.

**Comment by fehguy** [comment]
Please look at the approved, merged pull request for security updates in 3.0

**Comment by fehguy** [comment]
As we have added support for `openIdConnect`, I believe this can be closed.
