### ISSUE TITLE
Swagger UI - Blank parameter input results in paramter being ommited from URL

### ISSUE THREAD

**Issue by caroseuk** [OAI/OpenAPI-Specification#81]
When using swagger-ui to query an API, if you supply a blank parameter, the parameter is not included in the API query URI.

Currently when querying API with a blank parameter "query=":
http://api.server.com/REST/?query2=text&query3=text

Is it possible to make this configurable, so that if the parameter is provided as blank the URL still contains the blank parameter:
http://api.server.com/REST/query=&query2=text&query3=text

Spoke to Tonytam on IRC who advised me to raise this as a bug

Thanks

**Comment by webron** [comment]
Closing in favor of #611.
