### ISSUE TITLE
Clarify how/if null property values are supported

### ISSUE THREAD

**Issue by cipresso** [OAI/OpenAPI-Specification#835]
Hi.  One of the things we're hoping for in the OpenAPI spec is support for null types.  This is especially important for SQL where "property":"" means something different from "property":null.  Using JSON schema you indicate something can be null by using a type array as in "type":['string','null'].  What would be the equivalent in the next version of OpenAPI?

**Comment by darrelmiller** [comment]
The current plan is to have null support.  See https://github.com/OAI/OpenAPI-Specification/pull/741

**Comment by cipresso** [comment]
Thanks Darrel!
