### ISSUE TITLE
json schemas allows `$refs` in operation objects where the spec requires `type`

### ISSUE THREAD

**Issue by striglia** [OAI/OpenAPI-Specification#84]
The swagger spec is quite specific on how to refer to Models in your operations objects -- namely you MUST use `type` to reference models (see [this line](https://github.com/wordnik/swagger-spec/blame/master/versions/1.2.md#L783))

The schemas included in this repo are more lenient, they will allow anything matching the dataTypeBase, which allows for either `type` or `$ref` (see [this line](https://github.com/wordnik/swagger-spec/blob/master/schemas/v1.2/operationObject.json#L6)).

Seems like a constraint that can successfully be fixed in the schemas, hopefully without too much ugliness. It's worth noting that Swagger-UI's behavior matches up with the spec -- it will reject any operations object with a missing `type` field.

**Comment by webron** [comment]
Closing as no longer relevant.
