### ISSUE TITLE
Relative vs Absolute URLs

### ISSUE THREAD

**Issue by darrelmiller** [OAI/OpenAPI-Specification#843]
There are a number of properties that are defined in the OpenAPI specification.  Most of them do not specify if the URLs can be relative or absolute, and if they are allowed to be relative, where they are relative to.

Here is the list of URLs in the specification:
 - TermsOfService
 - ContactUrl
 - LicenseUrl
 - Server.Url
 - ExternalDocUrl
 - Link href
 - openIdConnectUrl
 - authorizationUrl
 - tokenUrl
 - refreshUrl

My suggestion is that wording should be added to indicate that all URLs should be allowed to be relative unless specifically prohibited and relative URLs are relative to the serverURL.  Only the Server.Url should be indicated as an URL that MUST be absolute.

Example:

```YAML
openapi: 3.0.0
info:
  title: My Awesome API
  termsOfService: ./terms/
servers:
- url: https://sandbox.gigantic-server.com/v1
  description: User testing server
- url: https://api.gigantic-server.com/v1
  description: Production server
```

The terms of service for the testing server would be at `https://sandbox.gigantic-server.com/terms` and for the production server `https://api.gigantic-server.com/terms`

Note that the terms for the production server is found at `https://api.gigantic-server.com/terms` and not `https://api.gigantic-server.com/v1/terms` due to the lack of a trailing slash on the server URL.

**Comment by DavidBiesack** [comment]
The example does not match up. The server `url` in the example is `https://sandbox.gigantic-server.com/v1` so appending the termsOfService relative URL `./terms/` to it yields ``https://sandbox.gigantic-server.com/v1./terms/` which is probably not the intent. 

I don't think we can/should strip anything (`v1`) off the server url. For example:

```YAML
openapi: 3.0.0
info:
  title: My Awesome API
  termsOfService: /terms
servers:
- url: https://sandbox.gigantic-server.com/v1
  description: User testing server
- url: https://api.gigantic-server.com/v1
  description: Production server
```

with the resulting url `https://sandbox.gigantic-server.com/v1/terms` for the test server, and  `https://api.gigantic-server.com/v1/terms` for prod

**Comment by darrelmiller** [comment]
@DavidBiesack We could choose to say that relative resolution is done via simple string concatenation, but that is not how it is defined in [RFC 3986](https://tools.ietf.org/html/rfc3986#section-5.4.1) and it is not how browsers do it, nor how libraries like .net do it.  Can't say for Java.

**Comment by DavidBiesack** [comment]
Got it, I stand corrected.

**Comment by darrelmiller** [comment]
While we are on the subject, technically, the fact that path keys all start with a '/' means that if you use the proper relative reference rules, then a server URL that is `http://api.example.org/{tenant}/` and have a path that is `/info`, then combining those to an absolute path would create `http://api.example.org/info` instead of the expected `http://api.example.org/{tenant}/info`.  

I'm going to guess that there is zero appetite for changing this, but I just figured I would bring it up, because it does keep me awake at night.

**Comment by ePaul** [comment]
@darrelmiller I guess [for paths](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#paths-object) we shouldn't use the "relative path" wording to make sure it is not confused with the relative URL resolution system?

Also, maybe here we should explicitly refer to RFC 3986 to when saying "relative to the server URL".

**Comment by darrelmiller** [comment]
Changes incorporated into V3
