### ISSUE TITLE
Allow a 'description' for examples

### ISSUE THREAD

**Issue by EricWittmann** [OAI/OpenAPI-Specification#849]
It will be very nice to be able to provide multiple examples for things like responses and definitions!  In addition to that nice change, it might be useful to provide an optional 'description' for each example.  When generating documentation, a label or description for each example would be extremely useful.

I'm not sure if a full description is needed, or perhaps just a label/title.

**Comment by darrelmiller** [comment]
We have 1 out of the 2 in V3.  You can now have multiple examples in both parameters and content objects.  However, we unfortunately were not able to get example descriptions into this release, however, it is a common request and we will try and work on it for the next release.
