### ISSUE TITLE
Broken links to json-schema references

### ISSUE THREAD

**Issue by yucer** [OAI/OpenAPI-Specification#850]
All links like this:

` http://json-schema.org/latest/json-schema-validation.html#anchor17`

need to be updated, they have been moved in the target to this format:

 ` http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.2`

**Comment by webron** [comment]
I'm afraid that's not accurate. The JSON Schema folks seem to have replaced the draft 4 with the latest, but I'm not sure they actually have draft 4 published so we can point to it. Will have to check with them.

**Comment by yucer** [comment]
It seems that they have improved the anchors to be more descriptive than `#anchor17`, `#anchor#21`. So I guess the new ones should be the final.

Sometimes that happen even when we take care of getting the links up to date.
If they would give enough time to Tim Berners-Lee, that might never happen. ;-)

**Comment by webron** [comment]
The anchors is not the problem - it's not the right spec anymore. As far as I can tell, there's no published draft 4 (haven't looked enough into it) so we can't fix the links easily.

**Comment by ePaul** [comment]
Related: https://github.com/json-schema-org/json-schema-org.github.io/issues/59

**Comment by Relequestual** [comment]
Ball is in your court guys https://github.com/json-schema-org/json-schema-org.github.io/issues/59#issuecomment-270329646

**Comment by Relequestual** [comment]
As an aside, given how many people and now companies are involved in OAS, it would be great to see some experienced individuals come and help with JSON Schema. Realistically there are 3 or 4 of us doing the work, none with experience of publishing IETF documents or defining internet standards... If OAS is going to be the future of APIs, and a huge core of that is JSON Schema, then the changes we make ought to be the right ones... - Any way this comment can be disseminated to those with experience?

**Comment by RobDolinMS** [comment]
@Relequestual I may be able to be of some assistance.  Want to email me and we can identify a time to chat about what might be needed?  <firstname><lastname><at>microsoft<dot>com

**Comment by Relequestual** [comment]
Thanks @RobDolinMS, I'll hopefully be able to email you later this week or next week. Super busy right now! =s
