### ISSUE TITLE
Explicitly define behavior for unhandled response codes and no default

### ISSUE THREAD

**Issue by carlansley** [OAI/OpenAPI-Specification#851]
This issue was raised by @shaxbee on our implementation carlansley/swagger2#8

Currently we assume an error if an unhandled response code is returned where no default ResponseObject is present.  The 2.0 spec is vague.. should any kind of response content should be allowed?  Maybe none?  It would be good to have some language in the 3.0 spec explicitly defining this.

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#responses-object

**Comment by darrelmiller** [comment]
Response codes in OpenAPI describe the details of status codes that may be returned.  In no way does it guarantee that other status codes will not be returned.  The nature of HTTP layered architecture allows any intermediary to short-circuit the response and return a status code.  Status codes such as 511, 502, 504, 203, 304 are explicitly intended to be returned by intermediary components that are not the origin server.
It would not make sense to require that people documenting their API also try and describe all status codes that might be returned from intermediary components.

**Comment by carlansley** [comment]
FWIW some context like this might be useful in the spec.

But that's not my particular concern.  We're validating the response against documentation at the origin server itself, before it's sent back on the wire.   If not we send back a 500.  The spec does speak to implementation/documentation expectations a little but doesn't flesh it out much:

> However, it is expected from the documentation to cover a successful operation response and any known errors.

Currently we treat something like a 409 where there's no ResponseObject and no default an error which seems reasonable but I'm not entirely sure that's what the spec intended.

**Comment by ePaul** [comment]
@carlansley I guess when implementing such a a server-side response validation one needs to question what would be more useful for a client: Safety that no other responses than the ones defined in the spec (and your 500 error?) can be returned, or having the specific status-codes for other error responses, allowing a client (or their developer) to find out a bit more about the problem.

I think converting 4** errors to 500 is not useful for the client.
On the other hand, logging any validation problems on the server side is certainly good, and helps to find bugs.

**Comment by carlansley** [comment]
Our attitude is 4** errors should be returned if the client request fails validation, 5** error if the server response fails validation.
