### ISSUE TITLE
api authentication example

### ISSUE THREAD

**Issue by d33pak-s1ngh** [OAI/OpenAPI-Specification#853]
how do i set user id and password into http header in swagger.json file
because my server need authentication and i am trying to test api using swagger editor.
so any one can tell me how do i set authentication(email,password).

**Comment by webron** [comment]
You have two ways of doing this:
1. Using a security scheme, specifically `apiKey` and setting it at the header - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securitySchemeObject
2. Using a regular header parameter across operation definitions.

If you have questions specific to the Swagger tooling, please use the [google group](https://groups.google.com/forum/#!forum/swagger-swaggersocket).
