### ISSUE TITLE
How to add meta data to a response of a list of objects? Docs unclear about that

### ISSUE THREAD

**Issue by linearregression** [OAI/OpenAPI-Specification#854]
I want the api response to return something like
{
"nextoken": "some string"
  "assets": [an array of asset]
}

I only want one nextoken value with a list of assets returned.  It is not clear in the docs how to do it.

spec of the following does not seem to work:
      responses:
        200:
          description: xxxxx
          schema:
            nextotken:
               type: string
            $ref: '#/definitions/assets'

definitions:
   asset:
         omitted .......
    assets:
             type: array
             $ref: '#/definition/asset'

**Comment by webron** [comment]
One way of describing it:

```yaml
responses:
  200:
    description: xxxxx
      schema:
        type: object
        properties:
          nextotken:
            type: string
          assets:
            $ref: '#/definitions/assets'
```

**Comment by DavidBiesack** [comment]
Hi, @linearregression . I suggest using the Swagger forum at http://swagger.io/forum/ to ask questions, rather than creating issues in the GitHub project. Thanks!

**Comment by webron** [comment]
I think it's okay to ask questions here if they are directly related to the spec... People are welcome to use Swagger's google group as well of course.
