### ISSUE TITLE
Extending - WAMP protocol

### ISSUE THREAD

**Issue by samson84** [OAI/OpenAPI-Specification#857]
Hi!

I would like to join to the Protocols and Payloads meta issue: Do you have any plans to support the [WAMP protocol](http://wamp-proto.org/)? 

> WAMP is an open standard WebSocket subprotocol that provides two application messaging patterns in one unified protocol: Remote Procedure Calls + Publish & Subscribe. 

It is basically meaning a support for the RPC + PUBSUB modell, and somewhere a WAMP enum in a some protocol field. 

The topic has been discussed in separate threads in the following parent issue:
parent issue #586

**Comment by samson84** [comment]
Oh, and these guys from WAMP trying to figure out something like this ofr 2 years: https://github.com/wamp-proto/wamp-proto/issues/61

**Comment by darrelmiller** [comment]
It is good to see someone making an effort to standardize an application protocol on top of WebSockets.  However, until WAMP makes it out of IETF draft status (especially expired draft status) I would be reluctant to spend any significant effort trying to change OpenAPI to support WAMP.  

It is challenging enough attempting to cover all the request/response HTTP use cases without trying to introduce full bi-directional support as well.  In many ways I think it would be easier to create a fork of the OpenAPI spec designed specifically for bi-directional messaging protocols and create specific tooling for that spec than try and have one spec address all distributed messaging architectures.

**Comment by samson84** [comment]
Yes, you have right this PUBSUB and RPC is not really related to REST and the main goal of the Open API initiative is improve the REST description language.

What do you think, what is needed to start working on this forked bi-directional part of the standard? Do you have a plan to open a working group based on that in the open API committee or it is not a priority at all? Can I help somehow?

**Comment by handrews** [comment]
This looks like it is out-of-scope for OpenAPI, but would likely be in-scope for AsyncAPI (they might already support it, I don't actually know).  I recommend checking with them!
