### ISSUE TITLE
wiki: broken link

### ISSUE THREAD

**Issue by activedecay** [OAI/OpenAPI-Specification#860]
[This wiki page](https://github.com/OAI/OpenAPI-Specification/wiki) contains a link to [swagger-play2 that doesn't exist](https://github.com/wordnik/swagger-core/tree/master/modules/swagger-play2).

https://github.com/swagger-api/swagger-play perhaps?

**Comment by RobDolinMS** [comment]
@activedecay Would you want to go ahead and submit the fix you propose?

/cc @webron

**Comment by webron** [comment]
The wiki needs to be completely reworked and is locked for external contributions. We should handle that after the 3.0.0 release.

**Comment by handrews** [comment]
The wiki seems to have been decommissioned in the intervening years.  Closing.
