### ISSUE TITLE
3.0 Release Timeline [Question]

### ISSUE THREAD

**Issue by jd-carroll** [OAI/OpenAPI-Specification#862]
Any idea when 3.0 will officially be released as the updated spec?  There are a couple of features we are anxious to start using (#646) and would like to see this land.

**Comment by darrelmiller** [comment]
ASAP.  I realize that is completely unhelpful.  However, it is an unfortunate reality when all the primary contributors have fulltime jobs and do this work on the side on a volunteer basis.

**Comment by jd-carroll** [comment]
Thanks @darrelmiller, how can I help with the process of moving things along?  Are issues appropriately updated with assignees so that I can work on un-assigned tickets?

**Comment by dilipkrish** [comment]
Im happy to help with the process as well /c @fehguy

**Comment by darrelmiller** [comment]
I've been out of the loop for a few weeks.  Keep your eyes open on the [blog](https://www.openapis.org/blog) for more details coming very soon.

**Comment by darrelmiller** [comment]
The implementers draft will be ready next week.
