### ISSUE TITLE
OpenAPI or swagger.json auto discovery

### ISSUE THREAD

**Issue by techtonik** [OAI/OpenAPI-Specification#864]
Is there any spec or convention on URL where one should place `swagger.json` (or whatever name it is agreed) so that public API of my site can be automatically discovered?

http://stackoverflow.com/questions/41660658/openapi-or-swagger-json-auto-discovery

**Comment by jdickey** [comment]
The OpenAPI Wiki [recommends](https://github.com/OAI/OpenAPI-Specification/wiki#server) using an `/api-docs` endpoint, at least for server APIs. I've seen several sites in the wild that use that, and it's our shop standard.

Hope that helps.

**Comment by techtonik** [comment]
@jdickey I don't like the convention, but it helps. =) The problem is that without reading the spec it is not clear what is the type of file. Because endpoint has no extension, server won't serve it as .JSON unless explicitly configured, which makes it less accessible for humans.

**Comment by webron** [comment]
Oh, no. Please ignore the wiki. The wiki is for a very very very old version of the spec. For 2.0 the standard is swagger.json, for 3.0 it changes to openapi.json.

**Comment by jdickey** [comment]
@webron Is that documented anywhere, ideally with a sample endpoint implementation?

**Comment by webron** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#file-structure

http://petstore.swagger.io/ with http://petstore.swagger.io/v2/swagger.json is a sample.

**Comment by jdickey** [comment]
@webron Thanks! Should have read the v2 docs more closely

**Comment by techtonik** [comment]
@webron maybe I am a bad English user, but I fail to see in spec where `openapi.json` should be located? What is the URL for scripts to discover API for my site?

**Comment by webron** [comment]
It doesn't say where it should be located. Again, it's more of a convention than it is a requirement. Normally it would be at the root of API host (or the context root).

**Comment by fehguy** [comment]
See here:

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#file-structure

**Comment by techtonik** [comment]
@fehguy it is still doesn't specify how to discover exact location of that file. It doesn't mention if it should be located at server root or somewhere else.

**Comment by techtonik** [comment]
I remember seeing some specification that used HTTP header to point to API location URL, but I can't find it anymore. It was from w3c and guys from Google, but I am not sure.
