### ISSUE TITLE
Have a parameter dependency to a specific schema defnition

### ISSUE THREAD

**Issue by levequej** [OAI/OpenAPI-Specification#867]
Hello,

I think it would be nice to have the possibility of  mapping  a definition depending on a parameter ( with an enum ) ? 

In my case it would avoid a lot of redundancy (much less stuff to write, and much clearer).

For example here is something in the spirit of what I'd like to do: The goal would be to have the proper schema definition mapped to the *stuffCategory* in that case

```yaml
paths:
  /{stuffCategory}/{stuffId}:
    get:
      description: "get stuff depending on its category "
      operationId: getHostInGroup
      responses:
        '200':
          description: OK
      parameters:
        - $ref: "#/parameters/stuffIdParam"
        - in: path
          name: groupName
          description: Nom du groupe
          required: true
          type: string
          enum:
           - categoryOne
           - categoryTwo
           - categoryThree
```

Thanks,

Julien

**Comment by atsu85** [comment]
That is exactly what i stumbled upon (referencing type definition from request parameter) - i'm sure if there are any other valid use-cases for parameter type references, but referencing enum definition is certainly the use-case i'm missing a lot!

At the moment it is allowed to reference enum definition for example from another type definition property (for example request/response body having property that is referencing enum).
Does someone know why currently it isn't allowed to reference enums from parameters?

**Comment by handrews** [comment]
This sort of thing is being addressed in OAS 4 Moonwalk as part of the [operation signatures](https://www.openapis.org/blog/2023/12/06/openapi-moonwalk-2024) principle, which proposes incorporating everything (paths, parameters, content schemas, etc.) into what constitutes a distinct operation.  Please take a look at the [initial (and already a bit outdated) proposal](https://github.com/OAI/sig-moonwalk) and join the [discussions](https://github.com/OAI/sig-moonwalk/discussions) in that repository if you are still interested!
