### ISSUE TITLE
Multiple operations under one HTTP method

### ISSUE THREAD

**Issue by tarunendra** [OAI/OpenAPI-Specification#868]
Hi, Swagger doesn't allow to create multiple operations under one HTTP method. 

How to handle use case where you need to create two operations like createCustomer and updateCustomer and both are suppose to use POST HTTP method.

**Comment by webron** [comment]
Well, the spec is opinionated, and we do suggest taking advantage of the HTTP verbs. So, POST for create, PUT/PATCH for update.

**Comment by tarunendra** [comment]
Thanks..
