### ISSUE TITLE
Fix $ref locations in 3.0 spec

### ISSUE THREAD

**Issue by curtisr7** [OAI/OpenAPI-Specification#870]
Numerous places in the 3.0 spec has `$ref: '#/definitions/[n]'`, but shouldn't they be referencing `$ref: '#/components/definitions/[n]'`?

If my understanding is correct I can open a PR?

**Comment by fehguy** [comment]
that is correct.  we are considering that as a secondary documentation step since there are major changes coming in the current one, and markdown isn't great for merging.  But do feel free to make that change in a PR.

**Comment by darrelmiller** [comment]
I believe all of these issues have now been resolved.
