### ISSUE TITLE
global "consumes" flag should be ignored when method is GET or DELETE

### ISSUE THREAD

**Issue by JLLeitschuh** [OAI/OpenAPI-Specification#873]
The logic I've laid out can be found in the swagger codegen issue:

https://github.com/swagger-api/swagger-codegen/issues/4668

Similarly: https://github.com/swagger-api/swagger-ui/issues/2408#issuecomment-248198223

TL;DR: GET and DELETE shouldn't have body's so requiring a `Content-Type` header to be sent makes no sense any may (depending on how you read them) go against some specs.

**Comment by JLLeitschuh** [comment]
I think this is a duplicate of: https://github.com/OAI/OpenAPI-Specification/issues/581

**Comment by darrelmiller** [comment]
There is no consumes/produces in V3 and the spec explicitly instructs consumers to ignore request bodies where the HTTP spec says the body has no semantic meaning.
