### ISSUE TITLE
3.0.md Parameter Object typo

### ISSUE THREAD

**Issue by curtisr7** [OAI/OpenAPI-Specification#874]
The parameter object definition states that there are four possible parameter types[1], but the `in` field states that there are five types[2].

I *believe* that the bulleted list should include formData.

Another nit. Should the bulleted types[1] be lower case rather than upper cased? ie: `path`, `query`, etc, etc?

[1] https://github.com/OAI/OpenAPI-Specification/blame/OpenAPI.next/versions/3.0.md#L734
[2] https://github.com/OAI/OpenAPI-Specification/blame/OpenAPI.next/versions/3.0.md#L745

**Comment by darrelmiller** [comment]
The issues with the parameter types have been fixed.  FormData is now handled with a content object, schema object and encoding object.
