### ISSUE TITLE
Consider releases and/or version tags 

### ISSUE THREAD

**Issue by dmolesUC** [OAI/OpenAPI-Specification#875]
It seems like right now there are two meaningful branches in this repo: `master` (latest stable) and `OpenAPI.next` (under development). The `versions` directory holds old versions of the spec, but there's no long-term stable way to link to them -- if in the future, the `versions` directory is reorganized to, say, something like this --

```
versions
├── 1.x
│   └── 1.2.md
└── 2.x
    ├── 2.0.md
    └── 2.1.md
```

then any links to `versions/2.0.md` would break. I do like the idea of including all old versions in the main repo, but it would be nice if `master` was tagged `2.0`, so `/blob/2.0/versions/2.0.md` would work as a canonical link.

**Comment by darrelmiller** [comment]
I agree we need some stable URLs for the specification.  It is essential to be able to do media type registration.  However, I don't think using GitHub links are going to be good enough.  I think we will either find some URL under OpenApis.org or within the Linux Foundation.

**Comment by MikeRalphson** [comment]
We have formatted versions of the spec available at https://spec.openapis.org

**Comment by dmolesUC** [comment]
@MikeRalphson Are the links to particular versions documented anywhere? (I mean, I can get to 3.0.0–3.0.3 by editing the URL for 3.1.0 that's linked from https://spec.openapis.org/, but that's not quite the same thing.)

**Comment by MikeRalphson** [comment]
@dmolesUC I'm not quite sure what you mean by "documented"? Each published (non-RC) version of the spec. from 2.0 has a rendered version available, and as you say, the URLs can be deduced fairly easily. Do you think this itself should be documented or should there be a landing page or a drop-down on openapis.org, or ... ?

**Comment by dmolesUC** [comment]
@MikeRalphson Up to you, but if it was me I'd probably have the version history and release notes on the main site, not just in GitHub. That said, it looks like since 3.0.0-rc0 (shortly after I originally filed this ticket) the versions have all been tagged as releases, so it's not that big a deal. If someone wanted to retroactively tag 1.2 and 2.0 that would be nice, but it'd be an archaeology project now to identify the right revision and probably not that important as those versions fall farther and farther out of use.
