### ISSUE TITLE
[Proposal] Raml-like Type Expressions & Union Type in 3.0?

### ISSUE THREAD

**Issue by IGZfranciscoserrano** [OAI/OpenAPI-Specification#876]
Hi,
Recently I have been working on a project with Raml specs, and their type expressions system is really powerful, as is the union type. I was wondering if there is any plan to include something similar on next OpenApi release.

https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#type-expressions
https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#union-type

**Comment by RobDolinMS** [comment]
Thanks for raising this issue @IGZfranciscoserrano.  

You can see the latest draft of the OpenAPI Spec v3 at: https://github.com/OAI/OpenAPI-Specification/edit/OpenAPI.next/versions/3.0.md

Does it have what you're looking for?

**Comment by LasneF** [comment]
@handrews  @MikeRalphson  ,  this ticket should be closed as addressed in OAS 3.0 / 3.1 with the usage of JSON schema specification and usage of anyOf / allOf and co

**Comment by lornajane** [comment]
Thanks @LasneF , I can do that!
