### ISSUE TITLE
3.0.md Examples Object bug

### ISSUE THREAD

**Issue by curtisr7** [OAI/OpenAPI-Specification#877]
The `Examples object` is listed twice.

The updated section also mentions a `produces attribute`, but that doesn't exist on a response payload.

**Comment by curtisr7** [comment]
I also noticed that the `content` object has both `examples` and `example` fields?  Is that intended?

**Comment by fehguy** [comment]
Yes that was intentional

**Comment by handrews** [comment]
If the `schema` object is a JSON Schema, note that `examples` (plural only) becomes an official keyword in soon-to-be-published Draft 06 (I know y'all aren't moving to that any time soon if ever, but FYI)

**Comment by webron** [comment]
Thanks for the update, @handrews.
