### ISSUE TITLE
Support for request body with arbitrary Content-Type (OpenAPI.Next)

### ISSUE THREAD

**Issue by lucafavatella** [OAI/OpenAPI-Specification#882]
When attempting to describe a [PUT request](https://github.com/OAI/OpenAPI-Specification/blob/17a389a2e3150c3b10a105e461b73666b2e560e0/versions/3.0.md#path-item-object) with arbitrary request body and Content-Type (think about a file upload server where you can choose the Content-Type), a "default" catch-all Content-Type needs to be added to [content object](https://github.com/OAI/OpenAPI-Specification/blob/17a389a2e3150c3b10a105e461b73666b2e560e0/versions/3.0.md#contentObject).

I understand that request with arbitrary body and Content-Type cannot be specified in OpenAPI 2.0 (`file` type has restrictions on Content-Type).

**Comment by webron** [comment]
This has been resolved in #878.

**Comment by lucafavatella** [comment]
I see an example of request body in https://github.com/OAI/OpenAPI-Specification/blob/17a389a2e3150c3b10a105e461b73666b2e560e0/versions/3.0.md#requestBodyObject has a `"*"` section that looks what I wanted. Thanks.

```
{
  "description": "user to add to the system",
  "content" : {
    "application/json" : {
      "schema": {
          "$ref": "#/definitions/User"
        },
      "examples": [
        { "$ref": 'http://foo.bar#/examples/address-example.json'}
      ]
    },
...
    "*": {
      "example": {
        $ref: "http://foo.bar#/examples/address-example.whatever"
      }
  }
}
```

**Comment by webron** [comment]
The example should actually be `*/*` but, the idea is the same.
