### ISSUE TITLE
3.0md callback responses?

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#896]
The [Operation object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#operationObject) has a non-camelCase field labeled `callback responses` can we get a better example of this? Is this a typo and should be `callbackResponses`? Is the following right?

```
callbackResponses:
  myWebhook:
    '$request.url':
      post:
        body:
          name: postResponse
          schema:
            $ref: '#/definitions/SomePayload'
        responses:
          200:
            description: webhook successfully processed an no retries will be performed
```

**Comment by darrelmiller** [comment]
Thanks for pointing that out.  I'm going to change that to just say `callbacks`.  The callback is an operation object that contains both outgoing request and response, so saying "callback responses" is just confusing.

**Comment by willdady** [comment]
Great. Thanks for the quick response. I'm working on an implementation and was a bit stumped when I came across that.

**Comment by darrelmiller** [comment]
If you are implementing, you probably want to check out the PR I submitted today https://github.com/OAI/OpenAPI-Specification/pull/891  that attempts to define the variable syntax of the callback key.  Hopefully, that will get finalized tomorrow.

**Comment by darrelmiller** [comment]
Changes to name of property are now included in PR.
