### ISSUE TITLE
Why updatePet operation does not have 200 as one of responses?

### ISSUE THREAD

**Issue by chuchuva** [OAI/OpenAPI-Specification#898]
From http://petstore.swagger.io/v2/swagger.json :

            "put": {
                "tags": [
                    "pet"
                ],
                "summary": "Update an existing pet",
                "description": "",
                "operationId": "updatePet",
                "consumes": [
                    "application/json",
                    "application/xml"
                ],
                "produces": [
                    "application/xml",
                    "application/json"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "body",
                        "description": "Pet object that needs to be added to the store",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Pet"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Invalid ID supplied"
                    },
                    "404": {
                        "description": "Pet not found"
                    },
                    "405": {
                        "description": "Validation exception"
                    }
                },

You can see that `responses` array includes values for 400, 404 and 405 only. Why 200 is not included? This breaks C# auto-generated code, see https://github.com/Azure/autorest/issues/1859

**Comment by darrelmiller** [comment]
It probably should, in fact in the V3 spec, it explicitly states that the successful response SHOULD be included.  However, it isn't a MUST and AutoREST shouldn't assume that it will be there.

**Comment by webron** [comment]
As @darrelmiller mentioned, it's a sample, not a rule. If you feel it should be changed, please open a ticket on https://github.com/swagger-api/swagger-samples. This is not the right place for this ticket.

**Comment by amarzavery** [comment]
@webron - This is straight from the V2 spec, and it is a rule as per the specification.

As per the [Open API Spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object)
> The Responses Object `MUST` contain at least one response code, and it `SHOULD` be the response for a **successful operation call**.

However, the `UpdatePet` operation in [Petstore swagger](http://petstore.swagger.io/v2/swagger.json) specifies only the negative response codes(400, 404, 405), which is grossly incorrect.

Petstore being the most common swagger that people use for onboarding, should definitely abide by the specification.

**Comment by webron** [comment]
It is abiding. SHOULD is not MUST. Regardless, this is not the right place for this ticket.
