### ISSUE TITLE
Can a json schema have nested $ref?

### ISSUE THREAD

**Issue by sanjay-ng** [OAI/OpenAPI-Specification#900]
Hi, I've a json schemas which has nested $ref references. Please see this example for reference: https://github.com/whitlockjc/json-refs/issues/105#issuecomment-279311750

Does swagger spec allow/support this kind of situation?

**Comment by darrelmiller** [comment]
Yes.  You can see an example of it in one of the test cases https://github.com/OAI/OpenAPI-Specification/blob/master/fixtures/v2.0/json/models/modelWithComposition.json

**Comment by sanjay-ng** [comment]
Thank you for quick reply!

The example which you've shared **does not have a nested $ref**. Please see my example **it has more than 2 levels of nested $ref using url**. Try using it on swagger-editor and see what happens, then you'll know what I'm referring too.

**Comment by webron** [comment]
@sanjay-ng - that's a tooling problem that should be handled by the respective project. There's no limitation on the depth when $ref's are used.
