### ISSUE TITLE
Swagger Contract Model fields are displayed as requestModel.<fields> 

### ISSUE THREAD

**Issue by GaneshMeenakshisundaram** [OAI/OpenAPI-Specification#904]
The Contract Model fields getting displayed as requestModel.<fieldname>. Why this appears?

![swagger contract model issues](https://cloud.githubusercontent.com/assets/14163306/23227325/8a1e1ae6-f906-11e6-8367-55bdc57576ed.jpg)

**Comment by fehguy** [comment]
Hi, looks like this is an issue for swagger-ui or whatever tooling you use to generate your integration.  Please open your issue there--this repo is just for the specification.
