### ISSUE TITLE
3.0.md Content Type broken links?

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#906]
For [Content Type](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#content-type-object) the `examples` and `example` links appear broken. Currently `example` links to `#exampleObject` which is non-existent. Should this link to `#examples-object`? It seems there is no such thing as Example Object.

Also, shouldn't the `examples` field be denoted as `[Example Object]`, not `Examples Array`? 

Or is it just the case that neither `example` or `examples` have a defined structure? If that's the case maye the _type_ of these fields should simply be `[*]` and `*` respectively?

**Comment by webron** [comment]
Thanks for bringing it up. We've just kicked off the process of cleaning out such errors in the docs. Having users point those out, saves us time ;)

/cc @RobDolinMS

**Comment by darrelmiller** [comment]
@willdady Let me know if this PR fixes all of the issues you see https://github.com/OAI/OpenAPI-Specification/pull/907

**Comment by willdady** [comment]
@darrelmiller Yep. Looks right to me. Thanks :)
