### ISSUE TITLE
openapis.org error 403

### ISSUE THREAD

**Issue by GhostRussia** [OAI/OpenAPI-Specification#908]
![2017-02-23 09 15 32](https://cloud.githubusercontent.com/assets/12181586/23239115/a5e6960c-f9a8-11e6-85c7-ec1f8d6ce914.png)

**Comment by webron** [comment]
Just checked and it loads fine. Can you try again? Maybe it was a momentary internet burp.

**Comment by GhostRussia** [comment]
Checked, it has long been 403 for me, but it works through a proxy. maybe you block my subnet? I have a 159.255.*.* IP

**Comment by RobDolinMS** [comment]
I'm also not able to reproduce this issue.  https://www.openapis.org/ loads fine for me in Edge on Windows 10 from Seattle, WA, USA.

**Comment by RobDolinMS** [comment]
I've seen other groups use a separate GitHub repository to track issues with their website.  

What do other folks think about moving this to a new repo (ex: GitHub.com/OAI/OpenAPIs.org-website)

**Comment by GhostRussia** [comment]
https://www.host-tracker.com/InstantCheck/ResultComplete/98f7a26f-b7fa-e611-80c2-0003ff73517a

Russia and Ukraine gets a 403 error

**Comment by GhostRussia** [comment]
for Russian server ip is 151.101.13.5
If I register as an ip 151.101.85.5(I took ip on the link from the test site availability) for the site, then it works. I use google dns.

```
nslookup www.openapis.org
Server:		8.8.4.4
Address:	8.8.4.4#53

Non-authoritative answer:
www.openapis.org	canonical name = n.ssl.fastly.net.
Name:	n.ssl.fastly.net
Address: 151.101.13.5
```

**Comment by fehguy** [comment]
Folks, I'm forwarding this to the Linux Foundation to look into.  They run that server.

**Comment by GhostRussia** [comment]
Now the site has started to work for me, but when checking the website https://www.host-tracker.com/ site, still have 403 errors

**Comment by fehguy** [comment]
I will post back after the LF team looks at this.  Thank you for reporting it, @GhostRussia

**Comment by fehguy** [comment]
@GhostRussia this should be fixed now--please confirm when you can.

**Comment by GhostRussia** [comment]
Now the site works, thanks.
