### ISSUE TITLE
Same path + same http-method + different parameters = possible?

### ISSUE THREAD

**Issue by hlubovac** [OAI/OpenAPI-Specification#909]
Hello -

JSON makes this impossible because swagger document defines them to be properties (as opposed to array).

I'm talking about `paths > "/some-path" > "http-method"`. I have 2 to describe, ideally at the same path, but with different request parameters. I see no reason for this restriction, semantically. It's be better if definitions, such as this one, are defined as arrays [of items that have a property that defines http-method].

**Is there another way for me to make this work, while keeping the same path and http-verb (again, different arguments; in particular `formData`)?**

While at it, why also not make it possible to specify a custom http-method? I understand that custom http verbs are legal (allowed), so why restrict to what's normally used? Perhaps we have special needs and we're anal about cosmetics.

Thanks!

**Comment by fehguy** [comment]
I think you may be missing background on this project.  Read the main page for the goals and if it's not inside your constraints then it may not be right for you.

Constraints in the specification have been pretty darn well thought out.  There are tickets explaining just about all of them.  Read them, then you'll have the info you need to see if it makes sense for you or not.

**Comment by hlubovac** [comment]
I'm not trying to criticize. I think that I understand the purpose of the project, but the fact is that people branch processing at same url-paths based on request arguments.

I, in particular, am trying to present two OAuth2 endpoints, both POST, both ideally at the same path, but with different arguments that appear as form-data. So, they are not exactly REST endpoints in my realm, but they are a part of the service. Sure, I can separate them at 2 different paths, as there's no other way around it. I wasn't able to find a way to craft this into the swagger-document in such a way that UI presents it somehow; I'm following https://tools.ietf.org/html/rfc6749, and I only implemented "password" and "refresh_token" handlings (if you're familiar).

All I tried to say was that it would take relatively very little (attributes becoming arrays) for this and all similar cases to generally work (of course with cooperation of consuming media, such as current UI), and that this restriction wasn't entirely necessary.

Thanks.

**Comment by fehguy** [comment]
Hi, no problem.  I'm just trying to say that it _is much more involved_ than just saying "pass an array" and that constraint has far-reaching effects across the tooling.  There is discussion in the issues as to why it's not supported.

But I do suggest you read the 3.0 spec, which will be hitting RC0 next week.  I believe it provides a mechanism--different from what you said--but acceptable for your goal.  Details are [here](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md).

**Comment by hlubovac** [comment]
Thank you.
