### ISSUE TITLE
3.0.md inconsistent type naming + broken links

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#920]
Found a few inconsistencies (or I may just be being pedantic):

[Server Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#server-object) has a field `templates` of type `Templates Object`, clicking this takes you to a section named **Host Templates Object** not **Templates Object**. Neither Host Templates Object or Templates Object is listed in the TOC.

Similarly, [Host Templates Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#host-templates-object) has a field `[variable name]` of type `Host Template Parameter`. Clicking this takes you to a section named **Host Template** not **Host Template Parameter**. Neither Host Template or Host Template Parameter is listed in the TOC.

All types under the [Components Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#components-object) have broken links. Looks like the problem is they're linking to camelCased anchors when they should be snake-case.

**Comment by webron** [comment]
All fixed, thanks for the feedback!
