### ISSUE TITLE
Two references to 'parameterContent' seem incomplete /  left-over ?

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#954]
> When passing complex objects in the x-www-form-urlencoded content type, the default serialization strategy of such properties is described in the parameterContent section as form.

> The Content-Type to use for encoding a specific property. See (#parameterContent) for details on the style property.

Also what looks like another broken link:

> The following shows how multiple servers can be described, for example, at the OpenAPI Object's servers(#oasServers):

**Comment by webron** [comment]
Fixed the `servers` link. @MikeRalphson - I'm not seeing the #parameterContent instance - might have changed with other changes. Please reopen if you can still spot it.

**Comment by MikeRalphson** [comment]
The wording 

> When passing complex objects in the x-www-form-urlencoded content type, the default serialization strategy of such properties is described in the parameterContent section as form.

Still seems to be present. Should this be changed to 

> [parameterObject]() `style` property

?

**Comment by webron** [comment]
Aha, it took me a while to track it down and follow the original intent. I think some of the wording around that needs to be improved. We'll reopen the ticket for now and see if I can get something to improve that.

**Comment by RobDolinMS** [comment]
TDC: @webron will review and either close, add a comment, or draft a PR.

**Comment by webron** [comment]
Resolved by #1209.
