### ISSUE TITLE
List of all OpenAPI 3.0.0-RC0 tools/services?

### ISSUE THREAD

**Issue by bootstraponline** [OAI/OpenAPI-Specification#955]
I think it'd be helpful to have a list of everyone supporting OpenAPI 3. Right now it's difficult for end users to understand what options are available.

**Comment by darrelmiller** [comment]
At the moment, no-one is supporting OpenAPI 3.  The point of this RC0 is to provide a stable base upon which people can build tooling to support it.  We are in the process of creating a list of implementations that are working to support V3.

**Comment by bootstraponline** [comment]
> We are in the process of creating a list of implementations that are working to support V3.

Is this going to be published on openapis.org?

**Comment by darrelmiller** [comment]
Either there or in the wiki of this repo.

**Comment by bootstraponline** [comment]
I like the wiki idea, especially if people can edit it so new entries don't get blocked waiting for approval.

**Comment by webron** [comment]
In my experience, opening the wiki for edits ends up butchering the wiki pages. I wish github had a PR process for that as well.

**Comment by bootstraponline** [comment]
How about a new repo for tools/services which is using gh-pages & accepts PRs? Then as PRs are merged, the website listing will auto update.

**Comment by bootstraponline** [comment]
Also as a counter example, the jekyll wiki is doing fine with open access rights:

- https://github.com/jekyll/jekyll/wiki/Themes

**Comment by webron** [comment]
Thanks. We're considering the options for this. Our first and immediate goal was to push the draft out, we'll tackle that (and much more) in the upcoming weeks.

**Comment by willdady** [comment]
Another option is creating a gist. People could leave a comment with a link to their project which someone would then need to review and add to the gist.

**Comment by brendo** [comment]
My team will be working on a renderer that supports Swagger V2 and the Open API spec. We have a vested interest in this as our current API cannot be accurately described using just Swagger V2 as we use parts of the JSON Schema spec that are not supported.

We'll be digging through the draft shortly!

**Comment by MikeRalphson** [comment]
For now, please feel free to issue pull requests to an unofficial list [here](https://github.com/Mermade/awesome-openapi3)

**Comment by philsturgeon** [comment]
Where is the link to the official list of implementations? There is a link to a implementations submission form, but no link to the actual implementations >.<

<img width="809" alt="Screen Shot 2019-06-11 at 09 57 26" src="https://user-images.githubusercontent.com/67381/59253864-66f20780-8c2f-11e9-9aa5-69f90e4716d7.png">

When we get that link done, we can probably close this issue. Mike hasa list, https://openapi.tools has a list, and there's an official one in hiding.

**Comment by darrelmiller** [comment]
It's not hiding.... it is right here https://github.com/OAI/OpenAPI-Specification/blob/master/IMPLEMENTATIONS.md   I know it is discoverable because we have at least 10 PRs to it that need attending to.

**Comment by philsturgeon** [comment]
Hiding for end users who aren’t combing through the repo. :) 

--
Phil Sturgeon
@philsturgeon

**Comment by MikeRalphson** [comment]
Thanks all, we're now in the process of moving from `IMPLEMENTATIONS.md` to https://tools.openapis.org
