### ISSUE TITLE
3.0.md links to LinkObject are broken

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#956]
As per the title. I had a quick look but can't figure out why it's not working.

`#linksObject` ->  `#links-object` Works fine.
`#linkObject` ->  `#link-object` Doesn't work.

**Comment by ePaul** [comment]
@willdady Thanks for noting. I opened pull request #966 to fix this.

**Comment by fehguy** [comment]
I think this can be closed
