### ISSUE TITLE
How can I represent java Generic type in swagger.yml

### ISSUE THREAD

**Issue by howshit** [OAI/OpenAPI-Specification#957]
Hi, I have multiple APIs returning data with same structure, just like examples underneath:
```
  CatResponse:
    type: object
    properties:
      counts:
        type: integer
      value:
        type: array
        items:
          $ref: '#/definitions/Cat'  
  DogResponse:
    type: object
    properties:
      counts:
        type: integer
      value:
        type: array
        items:
          $ref: '#/definitions/Dog' 
```
How can I represent them in swagger so that I can generate` EntityResponse<T>`, when I refer to them, I just replace T with Cat or Dog.

So that I just need to define one response object.

Thx.

**Comment by webron** [comment]
There's no support for templating of responses (or message wrappers).

**Comment by howshit** [comment]
You mean that no definition can generate Java generic type like EntityResponse<T>,
and thus I have to define ten response objects if I have ten kinds of animal entities.

**Comment by webron** [comment]
How it translates to code in a specific language is out of scope. You can use composition and inheritance, but not templating.

**Comment by macarlet** [comment]
Maybe this thread can be useful? Take a look at the last message
https://github.com/swagger-api/swagger-core/issues/498

**Comment by handrews** [comment]
Generics/templates are supported in OAS 3.1 by [using dynamic references](https://json-schema.org/blog/posts/dynamicref-and-generics).
