### ISSUE TITLE
Not correctly generating output link in Internet Explorer 11

### ISSUE THREAD

**Issue by anuar-zhaletov** [OAI/OpenAPI-Specification#958]
In Internet Explorer 11, when clicking on "Try it out", as response generated link. When you click on it, you can download output file. But in Internet Explorer 11 link generated not correctly. Link generated with relative path, not full in Chrome working correctly 
my question is.... is all Swagger functionality tested in Internet Explorer 11? Or it counted on browsers like Chrome?
Can you fix it, please. Because we using it in our project. 

Example: blob:http://some.site.com/81923-ab1-12123     is correct link, generated in Google Chrome
blob:81923-ab1-12123     is incorrect link, generated in Internet Explorer 11.

**Comment by darrelmiller** [comment]
I suspect this issue should be filed in the [Swagger-UI](https://github.com/swagger-api/swagger-ui) repo.  This repo is for just the OpenAPI specification.

**Comment by webron** [comment]
It's either that or swagger-editor. Please open the ticket on the relevant project.
