### ISSUE TITLE
3.0.0-rc0 ServerObject has no required fields?

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#962]
The `url` field for [ServerObject](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#serverObject) isn't explicitly marked as required? Shouldn't it be? Presumably all servers have URL's and the `variables` field is dependant on it being defined. You wouldn't (couldn't) define `variables` but not `url`.

**Comment by ePaul** [comment]
Good observation. I think `url` should be required.
