### ISSUE TITLE
3.0.0-rc0 Request Body Object has no required fields?

### ISSUE THREAD

**Issue by willdady** [OAI/OpenAPI-Specification#963]
Similar to #962, [Request Body Object](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#request-body-object) has no required fields. Shouldn't `content` be required?

**Comment by ePaul** [comment]
Hmm, interesting question. What could be the meaning of a Request body object without a content field?

* Clients can send anything, we don't document what is done with it?
    * I guess this should be done via a `*/*` entry in the Contend object, with documentation.
* Clients should not send anything (i.e. no/empty body)?
    * I guess in this case we omit the requestBody object?

So it seems that making it required is a good idea.
