### ISSUE TITLE
Consider renaming oAuth Flows Object from 'flow' to 'flows'

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#967]
This is probably a non-starter at this stage, but it is one of the rare examples in the specification of a singular noun being used to describe a collection. Changing this would draw attention to the fact this area of the specification has changed. See also #953 re: example/examples.

**Comment by ePaul** [comment]
I think now (before the final release of 3.0) is the perfect time to do this change.

**Comment by webron** [comment]
It looks like an oversight and a remnant from the previous version. We'll consider it.
