### ISSUE TITLE
headers under Encoding Property needs clarification

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#987]
The type and description are unclear, and there are no examples.

**Comment by RobDolinMS** [comment]
TDC: @fehguy will make something awesome!

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#encodingPropertyObject

**Comment by timburks** [comment]
As pointed out to me by @tfesenko, there seems to be an extra level of nesting in the definition of the "headers" property. Currently it is `Map[string, Headers Object]`. 

But "Headers Object" is also (essentially) a map. Should this property instead have type `Map[string, Header Object]` or simply `Headers Object`?

**Comment by webron** [comment]
@timburks that's on me to fix, but yes (it's on my todo list with #1115).

**Comment by webron** [comment]
Done!
