### ISSUE TITLE
Consider adding allowReserved to Encoding Property Object

### ISSUE THREAD

**Issue by webron** [OAI/OpenAPI-Specification#988]
We say that `x-www-form-urlencoded` follows what's allowed for `query` parameters, in terms of `style` and `explode`. It might make sense to add `allowReserved` to the mix.

**Comment by darrelmiller** [comment]
If you want a form that has a URL as a parameter that is not percent-encoded then yes `allowReserved` would be necessary.  It might be interesting to see what browsers do with a URL in a form parameter.
