### ISSUE TITLE
[3.0.0-RC0] parameters and headers with `schema` OR `content` property

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#996]
As per Twitter conversation with @webron 

There are no examples of parameters or headers with `content` properties.

Is the intention that a parameter in `query`, `path`, `header` or `cookie` could have a `content` property with one or more content-types which are *acceptable*, i.e. blobs of xml or json passed as query parameters? Obviously a parameter in one of the those locations does not have an **explicit** `Content-Type` - the server would need to detect the type and act accordingly.

Does it make sense to allow arbitrary content-types for `path` parameters? For `cookie` parameters, is the content-type applicable to the **value** (considering that `,` and `;` characters are not allowed) rather than the cookie as a whole, etc?

Some clarification may also be needed that either `schema` OR `content` MUST be provided for parameters and headers. The properties should probably be marked 'Required:' in the field tables.

**Comment by darrelmiller** [comment]
The general feeling is that using Content objects in parameters is one of those edge cases that we are reluctantly supporting.  If someone can come up with a sane use-case that we can base an example on, that would be great.
I think we need to find a way of only allowing a single media type objects for content objects used in parameters.  There is no way of identifying the media type in the message and starting to sniff the values just seems fraught with problems.

I think the concerns about serializing complex objects in the path are equally an issue in query parameters and headers.  If implementation experience shows that there are too many problems, we may have to reconsider this support before the final version.

I will add text to clarify what properties are required in a parameter.

**Comment by RobDolinMS** [comment]
TDC: Language around multi-part usage need clarifying
TDC: We DO want to allow multi-part responses (ex: Image + metadata)
TDC: @webron might be able to take this, but it would not get done by next TDC ConCall on Fri, 5/12
TDC: @darrelmiller has offered to review

**Comment by webron** [comment]
Fixed by #1212.
