### ISSUE TITLE
Consider adding `deprecated` property to server object

### ISSUE THREAD

**Issue by MikeRalphson** [OAI/OpenAPI-Specification#997]
Have scanned the issues but not found any other discussion. Have had a real-life example:

```xml
  <n:deprecations>
    <n:deprecated name="nitro.api.bbci.co.uk" type="host" deprecated_since="2015-12-24" replaced_by="programmes.api.bbc.com" replacement_type="host"/>
    <n:deprecated name="data.bbc.co.uk" type="host" deprecated_since="2015-12-24" replaced_by="programmes.api.bbc.com" replacement_type="host"/>
    <n:deprecated name="d.bbc.co.uk" type="host" deprecated_since="2015-12-24" replaced_by="programmes.api.bbc.com" replacement_type="host"/>
  </n:deprecations>
```

**Comment by RobDolinMS** [comment]
@webron Since you labeled this 3.0.0-RC1, I'm guessing you agree with including this for 3.0.0.  

Would you or @MikeRalphson want to submit a PR?

**Comment by webron** [comment]
@RobDolinMS I marked tickets as RC1 for points of discussion. They're not all automatically getting in.

I'd argue that if a server is deprecated, it should just be removed. I don't see that at the same level of transition of an operation/parameter/model property. Maybe I don't understand the actual use for it.

Given the schedule, it's unlikely to get into RC1, as we'd need to discus it.

**Comment by MikeRalphson** [comment]
No other feedback on this issue. I guess I can live without it!
